Repository Samsung/ONE, pull requests merged in 2020-10, with the labels that each got.

#4474 [res] Introduce FullyConnected_005
  res/TensorFlowLiteRecipes/FullyConnected_005/test.recipe
Labels: PR/ready for review

#4476 [luci] Revise SparsityParam
  compiler/luci/import/src/CircleReader.cpp
  compiler/luci/lang/include/luci/IR/SparsityParam.h
Labels: PR/ready for review

#4483 [luci] Export Sparsity
  compiler/luci/export/src/CircleExporterUtils.cpp
  compiler/luci/export/src/CircleExporterUtils.h
  compiler/luci/export/src/CircleTensorExporter.cpp
Labels: PR/ready for review

#4475 [luci] Add sparsify utils
  compiler/luci/pass/src/Sparsifier.cpp
  compiler/luci/pass/src/Sparsifier.h
Labels: PR/ready for review

#4485 [infra/package] Divide compiler test package
  infra/scripts/docker_build_nncc.sh
Labels: PR/ready for review

#4488 [one-cmds] Create python symbolic link
  compiler/one-cmds/one-prepare-venv
Labels: PR/ready for review

#4486 [luci] Introduce SparsifyTensorPass
  compiler/luci/pass/include/luci/CircleOptimizer.h
  compiler/luci/pass/include/luci/Pass/SparsifyTensorPass.h
  compiler/luci/pass/src/CircleOptimizer.cpp
  compiler/luci/pass/src/SparsifyTensorPass.cpp
Labels: PR/ready for review

#4497 [release_tool] fix minor bug
  tools/release_tool/git_release.sh
Labels: PR/ready for review

#4489 [onert] Move constant input checking
  runtime/onert/backend/acl_cl/KernelGenerator.cc
  runtime/onert/backend/acl_neon/KernelGenerator.cc
  runtime/onert/core/src/compiler/OperationValidator.cc
  runtime/onert/core/src/compiler/OperationValidator.h
  runtime/onert/core/src/compiler/ShapeValidator.cc
Labels: PR/ready for review

#4499 [circle2circle] Add sparsify-related option
  compiler/circle2circle/src/Circle2Circle.cpp
Labels: PR/ready for review

#4507 [onert] Move data type checking
  runtime/onert/core/src/compiler/OperationValidator.cc
  runtime/onert/core/src/compiler/OperationValidator.h
  runtime/onert/core/src/compiler/ShapeValidator.cc
Labels: PR/ready for review

#4521 [onert] Introduces ExternalContext into controlflow backend
  runtime/onert/core/src/backend/controlflow/BackendContext.h
  runtime/onert/core/src/backend/controlflow/ExternalContext.h
Labels: PR/ready for review, area/onert

#4438 [onert] Introduces a helper function ShapeLoop
  runtime/onert/core/include/util/Utils.h
  runtime/onert/core/src/exec/IPermuteFunction.h
Labels: PR/ready for review, area/onert

#4539 [luci-interpreter] Add support of S16 type to `dequantizeTensorData` helper
  compiler/luci-interpreter/src/kernels/TestUtils.cpp
Labels: PR/ready for review

#4535 [onert] Fix when an operand that is input & output
  runtime/onert/core/src/backend/controlflow/DynamicTensorManager.cc
  runtime/onert/core/src/backend/cpu_common/MemoryManager.cc
  runtime/onert/core/src/compiler/Compiler.cc
  runtime/onert/core/src/compiler/pass/OddOutputPass.cc
  runtime/onert/core/src/compiler/pass/OddOutputPass.h
  runtime/onert/core/src/compiler/pass/PermutationEliminationPass.cc
  tests/nnfw_api/src/GenModelTests.cc
Labels: Urgent

#4512 [onert] Fix a bug with consecutive calls of nnfw_run()
  runtime/onert/core/include/exec/FunctionSequence.h
  runtime/onert/core/src/exec/DataflowExecutor.cc
  runtime/onert/core/src/exec/LinearExecutor.cc
  runtime/onert/core/src/exec/ParallelExecutor.cc
  tests/nnfw_api/src/RegressionTests.cc
Labels: PR/ready for review

#4513 [onert] Supports optional input through nnapi frontend
  runtime/onert/frontend/nnapi/execution.cc
  runtime/onert/frontend/nnapi/wrapper/ANeuralNetworksExecution.cc
  runtime/onert/frontend/nnapi/wrapper/ANeuralNetworksExecution.h
Labels: PR/ready for review, area/onert

#4547 [onert] Fix when duplicated output tensors used
  runtime/onert/core/include/ir/OperandIndexSequence.h
  runtime/onert/core/src/compiler/pass/OddOutputPass.cc
  runtime/onert/core/src/compiler/pass/OddOutputPass.h
  runtime/onert/core/src/compiler/pass/PermutationEliminationPass.cc
  tests/nnfw_api/src/GenModelTests.cc
Labels: Urgent

#4532 [onert] Allows output of operation to be undefined
  runtime/onert/core/src/compiler/ExecutorFactory.cc
  runtime/onert/core/src/compiler/HEScheduler.cc
  runtime/onert/core/src/compiler/LoweredGraph.cc
  runtime/onert/core/src/compiler/pass/ConstantInsertionPass.cc
  runtime/onert/core/src/compiler/pass/PermutationOperationPass.cc
  runtime/onert/core/src/ir/Graph.cc
  runtime/onert/core/src/ir/GraphIterator.cc
  runtime/onert/core/src/ir/verifier/Verifier.cc
Labels: PR/ready for review, area/onert

#4557 [onert] Adding dynamic tests into skip file of acl and interp
  tests/nnapi/nnapi_gtest.skip.aarch64-linux.acl_cl
  tests/nnapi/nnapi_gtest.skip.aarch64-linux.acl_neon
  tests/nnapi/nnapi_gtest.skip.armv7l-linux.acl_cl
  tests/nnapi/nnapi_gtest.skip.armv7l-linux.acl_neon
  tests/nnapi/nnapi_gtest.skip.noarch.interp
Labels: PR/ready for review

#4541 [luci-interpreter] Support S16 AveragePool2D and MaxPool2D ops
  compiler/luci-interpreter/src/kernels/AveragePool2D.cpp
  compiler/luci-interpreter/src/kernels/AveragePool2D.h
  compiler/luci-interpreter/src/kernels/AveragePool2D.test.cpp
  compiler/luci-interpreter/src/kernels/MaxPool2D.cpp
  compiler/luci-interpreter/src/kernels/MaxPool2D.h
  compiler/luci-interpreter/src/kernels/MaxPool2D.test.cpp
  compiler/luci-interpreter/src/kernels/TestUtils.h
Labels: PR/ready for review

#4563 [infra] Remove TensorFlowLite 1.12 cmake
  infra/cmake/packages/TensorFlowLite-1.12/Lite/CMakeLists.txt
  infra/cmake/packages/TensorFlowLite-1.12/TensorFlowLiteConfig.cmake
  infra/cmake/packages/TensorFlowLite-1.12/TensorFlowLiteConfigVersion.cmake
Labels: PR/ready for review

#4564 [infra] Fix incorrect path cpuinfo.patch
  infra/cmake/packages/CpuInfo/cpuinfo.patch
Labels: PR/ready for review

#4413 [onert] Fix bug that doesn't round indices values in acl kernels
  compute/ARMComputeEx/src/core/CL/cl_kernels/one_hot.cl
  compute/ARMComputeEx/src/core/CL/kernels/CLOneHotKernel.cpp
  compute/ARMComputeEx/src/core/NEON/kernels/NEOneHotKernel.cpp
  tests/nnfw_api/src/CircleGen.cc
  tests/nnfw_api/src/CircleGen.h
  tests/nnfw_api/src/one_op_tests/OneHot.cc
Labels: PR/ready for review, area/onert

#4576 Revert "[infra] Fix incorrect path cpuinfo.patch (#4564)"
  infra/nnfw/cmake/packages/CpuInfo/cpuinfo.patch
Labels: Urgent

#4562 [onert] Move param and I/O size check
  runtime/onert/core/src/compiler/OperationValidator.cc
  runtime/onert/core/src/compiler/OperationValidator.h
  runtime/onert/core/src/compiler/ShapeValidator.cc
Labels: PR/ready for review

#4586 [one-cmds] Add missing declaration
  compiler/one-cmds/one-optimize
Labels: trivial

#4588 [mio-tf] Use tensorflow 2.3 source code
  compiler/mio-tf/CMakeLists.txt
Labels: PR/ready for review

#4573 [luci-interpreter] Fix symmetric quantization range
  compiler/luci-interpreter/src/kernels/Utils.cpp
Labels: PR/ready for review

#4567 [luci-interpreter] Add binary op helper function
  compiler/luci-interpreter/src/kernels/BinaryOpCommon.h
  compiler/luci-interpreter/src/kernels/CMakeLists.txt
Labels: PR/ready for review

#4597 [infra/cmd] Introduce user mode nnas docker-run
  infra/command/docker-run
Labels: PR/ready for review

#4545 [onert] Support ShapeValidator for BCQ Operations
  runtime/onert/core/src/compiler/ShapeValidator.cc
  runtime/onert/core/src/compiler/ShapeValidator.h
Labels: PR/ready for review

#4572 [luci-interpreter] Support S16 Relu op
  compiler/luci-interpreter/src/kernels/Relu.cpp
  compiler/luci-interpreter/src/kernels/Relu.h
  compiler/luci-interpreter/src/kernels/Relu.test.cpp
Labels: PR/ready for review

#4534 [onert] Support UnidirectionalSequenceLSTM on nnapi frontend
  runtime/onert/core/include/ir/operation/LSTM.h
  runtime/onert/core/src/compiler/ShapeValidator.cc
  runtime/onert/core/src/ir/OperationDumper.cc
  runtime/onert/core/src/ir/operation/LSTM.cc
  runtime/onert/frontend/nnapi/wrapper/OperationFactory.cc
Labels: PR/ready for review, area/onert

#4592 [luci-interpreter] Add TransposeConv U8 test
  compiler/luci-interpreter/src/kernels/TransposeConv.cpp
  compiler/luci-interpreter/src/kernels/TransposeConv.h
  compiler/luci-interpreter/src/kernels/TransposeConv.test.cpp
Labels: PR/ready for review

#4571 [luci-interpreter] Support S16 Mean op
  compiler/luci-interpreter/src/kernels/Mean.cpp
  compiler/luci-interpreter/src/kernels/Mean.h
  compiler/luci-interpreter/src/kernels/Mean.test.cpp
  compiler/luci-interpreter/src/kernels/Utils.h
Labels: PR/ready for review

#4610 [tools] Supports UnidirectionalSequenceLSTM on select_operator.py
  tools/tflitefile_tool/select_operator.py
  tools/tflitefile_tool/tensor_printer.py
Labels: PR/ready for review

#4580 [infra] Update cpuinfo package
  infra/cmake/packages/CpuInfoSourceConfig.cmake
  infra/nnfw/cmake/packages/CpuInfo/cpuinfo.patch
  packaging/cpuinfo.tar.gz
Labels: PR/ready for review

#4605 [onert] Fixes missing out printing name of LSTM
  runtime/onert/core/include/ir/operation/LSTM.h
  runtime/onert/core/src/ir/OperationDumper.cc
  runtime/onert/core/src/ir/operation/LSTM.cc
Labels: PR/ready for review, area/onert

#4619 [onert] Fix ResizeBilinear invalid output shape condition
  runtime/onert/core/src/util/ShapeInference.cc
Labels: PR/ready for review

#4608 [onert] Supports dynamic tensor for LSTM operation.
  runtime/onert/core/include/compiler/StaticShapeInference.h
  runtime/onert/core/include/exec/DynamicShapeInference.h
  runtime/onert/core/src/compiler/StaticShapeInference.cc
  runtime/onert/core/src/exec/DynamicShapeInference.cc
Labels: PR/ready for review, area/onert

#4621 [onert] Adds to initialize time_major param of LSTM operation
  runtime/onert/frontend/nnapi/wrapper/OperationFactory.cc
Labels: area/onert

#4614 [onert] Devirtualize calls in getTensorShape
  runtime/onert/backend/cpu/ops/OperationUtils.h
  runtime/onert/core/include/backend/IPortableTensor.h
  runtime/onert/core/include/backend/cpu_common/Tensor.h
  runtime/onert/core/src/backend/controlflow/UserTensor.h
Labels: PR/ready for review

#4616 [doc] Add supported operation on each backend
  docs/runtime/supported-operations-backend.md
Labels: PR/ready for review

#4569 [luci-interpreter] Support S16 Add op
  compiler/luci-interpreter/src/kernels/Add.cpp
  compiler/luci-interpreter/src/kernels/Add.h
  compiler/luci-interpreter/src/kernels/Add.test.cpp
Labels: PR/ready for review

#4570 [luci-interpreter] Support S16 Prelu op
  compiler/luci-interpreter/src/kernels/Prelu.cpp
  compiler/luci-interpreter/src/kernels/Prelu.h
  compiler/luci-interpreter/src/kernels/Prelu.test.cpp
Labels: PR/ready for review

#4624 [onert] Remove unused Source.h and Sink.h
  runtime/onert/core/src/exec/ExecutorBase.h
  runtime/onert/core/src/exec/Sink.h
  runtime/onert/core/src/exec/Source.h
Labels: PR/ready for review

#4617 [onert/lib] Restructure nnapi library
  runtime/libs/nnapi/CMakeLists.txt
  runtime/libs/nnapi/include/NeuralNetworksExShim.h
  runtime/libs/nnapi/include/NeuralNetworksLoadHelpers.h
  runtime/libs/nnapi/include/NeuralNetworksShim.h
  runtime/libs/nnapi/include/NeuralNetworksTypes.h
  runtime/libs/nnapi/v1.1/CMakeLists.txt
  runtime/libs/nnapi/v1.1/include/NeuralNetworksExShim.h
  runtime/libs/nnapi/v1.1/include/NeuralNetworksLoadHelpers.h
  runtime/libs/nnapi/v1.1/include/NeuralNetworksShim.h
  runtime/libs/nnapi/v1.2/CMakeLists.txt
Labels: PR/ready for review

#4630 [onert/cpu] Initialize ReduceLayer reduce type field
  runtime/onert/backend/cpu/ops/ReduceLayer.cc
  runtime/onert/backend/cpu/ops/ReduceLayer.h
Labels: PR/ready for review

#4629 [onert] Fix ResizeBilinear shape inference log
  runtime/onert/core/src/util/ShapeInference.cc
Labels: PR/ready for review, trivial

#4632 [onert] Install armcompute .so file only
  Makefile.template
Labels: PR/ready for review, trivial

#4636 [onert] Match mmap-munmap pair in base_loader
  runtime/onert/frontend/base_loader/include/base_loader.h
Labels: area/onert

#4643 Release note 1.10.0
  docs/release/1.10/release-note-1.10.0.md
Labels: PR/ready for review

#4635 Bump to verison 1.11.0
  docs/conf.py
  packaging/nnfw.spec
  runtime/contrib/android/api/build.gradle
  runtime/onert/api/include/nnfw_version.h
Labels: PR/NO MERGE, PR/ready for review

#4590 [luci-interpreter] Support S16 Conv2D op
  compiler/luci-interpreter/src/kernels/Conv2D.cpp
  compiler/luci-interpreter/src/kernels/Conv2D.h
  compiler/luci-interpreter/src/kernels/Conv2D.test.cpp
Labels: PR/ready for review

#4609 [onert] Support UnidirectionalSequenceLSTM operation on cpu backend
  compute/cker/include/cker/NeonTensorUtils.h
  compute/cker/include/cker/PortableTensorUtils.h
  compute/cker/include/cker/TensorUtils.h
  compute/cker/include/cker/Types.h
  compute/cker/include/cker/operation/LSTM.h
  runtime/onert/backend/cpu/KernelGenerator.cc
  runtime/onert/backend/cpu/KernelGenerator.h
  runtime/onert/backend/cpu/ops/LSTMLayer.cc
  runtime/onert/backend/cpu/ops/LSTMLayer.h
  runtime/onert/backend/cpu/ops/OperationUtils.h
Labels: PR/ready for review, area/onert

#4626 [onert/cpu] Implement Dequantize UINT8 kernel for cpu backend
  compute/cker/include/cker/operation/Dequantize.h
  runtime/onert/backend/cpu/KernelGenerator.cc
  runtime/onert/backend/cpu/ops/ElementwiseUnaryLayer.cc
  runtime/onert/backend/cpu/ops/ElementwiseUnaryLayer.h
  runtime/onert/frontend/base_loader/include/base_loader.h
  tests/nnapi/nnapi_gtest.skip.aarch64-linux.cpu
  tests/nnapi/nnapi_gtest.skip.armv7l-linux.cpu
  tests/nnapi/nnapi_gtest.skip.x86_64-linux.cpu
Labels: area/onert

#4591 [luci-interpreter] Support S16 DepthwiseConv2D op
  compiler/luci-interpreter/src/kernels/DepthwiseConv2D.cpp
  compiler/luci-interpreter/src/kernels/DepthwiseConv2D.h
  compiler/luci-interpreter/src/kernels/DepthwiseConv2D.test.cpp
Labels: PR/ready for review

#4593 [luci-interpreter] Support S16 TransposeConv op
  compiler/luci-interpreter/src/kernels/TransposeConv.cpp
  compiler/luci-interpreter/src/kernels/TransposeConv.h
  compiler/luci-interpreter/src/kernels/TransposeConv.test.cpp
Labels: PR/ready for review

#4633 [onert] Divide sparsity info loading function
  runtime/onert/frontend/base_loader/include/base_loader.h
Labels: PR/ready for review

#4648 [onert/cker] Define temporary variable to avoid warning
  compute/cker/include/cker/operation/LSTM.h
Labels: PR/ready for review, trivial

#4652 [onert] Enables some nnapi tests for UnidirectionalSequenceLSTM
  tests/nnapi/nnapi_gtest.skip.aarch64-linux.acl_cl
  tests/nnapi/nnapi_gtest.skip.aarch64-linux.acl_neon
  tests/nnapi/nnapi_gtest.skip.armv7l-linux.acl_cl
  tests/nnapi/nnapi_gtest.skip.armv7l-linux.acl_neon
  tests/nnapi/nnapi_gtest.skip.noarch.interp
  tests/nnapi/specs/V1_2/unidirectional_sequence_lstm_1step.mod.py
  tests/nnapi/specs/V1_2/unidirectional_sequence_lstm_batch_major_norm_peephole_projection.mod.py
  tests/nnapi/specs/V1_2/unidirectional_sequence_lstm_batch_major_peephole_projection_bias.mod.py
  tests/nnapi/specs/V1_2/unidirectional_sequence_lstm_layer_norm_cifg_peephole.mod.py
  tests/nnapi/specs/V1_2/unidirectional_sequence_lstm_norm_peephole_projection.mod.py
Labels: PR/ready for review, area/onert

#4656 [onert] Enables some LSTM tests for cpu
  tests/nnapi/nnapi_gtest.skip.aarch64-linux.cpu
  tests/nnapi/nnapi_gtest.skip.armv7l-linux.cpu
  tests/nnapi/nnapi_gtest.skip.x86_64-linux.cpu
Labels: PR/ready for review, area/onert

#4655 [onert] Allows variable tensor
  runtime/onert/core/include/ir/OperandInfo.h
  runtime/onert/core/src/compiler/Linear.cc
  runtime/onert/core/src/compiler/LoweredGraph.cc
  runtime/onert/frontend/base_loader/include/base_loader.h
Labels: PR/ready for review, area/onert

#4657 [onert/cpu] Implement Dequantize INT8 kernel for cpu backend
  compute/cker/include/cker/operation/Dequantize.h
  runtime/onert/backend/cpu/ops/ElementwiseUnaryLayer.cc
  runtime/onert/core/src/compiler/OperationValidator.cc
  tests/nnapi/nnapi_gtest.skip.aarch64-linux.acl_cl
  tests/nnapi/nnapi_gtest.skip.aarch64-linux.acl_neon
  tests/nnapi/nnapi_gtest.skip.aarch64-linux.cpu
  tests/nnapi/nnapi_gtest.skip.armv7l-linux.acl_cl
  tests/nnapi/nnapi_gtest.skip.armv7l-linux.acl_neon
  tests/nnapi/nnapi_gtest.skip.armv7l-linux.cpu
  tests/nnapi/nnapi_gtest.skip.noarch.interp
  tests/nnapi/nnapi_gtest.skip.x86_64-linux.cpu
  tests/nnapi/specs/V1_2/dequantize_v1_2.mod.py
Labels: area/onert

#4653 [onert] Supports UnidirectionalSequenceLSTM on base_loader
  runtime/onert/backend/cpu/KernelGenerator.cc
  runtime/onert/backend/cpu/ops/LSTMLayer.cc
  runtime/onert/backend/cpu/ops/LSTMLayer.h
  runtime/onert/core/src/compiler/ShapeValidator.cc
  runtime/onert/frontend/base_loader/include/base_loader.h
  runtime/onert/frontend/circle/src/circle_loader.cc
  runtime/onert/frontend/tflite/src/tflite_loader.cc
Labels: PR/ready for review, area/onert

#4667 [onert] Introduce int8 and int16 type
  runtime/onert/core/include/ir/DataType.h
  runtime/onert/core/src/ir/DataType.cc
Labels: PR/ready for review

#4668 [onert] Fix concat elimination bug
  runtime/onert/backend/acl_cl/Optimizer.cc
  runtime/onert/backend/acl_common/AclSubTensorAnalyzer.h
Labels: PR/ready for review

#4666 [onert] Add nnfw_api negative cases for Concat
  tests/nnfw_api/src/one_op_tests/Concat.cc
Labels: PR/ready for review

#4673 [nnpkgrun] Remove unnessary dependency
  tests/tools/nnpackage_run/CMakeLists.txt
Labels: trivial

#4568 [luci-interpreter] Support S16 Mul op
  compiler/luci-interpreter/src/kernels/Mul.cpp
  compiler/luci-interpreter/src/kernels/Mul.h
  compiler/luci-interpreter/src/kernels/Mul.test.cpp
Labels: PR/ready for review

#4676 [nnfwapi] Fix GTEST.NO_ASSERTION
  tests/nnfw_api/src/one_op_tests/Concat.cc
Labels: PR/ready for review

#4677 [release/1.10.0] [nnfwapi] Fix GTEST.NO_ASSERTION
  tests/nnfw_api/src/one_op_tests/Concat.cc
Labels: PR/ready for review

#4689 [onert/cpu] Fix Add&Sub assert bug
  runtime/onert/backend/cpu/ops/BinaryArithmeticLayer.cc
Labels: PR/ready for review

#4687 [OneOpTest] UINT8 tensor test
  runtime/onert/core/src/compiler/OperationValidator.cc
  runtime/onert/core/src/compiler/OperationValidator.h
  tests/nnfw_api/src/CircleGen.cc
  tests/nnfw_api/src/CircleGen.h
  tests/nnfw_api/src/GenModelTest.h
  tests/nnfw_api/src/one_op_tests/Add.cc
Labels: PR/ready for review

#4684 [nnfw_api] Introduce NNFW_TYPE_TENSOR_QUANT8_ASYMM_SIGNED type
  runtime/onert/api/include/nnfw.h
  runtime/onert/api/src/nnfw_api.cc
  runtime/onert/api/src/nnfw_api_internal.cc
  runtime/onert/backend/cpu/ops/ElementwiseUnaryLayer.cc
  runtime/onert/core/src/backend/IConstantInitializer.cc
  runtime/onert/core/src/compiler/OperationValidator.cc
  runtime/onert/core/src/exec/IPermuteFunction.h
  runtime/onert/frontend/base_loader/include/base_loader.h
  tests/nnfw_api/src/GenModelTest.h
Labels: PR/ready for review

#4701 [release/1.10.0] Update release note
  docs/release/1.10/release-note-1.10.0.md
Labels: PR/ready for review

#4717 Update release note
  docs/release/1.10/release-note-1.10.0.md
Labels: PR/ready for review

#4708 [onert] Select and SelectV2 operation validator
  runtime/onert/core/src/compiler/OperationValidator.cc
  runtime/onert/core/src/compiler/OperationValidator.h
  runtime/onert/core/src/compiler/ShapeValidator.cc
  tests/nnfw_api/src/CircleGen.cc
  tests/nnfw_api/src/CircleGen.h
  tests/nnfw_api/src/one_op_tests/Select.cc
Labels: PR/ready for review

#4651 [onert] Adds a nnapi test to verify dynamic inference of UnidirectionalSequenceLSTM
  runtime/onert/core/src/compiler/StaticShapeInferer.cc
  tests/nnapi/nnapi_gtest.skip.aarch64-linux.acl_cl
  tests/nnapi/nnapi_gtest.skip.aarch64-linux.acl_neon
  tests/nnapi/nnapi_gtest.skip.armv7l-linux.acl_cl
  tests/nnapi/nnapi_gtest.skip.armv7l-linux.acl_neon
  tests/nnapi/nnapi_gtest.skip.noarch.interp
  tests/nnapi/specs/V1_2/unidirectional_sequence_lstm_dynamic_nnfw.mod.py
Labels: PR/ready for review, area/onert

#4682 [onert] Support optional bias tensor for FullyConnected in ACL backend
  runtime/onert/backend/acl_common/AclConstantInitializer.cc
  runtime/onert/backend/acl_common/AclKernelGen.h
  tests/nnfw_api/src/one_op_tests/FullyConnected.cc
Labels: area/onert

#4720 [onert] Move operation validator to model loading phase
  runtime/onert/core/src/compiler/Compiler.cc
  runtime/onert/core/src/ir/Graph.cc
  runtime/onert/core/src/ir/OperationValidator.cc
  runtime/onert/core/src/ir/OperationValidator.h
  tests/nnfw_api/src/one_op_tests/Add.cc
  tests/nnfw_api/src/one_op_tests/Equal.cc
  tests/nnfw_api/src/one_op_tests/LeakyRelu.cc
  tests/nnfw_api/src/one_op_tests/Select.cc
Labels: PR/ready for review

#4724 [OneOpTest] Quantization tensor condition
  tests/nnfw_api/src/CircleGen.cc
  tests/nnfw_api/src/GenModelTest.h
  tests/nnfw_api/src/one_op_tests/Add.cc
Labels: PR/ready for review

#4737 [infra] Update dockerfile - ubuntu 18.04
  infra/docker/Dockerfile.1804
Labels: PR/ready for review

#4736 [onert] Update nnapi lib header
  runtime/libs/nnapi/include/NeuralNetworksShim.h
  runtime/libs/nnapi/include/NeuralNetworksTypes.h
Labels: PR/ready for review

#4738 [onert] make new_shape param optional in CircleGen::addOperatorReshape
  tests/nnfw_api/src/CircleGen.cc
  tests/nnfw_api/src/CircleGen.h
  tests/nnfw_api/src/GenModelTests.cc
  tests/nnfw_api/src/ModelTestDynamicTensor.cc
Labels: PR/ready for review

#4739 Strip unneeded for shared libraries
  runtime/onert/api/CMakeLists.txt
  runtime/onert/backend/acl_cl/CMakeLists.txt
  runtime/onert/backend/acl_neon/CMakeLists.txt
  runtime/onert/backend/cpu/CMakeLists.txt
  runtime/onert/core/CMakeLists.txt
  runtime/onert/frontend/circle/CMakeLists.txt
  runtime/onert/frontend/tflite/CMakeLists.txt
Labels: PR/ready for review

#4743 [infra] Introduce yapf format file
  .style.yapf
  infra/command/format
Labels: PR/ready for review

#4753 [onert] Ignore build type upper/lower case
  infra/nnfw/CMakeLists.txt
  runtime/onert/api/CMakeLists.txt
  runtime/onert/backend/acl_cl/CMakeLists.txt
  runtime/onert/backend/acl_neon/CMakeLists.txt
  runtime/onert/backend/cpu/CMakeLists.txt
  runtime/onert/core/CMakeLists.txt
  runtime/onert/frontend/circle/CMakeLists.txt
  runtime/onert/frontend/tflite/CMakeLists.txt
Labels: PR/ready for review

#4650 [onert] Implement AddN kernel for cpu backend
  compute/cker/include/cker/operation/AddN.h
  runtime/onert/backend/cpu/KernelGenerator.cc
  runtime/onert/backend/cpu/KernelGenerator.h
  runtime/onert/backend/cpu/ops/AddNLayer.cc
  runtime/onert/backend/cpu/ops/AddNLayer.h
  runtime/onert/core/include/ir/Operations.Include.h
  runtime/onert/core/include/ir/Operations.lst
  runtime/onert/core/include/ir/operation/AddN.h
  runtime/onert/core/src/ir/OperationValidator.cc
  runtime/onert/core/src/ir/OperationValidator.h
  runtime/onert/core/src/ir/operation/AddN.cc
  runtime/onert/frontend/base_loader/include/base_loader.h
  tests/nnfw_api/src/CircleGen.cc
  tests/nnfw_api/src/CircleGen.h
  tests/nnfw_api/src/one_op_tests/AddN.cc
Labels: PR/ready for review

#4771 [onert] Introduce private methods for OperationValidator
  runtime/onert/core/src/ir/OperationValidator.cc
  runtime/onert/core/src/ir/OperationValidator.h
Labels: PR/ready for review, trivial

#4775 Support optional bias tensor in HEScheduler and ExecutionObservers
  runtime/onert/core/src/compiler/HEScheduler.cc
  runtime/onert/core/src/exec/ExecutionObservers.cc
Labels: area/onert

#4777 [onert] Reduce namespace in OperationValidator
  runtime/onert/core/src/ir/OperationValidator.cc
  runtime/onert/core/src/ir/OperationValidator.h
Labels: PR/ready for review, trivial

#4770 [onert] Renaming expect_error_on_run() method
  tests/nnfw_api/src/GenModelTest.h
  tests/nnfw_api/src/GenModelTests.cc
  tests/nnfw_api/src/ModelTestDynamicTensor.cc
Labels: PR/ready for review

#4781 [tfgraph-xform] Remove tfgraph-xform
  compiler/tfgraph-xform/CMakeLists.txt
  compiler/tfgraph-xform/README.md
Labels: PR/ready for review

#4778 [onert] OperationValidator field
  runtime/onert/core/src/ir/OperationValidator.cc
  runtime/onert/core/src/ir/OperationValidator.h
Labels: PR/ready for review

#4792 [infra] Remove TensorFlowSource and TensorFlowProtoText 1.12
  infra/cmake/packages/TensorFlowProtoText-1.12/TensorFlowProtoTextConfig.cmake
  infra/cmake/packages/TensorFlowProtoText-1.12/TensorFlowProtoTextConfigVersion.cmake
  infra/cmake/packages/TensorFlowProtoText-1.12/build/CMakeLists.txt
  infra/cmake/packages/TensorFlowProtoText-1.12/make_directories.sh
  infra/cmake/packages/TensorFlowSource-1.12/TensorFlowSourceConfig.cmake
  infra/cmake/packages/TensorFlowSource-1.12/TensorFlowSourceConfigVersion.cmake
Labels: PR/ready for review

#4797 [res] Recurrent keras models
  res/TensorFlowPythonExamples/examples/gru/__init__.py
  res/TensorFlowPythonExamples/examples/lstm/__init__.py
  res/TensorFlowPythonExamples/examples/rnn/__init__.py
Labels: PR/ready for review

#4805 [bcq-tools] rename bcq-tools
  compiler/bcq-tools/generate_bcq_metadata.py
  compiler/bcq-tools/generate_bcq_output_arrays.py
Labels: PR/ready for review

#4802 [one-cmds] Revise one-import-tf as python script
  compiler/one-cmds/CMakeLists.txt
  compiler/one-cmds/one-import
  compiler/one-cmds/one-import-tf
  compiler/one-cmds/tests/CMakeLists.txt
  compiler/one-cmds/tests/one-import_002.cfg
  compiler/one-cmds/tests/one-import_002.test
  compiler/one-cmds/utils.py
Labels: PR/ready for review

#4803 [compiler] Removed not used project: gen-core and others
  compiler/gen-core/CMakeLists.txt
  compiler/gen-core/README.md
  compiler/gen-core/include/gencore/HDF5Common.h
  compiler/gen-core/include/gencore/HDF5Exporter.h
  compiler/gen-core/include/gencore/HDF5Importer.h
  compiler/gen-core/requires.cmake
  compiler/gen-core/src/HDF5Common.cpp
  compiler/gen-core/src/HDF5Exporter.cpp
  compiler/gen-core/src/HDF5Importer.cpp
  compiler/gen-tf-input/CMakeLists.txt
  compiler/gen-tf-input/README.md
  compiler/gen-tf-input/src/Driver.cpp
  compiler/gen-tf-output/CMakeLists.txt
  compiler/gen-tf-output/README.md
  compiler/gen-tf-output/src/Driver.cpp
  compiler/gen-tflite-output/CMakeLists.txt
  compiler/gen-tflite-output/README.md
  compiler/gen-tflite-output/src/Driver.cpp
Labels: PR/ready for review

#4751 [onert] Optimizes PermuteLayer of controlflow by ruy
  runtime/onert/core/CMakeLists.txt
  runtime/onert/core/include/ir/Coordinates.h
  runtime/onert/core/src/backend/controlflow/Backend.h
  runtime/onert/core/src/backend/controlflow/BackendContext.h
  runtime/onert/core/src/backend/controlflow/ExternalContext.h
  runtime/onert/core/src/backend/controlflow/KernelGenerator.cc
  runtime/onert/core/src/backend/controlflow/KernelGenerator.h
  runtime/onert/core/src/backend/controlflow/kernel/IfLayer.cc
  runtime/onert/core/src/backend/controlflow/kernel/IfLayer.h
  runtime/onert/core/src/backend/controlflow/kernel/PermuteLayer.cc
  runtime/onert/core/src/backend/controlflow/kernel/PermuteLayer.h
  runtime/onert/core/src/backend/controlflow/kernel/WhileLayer.cc
  runtime/onert/core/src/backend/controlflow/kernel/WhileLayer.h
  runtime/onert/core/src/exec/IPermuteFunction.h
Labels: area/onert

#4791 [infra] Build docker image with ubuntu codename
  infra/command/build-docker-image
  infra/docker/bionic/Dockerfile
  infra/docker/xenial/Dockerfile
Labels: PR/ready for review

#4816 [one-cmds] Revise one-codegen as python script
  compiler/one-cmds/one-codegen
Labels: PR/ready for review

#4818 [one-cmds] Revise one-import-bcq as python script
  compiler/one-cmds/one-import-bcq
  compiler/one-cmds/tests/one-import-bcq_neg_003.test
Labels: PR/ready for review

#4815 [infra] Fix tizen test package build fail
  infra/nnfw/cmake/packages/TensorFlowLite-1.13.1/TensorFlowLiteConfig.cmake
Labels: PR/ready for review

#4823 [one-cmds] Revise one-quantize as python script
  compiler/one-cmds/one-quantize
  compiler/one-cmds/tests/one-quantize_neg_006.test
Labels: PR/ready for review

#4809 [onert] Implement Floor kernel for cpu backend
  compute/cker/include/cker/operation/Elementwise.h
  runtime/onert/backend/cpu/KernelGenerator.cc
  runtime/onert/backend/cpu/ops/ElementwiseUnaryLayer.cc
  runtime/onert/backend/cpu/ops/ElementwiseUnaryLayer.h
  runtime/onert/core/src/ir/OperationValidator.cc
  runtime/onert/frontend/base_loader/include/base_loader.h
  tests/nnfw_api/src/CircleGen.cc
  tests/nnfw_api/src/CircleGen.h
  tests/nnfw_api/src/one_op_tests/Floor.cc
Labels: PR/ready for review

#4819 [one-cmds] Revise one-optimize as python script
  compiler/one-cmds/one-optimize
  compiler/one-cmds/tests/one-optimize_neg_002.test
  compiler/one-cmds/tests/one-optimize_neg_003.test
Labels: PR/ready for review

#4834 [moco-value-pbtxt-test] Check nnkit_tf_backend
  compiler/moco-value-pbtxt-test/CMakeLists.txt
Labels: PR/ready for review

#4787 Generate PNG from DOT while profiling
  tests/scripts/test_scheduler_with_profiling.sh
Labels: PR/ready for review

#4832 [infra] Introduce TensorFlow 1.13 package
  infra/cmake/packages/TensorFlow-1.13/TensorFlowConfig.cmake
  infra/cmake/packages/TensorFlow-1.13/TensorFlowConfigVersion.cmake
  infra/cmake/packages/TensorFlow-1.13/TensorFlowVersionChecker.c
Labels: PR/ready for review

#4822 [one-cmds] Revise one-import-tflite as python script
  compiler/one-cmds/one-import-tflite
Labels: PR/ready for review

#4821 [one-cmds] Revise one-pack as python script
  compiler/one-cmds/one-pack
  compiler/one-cmds/tests/one-pack_neg_001.test
  compiler/one-cmds/tests/one-pack_neg_003.test
Labels: PR/ready for review

#4841 [onert/cpu] Fix uninitialized field
  runtime/onert/backend/cpu/ops/BinaryArithmeticLayer.cc
Labels: PR/ready for review, trivial

#4846 [bcq-tools] Remove deprecated files
  compiler/bcq-tools/CMakeLists.txt
  compiler/bcq-tools/generate_bcq_metadata
  compiler/bcq-tools/generate_bcq_output_arrays
Labels: PR/ready for review

#4824 [one-cmds] Introduce one-build
  compiler/one-cmds/CMakeLists.txt
  compiler/one-cmds/how-to-use-one-commands.txt
  compiler/one-cmds/one-build
  compiler/one-cmds/one-build.template.cfg
  compiler/one-cmds/tests/one-build_001.cfg
  compiler/one-cmds/tests/one-build_001.test
  compiler/one-cmds/tests/one-build_002.cfg
  compiler/one-cmds/tests/one-build_002.test
  compiler/one-cmds/tests/one-build_neg_001.test
  compiler/one-cmds/tests/one-build_neg_002.cfg
  compiler/one-cmds/tests/one-build_neg_002.test
  compiler/one-cmds/tests/one-build_neg_003.cfg
  compiler/one-cmds/tests/one-build_neg_003.test
  compiler/one-cmds/tests/one-build_neg_004.cfg
  compiler/one-cmds/tests/one-build_neg_004.test
Labels: PR/ready for review

#4831 [luci] Revise vector access implementation in sparsifier
  compiler/luci/pass/src/Sparsifier.cpp
  compiler/luci/pass/src/Sparsifier.test.cpp
Labels: PR/ready for review

#4847 [one-cmds] fix one-build_neg_001 test
  compiler/one-cmds/tests/one-build_neg_001.test
Labels: PR/ready for review

#4835 [tfts] Check nnkit_tf_backend
  compiler/tfts/CMakeLists.txt
Labels: PR/ready for review

#4838 [infra] Remove TensorFlowProtoText and dependent package
  infra/cmake/packages/GoogleDoubleConversionConfig.cmake
  infra/cmake/packages/GoogleNSyncConfig.cmake
  infra/cmake/packages/TensorFlowProtoText-1.13.1/TensorFlowProtoTextConfig.cmake
  infra/cmake/packages/TensorFlowProtoText-1.13.1/TensorFlowProtoTextConfigVersion.cmake
  infra/cmake/packages/TensorFlowProtoText-1.13.1/build/CMakeLists.txt
  infra/cmake/packages/TensorFlowProtoText-1.13.1/make_directories.sh
Labels: PR/ready for review

#4845 [onert] Add newline to log
  runtime/onert/core/src/compiler/LoweredGraph.cc
Labels: trivial

#4741 [onert] Refactoring MoelTestDynamicTensor.cc
  tests/nnfw_api/src/ModelTestDynamicTensor.cc
Labels: PR/ready for review

#4840 [onert] Support depthwise convolution dilation
  runtime/onert/backend/acl_cl/KernelGenerator.cc
  runtime/onert/backend/acl_common/Convert.cc
  runtime/onert/backend/acl_common/Convert.h
  runtime/onert/backend/acl_neon/KernelGenerator.cc
  runtime/onert/backend/cpu/KernelGenerator.cc
  runtime/onert/backend/cpu/ops/DepthwiseConvolutionLayer.cc
  runtime/onert/backend/cpu/ops/DepthwiseConvolutionLayer.h
  runtime/onert/core/include/ir/operation/DepthwiseConv2D.h
  runtime/onert/core/src/ir/OperationValidator.cc
  runtime/onert/core/src/ir/OperationValidator.h
  runtime/onert/frontend/base_loader/include/base_loader.h
  runtime/onert/frontend/nnapi/wrapper/OperationFactory.cc
  tests/nnfw_api/src/CircleGen.cc
  tests/nnfw_api/src/CircleGen.h
  tests/nnfw_api/src/one_op_tests/DepthwiseConv2D.cc
Labels: PR/ready for review

#4827 [onert] Optimize PermuteLayer of controlflow by using enqueue functions
  runtime/onert/backend/acl_cl/operand/CLSubTensor.h
  runtime/onert/backend/acl_cl/operand/ICLTensor.cc
  runtime/onert/backend/acl_cl/operand/ICLTensor.h
  runtime/onert/backend/acl_neon/operand/NESubTensor.h
  runtime/onert/core/include/backend/ITensor.h
  runtime/onert/core/src/backend/controlflow/kernel/PermuteLayer.cc
  runtime/onert/core/src/backend/controlflow/kernel/PermuteLayer.h
  runtime/onert/core/src/exec/IPermuteFunction.h
  runtime/onert/core/src/exec/feature/nchw/Reader.h
  runtime/onert/core/src/exec/feature/nchw/View.h
  runtime/onert/core/src/exec/feature/nhwc/Reader.h
  runtime/onert/core/src/exec/feature/nhwc/View.h
Labels: PR/ready for review, area/onert
