Repository Samsung/ONE, pull requests merged in 2020-05, with the labels that each got.

#1318 [onert] Change the internal shape of dynamic_tensor.py
  tests/nnapi/nnapi_test_generator/android-10/dynamic_tensor.py
Labels: PR/NO MERGE

#1353 [luci/logex] LeakyRelu support for formatted logging
  compiler/luci/logex/src/FormattedGraph.cpp
Labels: PR/ready for review

#1354 [luci/service] LeakyRelu support for type and shape inference
  compiler/luci/service/src/CircleShapeInferenceRule.cpp
  compiler/luci/service/src/CircleTypeInferenceRule.cpp
Labels: PR/ready for review

#1339 [tflite2circle] Enable NEG
  compiler/tflite2circle/src/BuildBuiltinOptions.h
  compiler/tflite2circle/src/BuildBuiltinOptions/NegOptions.cpp
  compiler/tflite2circle/src/BuildBuiltinOptions/NegOptions.h
  compiler/tflite2circle/src/TFLBuiltinOptions.lst
Labels: PR/ready for review

#1338 [tflchef] Enable NEG operator
  compiler/tflchef/core/src/Op/Neg.cpp
  compiler/tflchef/core/src/Op/Neg.h
  compiler/tflchef/core/src/OpChef.def
  compiler/tflchef/core/src/OpChefs.h
  compiler/tflchef/proto/tflchef.proto
  compiler/tflchef/tflite/src/Op/Neg.cpp
  compiler/tflchef/tflite/src/Op/Neg.h
  compiler/tflchef/tflite/src/TFliteOpChefs.h
  compiler/tflchef/tflite/src/TFliteOpRegistry.h
Labels: PR/ready for review

#1349 [luci/tests] Enable testing for Pow operator
  compiler/luci/tests/test.lst
Labels: PR/ready for review

#1350 [luci/testing] enable testing for GatherNd operator
  compiler/luci/tests/test.lst
Labels: PR/ready for review

#1355 [tflchef] LeakyRelu support for network generation
  compiler/tflchef/core/src/Op/LeakyRelu.cpp
  compiler/tflchef/core/src/Op/LeakyRelu.h
  compiler/tflchef/core/src/OpChef.def
  compiler/tflchef/core/src/OpChefs.h
  compiler/tflchef/proto/tflchef.proto
  compiler/tflchef/tflite/src/Op/LeakyRelu.cpp
  compiler/tflchef/tflite/src/Op/LeakyRelu.h
  compiler/tflchef/tflite/src/TFliteOpChefs.h
  compiler/tflchef/tflite/src/TFliteOpRegistry.h
Labels: PR/ready for review

#1356 [tflite2circle] LeakyRelu support for circle conversion
  compiler/tflite2circle/src/BuildBuiltinOptions.h
  compiler/tflite2circle/src/BuildBuiltinOptions/LeakyReluOptions.cpp
  compiler/tflite2circle/src/BuildBuiltinOptions/LeakyReluOptions.h
  compiler/tflite2circle/src/TFLBuiltinOptions.lst
Labels: PR/ready for review

#1332 [luci/tests] Added ExpandDims test
  compiler/luci/tests/test.lst
Labels: PR/ready for review

#1337 [res] TF example for NEG
  res/TensorFlowPythonExamples/examples/negative/__init__.py
Labels: PR/ready for review

#1352 [luci/export] LeakyRelu support for export
  compiler/luci/export/src/CircleOperationExporter.cpp
Labels: PR/ready for review

#1351 [luci/import] LeakyRelu support for import
  compiler/luci/import/include/luci/Import/Nodes.h
  compiler/luci/import/include/luci/Import/Nodes/CircleLeakyRelu.h
  compiler/luci/import/src/GraphBuilderRegistry.cpp
  compiler/luci/import/src/Nodes/CircleLeakyRelu.cpp
Labels: PR/ready for review

#1322 [onert] Allow unused input of subgraph
  runtime/onert/core/src/backend/controlflow/kernel/IfLayer.cc
  runtime/onert/core/src/backend/controlflow/kernel/PermuteTensorsLayer.h
  runtime/onert/core/src/backend/controlflow/kernel/WhileLayer.cc
  runtime/onert/core/src/compiler/Linear.cc
  runtime/onert/core/src/exec/ExecutorBase.cc
  runtime/onert/core/src/ir/LoweredGraph.cc
Labels: PR/ready for review, area/onert

#1248 [onert/test] Update generated test archive
  packaging/nnapi_test_generated.tar.gz
  tests/nnapi/nnapi_gtest.skip.armv7l-tizen.acl_cl
Labels: PR/ready for review

#1323 [tools] Set subgraph index in select operator tool
  tools/tflitefile_tool/README.md
  tools/tflitefile_tool/select_operator.py
Labels: PR/ready for review

#1326 [onert] Introduce optimized broadcast mul kernel in cpu backend
  compute/cker/include/cker/operation/BinaryArithmeticOps.h
  compute/cker/include/cker/operation/optimized/BinaryArithmeticOps.h
Labels: PR/ready for review, area/onert

#1375 [onert] Unify PermuteLayer and PermuteTensorsLayer to PermuteLayer
  runtime/onert/core/src/backend/controlflow/KernelGenerator.cc
  runtime/onert/core/src/backend/controlflow/kernel/IfLayer.cc
  runtime/onert/core/src/backend/controlflow/kernel/PermuteLayer.cc
  runtime/onert/core/src/backend/controlflow/kernel/PermuteLayer.h
  runtime/onert/core/src/backend/controlflow/kernel/PermuteTensorsLayer.h
  runtime/onert/core/src/backend/controlflow/kernel/WhileLayer.cc
Labels: PR/ready for review, area/onert

#1333 [res] Add SpaceToDepth tfl recipe
  res/TensorFlowLiteRecipes/SpaceToDepth_000/test.recipe
  res/TensorFlowLiteRecipes/SpaceToDepth_000/test.reverse
Labels: PR/ready for review

#1382 [onert] Shape Inference for Expand_Dims and its tests
  runtime/onert/core/include/util/ShapeInference.h
  runtime/onert/core/src/util/shapeinf/ExpandDims.cc
  runtime/onert/test/util/ShapeInference.cc
  tests/nnapi/nnapi_gtest.skip.aarch64-linux.acl_cl
  tests/nnapi/nnapi_gtest.skip.aarch64-linux.acl_neon
  tests/nnapi/nnapi_gtest.skip.armv7l-linux.acl_cl
  tests/nnapi/nnapi_gtest.skip.armv7l-linux.acl_neon
  tests/nnapi/nnapi_gtest.skip.noarch.interp
  tests/nnapi/specs/V1_2/expand_dims_dynamic_nnfw.mod.py
Labels: PR/ready for review

#1396 [luci] Enable SpaceToDepth operator in export
  compiler/luci/export/src/CircleOperationExporter.cpp
Labels: PR/ready for review

#1421 [recipe] LeakyRelu add network recipe
  res/TensorFlowLiteRecipes/LeakyRelu_000/test.recipe
  res/TensorFlowLiteRecipes/LeakyRelu_000/test.reverse
Labels: PR/ready for review

#1426 [luci/tests] LeakyRelu enable luci testring
  compiler/luci/tests/test.lst
Labels: PR/ready for review

#1340 [luci] Support NEG operator in lang
  compiler/luci/lang/include/luci/IR/CircleNodes.h
  compiler/luci/lang/include/luci/IR/CircleNodes.lst
  compiler/luci/lang/include/luci/IR/Nodes/CircleNeg.h
  compiler/luci/lang/src/Nodes/CircleNeg.test.cpp
Labels: PR/ready for review

#1430 [tflchef] ResizeNearestNeighbor support for tflchef
  compiler/tflchef/core/src/Op/ResizeNearestNeighbor.cpp
  compiler/tflchef/core/src/Op/ResizeNearestNeighbor.h
  compiler/tflchef/core/src/OpChef.def
  compiler/tflchef/core/src/OpChefs.h
  compiler/tflchef/proto/tflchef.proto
  compiler/tflchef/tflite/src/Op/ResizeNearestNeighbor.cpp
  compiler/tflchef/tflite/src/Op/ResizeNearestNeighbor.h
  compiler/tflchef/tflite/src/TFliteOpChefs.h
  compiler/tflchef/tflite/src/TFliteOpRegistry.h
Labels: PR/ready for review

#1429 [luci/lang] ResizeNearestNeighbor support for IR
  compiler/luci/lang/include/luci/IR/CircleNodes.h
  compiler/luci/lang/include/luci/IR/CircleNodes.lst
  compiler/luci/lang/include/luci/IR/Nodes/CircleResizeNearestNeighbor.h
  compiler/luci/lang/src/Nodes/CircleResizeNearestNeighbor.test.cpp
Labels: PR/ready for review

#1433 [tflite2circle] ResizeNearestNeighbor support for circle conversion
  compiler/tflite2circle/src/BuildBuiltinOptions.h
  compiler/tflite2circle/src/BuildBuiltinOptions/ResizeNearestNeighborOptions.cpp
  compiler/tflite2circle/src/BuildBuiltinOptions/ResizeNearestNeighborOptions.h
  compiler/tflite2circle/src/TFLBuiltinOptions.lst
Labels: PR/ready for review

#1435 [tfldump] Support Reduce Max
  compiler/tfldump/src/OpPrinter.cpp
Labels: PR/ready for review

#1436 [circledump] Support Reduce Max
  compiler/circledump/src/OpPrinter.cpp
Labels: PR/ready for review

#1437 [luci] Support Reduce Max in tests
  compiler/luci/tests/test.lst
Labels: PR/ready for review

#1381 [onert] Make tanh test to use dynamic_tensor python module
  tests/nnapi/nnapi_gtest.skip.aarch64-linux.acl_cl
  tests/nnapi/nnapi_gtest.skip.aarch64-linux.acl_neon
  tests/nnapi/nnapi_gtest.skip.armv7l-linux.acl_cl
  tests/nnapi/nnapi_gtest.skip.armv7l-linux.acl_neon
  tests/nnapi/nnapi_gtest.skip.noarch.interp
  tests/nnapi/specs/V1_2/tanh_v1_dynamic.mod.py
  tests/nnapi/specs/V1_2/tanh_v1_dynamic_nnfw.mod.py
Labels: PR/ready for review

#1387 [onert] Adding const to the param of getShape(..)
  runtime/onert/core/include/backend/ITensor.h
  runtime/onert/core/src/backend/ITensor.cc
Labels: PR/ready for review

#1424 [onert] Introduce logging macro VERBOSE_F
  runtime/onert/core/include/util/logging.h
Labels: trivial

#1438 [luci-interpreter] Use optimized kernels for Conv2D
  compiler/luci-interpreter/src/kernels/CMakeLists.txt
  compiler/luci-interpreter/src/kernels/Conv2D.cpp
  compiler/luci-interpreter/src/kernels/Conv2D.h
Labels: PR/ready for review

#1446 Update readme.md
  README.md
Labels: PR/ready for review

#1442 Update how-to-contribute.md
  docs/howto/how-to-contribute.md
Labels: PR/ready for review

#1388 [onert] Change Shapes to ir::Shape in ShapeInference.cc
  runtime/onert/core/include/util/ShapeInference.h
  runtime/onert/core/src/interp/operations/AvgPool2D.cc
  runtime/onert/core/src/interp/operations/Conv2D.cc
  runtime/onert/core/src/interp/operations/DepthwiseConv2D.cc
  runtime/onert/core/src/interp/operations/MaxPool2D.cc
  runtime/onert/core/src/util/shapeinf/ShapeInference.cc
  runtime/onert/test/util/ShapeInference.cc
Labels: PR/ready for review

#1445 Update roadmap.md
  docs/overview/roadmap.md
Labels: PR/ready for review

#1451 Update how-to-contribute.md
  docs/howto/how-to-contribute.md
Labels: PR/ready for review

#1443 [onert/nnpkg] Set backend after model load
  tests/tools/nnpackage_run/src/nnpackage_run.cc
Labels: PR/ready for review

#1394 [onert] helper funcs to check if shape has unspecified rank or dim
  runtime/onert/core/include/ir/Shape.h
  runtime/onert/core/src/ir/Shape.cc
Labels: PR/ready for review

#1414 [onert] get output rank and dim from Tensor (not from operand)
  runtime/onert/core/include/exec/Execution.h
  runtime/onert/core/include/exec/IODescription.h
  runtime/onert/core/src/exec/Execution.cc
  runtime/onert/core/src/exec/ExecutorBase.cc
  runtime/onert/core/src/exec/ExecutorBase.h
  runtime/onert/core/src/exec/ShapeConverter.cc
  runtime/onert/core/src/exec/ShapeConverter.h
  runtime/onert/frontend/nnapi/wrapper/ANeuralNetworksExecution.cc
Labels: PR/ready for review

#1470 [res/PyExample] added L2 Normalize to python examples
  res/TensorFlowPythonExamples/examples/l2_normalize/__init__.py
Labels: PR/ready for review

#1488 [luci/export] ResizeNearestNeighbor support for export
  compiler/luci/export/src/CircleOperationExporter.cpp
Labels: PR/ready for review

#1487 [luci/import] ResizeNearestNeighbor support for import
  compiler/luci/import/include/luci/Import/Nodes.h
  compiler/luci/import/include/luci/Import/Nodes/CircleResizeNearestNeighbor.h
  compiler/luci/import/src/GraphBuilderRegistry.cpp
  compiler/luci/import/src/Nodes/CircleResizeNearestNeighbor.cpp
Labels: PR/ready for review

#1491 [tfldump] ResizeNearestNeighbor support for tflite dump
  compiler/tfldump/src/OpPrinter.cpp
Labels: PR/ready for review

#1492 [circledump] ResizeNearestNeighbor support for circle dump
  compiler/circledump/src/OpPrinter.cpp
Labels: PR/ready for review

#1490 [luci/service] ResizeNearestNeighbor support for shape and type inference
  compiler/luci/service/src/CircleShapeInferenceRule.cpp
  compiler/luci/service/src/CircleShapeInferenceRule.test.cpp
  compiler/luci/service/src/CircleTypeInferenceRule.cpp
  compiler/luci/service/src/TestGraph.h
Labels: PR/ready for review

#1493 [recipe] Add NearestNeighbor recipe for tflchef
  res/TensorFlowLiteRecipes/ResizeNearestNeightbor_000/test.recipe
  res/TensorFlowLiteRecipes/ResizeNearestNeightbor_000/test.reverse
Labels: PR/ready for review

#1489 [luci/logex] ResizeNearestNeighbor support for logging
  compiler/luci/logex/src/FormattedGraph.cpp
Labels: PR/ready for review

#1497 Update index of how-to-introduce-a-new-operation-into-runtime.md
  docs/howto/how-to-introduce-a-new-operation-into-runtime.md
Labels: PR/ready for review, trivial

#1504 [recipe] fix ResizeNearestNeighbor recipe name
  res/TensorFlowLiteRecipes/ResizeNearestNeighbor_000/test.recipe
  res/TensorFlowLiteRecipes/ResizeNearestNeighbor_000/test.reverse
Labels: PR/ready for review

#1499 [luci/export] Fix pow options type
  compiler/luci/export/src/CircleOperationExporter.cpp
Labels: PR/ready for review

#1507 [luci/tests] enable ResizeNearestNeighbor testing
  compiler/luci/tests/test.lst
Labels: PR/ready for review

#1510 [luci-interpreter] Expose Tensor class
  compiler/luci-interpreter/include/luci_interpreter/Interpreter.h
  compiler/luci-interpreter/include/luci_interpreter/core/DataType.h
  compiler/luci-interpreter/include/luci_interpreter/core/Tensor.h
  compiler/luci-interpreter/src/CMakeLists.txt
  compiler/luci-interpreter/src/TensorMap.h
  compiler/luci-interpreter/src/core/CMakeLists.txt
  compiler/luci-interpreter/src/core/Kernel.h
  compiler/luci-interpreter/src/core/Tensor.cpp
  compiler/luci-interpreter/src/kernels/Add.h
  compiler/luci-interpreter/src/kernels/AveragePool2D.h
  compiler/luci-interpreter/src/kernels/Concatenation.h
  compiler/luci-interpreter/src/kernels/Conv2D.h
  compiler/luci-interpreter/src/kernels/DepthwiseConv2D.h
  compiler/luci-interpreter/src/kernels/FullyConnected.h
  compiler/luci-interpreter/src/kernels/MaxPool2D.h
  compiler/luci-interpreter/src/kernels/Mul.h
  compiler/luci-interpreter/src/kernels/Reshape.h
  compiler/luci-interpreter/src/kernels/Softmax.h
  compiler/luci-interpreter/src/kernels/TestUtils.h
  compiler/luci-interpreter/src/kernels/Utils.h
Labels: PR/ready for review

#1457 [onert] Use default shape fixer visitor
  runtime/onert/backend/acl_cl/ShapeFixer.cc
  runtime/onert/backend/acl_cl/ShapeFixer.h
  runtime/onert/backend/acl_neon/ShapeFixer.cc
  runtime/onert/backend/acl_neon/ShapeFixer.h
  runtime/onert/backend/cpu/ShapeFixer.cc
  runtime/onert/backend/cpu/ShapeFixer.h
  runtime/onert/core/include/backend/IShapeFixer.h
Labels: PR/ready for review

#1458 [onert] Introduce new operations in extension for test
  runtime/nnapi-header/include/NeuralNetworksEx.h
  runtime/onert/frontend/nnapi/model.cc
Labels: PR/ready for review

#1358 [onert] Change `uses` and `defs` from list to set
  runtime/onert/core/include/ir/OpSequence.h
  runtime/onert/core/include/ir/Operand.h
  runtime/onert/core/include/ir/OperandIndexSequence.h
  runtime/onert/core/include/ir/Operation.h
  runtime/onert/core/include/ir/OperationIndexList.h
  runtime/onert/core/include/ir/OperationIndexSet.h
  runtime/onert/core/src/compiler/Fp32ToFp16Converter.cc
  runtime/onert/core/src/compiler/HEScheduler.cc
  runtime/onert/core/src/compiler/HEScheduler.h
  runtime/onert/core/src/compiler/Linear.cc
  runtime/onert/core/src/dumper/dot/DotDumper.cc
  runtime/onert/core/src/interp/Interpreter.cc
  runtime/onert/core/src/ir/Graph.cc
  runtime/onert/core/src/ir/GraphIterator.cc
  runtime/onert/core/src/ir/LoweredGraph.cc
  runtime/onert/core/src/ir/Operand.cc
  runtime/onert/core/src/ir/OperandIndexSequence.cc
  runtime/onert/core/src/ir/Operation.cc
  runtime/onert/core/src/ir/OperationIndexSet.cc
  runtime/onert/core/src/ir/pass/ConstantInsertionPass.cc
  runtime/onert/core/src/ir/pass/ConstantLoweringPass.cc
  runtime/onert/core/src/ir/pass/PermutationEliminationPass.cc
  runtime/onert/core/src/ir/pass/PermutationInsertionPass.cc
  runtime/onert/core/src/ir/pass/PermutationOperationPass.cc
  runtime/onert/core/src/ir/verifier/Verifier.cc
Labels: PR/ready for review, area/onert

#1417 [onert] Revising add_dynamic.mod.py
  tests/nnapi/nnapi_gtest.skip.aarch64-linux.acl_cl
  tests/nnapi/nnapi_gtest.skip.aarch64-linux.acl_neon
  tests/nnapi/nnapi_gtest.skip.armv7l-linux.acl_cl
  tests/nnapi/nnapi_gtest.skip.armv7l-linux.acl_neon
  tests/nnapi/nnapi_gtest.skip.noarch.interp
  tests/nnapi/specs/V1_0/add_dynamic_nnfw.mod.py
Labels: PR/ready for review

#1362 [onert] remove mbegin() and mend() from OperandIndexSequence
  runtime/onert/core/include/ir/OperandIndexSequence.h
Labels: PR/ready for review

#1374 [onert] Change WhileLayer's base interface to IFunction
  runtime/onert/core/src/backend/controlflow/kernel/WhileLayer.cc
  runtime/onert/core/src/backend/controlflow/kernel/WhileLayer.h
Labels: PR/ready for review, area/onert

#1521 [onert] Remove OperationValidator::visit(Fill) that validates nothing
  runtime/onert/core/src/compiler/OperationValidator.cc
  runtime/onert/core/src/compiler/OperationValidator.h
Labels: PR/ready for review

#1401 [onert] Implement Range Operation in cpu backend
  compute/cker/include/cker/operation/Range.h
  runtime/nnapi-header/include/NeuralNetworksEx.h
  runtime/onert/backend/cpu/KernelGenerator.cc
  runtime/onert/backend/cpu/KernelGenerator.h
  runtime/onert/backend/cpu/kernel/RangeLayer.cc
  runtime/onert/backend/cpu/kernel/RangeLayer.h
  runtime/onert/core/include/ir/Operations.Include.h
  runtime/onert/core/include/ir/Operations.lst
  runtime/onert/core/include/ir/operation/Range.h
  runtime/onert/core/src/compiler/OperationValidator.cc
  runtime/onert/core/src/compiler/OperationValidator.h
  runtime/onert/core/src/ir/OperationDumper.cc
  runtime/onert/core/src/ir/OperationDumper.h
  runtime/onert/core/src/ir/operation/Range.cc
  runtime/onert/frontend/base_loader/include/base_loader.h
  runtime/onert/frontend/nnapi/wrapper/OperationFactory.cc
  tests/nnapi/nnapi_gtest.skip.aarch64-linux.acl_cl
  tests/nnapi/nnapi_gtest.skip.aarch64-linux.acl_neon
  tests/nnapi/nnapi_gtest.skip.armv7l-linux.acl_cl
  tests/nnapi/nnapi_gtest.skip.armv7l-linux.acl_neon
  tests/nnapi/nnapi_gtest.skip.noarch.interp
  tests/nnapi/specs/Ex/range_ex_float_1.mod.py
  tests/nnapi/specs/Ex/range_ex_float_2.mod.py
Labels: PR/ready for review

#1538 [onert] Move calling time of adding controlflow backend to backend list
  runtime/onert/core/src/compiler/Compiler.cc
Labels: PR/ready for review, area/onert

#1544 [onert] Fix test error by assert condition
  runtime/onert/core/src/compiler/ManualScheduler.cc
Labels: PR/ready for review, bug

#1509 [luci-interpreter] Add Pad kernel
  compiler/luci-interpreter/src/KernelBuilder.cpp
  compiler/luci-interpreter/src/KernelBuilder.h
  compiler/luci-interpreter/src/kernels/CMakeLists.txt
  compiler/luci-interpreter/src/kernels/Pad.cpp
  compiler/luci-interpreter/src/kernels/Pad.h
  compiler/luci-interpreter/src/kernels/Pad.test.cpp
Labels: PR/ready for review

#1568 [tflchef] Introduce MatrixBandPart
  compiler/tflchef/core/src/CustomOp/MatrixBandPart.cpp
  compiler/tflchef/core/src/CustomOp/MatrixBandPart.h
  compiler/tflchef/core/src/OpChef.def
  compiler/tflchef/core/src/OpChefs.h
Labels: PR/ready for review

#1565 [tflchef] Suppport int64 dtype
  compiler/tflchef/core/src/DataChef.def
  compiler/tflchef/core/src/LexicalCast.cpp
  compiler/tflchef/core/src/ModelChef.cpp
Labels: PR/ready for review

#1513 [luci-interpreter] Make IR nodes available in `interpret` method
  compiler/luci-interpreter/include/luci_interpreter/Interpreter.h
  compiler/luci-interpreter/src/CMakeLists.txt
  compiler/luci-interpreter/src/Interpreter.cpp
  compiler/luci-interpreter/src/KernelMap.h
Labels: PR/ready for review

#1580 [onert] Adding basic flow to deallocate dynamic tensors
  runtime/onert/backend/cpu/DynamicTensorManager.cc
  runtime/onert/backend/cpu/DynamicTensorManager.h
  runtime/onert/core/include/backend/IDynamicTensorManager.h
  runtime/onert/core/src/compiler/Linear.cc
  runtime/onert/core/src/exec/ExecutorBase.cc
  runtime/onert/core/src/exec/FunctionSequence.cc
Labels: PR/ready for review

#1531 [onert] Modifying code that checks not specified graph output shape
  runtime/onert/frontend/nnapi/wrapper/ANeuralNetworksExecution.cc
Labels: PR/ready for review

#1579 [LUCI/IR] Added PRelu to luci IR
  compiler/luci/lang/include/luci/IR/CircleNodes.h
  compiler/luci/lang/include/luci/IR/CircleNodes.lst
  compiler/luci/lang/include/luci/IR/Nodes/CirclePRelu.h
  compiler/luci/lang/src/Nodes/CirclePRelu.test.cpp
Labels: PR/ready for review

#1569 [circlechef] Support int64 dtype
  compiler/circlechef/core/src/DataChef.def
  compiler/circlechef/core/src/LexicalCast.cpp
  compiler/circlechef/core/src/ModelChef.cpp
Labels: PR/ready for review

#1592 [tflchef] Added PRelu to tflchef
  compiler/tflchef/core/src/Op/PRelu.cpp
  compiler/tflchef/core/src/Op/PRelu.h
  compiler/tflchef/core/src/OpChef.def
  compiler/tflchef/core/src/OpChefs.h
  compiler/tflchef/tflite/src/Op/PRelu.cpp
  compiler/tflchef/tflite/src/Op/PRelu.h
  compiler/tflchef/tflite/src/TFliteOpChefs.h
  compiler/tflchef/tflite/src/TFliteOpRegistry.h
Labels: PR/ready for review

#1591 [tflite2circle] Added comment about PRelu to tflite2cicle
  compiler/tflite2circle/src/BuildBuiltinOptions.h
Labels: PR/ready for review

#1599 [luci] Add broadcast to Floor Mod shape inference
  compiler/luci/service/src/CircleShapeInferenceRule.cpp
Labels: PR/ready for review

#1603 [TensorFlowLiteRecipes] Add MatrixBandPart operator
  res/TensorFlowLiteRecipes/MatrixBandPart_000/test.recipe
Labels: PR/ready for review

#1541 [onert] Classifying and reordering methods in ITensorBuilder.h
  runtime/onert/core/include/backend/ITensorBuilder.h
Labels: PR/ready for review

#1536 [oneapi] Add RegressionTest #1535
  tests/nnfw_api/src/RegressionTests.cc
  tests/nnfw_api/src/fixtures.h
Labels: PR/ready for review

#1449 [onert/cpu] Implement ReduceAll operation for cpu backend
  runtime/onert/backend/cpu/KernelGenerator.cc
  runtime/onert/backend/cpu/KernelGenerator.h
  runtime/onert/backend/cpu/kernel/ReduceLayer.cc
  runtime/onert/backend/cpu/kernel/ReduceLayer.h
  runtime/onert/core/include/ir/Operations.Include.h
  runtime/onert/core/include/ir/Operations.lst
  runtime/onert/core/include/ir/operation/ReduceAll.h
  runtime/onert/core/src/ir/OperationDumper.cc
  runtime/onert/core/src/ir/OperationDumper.h
  runtime/onert/core/src/ir/operation/ReduceAll.cc
  runtime/onert/frontend/base_loader/CMakeLists.txt
  runtime/onert/frontend/base_loader/include/base_loader.h
  runtime/onert/frontend/nnapi/wrapper/OperationFactory.cc
  tests/nnapi/nnapi_gtest.skip.aarch64-linux.acl_cl
  tests/nnapi/nnapi_gtest.skip.aarch64-linux.acl_neon
  tests/nnapi/nnapi_gtest.skip.armv7l-linux.acl_cl
  tests/nnapi/nnapi_gtest.skip.armv7l-linux.acl_neon
  tests/nnapi/nnapi_gtest.skip.noarch.interp
  tests/nnapi/specs/V1_2/reduce_all.mod.py
  tests/nnapi/specs/V1_2/reduce_all_2D_nnfw.mod.py
  tests/nnapi/specs/V1_2/reduce_all_4D_nnfw.mod.py
Labels: PR/ready for review

#1601 [onert] support optional tensor in loader
  runtime/onert/core/include/util/Index.h
  runtime/onert/frontend/base_loader/include/base_loader.h
  runtime/onert/frontend/circle/src/circle_loader.cc
  runtime/onert/frontend/tflite/src/tflite_loader.cc
Labels: PR/ready for review

#1547 [onert] modify shape::num_element() considering dim = 0
  runtime/onert/core/include/ir/Shape.h
  runtime/onert/core/src/ir/Shape.cc
  runtime/onert/test/ir/Shape.cc
Labels: PR/ready for review

#1589 [res] Add half_pixel_centers attr in ResizeBilinear recipe
  res/TensorFlowLiteRecipes/ResizeBilinear_000/test.recipe
Labels: PR/ready for review

#1573 [luci] Enable ResizeBilinear in services
  compiler/luci/service/src/CircleShapeInferenceRule.cpp
  compiler/luci/service/src/CircleShapeInferenceRule.test.cpp
  compiler/luci/service/src/CircleTypeInferenceRule.cpp
  compiler/luci/service/src/TestGraph.h
Labels: PR/ready for review

#1627 [oneapi] Do not print package_dir in error
  runtime/onert/api/src/nnfw_api_internal.cc
Labels: trivial

#1620 [onert] support fullyconnected when bias is undefined in backend and kernel
  compute/cker/include/cker/operation/FullyConnected.h
  runtime/onert/backend/cpu/ConstantInitializer.cc
  runtime/onert/backend/cpu/KernelGenerator.cc
  runtime/onert/backend/cpu/kernel/FullyConnectedLayer.cc
  runtime/onert/backend/cpu/kernel/OperationUtils.h
Labels: PR/ready for review

#1550 [onert] assert for ITensor::setShape & getShape
  runtime/onert/core/src/backend/ITensor.cc
Labels: PR/ready for review, trivial

#1622 [onert] TC: multiple execution of a model with dynamic tensors
  tests/nnfw_api/src/ModelTestDynamicTensor.cc
Labels: PR/ready for review

#1613 [onert] Adding implementation for deallocSubgraphOutput()
  runtime/onert/backend/cpu/DynamicTensorManager.cc
  runtime/onert/core/src/exec/ExecutorBase.cc
  runtime/onert/core/src/exec/ExecutorBase.h
Labels: PR/ready for review

#1608 [onert] Adding implementation of planDealloc()
  runtime/onert/backend/cpu/DynamicTensorManager.cc
  runtime/onert/backend/cpu/DynamicTensorManager.h
  runtime/onert/core/include/backend/IDynamicTensorManager.h
  runtime/onert/core/src/compiler/Linear.cc
Labels: PR/ready for review

#1637 [oneapi/test] Close session on RegressionTest
  tests/nnfw_api/src/RegressionTests.cc
Labels: PR/ready for review

#1611 [onert] Adding implementation of DynamicTensorManager::deallocInput()
  runtime/onert/backend/cpu/DynamicTensorManager.cc
  runtime/onert/backend/cpu/DynamicTensorManager.h
  runtime/onert/backend/cpu/KernelGenerator.cc
  runtime/onert/core/include/backend/IDynamicTensorManager.h
  runtime/onert/core/include/exec/FunctionSequence.h
  runtime/onert/core/src/exec/FunctionSequence.cc
Labels: PR/ready for review

#1559 [onert] ShapeInference for Concat
  runtime/onert/core/include/util/ShapeInference.h
  runtime/onert/core/src/util/shapeinf/Concat.cc
  runtime/onert/core/src/util/shapeinf/ShapeInference.cc
  runtime/onert/test/util/ShapeInference.cc
  tests/nnapi/nnapi_gtest.skip.aarch64-linux.acl_cl
  tests/nnapi/nnapi_gtest.skip.aarch64-linux.acl_neon
  tests/nnapi/nnapi_gtest.skip.armv7l-linux.acl_cl
  tests/nnapi/nnapi_gtest.skip.armv7l-linux.acl_neon
  tests/nnapi/nnapi_gtest.skip.noarch.interp
  tests/nnapi/specs/V1_0/concat_dynamic_nnfw.mod.py
Labels: PR/ready for review

#1654 [onert] Refine BackendManager logging
  runtime/onert/core/src/compiler/BackendManager.cc
Labels: trivial

#1633 [luci-interpreter] Add observing functionality
  compiler/luci-interpreter/include/luci_interpreter/Interpreter.h
  compiler/luci-interpreter/include/luci_interpreter/core/Tensor.h
  compiler/luci-interpreter/src/Interpreter.cpp
Labels: PR/ready for review

#1667 [luci-value-test] Enable some tests
  compiler/luci-value-test/test.lst
Labels: PR/ready for review
