Repository Samsung/ONE, pull requests merged in 2020-12, with the labels that each got.

#5220 [onert] Revise Fill operation
  runtime/onert/backend/cpu/KernelGenerator.cc
  runtime/onert/core/include/ir/operation/Fill.h
  runtime/onert/core/include/util/ShapeInference.h
  runtime/onert/core/src/compiler/StaticShapeInferer.cc
  runtime/onert/core/src/exec/DynamicShapeInferer.cc
  runtime/onert/core/src/ir/OperationDumper.cc
  runtime/onert/core/src/ir/OperationDumper.h
  runtime/onert/core/src/ir/OperationValidator.cc
  runtime/onert/core/src/ir/OperationValidator.h
  runtime/onert/core/src/util/ShapeInference.cc
Labels: PR/ready for review

#5218 [onert] Support Elu operation on cpu backend
  compute/cker/include/cker/operation/ELU.h
  runtime/onert/backend/cpu/KernelGenerator.cc
  runtime/onert/backend/cpu/ops/ElementwiseActivationLayer.cc
  runtime/onert/backend/cpu/ops/ElementwiseActivationLayer.h
  runtime/onert/core/src/ir/OperationValidator.cc
  runtime/onert/frontend/base_loader/include/base_loader.h
  tests/nnfw_api/src/CircleGen.cc
  tests/nnfw_api/src/CircleGen.h
  tests/nnfw_api/src/one_op_tests/Elu.cc
Labels: PR/ready for review

#5228 [luci] Check nullptr exception in ShuffleWeight related test
  compiler/luci/pass/src/ShuffleWeightTo16x1Float32Pass.test.cpp
Labels: trivial

#5224 [infra] Install clang-format-8 in devloper docker image
  infra/docker/bionic/Dockerfile
  infra/docker/focal/Dockerfile
  infra/docker/xenial/Dockerfile
Labels: PR/ready for review

#5225 [onert/test] Use nnfw API for tflite loader test
  tests/tools/tflite_loader/CMakeLists.txt
  tests/tools/tflite_loader/src/tflite_loader.cc
Labels: PR/ready for review

#5231 [onert/cpu] Support Fill operation int64 shape data type
  compute/cker/include/cker/operation/Fill.h
  runtime/onert/backend/cpu/KernelGenerator.cc
  runtime/onert/backend/cpu/ops/FillLayer.cc
  runtime/onert/backend/cpu/ops/FillLayer.h
  runtime/onert/core/include/util/ShapeInference.h
  runtime/onert/core/src/compiler/StaticShapeInferer.cc
  runtime/onert/core/src/exec/DynamicShapeInferer.cc
  runtime/onert/core/src/util/ShapeInference.cc
  tests/nnfw_api/src/one_op_tests/Fill.cc
Labels: PR/ready for review

#5237 [onert/test] Remove unused function in tflite loader test tool
  tests/tools/tflite_loader/CMakeLists.txt
  tests/tools/tflite_loader/src/tflite_loader.cc
Labels: PR/ready for review, trivial

#5239 [onert] Modify shared_ptr<Execution> to unique_ptr<Execution>
  runtime/onert/api/src/nnfw_api_internal.cc
  runtime/onert/api/src/nnfw_api_internal.h
Labels: PR/ready for review

#5241 [onert] Remove unused option from CompilerOptions
  runtime/onert/core/include/compiler/Compiler.h
Labels: trivial

#5248 [bcq-tools] Fix typo in generate_bcq_output_arrays.py
  compiler/bcq-tools/generate_bcq_output_arrays.py
Labels: trivial

#5251 [one-cmds] Fix wrong arg and remove unnecessary comment
  compiler/one-cmds/one-import-bcq
  compiler/one-cmds/one-import-tf
Labels: PR/ready for review

#5238 [onert] Pass TracingCtx to Compiler
  runtime/onert/api/src/nnfw_api_internal.cc
  runtime/onert/core/include/compiler/Compiler.h
  runtime/onert/core/include/util/TracingCtx.h
  runtime/onert/core/src/compiler/Compiler.cc
  runtime/onert/core/src/compiler/ExecutorFactory.cc
  runtime/onert/core/src/compiler/LoweredGraph.cc
  runtime/onert/frontend/nnapi/wrapper/ANeuralNetworksCompilation.cc
  runtime/onert/frontend/nnapi/wrapper/ANeuralNetworksCompilation.h
  runtime/onert/test/core/exec/ExecInstance.cc
Labels: PR/ready for review

#5258 [onert] Make getter method be const
  runtime/onert/core/include/backend/BackendContext.h
Labels: trivial

#5245 [onert] Support FullyConnected operation on ruy backend
  compute/ruy/include/ruy/NeonTensorUtils.h
  compute/ruy/include/ruy/PortableTensorUtils.h
  compute/ruy/include/ruy/TensorUtils.h
  compute/ruy/include/ruy/Types.h
  compute/ruy/include/ruy/neon/neon_check.h
  compute/ruy/include/ruy/operation/FullyConnected.h
  runtime/onert/backend/ruy/KernelGenerator.cc
  runtime/onert/backend/ruy/KernelGenerator.h
  runtime/onert/backend/ruy/ops/FullyConnectedLayer.cc
  runtime/onert/backend/ruy/ops/FullyConnectedLayer.h
  runtime/onert/backend/ruy/ops/OperationUtils.h
  tests/nnfw_api/src/one_op_tests/FullyConnected.cc
Labels: area/onert

#5267 [onert] Remove redundant const init in cpu backend
  runtime/onert/backend/cpu/ConstantInitializer.cc
  runtime/onert/backend/cpu/ConstantInitializer.h
  runtime/onert/backend/xnnpack/ConstantInitializer.cc
  runtime/onert/backend/xnnpack/ConstantInitializer.h
Labels: PR/ready for review

#5283 [infra] Infra for clang-format-8 migration on each directory
  .clang-format.8
  infra/command/format
Labels: PR/ready for review

#5274 [onert] Pass TracingCtx to Executors and EventObserver
  runtime/onert/core/src/compiler/ExecutorFactory.cc
  runtime/onert/core/src/exec/DataflowExecutor.cc
  runtime/onert/core/src/exec/DataflowExecutor.h
  runtime/onert/core/src/exec/ExecutionObservers.cc
  runtime/onert/core/src/exec/ExecutionObservers.h
  runtime/onert/core/src/exec/ExecutorBase.cc
  runtime/onert/core/src/exec/ExecutorBase.h
  runtime/onert/core/src/exec/LinearExecutor.h
  runtime/onert/core/src/exec/ParallelExecutor.cc
  runtime/onert/core/src/exec/ParallelExecutor.h
  runtime/onert/core/src/util/EventCollector.h
Labels: PR/ready for review

#5280 [onert/cpu] Fix BackedContext getTensor bug
  runtime/onert/backend/cpu/BackendContext.cc
  runtime/onert/backend/ruy/BackendContext.cc
  runtime/onert/backend/xnnpack/BackendContext.cc
Labels: PR/ready for review

#5285 [luci] Remove unused header in CircleOperationExporter
  compiler/luci/export/src/CircleOperationExporter.cpp
Labels: trivial

#5287 [onert] Type validation check for EmbeddingLookup
  runtime/onert/core/src/ir/OperationValidator.cc
Labels: PR/ready for review, trivial

#5293 [tools] Update clang-format
  tools/.clang-format
  tools/kbenchmark/kernels/acl_cl/Convolution.cpp
  tools/kbenchmark/kernels/acl_cl/TransposeConv.cpp
  tools/kbenchmark/kernels/acl_neon/Convolution.cpp
  tools/kbenchmark/kernels/acl_neon/TransposeConv.cpp
  tools/tflite_accuracy/src/tflite_accuracy.cc
Labels: PR/ready for review, trivial

#5290 [runtime/contrib] Update clang-format
  runtime/contrib/.clang-format
  runtime/contrib/TFLiteSharp/TFLiteNative/include/tflite_log.h
  runtime/contrib/TFLiteSharp/TFLiteNative/include/tflite_nativewrapper.h
  runtime/contrib/android/api/src/main/native/onert-native-api.cpp
  runtime/contrib/android/api/src/main/native/onert-native-api.h
  runtime/contrib/android_benchmark_app/cpp/ndk_main.cpp
  runtime/contrib/android_tflite/builtin_ops_jni.cc
  runtime/contrib/heap_trace/src/cl_create_buffer_stub.cc
  runtime/contrib/heap_trace/src/memory_pool_for_symbol_searcher_internals.h
  runtime/contrib/heap_trace/src/trace.cc
  runtime/contrib/heap_trace/src/trace.h
  runtime/contrib/heap_trace/tests/src/cl_release_mem_object_interception_test.cc
  runtime/contrib/heap_trace/tests/src/malloc_interception_test.cc
  runtime/contrib/heap_trace/tests/src/realloc_interception_test.cc
  runtime/contrib/heap_trace/tests/src/symbol_searcher_test.cc
  runtime/contrib/heap_trace/tests/src/trace_test.cc
  runtime/contrib/labs/jniacl/src/jniacl_main.cc
  runtime/contrib/labs/opencl_test/src/opencl_test.cc
  runtime/contrib/labs/tflite_examples/src/conv.cpp
  runtime/contrib/style_transfer_app/src/bitmap_helper.cc
  runtime/contrib/style_transfer_app/src/jpeg_helper.cc
  runtime/contrib/style_transfer_app/src/style_transfer_app.cc
  runtime/contrib/tflite_classify/src/ImageClassifier.cc
  runtime/contrib/tflite_classify/src/InferenceInterface.cc
  runtime/contrib/tflite_classify/src/tflite_classify.cc
Labels: PR/ready for review, trivial

#5289 [compute/ruy] Update clang-format
  compute/ruy/.clang-format
  compute/ruy/include/ruy/RuySupport.h
  compute/ruy/include/ruy/Types.h
  compute/ruy/include/ruy/Utils.h
  compute/ruy/include/ruy/operation/Conv.h
Labels: PR/ready for review, trivial

#5294 [onert/libs] Update clang-format
  runtime/libs/.clang-format
  runtime/libs/benchmark/src/CsvWriter.cpp
  runtime/libs/benchmark/src/MemoryPoller.cpp
  runtime/libs/benchmark/src/Result.cpp
  runtime/libs/misc/include/misc/feature/Index.h
  runtime/libs/misc/include/misc/feature/Shape.h
  runtime/libs/misc/include/misc/kernel/Shape.h
  runtime/libs/misc/include/misc/tensor/Object.h
  runtime/libs/misc/include/misc/tensor/Zipper.h
  runtime/libs/misc/src/tensor/Comparator.cpp
  runtime/libs/nnapi/include/NeuralNetworksShim.h
  runtime/libs/nnapi/include/NeuralNetworksTypes.h
  runtime/libs/rua/dyn/src/DynamicBinder.cpp
  runtime/libs/tflite/include/tflite/Diff.h
  runtime/libs/tflite/include/tflite/RandomTestRunner.h
  runtime/libs/tflite/include/tflite/TensorLogger.h
  runtime/libs/tflite/src/Diff.cpp
  runtime/libs/tflite/src/RandomTestRunner.cpp
Labels: PR/ready for review, trivial

#5296 [onert] Make EventWriter work with multiple TracingObservers
  runtime/onert/core/src/exec/ExecutionObservers.cc
  runtime/onert/core/src/exec/ExecutionObservers.h
  runtime/onert/core/src/util/EventWriter.cc
  runtime/onert/core/src/util/EventWriter.h
Labels: PR/ready for review

#5299 [compute/cker] Update clang-format
  compute/cker/.clang-format
  compute/cker/include/cker/NeonTensorUtils.h
  compute/cker/include/cker/PortableTensorUtils.h
  compute/cker/include/cker/Types.h
  compute/cker/include/cker/Utils.h
  compute/cker/include/cker/eigen/EigenSupport.h
  compute/cker/include/cker/eigen/Utils.h
  compute/cker/include/cker/eigen/eigen_convolution_helpers.h
  compute/cker/include/cker/eigen/eigen_spatial_convolutions-inl.h
  compute/cker/include/cker/operation/AveragePool.h
  compute/cker/include/cker/operation/BatchToSpaceND.h
  compute/cker/include/cker/operation/BinaryArithmeticOps.h
  compute/cker/include/cker/operation/Common.h
  compute/cker/include/cker/operation/Comparison.h
  compute/cker/include/cker/operation/Concatenation.h
  compute/cker/include/cker/operation/DepthwiseConv.h
  compute/cker/include/cker/operation/Einsum.h
  compute/cker/include/cker/operation/FullyConnected.h
  compute/cker/include/cker/operation/FullyConnectedSparse16x1.h
  compute/cker/include/cker/operation/FusedBatchNorm.h
  compute/cker/include/cker/operation/Helper/BCast.h
  compute/cker/include/cker/operation/Helper/RandomDistributions.h
  compute/cker/include/cker/operation/Helper/RandomOpCpu.h
  compute/cker/include/cker/operation/Helper/Tensor.h
  compute/cker/include/cker/operation/InstanceNorm.h
  compute/cker/include/cker/operation/L2Normalize.h
  compute/cker/include/cker/operation/LSTM.h
  compute/cker/include/cker/operation/LogSoftMax.h
  compute/cker/include/cker/operation/MatrixBandPart.h
  compute/cker/include/cker/operation/MaxPool.h
  compute/cker/include/cker/operation/OneHot.h
  compute/cker/include/cker/operation/Range.h
  compute/cker/include/cker/operation/Reduce.h
  compute/cker/include/cker/operation/ReduceMean.h
  compute/cker/include/cker/operation/ResizeBilinear.h
  compute/cker/include/cker/operation/Select.h
  compute/cker/include/cker/operation/Slice.h
  compute/cker/include/cker/operation/SoftMax.h
  compute/cker/include/cker/operation/SpaceToBatchND.h
  compute/cker/include/cker/operation/StatelessRandomUniform.h
  compute/cker/include/cker/operation/Tile.h
  compute/cker/include/cker/operation/Transpose.h
  compute/cker/include/cker/operation/TransposeConv.h
  compute/cker/include/cker/operation/optimized/BinaryArithmeticOps.h
  compute/cker/include/cker/operation/optimized/Conv.h
  compute/cker/include/cker/operation/optimized/DepthwiseConvFloat.h
  compute/cker/include/cker/operation/optimized/DepthwiseConvUint8.h
  compute/cker/include/cker/operation/optimized/OptimizedUtils.h
  compute/cker/include/cker/operation/reference/BatchMatMul.h
  compute/cker/include/cker/operation/reference/BinaryArithmeticOps.h
  compute/cker/include/cker/operation/reference/Conv.h
  compute/cker/include/cker/ruy/RuySupport.h
Labels: PR/ready for review, trivial

#5300 [test/nnfw_api] Update clang-format
  tests/nnfw_api/.clang-format
  tests/nnfw_api/src/CircleGen.cc
  tests/nnfw_api/src/CircleGen.h
  tests/nnfw_api/src/GenModelTest.h
  tests/nnfw_api/src/NNPackages.cc
  tests/nnfw_api/src/RegressionTests.cc
  tests/nnfw_api/src/ValidationTestAddModelLoaded.cc
  tests/nnfw_api/src/ValidationTestAddSessionPrepared.cc
  tests/nnfw_api/src/ValidationTestMultipleSessions.cc
  tests/nnfw_api/src/ValidationTestSessionCreated.cc
  tests/nnfw_api/src/ValidationTestSingleSession.cc
  tests/nnfw_api/src/fixtures.h
  tests/nnfw_api/src/one_op_tests/ArgMinMax.cc
  tests/nnfw_api/src/one_op_tests/Cast.cc
  tests/nnfw_api/src/one_op_tests/Concat.cc
  tests/nnfw_api/src/one_op_tests/Conv2D.cc
  tests/nnfw_api/src/one_op_tests/DepthToSpace.cc
  tests/nnfw_api/src/one_op_tests/DepthwiseConv2D.cc
  tests/nnfw_api/src/one_op_tests/Elu.cc
  tests/nnfw_api/src/one_op_tests/Equal.cc
  tests/nnfw_api/src/one_op_tests/Fill.cc
  tests/nnfw_api/src/one_op_tests/FullyConnected.cc
  tests/nnfw_api/src/one_op_tests/L2Normalization.cc
  tests/nnfw_api/src/one_op_tests/LeakyRelu.cc
  tests/nnfw_api/src/one_op_tests/LogSoftmax.cc
  tests/nnfw_api/src/one_op_tests/OneHot.cc
  tests/nnfw_api/src/one_op_tests/Pad.cc
  tests/nnfw_api/src/one_op_tests/PadV2.cc
  tests/nnfw_api/src/one_op_tests/Rank.cc
  tests/nnfw_api/src/one_op_tests/ResizeBilinear.cc
  tests/nnfw_api/src/one_op_tests/ResizeNearestNeighbor.cc
  tests/nnfw_api/src/one_op_tests/Reverse.cc
  tests/nnfw_api/src/one_op_tests/Shape.cc
  tests/nnfw_api/src/one_op_tests/Split.cc
  tests/nnfw_api/src/one_op_tests/Sqrt.cc
  tests/nnfw_api/src/one_op_tests/Square.cc
  tests/nnfw_api/src/one_op_tests/Tile.cc
  tests/nnfw_api/src/one_op_tests/Transpose.cc
Labels: PR/ready for review, trivial

#5303 [onert] Rename nnfw_session::load_model_from_file()
  runtime/onert/api/src/nnfw_api.cc
  runtime/onert/api/src/nnfw_api_internal.cc
  runtime/onert/api/src/nnfw_api_internal.h
Labels: PR/ready for review

#5302 [onert] Update clang-format (except core and backend)
  runtime/onert/api/.clang-format
  runtime/onert/api/include/nnfw.h
  runtime/onert/api/src/CustomKernel.cc
  runtime/onert/api/src/nnfw_api_internal.cc
  runtime/onert/frontend/.clang-format
  runtime/onert/frontend/base_loader/include/base_loader.h
  runtime/onert/frontend/circle/src/circle_loader.cc
  runtime/onert/frontend/circle_schema/include/circle_schema_generated.h
  runtime/onert/frontend/nnapi/wrapper/ANeuralNetworksCompilation.cc
  runtime/onert/frontend/nnapi/wrapper/ANeuralNetworksEvent.cc
  runtime/onert/frontend/nnapi/wrapper/ANeuralNetworksExecution.cc
  runtime/onert/frontend/nnapi/wrapper/ANeuralNetworksExecution.h
  runtime/onert/frontend/nnapi/wrapper/ANeuralNetworksModel.cc
  runtime/onert/frontend/nnapi/wrapper/OperationFactory.cc
  runtime/onert/frontend/nnapi/wrapper/OperationFactory.h
  runtime/onert/frontend/tflite/src/tflite_schema_generated.h
  runtime/onert/sample/.clang-format
  runtime/onert/test/.clang-format
  runtime/onert/test/core/compiler/HEScheduler.cc
  runtime/onert/test/core/exec/ExecInstance.cc
  runtime/onert/test/core/interp/ExecManager.cc
  runtime/onert/test/graph/MockNode.h
  runtime/onert/test/graph/operand/UseDef.cc
  runtime/onert/test/util/ShapeInference.cc
Labels: PR/ready for review, trivial

#5309 [compute] Update clang-format
  compute/.clang-format
  compute/ARMComputeEx/.clang-format
  compute/cker/.clang-format
  compute/ruy/.clang-format
  compute/test/cker/Range.cc
Labels: PR/ready for review, trivial

#5310 [onert/test] Update clang-format
  tests/.clang-format
  tests/custom_op/FillFrom/FillFrom_runner.cc
  tests/nnfw_api/.clang-format
  tests/tools/nnpackage_run/src/allocation.h
  tests/tools/nnpackage_run/src/h5formatter.cc
  tests/tools/nnpackage_run/src/nnfw_util.cc
  tests/tools/nnpackage_run/src/nnpackage_run.cc
  tests/tools/nnpackage_run/src/randomgen.cc
  tests/tools/tflite_loader/src/tflite_loader.cc
  tests/tools/tflite_run/src/bin_image.cc
  tests/tools/tflite_run/src/tensor_loader.cc
  tests/tools/tflite_run/src/tflite_run.cc
  tests/tools/tflite_vanilla_run/src/tflite_vanilla_run.cc
Labels: PR/ready for review, trivial

#5306 [onert] ExpandDims allows int64 type axis value
  runtime/onert/backend/cpu/KernelGenerator.cc
  runtime/onert/backend/cpu/ops/ExpandDimsLayer.cc
  runtime/onert/backend/cpu/ops/ExpandDimsLayer.h
  runtime/onert/core/src/compiler/StaticShapeInferer.cc
  runtime/onert/core/src/exec/DynamicShapeInferer.cc
  runtime/onert/core/src/ir/OperationValidator.cc
  tests/nnfw_api/src/CircleGen.cc
  tests/nnfw_api/src/CircleGen.h
  tests/nnfw_api/src/GenModelTest.h
  tests/nnfw_api/src/one_op_tests/ExpandDims.cc
Labels: PR/ready for review

#5305 [doc] Update runtime supported operation
  docs/runtime/supported-operations-backend.md
Labels: PR/ready for review

#5291 [onert] Pass subgraph index to ExecutionObservers
  runtime/onert/api/src/nnfw_api_internal.cc
  runtime/onert/core/src/exec/DataflowExecutor.cc
  runtime/onert/core/src/exec/ExecutionObservee.cc
  runtime/onert/core/src/exec/ExecutionObservee.h
  runtime/onert/core/src/exec/ExecutionObservers.cc
  runtime/onert/core/src/exec/ExecutionObservers.h
  runtime/onert/core/src/exec/LinearExecutor.cc
  runtime/onert/core/src/exec/ParallelExecutor.cc
Labels: PR/ready for review

#5308 [onert] Fix wrong parameter in while dumper
  runtime/onert/core/src/ir/OperationDumper.cc
Labels: trivial

#5316 Fix defect 1217377: uninitialized members
  runtime/onert/core/src/util/EventCollector.h
Labels: type/release

#5253 [onert/test] TFlite model test support all input type
  tests/tools/tflite_loader/src/tflite_loader.cc
Labels: PR/ready for review

#5314 Bump to 1.13.0
  docs/conf.py
  packaging/nnfw.spec
  runtime/contrib/android/api/build.gradle
  runtime/onert/api/include/nnfw_version.h
Labels: PR/ready for review

#5320 [onert] Split EventWriter.cc into 4 files
  runtime/onert/core/src/util/ChromeTracingEventWriter.cc
  runtime/onert/core/src/util/EventWriter.cc
  runtime/onert/core/src/util/MDTableEventWriter.cc
  runtime/onert/core/src/util/SNPEEventWriter.cc
Labels: PR/ready for review

#5324 [release/1.12.0] [test/nnfw_api] Test: Workaround for TCM
  tests/nnfw_api/src/ValidationTestMultipleSessions.cc
Labels: PR/ready for review

#5327 [onert] Update clang-format
  runtime/.clang-format
  runtime/contrib/.clang-format
  runtime/libs/.clang-format
  runtime/nnapi-header/include/NeuralNetworksEx.h
  runtime/onert/api/.clang-format
  runtime/onert/backend/.clang-format
  runtime/onert/core/.clang-format
  runtime/onert/frontend/.clang-format
  runtime/onert/sample/.clang-format
  runtime/onert/test/.clang-format
Labels: PR/ready for review, trivial

#5328 [onert] Fix namespace comment
  runtime/onert/backend/acl_neon/BackendContext.cc
  runtime/onert/backend/cpu/ops/ArgMinMaxLayer.cc
  runtime/onert/backend/cpu/ops/LSTMLayer.cc
  runtime/onert/backend/ruy/Config.cc
  runtime/onert/backend/xnnpack/Config.cc
  runtime/onert/core/include/exec/IExecutor.h
  runtime/onert/core/src/backend/cpu_common/Tensor.cc
  runtime/onert/core/src/compiler/pass/Pass.h
  runtime/onert/core/src/ir/OpSequence.cc
  runtime/onert/core/src/ir/OperationValidator.cc
Labels: PR/ready for review, trivial

#5342 [one-cmds] add command option to one-codegen
  compiler/one-cmds/one-codegen
Labels: PR/ready for review, Urgent, type/release

#5341 [one-cmds] add command option to one-codegen
  compiler/one-cmds/one-codegen
Labels: PR/ready for review

#5325 [test/nnfw_api] Test: Workaround for TCM
  tests/nnfw_api/src/ValidationTestMultipleSessions.cc
Labels: PR/ready for review

#5348 [tflchef] Add BidirectionalSequenceLSTM Operation
  compiler/tflchef/core/src/Op/BidirectionalSequenceLSTM.cpp
  compiler/tflchef/core/src/Op/BidirectionalSequenceLSTM.h
  compiler/tflchef/core/src/OpChef.def
  compiler/tflchef/core/src/OpChefs.h
  compiler/tflchef/proto/tflchef.proto
  compiler/tflchef/tflite/src/Op/BidirectionalSequenceLSTM.cpp
  compiler/tflchef/tflite/src/Op/BidirectionalSequenceLSTM.h
  compiler/tflchef/tflite/src/TFliteOpChefs.h
  compiler/tflchef/tflite/src/TFliteOpRegistry.h
Labels: PR/ready for review

#5367 [bino] Update clang-format version
  compiler/bino/.clang-format
  compiler/bino/include/bino.h
Labels: PR/ready for review

#5369 [circlechef] Update clang-format version
  compiler/circlechef/.clang-format
  compiler/circlechef/core/src/ModelChef.cpp
  compiler/circlechef/core/src/Op/BCQFullyConnected.cpp
  compiler/circlechef/core/src/Op/BCQGather.cpp
  compiler/circlechef/core/src/Op/BatchMatMul.cpp
  compiler/circlechef/tools/file/Driver.cpp
  compiler/circlechef/tools/reverse/Driver.cpp
Labels: PR/ready for review

#5368 [circle2circle] Update clang-format version
  compiler/circle2circle/.clang-format
  compiler/circle2circle/src/Circle2Circle.cpp
  compiler/circle2circle/src/TestHelper.h
Labels: PR/ready for review

#5365 [angkor] Update clang-format version
  compiler/angkor/.clang-format
  compiler/angkor/include/nncc/core/ADT/feature/Overlay.h
  compiler/angkor/include/nncc/core/ADT/feature/Shape.h
  compiler/angkor/include/nncc/core/ADT/kernel/Overlay.h
  compiler/angkor/include/nncc/core/ADT/kernel/Shape.h
  compiler/angkor/include/nncc/core/ADT/tensor/Overlay.h
  compiler/angkor/include/nncc/core/ADT/tensor/View.h
  compiler/angkor/src/ADT/feature/Overlay.test.cpp
  compiler/angkor/src/ADT/kernel/Overlay.test.cpp
  compiler/angkor/src/ADT/tensor/Overlay.test.cpp
Labels: PR/ready for review

#5373 [circle-quantizer] Update clang-format version
  compiler/circle-quantizer/.clang-format
  compiler/circle-quantizer/src/CircleQuantizer.cpp
Labels: PR/ready for review

#5372 [circle-inspect] Update clang-format version
  compiler/circle-inspect/.clang-format
  compiler/circle-inspect/driver/Driver.cpp
Labels: PR/ready for review

#5371 [circledump] Update clang-format version
  compiler/circledump/.clang-format
  compiler/circledump/src/OpPrinter.cpp
Labels: PR/ready for review

#5366 [arser] Update clang-format version
  compiler/arser/.clang-format
  compiler/arser/include/arser/arser.h
  compiler/arser/tests/arser.test.cpp
Labels: PR/ready for review

#5377 [circle-tensordump] Update clang-format version
  compiler/circle-tensordump/.clang-format
  compiler/circle-tensordump/driver/Driver.cpp
  compiler/circle-tensordump/src/Dump.cpp
Labels: PR/ready for review

#5378 [coco] Update clang-format version
  compiler/coco/.clang-format
  compiler/coco/core/include/coco/IR/FeatureShape.h
  compiler/coco/core/include/coco/IR/Locatable.h
  compiler/coco/core/include/coco/IR/Ops.h
  compiler/coco/core/include/coco/IR/Padding2D.h
  compiler/coco/core/src/ADT/PtrList.test.cpp
  compiler/coco/core/src/ADT/PtrManager.test.cpp
  compiler/coco/generic/src/IR/Data.cpp
Labels: PR/ready for review

#5380 [cwrap] Update clang-format version
  compiler/cwrap/.clang-format
  compiler/cwrap/src/Fildes.test.cpp
Labels: PR/ready for review, trivial

#5379 [common-artifacts] Update clang-format version
  compiler/common-artifacts/.clang-format
  compiler/common-artifacts/src/TestDataGenerator.cpp
Labels: PR/ready for review

#5381 [one-cmds] fix one-build bug
  compiler/one-cmds/one-build
  compiler/one-cmds/tests/one-build_003.cfg
  compiler/one-cmds/tests/one-build_003.test
Labels: PR/ready for review

#5374 [one-cmds] fix one-build bug
  compiler/one-cmds/one-build
  compiler/one-cmds/tests/one-build_003.cfg
  compiler/one-cmds/tests/one-build_003.test
Labels: PR/ready for review

#5382 [release] 1.12.1 compiler release note
  docs/release/1.12/release-note-1.12.1.md
Labels: PR/ready for review

#5383 [enco] Update clang-format version
  compiler/enco/.clang-format
  compiler/enco/core/src/ANN/Binder.h
  compiler/enco/core/src/ANN/Context.test.cpp
  compiler/enco/core/src/ANN/IR/Operation.h
  compiler/enco/core/src/AsmCode.h
  compiler/enco/core/src/Backend.cpp
  compiler/enco/core/src/CodeIndex.h
  compiler/enco/core/src/CppGen/Host.cpp
  compiler/enco/core/src/CppGen/Subnet.cpp
  compiler/enco/core/src/Support/Debugging.cpp
  compiler/enco/core/src/Transforms/Split.cpp
  compiler/enco/core/src/Transforms/Split.h
  compiler/enco/frontend/caffe/src/Context.h
  compiler/enco/frontend/caffe/src/Layer/Convolution.cpp
  compiler/enco/frontend/tflite/src/Context.cpp
  compiler/enco/frontend/tflite/src/Context.h
  compiler/enco/frontend/tflite/src/GraphBuilderRegistry.h
  compiler/enco/frontend/tflite/src/Op/AveragePool2D.cpp
  compiler/enco/frontend/tflite/src/Op/Conv2D.cpp
  compiler/enco/frontend/tflite/src/Op/DepthwiseConv2D.cpp
  compiler/enco/frontend/tflite/src/Op/MaxPool2D.cpp
Labels: PR/ready for review

#5384 [exo] Update clang-format version
  compiler/exo/.clang-format
  compiler/exo/src/Circle/CircleExporterImpl.cpp
  compiler/exo/src/Circle/CircleExporterUtils.cpp
  compiler/exo/src/Circle/CircleOperationExporter.cpp
  compiler/exo/src/Conversion/DepthwiseConv2DConverter.cpp
  compiler/exo/src/Dialect/IR/CircleNodes.h
  compiler/exo/src/Dialect/IR/TFLNodes.h
  compiler/exo/src/Dialect/Service/TFLShapeInferenceRule.test.cpp
  compiler/exo/src/GraphBlock.h
  compiler/exo/src/LoggingContext.cpp
  compiler/exo/src/Pass/FoldTransposeOfConstPass.cpp
  compiler/exo/src/Pass/FuseBiasAddPass.cpp
  compiler/exo/src/Pass/FuseInstanceNormPass.cpp
  compiler/exo/src/Pass/FuseReluPass.test.cpp
  compiler/exo/src/Pass/MergeConcatNodesPass.cpp
  compiler/exo/src/Pass/ShapeInferencePass.cpp
  compiler/exo/src/Pass/TypeInferencePass.cpp
  compiler/exo/src/ProgressReporter.h
  compiler/exo/src/TFLite/TFLExporterImpl.cpp
  compiler/exo/src/TFLite/TFLExporterImpl.test.cpp
  compiler/exo/src/TFLite/TFLExporterUtils.cpp
  compiler/exo/src/TFLite/TFLOperationExporter.cpp
  compiler/exo/src/TFLite/TFLTensorExporter.cpp
  compiler/exo/src/TestGraph.h
Labels: PR/ready for review

#5386 [locoex-customop] Update clang-format version
  compiler/locoex-customop/.clang-format
  compiler/locoex-customop/src/COpCall.cpp
  compiler/locoex-customop/src/VariadicArityNode.test.cpp
Labels: PR/ready for review

#5388 [locomotiv] Update clang-format version
  compiler/locomotiv/.clang-format
  compiler/locomotiv/include/locomotiv/Session.h
  compiler/locomotiv/src/Node/AvgPool2D.cpp
  compiler/locomotiv/src/Node/AvgPool2D.test.cpp
  compiler/locomotiv/src/Node/BiasAdd.cpp
  compiler/locomotiv/src/Node/Conv2D.cpp
  compiler/locomotiv/src/Node/Conv2D.test.cpp
  compiler/locomotiv/src/Node/DepthwiseConv2D.cpp
  compiler/locomotiv/src/Node/DepthwiseConv2D.test.cpp
  compiler/locomotiv/src/Node/DepthwiseFilterEncode.cpp
  compiler/locomotiv/src/Node/DepthwiseFilterEncode.test.cpp
  compiler/locomotiv/src/Node/FeatureCodec.test.cpp
  compiler/locomotiv/src/Node/FeatureDecode.cpp
  compiler/locomotiv/src/Node/FeatureEncode.cpp
  compiler/locomotiv/src/Node/FilterEncode.cpp
  compiler/locomotiv/src/Node/FilterEncode.test.cpp
  compiler/locomotiv/src/Node/MatrixCodec.test.cpp
  compiler/locomotiv/src/Node/MatrixDecode.cpp
  compiler/locomotiv/src/Node/MatrixEncode.cpp
  compiler/locomotiv/src/Node/MaxPool2D.cpp
  compiler/locomotiv/src/Node/MaxPool2D.test.cpp
  compiler/locomotiv/src/Node/TensorConcat.cpp
  compiler/locomotiv/src/Node/TransposedConv2D.cpp
  compiler/locomotiv/src/Node/TransposedConv2D.test.cpp
  compiler/locomotiv/src/NodeExecution.h
Labels: PR/ready for review

#5389 [locop] Update clang-format version
  compiler/locop/.clang-format
  compiler/locop/src/FormattedTensorShape.cpp
  compiler/locop/src/NodeSummary.cpp
Labels: PR/ready for review

#5390 [logo] Update clang-format version
  compiler/logo/.clang-format
  compiler/logo/src/Passes/ConstantFoldingPass.cpp
  compiler/logo/src/Passes/SimplifyDomainConversionPass.cpp
Labels: PR/ready for review

#5385 [loco] Update clang-format version
  compiler/loco/.clang-format
  compiler/loco/include/loco/IR/Nodes.h
  compiler/loco/include/loco/IR/Padding2D.h
  compiler/loco/src/IR/Graph.test.cpp
  compiler/loco/src/Service/CanonicalShapeInferenceRule.cpp
  compiler/loco/src/Service/GraphBuilder.h
  compiler/loco/src/Service/GraphTestcase.h
  compiler/loco/src/Service/MultiDialectShapeInferenceRule.test.cpp
  compiler/loco/src/Service/TypeInference.test.cpp
  compiler/loco/src/tensorflow.test.cpp
Labels: PR/ready for review

#5392 [luci-value-test] Update clang-format version
  compiler/luci-value-test/.clang-format
  compiler/luci-value-test/tester/src/EvalTester.cpp
Labels: PR/ready for review

#5399 [moco-tf] Update clang-format version
  compiler/moco-tf/.clang-format
  compiler/moco-tf/src/BroadcastHelper.h
  compiler/moco-tf/src/Canonicalization/Conv2DBackpropInputCanonicalizer.cpp
  compiler/moco-tf/src/Canonicalization/DepthwiseConv2dNativeCanonicalizer.cpp
  compiler/moco-tf/src/Canonicalization/SoftmaxCanonicalizer.cpp
  compiler/moco-tf/src/Canonicalization/SoftmaxCanonicalizer.h
  compiler/moco-tf/src/Canonicalization/StopGradientCanonicalizer.cpp
  compiler/moco-tf/src/Canonicalization/StopGradientCanonicalizer.h
  compiler/moco-tf/src/Frontend.cpp
  compiler/moco-tf/src/Knob.cpp
  compiler/moco-tf/src/Op/COpCall.cpp
  compiler/moco-tf/src/Op/COpCall.h
  compiler/moco-tf/src/ProgressReporter.h
  compiler/moco-tf/src/Transforms/ShapeInferencePass.cpp
  compiler/moco-tf/src/Transforms/TypeInferencePass.cpp
Labels: PR/ready for review

#5405 [onert] Remove redundant include
  runtime/onert/core/include/backend/cpu_common/ConstantInitializerBase.h
Labels: trivial

#5403 [nest] Update clang-format version
  compiler/nest/.clang-format
  compiler/nest/core/include/nest/expr/AddNode.h
  compiler/nest/core/include/nest/expr/DerefNode.h
  compiler/nest/core/include/nest/expr/MulNode.h
  compiler/nest/core/src/Block.test.cpp
  compiler/nest/core/src/Closure.test.cpp
  compiler/nest/core/src/Expr.test.cpp
  compiler/nest/core/src/Ret.test.cpp
  compiler/nest/core/src/expr/AddNode.test.cpp
  compiler/nest/core/src/expr/DerefNode.test.cpp
  compiler/nest/core/src/expr/MulNode.test.cpp
  compiler/nest/core/src/stmt/PushNode.test.cpp
Labels: PR/ready for review

#5402 [moco] Update clang-format version
  compiler/moco/.clang-format
  compiler/moco/import/include/moco/Import/GraphBuilderContext.h
  compiler/moco/import/include/moco/Import/GraphBuilderRegistry.h
  compiler/moco/import/include/moco/Import/Nodes/Softmax.h
  compiler/moco/import/src/Nodes/AvgPool.cpp
  compiler/moco/import/src/Nodes/BiasAdd.cpp
  compiler/moco/import/src/Nodes/Concat.cpp
  compiler/moco/import/src/Nodes/Const.cpp
  compiler/moco/import/src/Nodes/Conv2DBackpropInput.cpp
  compiler/moco/import/src/Nodes/DepthwiseConv2dNative.cpp
  compiler/moco/import/src/Nodes/FakeQuantWithMinMaxVars.cpp
  compiler/moco/import/src/Nodes/FusedBatchNorm.cpp
  compiler/moco/import/src/Nodes/Identity.cpp
  compiler/moco/import/src/Nodes/MaxPool.cpp
  compiler/moco/import/src/Nodes/Mean.cpp
  compiler/moco/import/src/Nodes/Rsqrt.cpp
  compiler/moco/import/src/Nodes/Shape.cpp
  compiler/moco/import/src/Nodes/Softmax.cpp
  compiler/moco/import/src/Nodes/SquaredDifference.cpp
  compiler/moco/import/src/Nodes/Squeeze.cpp
  compiler/moco/import/src/Nodes/StopGradient.cpp
  compiler/moco/import/src/Nodes/StridedSlice.cpp
  compiler/moco/lang/include/moco/IR/Nodes/TFConv2DBackpropInput.h
  compiler/moco/lang/include/moco/IR/Nodes/TFDepthwiseConv2dNative.h
  compiler/moco/lang/include/moco/IR/Nodes/TFFakeQuantWithMinMaxVars.h
  compiler/moco/pass/include/moco/Pass/Passes/ConstantFoldMul.h
  compiler/moco/pass/include/moco/Pass/Passes/ConstantFoldPack.h
  compiler/moco/pass/include/moco/Pass/Passes/ConstantFoldStridedSlice.h
  compiler/moco/pass/include/moco/Pass/Passes/FuseBinaryIntoPreceding.h
  compiler/moco/pass/include/moco/Pass/Passes/ResolveFusedBatchNorm.h
  compiler/moco/pass/src/ConstantFoldHelper.cpp
  compiler/moco/pass/src/Passes/FuseBinaryIntoPreceding.cpp
  compiler/moco/service/src/Service/TFShapeInferenceRule.cpp
  compiler/moco/support/include/moco/Support/TFShapeInferenceHelper.h
Labels: PR/ready for review

#5407 [nnkit-inf] Update clang-format version
  compiler/nnkit-intf/.clang-format
  compiler/nnkit-intf/tensor/include/nnkit/TensorContext.h
Labels: PR/ready for review

#5409 [nnkit-mocotf] Update clang-format version
  compiler/nnkit-mocotf/.clang-format
  compiler/nnkit-mocotf/support/src/InputTensorContext.cpp
  compiler/nnkit-mocotf/support/src/InputTensorContext.h
  compiler/nnkit-mocotf/support/src/OutputTensorContext.cpp
  compiler/nnkit-mocotf/support/src/OutputTensorContext.h
Labels: PR/ready for review

#5411 [nnkit-onnxrt] Update clang-format version
  compiler/nnkit-onnxrt/.clang-format
  compiler/nnkit-onnxrt/support/include/nnkit/support/onnx/TensorSet.h
Labels: PR/ready for review

#5412 [nnkit-tflite] Update clang-format version
  compiler/nnkit-tflite/.clang-format
  compiler/nnkit-tflite/backend/Backend.cpp
Labels: PR/ready for review

#5415 [nnsuite] Update clang-format version
  compiler/nnsuite/.clang-format
  compiler/nnsuite/conv/model/src/RandomModel.cpp
  compiler/nnsuite/conv/nnkit-caffe/ConvBackend.test.cpp
  compiler/nnsuite/conv/nnkit-tflite/ConvBackend.cpp
  compiler/nnsuite/conv/nnkit-tflite/ConvBackend.test.cpp
Labels: PR/ready for review

#5414 [nnop] Update clang-format version
  compiler/nnop/.clang-format
  compiler/nnop/include/nnop/PadInfo.h
  compiler/nnop/include/nnop/StrideInfo.h
Labels: PR/ready for review

#5413 [nnkit-tf] Update clang-format version
  compiler/nnkit-tf/.clang-format
  compiler/nnkit-tf/support/include/nnkit/support/tf/TensorContext.h
  compiler/nnkit-tf/support/include/nnkit/support/tf/TensorDataMap.h
  compiler/nnkit-tf/support/src/Backend.cpp
  compiler/nnkit-tf/support/src/Runner.cpp
Labels: PR/ready for review

#5404 [nnc] Update clang-format version
  compiler/nnc/.clang-format
  compiler/nnc/backends/acl_soft_backend/AclCppGenerator.cpp
  compiler/nnc/backends/acl_soft_backend/AclCppOpGenerator.cpp
  compiler/nnc/backends/acl_soft_backend/ArtifactModel.cpp
  compiler/nnc/backends/acl_soft_backend/ArtifactModel.h
  compiler/nnc/backends/interpreter/InterpreterBackend.cpp
  compiler/nnc/backends/soft_backend/CPPGenerator.cpp
  compiler/nnc/backends/soft_backend/ModelAnalyzer.cpp
  compiler/nnc/backends/soft_backend/ModelAnalyzer.h
  compiler/nnc/backends/soft_backend/SequencedIR.h
  compiler/nnc/driver/Options.cpp
  compiler/nnc/include/pass/PassData.h
  compiler/nnc/include/passes/optimizations/CombineTransposes.h
  compiler/nnc/include/passes/optimizations/OptimizationUtils.h
  compiler/nnc/include/support/CommandLine.h
  compiler/nnc/passes/optimizations/CombineTransposes.cpp
  compiler/nnc/passes/optimizations/DeadCodeElimination.cpp
  compiler/nnc/passes/optimizations/FuseArithmeticOps.cpp
  compiler/nnc/passes/transformations/DataFormatSwitcher.cpp
  compiler/nnc/passes/transformations/LowerConv2D.cpp
  compiler/nnc/tests/acl_soft_backend/AclCppOperations.cpp
  compiler/nnc/tests/acl_soft_backend/artifact_cmake/main.cpp
  compiler/nnc/tests/soft_backend/CompileCPP.cpp
  compiler/nnc/unittests/acl_backend/DOMToText.cpp
  compiler/nnc/unittests/acl_backend/MIRToDOM.cpp
  compiler/nnc/unittests/optimizations/SinkTest.cpp
  compiler/nnc/unittests/soft_backend/CPPOperations.cpp
  compiler/nnc/unittests/support/CommandLineTest.cpp
  compiler/nnc/unittests/transformations/Switcher.cpp
Labels: PR/ready for review

#5397 [mir2loco] Update clang-format version
  compiler/mir2loco/.clang-format
  compiler/mir2loco/src/mir2loco.test.cpp
Labels: PR/ready for review

#5396 [mir-interpreter] Update clang-format version
  compiler/mir-interpreter/.clang-format
  compiler/mir-interpreter/src/ops/Add.cpp
  compiler/mir-interpreter/src/ops/AvgPool2D.cpp
  compiler/mir-interpreter/src/ops/CappedReLU.cpp
  compiler/mir-interpreter/src/ops/Concat.cpp
  compiler/mir-interpreter/src/ops/Conv2D.cpp
  compiler/mir-interpreter/src/ops/DeConv2D.cpp
  compiler/mir-interpreter/src/ops/Gather.cpp
  compiler/mir-interpreter/src/ops/MaxPool2D.cpp
  compiler/mir-interpreter/src/ops/QuantizationHelpers.h
  compiler/mir-interpreter/src/ops/Softmax.cpp
Labels: PR/ready for review

#5395 [mir] Update clang-format version
  compiler/mir/.clang-format
  compiler/mir/include/mir/Quantization.h
  compiler/mir/include/mir/ShapeRange.h
  compiler/mir/include/mir/TensorType.h
  compiler/mir/include/mir/ops/AvgPool2DOp.h
  compiler/mir/include/mir/ops/ConcatOp.h
  compiler/mir/include/mir/ops/Conv2DOp.h
  compiler/mir/include/mir/ops/Deconv2DOp.h
  compiler/mir/include/mir/ops/DepthwiseConv2DOp.h
  compiler/mir/include/mir/ops/FullyConnectedOp.h
  compiler/mir/include/mir/ops/GatherOp.h
  compiler/mir/include/mir/ops/MaxPool2DOp.h
  compiler/mir/include/mir/ops/PadOp.h
  compiler/mir/include/mir/ops/ReduceMeanOp.h
  compiler/mir/include/mir/ops/ReduceOp.h
  compiler/mir/include/mir/ops/ResizeOp.h
  compiler/mir/include/mir/ops/SliceOp.h
  compiler/mir/include/mir/ops/SqueezeOp.h
  compiler/mir/src/Graph.cpp
  compiler/mir/src/Operation.cpp
  compiler/mir/src/Shape.cpp
  compiler/mir/src/TensorVariant.cpp
  compiler/mir/src/mir_caffe2_importer/caffe2_importer.cpp
  compiler/mir/src/mir_caffe2_importer/caffe2_op_creator.cpp
  compiler/mir/src/mir_caffe_importer/caffe_importer.cpp
  compiler/mir/src/mir_caffe_importer/caffe_op_creator.cpp
  compiler/mir/src/mir_onnx_importer/AttributeHelpers.h
  compiler/mir/src/mir_onnx_importer/ConvPoolHelpers.cpp
  compiler/mir/src/mir_onnx_importer/ONNXHelpers.cpp
  compiler/mir/src/mir_onnx_importer/ONNXImporterImpl.cpp
  compiler/mir/src/mir_onnx_importer/ONNXNodeConverterRegistry.cpp
  compiler/mir/src/mir_onnx_importer/Op/AveragePool.cpp
  compiler/mir/src/mir_onnx_importer/Op/BatchNormalization.cpp
  compiler/mir/src/mir_onnx_importer/Op/Conv.cpp
  compiler/mir/src/mir_onnx_importer/Op/ConvTranspose.cpp
  compiler/mir/src/mir_onnx_importer/Op/MaxPool.cpp
  compiler/mir/src/mir_onnx_importer/Op/ReduceMean.cpp
  compiler/mir/src/mir_onnx_importer/Op/Upsample.cpp
  compiler/mir/src/mir_tflite_importer/tflite_importer.cpp
  compiler/mir/src/mir_tflite_importer/tflite_op_creator.cpp
  compiler/mir/src/ops/AvgPool2DOp.cpp
  compiler/mir/src/ops/Conv2DOp.cpp
  compiler/mir/src/ops/DeConv2DOp.cpp
  compiler/mir/src/ops/DepthwiseConv2DOp.cpp
  compiler/mir/src/ops/MaxPool2DOp.cpp
  compiler/mir/src/ops/PadOp.cpp
  compiler/mir/src/ops/TransposeOp.cpp
  compiler/mir/unittests/ShapeInference.cpp
  compiler/mir/unittests/ShapeRange.cpp
Labels: PR/ready for review

#4948 [luci-interpreter] Support PReLU with channel-wise quantization
  compiler/luci-interpreter/src/kernels/Prelu.cpp
  compiler/luci-interpreter/src/kernels/Prelu.h
  compiler/luci-interpreter/src/kernels/Prelu.test.cpp
  compiler/luci-interpreter/src/kernels/Utils.h
Labels: PR/ready for review

#5419 [oneco] Update clang-format version
  compiler/oneco/.clang-format
  compiler/oneco/src/GraphBuilder.h
  compiler/oneco/src/GraphBuilderContext.h
  compiler/oneco/src/GraphBuilderRegistry.h
  compiler/oneco/src/Op/Constant.h
  compiler/oneco/src/Op/Identity.h
Labels: PR/ready for review

#5422 [plier-tf] Update clang-format version
  compiler/plier-tf/.clang-format
  compiler/plier-tf/src/TestHelper.cpp
Labels: PR/ready for review

#5420 [oops] Update clang-format version
  compiler/oops/.clang-format
  compiler/oops/include/oops/InternalExn.h
  compiler/oops/include/oops/UserExn.h
Labels: PR/ready for review

#5421 [pepper-str] Update clang-format version
  compiler/pepper-str/.clang-format
  compiler/pepper-str/include/pepper/str.h
Labels: PR/ready for review

#5423 [record-minmax] Update clang-format version
  compiler/record-minmax/.clang-format
  compiler/record-minmax/driver/Driver.cpp
  compiler/record-minmax/include/RecordFunction.h
Labels: PR/ready for review

#5428 [tfinfo-v2] Update clang-format version
  compiler/tfinfo-v2/.clang-format
  compiler/tfinfo-v2/include/tfinfo-v2/TensorSignature.h
  compiler/tfinfo-v2/src/TFInfo_v2.test.cpp
  compiler/tfinfo-v2/src/TensorInfoLoader.cpp
Labels: PR/ready for review

#5429 [tfkit] Update clang-format version
  compiler/tfkit/.clang-format
  compiler/tfkit/src/PackCommand.cpp
  compiler/tfkit/src/Support.hpp
  compiler/tfkit/src/UnpackCommand.cpp
Labels: PR/ready for review

#5430 [tfl-inspect] Update clang-format version
  compiler/tfl-inspect/.clang-format
  compiler/tfl-inspect/driver/Driver.cpp
Labels: PR/ready for review

#5431 [tflchef] Update clang-format version
  compiler/tflchef/.clang-format
  compiler/tflchef/core/src/ModelChef.cpp
  compiler/tflchef/core/src/Op/BidirectionalSequenceLSTM.cpp
  compiler/tflchef/core/src/Op/BidirectionalSequenceLSTM.h
  compiler/tflchef/core/src/Op/LocalResponseNormalization.h
  compiler/tflchef/core/src/Op/Squeeze.cpp
  compiler/tflchef/core/src/Op/StridedSlice.cpp
  compiler/tflchef/core/src/Op/UnidirectionalSequenceLSTM.cpp
  compiler/tflchef/core/src/Op/UnidirectionalSequenceLSTM.h
  compiler/tflchef/tools/file/Driver.cpp
  compiler/tflchef/tools/reverse/Driver.cpp
Labels: PR/ready for review

#5427 [one-cmds] Add comments to one-build test
  compiler/one-cmds/tests/one-build_001.test
  compiler/one-cmds/tests/one-build_002.test
  compiler/one-cmds/tests/one-build_003.test
Labels: PR/ready for review

#5434 [tflit2circle] Update clang-format version
  compiler/tflite2circle/.clang-format
  compiler/tflite2circle/driver/Driver.cpp
  compiler/tflite2circle/src/BuildBuiltinOptions/AddOptions.cpp
  compiler/tflite2circle/src/BuildBuiltinOptions/ArgMaxOptions.cpp
  compiler/tflite2circle/src/BuildBuiltinOptions/ArgMinOptions.cpp
  compiler/tflite2circle/src/BuildBuiltinOptions/CastOptions.cpp
  compiler/tflite2circle/src/BuildBuiltinOptions/ConcatenationOptions.cpp
  compiler/tflite2circle/src/BuildBuiltinOptions/Conv2DOptions.cpp
  compiler/tflite2circle/src/BuildBuiltinOptions/DepthwiseConv2DOptions.cpp
  compiler/tflite2circle/src/BuildBuiltinOptions/DivOptions.cpp
  compiler/tflite2circle/src/BuildBuiltinOptions/FullyConnectedOptions.cpp
  compiler/tflite2circle/src/BuildBuiltinOptions/L2NormalizeOptions.cpp
  compiler/tflite2circle/src/BuildBuiltinOptions/MulOptions.cpp
  compiler/tflite2circle/src/BuildBuiltinOptions/Pool2DOptions.cpp
  compiler/tflite2circle/src/BuildBuiltinOptions/SubOptions.cpp
  compiler/tflite2circle/src/BuildBuiltinOptions/UnidirectionalSequenceLSTMOptions.cpp
  compiler/tflite2circle/src/BuildBuiltinOptions/UniqueOptions.cpp
  compiler/tflite2circle/src/CircleModel.cpp
  compiler/tflite2circle/src/DataLookup.cpp
  compiler/tflite2circle/src/DataLookup.h
Labels: PR/ready for review

#5433 [tfldump] Update clang-format version
  compiler/tfldump/.clang-format
  compiler/tfldump/src/OpPrinter.cpp
Labels: PR/ready for review

#5432 [tfinfo] Update clang-format version
  compiler/tfinfo/.clang-format
  compiler/tfinfo/include/nnkit/support/tftestinfo/ParsedTensor.h
Labels: PR/ready for review

#5408 [nnkit] Update clang-format version
  compiler/nnkit/.clang-format
  compiler/nnkit/actions/HDF5/Export.cpp
  compiler/nnkit/tools/run/nnkit-run.cpp
Labels: PR/ready for review

#5439 [infra] Use clang-format-8 as default
  infra/command/format
Labels: PR/ready for review

#5455 [runtime] Remove clang-format style file symbolic link
  .clang-format
  compute/.clang-format
  runtime/.clang-format
  tests/.clang-format
  tools/.clang-format
Labels: PR/ready for review

#5459 [cker] Update quantization softmax kernel
  compute/cker/include/cker/Types.h
  compute/cker/include/cker/Utils.h
  compute/cker/include/cker/operation/SoftMax.h
  runtime/onert/backend/cpu/ops/SoftMaxLayer.cc
  runtime/onert/backend/cpu/ops/SoftMaxLayer.h
Labels: PR/ready for review

#5450 [onert] Release freed weight of fullyconnected layer immediately
  runtime/onert/backend/cpu/ops/FullyConnectedLayer.cc
Labels: PR/ready for review

#5467 [cker] Remove duplicated function
  compute/cker/include/cker/operation/Quantize.h
Labels: PR/ready for review

#5463 [onert] Support cpu backend ResizeBilinear int8 datatype
  compute/cker/include/cker/operation/ResizeBilinear.h
  runtime/onert/backend/cpu/ops/ResizeBilinearLayer.cc
  tests/nnfw_api/src/one_op_tests/ResizeBilinear.cc
Labels: PR/ready for review

#5471 [onert] Remove redundant check in `initConsts`
  runtime/onert/core/include/backend/cpu_common/BackendContextHelpers.h
Labels: trivial

#5468 [compiler] Remove symbolic link clang format style files
  compiler/angkor/.clang-format
  compiler/arser/.clang-format
  compiler/bino/.clang-format
  compiler/circle-inspect/.clang-format
  compiler/circle-quantizer/.clang-format
  compiler/circle-tensordump/.clang-format
  compiler/circle2circle/.clang-format
  compiler/circlechef/.clang-format
  compiler/circledump/.clang-format
  compiler/coco/.clang-format
  compiler/common-artifacts/.clang-format
  compiler/cwrap/.clang-format
  compiler/enco/.clang-format
  compiler/exo/.clang-format
  compiler/loco/.clang-format
  compiler/locoex-customop/.clang-format
  compiler/locomotiv/.clang-format
  compiler/locop/.clang-format
  compiler/logo/.clang-format
  compiler/luci-interpreter/.clang-format
  compiler/luci-value-test/.clang-format
  compiler/luci/.clang-format
  compiler/mir-interpreter/.clang-format
  compiler/mir/.clang-format
  compiler/mir2loco/.clang-format
  compiler/moco-tf/.clang-format
  compiler/moco/.clang-format
  compiler/nest/.clang-format
  compiler/nnc/.clang-format
  compiler/nnkit-intf/.clang-format
  compiler/nnkit-mocotf/.clang-format
  compiler/nnkit-onnxrt/.clang-format
  compiler/nnkit-tf/.clang-format
  compiler/nnkit-tflite/.clang-format
  compiler/nnkit/.clang-format
  compiler/nnop/.clang-format
  compiler/nnsuite/.clang-format
  compiler/oneco/.clang-format
  compiler/oops/.clang-format
  compiler/pepper-str/.clang-format
  compiler/plier-tf/.clang-format
  compiler/record-minmax/.clang-format
  compiler/tfinfo-v2/.clang-format
  compiler/tfinfo/.clang-format
  compiler/tfkit/.clang-format
  compiler/tfl-inspect/.clang-format
  compiler/tflchef/.clang-format
  compiler/tfldump/.clang-format
  compiler/tflite2circle/.clang-format
Labels: PR/ready for review

#5441 [tflite2circle] Add BidirectionalSequenceLSTM operator
  compiler/tflite2circle/src/BuildBuiltinOptions.h
  compiler/tflite2circle/src/BuildBuiltinOptions/BidirectionalSequenceLSTMOptions.cpp
  compiler/tflite2circle/src/BuildBuiltinOptions/BidirectionalSequenceLSTMOptions.h
  compiler/tflite2circle/src/TFLBuiltinOptions.lst
Labels: PR/ready for review

#5436 [one-cmds] Add one-build_004 test
  compiler/one-cmds/CMakeLists.txt
  compiler/one-cmds/dummy-driver/CMakeLists.txt
  compiler/one-cmds/dummy-driver/src/dummy-compile.cpp
  compiler/one-cmds/tests/one-build_004.cfg
  compiler/one-cmds/tests/one-build_004.test
Labels: PR/ready for review

#5497 [luci] Add validation of CircleDepthwiseConv2DGraphBuilder
  compiler/luci/import/src/Nodes/CircleDepthwiseConv2D.cpp
Labels: PR/ready for review

#5499 [one-cmds] Add more one-build test
  compiler/one-cmds/tests/one-build_005.cfg
  compiler/one-cmds/tests/one-build_005.test
  compiler/one-cmds/tests/one-build_006.cfg
  compiler/one-cmds/tests/one-build_006.test
  compiler/one-cmds/tests/one-build_007.cfg
  compiler/one-cmds/tests/one-build_007.test
Labels: PR/ready for review

#5504 [luci] Fix wrong checking in CIrcleTypeInference
  compiler/luci/service/src/CircleTypeInference.cpp
Labels: trivial

#5437 [luci/pass] Update RemoveRedundantTranspose cover more case.
  compiler/luci/pass/src/RemoveRedundantTranspose.cpp
  compiler/luci/pass/src/RemoveRedundantTranspose.test.cpp
Labels: PR/ready for review

#5506 [luci] Change assert to if condition in DepthwiseConv2D validation
  compiler/luci/import/src/Nodes/CircleDepthwiseConv2D.cpp
Labels: PR/ready for review

#5508 [onert] Fix ifdef guards
  runtime/onert/core/include/compiler/GraphLowerInfo.h
  runtime/onert/core/include/compiler/LoweredGraph.h
  runtime/onert/core/include/compiler/OpSequenceLowerInfo.h
Labels: trivial

#5511 [onert/cpu] Support quantized int8 Softmax operation
  runtime/onert/backend/cpu/ops/SoftMaxLayer.cc
  runtime/onert/backend/cpu/ops/SoftMaxLayer.h
  runtime/onert/core/src/ir/OperationValidator.cc
  runtime/onert/core/src/ir/OperationValidator.h
  tests/nnfw_api/src/CircleGen.cc
  tests/nnfw_api/src/CircleGen.h
  tests/nnfw_api/src/one_op_tests/Softmax.cc
Labels: PR/ready for review

#5503 [luci] Fix wrong substitution in ResolveCustomOpBatchMatMulPass
  compiler/luci/pass/src/ResolveCustomOpBatchMatMulPass.cpp
Labels: PR/NO MERGE

#5457 [luci/pass] Introduce RemoveUnnecessarySlicePass.
  compiler/luci/pass/include/luci/CircleOptimizer.h
  compiler/luci/pass/include/luci/Pass/RemoveUnnecessarySlicePass.h
  compiler/luci/pass/src/CircleOptimizer.cpp
  compiler/luci/pass/src/RemoveUnnecessarySlicePass.cpp
  compiler/luci/pass/src/RemoveUnnecessarySlicePass.test.cpp
Labels: PR/ready for review

#5526 [infra] Remove unused clang format style file
  .clang-format.8
Labels: PR/ready for review, trivial

#5528 [doc] Update runtime cross build document for ACL build
  docs/howto/how-to-cross-build-runtime-for-arm.md
Labels: PR/ready for review

#5533 [onert/test] Install add nnpackage model for test
  tests/nnfw_api/CMakeLists.txt
Labels: PR/ready for review
