Repository Samsung/ONE, pull requests merged in 2020-11, with the labels that each got.

#4848 [one-cmds] fix typo
  compiler/one-cmds/tests/prepare_test_materials.sh
Labels: PR/ready for review

#4860 [nnkit-tf] Use TensorFlow package 1.13
  compiler/nnkit-tf/CMakeLists.txt
  compiler/nnkit-tf/support/CMakeLists.txt
Labels: PR/ready for review

#4839 Remove NEActivationLayerEx
  compute/ARMComputeEx/arm_compute/core/NEON/kernels/NEActivationLayerKernelEx.h
  compute/ARMComputeEx/arm_compute/runtime/NEON/NEFunctionsEx.h
  compute/ARMComputeEx/arm_compute/runtime/NEON/functions/NEActivationLayerEx.h
  compute/ARMComputeEx/src/core/NEON/kernels/NEActivationLayerKernelEx.cpp
  compute/ARMComputeEx/src/runtime/NEON/functions/NEActivationLayerEx.cpp
  runtime/onert/backend/acl_neon/KernelGenerator.cc
Labels: PR/ready for review, area/onert

#4853 [onert] revert add newline to log
  runtime/onert/core/src/compiler/LoweredGraph.cc
Labels: trivial

#4866 [onert/cpu] Initialize LSTMLayer and DepthwiseConvolutionLayer members
  runtime/onert/backend/cpu/ops/DepthwiseConvolutionLayer.cc
  runtime/onert/backend/cpu/ops/DepthwiseConvolutionLayer.h
  runtime/onert/backend/cpu/ops/LSTMLayer.cc
  runtime/onert/backend/cpu/ops/LSTMLayer.h
Labels: PR/ready for review

#4843 [onert/cpu] Fix memory leak in AddNLayer
  runtime/onert/backend/cpu/ops/AddNLayer.cc
Labels: PR/ready for review

#4875 [bcq-tools] Add removed files
  compiler/bcq-tools/CMakeLists.txt
  compiler/bcq-tools/generate_bcq_metadata
  compiler/bcq-tools/generate_bcq_output_arrays
Labels: PR/ready for review

#4877 [onert/cpu] Use vector for AddN variable input tensor configuration
  runtime/onert/backend/cpu/KernelGenerator.cc
  runtime/onert/backend/cpu/ops/AddNLayer.cc
  runtime/onert/backend/cpu/ops/AddNLayer.h
Labels: PR/ready for review, trivial

#4887 [onert/cpu] Fix optional tensor buffer access bug
  runtime/onert/backend/cpu/ops/LSTMLayer.cc
Labels: PR/ready for review

#4885 [infra] Update docker image build command
  infra/command/build-docker-image
  infra/docker/focal/Dockerfile
Labels: PR/ready for review

#4899 [cker] Initialize broadcast_category field
  compute/cker/include/cker/Types.h
Labels: PR/ready for review

#4873 [onert] Fix dilation parameter setting bug
  runtime/onert/backend/acl_cl/KernelGenerator.cc
  runtime/onert/backend/acl_neon/KernelGenerator.cc
  runtime/onert/backend/cpu/KernelGenerator.cc
  runtime/onert/core/src/ir/OperationValidator.cc
  runtime/onert/core/src/util/ShapeInference.cc
  runtime/onert/test/util/ShapeInference.cc
  tests/nnfw_api/src/one_op_tests/DepthwiseConv2D.cc
Labels: PR/ready for review

#4919 [onert/cpu] Use reference for BinaryArithmeticOpParam
  compute/cker/include/cker/Types.h
  runtime/onert/backend/cpu/ops/BinaryArithmeticLayer.cc
Labels: PR/ready for review

#4904 [onert] static functions to anonymous namespace
  runtime/onert/core/src/compiler/HEScheduler.cc
Labels: trivial

#4905 [onert] Add more ops into OneOp_While test
  runtime/onert/core/src/backend/controlflow/kernel/PermuteLayer.cc
  tests/nnfw_api/src/GenModelTests.cc
  tests/nnfw_api/src/one_op_tests/While.cc
Labels: PR/ready for review

#4851 [onert] Optimize PermuteLayer with using cached offsets
  runtime/onert/core/src/backend/controlflow/kernel/PermuteLayer.cc
  runtime/onert/core/src/exec/IPermuteFunction.h
Labels: PR/ready for review, area/onert

#4926 [onert/test] Fix test model download
  infra/scripts/common.sh
  infra/scripts/test_ubuntu_runtime_mixed.sh
  tests/scripts/command/verify-tflite
  tests/scripts/models/run_test.sh
Labels: PR/ready for review

#4927 [onert/test] Fix nnfw_api_gtest error message
  tests/nnfw_api/src/NNPackages.cc
Labels: PR/ready for review

#4917 [luci-interpreter] Support CWQ convolution op
  compiler/luci-interpreter/include/luci_interpreter/core/Tensor.h
  compiler/luci-interpreter/src/kernels/Conv2D.cpp
  compiler/luci-interpreter/src/kernels/Conv2D.test.cpp
  compiler/luci-interpreter/src/kernels/TestUtils.cpp
  compiler/luci-interpreter/src/kernels/TestUtils.h
  compiler/luci-interpreter/src/loader/GraphLoader.cpp
Labels: PR/ready for review

#4940 [luci-interpreter] Support DepthwiseConv2D channel-wise quantization
  compiler/luci-interpreter/src/kernels/Conv2D.cpp
  compiler/luci-interpreter/src/kernels/DepthwiseConv2D.cpp
  compiler/luci-interpreter/src/kernels/DepthwiseConv2D.test.cpp
  compiler/luci-interpreter/src/kernels/Utils.h
Labels: PR/ready for review

#4950 [onert] Fix runtime coverage test bug
  infra/scripts/test_coverage.sh
Labels: PR/ready for review

#4952 [infra] format checking of one-cmds as python
  infra/command/format
Labels: PR/ready for review

#4941 [luci-interpreter] Support Transpose conv with channel-wise quantization
  compiler/luci-interpreter/src/kernels/TransposeConv.cpp
  compiler/luci-interpreter/src/kernels/TransposeConv.h
  compiler/luci-interpreter/src/kernels/TransposeConv.test.cpp
Labels: PR/ready for review

#4956 [onert] Update condition to use im2col in Convolution layer
  compute/cker/include/cker/operation/Conv.h
  runtime/onert/backend/cpu/ops/ConvolutionLayer.cc
Labels: area/onert

#4718 Rewrite set_input_tensorinfo(shape) where shape==model input shape
  runtime/onert/api/src/nnfw_api_internal.cc
  tests/nnfw_api/src/ModelTestDynamicTensor.cc
Labels: PR/ready for review

#4965 [doc] Update runtime supported operation
  docs/runtime/supported-operations-backend.md
Labels: PR/ready for review

#4970 [onert] Fix nnpackage_run with load data fail
  tests/tools/nnpackage_run/src/nnpackage_run.cc
Labels: PR/ready for review

#4971 [onert] Test for set_input_tensorinfo() with a model having two inputs
  tests/nnfw_api/src/ModelTestDynamicTensor.cc
Labels: PR/ready for review

#4973 [infra] Get arch from env var in runtime test script
  infra/scripts/test_ubuntu_runtime.sh
  infra/scripts/test_ubuntu_runtime_mixed.sh
Labels: PR/ready for review

#4974 [infra] set arch manually in tizen test script
  infra/scripts/tizen_xu4_test.sh
Labels: PR/ready for review

#4986 [infra] Update ubuntu 18.04 dockerfile for coverage test
  infra/docker/bionic/Dockerfile
Labels: PR/ready for review

#4989 [tools] Update rootfs install tool
  tools/cross/install_rootfs.sh
Labels: PR/ready for review

#4987 [one-cmds] add converter_version option to cfg
  compiler/one-cmds/one-build.template.cfg
  compiler/one-cmds/one-import-bcq
  compiler/one-cmds/one-import-tf
  compiler/one-cmds/utils.py
Labels: PR/ready for review

#4988 [one-cmds] add model_format option to cfg
  compiler/one-cmds/one-import-bcq
  compiler/one-cmds/one-import-tf
  compiler/one-cmds/utils.py
Labels: PR/ready for review

#4992 [one-cmds] Revise one-prepare-venv
  compiler/one-cmds/one-prepare-venv
Labels: PR/ready for review

#4991 [tests/nnapi]Update unittest to build for android
  tests/nnapi/CMakeLists.txt
  tests/nnapi/nnapi_gtest.skip.aarch64-android.acl_cl
  tests/nnapi/nnapi_gtest.skip.aarch64-android.acl_neon
  tests/nnapi/nnapi_gtest.skip.aarch64-android.cpu
  tests/nnapi/src/TestGenerated.cpp
  tests/nnapi/src/TestValidation.cpp
Labels: target/android

#5009 [one-cmds] update cfg files
  compiler/one-cmds/tests/one-build_001.cfg
  compiler/one-cmds/tests/one-build_002.cfg
  compiler/one-cmds/tests/one-build_neg_002.cfg
  compiler/one-cmds/tests/one-build_neg_003.cfg
  compiler/one-cmds/tests/one-build_neg_004.cfg
  compiler/one-cmds/tests/one-import_002.cfg
Labels: PR/ready for review

#5007 [onert] Remove EventCollectorGlobal class
  runtime/onert/core/src/util/EventCollectorGlobal.cc
  runtime/onert/core/src/util/EventCollectorGlobal.h
Labels: PR/ready for review

#5012 [onert] Refactoring method names for execution observer
  runtime/onert/core/src/exec/DataflowExecutor.cc
  runtime/onert/core/src/exec/ExecutionObservee.cc
  runtime/onert/core/src/exec/ExecutionObservee.h
  runtime/onert/core/src/exec/ExecutionObservers.cc
  runtime/onert/core/src/exec/ExecutionObservers.h
  runtime/onert/core/src/exec/LinearExecutor.cc
  runtime/onert/core/src/exec/ParallelExecutor.cc
Labels: PR/ready for review

#5018 [infra] Update ubuntu 18.04 dockerfile lcov version
  infra/docker/bionic/Dockerfile
Labels: PR/ready for review

#5016 [onert] Use anonymous namespace for static functions
  runtime/onert/api/src/nnfw_api_internal.cc
Labels: trivial

#5005 [tests] Add setting RUY_THREADS into mixed test script
  infra/scripts/test_ubuntu_runtime_mixed.sh
Labels: PR/ready for review, area/onert

#5024 [onert/nnfw_api] Remove duplicate include
  runtime/onert/api/src/nnfw_api_internal.cc
Labels: trivial

#4951 [onert/cpu] Optimize DepthwiseConv float kernel
  compute/cker/include/cker/CpuBackendThreadpool.h
  compute/cker/include/cker/operation/DepthwiseConv.h
  compute/cker/include/cker/operation/optimized/DepthwiseConvFloat.h
  runtime/onert/backend/cpu/KernelGenerator.cc
  runtime/onert/backend/cpu/ops/DepthwiseConvolutionLayer.cc
  runtime/onert/backend/cpu/ops/DepthwiseConvolutionLayer.h
  runtime/onert/core/src/interp/operations/DepthwiseConv2D.cc
Labels: PR/ready for review

#5033 [infra] Revise android build option
  infra/nnfw/cmake/CfgOptionFlags.cmake
  infra/nnfw/cmake/options/options_aarch64-android.cmake
  tests/nnapi/CMakeLists.txt
  tests/nnapi/src/TestValidation.cpp
Labels: PR/ready for review

#5041 [onert] Use variable for controlflow ID
  runtime/onert/core/src/compiler/Compiler.cc
Labels: trivial

#5042 [onert/cpu] Merge DepthwiseConv uint8 kernel with float
  compute/cker/include/cker/operation/DepthwiseConv.h
  compute/cker/include/cker/operation/optimized/DepthwiseConvUint8.h
  runtime/onert/backend/cpu/ops/DepthwiseConvolutionLayer.cc
Labels: PR/ready for review

#5054 [model2nnpkg] Fix typo
  tools/nnpackage_tool/model2nnpkg/model2nnpkg.sh
Labels: PR/ready for review, trivial

#5059 [luci] Introduce WeightFormat attr
  compiler/luci/lang/include/luci/IR/Nodes/CircleFullyConnected.h
Labels: PR/ready for review

#5069 [luci] Introduce ShuffleWeightTo16x1Float32Pass
  compiler/luci/pass/include/luci/CircleOptimizer.h
  compiler/luci/pass/include/luci/Pass/ShuffleWeightTo16x1Float32Pass.h
  compiler/luci/pass/src/CircleOptimizer.cpp
  compiler/luci/pass/src/ShuffleWeightTo16x1Float32Pass.cpp
  compiler/luci/pass/src/ShuffleWeightTo16x1Float32Pass.test.cpp
Labels: PR/ready for review

#5060 [onert] Refactor EventWriter
  runtime/onert/core/src/util/EventWriter.cc
  runtime/onert/core/src/util/EventWriter.h
Labels: PR/ready for review

#5068 [luci] Revise import and export of FullyConnected op
  compiler/luci/export/src/CircleExporterUtils.cpp
  compiler/luci/export/src/CircleExporterUtils.h
  compiler/luci/export/src/CircleOperationExporter.cpp
  compiler/luci/import/include/luci/Import/CircleReader.h
  compiler/luci/import/src/CircleReader.cpp
  compiler/luci/import/src/Nodes/CircleFullyConnected.cpp
Labels: PR/ready for review

#5070 [circle2circle] Introduce shuffle_weight_to_16x1float32 option
  compiler/circle2circle/src/Circle2Circle.cpp
Labels: PR/ready for review

#5056 [onert/cpu] CPU backend Logical_and operation
  compute/cker/include/cker/operation/LogicalAnd.h
  runtime/onert/backend/cpu/KernelGenerator.cc
  runtime/onert/backend/cpu/ops/ElementwiseBinaryLayer.cc
  runtime/onert/frontend/base_loader/include/base_loader.h
  tests/nnapi/nnapi_gtest.skip.aarch64-android.cpu
  tests/nnapi/nnapi_gtest.skip.aarch64-linux.cpu
  tests/nnapi/nnapi_gtest.skip.armv7l-linux.cpu
  tests/nnapi/nnapi_gtest.skip.x86_64-linux.cpu
Labels: PR/ready for review

#5076 [onert] Remove unnecessary undef macro
  runtime/onert/backend/cpu/ops/ConvolutionLayer.cc
Labels: PR/ready for review, area/onert

#5078 [onert] Tidy ExecutionBase includes
  runtime/onert/core/src/exec/ExecutorBase.cc
  runtime/onert/core/src/exec/ExecutorBase.h
Labels: trivial

#5067 [onert] Introduce RUY backend
  runtime/onert/backend/CMakeLists.txt
  runtime/onert/backend/ruy/Backend.h
  runtime/onert/backend/ruy/BackendContext.h
  runtime/onert/backend/ruy/CMakeLists.txt
  runtime/onert/backend/ruy/Config.cc
  runtime/onert/backend/ruy/Config.h
  runtime/onert/backend/ruy/ConstantInitializer.cc
  runtime/onert/backend/ruy/ConstantInitializer.h
  runtime/onert/backend/ruy/ExternalContext.h
  runtime/onert/backend/ruy/KernelGenerator.cc
  runtime/onert/backend/ruy/KernelGenerator.h
  runtime/onert/backend/ruy/StaticTensorManager.cc
  runtime/onert/backend/ruy/StaticTensorManager.h
  runtime/onert/backend/ruy/Tensor.cc
  runtime/onert/backend/ruy/Tensor.h
  runtime/onert/backend/ruy/TensorBuilder.cc
  runtime/onert/backend/ruy/TensorBuilder.h
  runtime/onert/backend/ruy/ops/ConvolutionLayer.cc
  runtime/onert/backend/ruy/ops/ConvolutionLayer.h
  runtime/onert/backend/ruy/ops/OperationUtils.cc
  runtime/onert/backend/ruy/ops/OperationUtils.h
  runtime/onert/backend/ruy/ruy.cc
  runtime/onert/core/include/util/Config.lst
  tests/nnfw_api/src/one_op_tests/Conv2D.cc
Labels: area/onert

#5082 [luci] Introduce progress reporter for Module
  compiler/luci/pass/src/ProgressReporter.cpp
  compiler/luci/pass/src/ProgressReporter.h
Labels: PR/ready for review

#5081 [luci] Introduce LuciPass
  compiler/luci/pass/include/luci/LuciPass.h
Labels: PR/ready for review

#5090 [luci] Remove unused variable in LuciPass
  compiler/luci/pass/include/luci/LuciPass.h
Labels: trivial

#5097 [docs] Write How to Use Specific Backend during Inference
  docs/howto/how-to-use-specific-backend.md
Labels: PR/ready for review

#5103 [tests] Remove typo looking suffix xX
  tests/scripts/benchmark_nnapi.sh
  tests/scripts/test_scheduler_with_profiling.sh
  tests/scripts/test_scheduler_with_profiling_android.sh
Labels: trivial

#5105 [hermes] Fix typo for brief
  compiler/hermes/include/hermes/core/Message.h
Labels: trivial

#5107 [luci] Fix typo for brief
  compiler/luci/export/src/SerializedData.h
  compiler/luci/service/src/CircleShapeInferenceRule.cpp
Labels: trivial

#5104 [exo] Fix typo for brief
  compiler/exo/src/Circle/CircleExporterUtils.h
  compiler/exo/src/Dialect/Service/TFLShapeInferenceRule.cpp
  compiler/exo/src/TFLite/TFLExporterUtils.h
Labels: trivial

#5111 [moco] Fix typo for brief
  compiler/moco/support/src/TFShapeInferenceHelper.cpp
Labels: trivial

#5112 [nnc] Fix typo for brief
  compiler/nnc/include/Definitions.h.in
Labels: trivial

#5126 [onert] Revise data type
  compute/ARMComputeEx/src/runtime/CL/functions/CLFullyConnectedReshapingLayer.cpp
  compute/ARMComputeEx/src/runtime/NEON/functions/NEFullyConnectedReshapingLayer.cpp
  runtime/onert/backend/acl_common/Convert.cc
  runtime/onert/core/include/ir/DataType.h
  runtime/onert/core/src/ir/DataType.cc
  runtime/onert/frontend/nnapi/wrapper/NNAPIConvert.cc
Labels: PR/ready for review

#5134 [onert] Introduce ArgMinMax IR
  runtime/onert/backend/acl_cl/KernelGenerator.cc
  runtime/onert/backend/acl_cl/KernelGenerator.h
  runtime/onert/backend/acl_neon/KernelGenerator.cc
  runtime/onert/backend/acl_neon/KernelGenerator.h
  runtime/onert/backend/cpu/KernelGenerator.cc
  runtime/onert/backend/cpu/KernelGenerator.h
  runtime/onert/core/include/compiler/StaticShapeInferer.h
  runtime/onert/core/include/exec/DynamicShapeInferer.h
  runtime/onert/core/include/ir/Operations.Include.h
  runtime/onert/core/include/ir/Operations.lst
  runtime/onert/core/include/ir/operation/ArgMinMax.h
  runtime/onert/core/src/compiler/StaticShapeInferer.cc
  runtime/onert/core/src/exec/DynamicShapeInferer.cc
  runtime/onert/core/src/ir/OperationDumper.cc
  runtime/onert/core/src/ir/OperationDumper.h
  runtime/onert/core/src/ir/operation/ArgMinMax.cc
  runtime/onert/frontend/base_loader/include/base_loader.h
  runtime/onert/frontend/nnapi/wrapper/OperationFactory.cc
Labels: PR/ready for review

#5116 [onert] OperationValidator for ArgMax
  runtime/onert/core/src/ir/OperationValidator.cc
  runtime/onert/core/src/ir/OperationValidator.h
  tests/nnfw_api/src/one_op_tests/ArgMax.cc
Labels: PR/ready for review

#5139 [onert] Fix build fail by IR rename
  runtime/onert/core/src/ir/OperationValidator.cc
  runtime/onert/core/src/ir/OperationValidator.h
Labels: PR/ready for review, impact/critical

#5142 [onert] Fix indentation level in BackendManager
  runtime/onert/core/src/compiler/BackendManager.cc
Labels: trivial

#5133 [onert] Update base loader data type conversion
  runtime/onert/frontend/base_loader/include/base_loader.h
Labels: PR/ready for review

#5148 [infra] Fix clang format style option
  .clang-format
Labels: PR/ready for review

#5147 [onert] Rename shape inferer for ArgMinMax
  runtime/onert/core/include/util/ShapeInference.h
  runtime/onert/core/src/compiler/StaticShapeInferer.cc
  runtime/onert/core/src/exec/DynamicShapeInferer.cc
  runtime/onert/core/src/util/ShapeInference.cc
Labels: PR/ready for review

#5150 [onert] Support ArgMin on backends
  runtime/onert/backend/acl_cl/KernelGenerator.cc
  runtime/onert/backend/acl_neon/KernelGenerator.cc
  runtime/onert/backend/cpu/KernelGenerator.cc
  tests/nnapi/nnapi_gtest.skip.noarch.interp
  tests/nnapi/specs/V1_2/argmin_1.mod.py
  tests/nnapi/specs/V1_2/argmin_2.mod.py
  tests/nnapi/specs/V1_2/argmin_3.mod.py
  tests/nnfw_api/src/CircleGen.cc
  tests/nnfw_api/src/CircleGen.h
  tests/nnfw_api/src/one_op_tests/ArgMinMax.cc
Labels: PR/ready for review

#5160 Cherry-pick missing note of 1.7.0 release to master branch.
  docs/release/1.7/release-note-1.7.0.md
Labels: PR/ready for review

#5154 [test/nnfw_api] Fix nnfw_api_gtest fail on x86_64
  tests/nnfw_api/CMakeLists.txt
  tests/nnfw_api/src/GenModelTest.h
Labels: PR/ready for review

#5156 Update index of how-to- documents
  docs/howto/index.rst
Labels: PR/ready for review

#5158 Update index of runtime documents
  docs/runtime/index.rst
Labels: PR/ready for review

#5157 [onert] Support int8 quantization ArgMinMax
  compute/ARMComputeEx/src/core/CL/kernels/CLArgMinMaxLayerKernelEx.cpp
  runtime/onert/backend/acl_common/Convert.cc
  runtime/onert/backend/cpu/ops/ArgMinMaxLayer.cc
  tests/nnfw_api/src/one_op_tests/ArgMinMax.cc
Labels: PR/ready for review

#5164 [onert/acl] Update exception message
  runtime/onert/backend/acl_common/Convert.cc
Labels: PR/ready for review, trivial

#5163 [tool/kernel_report] Remove onert base directory from argument
  tools/kernel_report/kernel_report.py
Labels: PR/ready for review

#5165 [onert] Sort Operations.Include.h
  runtime/onert/core/include/ir/Operations.Include.h
Labels: PR/ready for review, trivial

#5127 [onert] Check BatchMatmul tensor type
  runtime/onert/backend/cpu/ops/BatchMatMulLayer.cc
  runtime/onert/core/src/ir/OperationValidator.cc
Labels: PR/ready for review

#5169 [onert] Sort Operations.lst
  runtime/onert/core/include/ir/Operations.lst
Labels: PR/ready for review, trivial

#5170 [onert] Fix indentation in LowerGraph
  runtime/onert/core/src/compiler/LoweredGraph.cc
Labels: PR/ready for review, trivial

#5171 [onert] Sort KernelGenerator visitors
  runtime/onert/backend/acl_cl/KernelGenerator.h
  runtime/onert/backend/acl_neon/KernelGenerator.h
  runtime/onert/backend/cpu/KernelGenerator.h
Labels: PR/ready for review, trivial

#5176 [onert] Sort baseloader operation loading methods
  runtime/onert/frontend/base_loader/include/base_loader.h
Labels: PR/ready for review, trivial

#5184 [onert] Check same data type for AddN operation
  runtime/onert/core/src/ir/OperationValidator.cc
  tests/nnfw_api/src/one_op_tests/AddN.cc
Labels: PR/ready for review

#5181 [onert] Support DepthToSpace on cpu backend
  compute/cker/include/cker/operation/DepthToSpace.h
  runtime/onert/backend/cpu/KernelGenerator.cc
  runtime/onert/backend/cpu/KernelGenerator.h
  runtime/onert/backend/cpu/ops/DepthToSpaceLayer.cc
  runtime/onert/backend/cpu/ops/DepthToSpaceLayer.h
  runtime/onert/core/src/ir/OperationValidator.cc
  runtime/onert/frontend/base_loader/include/base_loader.h
  tests/nnapi/nnapi_gtest.skip.aarch64-android.cpu
  tests/nnapi/nnapi_gtest.skip.aarch64-linux.cpu
  tests/nnapi/nnapi_gtest.skip.armv7l-linux.cpu
  tests/nnapi/nnapi_gtest.skip.x86_64-linux.cpu
  tests/nnfw_api/src/CircleGen.cc
  tests/nnfw_api/src/CircleGen.h
  tests/nnfw_api/src/one_op_tests/DepthToSpace.cc
Labels: PR/ready for review

#5166 [luci] Enable passes for module optimizations
  compiler/luci/pass/src/CircleOptimizer.cpp
Labels: PR/ready for review

#5200 [onert/cpu] Switch-case for DepthToSpace
  runtime/onert/backend/cpu/ops/DepthToSpaceLayer.cc
Labels: PR/ready for review, trivial

#5187 [onert] Test for multiple sessions
  tests/nnfw_api/src/ValidationTestMultipleSessions.cc
  tests/nnfw_api/src/fixtures.h
Labels: PR/ready for review

#5194 [onert] Fix validation check for BatchToSpaceND
  runtime/onert/backend/acl_cl/KernelGenerator.cc
  runtime/onert/backend/acl_neon/KernelGenerator.cc
  runtime/onert/core/src/compiler/ShapeValidator.cc
  runtime/onert/core/src/ir/OperationValidator.cc
Labels: PR/ready for review

#5204 [onert] Adds missing header guard into GenModelTest.h
  tests/nnfw_api/src/GenModelTest.h
Labels: PR/ready for review

#5203 [onert] Support int8 Concat
  runtime/onert/backend/cpu/ops/ConcatLayer.cc
  runtime/onert/core/src/ir/OperationValidator.cc
  runtime/onert/core/src/ir/OperationValidator.h
  tests/nnfw_api/src/one_op_tests/Concat.cc
Labels: PR/ready for review

#5206 [onert] Show shape information in Chrome Tracing
  runtime/onert/core/src/exec/ExecutionObservers.cc
  runtime/onert/core/src/util/EventCollector.cc
  runtime/onert/core/src/util/EventCollector.h
  runtime/onert/core/src/util/EventRecorder.h
  runtime/onert/core/src/util/EventWriter.cc
Labels: PR/ready for review

#5214 [onert/api] Introduce internal API for model file load
  runtime/onert/api/include/nnfw_internal.h
  runtime/onert/api/src/nnfw_api.cc
  runtime/onert/api/src/nnfw_api_internal.cc
  runtime/onert/api/src/nnfw_api_internal.h
Labels: PR/ready for review

#5216 [onert] ElementwiseBinary operation validation check
  runtime/onert/core/src/ir/OperationValidator.cc
Labels: PR/ready for review

#5189 [onert] Introduce TraceCtx that has profiling information per session
  runtime/onert/api/src/nnfw_api_internal.cc
  runtime/onert/api/src/nnfw_api_internal.h
  runtime/onert/core/include/ir/Subgraphs.h
  runtime/onert/core/include/util/TracingCtx.h
  runtime/onert/core/src/util/TracingCtx.cc
Labels: PR/ready for review

#5215 [tfldump] Add MEAN to OpPrinterRegistry
  compiler/tfldump/src/OpPrinter.cpp
Labels: trivial

#5217 [luci] Rename ShapeSignature inference helper function
  compiler/luci/service/include/luci/Service/CircleShapeSignatureInferenceHelper.h
  compiler/luci/service/src/CircleShapeSignatureInferenceHelper.cpp
  compiler/luci/service/src/Nodes/CircleOutput.cpp
  compiler/luci/service/src/Nodes/CircleRelu.cpp
  compiler/luci/service/src/Nodes/CircleRelu6.cpp
  compiler/luci/service/src/Nodes/CircleReluN1To1.cpp
Labels: trivial
