Repository Samsung/ONE, pull requests merged in 2020-08, with the labels that each got.

#3581 [TensorFlowPythonModels] Add tconv-bn network
  res/TensorFlowPythonModels/examples/tconv-bn/__init__.py
Labels: PR/ready for review

#3582 [common-artifacts] resolve circular dependency
  compiler/common-artifacts/CMakeLists.txt
Labels: PR/ready for review

#3580 [preset] Introduce 20200731 windows preset
  infra/packaging/preset/20200731_windows
Labels: PR/ready for review

#3559 [onert] Manage ruy_context on runtime
  compute/cker/include/cker/NeonTensorUtils.h
  compute/cker/include/cker/PortableTensorUtils.h
  compute/cker/include/cker/TensorUtils.h
  compute/cker/include/cker/operation/FullyConnected.h
  compute/cker/include/cker/ruy/RuySupport.h
  runtime/onert/backend/cpu/Backend.h
  runtime/onert/backend/cpu/BackendContext.h
  runtime/onert/backend/cpu/CMakeLists.txt
  runtime/onert/backend/cpu/ExternalContext.h
  runtime/onert/backend/cpu/KernelGenerator.cc
  runtime/onert/backend/cpu/KernelGenerator.h
  runtime/onert/backend/cpu/ops/FullyConnectedLayer.cc
  runtime/onert/backend/cpu/ops/FullyConnectedLayer.h
  runtime/onert/core/include/backend/BackendContext.h
  runtime/onert/core/include/backend/IExternalContext.h
Labels: PR/ready for review, area/onert

#3489 [onert] Add ResizeBilinear cker
  compute/cker/include/cker/Types.h
  compute/cker/include/cker/operation/ResizeBilinear.h
  runtime/onert/backend/cpu/KernelGenerator.cc
  runtime/onert/backend/cpu/KernelGenerator.h
  runtime/onert/backend/cpu/ops/ResizeBilinearLayer.cc
  runtime/onert/backend/cpu/ops/ResizeBilinearLayer.h
  runtime/onert/core/include/compiler/StaticShapeInference.h
  runtime/onert/core/include/exec/DynamicShapeInference.h
  runtime/onert/core/include/ir/operation/ResizeBilinear.h
  runtime/onert/core/include/util/ShapeInference.h
  runtime/onert/core/src/compiler/OperationValidator.cc
  runtime/onert/core/src/compiler/OperationValidator.h
  runtime/onert/core/src/compiler/StaticShapeInference.cc
  runtime/onert/core/src/exec/DynamicShapeInference.cc
  runtime/onert/core/src/util/ShapeInference.cc
  runtime/onert/frontend/base_loader/include/base_loader.h
  runtime/onert/frontend/nnapi/wrapper/OperationFactory.cc
  tests/nnapi/nnapi_gtest.skip.aarch64-linux.cpu
  tests/nnapi/nnapi_gtest.skip.armv7l-linux.cpu
  tests/nnapi/nnapi_gtest.skip.noarch.interp
  tests/nnapi/nnapi_gtest.skip.x86_64-linux.cpu
  tests/nnapi/specs/V1_0/resize_bilinear_quant8_nnfw.mod.py
Labels: PR/ready for review

#3469 [Compiler] Bugfix and patches for FuseBCQPass in 1.7.0
  compiler/luci/pass/src/FuseBCQPass.cpp
Labels: type/release

#3613 [tf2tfliteV2] Support more model format
  compiler/tf2tfliteV2/tf2tfliteV2.py
Labels: PR/ready for review

#3617 [TensorFlowPhtyonExample] `WHILE` example throwing incompatible shape
  res/TensorFlowPythonExamples/examples/while_2/__init__.py
Labels: PR/ready for review

#3604 [onert/test] Move unittest.sh
  tests/scripts/CMakeLists.txt
  tests/scripts/command/unittest
  tests/scripts/onert-test
  tests/scripts/test-driver.sh
Labels: PR/ready for review

#3631 [onert-test] Introduce nnpkg-test command
  tests/scripts/command/nnpkg-test
Labels: PR/ready for review

#3628 [one-cmds] Add user option to pip
  compiler/one-cmds/one-prepare-venv
Labels: PR/ready for review

#3642 [tf2circle-value-pbtxt-remote-test] Use installed nnpkg test command
  compiler/tf2circle-value-pbtxt-remote-test/CMakeLists.txt
  compiler/tf2circle-value-pbtxt-remote-test/README.md
  compiler/tf2circle-value-pbtxt-remote-test/testall.sh
Labels: PR/ready for review

#3643 [tf2nnpackage-value-remote-test] Use installed nnpkg test command
  compiler/tf2nnpackage-value-remote-test/CMakeLists.txt
  compiler/tf2nnpackage-value-remote-test/README.md
  compiler/tf2nnpackage-value-remote-test/testall.sh
Labels: PR/ready for review

#3662 [tflchef] fix TransposeConv filler bug
  compiler/tflchef/tflite/src/Op/TransposeConv.cpp
Labels: PR/ready for review

#3663 [TensorFlowLiteRecipes] Add Net_TConv_BN_000
  res/TensorFlowLiteRecipes/Net_TConv_BN_000/test.recipe
Labels: PR/ready for review

#3654 [cker/ruy] Use polymorphic_downcast to fix dynamic_cast error on android
  runtime/libs/misc/include/misc/polymorphic_downcast.h
  runtime/onert/backend/cpu/ops/FullyConnectedLayer.cc
Labels: PR/ready for review

#3668 [onert] Enable constant tensor deallocation if tensor is cached
  runtime/onert/backend/cpu/ops/FullyConnectedLayer.cc
  runtime/onert/backend/cpu/ops/FullyConnectedLayer.h
Labels: PR/ready for review, area/onert

#3641 [onert] Implement SplitV operation in cpu backend
  compute/cker/include/cker/Types.h
  compute/cker/include/cker/operation/SplitV.h
  runtime/nnapi-header/include/NeuralNetworksEx.h
  runtime/onert/backend/cpu/KernelGenerator.cc
  runtime/onert/backend/cpu/KernelGenerator.h
  runtime/onert/backend/cpu/ops/SplitVLayer.cc
  runtime/onert/backend/cpu/ops/SplitVLayer.h
  runtime/onert/core/include/ir/Operations.Include.h
  runtime/onert/core/include/ir/Operations.lst
  runtime/onert/core/include/ir/operation/SplitV.h
  runtime/onert/core/src/ir/operation/SplitV.cc
  runtime/onert/frontend/base_loader/include/base_loader.h
  runtime/onert/frontend/nnapi/model.cc
  runtime/onert/frontend/nnapi/wrapper/OperationFactory.cc
  tests/nnapi/nnapi_gtest.skip.aarch64-linux.acl_cl
  tests/nnapi/nnapi_gtest.skip.aarch64-linux.acl_neon
  tests/nnapi/nnapi_gtest.skip.armv7l-linux.acl_cl
  tests/nnapi/nnapi_gtest.skip.armv7l-linux.acl_neon
  tests/nnapi/nnapi_gtest.skip.noarch.interp
  tests/nnapi/specs/Ex/split_v_ex_1D_float_1_nnfw.mod.py
  tests/nnapi/specs/Ex/split_v_ex_1D_float_2_nnfw.mod.py
  tests/nnapi/specs/Ex/split_v_ex_1D_int32_nnfw.mod.py
  tests/nnapi/specs/Ex/split_v_ex_4D_float_1_nnfw.mod.py
  tests/nnapi/specs/Ex/split_v_ex_4D_float_2_nnfw.mod.py
  tests/nnapi/specs/Ex/split_v_ex_4D_float_3_nnfw.mod.py
  tests/nnapi/specs/Ex/split_v_ex_4D_float_4_nnfw.mod.py
  tests/nnapi/specs/Ex/split_v_ex_4D_int32_1_nnfw.mod.py
  tests/nnapi/specs/Ex/split_v_ex_4D_int32_2_nnfw.mod.py
  tests/nnapi/specs/Ex/split_v_ex_4D_int32_3_nnfw.mod.py
  tests/nnapi/specs/Ex/split_v_ex_4D_int32_4_nnfw.mod.py
Labels: PR/ready for review

#3630 [onert/test] Update unittest usage
  infra/scripts/common.sh
  infra/scripts/test_ubuntu_runtime.sh
  infra/scripts/test_ubuntu_runtime_mixed.sh
  tests/scripts/test-driver.sh
Labels: PR/ready for review

#3670 [onert/CI] Update package generation in Makefile.template
  Makefile.template
Labels: PR/ready for review

#3661 [common-artifacts] Add fixed_seed option to TestDataGenerator
  compiler/common-artifacts/CMakeLists.txt
  compiler/common-artifacts/requires.cmake
  compiler/common-artifacts/src/TestDataGenerator.cpp
Labels: PR/ready for review

#3690 [onert/test] Introduce model download command
  infra/scripts/test_ubuntu_runtime_mixed.sh
  tests/scripts/CMakeLists.txt
  tests/scripts/command/prepare-model
Labels: PR/ready for review

#3664 [onert/test] Use onert-test for nnpkg-test
  infra/scripts/common.sh
  tests/scripts/command/nnpkg-test
  tests/scripts/nnpkg_test.sh
  tools/nnpackage_tool/sth2nnpkgtc/pb2nnpkgtc.md
  tools/nnpackage_tool/sth2nnpkgtc/tflite2nnpkgtc.md
Labels: PR/ready for review

#3708 [circle-tensordump] Check whether option is provided or not
  compiler/circle-tensordump/driver/Driver.cpp
Labels: PR/ready for review

#3671 [onert] Put `private` to correct position
  runtime/onert/core/src/ir/pass/PermutationInsertionPass.h
Labels: PR/ready for review

#3714 [infra/CI] Divide venv tar from compiler package
  infra/scripts/docker_build_nncc.sh
Labels: PR/ready for review

#3693 [onert/test] Introduce tflite verification test command
  infra/scripts/common.sh
  tests/scripts/command/verify-tflite
  tests/scripts/models/run_test.sh
Labels: PR/ready for review

#3638 [onert] Implement quantization ReduceSum cpu backend
  compute/cker/include/cker/operation/Reduce.h
  runtime/onert/backend/cpu/ops/ReduceLayer.cc
  tests/scripts/list/frameworktest_list.aarch64.acl_cl.txt
  tests/scripts/list/frameworktest_list.armv7l.acl_cl.txt
  tests/scripts/list/tflite_loader_list.aarch64.txt
  tests/scripts/list/tflite_loader_list.armv7l.txt
  tests/scripts/models/config/reduce_sum/float/config.sh
  tests/scripts/models/config/reduce_sum/uint8/config.sh
Labels: PR/ready for review

#3722 [tf2tfliteV2] Update README.md and help message
  compiler/tf2tfliteV2/README.md
  compiler/tf2tfliteV2/tf2tfliteV2.py
Labels: PR/ready for review

#3724 [onert] Find package to link flatbuffers to circle_schema
  runtime/onert/frontend/circle_schema/CMakeLists.txt
Labels: PR/ready for review

#3728 [infra/script] Fix bug in docker_build_nncc.sh
  infra/scripts/docker_build_nncc.sh
Labels: PR/ready for review

#3721 [onert/test] Use installed list and model config
  infra/scripts/test_arm_nnpkg.sh
  infra/scripts/test_coverage.sh
  infra/scripts/test_ubuntu_runtime.sh
  infra/scripts/test_ubuntu_runtime_mixed.sh
  tests/scripts/CMakeLists.txt
  tests/scripts/command/prepare-model
  tests/scripts/command/verify-tflite
Labels: PR/ready for review

#3730 [onert/test] Rename minimal app
  packaging/nnfw.spec
  runtime/onert/sample/minimal/CMakeLists.txt
Labels: PR/ready for review

#3725 [onert/gbs] Fix directory ownership
  packaging/nnfw.spec
Labels: PR/ready for review

#3739 [onert/test] Install tflite download model config
  tests/scripts/CMakeLists.txt
Labels: PR/ready for review, bug, impact/critical

#3741 [onert/test] Check config directory exist in run_test.sh
  tests/scripts/models/run_test.sh
Labels: PR/ready for review, trivial

#3744 [onert/test] Move custom op test install directory
  infra/scripts/test_ubuntu_runtime.sh
  infra/scripts/test_ubuntu_runtime_mixed.sh
  tests/custom_op/FillFrom/CMakeLists.txt
Labels: PR/ready for review, trivial

#3735 [infra] Use user defined value by default
  infra/packaging/build
Labels: PR/ready for review

#3736 [onert/cpu] Implement BatchToSpaceND quantized uint8 cpu backend
  runtime/onert/backend/cpu/ops/BatchToSpaceNDLayer.cc
  runtime/onert/backend/cpu/ops/BatchToSpaceNDLayer.h
  tests/nnapi/nnapi_gtest.skip.aarch64-linux.cpu
  tests/nnapi/nnapi_gtest.skip.armv7l-linux.cpu
  tests/nnapi/nnapi_gtest.skip.x86_64-linux.cpu
Labels: PR/ready for review

#3752 [common-artifacts] Disable interpreter tests for PadV2
  compiler/common-artifacts/exclude.lst
Labels: PR/ready for review

#3710 [onert] Remove unused function for munmap
  runtime/onert/frontend/base_loader/include/base_loader.h
Labels: PR/ready for review, area/onert

#3750 [onert] Remove unused class `OperandContext`
  runtime/onert/core/src/compiler/OperandContext.cc
  runtime/onert/core/src/compiler/OperandContext.h
  runtime/onert/core/src/exec/ExecutorBase.h
Labels: trivial

#3729 [onert] Update tizen test infra
  infra/scripts/tizen_xu4_test.sh
  packaging/nnapi_test_generated.tar.gz
  packaging/nnfw.spec
Labels: PR/ready for review

#3765 Release Note for 1.8.0
  docs/release/1.8/release-note-1.8.0.md
Labels: PR/ready for review

#3762 [onert/compute] Check ENABLE_TEST for test build
  compute/test/CMakeLists.txt
Labels: PR/ready for review

#3760 [onert/cpu] Move softmax implementation
  compute/cker/include/cker/operation/SoftMax.h
  runtime/onert/backend/cpu/ops/SoftMaxLayer.cc
  runtime/onert/core/src/interp/operations/Softmax.cc
Labels: PR/ready for review

#3771 [release/1.8.0] Fix runtime makefile for packaging
  Makefile.template
Labels: PR/ready for review, area/CI, impact/critical, trivial

#3772 [onert] Fix runtime makefile for packaging
  Makefile.template
Labels: PR/ready for review

#3758 [onert] Add log_softmax kernel to support quant8
  compute/cker/include/cker/Types.h
  compute/cker/include/cker/operation/LogSoftMax.h
  runtime/onert/backend/cpu/ops/LogSoftMaxLayer.cc
  runtime/onert/backend/cpu/ops/LogSoftMaxLayer.h
  tests/nnapi/nnapi_gtest.skip.aarch64-linux.acl_cl
  tests/nnapi/nnapi_gtest.skip.aarch64-linux.acl_neon
  tests/nnapi/nnapi_gtest.skip.armv7l-linux.acl_cl
  tests/nnapi/nnapi_gtest.skip.armv7l-linux.acl_neon
  tests/nnapi/nnapi_gtest.skip.noarch.interp
  tests/nnapi/specs/V1_2/log_softmax_nnfw.mod.py
Labels: PR/ready for review

#3773 [onert] Merge operation input dynamic shape checking
  runtime/onert/core/include/compiler/StaticShapeInference.h
  runtime/onert/core/src/compiler/StaticShapeInference.cc
Labels: PR/ready for review

#3782 [onert] Unify binary arithmetic operations to BinaryArithmetic
  runtime/onert/backend/acl_cl/KernelGenerator.cc
  runtime/onert/backend/acl_cl/KernelGenerator.h
  runtime/onert/backend/acl_neon/KernelGenerator.cc
  runtime/onert/backend/acl_neon/KernelGenerator.h
  runtime/onert/backend/cpu/KernelGenerator.cc
  runtime/onert/backend/cpu/KernelGenerator.h
  runtime/onert/backend/cpu/ops/AddLayer.cc
  runtime/onert/backend/cpu/ops/AddLayer.h
  runtime/onert/backend/cpu/ops/BinaryArithmeticLayer.cc
  runtime/onert/backend/cpu/ops/BinaryArithmeticLayer.h
  runtime/onert/backend/cpu/ops/DivLayer.cc
  runtime/onert/backend/cpu/ops/DivLayer.h
  runtime/onert/backend/cpu/ops/MulLayer.cc
  runtime/onert/backend/cpu/ops/SubLayer.cc
  runtime/onert/backend/cpu/ops/SubLayer.h
  runtime/onert/core/include/compiler/StaticShapeInference.h
  runtime/onert/core/include/exec/DynamicShapeInference.h
  runtime/onert/core/include/ir/Operations.Include.h
  runtime/onert/core/include/ir/Operations.lst
  runtime/onert/core/include/ir/operation/Add.h
  runtime/onert/core/include/ir/operation/BinaryArithmetic.h
  runtime/onert/core/include/ir/operation/Div.h
  runtime/onert/core/include/ir/operation/Einsum.h
  runtime/onert/core/include/ir/operation/Mul.h
  runtime/onert/core/src/compiler/HEScheduler.cc
  runtime/onert/core/src/compiler/StaticShapeInference.cc
  runtime/onert/core/src/exec/DynamicShapeInference.cc
  runtime/onert/core/src/interp/InterpOps.lst
  runtime/onert/core/src/interp/operations/BinaryArithmeticOps.cc
  runtime/onert/core/src/ir/OperationDumper.cc
  runtime/onert/core/src/ir/OperationDumper.h
  runtime/onert/core/src/ir/operation/Add.cc
  runtime/onert/core/src/ir/operation/BinaryArithmetic.cc
  runtime/onert/core/src/ir/operation/Div.cc
  runtime/onert/core/src/ir/operation/Sub.cc
  runtime/onert/core/src/ir/pass/PermutationOperationPass.cc
  runtime/onert/core/src/ir/pass/PermutationOperationPass.h
  runtime/onert/frontend/base_loader/include/base_loader.h
  runtime/onert/frontend/nnapi/wrapper/OperationFactory.cc
  runtime/onert/test/core/compiler/Scheduler.cc
  runtime/onert/test/core/exec/ExecInstance.cc
  runtime/onert/test/core/interp/ExecManager.cc
Labels: PR/ready for review, area/onert

#3753 [tfldump] Fix comment for PadV2 op
  compiler/tfldump/src/OpPrinter.cpp
Labels: PR/ready for review

#3810 [onert] Fix weight deallocation to work on android (1.8.0 release)
  runtime/onert/backend/cpu/ops/FullyConnectedLayer.cc
Labels: PR/ready for review, area/onert

#3814 [onert/test] Return void setInputsAndOutputs
  tests/nnfw_api/src/CircleGen.cc
  tests/nnfw_api/src/CircleGen.h
Labels: PR/ready for review

#3817 [onert] Use CachedData instead of MMapedData (1.8.0)
  runtime/onert/frontend/base_loader/include/base_loader.h
Labels: PR/ready for review, area/onert

#3822 [onert] Generate test package using ls
  Makefile.template
Labels: PR/ready for review

#3807 [onert] Fix weight deallocation to work on android
  runtime/onert/backend/cpu/ops/FullyConnectedLayer.cc
Labels: PR/ready for review, area/onert

#3821 [tool/update-version] Show current version
  tools/update_version/update-version.sh
Labels: PR/ready for review

#3812 [onert] Change param ReduceType to template in base_loader
  runtime/onert/frontend/base_loader/include/base_loader.h
Labels: PR/ready for review, area/onert

#3815 [tool/tflitefile] Add requirements.txt file
  tools/tflitefile_tool/model_parser.py
  tools/tflitefile_tool/requirements.txt
  tools/tflitefile_tool/select_operator.py
Labels: PR/ready for review

#3791 [onert] Unify element-wise binary operations to ElementwiseBinary
  runtime/onert/backend/acl_cl/KernelGenerator.cc
  runtime/onert/backend/acl_cl/KernelGenerator.h
  runtime/onert/backend/acl_neon/KernelGenerator.cc
  runtime/onert/backend/acl_neon/KernelGenerator.h
  runtime/onert/backend/cpu/KernelGenerator.cc
  runtime/onert/backend/cpu/KernelGenerator.h
  runtime/onert/backend/cpu/ops/ElementwiseBinaryLayer.cc
  runtime/onert/backend/cpu/ops/ElementwiseBinaryLayer.h
  runtime/onert/backend/cpu/ops/LogicalOrLayer.cc
  runtime/onert/backend/cpu/ops/LogicalOrLayer.h
  runtime/onert/backend/cpu/ops/MaxLayer.cc
  runtime/onert/backend/cpu/ops/MaxLayer.h
  runtime/onert/backend/cpu/ops/MinLayer.cc
  runtime/onert/core/include/compiler/StaticShapeInference.h
  runtime/onert/core/include/exec/DynamicShapeInference.h
  runtime/onert/core/include/ir/Operations.Include.h
  runtime/onert/core/include/ir/Operations.lst
  runtime/onert/core/include/ir/operation/ElementwiseBinary.h
  runtime/onert/core/include/ir/operation/LogicalAnd.h
  runtime/onert/core/include/ir/operation/LogicalOr.h
  runtime/onert/core/include/ir/operation/Max.h
  runtime/onert/core/src/compiler/OperationValidator.cc
  runtime/onert/core/src/compiler/OperationValidator.h
  runtime/onert/core/src/compiler/StaticShapeInference.cc
  runtime/onert/core/src/exec/DynamicShapeInference.cc
  runtime/onert/core/src/interp/InterpOps.lst
  runtime/onert/core/src/ir/OperationDumper.cc
  runtime/onert/core/src/ir/OperationDumper.h
  runtime/onert/core/src/ir/operation/ElementwiseBinary.cc
  runtime/onert/core/src/ir/operation/LogicalAnd.cc
  runtime/onert/core/src/ir/operation/LogicalOr.cc
  runtime/onert/core/src/ir/operation/Max.cc
  runtime/onert/core/src/ir/operation/Min.cc
  runtime/onert/core/src/ir/pass/PermutationOperationPass.cc
  runtime/onert/core/src/ir/pass/PermutationOperationPass.h
  runtime/onert/frontend/base_loader/include/base_loader.h
  runtime/onert/frontend/nnapi/wrapper/OperationFactory.cc
Labels: PR/ready for review, area/onert

#3842 [onert] Remove method `TensorBuilder::iterate`
  runtime/onert/backend/acl_common/AclTensorBuilder.h
  runtime/onert/backend/cpu/TensorBuilder.cc
  runtime/onert/backend/cpu/TensorBuilder.h
  runtime/onert/core/include/backend/ITensorBuilder.h
  runtime/onert/core/src/backend/controlflow/TensorBuilder.cc
  runtime/onert/core/src/backend/controlflow/TensorBuilder.h
Labels: trivial

#3843 [benchmark] Measure memory usage at the end of each phase
  runtime/libs/benchmark/src/MemoryPoller.cpp
Labels: PR/ready for review

#3853 [onert] Unify pooling operations to Pool2D
  compute/cker/include/cker/operation/AveragePool.h
  compute/cker/include/cker/operation/MaxPool.h
  runtime/onert/backend/acl_cl/KernelGenerator.cc
  runtime/onert/backend/acl_cl/KernelGenerator.h
  runtime/onert/backend/acl_common/Convert.cc
  runtime/onert/backend/acl_common/Convert.h
  runtime/onert/backend/acl_neon/KernelGenerator.cc
  runtime/onert/backend/acl_neon/KernelGenerator.h
  runtime/onert/backend/cpu/KernelGenerator.cc
  runtime/onert/backend/cpu/KernelGenerator.h
  runtime/onert/backend/cpu/ops/AvgPoolLayer.cc
  runtime/onert/backend/cpu/ops/AvgPoolLayer.h
  runtime/onert/backend/cpu/ops/MaxPoolLayer.cc
  runtime/onert/backend/cpu/ops/PoolLayer.cc
  runtime/onert/backend/cpu/ops/PoolLayer.h
  runtime/onert/core/include/ir/Operations.Include.h
  runtime/onert/core/include/ir/Operations.lst
  runtime/onert/core/include/ir/operation/AvgPool2D.h
  runtime/onert/core/include/ir/operation/L2Pool2D.h
  runtime/onert/core/include/ir/operation/Pool2D.h
  runtime/onert/core/include/util/ShapeInference.h
  runtime/onert/core/src/compiler/OperationValidator.cc
  runtime/onert/core/src/compiler/OperationValidator.h
  runtime/onert/core/src/interp/InterpOps.lst
  runtime/onert/core/src/interp/operations/AvgPool2D.cc
  runtime/onert/core/src/interp/operations/Pool2D.cc
  runtime/onert/core/src/ir/OperationDumper.cc
  runtime/onert/core/src/ir/OperationDumper.h
  runtime/onert/core/src/ir/operation/L2Pool2D.cc
  runtime/onert/core/src/ir/operation/MaxPool2D.cc
  runtime/onert/core/src/ir/operation/Pool2D.cc
  runtime/onert/core/src/util/ShapeInference.cc
  runtime/onert/frontend/base_loader/include/base_loader.h
  runtime/onert/frontend/nnapi/wrapper/OperationFactory.cc
  runtime/onert/test/util/ShapeInference.cc
Labels: PR/ready for review, area/onert

#3861 [tool/nnpkg] Set nnpacakge name
  tools/nnpackage_tool/model2nnpkg/README.md
  tools/nnpackage_tool/model2nnpkg/model2nnpkg.sh
Labels: PR/ready for review

#3867 [infra/cmake] Boost config and Install path
  infra/cmake/packages/BoostSourceConfig.cmake
  infra/nnfw/cmake/packages/BoostConfig.cmake
Labels: PR/ready for review

#3868 [onert] Add ifdef guard to controlflow TensorReg
  runtime/onert/core/src/backend/controlflow/TensorRegistry.h
Labels: trivial

#3871 [tool/model2nnpkg] Fix string comparison bug
  tools/nnpackage_tool/model2nnpkg/model2nnpkg.sh
Labels: PR/ready for review

#3883 [infra] Update eigen download url
  infra/3rdparty/Eigen/fd6845384b86/URL.default
  infra/cmake/packages/EigenSourceConfig.cmake
Labels: PR/ready for review, impact/critical

#3888 [onert/test] Fix test command warning
  tests/scripts/models/run_test.sh
Labels: PR/ready for review, trivial

#3898 [onert] Remove unused Mean IR
  runtime/onert/core/include/ir/operation/Mean.h
Labels: trivial

#3895 [onert] cpu KernelGen use _tensor_reg directly
  runtime/onert/backend/cpu/KernelGenerator.cc
Labels: trivial

#3892 [tflite2circle] verify tflite file
  compiler/tflite2circle/src/CircleModel.cpp
Labels: PR/ready for review

#3893 [record-minmax] verify circle file
  compiler/record-minmax/src/RecordMinMax.cpp
Labels: PR/ready for review

#3894 [circle-quantizer] verify circle file
  compiler/circle-quantizer/src/CircleQuantizer.cpp
Labels: PR/ready for review

#3887 [onert] Enable L2Norm and PadV2 operation loading
  runtime/onert/core/src/ir/operation/Pad.cc
  runtime/onert/frontend/base_loader/include/base_loader.h
  tests/nnfw_api/src/CircleGen.cc
  tests/nnfw_api/src/CircleGen.h
  tests/nnfw_api/src/GenModelTests.cc
Labels: PR/ready for review

#3927 [common-artifacts] Remove redundant space
  compiler/common-artifacts/CMakeLists.txt
Labels: PR/ready for review

#3911 [onert/test] Split GenModelTests.cc
  tests/nnfw_api/src/GenModelTest.h
  tests/nnfw_api/src/GenModelTests.cc
  tests/nnfw_api/src/one_op_tests/Add.cc
  tests/nnfw_api/src/one_op_tests/AveragePool2D.cc
  tests/nnfw_api/src/one_op_tests/Cos.cc
  tests/nnfw_api/src/one_op_tests/L2Normalization.cc
  tests/nnfw_api/src/one_op_tests/Pad.cc
  tests/nnfw_api/src/one_op_tests/PadV2.cc
Labels: PR/ready for review

#3926 [infra] Update eigen download url
  infra/3rdparty/Eigen/fd6845384b86/URL.default
  infra/cmake/packages/EigenSourceConfig.cmake
Labels: PR/ready for review

#3928 [onert/test] Update nnpackage test list
  tests/scripts/list/nnpkg_test_list.armv7l-linux.acl_cl
  tests/scripts/list/nnpkg_test_list.armv7l-linux.acl_neon
  tests/scripts/list/nnpkg_test_list.armv7l-linux.cpu
  tests/scripts/list/nnpkg_test_list.armv7l-linux.srcn
  tests/scripts/list/nnpkg_test_list.noarch.interp
Labels: PR/ready for review

#3930 [tflite2circle] verify tflite file
  compiler/tflite2circle/src/CircleModel.cpp
Labels: PR/ready for review

#3885 [onert] Copy and package armcompute only in overlay
  Makefile.template
Labels: PR/ready for review

#3918 [circle-quantizer] verify circle file
  compiler/circle-quantizer/src/CircleQuantizer.cpp
Labels: PR/ready for review

#3921 [record-minmax] verify circle file
  compiler/record-minmax/src/RecordMinMax.cpp
Labels: PR/ready for review

#3924 [onert] Move the time of choosing kernel to configure
  runtime/onert/backend/cpu/ops/BinaryArithmeticLayer.cc
  runtime/onert/backend/cpu/ops/BinaryArithmeticLayer.h
  runtime/onert/backend/cpu/ops/ElementwiseBinaryLayer.cc
  runtime/onert/backend/cpu/ops/ElementwiseBinaryLayer.h
  runtime/onert/backend/cpu/ops/PoolLayer.cc
  runtime/onert/backend/cpu/ops/PoolLayer.h
  runtime/onert/backend/cpu/ops/ReduceLayer.cc
  runtime/onert/backend/cpu/ops/ReduceLayer.h
Labels: PR/ready for review, area/onert

#3901 Unify element-wise activation operations to ElementwiseActivation for reducing code duplication
  runtime/onert/backend/acl_cl/KernelGenerator.cc
  runtime/onert/backend/acl_cl/KernelGenerator.h
  runtime/onert/backend/acl_common/Convert.cc
  runtime/onert/backend/acl_common/Convert.h
  runtime/onert/backend/acl_neon/KernelGenerator.cc
  runtime/onert/backend/acl_neon/KernelGenerator.h
  runtime/onert/backend/cpu/KernelGenerator.cc
  runtime/onert/backend/cpu/KernelGenerator.h
  runtime/onert/backend/cpu/ops/ElementwiseActivationLayer.cc
  runtime/onert/backend/cpu/ops/ElementwiseActivationLayer.h
  runtime/onert/backend/cpu/ops/LogisticLayer.cc
  runtime/onert/backend/cpu/ops/LogisticLayer.h
  runtime/onert/backend/cpu/ops/ReLU6Layer.cc
  runtime/onert/backend/cpu/ops/ReLU6Layer.h
  runtime/onert/backend/cpu/ops/ReLULayer.cc
  runtime/onert/backend/cpu/ops/ReLULayer.h
  runtime/onert/backend/cpu/ops/TanhLayer.cc
  runtime/onert/core/include/compiler/StaticShapeInference.h
  runtime/onert/core/include/exec/DynamicShapeInference.h
  runtime/onert/core/include/ir/Operations.Include.h
  runtime/onert/core/include/ir/Operations.lst
  runtime/onert/core/include/ir/operation/ElementwiseActivation.h
  runtime/onert/core/include/ir/operation/Logistic.h
  runtime/onert/core/include/ir/operation/ReLU.h
  runtime/onert/core/include/ir/operation/ReLU1.h
  runtime/onert/core/include/ir/operation/ReLU6.h
  runtime/onert/core/include/ir/operation/Tanh.h
  runtime/onert/core/src/compiler/OperationValidator.cc
  runtime/onert/core/src/compiler/OperationValidator.h
  runtime/onert/core/src/compiler/StaticShapeInference.cc
  runtime/onert/core/src/exec/DynamicShapeInference.cc
  runtime/onert/core/src/interp/InterpOps.lst
  runtime/onert/core/src/interp/operations/ElementwiseActivations.cc
  runtime/onert/core/src/interp/operations/Logistic.cc
  runtime/onert/core/src/ir/OperationDumper.cc
  runtime/onert/core/src/ir/OperationDumper.h
  runtime/onert/core/src/ir/operation/ElementwiseActivation.cc
  runtime/onert/core/src/ir/operation/Logistic.cc
  runtime/onert/core/src/ir/operation/ReLU.cc
  runtime/onert/core/src/ir/operation/ReLU1.cc
  runtime/onert/core/src/ir/operation/ReLU6.cc
  runtime/onert/core/src/ir/operation/Tanh.cc
  runtime/onert/frontend/base_loader/include/base_loader.h
  runtime/onert/frontend/nnapi/wrapper/OperationFactory.cc
Labels: PR/ready for review, area/onert

#3900 [tools] Introduce github release tool
  tools/release_tool/README.md
  tools/release_tool/git_release.sh
Labels: PR/ready for review

#3945 [onert] Copyright fix
  compute/ARMComputeEx/src/runtime/NEON/functions/NETransposeConvLayer.cpp
  compute/cker/include/cker/eigen/eigen_convolution_helpers.h
  compute/cker/include/cker/eigen/eigen_spatial_convolutions.h
  compute/cker/include/cker/neon/neon_check.h
  infra/nnfw/command/copyright-check
  runtime/contrib/android/api/src/main/native/onert-native-api.h
Labels: PR/ready for review

#3939 [onert/test] Operation backend test on one_op_tests
  tests/nnfw_api/CMakeLists.txt
  tests/nnfw_api/src/GenModelTest.h
  tests/nnfw_api/src/one_op_tests/Add.cc
  tests/nnfw_api/src/one_op_tests/AveragePool2D.cc
  tests/nnfw_api/src/one_op_tests/Cos.cc
  tests/nnfw_api/src/one_op_tests/L2Normalization.cc
  tests/nnfw_api/src/one_op_tests/Pad.cc
  tests/nnfw_api/src/one_op_tests/PadV2.cc
Labels: PR/ready for review

#3940 [luci-interpreter] Add assert condition of CircleTransposeConv
  compiler/luci-interpreter/src/loader/KernelBuilder.cpp
Labels: PR/ready for review

#3947 [tflite2circle] Support SparsityParameters
  compiler/tflite2circle/src/CircleModel.cpp
  compiler/tflite2circle/src/DataLookup.cpp
  compiler/tflite2circle/src/DataLookup.h
Labels: PR/ready for review

#3958 [luci] Add bias attribute to CircleTrasnposeConv IR
  compiler/luci/import/src/Nodes/CircleTransposeConv.cpp
  compiler/luci/lang/include/luci/IR/Nodes/CircleTransposeConv.h
  compiler/luci/lang/src/Nodes/CircleTransposeConv.test.cpp
Labels: PR/ready for review

#3959 [TensorFlowLiteRecipes] Add test.rule to Net_TConv_BN_000
  res/TensorFlowLiteRecipes/Net_TConv_BN_000/test.rule
Labels: PR/ready for review

#3948 [onert] Make acl's KernelGenerators use generateLayer
  runtime/onert/backend/acl_cl/KernelGenerator.cc
  runtime/onert/backend/acl_common/AclKernelGen.h
  runtime/onert/backend/acl_neon/KernelGenerator.cc
Labels: PR/ready for review, area/onert

#3952 [onert] Remove duplicated codes from Reader/View for shape::feature
  runtime/onert/core/src/exec/feature/nchw/Reader.h
  runtime/onert/core/src/exec/feature/nchw/View.h
  runtime/onert/core/src/exec/feature/nhwc/Reader.h
  runtime/onert/core/src/exec/feature/nhwc/View.h
Labels: PR/ready for review, area/onert

#3967 [tests] exclude TransposeConv test from nnpkg test of acl_cl, acl_neon
  tests/scripts/list/nnpkg_test_list.armv7l-linux.acl_cl
  tests/scripts/list/nnpkg_test_list.armv7l-linux.acl_neon
Labels: PR/ready for review

#3971 [luci] Introduce FuseBatchNormWithTConv pass
  compiler/luci/pass/include/luci/CircleOptimizer.h
  compiler/luci/pass/include/luci/Pass/FuseBatchNormWithTConv.h
  compiler/luci/pass/src/CircleOptimizer.cpp
  compiler/luci/pass/src/FuseBatchNormWithTConv.cpp
Labels: PR/ready for review

#3972 [onert/test] Skip running test on tizen_xu4_test.sh script
  infra/scripts/tizen_xu4_test.sh
Labels: PR/ready for review

#3979 [circle2circle] Add FuseBatchNormWithTConv option
  compiler/circle2circle/src/Circle2Circle.cpp
Labels: PR/ready for review

#3984 [onert] Reduce lines of OperationDumper
  runtime/onert/core/src/ir/OperationDumper.cc
Labels: PR/ready for review, area/onert

#3985 [luci-interpreter] Add bias attribute to TransposeConv
  compiler/luci-interpreter/src/loader/KernelBuilder.cpp
  compiler/luci-interpreter/src/loader/KernelBuilder.test.cpp
Labels: PR/ready for review

#3988 [onert] Replace AclCLFunction with AclFunction
  runtime/onert/backend/acl_cl/KernelGenerator.cc
  runtime/onert/backend/acl_common/AclFunction.h
  runtime/onert/backend/acl_common/Convert.cc
  runtime/onert/backend/acl_common/Convert.h
Labels: PR/ready for review, area/onert

#3969 [onert] Enable tflite_run on tizen build
  infra/nnfw/cmake/options/options_aarch64-tizen.cmake
  infra/nnfw/cmake/options/options_armv7l-tizen.cmake
Labels: PR/ready for review

#3983 [tflitefile_tool] Support leaky_relu in select_operator.py
  tools/tflitefile_tool/select_operator.py
Labels: PR/ready for review

#3974 [onert] Support acl backend LeakyRelu
  runtime/onert/backend/acl_common/Convert.cc
  runtime/onert/core/include/ir/operation/ElementwiseActivation.h
  runtime/onert/core/src/ir/OperationDumper.cc
  runtime/onert/frontend/base_loader/include/base_loader.h
  tests/nnfw_api/src/CircleGen.cc
  tests/nnfw_api/src/CircleGen.h
  tests/nnfw_api/src/GenModelTest.h
  tests/nnfw_api/src/one_op_tests/LeakyRelu.cc
Labels: PR/ready for review

#3982 [onert/test] Random uint8 input value generation for tflite_run
  tests/tools/tflite_run/src/tflite_run.cc
Labels: PR/ready for review

#3997 [onert/nnapi] Handle param initialize warning
  runtime/onert/frontend/nnapi/wrapper/OperationFactory.cc
Labels: PR/ready for review

#3998 [onert] Do nothing when 'passed shape of nnfw_set_tensorinfo() == model shape'
  runtime/onert/api/src/nnfw_api_internal.cc
Labels: PR/ready for review

#3980 [circle2circle-dredd-recipe-test] Add Net_TConv_BN_000 test
  compiler/circle2circle-dredd-recipe-test/test.lst
Labels: PR/ready for review

#3978 [one-cmds] Revise one-import-tf
  compiler/one-cmds/one-import-tf
Labels: PR/ready for review

#4003 [acl-ex] Check reduce axis set size before use
  compute/ARMComputeEx/src/runtime/CL/functions/CLReduceOperation.cpp
Labels: PR/ready for review

#4009 [onert/cpu] Optimized cpu backend kernel for quantized arithmetic operation
  compute/cker/include/cker/operation/optimized/BinaryArithmeticOps.h
Labels: PR/ready for review

#3949 [onert] Merge acl's ConstantInitializer into AclConstantInitializer
  runtime/onert/backend/acl_cl/ConstantInitializer.cc
  runtime/onert/backend/acl_cl/ConstantInitializer.h
  runtime/onert/backend/acl_common/AclConstantInitializer.cc
  runtime/onert/backend/acl_common/AclConstantInitializer.h
  runtime/onert/backend/acl_neon/ConstantInitializer.cc
  runtime/onert/backend/acl_neon/ConstantInitializer.h
  runtime/onert/core/include/backend/IConstantInitializer.h
Labels: PR/ready for review, area/onert

#3987 [onert] Make feature::View reuses feature::Reader
  runtime/onert/core/src/exec/feature/nchw/Reader.h
  runtime/onert/core/src/exec/feature/nchw/View.h
  runtime/onert/core/src/exec/feature/nhwc/Reader.h
  runtime/onert/core/src/exec/feature/nhwc/View.h
Labels: PR/ready for review, area/onert

#4010 [onert] Renaming member var name of IODescription
  runtime/onert/core/include/exec/IODescription.h
  runtime/onert/core/src/exec/Execution.cc
  runtime/onert/core/src/exec/ExecutorBase.cc
Labels: PR/ready for review

#4015 [onert] Remove unused stuff in CF KernelGen
  runtime/onert/core/src/backend/controlflow/KernelGenerator.cc
  runtime/onert/core/src/backend/controlflow/KernelGenerator.h
Labels: trivial

#4020 [onert] Fix log generation fail for LeakyRelu
  runtime/onert/core/src/ir/operation/ElementwiseActivation.cc
Labels: PR/ready for review

#4014 [onert/acl-cl] Support ResizeNearestNeighbor operation
  runtime/onert/backend/acl_cl/KernelGenerator.cc
  runtime/onert/backend/acl_cl/KernelGenerator.h
  runtime/onert/core/include/ir/Operations.Include.h
  runtime/onert/core/include/ir/Operations.lst
  runtime/onert/core/include/ir/operation/ResizeNearestNeighbor.h
  runtime/onert/core/src/ir/operation/ResizeNearestNeighbor.cc
  runtime/onert/frontend/base_loader/include/base_loader.h
  tests/nnfw_api/src/CircleGen.cc
  tests/nnfw_api/src/CircleGen.h
  tests/nnfw_api/src/one_op_tests/ResizeNearestNeighbor.cc
Labels: PR/ready for review

#4007 [onert] Use CachedData instead of MMapedData
  runtime/onert/frontend/base_loader/include/base_loader.h
Labels: PR/ready for review, area/onert

#4012 [onert/cpu] Implement Rank cpu backend
  runtime/onert/backend/cpu/KernelGenerator.cc
  runtime/onert/backend/cpu/KernelGenerator.h
  runtime/onert/backend/cpu/ops/RankLayer.cc
  runtime/onert/backend/cpu/ops/RankLayer.h
  runtime/onert/core/include/ir/Operations.Include.h
  runtime/onert/core/include/ir/Operations.lst
  runtime/onert/core/include/ir/operation/Rank.h
  runtime/onert/core/src/ir/OperationDumper.cc
  runtime/onert/core/src/ir/OperationDumper.h
  runtime/onert/core/src/ir/operation/Rank.cc
  runtime/onert/frontend/base_loader/include/base_loader.h
  tests/nnfw_api/src/CircleGen.cc
  tests/nnfw_api/src/CircleGen.h
  tests/nnfw_api/src/one_op_tests/Rank.cc
Labels: PR/ready for review

#4027 [onert/test] Fix backend mapping in nnpackage_run
  tests/tools/nnpackage_run/src/nnpackage_run.cc
Labels: PR/ready for review
