Repository Samsung/ONE, pull requests merged in 2020-06, with the labels that each got.

#1526 [luci/service] Enable shape/type inference for Floor Op
  compiler/luci/service/src/CircleShapeInferenceRule.cpp
  compiler/luci/service/src/CircleTypeInferenceRule.cpp
Labels: PR/ready for review

#1670 [luci] remove unused var in import
  compiler/luci/import/src/Nodes/CircleWhile.cpp
Labels: PR/ready for review

#1619 [TensorFlowPythonExamples] fix placeholder shape in expand_dims_00
  res/TensorFlowPythonExamples/examples/expand_dims_00/__init__.py
Labels: PR/ready for review

#1644 [onert] Rename internal quantization type enum name
  runtime/onert/api/src/CustomKernel.cc
  runtime/onert/api/src/nnfw_api_internal.cc
  runtime/onert/backend/acl_cl/KernelGenerator.cc
  runtime/onert/backend/acl_common/Convert.cc
  runtime/onert/backend/cpu/ShapeFixer.cc
  runtime/onert/backend/cpu/ops/AbsLayer.cc
  runtime/onert/backend/cpu/ops/AddLayer.cc
  runtime/onert/backend/cpu/ops/ArgMinMaxLayer.cc
  runtime/onert/backend/cpu/ops/AvgPoolLayer.cc
  runtime/onert/backend/cpu/ops/CompareLayer.cc
  runtime/onert/backend/cpu/ops/ConcatLayer.cc
  runtime/onert/backend/cpu/ops/ConvolutionLayer.cc
  runtime/onert/backend/cpu/ops/CosLayer.cc
  runtime/onert/backend/cpu/ops/DepthwiseConvolutionLayer.cc
  runtime/onert/backend/cpu/ops/DivLayer.cc
  runtime/onert/backend/cpu/ops/ExpLayer.cc
  runtime/onert/backend/cpu/ops/FullyConnectedLayer.cc
  runtime/onert/backend/cpu/ops/GatherLayer.cc
  runtime/onert/backend/cpu/ops/LogLayer.cc
  runtime/onert/backend/cpu/ops/LogisticLayer.cc
  runtime/onert/backend/cpu/ops/MaxLayer.cc
  runtime/onert/backend/cpu/ops/MaxPoolLayer.cc
  runtime/onert/backend/cpu/ops/MeanLayer.cc
  runtime/onert/backend/cpu/ops/MinLayer.cc
  runtime/onert/backend/cpu/ops/MulLayer.cc
  runtime/onert/backend/cpu/ops/NegLayer.cc
  runtime/onert/backend/cpu/ops/OneHotLayer.cc
  runtime/onert/backend/cpu/ops/OperationUtils.cc
  runtime/onert/backend/cpu/ops/PackLayer.cc
  runtime/onert/backend/cpu/ops/PadLayer.cc
  runtime/onert/backend/cpu/ops/ReLULayer.cc
  runtime/onert/backend/cpu/ops/RsqrtLayer.cc
  runtime/onert/backend/cpu/ops/ShapeLayer.cc
  runtime/onert/backend/cpu/ops/SinLayer.cc
  runtime/onert/backend/cpu/ops/SliceLayer.cc
  runtime/onert/backend/cpu/ops/SoftMaxLayer.cc
  runtime/onert/backend/cpu/ops/SplitLayer.cc
  runtime/onert/backend/cpu/ops/StridedSliceLayer.cc
  runtime/onert/backend/cpu/ops/SubLayer.cc
  runtime/onert/backend/cpu/ops/TanhLayer.cc
  runtime/onert/backend/cpu/ops/TileLayer.cc
  runtime/onert/backend/cpu/ops/TransposeLayer.cc
  runtime/onert/backend/cpu/ops/UnpackLayer.cc
  runtime/onert/core/include/backend/IConstantInitializer.h
  runtime/onert/core/include/exec/IPermuteFunction.h
  runtime/onert/core/include/ir/DataType.h
  runtime/onert/core/src/compiler/HEScheduler.cc
  runtime/onert/core/src/compiler/OperationValidator.cc
  runtime/onert/core/src/exec/ExecutionObservers.cc
  runtime/onert/core/src/exec/ExecutorBase.cc
  runtime/onert/core/src/interp/operations/Gather.cc
  runtime/onert/frontend/base_loader/include/base_loader.h
  runtime/onert/frontend/nnapi/wrapper/ANeuralNetworksModel.cc
  runtime/onert/frontend/nnapi/wrapper/NNAPIConvert.cc
  runtime/onert/frontend/nnapi/wrapper/OperationFactory.cc
Labels: PR/ready for review

#1609 [onert] introduce pipe to filter OperandIndexSequence
  runtime/onert/core/include/ir/OperandIndexSequence.h
  runtime/onert/core/src/compiler/Fp32ToFp16Converter.cc
  runtime/onert/core/src/compiler/Linear.cc
  runtime/onert/core/src/ir/GraphIterator.cc
  runtime/onert/core/src/ir/LoweredGraph.cc
  runtime/onert/core/src/ir/pass/ConstantInsertionPass.cc
  runtime/onert/core/src/ir/pass/ConstantLoweringPass.cc
  runtime/onert/core/src/ir/pass/PermutationOperationPass.cc
  runtime/onert/core/src/ir/verifier/Verifier.cc
Labels: PR/ready for review

#1664 [onert] Modify using Round enum instead of ZerosLike
  runtime/onert/backend/cpu/KernelGenerator.cc
Labels: PR/ready for review

#1657 [onert] Update tensor managers of controlflow from cpu backend
  runtime/onert/core/src/backend/controlflow/DynamicTensorManager.cc
  runtime/onert/core/src/backend/controlflow/DynamicTensorManager.h
  runtime/onert/core/src/backend/controlflow/MemoryManager.cc
  runtime/onert/core/src/backend/controlflow/MemoryManager.h
  runtime/onert/core/src/backend/controlflow/StaticTensorManager.cc
  runtime/onert/core/src/backend/controlflow/StaticTensorManager.h
  runtime/onert/core/src/backend/controlflow/TensorBuilder.cc
  runtime/onert/core/src/backend/controlflow/TensorBuilder.h
  runtime/onert/core/src/backend/controlflow/TensorRegistry.h
  runtime/onert/core/src/backend/controlflow/operand/Tensor.h
Labels: PR/ready for review, area/onert

#1704 [TensorFlowPythonExamples] Add reduce_all operator
  res/TensorFlowPythonExamples/examples/reduce_all/__init__.py
Labels: PR/ready for review

#1466 [luci/lang] Added L2Normalize to LUCI IR
  compiler/luci/lang/include/luci/IR/CircleNodes.h
  compiler/luci/lang/include/luci/IR/CircleNodes.lst
  compiler/luci/lang/include/luci/IR/Nodes/CircleL2Normalize.h
Labels: PR/ready for review

#1719 [packaging] Update generated nnapi test tar
  packaging/nnapi_test_generated.tar.gz
Labels: PR/ready for review

#1687 [onert/test] Set backend on tflite loader test
  infra/scripts/common.sh
  infra/scripts/test_ubuntu_runtime.sh
Labels: PR/ready for review

#1659 [onert] Enable dynamic tensor with controlflow operation
  runtime/onert/backend/acl_common/IACLTensor.h
  runtime/onert/core/include/backend/ITensor.h
  runtime/onert/core/src/backend/controlflow/kernel/IfLayer.cc
  runtime/onert/core/src/backend/controlflow/kernel/WhileLayer.cc
  runtime/onert/core/src/exec/ExecutorBase.cc
  runtime/onert/core/src/exec/ExecutorBase.h
  runtime/onert/core/src/interp/Tensor.h
Labels: PR/ready for review, area/onert

#1716 [onert] Remove experimental nnpack backend
  infra/cmake/packages/CpuinfoSourceConfig.cmake
  infra/cmake/packages/Enum34SourceConfig.cmake
  infra/cmake/packages/FP16SourceConfig.cmake
  infra/cmake/packages/FXdivSourceConfig.cmake
  infra/cmake/packages/NNPACKConfig.cmake
  infra/cmake/packages/NNPACKSourceConfig.cmake
  infra/cmake/packages/OpcodesSourceConfig.cmake
  infra/cmake/packages/PSIMDSourceConfig.cmake
  infra/cmake/packages/PeachpySourceConfig.cmake
  infra/cmake/packages/PthreadpoolSourceConfig.cmake
  infra/cmake/packages/SixSourceConfig.cmake
  infra/nnfw/cmake/CfgOptionFlags.cmake
  infra/nnfw/cmake/options/options_aarch64-tizen.cmake
  infra/nnfw/cmake/options/options_armv7l-tizen.cmake
  runtime/contrib/hi_perf_cpu/CMakeLists.txt
  runtime/contrib/hi_perf_cpu/HighPerformanceBackend.test.cc
  runtime/contrib/hi_perf_cpu/KernelGenerator.cc
  runtime/contrib/hi_perf_cpu/KernelGenerator.h
  runtime/contrib/hi_perf_cpu/TensorBuilder.cc
  runtime/contrib/hi_perf_cpu/TensorBuilder.h
Labels: PR/ready for review

#1724 [infra] Update tizen_xu4_test script
  infra/scripts/tizen_xu4_test.sh
Labels: PR/ready for review

#1660 [onert] Modify `ir::OpSequence` to be index based
  runtime/onert/backend/acl_cl/Backend.h
  runtime/onert/backend/acl_cl/KernelGenerator.cc
  runtime/onert/backend/acl_cl/KernelGenerator.h
  runtime/onert/backend/acl_neon/Backend.h
  runtime/onert/backend/acl_neon/KernelGenerator.cc
  runtime/onert/backend/acl_neon/KernelGenerator.h
  runtime/onert/backend/cpu/Backend.h
  runtime/onert/backend/cpu/KernelGenerator.cc
  runtime/onert/backend/cpu/KernelGenerator.h
  runtime/onert/core/include/backend/IShapeFixer.h
  runtime/onert/core/include/exec/ExecutionObservers.h
  runtime/onert/core/include/exec/FunctionSequence.h
  runtime/onert/core/include/ir/OpSequence.h
  runtime/onert/core/include/ir/OpSequences.h
  runtime/onert/core/include/ir/OperationVisitor.h
  runtime/onert/core/include/util/ShapeInference.h
  runtime/onert/core/src/backend/controlflow/Backend.h
  runtime/onert/core/src/backend/controlflow/KernelGenerator.cc
  runtime/onert/core/src/backend/controlflow/KernelGenerator.h
  runtime/onert/core/src/compiler/ExecutorFactory.cc
  runtime/onert/core/src/compiler/Fp32ToFp16Converter.cc
  runtime/onert/core/src/compiler/Linear.cc
  runtime/onert/core/src/dumper/dot/DotDumper.cc
  runtime/onert/core/src/dumper/dot/DotSubgraphInfo.cc
  runtime/onert/core/src/dumper/dot/DotSubgraphInfo.h
  runtime/onert/core/src/exec/DataflowExecutor.cc
  runtime/onert/core/src/exec/DataflowExecutor.h
  runtime/onert/core/src/exec/ExecutionObservers.cc
  runtime/onert/core/src/exec/FunctionSequence.cc
  runtime/onert/core/src/exec/LinearExecutor.cc
  runtime/onert/core/src/ir/LoweredGraph.cc
  runtime/onert/core/src/ir/OpSequence.cc
  runtime/onert/core/src/ir/OpSequences.cc
  runtime/onert/core/src/ir/pass/PermutationInsertionPass.cc
  runtime/onert/core/src/ir/pass/PermutationOperationPass.cc
Labels: PR/ready for review, area/onert

#1720 [oneapi_test] Implement realpath command
  tests/scripts/oneapi_test/install_oneapi_test_nnpackages.sh
Labels: PR/ready for review

#1722 [luci/import] added L2 Norm to LUCI import
  compiler/luci/import/include/luci/Import/Nodes.h
  compiler/luci/import/include/luci/Import/Nodes/CircleL2Normalize.h
  compiler/luci/import/src/GraphBuilderRegistry.cpp
  compiler/luci/import/src/Nodes/CircleL2Normalize.cpp
Labels: PR/ready for review

#1723 [luci/exporter] added L2 Normalize to luci exporter
  compiler/luci/export/src/CircleOperationExporter.cpp
Labels: PR/ready for review

#1744 [onert] nnapi test generator will use current environment's python
  tests/nnapi/nnapi_test_generator/android-10/cts_generator.py
Labels: PR/ready for review

#1743 [circle2circle-dredd-recipe-test] Rename circle2circle-dredd-pbtxt-test
  compiler/circle2circle-dredd-recipe-test/CMakeLists.txt
  compiler/circle2circle-dredd-recipe-test/README.md
  compiler/circle2circle-dredd-recipe-test/requires.cmake
  compiler/circle2circle-dredd-recipe-test/test.lst
  compiler/circle2circle-dredd-recipe-test/testall.sh
Labels: PR/ready for review

#1745 [tflchef] Support All custom operator
  compiler/tflchef/core/src/CustomOp/All.cpp
  compiler/tflchef/core/src/CustomOp/All.h
  compiler/tflchef/core/src/OpChef.def
  compiler/tflchef/core/src/OpChefs.h
  compiler/tflchef/proto/tflchef.proto
Labels: PR/ready for review

#1748 [TensorFlowLiteRecipes] Add All custom operator
  res/TensorFlowLiteRecipes/All_000/test.recipe
Labels: PR/ready for review

#1718 [onert] Introduce einsum operation in nnapi extension
  runtime/nnapi-header/include/NeuralNetworksEx.h
Labels: PR/ready for review

#1749 [onert] Use haveUnspecifiedDims helper in nnapi frontend
  runtime/onert/frontend/nnapi/wrapper/ANeuralNetworksExecution.cc
Labels: PR/ready for review

#1699 [onert] filter out undefined operand before accessing operand
  runtime/onert/backend/cpu/KernelGenerator.cc
  runtime/onert/core/include/backend/ITensorRegister.h
  runtime/onert/core/include/ir/OperandIndexSequence.h
  runtime/onert/core/src/compiler/ExecutorFactory.cc
  runtime/onert/core/src/compiler/Fp32ToFp16Converter.cc
  runtime/onert/core/src/compiler/HEScheduler.cc
  runtime/onert/core/src/compiler/Linear.cc
  runtime/onert/core/src/ir/Graph.cc
  runtime/onert/core/src/ir/LoweredGraph.cc
  runtime/onert/core/src/ir/pass/ConstantInsertionPass.cc
  runtime/onert/core/src/ir/pass/ConstantLoweringPass.cc
  runtime/onert/core/src/ir/pass/PermutationOperationPass.cc
  runtime/onert/core/src/ir/verifier/Verifier.cc
Labels: PR/ready for review

#1679 [onert] Undefined OperandIndex will be printed "undefined"
  runtime/onert/core/include/ir/OperandIndexSequence.h
  runtime/onert/core/include/util/Index.h
  runtime/onert/core/src/ir/OperandIndexSequence.cc
  runtime/onert/core/src/ir/OperationDumper.cc
Labels: PR/ready for review

#1695 [onert/lib] Move RandomGenerator class
  runtime/libs/misc/include/misc/RandomGenerator.h
  runtime/libs/misc/src/RandomGenerator.cpp
  runtime/libs/tflite/include/tflite/Diff.h
  runtime/libs/tflite/src/Diff.cpp
  tests/tools/nnpackage_run/src/nnpackage_run.cc
  tests/tools/tflite_loader/src/tflite_loader.cc
  tests/tools/tflite_run/src/tflite_run.cc
Labels: PR/ready for review, trivial

#1713 [onert/cpu] Rename tensor shape getter
  runtime/onert/backend/cpu/ops/AbsLayer.cc
  runtime/onert/backend/cpu/ops/AddLayer.cc
  runtime/onert/backend/cpu/ops/ArgMinMaxLayer.cc
  runtime/onert/backend/cpu/ops/AvgPoolLayer.cc
  runtime/onert/backend/cpu/ops/CastLayer.cc
  runtime/onert/backend/cpu/ops/CompareLayer.cc
  runtime/onert/backend/cpu/ops/ConcatLayer.cc
  runtime/onert/backend/cpu/ops/ConvolutionLayer.cc
  runtime/onert/backend/cpu/ops/CosLayer.cc
  runtime/onert/backend/cpu/ops/DepthwiseConvolutionLayer.cc
  runtime/onert/backend/cpu/ops/DivLayer.cc
  runtime/onert/backend/cpu/ops/ExpLayer.cc
  runtime/onert/backend/cpu/ops/FillLayer.cc
  runtime/onert/backend/cpu/ops/FullyConnectedLayer.cc
  runtime/onert/backend/cpu/ops/GatherLayer.cc
  runtime/onert/backend/cpu/ops/LogLayer.cc
  runtime/onert/backend/cpu/ops/LogicalNotLayer.cc
  runtime/onert/backend/cpu/ops/LogicalOrLayer.cc
  runtime/onert/backend/cpu/ops/LogisticLayer.cc
  runtime/onert/backend/cpu/ops/MaxLayer.cc
  runtime/onert/backend/cpu/ops/MaxPoolLayer.cc
  runtime/onert/backend/cpu/ops/MeanLayer.cc
  runtime/onert/backend/cpu/ops/MinLayer.cc
  runtime/onert/backend/cpu/ops/MulLayer.cc
  runtime/onert/backend/cpu/ops/NegLayer.cc
  runtime/onert/backend/cpu/ops/OneHotLayer.cc
  runtime/onert/backend/cpu/ops/OperationUtils.h
  runtime/onert/backend/cpu/ops/PackLayer.cc
  runtime/onert/backend/cpu/ops/PadLayer.cc
  runtime/onert/backend/cpu/ops/PowLayer.cc
  runtime/onert/backend/cpu/ops/ReLULayer.cc
  runtime/onert/backend/cpu/ops/ReduceLayer.cc
  runtime/onert/backend/cpu/ops/ReverseLayer.cc
  runtime/onert/backend/cpu/ops/RoundLayer.cc
  runtime/onert/backend/cpu/ops/RsqrtLayer.cc
  runtime/onert/backend/cpu/ops/SelectLayer.cc
  runtime/onert/backend/cpu/ops/SinLayer.cc
  runtime/onert/backend/cpu/ops/SliceLayer.cc
  runtime/onert/backend/cpu/ops/SoftMaxLayer.cc
  runtime/onert/backend/cpu/ops/SplitLayer.cc
  runtime/onert/backend/cpu/ops/SquaredDiffLayer.cc
  runtime/onert/backend/cpu/ops/StridedSliceLayer.cc
  runtime/onert/backend/cpu/ops/SubLayer.cc
  runtime/onert/backend/cpu/ops/TanhLayer.cc
  runtime/onert/backend/cpu/ops/TileLayer.cc
  runtime/onert/backend/cpu/ops/TransposeLayer.cc
  runtime/onert/backend/cpu/ops/UnpackLayer.cc
  runtime/onert/backend/cpu/ops/ZerosLikeLayer.cc
Labels: PR/ready for review, trivial

#1602 [onert] keep optional tensor supporting ops in list
  runtime/onert/frontend/base_loader/include/base_loader.h
Labels: PR/ready for review

#1763 [onert] Fix implicit instantiation of undefined template
  runtime/onert/core/include/util/Index.h
Labels: PR/ready for review, area/onert

#1762 [TensorFlowPythonExamples] Add max_pool_with_argmax operator
  res/TensorFlowPythonExamples/examples/max_pool_with_argmax/__init__.py
Labels: PR/ready for review

#1765 [tf2tfliteV2] Add short option
  compiler/tf2tfliteV2/tf2tfliteV2.py
Labels: PR/ready for review

#1731 [luci/service] added L2 Normalize to luci service
  compiler/luci/service/src/CircleShapeInferenceRule.cpp
  compiler/luci/service/src/CircleTypeInferenceRule.cpp
Labels: PR/ready for review

#1747 [onert] Catch exception by input generation on tflite loader
  tests/tools/tflite_loader/src/tflite_loader.cc
Labels: PR/ready for review, trivial

#1454 [onert] Add shape inference for Cos
  runtime/onert/core/include/util/ShapeInference.h
  runtime/onert/core/src/util/shapeinf/Cos.cc
  tests/nnapi/nnapi_gtest.skip.aarch64-linux.acl_cl
  tests/nnapi/nnapi_gtest.skip.aarch64-linux.acl_neon
  tests/nnapi/nnapi_gtest.skip.armv7l-linux.acl_cl
  tests/nnapi/nnapi_gtest.skip.armv7l-linux.acl_neon
  tests/nnapi/nnapi_gtest.skip.noarch.interp
  tests/nnapi/specs/Ex/cos_ex_dynamic_nnfw.mod.py
Labels: PR/ready for review

#1669 [luci-interpreter] Add Mean kernel
  compiler/luci-interpreter/src/KernelBuilder.cpp
  compiler/luci-interpreter/src/KernelBuilder.h
  compiler/luci-interpreter/src/core/KernelParams.h
  compiler/luci-interpreter/src/kernels/CMakeLists.txt
  compiler/luci-interpreter/src/kernels/Mean.cpp
  compiler/luci-interpreter/src/kernels/Mean.h
  compiler/luci-interpreter/src/kernels/Mean.test.cpp
Labels: PR/ready for review

#1778 [luci] Rename method of CircleTopKV2Out and CircleUnPackOut
  compiler/luci/import/src/Nodes/CircleTopKV2.cpp
  compiler/luci/import/src/Nodes/CircleUnpack.cpp
  compiler/luci/lang/include/luci/IR/Nodes/CircleTopKV2Out.h
  compiler/luci/lang/include/luci/IR/Nodes/CircleUnpackOut.h
  compiler/luci/lang/src/Nodes/CircleTopKV2Out.test.cpp
  compiler/luci/lang/src/Nodes/CircleUnpackOut.test.cpp
  compiler/luci/logex/src/FormattedGraph.cpp
  compiler/luci/service/src/CircleShapeInferenceRule.cpp
  compiler/luci/service/src/CircleTypeInferenceRule.cpp
Labels: PR/ready for review

#1590 [circle dump] Added L2Norm to circle dump
  compiler/circledump/src/OpPrinter.cpp
Labels: PR/ready for review

#1755 [onert] Apply setting input tensors as dynamic for all subgraphs
  runtime/onert/core/src/compiler/Compiler.cc
Labels: PR/ready for review, area/onert

#1785 [luci] Introduce CircleCustomOut IR
  compiler/luci/lang/include/luci/IR/CircleNodes.h
  compiler/luci/lang/include/luci/IR/CircleNodes.lst
  compiler/luci/lang/include/luci/IR/Nodes/CircleCustomOut.h
  compiler/luci/lang/src/Nodes/CircleCustomOut.test.cpp
Labels: PR/ready for review

#1790 [tfldump] Added comment about PRelu to tfldump
  compiler/tfldump/src/OpPrinter.cpp
Labels: PR/ready for review

#1791 [circledump] Added comment about PRelu to circledump
  compiler/circledump/src/OpPrinter.cpp
Labels: PR/ready for review

#1766 [luci/logex] added L2 Normalize to luci logex
  compiler/luci/logex/src/FormattedGraph.cpp
Labels: PR/ready for review

#1736 [luci/export] Added PRelu to Luci Export
  compiler/luci/export/src/CircleOperationExporter.cpp
Labels: PR/ready for review

#1735 [LUCI/import] Added PRelu to luci import
  compiler/luci/import/include/luci/Import/Nodes.h
  compiler/luci/import/include/luci/Import/Nodes/CirclePRelu.h
  compiler/luci/import/src/GraphBuilderRegistry.cpp
  compiler/luci/import/src/Nodes/CirclePRelu.cpp
Labels: PR/ready for review

#1783 [res/pyExamples] Updated python example for PRelu
  res/TensorFlowPythonExamples/examples/prelu/__init__.py
Labels: PR/ready for review

#1801 [res] Add TF python examples of Squeeze op
  res/TensorFlowPythonExamples/examples/squeeze_1/__init__.py
  res/TensorFlowPythonExamples/examples/squeeze_2/__init__.py
Labels: PR/ready for review

#1777 [cmake] Remove arm compute scon script for tizen
  infra/cmake/packages/ARMCompute/SConstruct
  infra/cmake/packages/ARMComputeConfig.cmake
Labels: PR/ready for review

#1648 [onert] ShapeInference for ArgMax
  runtime/onert/core/include/util/ShapeInference.h
  runtime/onert/core/src/util/shapeinf/ArgMax.cc
  tests/nnapi/nnapi_gtest.skip.aarch64-linux.acl_cl
  tests/nnapi/nnapi_gtest.skip.aarch64-linux.acl_neon
  tests/nnapi/nnapi_gtest.skip.armv7l-linux.acl_cl
  tests/nnapi/nnapi_gtest.skip.armv7l-linux.acl_neon
  tests/nnapi/nnapi_gtest.skip.noarch.interp
  tests/nnapi/specs/V1_2/argmax_dynamic_nnfw.mod.py
Labels: PR/ready for review

#1757 [onert] Remove rank info from kernels of controlflow
  runtime/onert/core/include/exec/IPermuteFunction.h
  runtime/onert/core/src/backend/controlflow/KernelGenerator.cc
  runtime/onert/core/src/backend/controlflow/kernel/IfLayer.cc
  runtime/onert/core/src/backend/controlflow/kernel/PermuteLayer.h
  runtime/onert/core/src/backend/controlflow/kernel/WhileLayer.cc
  runtime/onert/core/src/backend/controlflow/kernel/WhileLayer.h
Labels: PR/ready for review, area/onert

#1780 [onert] Update nnapi test generator README.md
  tests/nnapi/nnapi_test_generator/android-10/README.md
Labels: PR/ready for review

#1467 [tfldump] L2 norm in tfldump
  compiler/tfldump/src/OpPrinter.cpp
Labels: PR/ready for review

#1807 Add tensor type argument for DynamicInputGenerator
  tests/nnapi/nnapi_test_generator/android-10/dynamic_tensor.py
  tests/nnapi/specs/Ex/cos_ex_dynamic_nnfw.mod.py
  tests/nnapi/specs/Ex/round_ex_dynamic_nnfw.mod.py
  tests/nnapi/specs/V1_0/add_dynamic_nnfw.mod.py
  tests/nnapi/specs/V1_0/concat_dynamic_nnfw.mod.py
  tests/nnapi/specs/V1_0/logistic_dynamic_nnfw.mod.py
  tests/nnapi/specs/V1_0/softmax_dynamic_nnfw.mod.py
  tests/nnapi/specs/V1_2/abs_dynamic_nnfw.mod.py
  tests/nnapi/specs/V1_2/cast_dynamic_float32_to_int32_nnfw.mod.py
  tests/nnapi/specs/V1_2/exp_dynamic_nnfw.mod.py
  tests/nnapi/specs/V1_2/log_dynamic_nnfw.mod.py
  tests/nnapi/specs/V1_2/neg_dynamic_nnfw.mod.py
  tests/nnapi/specs/V1_2/sub_dynamic_nnfw.mod.py
  tests/nnapi/specs/V1_2/tanh_v1_dynamic_nnfw.mod.py
Labels: PR/ready for review

#1823 [onert] Fix missing tensor_type error for nnapi tests
  tests/nnapi/specs/V1_2/argmax_dynamic_nnfw.mod.py
  tests/nnapi/specs/V1_2/div_dynamic_nnfw.mod.py
  tests/nnapi/specs/V1_2/mul_dynamic_nnfw.mod.py
Labels: PR/ready for review, area/onert

#1813 [luci] Import Log Op
  compiler/luci/import/include/luci/Import/Nodes.h
  compiler/luci/import/include/luci/Import/Nodes/CircleLog.h
  compiler/luci/import/src/GraphBuilderRegistry.cpp
  compiler/luci/import/src/Nodes/CircleLog.cpp
Labels: PR/ready for review

#1756 [onert] Adds shape inference for Zeros_like and its test case.
  runtime/onert/core/include/util/ShapeInference.h
  runtime/onert/core/src/util/shapeinf/ZerosLike.cc
  tests/nnapi/nnapi_gtest.skip.aarch64-linux.acl_cl
  tests/nnapi/nnapi_gtest.skip.aarch64-linux.acl_neon
  tests/nnapi/nnapi_gtest.skip.armv7l-linux.acl_cl
  tests/nnapi/nnapi_gtest.skip.armv7l-linux.acl_neon
  tests/nnapi/nnapi_gtest.skip.noarch.interp
  tests/nnapi/specs/Ex/zeros_like_ex_dynamic_float32.mod.py
Labels: PR/ready for review

#1663 [onert] ShapeInference for Pack
  runtime/onert/core/include/util/ShapeInference.h
  runtime/onert/core/src/util/shapeinf/Pack.cc
  tests/nnapi/nnapi_gtest.skip.aarch64-linux.acl_cl
  tests/nnapi/nnapi_gtest.skip.aarch64-linux.acl_neon
  tests/nnapi/nnapi_gtest.skip.armv7l-linux.acl_cl
  tests/nnapi/nnapi_gtest.skip.armv7l-linux.acl_neon
  tests/nnapi/nnapi_gtest.skip.noarch.interp
  tests/nnapi/specs/Ex/pack_ex_dynamic_nnfw.mod.py
Labels: PR/ready for review

#1658 [onert] Adding shape inference for operations of controlflow
  runtime/onert/core/include/util/ShapeInference.h
  runtime/onert/core/src/util/shapeinf/If.cc
  runtime/onert/core/src/util/shapeinf/Permute.cc
  runtime/onert/core/src/util/shapeinf/While.cc
Labels: PR/ready for review, area/onert

#1827 [cmake] Remove ExternalSource_Get function
  infra/cmake/modules/ExternalSourceTools.cmake
  infra/cmake/packages/ARMComputeSourceConfig.cmake
  infra/cmake/packages/BoostSourceConfig.cmake
  infra/cmake/packages/NoniusSourceConfig.cmake
  infra/nnfw/cmake/packages/AbslSourceConfig.cmake
  infra/nnfw/cmake/packages/EigenSourceConfig.cmake
  infra/nnfw/cmake/packages/FarmhashSourceConfig.cmake
  infra/nnfw/cmake/packages/FlatBuffersSourceConfig.cmake
  infra/nnfw/cmake/packages/GEMMLowpSourceConfig.cmake
  infra/nnfw/cmake/packages/GTestConfig.cmake
  infra/nnfw/cmake/packages/NEON2SSESourceConfig.cmake
  infra/nnfw/cmake/packages/RuySourceConfig.cmake
  infra/nnfw/cmake/packages/TensorFlowSourceConfig.cmake
Labels: PR/ready for review

#1812 [onert] Dynamic Shape Inference considering apply_tensorinfo() after compilation
  runtime/onert/core/src/util/shapeinf/ArgMax.cc
  runtime/onert/core/src/util/shapeinf/Concat.cc
  runtime/onert/core/src/util/shapeinf/ExpandDims.cc
  runtime/onert/core/src/util/shapeinf/Reshape.cc
  runtime/onert/core/src/util/shapeinf/ShapeInference.cc
Labels: PR/ready for review

#1738 [LUCI/service] Added PRelu to luci service
  compiler/luci/service/src/CircleShapeInferenceRule.cpp
  compiler/luci/service/src/CircleTypeInferenceRule.cpp
Labels: PR/ready for review

#1796 [res] Add recipe with dilation in DepthwiseConv2D
  res/TensorFlowLiteRecipes/DeptwiseConv2D_001/test.recipe
  res/TensorFlowLiteRecipes/DeptwiseConv2D_001/test.reverse
Labels: PR/ready for review

#1737 [LUCI/logex] Added PRelu to luci logex
  compiler/luci/logex/src/FormattedGraph.cpp
Labels: PR/ready for review

#1832 [res] Add second Floor Mod recipe
  res/TensorFlowLiteRecipes/FloorMod_001/test.recipe
  res/TensorFlowLiteRecipes/FloorMod_001/test.reverse
Labels: PR/ready for review

#1830 [onert] Add shape inference for sin operation
  runtime/onert/core/include/util/ShapeInference.h
  runtime/onert/core/src/util/shapeinf/Sin.cc
  tests/nnapi/nnapi_gtest.skip.aarch64-linux.acl_cl
  tests/nnapi/nnapi_gtest.skip.aarch64-linux.acl_neon
  tests/nnapi/nnapi_gtest.skip.armv7l-linux.acl_cl
  tests/nnapi/nnapi_gtest.skip.armv7l-linux.acl_neon
  tests/nnapi/nnapi_gtest.skip.noarch.interp
  tests/nnapi/specs/V1_2/sin_dynamic_nnfw.mod.py
Labels: PR/ready for review

#1574 [luci/tests] added L2 Normalize to luci tests
  compiler/luci/tests/test.lst
Labels: PR/ready for review

#1742 [luci-interpreter] Add Split kernel
  compiler/luci-interpreter/src/Interpreter.cpp
  compiler/luci-interpreter/src/KernelBuilder.cpp
  compiler/luci-interpreter/src/KernelBuilder.h
  compiler/luci-interpreter/src/kernels/CMakeLists.txt
  compiler/luci-interpreter/src/kernels/Concatenation.cpp
  compiler/luci-interpreter/src/kernels/Split.cpp
  compiler/luci-interpreter/src/kernels/Split.h
  compiler/luci-interpreter/src/kernels/Split.test.cpp
  compiler/luci-interpreter/src/kernels/TestUtils.h
  compiler/luci-interpreter/src/kernels/Utils.h
Labels: PR/ready for review

#1822 [onert] Set unknown dim (unspecified dim) to -1
  runtime/onert/core/include/ir/Shape.h
  runtime/onert/core/src/ir/Shape.cc
  runtime/onert/frontend/base_loader/include/base_loader.h
  runtime/onert/test/ir/Shape.cc
Labels: PR/ready for review

#1840 [onert] Move internal 3rd party codes
  infra/scripts/docker_coverage_report.sh
  runtime/3rdparty/.FORMATDENY
  runtime/3rdparty/CMakeLists.txt
  runtime/3rdparty/half/CMakeLists.txt
  runtime/3rdparty/half/include/Half.h
  runtime/3rdparty/half/include/half/.FORMATDENY
  runtime/3rdparty/half/include/half/ChangeLog.txt
  runtime/3rdparty/half/include/half/LICENSE.txt
  runtime/3rdparty/half/include/half/README.txt
  runtime/3rdparty/half/include/half/include/half.hpp
  runtime/3rdparty/jsoncpp/CMakeLists.txt
  runtime/3rdparty/jsoncpp/README.md
  runtime/3rdparty/jsoncpp/json/json-forwards.h
  runtime/3rdparty/jsoncpp/json/json.h
  runtime/3rdparty/jsoncpp/jsoncpp.cpp
  runtime/3rdparty/lcov-to-cobertura-xml/README.md
  runtime/3rdparty/lcov-to-cobertura-xml/lcov_cobertura.py
  runtime/libs/half/include/half/.FORMATDENY
Labels: PR/ready for review

#1853 [luci-interpreter] Add Unpack kernel
  compiler/luci-interpreter/src/Interpreter.cpp
  compiler/luci-interpreter/src/KernelBuilder.cpp
  compiler/luci-interpreter/src/KernelBuilder.h
  compiler/luci-interpreter/src/core/KernelParams.h
  compiler/luci-interpreter/src/kernels/CMakeLists.txt
  compiler/luci-interpreter/src/kernels/TestUtils.h
  compiler/luci-interpreter/src/kernels/Unpack.cpp
  compiler/luci-interpreter/src/kernels/Unpack.h
  compiler/luci-interpreter/src/kernels/Unpack.test.cpp
Labels: PR/ready for review

#1805 [luci] Support custom op multiple outputs
  compiler/luci/export/src/CircleOperationExporter.cpp
  compiler/luci/import/src/Nodes/CircleCustom.cpp
  compiler/luci/service/src/CircleShapeInferenceRule.cpp
  compiler/luci/service/src/CircleTypeInferenceRule.cpp
Labels: PR/ready for review

#1861 [onert/nnpkg] Set backend after model load
  tests/tools/nnpackage_run/src/nnpackage_run.cc
Labels: PR/ready for review

#1862 [exo] Resolve static analysis warning
  compiler/exo/src/Conversion/TensorBroadcastConverter.cpp
  compiler/exo/src/Dialect/IR/CircleNodeImpl.h
  compiler/exo/src/Dialect/IR/CircleNodeVisitor.h
  compiler/exo/src/Dialect/IR/TFLNodeImpl.h
  compiler/exo/src/Dialect/IR/TFLNodeVisitor.h
  compiler/exo/src/Dialect/IR/TFLNodes.h
  compiler/exo/src/Pass/FuseBiasAddPass.cpp
  compiler/exo/src/Pass/FuseReluPass.cpp
  compiler/exo/src/TFLite/TFLTypeInference.test.cpp
Labels: PR/ready for review

#1836 [luci] Add Floor Mod test
  compiler/luci/tests/test.lst
Labels: PR/ready for review

#1871 [circledump] Support BatchMatMul
  compiler/circledump/src/OpPrinter.cpp
Labels: PR/ready for review

#1872 [luci] Import BatchMatMul
  compiler/luci/import/include/luci/Import/Nodes.h
  compiler/luci/import/include/luci/Import/Nodes/CircleBatchMatMul.h
  compiler/luci/import/src/GraphBuilderRegistry.cpp
  compiler/luci/import/src/Nodes/CircleBatchMatMul.cpp
Labels: PR/ready for review

#1868 [onert] Unify "cpu_common" of cpu and controlflow in "core"
  runtime/onert/backend/CMakeLists.txt
  runtime/onert/backend/cpu/CMakeLists.txt
  runtime/onert/backend/cpu/DynamicTensorManager.h
  runtime/onert/backend/cpu/StaticTensorManager.h
  runtime/onert/backend/cpu/Tensor.h
  runtime/onert/backend/cpu_common/CMakeLists.txt
  runtime/onert/backend/cpu_common/MemoryPlanner.h
  runtime/onert/core/CMakeLists.txt
  runtime/onert/core/include/backend/cpu_common/Allocator.h
  runtime/onert/core/include/backend/cpu_common/IMemoryPlanner.h
  runtime/onert/core/include/backend/cpu_common/MemoryManager.h
  runtime/onert/core/src/backend/controlflow/DynamicTensorManager.cc
  runtime/onert/core/src/backend/controlflow/DynamicTensorManager.h
  runtime/onert/core/src/backend/controlflow/MemoryManager.cc
  runtime/onert/core/src/backend/controlflow/StaticTensorManager.cc
  runtime/onert/core/src/backend/controlflow/StaticTensorManager.h
  runtime/onert/core/src/backend/controlflow/operand/Allocator.cc
  runtime/onert/core/src/backend/controlflow/operand/Allocator.h
  runtime/onert/core/src/backend/controlflow/operand/Tensor.h
  runtime/onert/core/src/backend/cpu_common/Allocator.cc
  runtime/onert/core/src/backend/cpu_common/MemoryManager.cc
  runtime/onert/core/src/backend/cpu_common/MemoryManager.h
  runtime/onert/core/src/backend/cpu_common/MemoryPlanner.cc
  runtime/onert/core/src/backend/cpu_common/MemoryPlanner.h
  runtime/onert/core/src/backend/cpu_common/MemoryPlanner.test.cc
  runtime/onert/core/src/backend/cpu_common/MemoryPlannerFactory.cc
  runtime/onert/core/src/backend/cpu_common/MemoryPlannerFactory.h
Labels: PR/ready for review, area/onert

#1870 [CircleRecipes] Fix BatchMatMul_000 recipe
  res/CircleRecipes/BatchMatMul_000/test.recipe
Labels: PR/ready for review

#1890 [onert] Fix format error by permission
  tests/nnapi/specs/Ex/shape_ex_dynamic_nnfw.mod.py
Labels: PR/ready for review, trivial

#1863 [nnc] Remove abandoned utility
  compiler/nnc/utils/caffe_model_maker/AllFill.sh
  compiler/nnc/utils/caffe_model_maker/Filler.sh
  compiler/nnc/utils/caffe_model_maker/GenerateCaffeModels.py
  compiler/nnc/utils/caffe_model_maker/Pyloss.py
  compiler/nnc/utils/caffe_model_maker/README.md
Labels: PR/ready for review

#1893 [onert] Add shape inference for Rsqrt operation
  runtime/onert/core/include/util/ShapeInference.h
  runtime/onert/core/src/util/shapeinf/Rsqrt.cc
  tests/nnapi/nnapi_gtest.skip.aarch64-linux.acl_cl
  tests/nnapi/nnapi_gtest.skip.aarch64-linux.acl_neon
  tests/nnapi/nnapi_gtest.skip.armv7l-linux.acl_cl
  tests/nnapi/nnapi_gtest.skip.armv7l-linux.acl_neon
  tests/nnapi/nnapi_gtest.skip.noarch.interp
  tests/nnapi/specs/V1_2/rsqrt_dynamic_nnfw.mod.py
Labels: PR/ready for review

#1903 [CI/script] Compiler build configure for coverage
  infra/scripts/configure_compiler_coverage.sh
Labels: PR/ready for review

#1908 [onert] Move managing cpu tensor into core
  runtime/onert/backend/cpu/Tensor.h
  runtime/onert/backend/cpu/TensorBuilder.cc
  runtime/onert/backend/cpu/TensorBuilder.h
  runtime/onert/core/include/backend/cpu_common/DynamicTensorManager.h
  runtime/onert/core/include/backend/cpu_common/StaticTensorManager.h
  runtime/onert/core/include/backend/cpu_common/Tensor.h
  runtime/onert/core/include/backend/cpu_common/TensorRegistry.h
  runtime/onert/core/src/backend/cpu_common/DynamicTensorManager.cc
  runtime/onert/core/src/backend/cpu_common/StaticTensorManager.cc
  runtime/onert/core/src/backend/cpu_common/Tensor.cc
Labels: PR/ready for review, area/onert

#1883 [luci] Enable BatchMatMul test
  compiler/luci/tests/test.lst
Labels: PR/ready for review

#1809 [cmake] Move external library packages for runtime
  compute/ARMComputeEx/CMakeLists.txt
  infra/cmake/packages/NoniusSourceConfig.cmake
  infra/nnfw/CMakeLists.txt
  infra/nnfw/cmake/packages/ARMComputeConfig.cmake
  infra/nnfw/cmake/packages/BoostConfig.cmake
  infra/nnfw/cmake/packages/NoniusConfig.cmake
  runtime/contrib/android_benchmark_app/CMakeLists.txt
  runtime/contrib/benchmark_acl/CMakeLists.txt
  runtime/contrib/labs/jniacl/CMakeLists.txt
  runtime/contrib/labs/opencl_test/CMakeLists.txt
  runtime/contrib/logging/CMakeLists.txt
  runtime/contrib/style_transfer_app/CMakeLists.txt
  runtime/contrib/uben/CMakeLists.txt
  runtime/onert/backend/acl_cl/CMakeLists.txt
  runtime/onert/backend/acl_common/CMakeLists.txt
  runtime/onert/backend/acl_neon/CMakeLists.txt
  tests/tools/nnpackage_run/CMakeLists.txt
  tests/tools/tflite_loader/CMakeLists.txt
  tests/tools/tflite_run/CMakeLists.txt
  tools/kbenchmark/CMakeLists.txt
  tools/kbenchmark/kernels/acl_cl/CMakeLists.txt
  tools/kbenchmark/kernels/acl_neon/CMakeLists.txt
  tools/opencl_tool/CMakeLists.txt
Labels: PR/ready for review

#1923 Update version information for readthedocs.
  docs/conf.py
Labels: PR/ready for review

#1916 [onert] Remove debug flag on android release build
  infra/nnfw/cmake/buildtool/cross/toolchain_aarch64-android.cmake
Labels: PR/ready for review

#1873 [onert] TC for apply_tensorinfo
  tests/nnfw_api/src/ModelTestDynamicTensor.cc
  tests/nnfw_api/src/NNPackages.cc
  tests/nnfw_api/src/NNPackages.h
  tests/scripts/oneapi_test/models/add_unspecified_rank_inputs/config.sh
  tests/scripts/oneapi_test/models/neg/config.sh
Labels: PR/ready for review

#1614 [onert] Add Shape inference for Pow and its test case
  runtime/onert/core/include/util/ShapeInference.h
  runtime/onert/core/src/util/shapeinf/Pow.cc
  tests/nnapi/nnapi_gtest.skip.aarch64-linux.acl_cl
  tests/nnapi/nnapi_gtest.skip.aarch64-linux.acl_neon
  tests/nnapi/nnapi_gtest.skip.armv7l-linux.acl_cl
  tests/nnapi/nnapi_gtest.skip.armv7l-linux.acl_neon
  tests/nnapi/nnapi_gtest.skip.noarch.interp
  tests/nnapi/specs/V1_2/pow_dynamic_nnfw.mod.py
Labels: PR/ready for review

#1882 [Onert] Add Shape inference for Comparison OP its test case
  runtime/onert/core/include/util/ShapeInference.h
  runtime/onert/core/src/util/shapeinf/Comparison.cc
  tests/nnapi/nnapi_gtest.skip.aarch64-linux.acl_cl
  tests/nnapi/nnapi_gtest.skip.aarch64-linux.acl_neon
  tests/nnapi/nnapi_gtest.skip.armv7l-linux.acl_cl
  tests/nnapi/nnapi_gtest.skip.armv7l-linux.acl_neon
  tests/nnapi/nnapi_gtest.skip.noarch.interp
  tests/nnapi/specs/V1_2/equal_dynamic_float_nnfw.mod.py
  tests/nnapi/specs/V1_2/greater_dynamic_float_nnfw.mod.py
  tests/nnapi/specs/V1_2/greater_equal_dynamic_float_nnfw.mod.py
  tests/nnapi/specs/V1_2/less_dynamic_float_nnfw.mod.py
  tests/nnapi/specs/V1_2/less_equal_dynamic_float_nnfw.mod.py
  tests/nnapi/specs/V1_2/not_equal_dynamic_float_nnfw.mod.py
Labels: PR/ready for review, area/onert

#1826 [onert] Apply dynamic tensor for PermuteLayer of controlflow
  runtime/onert/core/include/exec/IExecutor.h
  runtime/onert/core/src/backend/controlflow/KernelGenerator.cc
  runtime/onert/core/src/backend/controlflow/KernelGenerator.h
  runtime/onert/core/src/backend/controlflow/kernel/IfLayer.cc
  runtime/onert/core/src/backend/controlflow/kernel/IfLayer.h
  runtime/onert/core/src/backend/controlflow/kernel/PermuteLayer.cc
  runtime/onert/core/src/backend/controlflow/kernel/PermuteLayer.h
  runtime/onert/core/src/backend/controlflow/kernel/WhileLayer.cc
  runtime/onert/core/src/backend/controlflow/kernel/WhileLayer.h
  runtime/onert/core/src/exec/ExecutorBase.cc
  runtime/onert/core/src/exec/ExecutorBase.h
Labels: PR/ready for review, area/onert

#1960 [onert] Unify Managing tensors of controlflow and cpu
  runtime/onert/backend/cpu/TensorBuilder.cc
  runtime/onert/core/include/backend/cpu_common/DynamicTensorManager.h
  runtime/onert/core/include/backend/cpu_common/StaticTensorManager.h
  runtime/onert/core/include/backend/cpu_common/Tensor.h
  runtime/onert/core/src/backend/controlflow/DynamicTensorManager.cc
  runtime/onert/core/src/backend/controlflow/DynamicTensorManager.h
  runtime/onert/core/src/backend/controlflow/StaticTensorManager.cc
  runtime/onert/core/src/backend/controlflow/StaticTensorManager.h
  runtime/onert/core/src/backend/controlflow/TensorBuilder.cc
  runtime/onert/core/src/backend/controlflow/TensorBuilder.h
  runtime/onert/core/src/backend/controlflow/TensorRegistry.h
  runtime/onert/core/src/backend/controlflow/operand/Tensor.cc
  runtime/onert/core/src/backend/controlflow/operand/Tensor.h
  runtime/onert/core/src/backend/cpu_common/DynamicTensorManager.cc
  runtime/onert/core/src/backend/cpu_common/StaticTensorManager.cc
Labels: PR/ready for review, area/onert

#1971 [onert] Remove deprecated methods
  runtime/onert/core/include/backend/IDynamicTensorManager.h
  runtime/onert/core/include/backend/cpu_common/DynamicTensorManager.h
  runtime/onert/core/include/exec/IExecutor.h
  runtime/onert/core/src/backend/cpu_common/DynamicTensorManager.cc
  runtime/onert/core/src/exec/ExecutorBase.cc
  runtime/onert/core/src/exec/ExecutorBase.h
Labels: PR/ready for review

#1943 [onert] Fix build error for ruy_profiler
  runtime/onert/core/src/exec/LinearExecutor.cc
Labels: PR/ready for review, area/onert

#1824 [onert] Add shape inference for strided_slice operation
  runtime/onert/backend/cpu/ops/StridedSliceLayer.cc
  runtime/onert/core/include/util/ShapeInference.h
  runtime/onert/core/src/util/shapeinf/StridedSlice.cc
  tests/nnapi/nnapi_gtest.skip.aarch64-linux.acl_cl
  tests/nnapi/nnapi_gtest.skip.aarch64-linux.acl_neon
  tests/nnapi/nnapi_gtest.skip.armv7l-linux.acl_cl
  tests/nnapi/nnapi_gtest.skip.armv7l-linux.acl_neon
  tests/nnapi/nnapi_gtest.skip.noarch.interp
  tests/nnapi/specs/V1_1/strided_slice_dynamic_nnfw.mod.py
Labels: PR/ready for review

#1946 [infra/CI] Merge interpreter test script
  infra/scripts/docker_build_test_x64.sh
  infra/scripts/test_coverage.sh
  infra/scripts/test_ubuntu_runtime.sh
  infra/scripts/test_ubuntu_runtime_interp.sh
  infra/scripts/tizen_xu4_test.sh
Labels: PR/ready for review

#1974 [onert] Adds shape inference for Tile op and its test case.
  runtime/onert/core/include/util/ShapeInference.h
  runtime/onert/core/src/util/shapeinf/Tile.cc
  tests/nnapi/nnapi_gtest.skip.aarch64-linux.acl_cl
  tests/nnapi/nnapi_gtest.skip.aarch64-linux.acl_neon
  tests/nnapi/nnapi_gtest.skip.armv7l-linux.acl_cl
  tests/nnapi/nnapi_gtest.skip.armv7l-linux.acl_neon
  tests/nnapi/nnapi_gtest.skip.noarch.interp
  tests/nnapi/specs/V1_2/tile_1_dynamic_float32_nnfw.mod.py
  tests/nnapi/specs/V1_2/tile_2_dynamic_float32_nnfw.mod.py
  tests/nnapi/specs/V1_2/tile_3_dynamic_float32_nnfw.mod.py
Labels: PR/ready for review

#1961 [onert] Add iterateOpSeqs into PostDfsIterator
  runtime/onert/core/src/ir/GraphIterator.cc
  runtime/onert/core/src/ir/GraphIterator.h
Labels: PR/ready for review, area/onert

#1839 [onert/lib] Move RandomTestRunner class
  runtime/libs/tflite/include/tflite/Diff.h
  runtime/libs/tflite/include/tflite/RandomTestRunner.h
  runtime/libs/tflite/src/Diff.cpp
  runtime/libs/tflite/src/RandomTestRunner.cpp
  tests/tools/nnapi_test/src/nnapi_test.cc
Labels: PR/ready for review, trivial

#1983 [onert] Unify duplicated code in IfLayer
  runtime/onert/core/src/backend/controlflow/kernel/IfLayer.cc
Labels: PR/ready for review, area/onert

#1985 [onert] Add topological sorted iterating method into LoweredGraph
  runtime/onert/core/include/ir/LoweredGraph.h
  runtime/onert/core/src/compiler/ExecutorFactory.cc
  runtime/onert/core/src/compiler/Linear.cc
  runtime/onert/core/src/ir/LoweredGraph.cc
Labels: PR/ready for review, area/onert

#1922 Add hall-of-fame section to README.md
  README.md
Labels: PR/ready for review, trivial

#2016 [onert] Fix wrong reference in PostDfsIterator::OpSeqIterFn
  runtime/onert/core/src/ir/GraphIterator.h
Labels: PR/ready for review, area/onert

#1982 [TensorFlowPythonExamples] rename reshape python file
  res/TensorFlowPythonExamples/examples/reshape/__init__.py
Labels: PR/ready for review

#1987 [CircleRecipes] Add BatchMatMul_000 rule
  res/CircleRecipes/BatchMatMul_000/test.rule
Labels: PR/ready for review

#1992 [tf2tfliteV2] Add shebang
  compiler/tf2tfliteV2/tf2tfliteV2.py
Labels: PR/ready for review

#1996 [tfkit] fix indentation in UnpackCommand
  compiler/tfkit/src/UnpackCommand.cpp
Labels: PR/ready for review

#2000 [tfkit] fix indentation in PackCommand
  compiler/tfkit/src/PackCommand.cpp
Labels: PR/ready for review

#1991 [TensorFlowPythonExamples] Add matrix_band_part
  res/TensorFlowPythonExamples/examples/matrix_band_part/__init__.py
Labels: PR/ready for review

#1993 [TensorFlowPythonExamples] Add shebang
  res/TensorFlowPythonExamples/tfpem.py
Labels: PR/ready for review

#1998 [tfkit] Support bool dtype in unpack
  compiler/tfkit/src/UnpackCommand.cpp
Labels: PR/ready for review

#1995 [packaging] Update default preset version
  infra/packaging/build
Labels: PR/ready for review

#1994 [tf2tfliteV2] change short option
  compiler/tf2tfliteV2/README.md
  compiler/tf2tfliteV2/tf2tfliteV2.py
Labels: PR/ready for review

#2037 [circle2circle-dredd-recipe-test] Add CircleRecipes
  compiler/circle2circle-dredd-recipe-test/CMakeLists.txt
  compiler/circle2circle-dredd-recipe-test/requires.cmake
  compiler/circle2circle-dredd-recipe-test/test.lst
Labels: PR/ready for review

#2050 [onert] Apply adding default lower_info for unused non-constant output of Graph
  runtime/onert/core/src/ir/LoweredGraph.cc
Labels: PR/ready for review, area/onert

#2057 [luci] Supports when input of CircleGather has a dynamic shape
  compiler/luci/service/src/CircleShapeInferenceRule.cpp
Labels: PR/ready for review

#2071 [packaging] Update 20200508 preset
  infra/packaging/preset/20200508
Labels: PR/ready for review

#2064 [onert] Add shape inference for slice and its testcases
  runtime/onert/core/include/util/ShapeInference.h
  runtime/onert/core/src/util/shapeinf/Slice.cc
  tests/nnapi/nnapi_gtest.skip.aarch64-linux.acl_cl
  tests/nnapi/nnapi_gtest.skip.aarch64-linux.acl_neon
  tests/nnapi/nnapi_gtest.skip.armv7l-linux.acl_cl
  tests/nnapi/nnapi_gtest.skip.armv7l-linux.acl_neon
  tests/nnapi/nnapi_gtest.skip.noarch.interp
  tests/nnapi/specs/V1_2/slice_dynamic_nnfw.mod.py
Labels: PR/ready for review, area/onert

#2084 [onert] throw runtime error for unsupported data type in cpu backcend
  runtime/onert/backend/cpu/ops/AbsLayer.cc
  runtime/onert/backend/cpu/ops/AddLayer.cc
  runtime/onert/backend/cpu/ops/ArgMinMaxLayer.cc
  runtime/onert/backend/cpu/ops/AvgPoolLayer.cc
  runtime/onert/backend/cpu/ops/CastLayer.cc
  runtime/onert/backend/cpu/ops/ConcatLayer.cc
  runtime/onert/backend/cpu/ops/ConvolutionLayer.cc
  runtime/onert/backend/cpu/ops/DepthwiseConvolutionLayer.cc
  runtime/onert/backend/cpu/ops/DivLayer.cc
  runtime/onert/backend/cpu/ops/ExpLayer.cc
  runtime/onert/backend/cpu/ops/FillLayer.cc
  runtime/onert/backend/cpu/ops/FullyConnectedLayer.cc
  runtime/onert/backend/cpu/ops/GatherLayer.cc
  runtime/onert/backend/cpu/ops/LogLayer.cc
  runtime/onert/backend/cpu/ops/LogicalNotLayer.cc
  runtime/onert/backend/cpu/ops/LogicalOrLayer.cc
  runtime/onert/backend/cpu/ops/LogisticLayer.cc
  runtime/onert/backend/cpu/ops/MatrixBandPartLayer.cc
  runtime/onert/backend/cpu/ops/MaxLayer.cc
  runtime/onert/backend/cpu/ops/MaxPoolLayer.cc
  runtime/onert/backend/cpu/ops/MeanLayer.cc
  runtime/onert/backend/cpu/ops/MinLayer.cc
  runtime/onert/backend/cpu/ops/MulLayer.cc
  runtime/onert/backend/cpu/ops/NegLayer.cc
  runtime/onert/backend/cpu/ops/OneHotLayer.cc
  runtime/onert/backend/cpu/ops/PackLayer.cc
  runtime/onert/backend/cpu/ops/PadLayer.cc
  runtime/onert/backend/cpu/ops/PowLayer.cc
  runtime/onert/backend/cpu/ops/ReLULayer.cc
  runtime/onert/backend/cpu/ops/ReduceLayer.cc
  runtime/onert/backend/cpu/ops/SelectLayer.cc
  runtime/onert/backend/cpu/ops/ShapeLayer.cc
  runtime/onert/backend/cpu/ops/SliceLayer.cc
  runtime/onert/backend/cpu/ops/SoftMaxLayer.cc
  runtime/onert/backend/cpu/ops/SplitLayer.cc
  runtime/onert/backend/cpu/ops/SquaredDiffLayer.cc
  runtime/onert/backend/cpu/ops/StridedSliceLayer.cc
  runtime/onert/backend/cpu/ops/SubLayer.cc
  runtime/onert/backend/cpu/ops/TanhLayer.cc
  runtime/onert/backend/cpu/ops/TileLayer.cc
  runtime/onert/backend/cpu/ops/TransposeLayer.cc
  runtime/onert/backend/cpu/ops/UnpackLayer.cc
Labels: PR/ready for review

#2083 [onert] Move calling StaticInferer after creating LoweredGraphs
  runtime/onert/core/include/util/ShapeInference.h
  runtime/onert/core/src/compiler/Compiler.cc
  runtime/onert/core/src/ir/LoweredGraph.cc
  runtime/onert/core/src/util/shapeinf/ShapeInference.cc
Labels: PR/ready for review, area/onert

#2098 [packaging] Add luci-interpreter to preset
  infra/packaging/preset/20200508
Labels: PR/ready for review

#2067 [onert] Support INT8 type in base_loader
  runtime/onert/frontend/base_loader/include/base_loader.h
Labels: PR/ready for review, area/onert

#2008 [onert] Support custom BatchMatMul on cpu backend
  compute/cker/include/cker/Shape.h
  compute/cker/include/cker/operation/BatchMatMul.h
  compute/cker/include/cker/operation/reference/BatchMatMul.h
  runtime/nnapi-header/include/NeuralNetworksEx.h
  runtime/onert/backend/cpu/KernelGenerator.cc
  runtime/onert/backend/cpu/KernelGenerator.h
  runtime/onert/backend/cpu/ops/BatchMatMulLayer.cc
  runtime/onert/backend/cpu/ops/BatchMatMulLayer.h
  runtime/onert/core/include/ir/Operations.Include.h
  runtime/onert/core/include/ir/Operations.lst
  runtime/onert/core/include/ir/operation/BatchMatMul.h
  runtime/onert/core/src/compiler/OperationValidator.cc
  runtime/onert/core/src/compiler/OperationValidator.h
  runtime/onert/core/src/ir/operation/BatchMatMul.cc
  runtime/onert/frontend/base_loader/include/base_loader.h
  runtime/onert/frontend/nnapi/wrapper/OperationFactory.cc
  tests/nnapi/nnapi_gtest.skip.aarch64-linux.acl_cl
  tests/nnapi/nnapi_gtest.skip.aarch64-linux.acl_neon
  tests/nnapi/nnapi_gtest.skip.armv7l-linux.acl_cl
  tests/nnapi/nnapi_gtest.skip.armv7l-linux.acl_neon
  tests/nnapi/nnapi_gtest.skip.noarch.interp
  tests/nnapi/specs/Ex/batch_matmul_ex_float.mod.py
Labels: PR/ready for review

#2110 [packaging] add circle-verify to preset
  infra/packaging/preset/20200508
Labels: PR/ready for review

#1842 [onert/interp] NYI operation exception
  runtime/onert/core/src/interp/Interpreter.cc
Labels: PR/ready for review, trivial

#1815 [onert] Shape inference for LOGICAL_NOT
  runtime/onert/core/include/util/ShapeInference.h
  runtime/onert/core/src/util/shapeinf/LogicalNot.cc
  tests/nnapi/nnapi_gtest.skip.aarch64-linux.acl_cl
  tests/nnapi/nnapi_gtest.skip.aarch64-linux.acl_neon
  tests/nnapi/nnapi_gtest.skip.armv7l-linux.acl_cl
  tests/nnapi/nnapi_gtest.skip.armv7l-linux.acl_neon
  tests/nnapi/nnapi_gtest.skip.noarch.interp
  tests/nnapi/specs/V1_2/logical_not_dynamic_nnfw.mod.py
Labels: PR/ready for review

#2100 [onert] support StridedSlice int32 type in cpu backend
  runtime/onert/backend/cpu/ops/StridedSliceLayer.cc
  runtime/onert/backend/cpu/ops/StridedSliceLayer.h
Labels: PR/ready for review

#2093 [onert] support int32 type for pack in cpu backend
  runtime/onert/backend/cpu/ops/PackLayer.cc
  runtime/onert/backend/cpu/ops/PackLayer.h
  tests/nnapi/nnapi_gtest.skip.aarch64-linux.cpu
  tests/nnapi/nnapi_gtest.skip.armv7l-linux.cpu
  tests/nnapi/nnapi_gtest.skip.x86_64-linux.cpu
Labels: PR/ready for review

#2132 [onert] support int32 type for unpack in cpu backend
  runtime/onert/backend/cpu/ops/UnpackLayer.cc
  runtime/onert/backend/cpu/ops/UnpackLayer.h
  tests/nnapi/nnapi_gtest.skip.aarch64-linux.cpu
  tests/nnapi/nnapi_gtest.skip.armv7l-linux.cpu
  tests/nnapi/nnapi_gtest.skip.x86_64-linux.cpu
Labels: PR/ready for review

#2085 [onert] remove unnecessary code in StridedSlice
  runtime/onert/core/src/util/shapeinf/StridedSlice.cc
Labels: PR/ready for review

#2153 [onert] div will check requires_broadcast with haveSameShape
  runtime/onert/backend/cpu/ops/DivLayer.cc
Labels: PR/ready for review

#2101 [onert] Add def_factor to unused inputs in subgraph
  runtime/onert/core/src/ir/LoweredGraph.cc
Labels: PR/ready for review, area/onert

#2118 [onert] Support int32 type in AddLayer of cpu
  runtime/onert/backend/cpu/ops/AddLayer.cc
  runtime/onert/backend/cpu/ops/AddLayer.h
  runtime/onert/backend/cpu/ops/OperationUtils.cc
  runtime/onert/backend/cpu/ops/OperationUtils.h
Labels: PR/ready for review, area/onert

#2055 [onert] Support int32 in ConcatLayer of cpu
  runtime/onert/backend/cpu/ops/ConcatLayer.cc
  runtime/onert/backend/cpu/ops/ConcatLayer.h
Labels: PR/ready for review, area/onert

#2120 [res] TF Depthwise Conv python example
  res/TensorFlowPythonExamples/examples/depthwise_conv2d_1/__init__.py
  res/TensorFlowPythonExamples/examples/depthwise_conv2d_2/__init__.py
Labels: PR/ready for review

#2122 [res] TensorFlow python examples of conv operator
  res/TensorFlowPythonExamples/examples/conv2d_1/__init__.py
  res/TensorFlowPythonExamples/examples/conv2d_2/__init__.py
Labels: PR/ready for review

#2190 [onert] Remove cpu backend dependency on misc
  runtime/onert/backend/cpu/CMakeLists.txt
Labels: trivial

#1944 [onert] Add shape inference for onehot and its testcases.
  compute/cker/include/cker/operation/OneHot.h
  runtime/onert/backend/cpu/ops/OneHotLayer.cc
  runtime/onert/core/include/util/ShapeInference.h
  runtime/onert/core/src/util/shapeinf/Onehot.cc
  tests/nnapi/nnapi_gtest.skip.aarch64-linux.acl_cl
  tests/nnapi/nnapi_gtest.skip.aarch64-linux.acl_neon
  tests/nnapi/nnapi_gtest.skip.armv7l-linux.acl_cl
  tests/nnapi/nnapi_gtest.skip.armv7l-linux.acl_neon
  tests/nnapi/nnapi_gtest.skip.noarch.interp
  tests/nnapi/specs/Ex/one_hot_ex_dynamic_nnfw.mod.py
Labels: PR/ready for review

#2059 [onert] When input shape.dim[k]==1 && signature[k]==-1, run model with input shape.dim[k]==1
  runtime/onert/core/src/compiler/Compiler.cc
  runtime/onert/frontend/base_loader/include/base_loader.h
  tests/nnfw_api/src/ModelTestDynamicTensor.cc
Labels: PR/ready for review

#2202 [onert] use 0 to 99 range when generating random input for int32
  runtime/libs/misc/src/RandomGenerator.cpp
  tools/nnpackage_tool/gen_golden/gen_golden.py
Labels: PR/ready for review

#1945 [onert] Add shape inference for fill and its testcases
  runtime/onert/core/include/util/ShapeInference.h
  runtime/onert/core/src/util/shapeinf/Fill.cc
  tests/nnapi/nnapi_gtest.skip.aarch64-linux.acl_cl
  tests/nnapi/nnapi_gtest.skip.aarch64-linux.acl_neon
  tests/nnapi/nnapi_gtest.skip.armv7l-linux.acl_cl
  tests/nnapi/nnapi_gtest.skip.armv7l-linux.acl_neon
  tests/nnapi/nnapi_gtest.skip.noarch.interp
  tests/nnapi/specs/Ex/fill_ex_dynamic_nnfw.mod.py
Labels: PR/ready for review

#2014 [onert] add shape inference interface and its test case for SQUARED_DIFF op.
  runtime/onert/core/include/util/ShapeInference.h
  runtime/onert/core/src/util/shapeinf/SquaredDifference.cc
  tests/nnapi/nnapi_gtest.skip.aarch64-linux.acl_cl
  tests/nnapi/nnapi_gtest.skip.aarch64-linux.acl_neon
  tests/nnapi/nnapi_gtest.skip.armv7l-linux.acl_cl
  tests/nnapi/nnapi_gtest.skip.armv7l-linux.acl_neon
  tests/nnapi/nnapi_gtest.skip.noarch.interp
  tests/nnapi/specs/Ex/squared_difference_ex_dynamic_nnfw.mod.py
Labels: PR/ready for review

#2040 [onert] Add shape inference for squeeze and its testcases
  runtime/onert/core/include/util/ShapeInference.h
  runtime/onert/core/src/util/shapeinf/Squeeze.cc
  tests/nnapi/nnapi_gtest.skip.aarch64-linux.acl_cl
  tests/nnapi/nnapi_gtest.skip.aarch64-linux.acl_neon
  tests/nnapi/nnapi_gtest.skip.armv7l-linux.acl_cl
  tests/nnapi/nnapi_gtest.skip.armv7l-linux.acl_neon
  tests/nnapi/nnapi_gtest.skip.noarch.interp
  tests/nnapi/specs/V1_1/squeeze_dynamic_float_nnfw.mod.py
Labels: PR/ready for review, area/onert

#2082 [onert] add shape inference for (reduce_)mean.
  runtime/onert/core/include/util/ShapeInference.h
  runtime/onert/core/src/util/shapeinf/Mean.cc
  tests/nnapi/nnapi_gtest.skip.aarch64-linux.acl_cl
  tests/nnapi/nnapi_gtest.skip.aarch64-linux.acl_neon
  tests/nnapi/nnapi_gtest.skip.armv7l-linux.acl_cl
  tests/nnapi/nnapi_gtest.skip.armv7l-linux.acl_neon
  tests/nnapi/nnapi_gtest.skip.noarch.interp
  tests/nnapi/specs/V1_2/reduce_mean_dynamic_1_nnfw.mod.py
  tests/nnapi/specs/V1_2/reduce_mean_dynamic_2_nnfw.mod.py
Labels: PR/ready for review

#2209 [foder] Introduce file loader module
  compiler/foder/CMakeLists.txt
  compiler/foder/README.md
  compiler/foder/include/foder/FileLoader.h
Labels: PR/ready for review

#2217 [TensorFlowPythonExamples] Add AddV2 op
  res/TensorFlowPythonExamples/examples/AddV2/__init__.py
Labels: PR/ready for review

#2188 [onert] Support multiple subgraph with If op in StaticInferer
  runtime/onert/core/include/util/ShapeInference.h
  runtime/onert/core/src/compiler/Compiler.cc
  runtime/onert/core/src/util/shapeinf/If.cc
Labels: PR/ready for review, area/onert

#2203 [onert] fix wrong inclusion guard in ir/index.h
  runtime/onert/core/include/ir/Index.h
Labels: PR/ready for review

#2170 [onert] Add a condition and converting function in shape inference of reshape
  runtime/onert/core/src/util/shapeinf/Reshape.cc
  tests/nnapi/specs/V1_0/reshape_dynamic_nnfw.mod.py
  tests/nnapi/specs/V1_0/reshape_float_nnfw.mod.py
Labels: PR/ready for review, area/onert

#2207 [onert] Shape inference for ReduceAll
  runtime/onert/core/include/util/ShapeInference.h
  runtime/onert/core/src/util/shapeinf/ReduceAll.cc
  tests/nnapi/nnapi_gtest.skip.aarch64-linux.acl_cl
  tests/nnapi/nnapi_gtest.skip.aarch64-linux.acl_neon
  tests/nnapi/nnapi_gtest.skip.armv7l-linux.acl_cl
  tests/nnapi/nnapi_gtest.skip.armv7l-linux.acl_neon
  tests/nnapi/nnapi_gtest.skip.noarch.interp
  tests/nnapi/specs/V1_2/reduce_all_dynamic_nnfw.mod.py
Labels: PR/ready for review
