Repository Samsung/ONE, pull requests merged in 2020-09, with the labels that each got.

#4035 [onert/cpu] Support erf operation
  compute/cker/include/cker/operation/Erf.h
  runtime/onert/backend/cpu/KernelGenerator.cc
  runtime/onert/backend/cpu/ops/ElementwiseUnaryLayer.cc
  runtime/onert/backend/cpu/ops/ElementwiseUnaryLayer.h
  runtime/onert/core/include/ir/operation/ElementwiseUnary.h
  runtime/onert/core/src/ir/operation/ElementwiseUnary.cc
  runtime/onert/frontend/base_loader/include/base_loader.h
Labels: PR/ready for review

#4032 [docs] Add a section for shape inference into doc
  docs/howto/how-to-introduce-a-new-operation-into-runtime.md
Labels: PR/ready for review

#4050 [onert/cmake] Introduce option build without hdf5
  infra/nnfw/cmake/CfgOptionFlags.cmake
  infra/nnfw/cmake/packages/HDF5Config.cmake
Labels: PR/ready for review

#4060 [infra] temporary fix of nncc docker build script
  infra/scripts/docker_build_nncc.sh
Labels: PR/ready for review

#4054 [tflite2circle] add SparseIndexVector_NONE type
  compiler/tflite2circle/src/DataLookup.cpp
Labels: PR/ready for review

#4057 [luci] fix shape inference that infers CircleSparseToDense node shape
  compiler/luci/service/src/CircleShapeInferenceRule.cpp
Labels: PR/ready for review

#4056 [luci] add condition that builds CircleSparseToDense node
  compiler/luci/import/src/Nodes/CircleSparseToDense.cpp
Labels: PR/ready for review

#4063 [luci] Change default value of CircleSparseToDense's attribute
  compiler/luci/lang/include/luci/IR/Nodes/CircleSparseToDense.h
  compiler/luci/lang/src/Nodes/CircleSparseToDense.test.cpp
Labels: PR/ready for review

#4059 [onert] Reduce memory usage in Conv qasymm uint8 operation
  compute/cker/include/cker/operation/Conv.h
Labels: PR/ready for review

#4038 [onert] Rewrite some dynamic tensor tests with CircleGen
  tests/nnfw_api/src/CircleGen.cc
  tests/nnfw_api/src/CircleGen.h
  tests/nnfw_api/src/ModelTestDynamicTensor.cc
  tests/nnfw_api/src/NNPackages.cc
  tests/nnfw_api/src/NNPackages.h
Labels: PR/ready for review

#4019 [TensorFlowLiteRecipes] fix unique op recipe
  res/TensorFlowLiteRecipes/Unique_000/test.recipe
  res/TensorFlowLiteRecipes/Unique_001/test.recipe
  res/TensorFlowLiteRecipes/Unique_002/test.recipe
  res/TensorFlowLiteRecipes/Unique_003/test.recipe
  res/TensorFlowLiteRecipes/Unique_U8_000/test.recipe
  res/TensorFlowLiteRecipes/Unique_U8_001/test.recipe
Labels: PR/ready for review

#4072 [release_tool] fix bug
  tools/release_tool/git_release.sh
Labels: PR/ready for review

#4016 [onert] Remove duplicated codes in base_loader
  runtime/onert/frontend/base_loader/include/base_loader.h
  runtime/onert/frontend/circle/src/circle_loader.cc
  runtime/onert/frontend/tflite/src/tflite_loader.cc
Labels: PR/ready for review, area/onert

#4073 [onert/test] Add negative tests for GenModelTest
  tests/nnfw_api/src/GenModelTest.h
  tests/nnfw_api/src/RegressionTests.cc
  tests/nnfw_api/src/ValidationTestAddModelLoaded.cc
  tests/nnfw_api/src/ValidationTestFourAddModelsSetInput.cc
  tests/nnfw_api/src/ValidationTestSessionCreated.cc
  tests/nnfw_api/src/ValidationTestSingleSession.cc
  tests/nnfw_api/src/one_op_tests/Add.cc
  tests/nnfw_api/src/one_op_tests/AveragePool2D.cc
  tests/nnfw_api/src/one_op_tests/Cos.cc
  tests/nnfw_api/src/one_op_tests/L2Normalization.cc
  tests/nnfw_api/src/one_op_tests/LeakyRelu.cc
  tests/nnfw_api/src/one_op_tests/Pad.cc
  tests/nnfw_api/src/one_op_tests/PadV2.cc
  tests/nnfw_api/src/one_op_tests/Rank.cc
  tests/nnfw_api/src/one_op_tests/ResizeNearestNeighbor.cc
  tests/nnfw_api/src/one_op_tests/While.cc
Labels: PR/ready for review

#4077 [release/1.9.0] [onert/test] Add negative tests for GenModelTest
  tests/nnfw_api/src/GenModelTest.h
  tests/nnfw_api/src/RegressionTests.cc
  tests/nnfw_api/src/ValidationTestAddModelLoaded.cc
  tests/nnfw_api/src/ValidationTestFourAddModelsSetInput.cc
  tests/nnfw_api/src/ValidationTestSessionCreated.cc
  tests/nnfw_api/src/ValidationTestSingleSession.cc
  tests/nnfw_api/src/one_op_tests/Add.cc
  tests/nnfw_api/src/one_op_tests/AveragePool2D.cc
  tests/nnfw_api/src/one_op_tests/Cos.cc
  tests/nnfw_api/src/one_op_tests/L2Normalization.cc
  tests/nnfw_api/src/one_op_tests/LeakyRelu.cc
  tests/nnfw_api/src/one_op_tests/Pad.cc
  tests/nnfw_api/src/one_op_tests/PadV2.cc
  tests/nnfw_api/src/one_op_tests/Rank.cc
  tests/nnfw_api/src/one_op_tests/ResizeNearestNeighbor.cc
  tests/nnfw_api/src/one_op_tests/While.cc
Labels: PR/ready for review

#4079 Resolve TCM
  tests/nnfw_api/src/one_op_tests/Add.cc
Labels: PR/ready for review

#4082 MIN supports INT32 type
  runtime/onert/backend/cpu/ops/ElementwiseBinaryLayer.cc
Labels: release/1.9.0

#4080 Resolve TCM
  tests/nnfw_api/src/one_op_tests/Add.cc
Labels: PR/ready for review

#4090 [onert] Move wrong param axis of ArgMax to inputs
  runtime/onert/backend/acl_cl/KernelGenerator.cc
  runtime/onert/backend/acl_neon/KernelGenerator.cc
  runtime/onert/backend/cpu/KernelGenerator.cc
  runtime/onert/backend/cpu/ops/ArgMinMaxLayer.cc
  runtime/onert/backend/cpu/ops/ArgMinMaxLayer.h
  runtime/onert/core/include/ir/operation/ArgMax.h
  runtime/onert/core/src/compiler/StaticShapeInference.cc
  runtime/onert/core/src/exec/DynamicShapeInference.cc
  runtime/onert/core/src/ir/OperationDumper.cc
  runtime/onert/core/src/ir/operation/ArgMax.cc
  runtime/onert/frontend/base_loader/include/base_loader.h
  runtime/onert/frontend/nnapi/wrapper/OperationFactory.cc
Labels: PR/ready for review, area/onert

#4075 [onert] Rewrite ModelTestInputReshaping.cc test with CircleGen
  tests/nnfw_api/src/ModelTestInputReshaping.cc
  tests/nnfw_api/src/NNPackages.cc
  tests/nnfw_api/src/NNPackages.h
Labels: PR/ready for review

#4028 [onert] Make `--shape_run h5` as default option of nnpackage_run when '--load' is provided
  runtime/onert/core/src/exec/Execution.cc
  tests/tools/nnpackage_run/src/args.cc
  tests/tools/nnpackage_run/src/args.h
  tests/tools/nnpackage_run/src/nnpackage_run.cc
Labels: PR/ready for review

#4092 [onert] Add an optional input to ir::ResizeBilinear
  runtime/onert/backend/acl_cl/KernelGenerator.cc
  runtime/onert/backend/acl_neon/KernelGenerator.cc
  runtime/onert/backend/cpu/KernelGenerator.cc
  runtime/onert/backend/cpu/ops/ResizeBilinearLayer.cc
  runtime/onert/backend/cpu/ops/ResizeBilinearLayer.h
  runtime/onert/core/include/ir/operation/ResizeBilinear.h
  runtime/onert/core/src/compiler/StaticShapeInference.cc
  runtime/onert/core/src/exec/DynamicShapeInference.cc
  runtime/onert/core/src/ir/OperationDumper.cc
  runtime/onert/core/src/ir/operation/ResizeBilinear.cc
  runtime/onert/frontend/base_loader/include/base_loader.h
Labels: PR/ready for review, area/onert

#4096 [onert] Move wrong param axis of Split to inputs
  runtime/onert/backend/acl_cl/KernelGenerator.cc
  runtime/onert/backend/acl_neon/KernelGenerator.cc
  runtime/onert/backend/cpu/KernelGenerator.cc
  runtime/onert/backend/cpu/ops/SplitLayer.cc
  runtime/onert/backend/cpu/ops/SplitLayer.h
  runtime/onert/core/include/ir/operation/Split.h
  runtime/onert/core/src/compiler/OperationValidator.cc
  runtime/onert/core/src/compiler/StaticShapeInference.cc
  runtime/onert/core/src/exec/DynamicShapeInference.cc
  runtime/onert/core/src/ir/OperationDumper.cc
  runtime/onert/core/src/ir/operation/Split.cc
  runtime/onert/frontend/base_loader/include/base_loader.h
  runtime/onert/frontend/nnapi/wrapper/OperationFactory.cc
  tests/nnapi/nnapi_gtest.skip.aarch64-linux.acl_cl
  tests/nnapi/nnapi_gtest.skip.aarch64-linux.acl_neon
  tests/nnapi/nnapi_gtest.skip.armv7l-linux.acl_cl
  tests/nnapi/nnapi_gtest.skip.armv7l-linux.acl_neon
  tests/nnapi/nnapi_gtest.skip.noarch.interp
  tests/nnapi/specs/V1_2/split_float_5_axis_as_input_nnfw.mod.py
Labels: PR/ready for review, area/onert

#4031 [doc] Update how-to-build-runtime.md
  docs/howto/how-to-build-runtime.md
Labels: PR/ready for review

#4108 [onert] Add a nnapi test for ArgMax
  tests/nnapi/nnapi_gtest.skip.aarch64-linux.acl_cl
  tests/nnapi/nnapi_gtest.skip.aarch64-linux.acl_neon
  tests/nnapi/nnapi_gtest.skip.armv7l-linux.acl_cl
  tests/nnapi/nnapi_gtest.skip.armv7l-linux.acl_neon
  tests/nnapi/nnapi_gtest.skip.noarch.interp
  tests/nnapi/specs/V1_2/argmax_3_axis_as_input_nnfw.mod.py
Labels: PR/ready for review, area/onert

#4127 [onert] Fix Split operation input index
  runtime/onert/core/include/ir/operation/Split.h
  runtime/onert/frontend/nnapi/wrapper/OperationFactory.cc
Labels: PR/ready for review

#4126 [circledump] Revise dump function that dumps flatbuffers vector
  compiler/circledump/src/Dump.cpp
Labels: PR/ready for review

#4132 [tfldump] Revise dump function that dumps flatbuffers vector
  compiler/tfldump/src/Dump.cpp
Labels: PR/ready for review

#4121 [onert/tool] Rootfs generator for ubuntu 20.04
  docs/howto/how-to-cross-build-runtime-for-arm.md
  tools/cross/aarch64/sources.list.focal
  tools/cross/arm/sources.list.focal
  tools/cross/install_rootfs.sh
Labels: PR/ready for review

#4136 [onert] Disable dim_correction of input of acl StridedSlice kernels
  runtime/onert/backend/acl_cl/KernelGenerator.cc
  runtime/onert/backend/acl_neon/KernelGenerator.cc
Labels: PR/ready for review, area/onert

#4113 [onert] Move wrong param perms of Transpose to inputs
  runtime/onert/backend/acl_cl/KernelGenerator.cc
  runtime/onert/backend/acl_neon/KernelGenerator.cc
  runtime/onert/backend/cpu/KernelGenerator.cc
  runtime/onert/backend/cpu/ops/TransposeLayer.cc
  runtime/onert/backend/cpu/ops/TransposeLayer.h
  runtime/onert/core/include/ir/operation/Transpose.h
  runtime/onert/core/include/util/ShapeInference.h
  runtime/onert/core/src/compiler/OperationValidator.cc
  runtime/onert/core/src/compiler/StaticShapeInference.cc
  runtime/onert/core/src/exec/DynamicShapeInference.cc
  runtime/onert/core/src/ir/OperationDumper.cc
  runtime/onert/core/src/ir/operation/Transpose.cc
  runtime/onert/core/src/util/ShapeInference.cc
  runtime/onert/frontend/base_loader/include/base_loader.h
  runtime/onert/frontend/nnapi/wrapper/OperationFactory.cc
  runtime/onert/test/util/ShapeInference.cc
  tests/nnapi/nnapi_gtest.skip.aarch64-linux.acl_cl
  tests/nnapi/nnapi_gtest.skip.aarch64-linux.acl_neon
  tests/nnapi/nnapi_gtest.skip.armv7l-linux.acl_cl
  tests/nnapi/nnapi_gtest.skip.armv7l-linux.acl_neon
  tests/nnapi/nnapi_gtest.skip.noarch.interp
  tests/nnapi/specs/V1_1/transpose_float_1_perms_as_input_nnfw.mod.py
Labels: PR/ready for review, area/onert

#4131 Fix coverity1148326
  compute/ARMComputeEx/src/runtime/CL/functions/CLReduceOperation.cpp
Labels: Urgent, release/1.9.0, target/tizen

#4140 [onert/test] OneOp Split test
  tests/nnfw_api/src/CircleGen.cc
  tests/nnfw_api/src/CircleGen.h
  tests/nnfw_api/src/one_op_tests/Split.cc
Labels: PR/ready for review

#4124 [infra/cmake] Use `EXTERNALS_BUILD_THREADS` to set multi-threading for acl and boost
  Makefile.template
  infra/cmake/packages/BoostConfig.cmake
  infra/nnfw/cmake/packages/ARMComputeConfig.cmake
  infra/nnfw/cmake/packages/BoostConfig.cmake
Labels: PR/ready for review

#4011 [onert] Add SplitV support for acl-cl backend
  compute/ARMComputeEx/arm_compute/runtime/CL/CLFunctionsEx.h
  compute/ARMComputeEx/arm_compute/runtime/CL/functions/CLSplitVEx.h
  compute/ARMComputeEx/src/runtime/CL/functions/CLSplitVEx.cpp
  runtime/onert/backend/acl_cl/KernelGenerator.cc
  runtime/onert/backend/acl_cl/KernelGenerator.h
Labels: PR/ready for review

#4156 [onert] Boost build and install stamp
  infra/nnfw/cmake/packages/BoostConfig.cmake
Labels: PR/ready for review

#4164 [onert] ARMCompute build and install stamp
  Makefile.template
  infra/nnfw/cmake/packages/ARMComputeConfig.cmake
Labels: PR/ready for review

#4168 [luci-interpreter] Add quantized version of makeInputTensor
  compiler/luci-interpreter/src/kernels/Add.test.cpp
  compiler/luci-interpreter/src/kernels/ArgMax.test.cpp
  compiler/luci-interpreter/src/kernels/AveragePool2D.test.cpp
  compiler/luci-interpreter/src/kernels/Conv2D.test.cpp
  compiler/luci-interpreter/src/kernels/DepthwiseConv2D.test.cpp
  compiler/luci-interpreter/src/kernels/Elu.test.cpp
  compiler/luci-interpreter/src/kernels/LeakyRelu.test.cpp
  compiler/luci-interpreter/src/kernels/LogSoftmax.test.cpp
  compiler/luci-interpreter/src/kernels/MaxPool2D.test.cpp
  compiler/luci-interpreter/src/kernels/Mean.test.cpp
  compiler/luci-interpreter/src/kernels/Pad.test.cpp
  compiler/luci-interpreter/src/kernels/Prelu.test.cpp
  compiler/luci-interpreter/src/kernels/Rsqrt.test.cpp
  compiler/luci-interpreter/src/kernels/SpaceToDepth.test.cpp
  compiler/luci-interpreter/src/kernels/Split.test.cpp
  compiler/luci-interpreter/src/kernels/Sqrt.test.cpp
  compiler/luci-interpreter/src/kernels/Squeeze.test.cpp
  compiler/luci-interpreter/src/kernels/StridedSlice.test.cpp
  compiler/luci-interpreter/src/kernels/Tanh.test.cpp
  compiler/luci-interpreter/src/kernels/TestUtils.h
  compiler/luci-interpreter/src/kernels/Transpose.test.cpp
  compiler/luci-interpreter/src/kernels/TransposeConv.test.cpp
Labels: PR/ready for review

#4167 [onert] Rewrite `dynamic reshape` test with CircleGen
  tests/nnfw_api/src/CircleGen.cc
  tests/nnfw_api/src/CircleGen.h
  tests/nnfw_api/src/GenModelTest.h
  tests/nnfw_api/src/ModelTestDynamicTensor.cc
Labels: PR/ready for review

#4174 [release/1.9.0][bcq-tools] Modify unique value generator
  compiler/bcq-tools/preserve_bcq_info
Labels: release/1.9.0

#4177 Compiler FE bump 1.9.1
  compiler/vconone/CMakeLists.txt
Labels: release/1.9.0

#4179 [release/1.9.0][infra] Update tf2nnpkg to apply BCQ automatically
  infra/packaging/res/tf2nnpkg.20200630
Labels: release/1.9.0

#4170 [onert] Introduce USE_MMAPED_DATA option
  runtime/onert/core/include/util/Config.lst
  runtime/onert/frontend/base_loader/include/base_loader.h
Labels: PR/ready for review, area/onert

#4184 [release] 1.9.1 compiler release note
  docs/release/1.9/release-note-1.9.1.md
Labels: PR/ready for review

#4182 [release] 1.9.1 compiler release note
  docs/release/1.9/release-note-1.9.1.md
Labels: PR/ready for review

#4143 [onert] Add nnfw_api tests for ArgMax
  runtime/onert/core/src/compiler/StaticShapeInference.cc
  runtime/onert/core/src/exec/DynamicShapeInference.cc
  runtime/onert/core/src/util/ShapeInference.cc
  tests/nnfw_api/src/CircleGen.cc
  tests/nnfw_api/src/CircleGen.h
  tests/nnfw_api/src/one_op_tests/ArgMax.cc
Labels: PR/ready for review, area/onert

#4197 [record-minmax] Handling error when data file is not HDF5
  compiler/record-minmax/src/HDF5Importer.h
Labels: Urgent

#4180 [onert/nnpackage_run] Disallow two shape-related options together to be given from cmd
  tests/tools/nnpackage_run/src/args.cc
Labels: PR/ready for review

#4207 [release] Update 1.9 release note
  docs/release/1.9/release-note-1.9.1.md
Labels: PR/ready for review

#4191 [luci-interpreter] Rework Relu tests
  compiler/luci-interpreter/src/kernels/Relu.test.cpp
Labels: PR/ready for review

#4208 [release] Update 1.9 release note
  docs/release/1.9/release-note-1.9.1.md
Labels: PR/ready for review

#4206 [release/1.9.0][one-cmds] Print error msg when error occurs
  compiler/one-cmds/one-import-bcq
Labels: release/1.9.0

#4211 [one-cmds] Fix invalid input arguments
  compiler/one-cmds/one-quantize
Labels: release/1.9.0

#4203 [1.9.1][one-cmds] Fix invalid input arguments
  compiler/one-cmds/one-import-tf
  compiler/one-cmds/one-import-tflite
  compiler/one-cmds/one-pack
Labels: release/1.9.0

#4213 [release/1.9.0][one-cmds] Handling invalid input arguments
  compiler/one-cmds/one-import-bcq
Labels: release/1.9.0

#4204 [release/1.9.0][record-minmax] Handling error when data file is not HDF5
  compiler/record-minmax/src/HDF5Importer.h
Labels: release/1.9.0

#4215 [infra] Move RuySource download cmake
  infra/cmake/packages/RuySourceConfig.cmake
  infra/nnfw/cmake/packages/RuyConfig.cmake
Labels: PR/ready for review

#4216 [infra/cmake] Remove unused setting SOURCE_GET
  infra/cmake/packages/ARMComputeSourceConfig.cmake
  infra/cmake/packages/BoostSourceConfig.cmake
  infra/cmake/packages/NoniusSourceConfig.cmake
  infra/nnfw/cmake/packages/FarmhashSourceConfig.cmake
  infra/nnfw/cmake/packages/GEMMLowpSourceConfig.cmake
  infra/nnfw/cmake/packages/NEON2SSESourceConfig.cmake
Labels: PR/ready for review

#4217 [onert/gbs] Update ruy tar file
  packaging/ruy.tar.gz
Labels: PR/ready for review

#4220 [release_tool] fix minor bug
  tools/release_tool/git_release.sh
Labels: PR/ready for review

#4222 [onert] Support OneHot on acl_cl
  compute/ARMComputeEx/arm_compute/core/CL/kernels/CLOneHotKernel.h
  compute/ARMComputeEx/arm_compute/core/utils/misc/ShapeCalculatorEx.h
  compute/ARMComputeEx/arm_compute/runtime/CL/CLFunctionsEx.h
  compute/ARMComputeEx/arm_compute/runtime/CL/functions/CLOneHot.h
  compute/ARMComputeEx/src/core/CL/CLKernelLibrary.cpp
  compute/ARMComputeEx/src/core/CL/cl_kernels/one_hot.cl
  compute/ARMComputeEx/src/core/CL/kernels/CLOneHotKernel.cpp
  compute/ARMComputeEx/src/runtime/CL/functions/CLOneHot.cpp
  runtime/onert/backend/acl_cl/KernelGenerator.cc
  runtime/onert/backend/acl_cl/KernelGenerator.h
  runtime/onert/core/src/compiler/pass/PermutationOperationPass.cc
  runtime/onert/core/src/compiler/pass/PermutationOperationPass.h
  tests/nnapi/nnapi_gtest.skip.aarch64-linux.acl_neon
  tests/nnapi/nnapi_gtest.skip.armv7l-linux.acl_neon
  tests/nnapi/nnapi_gtest.skip.noarch.interp
  tests/nnapi/specs/Ex/one_hot_ex_float_1_nnfw.mod.py
  tests/nnapi/specs/Ex/one_hot_ex_float_2_nnfw.mod.py
Labels: PR/ready for review, area/onert

#4198 [luci-interpreter] Use makeInputTensor in the remaining tests
  compiler/luci-interpreter/src/kernels/FullyConnected.test.cpp
  compiler/luci-interpreter/src/kernels/ResizeBilinear.test.cpp
  compiler/luci-interpreter/src/kernels/ResizeNearestNeighbor.test.cpp
Labels: PR/ready for review

#4226 [luci] Revise the comments in create_circleconst method
  compiler/luci/import/src/Nodes/CircleConst.cpp
Labels: PR/ready for review

#4233 [luci-interpreter] Restrict quantization helpers to integer types
  compiler/luci-interpreter/src/kernels/TestUtils.h
Labels: PR/ready for review

#4234 [luci-interpreter] Add a helper to dequantize tensor data
  compiler/luci-interpreter/src/kernels/Add.test.cpp
  compiler/luci-interpreter/src/kernels/AveragePool2D.test.cpp
  compiler/luci-interpreter/src/kernels/Conv2D.test.cpp
  compiler/luci-interpreter/src/kernels/DepthwiseConv2D.test.cpp
  compiler/luci-interpreter/src/kernels/FullyConnected.test.cpp
  compiler/luci-interpreter/src/kernels/LogSoftmax.test.cpp
  compiler/luci-interpreter/src/kernels/MaxPool2D.test.cpp
  compiler/luci-interpreter/src/kernels/Mean.test.cpp
  compiler/luci-interpreter/src/kernels/Pad.test.cpp
  compiler/luci-interpreter/src/kernels/Prelu.test.cpp
  compiler/luci-interpreter/src/kernels/Relu.test.cpp
  compiler/luci-interpreter/src/kernels/Relu6.test.cpp
  compiler/luci-interpreter/src/kernels/ResizeBilinear.test.cpp
  compiler/luci-interpreter/src/kernels/ResizeNearestNeighbor.test.cpp
  compiler/luci-interpreter/src/kernels/StridedSlice.test.cpp
  compiler/luci-interpreter/src/kernels/Tanh.test.cpp
  compiler/luci-interpreter/src/kernels/TestUtils.cpp
  compiler/luci-interpreter/src/kernels/TestUtils.h
Labels: PR/ready for review

#4227 [onert] Fixing DynamicShapeInference of ArgMax
  runtime/onert/core/src/exec/DynamicShapeInference.cc
Labels: PR/ready for review

#4236 [tflite2circle] Fix bug that incorrectly convert sparsity info
  compiler/tflite2circle/src/CircleModel.cpp
  compiler/tflite2circle/src/DataLookup.cpp
  compiler/tflite2circle/src/DataLookup.h
Labels: PR/ready for review

#4237 [circledump] Dump sparsity
  compiler/circledump/src/Dump.cpp
Labels: PR/ready for review

#4238 [tfldump] Dump sparsity
  compiler/tfldump/src/Dump.cpp
Labels: PR/ready for review

#4240 [tflchef] Cook sparsity
  compiler/tflchef/proto/tflchef.proto
Labels: PR/ready for review

#4145 [onert] Add nnfw_api tests for ResizeBilinear
  runtime/onert/backend/cpu/ops/ResizeBilinearLayer.cc
  runtime/onert/core/src/util/ShapeInference.cc
  tests/nnfw_api/src/CircleGen.cc
  tests/nnfw_api/src/CircleGen.h
  tests/nnfw_api/src/one_op_tests/ResizeBilinear.cc
Labels: PR/ready for review, area/onert

#4239 [luci] Introduce SparsityParam
  compiler/luci/lang/include/luci/IR/SparsityParam.h
Labels: PR/ready for review

#4230 [onert] Add an optimized cl kernel for OneHot
  compute/ARMComputeEx/arm_compute/core/CL/kernels/CLOneHotKernel.h
  compute/ARMComputeEx/arm_compute/runtime/CL/functions/CLOneHot.h
  compute/ARMComputeEx/src/core/CL/CLKernelLibrary.cpp
  compute/ARMComputeEx/src/core/CL/cl_kernels/one_hot.cl
  compute/ARMComputeEx/src/core/CL/kernels/CLOneHotKernel.cpp
  compute/ARMComputeEx/src/runtime/CL/functions/CLOneHot.cpp
  runtime/onert/backend/acl_cl/KernelGenerator.cc
  runtime/onert/backend/acl_common/Convert.cc
  runtime/onert/backend/acl_common/Convert.h
  tests/nnapi/nnapi_gtest.skip.aarch64-linux.acl_neon
  tests/nnapi/nnapi_gtest.skip.armv7l-linux.acl_neon
  tests/nnapi/nnapi_gtest.skip.noarch.interp
  tests/nnapi/specs/Ex/one_hot_ex_float_off_value_constant_zero_nnfw.mod.py
Labels: PR/ready for review, area/onert

#4250 [tizen] Add cpuinfo tar ball to packaging
  packaging/cpuinfo.tar.gz
Labels: PR/ready for review

#4243 [infra/cmake] Merge neon2sse source download
  infra/cmake/packages/NEON2SSESourceConfig.cmake
  infra/nnfw/cmake/packages/NEON2SSESourceConfig.cmake
  infra/nnfw/cmake/packages/TensorFlowLite-1.13.1/TensorFlowLiteConfig.cmake
Labels: PR/ready for review

#4249 [luci] Add sparsity-related function
  compiler/luci/import/include/luci/Import/CircleReader.h
  compiler/luci/import/src/CircleReader.cpp
  compiler/luci/import/src/Nodes/CircleConst.cpp
  compiler/luci/lang/include/luci/IR/CircleNodeDecl.h
Labels: PR/ready for review

#4251 [tflchef] Support sparsity
  compiler/tflchef/core/src/Convert.cpp
  compiler/tflchef/core/src/Convert.h
  compiler/tflchef/core/src/ModelChef.cpp
Labels: PR/ready for review

#4248 [infra/cmake] Add cpuinfo library to infra
  infra/cmake/packages/CpuInfoSourceConfig.cmake
  infra/nnfw/cmake/CfgOptionFlags.cmake
  infra/nnfw/cmake/packages/CpuInfo/cpuinfo.patch
  infra/nnfw/cmake/packages/CpuInfoConfig.cmake
Labels: PR/ready for review

#4247 [release_tool] Support asset_url option
  tools/release_tool/git_release.sh
Labels: PR/ready for review

#4252 [tflchef] Support sparsity of recipechef
  compiler/tflchef/tflite/src/Convert.cpp
  compiler/tflchef/tflite/src/Convert.h
  compiler/tflchef/tflite/src/RecipeChef.cpp
Labels: PR/ready for review

#4218 [onert] Rewriting all dynamic reshaping tests with GenModelTest
  tests/nnfw_api/src/GenModelTest.h
  tests/nnfw_api/src/ModelTestDynamicTensor.cc
  tests/nnfw_api/src/NNPackages.cc
  tests/nnfw_api/src/NNPackages.h
  tests/scripts/models/nnfw_api_gtest/dynamic_tensor_reshape/config.sh
Labels: PR/ready for review

#4258 [res] Add FullyConnected network that contains sparse tensor
  res/TensorFlowLiteRecipes/FullyConnected_004/test.recipe
  res/TensorFlowLiteRecipes/FullyConnected_004/test.reverse
Labels: PR/ready for review

#4259 [onert] Remove unused method in controlflow::TensorBuilder
  runtime/onert/core/src/backend/controlflow/TensorBuilder.cc
  runtime/onert/core/src/backend/controlflow/TensorBuilder.h
Labels: PR/ready for review

#4263 [infra/cmake] GTest source download
  infra/nnfw/cmake/CfgOptionFlags.cmake
  infra/nnfw/cmake/packages/GTestConfig.cmake
  packaging/gtest.tar.gz
Labels: PR/ready for review

#4276 [souschef] Add missing header
  compiler/souschef/include/souschef/Dims.h
Labels: PR/ready for review

#4275 [preset] Remove deprecated command
  infra/packaging/preset/20200731_windows
Labels: PR/ready for review

#4282 [record-minmax] Add missing header
  compiler/record-minmax/src/HDF5Importer.h
Labels: PR/ready for review

#4280 [infra] Remove Eigen source download cmake for TF2.3-rc0
  infra/cmake/packages/TensorFlowEigenSource-2.3.0-rc0Config.cmake
Labels: PR/ready for review

#4285 [one-cmds] Update how-to-prepare-virtualenv.txt
  compiler/one-cmds/how-to-prepare-virtualenv.txt
Labels: PR/ready for review

#4277 [onert] Change shared_ptr for tensors to unique_ptr
  runtime/onert/backend/acl_cl/KernelGenerator.cc
  runtime/onert/backend/acl_common/AclKernelGen.h
  runtime/onert/backend/acl_common/AclTensorRegistry.h
  runtime/onert/backend/acl_neon/KernelGenerator.cc
  runtime/onert/backend/cpu/KernelGenerator.cc
  runtime/onert/backend/cpu/StaticTensorManager.cc
  runtime/onert/core/include/backend/CustomKernelBuilder.h
  runtime/onert/core/include/backend/ITensorRegistry.h
  runtime/onert/core/src/backend/controlflow/DynamicTensorManager.cc
  runtime/onert/core/src/backend/controlflow/KernelGenerator.cc
  runtime/onert/core/src/backend/controlflow/KernelGenerator.h
  runtime/onert/core/src/backend/controlflow/TensorBuilder.cc
  runtime/onert/core/src/backend/controlflow/TensorBuilder.h
  runtime/onert/core/src/backend/controlflow/TensorRegistry.h
  runtime/onert/core/src/backend/controlflow/kernel/IfLayer.cc
  runtime/onert/core/src/backend/controlflow/kernel/IfLayer.h
  runtime/onert/core/src/backend/controlflow/kernel/PermuteLayer.h
  runtime/onert/core/src/backend/controlflow/kernel/WhileLayer.cc
  runtime/onert/core/src/backend/controlflow/kernel/WhileLayer.h
  runtime/onert/core/src/backend/cpu_common/DynamicTensorManager.cc
  runtime/onert/core/src/backend/cpu_common/StaticTensorManager.cc
  runtime/onert/core/src/compiler/ExecutorFactory.cc
  runtime/onert/core/src/compiler/ExecutorFactory.h
  runtime/onert/core/src/compiler/TensorRegistries.h
  runtime/onert/core/src/exec/DataflowExecutor.cc
  runtime/onert/core/src/exec/DataflowExecutor.h
  runtime/onert/core/src/exec/DynamicShapeInference.cc
  runtime/onert/core/src/exec/ExecutorBase.cc
  runtime/onert/core/src/exec/ExecutorBase.h
  runtime/onert/core/src/exec/IPermuteFunction.h
  runtime/onert/core/src/exec/LinearExecutor.h
  runtime/onert/core/src/exec/ParallelExecutor.cc
  runtime/onert/core/src/exec/ParallelExecutor.h
Labels: PR/ready for review

#4257 [nnfwapi] Remove duplicated license in CircleGen
  tests/nnfw_api/src/CircleGen.cc
Labels: trivial

#4284 [docs] How to build compiler for Windows
  docs/howto/how-to-build-compiler.md
Labels: PR/ready for review

#4271 [onert] Rename "External" to "Migrant"
  runtime/onert/core/include/backend/ITensorRegistry.h
  runtime/onert/core/src/compiler/ExecutorFactory.cc
  runtime/onert/core/src/compiler/ExecutorFactory.h
Labels: PR/ready for review

#4269 [onert] Remove unused type: UserTensorRegistry
  runtime/onert/core/src/backend/controlflow/TensorBuilder.h
  runtime/onert/core/src/backend/controlflow/UserTensorRegistry.h
Labels: PR/ready for review

#4281 [luci-interperter] Add missing header
  compiler/luci-interpreter/src/kernels/Utils.h
Labels: PR/ready for review

#4235 [luci-interpreter] Incorporate ElementsAreArray into ArrayFloatNear
  compiler/luci-interpreter/src/kernels/Add.test.cpp
  compiler/luci-interpreter/src/kernels/AveragePool2D.test.cpp
  compiler/luci-interpreter/src/kernels/Concatenation.test.cpp
  compiler/luci-interpreter/src/kernels/Conv2D.test.cpp
  compiler/luci-interpreter/src/kernels/DepthwiseConv2D.test.cpp
  compiler/luci-interpreter/src/kernels/Elu.test.cpp
  compiler/luci-interpreter/src/kernels/FullyConnected.test.cpp
  compiler/luci-interpreter/src/kernels/If.test.cpp
  compiler/luci-interpreter/src/kernels/L2Normalize.test.cpp
  compiler/luci-interpreter/src/kernels/L2Pool2D.test.cpp
  compiler/luci-interpreter/src/kernels/LocalResponseNormalization.test.cpp
  compiler/luci-interpreter/src/kernels/LogSoftmax.test.cpp
  compiler/luci-interpreter/src/kernels/Logistic.test.cpp
  compiler/luci-interpreter/src/kernels/MaxPool2D.test.cpp
  compiler/luci-interpreter/src/kernels/Mean.test.cpp
  compiler/luci-interpreter/src/kernels/Mul.test.cpp
  compiler/luci-interpreter/src/kernels/Pad.test.cpp
  compiler/luci-interpreter/src/kernels/Prelu.test.cpp
  compiler/luci-interpreter/src/kernels/Relu.test.cpp
  compiler/luci-interpreter/src/kernels/Relu6.test.cpp
  compiler/luci-interpreter/src/kernels/Reshape.test.cpp
  compiler/luci-interpreter/src/kernels/ResizeBilinear.test.cpp
  compiler/luci-interpreter/src/kernels/ResizeNearestNeighbor.test.cpp
  compiler/luci-interpreter/src/kernels/Rsqrt.test.cpp
  compiler/luci-interpreter/src/kernels/Softmax.test.cpp
  compiler/luci-interpreter/src/kernels/Sqrt.test.cpp
  compiler/luci-interpreter/src/kernels/StridedSlice.test.cpp
  compiler/luci-interpreter/src/kernels/Tanh.test.cpp
  compiler/luci-interpreter/src/kernels/TestUtils.cpp
  compiler/luci-interpreter/src/kernels/TestUtils.h
Labels: PR/ready for review

#4298 [infra] Remove creating virtual env on compiler package generation
  infra/scripts/docker_build_nncc.sh
Labels: PR/ready for review

#4109 [onert] Support Tile operation's multiplies as input on loader
  runtime/onert/core/include/util/ShapeInference.h
  runtime/onert/core/src/compiler/StaticShapeInference.cc
  runtime/onert/core/src/exec/DynamicShapeInference.cc
  runtime/onert/core/src/util/ShapeInference.cc
  runtime/onert/frontend/base_loader/include/base_loader.h
  tests/nnfw_api/src/one_op_tests/Tile.cc
Labels: PR/ready for review, area/onert

#4303 [onert/test] Fix build fail by method rename expectFailCompile
  tests/nnfw_api/src/one_op_tests/Tile.cc
Labels: PR/ready for review

#4297 [onert/test] Fix modelfile download URL setting bug
  tests/scripts/models/run_test.sh
  tests/scripts/models/tflite/MODELS/inception_nonslim/config.sh
  tests/scripts/models/tflite/MODELS/inception_slim/config.sh
  tests/scripts/models/tflite/MODELS/mobilenet/config.sh
  tests/scripts/models/tflite/MODELS/mobilenet_quant8/config.sh
Labels: PR/ready for review

#4311 [tflchef] Implement FullyConnected filler
  compiler/tflchef/tflite/src/Op/FullyConnected.cpp
Labels: PR/ready for review

#4273 [cker/ruy] Update ruy library version
  compute/cker/include/cker/NeonTensorUtils.h
  compute/cker/include/cker/Types.h
  compute/cker/include/cker/ruy/RuySupport.h
  infra/cmake/packages/RuySourceConfig.cmake
  infra/nnfw/cmake/packages/Ruy/CMakeLists.txt
  infra/nnfw/cmake/packages/RuyConfig.cmake
  packaging/nnfw.spec
  packaging/ruy.tar.gz
  runtime/onert/backend/cpu/ExternalContext.h
  runtime/onert/backend/cpu/ops/FullyConnectedLayer.cc
  runtime/onert/core/CMakeLists.txt
Labels: PR/ready for review

#4295 [onert/test] Download server setting and help message
  tests/nnfw_api/src/NNPackages.cc
  tests/scripts/command/prepare-model
Labels: PR/ready for review

#4312 [onert] Optimize DynamicTensorManager::deallocInput()
  runtime/onert/core/include/backend/IDynamicTensorManager.h
  runtime/onert/core/include/backend/cpu_common/DynamicTensorManager.h
  runtime/onert/core/src/backend/controlflow/DynamicTensorManager.cc
  runtime/onert/core/src/backend/controlflow/DynamicTensorManager.h
  runtime/onert/core/src/backend/cpu_common/DynamicTensorManager.cc
  runtime/onert/core/src/compiler/Linear.cc
Labels: PR/ready for review

#4307 [onert] Fix incorrect result of Cast op with bool type input in acl_cl backend
  compute/ARMComputeEx/arm_compute/core/CL/kernels/CLCastBoolKernel.h
  compute/ARMComputeEx/arm_compute/runtime/CL/CLFunctionsEx.h
  compute/ARMComputeEx/arm_compute/runtime/CL/functions/CLCastBool.h
  compute/ARMComputeEx/src/core/CL/CLKernelLibrary.cpp
  compute/ARMComputeEx/src/core/CL/cl_kernels/cast.cl
  compute/ARMComputeEx/src/core/CL/kernels/CLCastBoolKernel.cpp
  compute/ARMComputeEx/src/runtime/CL/functions/CLCastBool.cpp
  runtime/onert/backend/acl_cl/KernelGenerator.cc
  tests/nnfw_api/src/CircleGen.cc
  tests/nnfw_api/src/CircleGen.h
  tests/nnfw_api/src/GenModelTest.h
  tests/nnfw_api/src/one_op_tests/Cast.cc
Labels: PR/ready for review, area/onert

#4321 [qtflchef] Revise FullyConnected filler
  compiler/tflchef/tflite/src/Op/FullyConnected.cpp
Labels: PR/ready for review

#4320 [tools] Version info for nightly
  tools/release_tool/onert_version.sh
Labels: PR/ready for review

#4317 [onert] Adds some nnfw api testcases for Cast operation
  runtime/onert/core/include/ir/Operation.h
  runtime/onert/core/src/ir/Operation.cc
  runtime/onert/core/src/ir/operation/ElementwiseUnary.cc
  tests/nnfw_api/src/one_op_tests/Cast.cc
Labels: PR/ready for review, area/onert

#4266 [onert] Refines disabling applied dimension correction
  compute/ARMComputeEx/arm_compute/core/NEON/kernels/NEGatherKernelEx.h
  compute/ARMComputeEx/src/core/NEON/kernels/NEGatherKernelEx.cpp
  runtime/onert/backend/acl_cl/KernelGenerator.cc
  runtime/onert/backend/acl_common/AclKernelGen.h
  runtime/onert/backend/acl_common/AclTensorBuilder.h
  runtime/onert/backend/acl_neon/KernelGenerator.cc
  tests/nnfw_api/src/one_op_tests/Concat.cc
Labels: PR/ready for review, area/onert

#4318 [onert] Adds an acl_neon kernel for Cast op with bool input
  compute/ARMComputeEx/arm_compute/core/NEON/kernels/NECastBoolKernel.h
  compute/ARMComputeEx/arm_compute/runtime/NEON/NEFunctionsEx.h
  compute/ARMComputeEx/arm_compute/runtime/NEON/functions/NECastBool.h
  compute/ARMComputeEx/src/core/NEON/kernels/NECastBoolKernel.cpp
  compute/ARMComputeEx/src/runtime/NEON/functions/NECastBool.cpp
  runtime/onert/backend/acl_neon/KernelGenerator.cc
  tests/nnfw_api/src/one_op_tests/Cast.cc
Labels: PR/ready for review, area/onert

#4329 [onert] Use explicit copy constructor for Operand
  runtime/onert/backend/acl_cl/KernelGenerator.cc
  runtime/onert/backend/acl_neon/KernelGenerator.cc
  runtime/onert/core/include/ir/Operand.h
  runtime/onert/core/src/compiler/StaticShapeInference.cc
  runtime/onert/core/src/compiler/pass/ConstantInsertionPass.cc
  runtime/onert/frontend/base_loader/include/base_loader.h
Labels: PR/ready for review

#4335 [onert] Fixes dim_correction incorrectly applied to Unpack
  runtime/onert/backend/acl_cl/KernelGenerator.cc
  runtime/onert/backend/acl_neon/KernelGenerator.cc
Labels: PR/ready for review, area/onert

#4349 [onert] Enable dynamic_cast assert for android in polymorphic_downcast
  runtime/libs/misc/include/misc/polymorphic_downcast.h
Labels: PR/ready for review

#4365 [infra] Update FlatBuffers version
  infra/cmake/packages/FlatBuffersSource-1.12/FlatBuffersSourceConfig.cmake
  infra/cmake/packages/FlatBuffersSource-1.12/FlatBuffersSourceConfigVersion.cmake
  infra/nnfw/cmake/packages/FlatBuffersConfig.cmake
  runtime/contrib/android_benchmark_app/CMakeLists.txt
Labels: PR/ready for review

#4362 [onert] Rename OperationValidator to ShapeValidator
  runtime/onert/core/src/compiler/Compiler.cc
  runtime/onert/core/src/compiler/ShapeValidator.cc
  runtime/onert/core/src/compiler/ShapeValidator.h
Labels: PR/ready for review

#4384 [infra] Rename default docker image
  infra/command/build-docker-image
  infra/config/docker.configuration
  infra/nncc/config/docker.configuration
  infra/nnfw/config/docker.configuration
Labels: PR/ready for review

#4376 [onert/test] Flattened cache directory contents
  tests/scripts/models/run_test.sh
Labels: PR/ready for review

#4393 [circle-dredd-test] Add tests for fuse_add_with_tconv
  compiler/circle2circle-dredd-recipe-test/test.lst
Labels: trivial

#4331 [onert] Adds an acl_neon kernel for OneHot operation
  compute/ARMComputeEx/arm_compute/core/CPP/kernels/CPPOneHotKernelEx.h
  compute/ARMComputeEx/arm_compute/core/NEON/kernels/NEOneHotKernel.h
  compute/ARMComputeEx/arm_compute/runtime/CPP/functions/CPPOneHotEx.h
  compute/ARMComputeEx/arm_compute/runtime/NEON/NEFunctionsEx.h
  compute/ARMComputeEx/arm_compute/runtime/NEON/functions/NEOneHot.h
  compute/ARMComputeEx/src/core/CPP/kernels/CPPOneHotKernelEx.cpp
  compute/ARMComputeEx/src/core/NEON/kernels/NEOneHotKernel.cpp
  compute/ARMComputeEx/src/runtime/NEON/functions/NEOneHot.cpp
  runtime/onert/backend/acl_neon/KernelGenerator.cc
  tests/nnapi/nnapi_gtest.skip.aarch64-linux.acl_neon
  tests/nnapi/nnapi_gtest.skip.armv7l-linux.acl_neon
Labels: PR/ready for review, area/onert

#4350 [armcl-ex] Add copyright to arg_min_max_ex.cl
  compute/ARMComputeEx/src/core/CL/cl_kernels/arg_min_max_ex.cl
Labels: PR/ready for review

#4406 [onert] Introduce OperationValidator
  runtime/onert/core/src/compiler/Compiler.cc
  runtime/onert/core/src/compiler/OperationValidator.cc
  runtime/onert/core/src/compiler/OperationValidator.h
  runtime/onert/core/src/compiler/ShapeValidator.cc
  tests/nnfw_api/src/one_op_tests/LeakyRelu.cc
Labels: PR/ready for review

#4390 [onert] Rename package tar
  Makefile.template
Labels: PR/ready for review

#4426 [onert] Fix package name typo
  Makefile.template
Labels: PR/ready for review, trivial

#4246 [onert] Update NNAPI header
  runtime/nnapi-header/include/NeuralNetworks.h
  runtime/nnapi-header/include/NeuralNetworksExtensions.h
Labels: PR/ready for review

#4415 [onert/test] More fail message
  tests/nnfw_api/src/GenModelTest.h
Labels: PR/ready for review

#4432 [onert] Move comparison type validation check
  runtime/onert/core/src/compiler/OperationValidator.cc
  runtime/onert/core/src/compiler/OperationValidator.h
  runtime/onert/core/src/compiler/ShapeValidator.cc
  tests/nnfw_api/src/GenModelTest.h
  tests/nnfw_api/src/one_op_tests/Equal.cc
Labels: PR/ready for review

#4450 [nnfwapi] Fix typo in GenModelTest
  tests/nnfw_api/src/GenModelTest.h
Labels: trivial

#3884 [onert/gbs] Enable x86_64 gbs build
  infra/nnfw/cmake/buildtool/config/config_x86_64-tizen.cmake
  infra/nnfw/cmake/options/options_x86_64-tizen.cmake
  packaging/nnfw.spec
Labels: PR/ready for review
