Repository Samsung/ONE, pull requests merged in 2020-07, with the labels that each got.

#2723 [infra] Update abseil-cpp version
  infra/cmake/packages/AbseilConfig.cmake
  infra/cmake/packages/AbseilSourceConfig.cmake
  infra/nnfw/cmake/CfgOptionFlags.cmake
  infra/nnfw/cmake/packages/AbslSourceConfig.cmake
  infra/nnfw/cmake/packages/TensorFlowLite/CMakeLists.txt
  infra/nnfw/cmake/packages/TensorFlowLiteConfig.cmake
Labels: PR/ready for review

#2627 [onert] Support comparison for quant8 cker
  compute/cker/include/cker/Types.h
  compute/cker/include/cker/operation/Comparison.h
  runtime/onert/backend/cpu/ops/CompareLayer.cc
  runtime/onert/backend/cpu/ops/CompareLayer.h
  tests/nnapi/nnapi_gtest.skip.aarch64-linux.cpu
  tests/nnapi/nnapi_gtest.skip.armv7l-linux.cpu
  tests/nnapi/nnapi_gtest.skip.noarch.interp
  tests/nnapi/nnapi_gtest.skip.x86_64-linux.cpu
  tests/nnapi/specs/V1_2/equal_broadcast_quant8_nnfw.mod.py
  tests/nnapi/specs/V1_2/greater_broadcast_quant8_nnfw.mod.py
  tests/nnapi/specs/V1_2/greater_equal_broadcast_quant8_nnfw.mod.py
  tests/nnapi/specs/V1_2/greater_equal_quant8_nnfw.mod.py
  tests/nnapi/specs/V1_2/greater_quant8_nnfw.mod.py
  tests/nnapi/specs/V1_2/less_broadcast_quant8_nnfw.mod.py
  tests/nnapi/specs/V1_2/less_equal_broadcast_quant8_nnfw.mod.py
  tests/nnapi/specs/V1_2/less_equal_quant8_nnfw.mod.py
  tests/nnapi/specs/V1_2/less_quant8_nnfw.mod.py
  tests/nnapi/specs/V1_2/not_equal_broadcast_quant8_nnfw.mod.py
Labels: PR/ready for review

#2254 [onert] Add Logistic operation for quantization
  runtime/onert/backend/cpu/ops/LogisticLayer.cc
  runtime/onert/backend/cpu/ops/LogisticLayer.h
  tests/nnapi/nnapi_gtest.skip.aarch64-linux.cpu
  tests/nnapi/nnapi_gtest.skip.armv7l-linux.cpu
  tests/nnapi/nnapi_gtest.skip.x86_64-linux.cpu
Labels: PR/ready for review

#2672 [onert] Add some dimension checks for MatrixBandPart
  compute/cker/include/cker/operation/MatrixBandPart.h
  runtime/onert/core/src/compiler/OperationValidator.cc
  runtime/onert/core/src/compiler/OperationValidator.h
  tests/nnapi/specs/Ex/matrix_band_part_ex_4D_float.mod.py
Labels: PR/ready for review

#2760 [infra/cmake] Remove TensorFlowLite-1.7 cmake config
  infra/cmake/packages/TensorFlowLite-1.7/Lite/CMakeLists.txt
  infra/cmake/packages/TensorFlowLite-1.7/TensorFlowLiteConfig.cmake
  infra/cmake/packages/TensorFlowLite-1.7/TensorFlowLiteConfigVersion.cmake
  infra/cmake/packages/TensorFlowSource-1.7/TensorFlowSourceConfig.cmake
  infra/cmake/packages/TensorFlowSource-1.7/TensorFlowSourceConfigVersion.cmake
Labels: PR/ready for review

#2758 [cker] Add an assertion checking accum_depth in BatchMatMul kernel
  compute/cker/include/cker/operation/BatchMatMul.h
Labels: PR/ready for review, area/onert

#2718 [cker] Add scalar case to the function to check matching of shapes
  compute/cker/include/cker/Shape.h
Labels: PR/ready for review

#2759 [onert] OneHot will store depth and on/off value in input tensor
  compute/ARMComputeEx/arm_compute/core/CPP/kernels/CPPOneHotKernelEx.h
  compute/ARMComputeEx/arm_compute/runtime/CPP/functions/CPPOneHotEx.h
  compute/ARMComputeEx/src/core/CPP/kernels/CPPOneHotKernelEx.cpp
  compute/ARMComputeEx/src/runtime/CPP/functions/CPPOneHotEx.cpp
  runtime/libs/tflite/port/1.13.1/src/nnapi_delegate.cpp
  runtime/libs/tflite/port/1.13.1/src/nnapi_delegate_ex_AddOpsAndParams_lambda.inc
  runtime/nnapi-header/include/NeuralNetworksEx.h
  runtime/onert/backend/acl_neon/KernelGenerator.cc
  runtime/onert/backend/cpu/KernelGenerator.cc
  runtime/onert/backend/cpu/ops/OneHotLayer.cc
  runtime/onert/backend/cpu/ops/OneHotLayer.h
  runtime/onert/core/include/ir/operation/OneHot.h
  runtime/onert/core/src/util/shapeinf/Onehot.cc
  runtime/onert/frontend/base_loader/include/base_loader.h
  runtime/onert/frontend/nnapi/wrapper/OperationFactory.cc
  tests/nnapi/specs/Ex/one_hot_ex_dynamic_nnfw.mod.py
Labels: PR/ready for review

#2747 [onert] Change param axes of cpu layers of reducing ops to IPortableTensor
  compute/cker/include/cker/operation/ReduceMean.h
  runtime/onert/backend/cpu/KernelGenerator.cc
  runtime/onert/backend/cpu/ops/MeanLayer.cc
  runtime/onert/backend/cpu/ops/MeanLayer.h
  runtime/onert/backend/cpu/ops/OperationUtils.cc
  runtime/onert/backend/cpu/ops/OperationUtils.h
  runtime/onert/backend/cpu/ops/ReduceLayer.cc
  runtime/onert/backend/cpu/ops/ReduceLayer.h
Labels: PR/ready for review, area/onert

#2786 [luci] Support ReLU6 op in importer
  compiler/luci/import/include/luci/Import/Nodes.h
  compiler/luci/import/include/luci/Import/Nodes/CircleRelu6.h
  compiler/luci/import/src/GraphBuilderRegistry.cpp
  compiler/luci/import/src/Nodes/CircleRelu6.cpp
  compiler/luci/tests/test.lst
Labels: PR/ready for review

#2791 [onert] Add override keyword for FullyConnectedLayer method
  runtime/onert/backend/cpu/ops/FullyConnectedLayer.h
Labels: PR/ready for review

#2798 [onert] Fix getReducerAxes bug
  runtime/onert/backend/cpu/ops/OperationUtils.cc
Labels: PR/ready for review, impact/critical

#2821 [contrib/android] Append content for ndk install to README
  runtime/contrib/android/README.md
Labels: PR/NO MERGE, PR/NO TEST

#2819 [onert] Set OP_SEQ_MAX_NODE to 1 if RUY_PROFILER is enabled
  runtime/onert/core/src/compiler/Compiler.cc
Labels: PR/ready for review, area/onert

#2823 [circle2circle] Change the way models are loaded
  compiler/circle2circle/CMakeLists.txt
  compiler/circle2circle/requires.cmake
  compiler/circle2circle/src/Circle2Circle.cpp
  compiler/circle2circle/src/Model.cpp
Labels: PR/ready for review

#2824 [luci] Change the way models are loaded
  compiler/luci/requires.cmake
  compiler/luci/tester/CMakeLists.txt
  compiler/luci/tester/src/Model.cpp
  compiler/luci/tester/src/Model.h
  compiler/luci/tester/src/ReadTester.cpp
  compiler/luci/tester/src/WriteTester.cpp
Labels: PR/ready for review

#2825 [circle-quantizer] Change the way models are loaded
  compiler/circle-quantizer/CMakeLists.txt
  compiler/circle-quantizer/include/Model.h
  compiler/circle-quantizer/requires.cmake
  compiler/circle-quantizer/src/CircleQuantizer.cpp
  compiler/circle-quantizer/src/Model.cpp
Labels: PR/ready for review

#2837 [onert] Nit: Fix bug in IPermuteFunction
  runtime/onert/core/src/exec/IPermuteFunction.h
Labels: trivial

#2839 [onert] Remove redundant cast in TensorRegistry
  runtime/onert/core/include/backend/ITensorRegistry.h
Labels: trivial

#2728 [luci-interpreter] Test quantized Add kernels for ResNet-v1
  compiler/luci-interpreter/src/kernels/Add.test.cpp
Labels: PR/ready for review

#2840 [luci-interpreter] Skip build if dependencies are missing
  compiler/luci-interpreter/src/CMakeLists.txt
  compiler/luci-interpreter/src/kernels/CMakeLists.txt
Labels: PR/ready for review

#2692 [tools/tflitefile] Support controlflow operators in select_operator.py
  tools/tflitefile_tool/README.md
  tools/tflitefile_tool/select_operator.py
Labels: PR/ready for review

#2861 [onert] Fix set_op_backend bug
  runtime/onert/api/src/nnfw_api_internal.cc
Labels: PR/ready for review

#2862 [onert] Update OpMap.lst
  runtime/onert/api/src/OpMap.lst
Labels: PR/ready for review

#2864 [onert] Move shape calculation code into ShapeInference.cc
  runtime/onert/core/include/util/ShapeInference.h
  runtime/onert/core/src/util/shapeinf/ArgMax.cc
  runtime/onert/core/src/util/shapeinf/BatchMatMul.cc
  runtime/onert/core/src/util/shapeinf/BroadcastTo.cc
  runtime/onert/core/src/util/shapeinf/Concat.cc
  runtime/onert/core/src/util/shapeinf/Conv2D.cc
  runtime/onert/core/src/util/shapeinf/ExpandDims.cc
  runtime/onert/core/src/util/shapeinf/Fill.cc
  runtime/onert/core/src/util/shapeinf/FullyConnected.cc
  runtime/onert/core/src/util/shapeinf/Gather.cc
  runtime/onert/core/src/util/shapeinf/Onehot.cc
  runtime/onert/core/src/util/shapeinf/Pack.cc
  runtime/onert/core/src/util/shapeinf/Pad.cc
  runtime/onert/core/src/util/shapeinf/Range.cc
  runtime/onert/core/src/util/shapeinf/Reshape.cc
  runtime/onert/core/src/util/shapeinf/Select.cc
  runtime/onert/core/src/util/shapeinf/ShapeInference.cc
  runtime/onert/core/src/util/shapeinf/Slice.cc
  runtime/onert/core/src/util/shapeinf/Split.cc
  runtime/onert/core/src/util/shapeinf/Squeeze.cc
  runtime/onert/core/src/util/shapeinf/StridedSlice.cc
  runtime/onert/core/src/util/shapeinf/Tile.cc
  runtime/onert/core/src/util/shapeinf/Transpose.cc
  runtime/onert/core/src/util/shapeinf/Unpack.cc
Labels: PR/ready for review

#2865 [luci-value-test] Rename variable
  compiler/luci-value-test/tester/src/EvalTester.cpp
Labels: type/discussion

#2860 [common-artifacts] Introduce common artifacts
  compiler/common-artifacts/CMakeLists.txt
  compiler/common-artifacts/README.md
  compiler/common-artifacts/exclude.lst
  compiler/common-artifacts/requires.cmake
  compiler/common-artifacts/src/TestDataGenerator.cpp
Labels: PR/ready for review

#2898 [common-artifacts] exclude NYI OP from tc generation
  compiler/common-artifacts/exclude.lst
Labels: PR/ready for review

#2897 [onert] Fix unittest report path
  tests/scripts/unittest.sh
Labels: PR/ready for review

#2886 [onert] Make applying dynamic of controlflow operations only in PermuteLayer
  runtime/onert/core/src/backend/controlflow/kernel/IfLayer.cc
  runtime/onert/core/src/backend/controlflow/kernel/PermuteLayer.cc
  runtime/onert/core/src/backend/controlflow/kernel/WhileLayer.cc
Labels: PR/ready for review, area/onert

#2905 [cmd] Ignore new line check
  infra/command/format
Labels: PR/ready for review

#2894 [onert][cker] Introduce checking constant into OperandInfo
  compute/cker/include/cker/operation/Conv.h
  runtime/onert/backend/cpu/ops/ConvolutionLayer.cc
  runtime/onert/backend/cpu/ops/ConvolutionLayer.h
  runtime/onert/core/include/backend/ITensor.h
  runtime/onert/core/include/backend/cpu_common/Tensor.h
  runtime/onert/core/include/ir/Operand.h
  runtime/onert/core/include/ir/OperandInfo.h
Labels: PR/ready for review, area/onert

#2908 [cmd] Remove debug log in format command
  infra/command/format
Labels: bug, trivial

#2912 [onert] Fix assert condition in isConstant()
  runtime/onert/core/include/ir/OperandInfo.h
Labels: PR/ready for review

#2841 [luci-interpreter] Add preOperatorExecute and postOperatorExecute events
  compiler/luci-interpreter/include/luci_interpreter/Interpreter.h
  compiler/luci-interpreter/src/Interpreter.cpp
  compiler/luci-interpreter/src/core/EventNotifier.h
  compiler/luci-interpreter/src/core/RuntimeGraph.cpp
  compiler/luci-interpreter/src/loader/GraphLoader.cpp
  compiler/luci-interpreter/src/loader/RuntimeToIR.h
Labels: PR/ready for review

#2891 [onert] Move inference code to compier & exec dir
  runtime/onert/backend/cpu/KernelGenerator.cc
  runtime/onert/core/include/compiler/StaticShapeInference.h
  runtime/onert/core/include/exec/DynamicShapeInference.h
  runtime/onert/core/include/exec/FunctionSequence.h
  runtime/onert/core/src/compiler/Compiler.cc
  runtime/onert/core/src/compiler/StaticShapeInference.cc
  runtime/onert/core/src/exec/DynamicShapeInference.cc
  runtime/onert/core/src/exec/FunctionSequence.cc
Labels: PR/ready for review

#2909 [tf2nnpackage-value-remote-test] Introduce e2e test
  compiler/tf2nnpackage-value-remote-test/CMakeLists.txt
  compiler/tf2nnpackage-value-remote-test/README.md
  compiler/tf2nnpackage-value-remote-test/requires.cmake
  compiler/tf2nnpackage-value-remote-test/test.lst
  compiler/tf2nnpackage-value-remote-test/testall.sh
Labels: PR/ready for review

#2816 [onert] Introduce sequence_index cache to optimize findOperation
  runtime/onert/core/include/ir/OpSequence.h
  runtime/onert/core/include/ir/OpSequences.h
  runtime/onert/core/src/ir/OpSequences.cc
Labels: PR/ready for review, area/onert

#2794 Use shared library variant of libc++ for android build
  infra/nnfw/cmake/buildtool/cross/toolchain_aarch64-android.cmake
Labels: PR/ready for review

#2927 [onert] Remove `shapeinf` dir in `util`
  runtime/onert/core/src/util/ShapeInference.cc
  runtime/onert/core/src/util/shapeinf/Abs.cc
  runtime/onert/core/src/util/shapeinf/Add.cc
  runtime/onert/core/src/util/shapeinf/ArgMax.cc
  runtime/onert/core/src/util/shapeinf/BatchMatMul.cc
  runtime/onert/core/src/util/shapeinf/BroadcastTo.cc
  runtime/onert/core/src/util/shapeinf/Cast.cc
  runtime/onert/core/src/util/shapeinf/Comparison.cc
  runtime/onert/core/src/util/shapeinf/Concat.cc
  runtime/onert/core/src/util/shapeinf/Conv2D.cc
  runtime/onert/core/src/util/shapeinf/Cos.cc
  runtime/onert/core/src/util/shapeinf/Div.cc
  runtime/onert/core/src/util/shapeinf/Exp.cc
  runtime/onert/core/src/util/shapeinf/ExpandDims.cc
  runtime/onert/core/src/util/shapeinf/Fill.cc
  runtime/onert/core/src/util/shapeinf/FullyConnected.cc
  runtime/onert/core/src/util/shapeinf/FusedBatchNorm.cc
  runtime/onert/core/src/util/shapeinf/Gather.cc
  runtime/onert/core/src/util/shapeinf/If.cc
  runtime/onert/core/src/util/shapeinf/Log.cc
  runtime/onert/core/src/util/shapeinf/LogicalNot.cc
  runtime/onert/core/src/util/shapeinf/LogicalOr.cc
  runtime/onert/core/src/util/shapeinf/Logistic.cc
  runtime/onert/core/src/util/shapeinf/MatrixBandPart.cc
  runtime/onert/core/src/util/shapeinf/Max.cc
  runtime/onert/core/src/util/shapeinf/Mean.cc
  runtime/onert/core/src/util/shapeinf/Min.cc
  runtime/onert/core/src/util/shapeinf/Mul.cc
  runtime/onert/core/src/util/shapeinf/Neg.cc
  runtime/onert/core/src/util/shapeinf/Onehot.cc
  runtime/onert/core/src/util/shapeinf/Pack.cc
  runtime/onert/core/src/util/shapeinf/Pad.cc
  runtime/onert/core/src/util/shapeinf/Permute.cc
  runtime/onert/core/src/util/shapeinf/Pow.cc
  runtime/onert/core/src/util/shapeinf/Range.cc
  runtime/onert/core/src/util/shapeinf/ReduceAll.cc
  runtime/onert/core/src/util/shapeinf/ReduceMin.cc
  runtime/onert/core/src/util/shapeinf/ReduceProd.cc
  runtime/onert/core/src/util/shapeinf/ReduceSum.cc
  runtime/onert/core/src/util/shapeinf/Reshape.cc
  runtime/onert/core/src/util/shapeinf/Reverse.cc
  runtime/onert/core/src/util/shapeinf/Round.cc
  runtime/onert/core/src/util/shapeinf/Rsqrt.cc
  runtime/onert/core/src/util/shapeinf/Select.cc
  runtime/onert/core/src/util/shapeinf/Shape.cc
  runtime/onert/core/src/util/shapeinf/Sin.cc
  runtime/onert/core/src/util/shapeinf/Slice.cc
  runtime/onert/core/src/util/shapeinf/Softmax.cc
  runtime/onert/core/src/util/shapeinf/Split.cc
  runtime/onert/core/src/util/shapeinf/SquaredDifference.cc
  runtime/onert/core/src/util/shapeinf/Squeeze.cc
  runtime/onert/core/src/util/shapeinf/StridedSlice.cc
  runtime/onert/core/src/util/shapeinf/Sub.cc
  runtime/onert/core/src/util/shapeinf/Tanh.cc
  runtime/onert/core/src/util/shapeinf/Tile.cc
  runtime/onert/core/src/util/shapeinf/Transpose.cc
  runtime/onert/core/src/util/shapeinf/Unpack.cc
  runtime/onert/core/src/util/shapeinf/While.cc
  runtime/onert/core/src/util/shapeinf/ZerosLike.cc
Labels: PR/ready for review

#2869 [onert] Remove applying dim_correction from ShapeFixer to KernelGenerators of acl
  compute/ARMComputeEx/arm_compute/core/CL/kernels/CLSpaceToBatchNDKernel.h
  compute/ARMComputeEx/arm_compute/runtime/CL/CLFunctionsEx.h
  compute/ARMComputeEx/arm_compute/runtime/CL/functions/CLSpaceToBatchND.h
  compute/ARMComputeEx/src/core/CL/CLKernelLibrary.cpp
  compute/ARMComputeEx/src/core/CL/cl_kernels/space_to_batch.cl
  compute/ARMComputeEx/src/core/CL/kernels/CLSpaceToBatchNDKernel.cpp
  compute/ARMComputeEx/src/runtime/CL/functions/CLSpaceToBatchND.cpp
  runtime/onert/backend/acl_cl/KernelGenerator.cc
  runtime/onert/backend/acl_cl/ShapeFixer.cc
  runtime/onert/backend/acl_cl/ShapeFixer.h
  runtime/onert/backend/acl_common/AclTensorBuilder.h
  runtime/onert/backend/acl_neon/KernelGenerator.cc
  runtime/onert/backend/acl_neon/ShapeFixer.cc
  runtime/onert/backend/acl_neon/ShapeFixer.h
Labels: PR/ready for review, area/onert

#2930 [onert] Remove unused variable in acl-cl KernelGenerator.cc
  runtime/onert/backend/acl_cl/KernelGenerator.cc
Labels: PR/ready for review, trivial

#2936 [packaging] revise tf2nnpkg.20200630
  infra/packaging/res/tf2nnpkg.20200630
Labels: PR/ready for review

#2928 [tests/tools] Make nnapi_test runs nnapi_delegate twice
  runtime/libs/tflite/include/tflite/RandomTestRunner.h
  runtime/libs/tflite/src/RandomTestRunner.cpp
  runtime/onert/backend/cpu/ops/FullyConnectedLayer.cc
  tests/scripts/list/frameworktest_list.aarch64.cpu.txt
  tests/tools/nnapi_test/src/nnapi_test.cc
Labels: PR/ready for review

#2945 [onert] Parallel build on tizen build
  packaging/nnfw.spec
Labels: PR/ready for review

#2944 [onert] Remove unused field
  runtime/onert/backend/cpu/ops/FullyConnectedLayer.h
Labels: PR/ready for review, trivial

#2946 [infra/cmake] Revise nnfw TensorFlow 1.13.1 package config
  infra/cmake/packages/TensorFlowSource-1.13.1/TensorFlowSourceConfig.cmake
  infra/nnfw/cmake/packages/TensorFlowLite-1.13.1/TensorFlowLite/CMakeLists.txt
  infra/nnfw/cmake/packages/TensorFlowLite-1.13.1/TensorFlowLiteConfig.cmake
  infra/nnfw/cmake/packages/TensorFlowLite-1.13.1/TensorFlowLiteConfigVersion.cmake
  infra/nnfw/cmake/packages/TensorFlowSourceConfig.cmake
  runtime/contrib/android_tflite/CMakeLists.txt
  runtime/libs/tflite/CMakeLists.txt
  tests/tools/tflite_benchmark_model/CMakeLists.txt
Labels: PR/ready for review

#2917 [circle2circle-dredd-recipe-test] Enable resolve_customop_matmul pass
  compiler/circle2circle-dredd-recipe-test/test.lst
Labels: PR/ready for review

#2953 [onert] Use optimized logistic cpu kernel for aarch64 only
  compute/cker/include/cker/operation/Logistic.h
Labels: PR/ready for review, area/onert

#2975 [onert] Remove flatbuffers source tar
  infra/nnfw/cmake/packages/FlatBuffersConfig.cmake
  packaging/flatbuffers.tar.gz
  packaging/nnfw.spec
  runtime/onert/frontend/base_loader/CMakeLists.txt
  runtime/onert/frontend/circle/CMakeLists.txt
  runtime/onert/frontend/tflite/CMakeLists.txt
  tests/custom_op/CMakeLists.txt
Labels: PR/ready for review

#2465 [onert] Add quant8 support for split cker
  runtime/onert/backend/cpu/ops/SplitLayer.cc
  runtime/onert/backend/cpu/ops/SplitLayer.h
  tests/nnapi/nnapi_gtest.skip.aarch64-linux.cpu
  tests/nnapi/nnapi_gtest.skip.armv7l-linux.cpu
  tests/nnapi/nnapi_gtest.skip.x86_64-linux.cpu
Labels: PR/ready for review

#2940 Apply -O3 for release build
  infra/nnfw/cmake/ApplyCompileFlags.cmake
Labels: PR/ready for review

#2987 [infra/cmake] Update FlatbuffersSource config
  infra/cmake/packages/FlatBuffersSource-1.10/FlatBuffersSourceConfig.cmake
  infra/cmake/packages/FlatBuffersSource-1.11/FlatBuffersSourceConfig.cmake
  infra/cmake/packages/FlatBuffersSource-1.11/FlatBuffersSourceConfigVersion.cmake
  infra/cmake/packages/FlatBuffersSourceConfig.cmake
Labels: PR/ready for review

#2955 [onert] Add expand rank in PermutationOperationPass
  runtime/onert/core/src/ir/pass/PermutationOperationPass.cc
  runtime/onert/core/src/ir/pass/PermutationOperationPass.h
Labels: PR/ready for review, area/onert

#2959 [tests/tools] Introduce args into nnapi_test
  tests/tools/nnapi_test/CMakeLists.txt
  tests/tools/nnapi_test/src/args.cc
  tests/tools/nnapi_test/src/args.h
  tests/tools/nnapi_test/src/nnapi_test.cc
Labels: PR/ready for review

#2998 [common-artifacts] Add unsupported Add_001
  compiler/common-artifacts/exclude.lst
Labels: PR/ready for review

#2997 [TensorFlowLiteRecipes] fix indentation of Add_001
  res/TensorFlowLiteRecipes/Add_001/test.recipe
Labels: PR/ready for review

#2999 [tf2nnpackage-value-remote-test] fix testall script
  compiler/tf2nnpackage-value-remote-test/testall.sh
Labels: PR/ready for review

#3005 [cmake] Add HDF5Config.cmake
  infra/cmake/packages/HDF5Config.cmake
  infra/cmake/packages/HDF5SourceConfig.cmake
Labels: PR/ready for review

#2992 Remove -funsafe-math-optimizations option on armv7 linux build
  infra/nnfw/cmake/buildtool/config/config_armv7l-linux.cmake
Labels: PR/ready for review

#3002 [arser] Introduce arser
  compiler/arser/CMakeLists.txt
  compiler/arser/README.md
  compiler/arser/include/arser/arser.h
  compiler/arser/tests/arser.test.cpp
Labels: PR/ready for review

#3006 [tflite2circle-conversion-test] revise to use common-artifacts
  compiler/tflite2circle-conversion-test/CMakeLists.txt
  compiler/tflite2circle-conversion-test/requires.cmake
  compiler/tflite2circle-conversion-test/testall.sh
Labels: PR/ready for review

#3008 [nncc] Add HDF5 related option to cmake
  infra/nncc/CMakeLists.txt
Labels: PR/ready for review

#3024 [arser] Support float dtype
  compiler/arser/include/arser/arser.h
  compiler/arser/tests/arser.test.cpp
Labels: PR/ready for review

#3019 [common-artifacts] use internal HDF5
  compiler/common-artifacts/CMakeLists.txt
Labels: PR/ready for review

#3000 [onert] Introduce BUILD_NNAPI_TEST option
  infra/nnfw/cmake/CfgOptionFlags.cmake
  infra/nnfw/cmake/options/options_aarch64-android.cmake
  tests/tools/nnapi_test/CMakeLists.txt
Labels: PR/ready for review

#3029 [common-artifacts] restore HDF5 find package
  compiler/common-artifacts/CMakeLists.txt
Labels: PR/ready for review

#2942 [onert] Remove unused code from ShapeInference
  runtime/onert/core/include/util/ShapeInference.h
  runtime/onert/core/src/util/ShapeInference.cc
Labels: PR/ready for review

#3026 [onert] Remove the member `_constants` from TensorBuilders
  runtime/onert/backend/acl_common/AclTensorBuilder.h
  runtime/onert/backend/cpu/TensorBuilder.cc
  runtime/onert/backend/cpu/TensorBuilder.h
  runtime/onert/core/include/backend/ITensorBuilder.h
  runtime/onert/core/include/backend/ITensorRegister.h
  runtime/onert/core/include/ir/OperandInfo.h
  runtime/onert/core/src/backend/controlflow/TensorBuilder.cc
  runtime/onert/core/src/backend/controlflow/TensorBuilder.h
  runtime/onert/core/src/compiler/ExecutorFactory.cc
  runtime/onert/core/src/compiler/Linear.cc
Labels: PR/ready for review, area/onert

#3011 [onert] Support qassym8 in TransposeLayer
  runtime/onert/backend/cpu/ops/TransposeLayer.cc
  tests/nnapi/nnapi_gtest.skip.aarch64-linux.cpu
  tests/nnapi/nnapi_gtest.skip.armv7l-linux.cpu
  tests/nnapi/nnapi_gtest.skip.x86_64-linux.cpu
Labels: PR/ready for review

#3028 [cmake] Delete HDF5 config file
  infra/cmake/packages/HDF5Config.cmake
  infra/cmake/packages/HDF5SourceConfig.cmake
Labels: PR/ready for review

#3035 [infra/cmake] Update GEMMLowp version
  infra/cmake/packages/GEMMLowpSourceConfig.cmake
Labels: PR/ready for review

#3043 [onert] Update nnapi gtest skiplists
  tests/nnapi/nnapi_gtest.skip.aarch64-linux.acl_cl
  tests/nnapi/nnapi_gtest.skip.aarch64-linux.acl_neon
  tests/nnapi/nnapi_gtest.skip.aarch64-linux.cpu
  tests/nnapi/nnapi_gtest.skip.armv7l-linux.acl_cl
  tests/nnapi/nnapi_gtest.skip.armv7l-linux.acl_neon
  tests/nnapi/nnapi_gtest.skip.armv7l-linux.cpu
  tests/nnapi/nnapi_gtest.skip.noarch.interp
  tests/nnapi/nnapi_gtest.skip.x86_64-linux.cpu
Labels: PR/ready for review

#3009 [record-minmax-conversion-test] Add output path option
  compiler/record-minmax-conversion-test/gen_h5_random_inputs.py
  compiler/record-minmax-conversion-test/testall.sh
Labels: PR/ready for review

#3046 [infra/cmake] Introduce TensorFlowLite 1.13.1 config for compiler
  infra/cmake/packages/TensorFlowLite-1.13.1/Lite/CMakeLists.txt
  infra/cmake/packages/TensorFlowLite-1.13.1/TensorFlowLiteConfig.cmake
  infra/cmake/packages/TensorFlowLite-1.13.1/TensorFlowLiteConfigVersion.cmake
Labels: PR/ready for review

#3065 [gen-core] temporary cmake change
  compiler/gen-core/CMakeLists.txt
Labels: PR/ready for review

#3052 [circle-tensordump] temporary cmake change
  compiler/circle-tensordump/CMakeLists.txt
Labels: PR/ready for review

#3050 [onert] Rename some functions in ShapeInference.h
  runtime/onert/core/include/util/ShapeInference.h
  runtime/onert/core/src/compiler/StaticShapeInference.cc
  runtime/onert/core/src/exec/DynamicShapeInference.cc
  runtime/onert/core/src/util/ShapeInference.cc
Labels: PR/ready for review

#3064 [common-artifacts] temporary cmake change
  compiler/common-artifacts/CMakeLists.txt
Labels: PR/ready for review

#3066 [i5diff] temporary cmake change
  compiler/i5diff/CMakeLists.txt
Labels: PR/ready for review

#3068 [nnkit] temporary cmake change
  compiler/nnkit/actions/HDF5/CMakeLists.txt
Labels: PR/ready for review

#3069 [record-minmax] temporary cmake change
  compiler/record-minmax/CMakeLists.txt
Labels: PR/ready for review

#3056 [tflite2circle] Revise to use arser
  compiler/tflite2circle/CMakeLists.txt
  compiler/tflite2circle/driver/Driver.cpp
  compiler/tflite2circle/requires.cmake
Labels: PR/ready for review

#3071 [pota-quantization-value-test] turn off ctest
  compiler/pota-quantization-value-test/CMakeLists.txt
Labels: PR/ready for review

#3062 [circle-tensordump] Fix README.md
  compiler/circle-tensordump/README.md
Labels: PR/ready for review

#3070 [cmake] temporary cmake change
  infra/cmake/packages/CaffeConfig.cmake
Labels: PR/ready for review

#3078 [pota-quantization-value-test] Revise circle-tensordump interface
  compiler/pota-quantization-value-test/test_fake_wquant.sh
  compiler/pota-quantization-value-test/test_quantization.sh
  compiler/pota-quantization-value-test/test_record_minmax.sh
Labels: PR/ready for review

#3061 [circle-tensordump] Revise to use arser
  compiler/circle-tensordump/CMakeLists.txt
  compiler/circle-tensordump/driver/Driver.cpp
  compiler/circle-tensordump/requires.cmake
Labels: PR/ready for review

#3082 [infra] Revise nnpackage test script
  infra/scripts/docker_collect_nnpkg_resources.sh
Labels: PR/ready for review

#3038 [onert] Revise memory plan traverse of WICPlanner
  runtime/onert/core/src/backend/cpu_common/MemoryPlanner.cc
  runtime/onert/core/src/backend/cpu_common/MemoryPlanner.h
Labels: PR/ready for review, area/onert

#3051 [luci-interpreter] Dynamic shapes support
  compiler/luci-interpreter/src/Interpreter.cpp
  compiler/luci-interpreter/src/core/RuntimeGraph.cpp
  compiler/luci-interpreter/src/core/RuntimeGraph.h
  compiler/luci-interpreter/src/core/RuntimeModule.h
  compiler/luci-interpreter/src/kernels/If.cpp
  compiler/luci-interpreter/src/loader/KernelBuilder.cpp
Labels: PR/ready for review

#3034 [onert] Remove ShapeFixer from backends
  runtime/onert/backend/acl_cl/Backend.h
  runtime/onert/backend/acl_cl/ShapeFixer.cc
  runtime/onert/backend/acl_cl/ShapeFixer.h
  runtime/onert/backend/acl_neon/Backend.h
  runtime/onert/backend/acl_neon/ShapeFixer.cc
  runtime/onert/backend/acl_neon/ShapeFixer.h
  runtime/onert/backend/cpu/Backend.h
  runtime/onert/backend/cpu/ShapeFixer.cc
  runtime/onert/backend/cpu/ShapeFixer.h
  runtime/onert/core/include/backend/BackendContext.h
  runtime/onert/core/include/backend/IShapeFixer.h
  runtime/onert/core/src/backend/BackendContext.cc
  runtime/onert/core/src/backend/controlflow/Backend.h
  runtime/onert/core/src/compiler/ExecutorFactory.cc
  runtime/onert/core/src/compiler/HEScheduler.cc
  runtime/onert/core/src/compiler/Linear.cc
  runtime/onert/test/core/compiler/Scheduler.cc
Labels: PR/ready for review, area/onert

#3067 [nnc] temporary cmake change
  compiler/nnc/cmake/config.cmake
  compiler/nnc/tests/acl_soft_backend/CMakeLists.txt
  compiler/nnc/tests/acl_soft_backend/artifact_cmake/CMakeLists.txt
Labels: PR/ready for review

#3084 [pota-quantization-value-test] turn on fake_wquant test
  compiler/pota-quantization-value-test/CMakeLists.txt
Labels: PR/ready for review

#3090 [infra/cmake] Introduce TensorFlowProtoText 1.13.1
  infra/cmake/packages/TensorFlowProtoText-1.13.1/TensorFlowProtoTextConfig.cmake
  infra/cmake/packages/TensorFlowProtoText-1.13.1/TensorFlowProtoTextConfigVersion.cmake
  infra/cmake/packages/TensorFlowProtoText-1.13.1/build/CMakeLists.txt
  infra/cmake/packages/TensorFlowProtoText-1.13.1/make_directories.sh
Labels: PR/ready for review

#3089 [nnkit-tflite] Use TensorFlowLite 1.13.1
  compiler/nnkit-tflite/CMakeLists.txt
  compiler/nnkit-tflite/backend/Backend.cpp
  compiler/nnkit-tflite/support/CMakeLists.txt
  compiler/nnkit-tflite/support/include/nnkit/support/tflite/AbstractBackend.h
  compiler/nnkit-tflite/support/include/nnkit/support/tflite/TensorSet.h
  compiler/nnkit-tflite/support/include/nnkit/support/tflite/TensorSets.h
  compiler/nnkit-tflite/support/include/nnkit/support/tflite/TensorUtils.h
Labels: PR/ready for review

#3031 [infra/cmake] Revise runtime flatbuffers config
  infra/nnfw/cmake/packages/FlatBuffersConfig.cmake
  infra/nnfw/cmake/packages/FlatBuffersSourceConfig.cmake
  infra/nnfw/cmake/packages/TensorFlowLite-1.13.1/TensorFlowLite/CMakeLists.txt
  infra/nnfw/cmake/packages/TensorFlowLite-1.13.1/TensorFlowLiteConfig.cmake
  runtime/contrib/android_benchmark_app/CMakeLists.txt
Labels: PR/ready for review

#3098 [luci-interpreter] Fix unused variable error in If kernel
  compiler/luci-interpreter/src/kernels/If.cpp
Labels: Urgent

#3097 [onert] Fix android build fail by unused field
  runtime/onert/core/src/compiler/HEScheduler.h
Labels: PR/ready for review, trivial

#2954 [onert] Add some caching conditions in FullyConnectedLayer
  runtime/onert/backend/cpu/ops/FullyConnectedLayer.cc
  runtime/onert/backend/cpu/ops/FullyConnectedLayer.h
Labels: PR/ready for review, area/onert

#3101 [cmake] Add HDF5 Config
  infra/cmake/packages/HDF5Config.cmake
  infra/cmake/packages/HDF5SourceConfig.cmake
Labels: PR/ready for review

#3105 [common-artifacts] common venv
  compiler/common-artifacts/CMakeLists.txt
Labels: PR/ready for review

#3108 [circle-tensordump] Use own built HDF5 package
  compiler/circle-tensordump/CMakeLists.txt
Labels: PR/ready for review

#3110 [gen-core] Use own built HDF5 package
  compiler/gen-core/CMakeLists.txt
Labels: PR/ready for review

#3111 [i5diff] Use own built HDF5 package
  compiler/i5diff/CMakeLists.txt
Labels: PR/ready for review

#3112 [nnc] Use own built HDF5 package
  compiler/nnc/cmake/config.cmake
  compiler/nnc/tests/acl_soft_backend/CMakeLists.txt
  compiler/nnc/tests/acl_soft_backend/artifact_cmake/CMakeLists.txt
Labels: PR/ready for review

#3113 [nnkit] Use own built HDF5 package
  compiler/nnkit/actions/HDF5/CMakeLists.txt
Labels: PR/ready for review

#3114 [record-minmax] Use own built HDF5 package
  compiler/record-minmax/CMakeLists.txt
Labels: PR/ready for review

#3115 [cmake] Use own built HDF5 package in Caffe
  infra/cmake/packages/CaffeConfig.cmake
Labels: PR/ready for review

#3106 [circle-tensordump] Add cmake message
  compiler/circle-tensordump/CMakeLists.txt
Labels: PR/ready for review

#3107 [mio-tflite] Add cmake message
  compiler/mio-tflite/CMakeLists.txt
Labels: PR/ready for review

#3116 [tflchef] Add cmake message
  compiler/tflchef/CMakeLists.txt
Labels: PR/ready for review

#3118 [tfldump] Add cmake message
  compiler/tfldump/CMakeLists.txt
Labels: PR/ready for review

#3120 [tflite2circle] Use standard library
  compiler/tflite2circle/CMakeLists.txt
  compiler/tflite2circle/driver/Driver.cpp
  compiler/tflite2circle/include/CircleModel.h
  compiler/tflite2circle/requires.cmake
  compiler/tflite2circle/src/CircleModel.cpp
Labels: PR/ready for review

#3040 [onert] renaming StaticInferer and DynamicInferer
  runtime/onert/backend/cpu/KernelGenerator.cc
  runtime/onert/core/include/compiler/StaticShapeInference.h
  runtime/onert/core/include/exec/DynamicShapeInference.h
  runtime/onert/core/include/exec/FunctionSequence.h
  runtime/onert/core/src/compiler/Compiler.cc
  runtime/onert/core/src/compiler/StaticShapeInference.cc
  runtime/onert/core/src/exec/DynamicShapeInference.cc
Labels: PR/ready for review

#3086 [onert] Update version eigen
  compute/cker/CMakeLists.txt
  compute/cker/include/cker/eigen/eigen_convolution_helpers.h
  compute/cker/include/cker/eigen/eigen_spatial_convolutions-inl.h
  compute/cker/include/cker/eigen/eigen_tensor_reduced_instantiations_oss.h
  infra/cmake/packages/TensorFlowEigenSource-2.3.0-rc0Config.cmake
  infra/nnfw/cmake/packages/EigenConfig.cmake
  infra/nnfw/cmake/packages/EigenSourceConfig.cmake
  infra/nnfw/cmake/packages/TensorFlowEigen-1.13.1/TensorFlowEigenConfig.cmake
  infra/nnfw/cmake/packages/TensorFlowEigen-1.13.1/TensorFlowEigenConfigVersion.cmake
  infra/nnfw/cmake/packages/TensorFlowLite-1.13.1/TensorFlowLite/CMakeLists.txt
  infra/nnfw/cmake/packages/TensorFlowLite-1.13.1/TensorFlowLiteConfig.cmake
  packaging/eigen.tar.gz
Labels: PR/ready for review

#3109 [common-artifacts] Use own built HDF5 package
  compiler/common-artifacts/CMakeLists.txt
Labels: PR/ready for review

#3129 [onert] Initialize FullyConnectedLayer's field
  runtime/onert/backend/cpu/ops/FullyConnectedLayer.cc
Labels: PR/ready for review, trivial

#3044 [onert] Find a model has dynamic tensor at compilation time
  runtime/onert/core/include/compiler/StaticShapeInference.h
  runtime/onert/core/include/ir/OpSequence.h
  runtime/onert/core/src/compiler/Compiler.cc
  runtime/onert/core/src/compiler/StaticShapeInference.cc
Labels: PR/ready for review

#3139 [tf2tfliteV2-conversion-test] Use common-artifacts
  compiler/tf2tfliteV2-conversion-test/CMakeLists.txt
  compiler/tf2tfliteV2-conversion-test/requirements.txt
  compiler/tf2tfliteV2-conversion-test/requires.cmake
Labels: PR/ready for review

#3128 [record-minmax-conversion-test] Use common-artifacts
  compiler/record-minmax-conversion-test/CMakeLists.txt
  compiler/record-minmax-conversion-test/requirements.txt
  compiler/record-minmax-conversion-test/requires.cmake
  compiler/record-minmax-conversion-test/testall.sh
Labels: PR/ready for review

#3131 [pota-quantization-value-test] Use common-artifacts
  compiler/pota-quantization-value-test/CMakeLists.txt
  compiler/pota-quantization-value-test/requirements.txt
  compiler/pota-quantization-value-test/requires.cmake
  compiler/pota-quantization-value-test/test_fake_wquant.sh
  compiler/pota-quantization-value-test/test_quantization.sh
  compiler/pota-quantization-value-test/test_record_minmax.sh
Labels: PR/ready for review

#3140 [luci-value-test] Use common-artifacts
  compiler/luci-value-test/CMakeLists.txt
  compiler/luci-value-test/evalverify.sh
  compiler/luci-value-test/requirements.txt
  compiler/luci-value-test/requires.cmake
Labels: PR/ready for review

#3142 [arser] Support multiple string argument
  compiler/arser/include/arser/arser.h
  compiler/arser/tests/arser.test.cpp
Labels: PR/ready for review

#3157 [packaging] Update default preset version
  infra/packaging/build
Labels: PR/ready for review

#3042 [onert] Make FunctionSequence::run() handle dynamic tensor
  runtime/onert/core/include/exec/FunctionSequence.h
  runtime/onert/core/src/exec/FunctionSequence.cc
Labels: PR/ready for review

#3163 [onert] Fix no member named `DynamicInferer`
  runtime/onert/core/include/exec/FunctionSequence.h
Labels: Urgent

#3045 [onert] Implement LOG_SOFTMAX operation in cpu backend
  compute/cker/include/cker/Types.h
  compute/cker/include/cker/operation/LogSoftMax.h
  runtime/onert/backend/cpu/KernelGenerator.cc
  runtime/onert/backend/cpu/KernelGenerator.h
  runtime/onert/backend/cpu/ops/LogSoftMaxLayer.cc
  runtime/onert/backend/cpu/ops/LogSoftMaxLayer.h
  runtime/onert/core/include/ir/Operations.Include.h
  runtime/onert/core/include/ir/Operations.lst
  runtime/onert/core/include/ir/operation/LogSoftmax.h
  runtime/onert/core/src/compiler/OperationValidator.cc
  runtime/onert/core/src/compiler/OperationValidator.h
  runtime/onert/core/src/ir/operation/LogSoftmax.cc
  runtime/onert/frontend/base_loader/include/base_loader.h
  runtime/onert/frontend/nnapi/wrapper/OperationFactory.cc
  tests/nnapi/nnapi_gtest.skip.aarch64-linux.acl_cl
  tests/nnapi/nnapi_gtest.skip.aarch64-linux.acl_neon
  tests/nnapi/nnapi_gtest.skip.armv7l-linux.acl_cl
  tests/nnapi/nnapi_gtest.skip.armv7l-linux.acl_neon
  tests/nnapi/nnapi_gtest.skip.noarch.interp
  tests/nnapi/specs/V1_2/log_softmax_nnfw.mod.py
Labels: PR/ready for review

#3164 [onert] Remove code duplication in OperationValidator
  runtime/onert/core/src/compiler/OperationValidator.cc
  runtime/onert/core/src/compiler/OperationValidator.h
Labels: PR/ready for review, trivial

#3168 [arser] Support exit_with api
  compiler/arser/include/arser/arser.h
  compiler/arser/tests/arser.test.cpp
Labels: PR/ready for review

#3170 [onert] Add override to ShapeInferer methods
  runtime/onert/core/include/compiler/StaticShapeInference.h
  runtime/onert/core/include/exec/DynamicShapeInference.h
Labels: PR/ready for review, trivial

#3180 [common-artifacts] Support circle recipe
  compiler/common-artifacts/CMakeLists.txt
  compiler/common-artifacts/exclude.lst
  compiler/common-artifacts/requires.cmake
Labels: PR/ready for review

#3194 [arser] fix type mismatch
  compiler/arser/include/arser/arser.h
Labels: trivial

#3176 [onert] Fix typo in StaticShapeInference.cc
  runtime/onert/core/src/compiler/StaticShapeInference.cc
Labels: trivial

#3199 [circle-verify] Use standard library
  compiler/circle-verify/CMakeLists.txt
  compiler/circle-verify/requires.cmake
  compiler/circle-verify/src/Driver.cpp
Labels: PR/ready for review

#3182 [onert] Change FunctionSequence::SetDynamicTensorContext() signature
  runtime/onert/core/include/exec/FunctionSequence.h
  runtime/onert/core/src/exec/FunctionSequence.cc
Labels: PR/ready for review

#3200 [circlechef] Use arser
  compiler/circlechef/requires.cmake
  compiler/circlechef/tools/file/CMakeLists.txt
  compiler/circlechef/tools/file/Driver.cpp
  compiler/circlechef/tools/reverse/CMakeLists.txt
  compiler/circlechef/tools/reverse/Driver.cpp
Labels: PR/ready for review

#3201 [circledump] Use standard library
  compiler/circledump/CMakeLists.txt
  compiler/circledump/requires.cmake
  compiler/circledump/src/OpPrinter.cpp
Labels: PR/ready for review

#3203 [tflchef] Use arser
  compiler/tflchef/requires.cmake
  compiler/tflchef/tools/file/CMakeLists.txt
  compiler/tflchef/tools/file/Driver.cpp
  compiler/tflchef/tools/reverse/CMakeLists.txt
  compiler/tflchef/tools/reverse/Driver.cpp
Labels: PR/ready for review

#3205 [tfl-verify] Use standard library
  compiler/tfl-verify/CMakeLists.txt
  compiler/tfl-verify/requires.cmake
  compiler/tfl-verify/src/Driver.cpp
Labels: PR/ready for review

#3206 [circle-verify] Use arser
  compiler/circle-verify/CMakeLists.txt
  compiler/circle-verify/requires.cmake
  compiler/circle-verify/src/Driver.cpp
Labels: PR/ready for review

#3204 [tfldump] Use standard library
  compiler/tfldump/CMakeLists.txt
  compiler/tfldump/requires.cmake
  compiler/tfldump/src/OpPrinter.cpp
Labels: PR/ready for review

#3214 [common-artifacts] Copy rule file
  compiler/common-artifacts/CMakeLists.txt
Labels: PR/ready for review

#3209 [common-artifacts] modify cmake HDF5 missing message
  compiler/common-artifacts/CMakeLists.txt
Labels: PR/ready for review

#3207 [onert] Fix dumper bug on constant tensor
  runtime/onert/core/src/dumper/dot/DotDumper.cc
Labels: PR/ready for review

#3186 [onert] Make exec::Job work for FunctionSequence (not IFunction)
  runtime/onert/core/src/exec/Job.cc
  runtime/onert/core/src/exec/Job.h
  runtime/onert/core/src/exec/ParallelExecutor.cc
Labels: PR/ready for review

#3215 [circledump] Use arser
  compiler/circledump/CMakeLists.txt
  compiler/circledump/driver/Driver.cpp
  compiler/circledump/requires.cmake
Labels: PR/ready for review

#3222 [tfldump] Use arser
  compiler/tfldump/CMakeLists.txt
  compiler/tfldump/driver/Driver.cpp
  compiler/tfldump/requires.cmake
Labels: PR/ready for review

#3173 [onert] Unify Reduce operations
  runtime/onert/backend/acl_cl/KernelGenerator.cc
  runtime/onert/backend/acl_cl/KernelGenerator.h
  runtime/onert/backend/acl_common/Convert.cc
  runtime/onert/backend/acl_common/Convert.h
  runtime/onert/backend/acl_neon/KernelGenerator.cc
  runtime/onert/backend/acl_neon/KernelGenerator.h
  runtime/onert/backend/cpu/KernelGenerator.cc
  runtime/onert/backend/cpu/KernelGenerator.h
  runtime/onert/core/include/compiler/StaticShapeInference.h
  runtime/onert/core/include/exec/DynamicShapeInference.h
  runtime/onert/core/include/ir/Operations.Include.h
  runtime/onert/core/include/ir/Operations.lst
  runtime/onert/core/include/ir/operation/Reduce.h
  runtime/onert/core/include/ir/operation/ReduceAll.h
  runtime/onert/core/include/ir/operation/ReduceAny.h
  runtime/onert/core/include/ir/operation/ReduceMax.h
  runtime/onert/core/include/ir/operation/ReduceMin.h
  runtime/onert/core/include/ir/operation/ReduceSum.h
  runtime/onert/core/src/compiler/OperationValidator.cc
  runtime/onert/core/src/compiler/OperationValidator.h
  runtime/onert/core/src/compiler/StaticShapeInference.cc
  runtime/onert/core/src/exec/DynamicShapeInference.cc
  runtime/onert/core/src/interp/InterpOps.lst
  runtime/onert/core/src/ir/OperationDumper.cc
  runtime/onert/core/src/ir/OperationDumper.h
  runtime/onert/core/src/ir/operation/Mean.cc
  runtime/onert/core/src/ir/operation/Reduce.cc
  runtime/onert/core/src/ir/operation/ReduceAll.cc
  runtime/onert/core/src/ir/operation/ReduceAny.cc
  runtime/onert/core/src/ir/operation/ReduceMax.cc
  runtime/onert/core/src/ir/operation/ReduceMin.cc
  runtime/onert/core/src/ir/operation/ReduceProd.cc
  runtime/onert/core/src/ir/operation/ReduceSum.cc
  runtime/onert/frontend/base_loader/include/base_loader.h
  runtime/onert/frontend/nnapi/wrapper/OperationFactory.cc
Labels: PR/ready for review, area/onert

#3188 [onert] Deallocate memory used by CustomKernel
  runtime/onert/api/src/CustomKernel.cc
  runtime/onert/api/src/CustomKernel.h
Labels: PR/ready for review
