Repository Samsung/ONE, pull requests merged in 2021-03, with the labels that each got.

#6105 [onert/lib] Introduce tflite output resetter
  runtime/libs/tflite/include/tflite/OutputResetter.h
  runtime/libs/tflite/src/OutputResetter.cpp
  runtime/libs/tflite/src/RandomTestRunner.cpp
Labels: PR/ready for review

#6077 [onert] Throw exception when backend mapping failed
  runtime/onert/core/src/compiler/LoweredGraph.cc
Labels: PR/ready for review

#6194 [onert/cpu] Support int64 Slice begins and sizes
  runtime/onert/backend/cpu/ops/SliceLayer.cc
  runtime/onert/core/include/util/ShapeInference.h
  runtime/onert/core/src/compiler/StaticShapeInferer.cc
  runtime/onert/core/src/ir/OperationValidator.cc
  runtime/onert/core/src/ir/OperationValidator.h
  runtime/onert/core/src/util/ShapeInference.cc
  tests/nnfw_api/src/CircleGen.cc
  tests/nnfw_api/src/CircleGen.h
  tests/nnfw_api/src/one_op_tests/Slice.cc
Labels: PR/ready for review

#6205 [luci] Fix FuseActivationFunctionPass
  compiler/luci/pass/src/FuseActivationFunctionPass.cpp
Labels: Urgent

#6201 [onert] Skip permute shape calculation
  runtime/onert/core/src/ir/Shape.cc
Labels: PR/ready for review

#6225 [circledump] Introduce MetadataPrinter
  compiler/circledump/src/Dump.cpp
  compiler/circledump/src/MetadataPrinter.cpp
  compiler/circledump/src/MetadataPrinter.h
Labels: PR/ready for review

#6235 [luci/export] Remove duplicated header file
  compiler/luci/export/src/CircleExporterImpl.h
Labels: trivial

#6233 [circle-quantizer] Add profiling_data_gen option
  compiler/circle-quantizer/CMakeLists.txt
  compiler/circle-quantizer/src/CircleQuantizer.cpp
Labels: PR/ready for review

#6238 [luci] Propagate origin in optimization pass
  compiler/luci/pass/CMakeLists.txt
  compiler/luci/pass/src/ForwardReshapeToUnaryOpPass.cpp
  compiler/luci/pass/src/FuseAddWithTConvPass.cpp
  compiler/luci/pass/src/FuseBCQPass.cpp
  compiler/luci/pass/src/FuseBatchNormWithConvPass.cpp
  compiler/luci/pass/src/FuseBatchNormWithDwConvPass.cpp
  compiler/luci/pass/src/FuseBatchNormWithTConvPass.cpp
  compiler/luci/pass/src/FuseInstanceNormPass.cpp
  compiler/luci/pass/src/FusePreActivationBatchNormPass.cpp
  compiler/luci/pass/src/RemoveRedundantTransposePass.cpp
  compiler/luci/pass/src/ReplaceMulAddWithDepthwiseConvPass.cpp
  compiler/luci/pass/src/ResolveCustomOpAddPass.cpp
  compiler/luci/pass/src/ResolveCustomOpBatchMatMulPass.cpp
  compiler/luci/pass/src/ResolveCustomOpMatMulPass.cpp
  compiler/luci/pass/src/SubstitutePackToReshapePass.cpp
  compiler/luci/pass/src/SubstituteSqueezeToReshapePass.cpp
  compiler/luci/pass/src/SubstituteTransposeToReshapePass.cpp
  compiler/luci/pass/src/TransformMinMaxToRelu6Pass.cpp
Labels: PR/ready for review

#6242 [luci/export] Rename CircleMetadataExporter to CircleExportMetadata
  compiler/luci/export/src/CircleExportMetadata.cpp
Labels: trivial

#6076 [onert/lib] Move CopyInputInitializer class definition
  runtime/libs/tflite/include/tflite/CopyInputInitializer.h
  runtime/libs/tflite/src/CopyInputInitializer.cpp
  runtime/libs/tflite/src/RandomTestRunner.cpp
Labels: PR/ready for review

#6247 [onert] Fix dynamic casting
  runtime/onert/core/include/backend/cpu_common/BackendContextHelpers.h
  runtime/onert/core/src/util/MDTableEventWriter.cc
Labels: PR/ready for review

#6249 [onert] Initialize DurationEvent fields
  runtime/onert/core/src/util/EventRecorder.h
Labels: PR/ready for review

#6248 [onert] Fix OperationValidator bug
  runtime/onert/core/src/ir/OperationValidator.cc
Labels: PR/ready for review

#6237 Remove Hall of fame in README.md
  README.md
Labels: trivial

#6252 [circle2circle] change `profiling_data_gen` option name
  compiler/circle2circle/src/Circle2Circle.cpp
Labels: PR/ready for review

#6253 [circle-quantizer] change `profiling_data_gen` option name
  compiler/circle-quantizer/src/CircleQuantizer.cpp
Labels: PR/ready for review

#6260 [luci/import] Remove duplicate comments
  compiler/luci/export/src/CircleExportMetadata.cpp
  compiler/luci/import/src/CircleImportMetadata.cpp
Labels: trivial

#6250 [one-cmds] Add profiling option
  compiler/one-cmds/how-to-use-one-commands.txt
  compiler/one-cmds/one-build.template.cfg
  compiler/one-cmds/one-optimize
  compiler/one-cmds/one-quantize
  compiler/one-cmds/utils.py
Labels: PR/ready for review

#6263 [onert/lib] Revise RandomTestRunner compile and run method
  runtime/libs/tflite/src/RandomTestRunner.cpp
Labels: PR/ready for review

#6267 [onert/lib] Use switch-case for RandomInputInitializer
  runtime/libs/tflite/src/RandomInputInitializer.cpp
Labels: PR/ready for review, trivial

#6272 [onert] Enable clang format check in BackendManager
  runtime/onert/core/src/compiler/BackendManager.cc
Labels: PR/ready for review, trivial

#6275 [onert/frontend] Use std::string to pass package dir path
  runtime/onert/api/src/nnfw_api_internal.cc
  runtime/onert/frontend/base_loader/include/base_loader.h
  runtime/onert/frontend/circle/include/circle_loader.h
  runtime/onert/frontend/circle/src/circle_loader.cc
  runtime/onert/frontend/tflite/include/tflite_loader.h
  runtime/onert/frontend/tflite/src/tflite_loader.cc
Labels: PR/ready for review, trivial

#6283 [one-cmds] Fix one-codegen bug
  compiler/one-cmds/one-codegen
Labels: PR/ready for review, Urgent

#6285 [one-cmds] Make up for insufficient description of one-codegen
  compiler/one-cmds/one-codegen
Labels: PR/ready for review, Urgent

#6289 [one-cmds] fix one-quantize to propagate profile data properly
  compiler/one-cmds/one-quantize
Labels: PR/ready for review, Urgent

#6288 [record-minmax] Add profile option
  compiler/record-minmax/CMakeLists.txt
  compiler/record-minmax/driver/Driver.cpp
Labels: PR/ready for review, Urgent

#6287 [onert] Remove ParamChecker
  runtime/onert/core/include/compiler/Compiler.h
  runtime/onert/core/src/compiler/Compiler.cc
  runtime/onert/core/src/compiler/ParamChecker.cc
  runtime/onert/core/src/compiler/ParamChecker.h
Labels: PR/ready for review

#6293 Release Note for ONE 1.14.0
  docs/release/1.14/index.rst
  docs/release/1.14/release-note-1.14.0.md
Labels: PR/ready for review

#6298 [runtime] Remove coverage build option from test library
  runtime/libs/profiling/CMakeLists.txt
  runtime/libs/rua/anchor/CMakeLists.txt
  runtime/libs/rua/dyn/CMakeLists.txt
  runtime/libs/tflite/CMakeLists.txt
Labels: PR/ready for review

#6300 [one-cmds] one-codegen backward compatibility
  compiler/one-cmds/one-codegen
  compiler/one-cmds/tests/one-codegen_002.test
  compiler/one-cmds/tests/one-codegen_003.test
  compiler/one-cmds/tests/one-codegen_004.test
Labels: PR/ready for review, type/release

#6299 [one-cmds] one-codegen backward compatibility
  compiler/one-cmds/one-codegen
  compiler/one-cmds/tests/one-codegen_002.test
  compiler/one-cmds/tests/one-codegen_003.test
  compiler/one-cmds/tests/one-codegen_004.test
Labels: PR/ready for review

#6276 Fix wrong compilation option in some tizen toolchains
  infra/nnfw/cmake/packages/XnnpackConfig.cmake
Labels: target/tizen

#6308 [luci] Remove unused loco headers
  compiler/luci/pass/src/FoldDequantizePass.cpp
  compiler/luci/service/src/CircleTypeInferenceHelper.cpp
  compiler/luci/service/src/Validate.cpp
Labels: trivial

#6307 [luci] Remove unused shape/type inference pass
  compiler/luci/pass/include/luci/Pass/ShapeInferencePass.h
  compiler/luci/pass/include/luci/Pass/TypeInferencePass.h
  compiler/luci/pass/src/ShapeInferencePass.cpp
  compiler/luci/pass/src/TypeInferencePass.cpp
  compiler/luci/tester/src/ReadModule.cpp
Labels: trivial

#6311 [luci] Remove unused loco headers - 2
  compiler/luci/pass/src/ConvertNCHWToNHWCPass.cpp
  compiler/luci/pass/src/FuseInstanceNormPass.cpp
  compiler/luci/service/src/CircleShapeInference.cpp
  compiler/luci/service/src/CircleShapeInferenceHelper.cpp
  compiler/luci/service/src/ShapeInfer_StridedSlice.cpp
Labels: trivial

#6316 [luci/service] Remove old inference algorithm of CircleIfOut
  compiler/luci/service/src/CircleInferenceHelper.cpp
  compiler/luci/service/src/CircleInferenceHelper.h
  compiler/luci/service/src/CircleShapeInferenceRule.cpp
  compiler/luci/service/src/CircleTypeInferenceRule.cpp
Labels: trivial

#6322 [onert] Rename "cpu_common" to "basic"
  runtime/onert/backend/acl_cl/KernelGenerator.h
  runtime/onert/backend/acl_neon/KernelGenerator.h
  runtime/onert/backend/cpu/BackendContext.cc
  runtime/onert/backend/cpu/KernelGenerator.h
  runtime/onert/backend/cpu/StaticTensorManager.h
  runtime/onert/backend/cpu/Tensor.h
  runtime/onert/backend/cpu/TensorBuilder.h
  runtime/onert/backend/ruy/BackendContext.cc
  runtime/onert/backend/ruy/KernelGenerator.h
  runtime/onert/backend/ruy/StaticTensorManager.h
  runtime/onert/backend/ruy/Tensor.h
  runtime/onert/backend/ruy/TensorBuilder.h
  runtime/onert/backend/xnnpack/BackendContext.cc
  runtime/onert/backend/xnnpack/KernelGenerator.h
  runtime/onert/backend/xnnpack/StaticTensorManager.h
  runtime/onert/backend/xnnpack/Tensor.h
  runtime/onert/backend/xnnpack/TensorBuilder.h
  runtime/onert/core/include/backend/basic/Allocator.h
  runtime/onert/core/include/backend/basic/BackendContextHelpers.h
  runtime/onert/core/include/backend/basic/DynamicTensorManager.h
  runtime/onert/core/include/backend/basic/IMemoryPlanner.h
  runtime/onert/core/include/backend/basic/KernelGeneratorBase.h
  runtime/onert/core/include/backend/basic/MemoryManager.h
  runtime/onert/core/include/backend/basic/StaticTensorManager.h
  runtime/onert/core/include/backend/basic/Tensor.h
  runtime/onert/core/include/backend/basic/TensorBuilder.h
  runtime/onert/core/include/backend/basic/TensorRegistry.h
  runtime/onert/core/include/backend/cpu_common/Allocator.h
  runtime/onert/core/src/backend/basic/Allocator.cc
  runtime/onert/core/src/backend/basic/BackendContextHelpers.cc
  runtime/onert/core/src/backend/basic/DynamicTensorManager.cc
  runtime/onert/core/src/backend/basic/MemoryManager.cc
  runtime/onert/core/src/backend/basic/MemoryPlanner.cc
  runtime/onert/core/src/backend/basic/MemoryPlanner.h
  runtime/onert/core/src/backend/basic/MemoryPlanner.test.cc
  runtime/onert/core/src/backend/basic/MemoryPlannerFactory.cc
  runtime/onert/core/src/backend/basic/MemoryPlannerFactory.h
  runtime/onert/core/src/backend/basic/StaticTensorManager.cc
  runtime/onert/core/src/backend/basic/Tensor.cc
  runtime/onert/core/src/backend/basic/TensorBuilder.cc
  runtime/onert/core/src/backend/builtin/BackendContext.cc
  runtime/onert/core/src/backend/builtin/ConstantInitializer.h
  runtime/onert/core/src/backend/builtin/KernelGenerator.h
  runtime/onert/core/src/backend/builtin/Tensor.h
  runtime/onert/core/src/backend/builtin/TensorBuilder.h
  runtime/onert/core/src/backend/builtin/TensorRegistry.h
  runtime/onert/core/src/backend/builtin/kernel/WhileLayer.h
Labels: PR/ready for review, trivial

#6323 [onert] Update basic backend namespace
  runtime/onert/backend/acl_cl/KernelGenerator.cc
  runtime/onert/backend/acl_cl/KernelGenerator.h
  runtime/onert/backend/acl_neon/KernelGenerator.cc
  runtime/onert/backend/acl_neon/KernelGenerator.h
  runtime/onert/backend/cpu/Backend.h
  runtime/onert/backend/cpu/BackendContext.cc
  runtime/onert/backend/cpu/KernelGenerator.cc
  runtime/onert/backend/cpu/KernelGenerator.h
  runtime/onert/backend/cpu/StaticTensorManager.h
  runtime/onert/backend/cpu/Tensor.h
  runtime/onert/backend/cpu/TensorBuilder.h
  runtime/onert/backend/ruy/Backend.h
  runtime/onert/backend/ruy/BackendContext.cc
  runtime/onert/backend/ruy/KernelGenerator.cc
  runtime/onert/backend/ruy/KernelGenerator.h
  runtime/onert/backend/ruy/StaticTensorManager.h
  runtime/onert/backend/ruy/Tensor.h
  runtime/onert/backend/ruy/TensorBuilder.h
  runtime/onert/backend/xnnpack/Backend.h
  runtime/onert/backend/xnnpack/BackendContext.cc
  runtime/onert/backend/xnnpack/KernelGenerator.cc
  runtime/onert/backend/xnnpack/KernelGenerator.h
  runtime/onert/backend/xnnpack/StaticTensorManager.h
  runtime/onert/backend/xnnpack/Tensor.h
  runtime/onert/backend/xnnpack/TensorBuilder.h
  runtime/onert/core/include/backend/basic/Allocator.h
  runtime/onert/core/include/backend/basic/BackendContextHelpers.h
  runtime/onert/core/include/backend/basic/DynamicTensorManager.h
  runtime/onert/core/include/backend/basic/IMemoryPlanner.h
  runtime/onert/core/include/backend/basic/KernelGeneratorBase.h
  runtime/onert/core/include/backend/basic/MemoryManager.h
  runtime/onert/core/include/backend/basic/StaticTensorManager.h
  runtime/onert/core/include/backend/basic/Tensor.h
  runtime/onert/core/include/backend/basic/TensorBuilder.h
  runtime/onert/core/include/backend/basic/TensorRegistry.h
  runtime/onert/core/src/backend/basic/Allocator.cc
  runtime/onert/core/src/backend/basic/DynamicTensorManager.cc
  runtime/onert/core/src/backend/basic/MemoryManager.cc
  runtime/onert/core/src/backend/basic/MemoryPlanner.cc
  runtime/onert/core/src/backend/basic/MemoryPlanner.h
  runtime/onert/core/src/backend/basic/MemoryPlanner.test.cc
  runtime/onert/core/src/backend/basic/MemoryPlannerFactory.cc
  runtime/onert/core/src/backend/basic/MemoryPlannerFactory.h
  runtime/onert/core/src/backend/basic/StaticTensorManager.cc
  runtime/onert/core/src/backend/basic/Tensor.cc
  runtime/onert/core/src/backend/basic/TensorBuilder.cc
  runtime/onert/core/src/backend/builtin/BackendContext.cc
  runtime/onert/core/src/backend/builtin/ConstantInitializer.h
  runtime/onert/core/src/backend/builtin/DynamicTensorManager.h
  runtime/onert/core/src/backend/builtin/KernelGenerator.cc
  runtime/onert/core/src/backend/builtin/KernelGenerator.h
  runtime/onert/core/src/backend/builtin/Tensor.h
  runtime/onert/core/src/backend/builtin/TensorBuilder.cc
  runtime/onert/core/src/backend/builtin/TensorBuilder.h
  runtime/onert/core/src/backend/builtin/TensorRegistry.h
  runtime/onert/core/src/backend/builtin/kernel/WhileLayer.cc
  runtime/onert/core/src/backend/builtin/kernel/WhileLayer.h
Labels: PR/ready for review, trivial

#6329 [onert] Rename core unittest name
  runtime/onert/core/CMakeLists.txt
Labels: PR/ready for review

#6324 [infra] Update configuration file for TCM tools
  .ahub/tcchecker-tca/config.yaml
Labels: PR/ready for review

#6371 [onert] Change frontend loader library to static
  runtime/contrib/android/api/Prebuilt.mk
  runtime/onert/frontend/circle/CMakeLists.txt
  runtime/onert/frontend/tflite/CMakeLists.txt
Labels: PR/ready for review
