Repository Samsung/ONE, pull requests merged in 2021-11, with the labels that each got.

#7905 [infra] Remove remain ARMCompute test build
  infra/nnfw/cmake/packages/ARMComputeConfig.cmake
Labels: PR/ready for review

#7910 [one-cmds] Add input_model_dtype to one-quantize
  compiler/one-cmds/one-quantize
Labels: area/quant

#7917 [luci] Revise logger
  compiler/luci/log/include/luci/Log.h
  compiler/luci/log/src/Log.cpp
Labels: PR/ready for review

#7916 [one-cmds] Improve help message of one-quantize
  compiler/one-cmds/one-quantize
Labels: area/quant

#7915 [one-cmds] Make argument group for force_quantparam
  compiler/one-cmds/one-quantize
Labels: area/quant

#7937 [luci/import] Add VectorWrapper helper struct
  compiler/luci/import/include/luci/Import/CircleReader.h
  compiler/luci/import/src/CircleReader.cpp
  compiler/luci/import/src/CircleReader.test.cpp
Labels: PR/ready for review

#7947 [luci/import] Use direct access for inputs, outputs and name
  compiler/luci/import/src/Importer.cpp
Labels: PR/ready for review

#7949 [luci/import] Add opcode_name and builtin_code definitions
  compiler/luci/import/src/CircleReader.cpp
Labels: PR/ready for review

#7950 [luci/import] Use direct access for metadata
  compiler/luci/import/src/CircleImportMetadata.cpp
Labels: PR/ready for review

#7951 [luci/import] Use direct access for opcodes
  compiler/luci/import/src/GraphBuilder.cpp
  compiler/luci/import/src/GraphBuilderMultiOutput.cpp
  compiler/luci/import/src/Nodes/CircleCustom.cpp
  compiler/luci/import/src/Nodes/CircleWhile.cpp
Labels: PR/ready for review

#7952 [luci/import] Use direct access for operators
  compiler/luci/import/src/Importer.cpp
Labels: PR/ready for review

#7957 [luci/import] Use direct-access tensors from Abs to If
  compiler/luci/import/src/Nodes/CircleCast.cpp
  compiler/luci/import/src/Nodes/CircleConst.cpp
  compiler/luci/import/src/Nodes/CircleDepthToSpace.cpp
  compiler/luci/import/src/Nodes/CircleDepthwiseConv2D.cpp
  compiler/luci/import/src/Nodes/CircleElu.cpp
  compiler/luci/import/src/Nodes/CircleEqual.cpp
  compiler/luci/import/src/Nodes/CircleExp.cpp
  compiler/luci/import/src/Nodes/CircleExpandDims.cpp
  compiler/luci/import/src/Nodes/CircleFloorDiv.cpp
  compiler/luci/import/src/Nodes/CircleFloorMod.cpp
  compiler/luci/import/src/Nodes/CircleGatherNd.cpp
  compiler/luci/import/src/Nodes/CircleGreater.cpp
  compiler/luci/import/src/Nodes/CircleGreaterEqual.cpp
  compiler/luci/import/src/Nodes/CircleIf.cpp
Labels: PR/ready for review

#7956 [luci/import] Use direct-access tensors
  compiler/luci/import/src/GraphBuilder.cpp
  compiler/luci/import/src/GraphBuilderMultiOutput.cpp
  compiler/luci/import/src/Importer.cpp
  compiler/luci/import/src/ValidateHelpers.cpp
Labels: PR/ready for review

#7965 Revert commits
  compiler/luci/import/include/luci/Import/CircleReader.h
  compiler/luci/import/src/CircleImportMetadata.cpp
  compiler/luci/import/src/CircleReader.cpp
  compiler/luci/import/src/GraphBuilder.cpp
  compiler/luci/import/src/GraphBuilderMultiOutput.cpp
  compiler/luci/import/src/Importer.cpp
  compiler/luci/import/src/Nodes/CircleCast.cpp
  compiler/luci/import/src/Nodes/CircleConst.cpp
  compiler/luci/import/src/Nodes/CircleCustom.cpp
  compiler/luci/import/src/Nodes/CircleDepthToSpace.cpp
  compiler/luci/import/src/Nodes/CircleDepthwiseConv2D.cpp
  compiler/luci/import/src/Nodes/CircleElu.cpp
  compiler/luci/import/src/Nodes/CircleEqual.cpp
  compiler/luci/import/src/Nodes/CircleExp.cpp
  compiler/luci/import/src/Nodes/CircleExpandDims.cpp
  compiler/luci/import/src/Nodes/CircleFloorDiv.cpp
  compiler/luci/import/src/Nodes/CircleFloorMod.cpp
  compiler/luci/import/src/Nodes/CircleGatherNd.cpp
  compiler/luci/import/src/Nodes/CircleGreater.cpp
  compiler/luci/import/src/Nodes/CircleGreaterEqual.cpp
  compiler/luci/import/src/Nodes/CircleIf.cpp
  compiler/luci/import/src/Nodes/CircleWhile.cpp
  compiler/luci/import/src/ValidateHelpers.cpp
  compiler/one-cmds/one-build
  compiler/one-cmds/one-codegen
  compiler/one-cmds/one-import-bcq
  compiler/one-cmds/one-import-onnx
  compiler/one-cmds/one-import-tf
  compiler/one-cmds/one-import-tflite
  compiler/one-cmds/one-optimize
  compiler/one-cmds/one-pack
  compiler/one-cmds/one-profile
  compiler/one-cmds/one-quantize
  compiler/one-cmds/onecc
  compiler/one-cmds/utils.py
Labels: PR/ready for review

#7963 [onert] debian pkg verison 1.19.0
  infra/debian/runtime/changelog
Labels: type/release

#7968 [infra] Update compiler changelog for 1.19.0
  infra/debian/compiler/changelog
Labels: PR/ready for review, type/release

#7967 Release note 1.19.0
  docs/release/1.19/index.rst
  docs/release/1.19/release-note-1.19.0.md
Labels: type/release

#7970 [vconone] Bump to 1.20.0
  compiler/vconone/CMakeLists.txt
Labels: PR/ready for review

#7988 [luci/import] Return reverted commits
  compiler/luci/import/include/luci/Import/CircleReader.h
  compiler/luci/import/src/CircleImportMetadata.cpp
  compiler/luci/import/src/CircleReader.cpp
  compiler/luci/import/src/GraphBuilder.cpp
  compiler/luci/import/src/GraphBuilderMultiOutput.cpp
  compiler/luci/import/src/Importer.cpp
  compiler/luci/import/src/Nodes/CircleCast.cpp
  compiler/luci/import/src/Nodes/CircleConst.cpp
  compiler/luci/import/src/Nodes/CircleCustom.cpp
  compiler/luci/import/src/Nodes/CircleDepthToSpace.cpp
  compiler/luci/import/src/Nodes/CircleDepthwiseConv2D.cpp
  compiler/luci/import/src/Nodes/CircleElu.cpp
  compiler/luci/import/src/Nodes/CircleEqual.cpp
  compiler/luci/import/src/Nodes/CircleExp.cpp
  compiler/luci/import/src/Nodes/CircleExpandDims.cpp
  compiler/luci/import/src/Nodes/CircleFloorDiv.cpp
  compiler/luci/import/src/Nodes/CircleFloorMod.cpp
  compiler/luci/import/src/Nodes/CircleGatherNd.cpp
  compiler/luci/import/src/Nodes/CircleGreater.cpp
  compiler/luci/import/src/Nodes/CircleGreaterEqual.cpp
  compiler/luci/import/src/Nodes/CircleIf.cpp
  compiler/luci/import/src/Nodes/CircleWhile.cpp
  compiler/luci/import/src/ValidateHelpers.cpp
Labels: PR/ready for review

#7993 [luci/import] Use direct tensors from NonMaxSuppression to OneHot
  compiler/luci/import/src/Nodes/CircleNonMaxSuppressionV4.cpp
  compiler/luci/import/src/Nodes/CircleNonMaxSuppressionV5.cpp
  compiler/luci/import/src/Nodes/CircleNotEqual.cpp
  compiler/luci/import/src/Nodes/CircleOneHot.cpp
Labels: PR/ready for review

#7994 [luci/import] Use direct tensors from ReduceAny to Reverse
  compiler/luci/import/src/Nodes/CircleReduceAny.cpp
  compiler/luci/import/src/Nodes/CircleReduceProd.cpp
  compiler/luci/import/src/Nodes/CircleReshape.cpp
  compiler/luci/import/src/Nodes/CircleReverseSequence.cpp
  compiler/luci/import/src/Nodes/CircleReverseV2.cpp
Labels: PR/ready for review

#7995 [luci/import] Use direct tensors from Round to Sin
  compiler/luci/import/src/Nodes/CircleRound.cpp
  compiler/luci/import/src/Nodes/CircleRsqrt.cpp
  compiler/luci/import/src/Nodes/CircleScatterNd.cpp
  compiler/luci/import/src/Nodes/CircleSegmentSum.cpp
  compiler/luci/import/src/Nodes/CircleSelect.cpp
  compiler/luci/import/src/Nodes/CircleSelectV2.cpp
  compiler/luci/import/src/Nodes/CircleSin.cpp
Labels: PR/ready for review

#7998 [luci/import] Use direct tensors from Square to TopKV2
  compiler/luci/import/src/Nodes/CircleSquare.cpp
  compiler/luci/import/src/Nodes/CircleSquaredDifference.cpp
  compiler/luci/import/src/Nodes/CircleTanh.cpp
  compiler/luci/import/src/Nodes/CircleTile.cpp
  compiler/luci/import/src/Nodes/CircleTopKV2.cpp
Labels: PR/ready for review

#7999 [luci/import] Use direct tensors from TransposeConv to While
  compiler/luci/import/src/Nodes/CircleTransposeConv.cpp
  compiler/luci/import/src/Nodes/CircleUnpack.cpp
  compiler/luci/import/src/Nodes/CircleWhere.cpp
  compiler/luci/import/src/Nodes/CircleWhile.cpp
Labels: PR/ready for review

#8006 [luci/import] Remove tensors_ptr from CircleReader
  compiler/luci/import/include/luci/Import/CircleReader.h
  compiler/luci/import/src/CircleReader.cpp
Labels: PR/ready for review

#8007 [luci/import] Redefine num_subgraph with direct structures
  compiler/luci/import/include/luci/Import/CircleReader.h
Labels: PR/ready for review

#8008 [luci/import] Use direct access for buffers
  compiler/luci/import/src/CircleImportMetadata.cpp
  compiler/luci/import/src/Nodes/CircleConst.cpp
Labels: PR/ready for review

#8011 [luci/import] Remove UnPack API from CircleReader class
  compiler/luci/import/include/luci/Import/CircleReader.h
  compiler/luci/import/src/CircleReader.cpp
Labels: PR/ready for review

#8014 [luci/import] Remove helpers for UnPack from CircleReader
  compiler/luci/import/include/luci/Import/CircleReader.h
  compiler/luci/import/src/CircleReader.cpp
Labels: PR/ready for review

#8018 [luci/import] Rename native_tensors to tensors
  compiler/luci/import/include/luci/Import/CircleReader.h
  compiler/luci/import/src/GraphBuilder.cpp
  compiler/luci/import/src/GraphBuilderMultiOutput.cpp
  compiler/luci/import/src/Importer.cpp
  compiler/luci/import/src/Nodes/CircleCast.cpp
  compiler/luci/import/src/Nodes/CircleConst.cpp
  compiler/luci/import/src/Nodes/CircleDepthToSpace.cpp
  compiler/luci/import/src/Nodes/CircleDepthwiseConv2D.cpp
  compiler/luci/import/src/Nodes/CircleElu.cpp
  compiler/luci/import/src/Nodes/CircleEqual.cpp
  compiler/luci/import/src/Nodes/CircleExp.cpp
  compiler/luci/import/src/Nodes/CircleExpandDims.cpp
  compiler/luci/import/src/Nodes/CircleFloorDiv.cpp
  compiler/luci/import/src/Nodes/CircleFloorMod.cpp
  compiler/luci/import/src/Nodes/CircleGatherNd.cpp
  compiler/luci/import/src/Nodes/CircleGreater.cpp
  compiler/luci/import/src/Nodes/CircleGreaterEqual.cpp
  compiler/luci/import/src/Nodes/CircleIf.cpp
  compiler/luci/import/src/Nodes/CircleLess.cpp
  compiler/luci/import/src/Nodes/CircleLessEqual.cpp
  compiler/luci/import/src/Nodes/CircleLog.cpp
  compiler/luci/import/src/Nodes/CircleLogicalAnd.cpp
  compiler/luci/import/src/Nodes/CircleLogicalNot.cpp
  compiler/luci/import/src/Nodes/CircleLogicalOr.cpp
  compiler/luci/import/src/Nodes/CircleLogistic.cpp
  compiler/luci/import/src/Nodes/CircleMatrixDiag.cpp
  compiler/luci/import/src/Nodes/CircleMatrixSetDiag.cpp
  compiler/luci/import/src/Nodes/CircleNonMaxSuppressionV4.cpp
  compiler/luci/import/src/Nodes/CircleNonMaxSuppressionV5.cpp
  compiler/luci/import/src/Nodes/CircleNotEqual.cpp
  compiler/luci/import/src/Nodes/CircleOneHot.cpp
  compiler/luci/import/src/Nodes/CircleReduceAny.cpp
  compiler/luci/import/src/Nodes/CircleReduceProd.cpp
  compiler/luci/import/src/Nodes/CircleReshape.cpp
  compiler/luci/import/src/Nodes/CircleReverseSequence.cpp
  compiler/luci/import/src/Nodes/CircleReverseV2.cpp
  compiler/luci/import/src/Nodes/CircleRound.cpp
  compiler/luci/import/src/Nodes/CircleRsqrt.cpp
  compiler/luci/import/src/Nodes/CircleScatterNd.cpp
  compiler/luci/import/src/Nodes/CircleSegmentSum.cpp
  compiler/luci/import/src/Nodes/CircleSelect.cpp
  compiler/luci/import/src/Nodes/CircleSelectV2.cpp
  compiler/luci/import/src/Nodes/CircleSin.cpp
  compiler/luci/import/src/Nodes/CircleSquare.cpp
  compiler/luci/import/src/Nodes/CircleSquaredDifference.cpp
  compiler/luci/import/src/Nodes/CircleTanh.cpp
  compiler/luci/import/src/Nodes/CircleTile.cpp
  compiler/luci/import/src/Nodes/CircleTopKV2.cpp
  compiler/luci/import/src/Nodes/CircleTransposeConv.cpp
  compiler/luci/import/src/Nodes/CircleUnpack.cpp
  compiler/luci/import/src/Nodes/CircleWhere.cpp
  compiler/luci/import/src/Nodes/CircleWhile.cpp
  compiler/luci/import/src/ValidateHelpers.cpp
Labels: PR/ready for review

#8019 [luci/import] Rename inputs, outputs, name and data_format
  compiler/luci/import/include/luci/Import/CircleReader.h
  compiler/luci/import/src/Importer.cpp
Labels: PR/ready for review

#8020 [luci/import] Remove native_ prefix from CircleReader methods
  compiler/luci/import/include/luci/Import/CircleReader.h
  compiler/luci/import/src/CircleImportMetadata.cpp
  compiler/luci/import/src/CircleReader.cpp
  compiler/luci/import/src/GraphBuilder.cpp
  compiler/luci/import/src/GraphBuilderMultiOutput.cpp
  compiler/luci/import/src/Importer.cpp
  compiler/luci/import/src/Nodes/CircleConst.cpp
  compiler/luci/import/src/Nodes/CircleCustom.cpp
  compiler/luci/import/src/Nodes/CircleWhile.cpp
Labels: PR/ready for review

#8021 [luci/import] Remove native_ prefix from member names
  compiler/luci/import/include/luci/Import/CircleReader.h
  compiler/luci/import/src/CircleReader.cpp
Labels: PR/ready for review

#8025 [luci] Remove unnecessary check in PropagateQuantParam
  compiler/luci/pass/src/PropagateQuantParamPass.cpp
Labels: area/quant

#8026 [luci] Support propagation of qparam for more Ops
  compiler/luci/pass/src/PropagateQuantParamPass.cpp
  compiler/luci/pass/src/QuantizeWithMinMaxPass.cpp
Labels: area/quant

#8052 [onert/gpu-cl] Revise ClMemoryManager
  runtime/onert/backend/gpu_cl/ClTensorManager.h
  runtime/onert/backend/gpu_cl/MemoryManager.h
  runtime/onert/backend/gpu_cl/TensorManager.h
  runtime/onert/backend/gpu_cl/ex/InferenceContextEx.h
Labels: PR/ready for review

#8058 [onert/gpu-cl] Revise ClTensorManager
  runtime/onert/backend/gpu_cl/Backend.h
  runtime/onert/backend/gpu_cl/ClTensorBuilder.h
  runtime/onert/backend/gpu_cl/ClTensorManager.cc
  runtime/onert/backend/gpu_cl/ClTensorManager.h
  runtime/onert/backend/gpu_cl/KernelGenerator.cc
  runtime/onert/backend/gpu_cl/KernelGenerator.h
  runtime/onert/backend/gpu_cl/MemoryManager.h
  runtime/onert/backend/gpu_cl/TensorManager.h
Labels: PR/ready for review

#8057 [luci] Support TF-style MaxPool quantization
  compiler/luci/pass/include/luci/CircleOptimizer.h
  compiler/luci/pass/include/luci/Pass/PropagateQuantParamPass.h
  compiler/luci/pass/src/CircleOptimizer.cpp
  compiler/luci/pass/src/PropagateQuantParamPass.cpp
Labels: area/quant

#7987 [luci-interpreter] New PAL interface for Conv2d temporary buffers
  compiler/luci-interpreter/pal/cmsisnn/PALConv2d.h
  compiler/luci-interpreter/pal/linux/PALConv2d.h
  compiler/luci-interpreter/pal/mcu/PALConv2d.h
  compiler/luci-interpreter/src/kernels/Conv2D.cpp
  compiler/luci-interpreter/src/kernels/Conv2D.h
  compiler/luci-interpreter/src/loader/nodes/Conv2D.cpp
Labels: PR/ready for review

#8066 [circle-quantizer] Support TF-style MaxPool Op
  compiler/circle-quantizer/src/CircleQuantizer.cpp
Labels: area/quant
