Repository Samsung/ONE, pull requests merged in 2021-07, with the labels that each got.

#6900 [onert] Async apis for pipelining of Multiexecution
  runtime/onert/api/include/nnfw_experimental.h
  runtime/onert/api/src/nnfw_api.cc
  runtime/onert/api/src/nnfw_api_internal.cc
  runtime/onert/api/src/nnfw_api_internal.h
  runtime/onert/core/include/exec/Execution.h
  runtime/onert/core/include/exec/IODescription.h
  runtime/onert/core/src/exec/Execution.cc
  tests/nnfw_api/src/ValidationTestPipelineSession.cc
Labels: PR/ready for review

#7146 [tflite2circle] Fix error message
  compiler/tflite2circle/src/CircleModel.cpp
Labels: PR/ready for review

#7155 [tfkit] Remove redundant "ERROR" string
  compiler/tfkit/src/Support.cpp
Labels: PR/ready for review

#7153 [record-minmax] Remove redundant "ERROR" string
  compiler/record-minmax/src/RecordMinMax.cpp
Labels: PR/ready for review

#7157 [foder] Remove redundant "ERROR" string
  compiler/foder/include/foder/FileLoader.h
Labels: PR/ready for review

#7156 [onnxkit] Remove redundant "ERROR" string
  compiler/onnxkit/src/Support.cpp
Labels: PR/ready for review

#7160 [record-minmax] Support calibration using raw data
  compiler/record-minmax/include/RecordMinMax.h
  compiler/record-minmax/src/RecordMinMax.cpp
Labels: area/quant

#7170 [record-minmax] Add input_data_format option to record-minmax
  compiler/record-minmax/driver/Driver.cpp
Labels: area/quant

#7174 [one-cmds] Support list data format in one-quantize
  compiler/one-cmds/one-quantize
  compiler/one-cmds/tests/one-build_012.cfg
  compiler/one-cmds/tests/one-build_012.test
  compiler/one-cmds/tests/one-quantize_003.test
  compiler/one-cmds/tests/one-quantize_neg_014.test
  compiler/one-cmds/tests/one-quantize_neg_015.test
  compiler/one-cmds/tests/one-quantize_neg_016.test
Labels: area/quant

#7193 [circle-quantizer] Use the same qparam for input/output of Split
  compiler/luci/pass/src/QuantizeWithMinMaxPass.cpp
  compiler/luci/pass/src/VerifyQuantizedNodeS16Type.h
  compiler/luci/pass/src/VerifyQuantizedNodeU8Type.h
  compiler/pota-quantization-value-test/expected_outputs/Split_000/channel/int16/quantization/ofm1.json
  compiler/pota-quantization-value-test/expected_outputs/Split_000/channel/int16/quantization/ofm2.json
  compiler/pota-quantization-value-test/expected_outputs/Split_000/channel/uint8/quantization/ofm1.json
  compiler/pota-quantization-value-test/expected_outputs/Split_000/channel/uint8/quantization/ofm2.json
Labels: area/quant

#7182 Change debian directory location
  infra/command/format
  infra/debian/compiler/changelog
  infra/debian/compiler/compat
  infra/debian/compiler/control
  infra/debian/compiler/copyright
  infra/debian/compiler/docs/one-build.1
  infra/debian/compiler/docs/one-codegen.1
  infra/debian/compiler/docs/one-import-bcq.1
  infra/debian/compiler/docs/one-import-onnx.1
  infra/debian/compiler/docs/one-import-tf.1
  infra/debian/compiler/docs/one-import-tflite.1
  infra/debian/compiler/docs/one-optimize.1
  infra/debian/compiler/docs/one-pack.1
  infra/debian/compiler/docs/one-quantize.1
  infra/debian/compiler/one-compiler-dev.install
  infra/debian/compiler/one-compiler-dev.links
  infra/debian/compiler/one-compiler-test.install
  infra/debian/compiler/one-compiler.install
  infra/debian/compiler/one-compiler.links
  infra/debian/compiler/one-compiler.manpages
  infra/debian/compiler/postinst
  infra/debian/compiler/postrm
  infra/debian/compiler/rules
  infra/debian/compiler/source/format
  infra/debian/compiler/source/local-options
Labels: PR/ready for review

#7208 [circle-quantizer] Quantize fused Tanh using pre-determined values.
  compiler/luci/pass/src/QuantizeWithMinMaxPass.cpp
Labels: area/quant

#7211 [tools] Remove commit date on nightly build tar file name
  tools/release_tool/onert_version.sh
Labels: PR/ready for review

#7214 [circle-quantizer] Verify optional bias in FC layer.
  compiler/luci/pass/src/VerifyQuantizedNodeChannelWiseGranularity.h
Labels: area/quant

#7215 [circle-quantizer] Propagate quantparam forward direction
  compiler/luci/pass/src/PropagateQuantParamPass.cpp
  compiler/luci/pass/src/PropagateQuantParamPass.test.cpp
Labels: area/quant

#7219 [one-cmds] Remove virtualenv installation command
  compiler/one-cmds/one-prepare-venv
Labels: PR/ready for review

#7255 [infra] Revise postinst
  infra/debian/compiler/postinst
Labels: PR/ready for review

#7268 [luci/partition] Introduce clone_ifnode_subgraphs
  compiler/luci/partition/src/PartitionPModules.cpp
Labels: PR/NO MERGE

#7274 [circle-part-value-test] Adding DEPENDS
  compiler/circle-part-value-test/CMakeLists.txt
Labels: PR/ready for review

#7287 [circle-quantizer] Fix bug in fused TANH quantization
  compiler/luci/pass/src/QuantizeWithMinMaxPass.cpp
Labels: area/quant

#7286 [luci] Improve error msg of QuantizedModelVerifier
  compiler/luci/pass/src/QuantizedModelVerifier.cpp
Labels: area/quant

#7322 [circle-quantizer] Support optional bias in quantizer
  compiler/luci/pass/src/VerifyQuantizedNodeChannelWiseGranularity.h
  compiler/luci/pass/src/VerifyQuantizedNodeLayerWiseGranularity.h
Labels: area/quant

#7296 [onert] Add FloorDiv operation for cpu backend
  compute/cker/include/cker/operation/FloorDiv.h
  runtime/onert/backend/cpu/KernelGenerator.cc
  runtime/onert/backend/cpu/ops/ElementwiseBinaryLayer.cc
  runtime/onert/backend/cpu/ops/ElementwiseBinaryLayer.h
  runtime/onert/core/include/ir/operation/ElementwiseBinary.h
  runtime/onert/core/src/ir/operation/ElementwiseBinary.cc
  runtime/onert/frontend/base_loader/include/base_loader.h
  tests/nnfw_api/src/CircleGen.cc
  tests/nnfw_api/src/CircleGen.h
  tests/nnfw_api/src/one_op_tests/FloorDiv.cc
Labels: PR/ready for review

#7352 [lib/tflite] Remove NNAPI delegator extension
  runtime/libs/tflite/include/tflite/NNAPISession.h
  runtime/libs/tflite/port/1.13.1/include/tflite/ext/nnapi_delegate.h
  runtime/libs/tflite/port/1.13.1/src/nnapi_delegate.cpp
  runtime/libs/tflite/port/1.13.1/src/nnapi_delegate_ex_AddOpsAndParams_lambda.inc
  runtime/libs/tflite/src/RandomTestRunner.cpp
Labels: PR/ready for review
