Repository Samsung/ONE, pull requests merged in 2021-06, with the labels that each got.

#6908 [debian] Override dh_builddeb
  debian/rules
Labels: PR/ready for review

#6907 [infra] Update docker_build_nncc script
  infra/scripts/docker_build_nncc.sh
Labels: PR/ready for review

#6915 [one-cmds] Add comments
  compiler/one-cmds/one-prepare-venv
Labels: PR/ready for review

#6914 [one-cmds] Remove python symbolic link
  compiler/one-cmds/one-prepare-venv
Labels: PR/ready for review

#6951 [Infra/docker] Upgrade git version
  infra/docker/bionic/Dockerfile
Labels: PR/ready for review

#6937 [onert] Add mutex for multi-threading
  compute/cker/include/cker/operation/optimized/Conv.h
Labels: PR/ready for review

#6942 [onert] Reallocate backends to operations at runtime
  runtime/onert/api/include/nnfw_experimental.h
  runtime/onert/api/src/nnfw_api.cc
  runtime/onert/api/src/nnfw_api_internal.cc
  runtime/onert/api/src/nnfw_api_internal.h
  runtime/onert/core/include/compiler/Compiler.h
  runtime/onert/core/src/compiler/Compiler.cc
Labels: PR/ready for review

#6973 [onert] Multiple Executions for Pipeline
  runtime/onert/api/include/nnfw_experimental.h
  runtime/onert/api/src/nnfw_api.cc
  runtime/onert/api/src/nnfw_api_internal.cc
  runtime/onert/api/src/nnfw_api_internal.h
  runtime/onert/core/include/compiler/Compiler.h
  runtime/onert/core/include/compiler/LoweredGraph.h
  runtime/onert/core/include/exec/Execution.h
  runtime/onert/core/include/exec/IExecutor.h
  runtime/onert/core/include/ir/Graph.h
  runtime/onert/core/include/ir/OperandIndexSequence.h
  runtime/onert/core/src/compiler/Compiler.cc
  runtime/onert/core/src/compiler/LoweredGraph.cc
  runtime/onert/core/src/exec/ExecutorBase.cc
  runtime/onert/core/src/exec/ExecutorBase.h
  runtime/onert/core/src/exec/LinearExecutor.cc
  runtime/onert/core/src/interp/InterpExecutor.h
  runtime/onert/frontend/base_loader/include/base_loader.h
  runtime/onert/frontend/circle/src/circle_loader.cc
  runtime/onert/frontend/tflite/src/tflite_loader.cc
  tests/nnfw_api/CMakeLists.txt
  tests/nnfw_api/src/NNPackages.cc
  tests/nnfw_api/src/NNPackages.h
  tests/nnfw_api/src/ValidationTestPipelineSession.cc
  tests/nnfw_api/src/fixtures.h
Labels: PR/ready for review

#7007 [circle-quantizer] Use the same scales for input/output of StridedSlice
  compiler/luci/pass/src/QuantizeWithMinMaxPass.cpp
  compiler/luci/pass/src/VerifyQuantizedNodeS16Type.h
  compiler/luci/pass/src/VerifyQuantizedNodeU8Type.h
Labels: area/quant

#7018 [record-minmax] Fix boundary percentile cases
  compiler/record-minmax/include/RecordFunction.h
Labels: PR/ready for review, area/quant

#7006 [docker] Update focal Dockerfile
  infra/docker/focal/Dockerfile
Labels: PR/ready for review

#7050 [infra] Add ubuntu codename info
  infra/scripts/docker_build_nncc.sh
Labels: PR/ready for review

#7052 [infra] Add dh-python to focal Dockerfile
  infra/docker/focal/Dockerfile
Labels: PR/ready for review

#7051 Add the test case for pipeline
  runtime/onert/api/src/nnfw_api_internal.cc
  tests/nnfw_api/src/ValidationTestPipelineSession.cc
Labels: PR/ready for review

#7053 [debian] Add ONE compiler manpages
  debian/docs/one-build.1
  debian/docs/one-codegen.1
  debian/docs/one-import-bcq.1
  debian/docs/one-import-onnx.1
  debian/docs/one-import-tf.1
  debian/docs/one-import-tflite.1
  debian/docs/one-optimize.1
  debian/docs/one-pack.1
  debian/docs/one-quantize.1
  debian/one-compiler.manpages
Labels: PR/ready for review

#7063 [luci] Set minimum value of scale for Q16
  compiler/luci/pass/src/QuantizationUtils.cpp
Labels: area/quant

#7064 [model_partition] Add scripts for runtime-driven, heuristic-based model partitioning
  tools/model_partition_tool/Graph.py
  tools/model_partition_tool/README.md
  tools/model_partition_tool/graph_analysis.py
  tools/model_partition_tool/runtime_stats.py
  tools/model_partition_tool/test_partition.py
Labels: PR/ready for review
