Repository Samsung/ONE, pull requests merged in 2021-12, with the labels that each got.

#8059 [onert/gpu-cl] Revise ClTensorBuilder
  runtime/onert/backend/gpu_cl/TensorBuilder.cc
  runtime/onert/backend/gpu_cl/TensorBuilder.h
Labels: PR/ready for review

#8067 [one-cmds] Support TF-style MaxPool Quantization
  compiler/one-cmds/one-quantize
Labels: area/quant

#8080 [onert/gpu-cl] Remove deprecated code
  runtime/onert/backend/gpu_cl/ClTensorManager.h
  runtime/onert/backend/gpu_cl/TensorBuilder.cc
Labels: PR/ready for review

#8081 [onert/gpu-cl] Revise ClTensorRegistry
  runtime/onert/backend/gpu_cl/Backend.h
  runtime/onert/backend/gpu_cl/ClConstantInitializer.h
  runtime/onert/backend/gpu_cl/KernelGenerator.cc
  runtime/onert/backend/gpu_cl/KernelGenerator.h
  runtime/onert/backend/gpu_cl/TensorBuilder.cc
  runtime/onert/backend/gpu_cl/TensorRegistry.h
Labels: PR/ready for review

#8087 [onert/gpu-cl] Rename ClTensorManager
  runtime/onert/backend/gpu_cl/Backend.h
  runtime/onert/backend/gpu_cl/KernelGenerator.cc
  runtime/onert/backend/gpu_cl/KernelGenerator.h
  runtime/onert/backend/gpu_cl/TensorBuilder.cc
  runtime/onert/backend/gpu_cl/TensorBuilder.h
  runtime/onert/backend/gpu_cl/TensorManager.cc
  runtime/onert/backend/gpu_cl/TensorManager.h
  runtime/onert/backend/gpu_cl/TensorRegistry.h
Labels: PR/ready for review

#8111 [luci-interpreter] Add negative test for OneHot kernel
  compiler/luci-interpreter/src/kernels/OneHot.test.cpp
Labels: PR/ready for review

#8108 [luci-interpreter] Enable OneHot kernel
  compiler/luci-interpreter/pal/linux/KernelsToBuild.lst
  compiler/luci-interpreter/src/loader/KernelBuilder.test.cpp
  compiler/luci-interpreter/src/loader/nodes/OneHot.cpp
Labels: PR/ready for review

#8132 [luci] Support copy quantparam pass
  compiler/luci/pass/include/luci/CircleOptimizer.h
  compiler/luci/pass/include/luci/Pass/CopyQuantParamPass.h
  compiler/luci/pass/src/CircleOptimizer.cpp
  compiler/luci/pass/src/CopyQuantParamPass.cpp
Labels: area/quant

#8134 [circle-quantizer] Support copy qparam option
  compiler/circle-quantizer/src/CircleQuantizer.cpp
Labels: area/quant

#8145 [one-cmds] Support copy qparam in one-quantize
  compiler/one-cmds/one-quantize
  compiler/one-cmds/utils.py
Labels: area/quant

#8135 [tools] Revise install-rootfs script
  tools/cross/install_rootfs.sh
Labels: PR/ready for review

#8149 [one-cmd] Use latest pip and setuptools
  compiler/one-cmds/one-prepare-venv
Labels: PR/ready for review

#8172 [record-minmax] Add integer generator of random data
  compiler/record-minmax/src/RecordMinMax.cpp
Labels: PR/ready for review

#8173 [record-minmax] Skip minmax recording for integer tensors
  compiler/record-minmax/src/MinMaxObserver.cpp
Labels: PR/ready for review

#8175 [record-minmax] Allow random integer inputs
  compiler/record-minmax/src/RecordMinMax.cpp
Labels: PR/ready for review

#8174 [luci/pass] Enable OneHot quantization
  compiler/luci/pass/src/QuantizeWithMinMaxPass.cpp
  compiler/luci/pass/src/QuantizedModelVerifier.test.cpp
  compiler/luci/pass/src/VerifyQuantizedNodeChannelWiseGranularity.h
  compiler/luci/pass/src/VerifyQuantizedNodeLayerWiseGranularity.h
  compiler/luci/pass/src/VerifyQuantizedNodeS16Type.h
  compiler/luci/pass/src/VerifyQuantizedNodeU8Type.h
Labels: PR/ready for review

#8178 [luci/pass] Fix typos in error message and comment
  compiler/luci/pass/src/QuantizeWithMinMaxPass.cpp
Labels: PR/ready for review

#8183 [record-minmax] Remove redundant ArgMax case
  compiler/record-minmax/src/MinMaxObserver.cpp
Labels: PR/ready for review

#8224 [onert/nnpackage_run] Fix parameter help message for nnpackage_run
  tests/tools/nnpackage_run/src/args.cc
Labels: PR/ready for review

#8221 [infra] Speed up file search in format
  infra/command/format
Labels: PR/ready for review

#8214 [tflitefile_tool] Use workaround for EndVector
  tools/tflitefile_tool/select_operator.py
Labels: PR/ready for review

#8204 [tflite2circle] support SVDF for circle conversion
  compiler/tflite2circle/src/BuildBuiltinOptions.h
  compiler/tflite2circle/src/BuildBuiltinOptions/SVDFOptions.cpp
  compiler/tflite2circle/src/BuildBuiltinOptions/SVDFOptions.h
  compiler/tflite2circle/src/TFLBuiltinOptions.lst
Labels: PR/NO MERGE
