Repository Samsung/ONE, pull requests merged in 2021-01, with the labels that each got.

#5531 [luci] Fix wrong dimension copy in CircleShapeInferenceHelper
  compiler/luci/service/src/CircleShapeInferenceHelper.cpp
Labels: trivial

#5521 [luci] Print unknown dimension as question mark
  compiler/luci/service/src/CircleShapeInference.cpp
  compiler/luci/service/src/CircleShapeInferenceRule.cpp
  compiler/luci/service/src/Validate.cpp
Labels: trivial

#5542 [onert] Support quantized Pad operation
  runtime/onert/backend/cpu/ops/PadLayer.cc
  tests/nnfw_api/src/one_op_tests/Pad.cc
Labels: PR/ready for review

#5546 [nnpackage] Add NNPackage example
  nnpackage/examples/README.md
  nnpackage/examples/v1.0.0/add/add.tflite
  nnpackage/examples/v1.0.0/add/metadata/MANIFEST
  nnpackage/examples/v1.0.0/add_invalid_manifest/add.tflite
  nnpackage/examples/v1.0.0/add_invalid_manifest/metadata/MANIFEST
  nnpackage/examples/v1.0.0/if_dynamic/if_dynamic.tflite
  nnpackage/examples/v1.0.0/if_dynamic/metadata/MANIFEST
  nnpackage/examples/v1.0.0/if_dynamic/metadata/tc/expected.h5
  nnpackage/examples/v1.0.0/if_dynamic/metadata/tc/input.h5
  nnpackage/examples/v1.0.0/while_dynamic/metadata/MANIFEST
  nnpackage/examples/v1.0.0/while_dynamic/metadata/tc/expected.h5
  nnpackage/examples/v1.0.0/while_dynamic/metadata/tc/input.h5
  nnpackage/examples/v1.0.0/while_dynamic/while_dynamic.tflite
  nnpackage/examples/v1.1.0/one_op_in_tflite/add.tflite
  nnpackage/examples/v1.1.0/one_op_in_tflite/metadata/MANIFEST
  nnpackage/examples/v1.1.0/one_op_in_tflite/metadata/config.cfg
  tests/nnfw_api/CMakeLists.txt
Labels: PR/ready for review

#5549 [infra] Remove nnpackage download config script
  infra/scripts/tizen_xu4_test.sh
  tests/scripts/CMakeLists.txt
  tests/scripts/command/prepare-model
  tests/scripts/models/nnfw_api_gtest/add/config.sh
  tests/scripts/models/nnfw_api_gtest/add_invalid_manifest/config.sh
  tests/scripts/models/nnfw_api_gtest/add_no_manifest/config.sh
  tests/scripts/models/nnfw_api_gtest/if_dynamic/config.sh
  tests/scripts/models/nnfw_api_gtest/while_dynamic/config.sh
Labels: PR/ready for review

#5507 [luci] Change candidates for circle type inference pass
  compiler/luci/pass/src/CircleTypeInferencePass.cpp
Labels: PR/ready for review

#5560 [one-cmds] Update one-cmds' optimization option
  compiler/one-cmds/one-optimize
  compiler/one-cmds/utils.py
Labels: PR/ready for review

#5550 [luci-interpreter] Remove overflow possibility
  compiler/luci-interpreter/src/kernels/Prelu.cpp
Labels: trivial

#5555 [onert/cpu] Introduce getBuffer function
  compute/cker/include/cker/operation/Fill.h
  runtime/onert/backend/cpu/ops/AddNLayer.cc
  runtime/onert/backend/cpu/ops/ArgMinMaxLayer.cc
  runtime/onert/backend/cpu/ops/BatchMatMulLayer.cc
  runtime/onert/backend/cpu/ops/BatchToSpaceNDLayer.cc
  runtime/onert/backend/cpu/ops/BinaryArithmeticLayer.cc
  runtime/onert/backend/cpu/ops/BroadcastToLayer.cc
  runtime/onert/backend/cpu/ops/CompareLayer.cc
  runtime/onert/backend/cpu/ops/ConcatLayer.cc
  runtime/onert/backend/cpu/ops/ConvolutionLayer.cc
  runtime/onert/backend/cpu/ops/DepthToSpaceLayer.cc
  runtime/onert/backend/cpu/ops/DepthwiseConvolutionLayer.cc
  runtime/onert/backend/cpu/ops/EinsumLayer.cc
  runtime/onert/backend/cpu/ops/ElementwiseActivationLayer.cc
  runtime/onert/backend/cpu/ops/ElementwiseBinaryLayer.cc
  runtime/onert/backend/cpu/ops/ElementwiseUnaryLayer.cc
  runtime/onert/backend/cpu/ops/FillLayer.cc
  runtime/onert/backend/cpu/ops/FullyConnectedLayer.cc
  runtime/onert/backend/cpu/ops/FusedBatchNormLayer.cc
  runtime/onert/backend/cpu/ops/GatherLayer.cc
  runtime/onert/backend/cpu/ops/L2NormLayer.cc
  runtime/onert/backend/cpu/ops/LSTMLayer.cc
  runtime/onert/backend/cpu/ops/LogSoftMaxLayer.cc
  runtime/onert/backend/cpu/ops/MatrixBandPartLayer.cc
  runtime/onert/backend/cpu/ops/MeanLayer.cc
  runtime/onert/backend/cpu/ops/OneHotLayer.cc
  runtime/onert/backend/cpu/ops/OperationUtils.cc
  runtime/onert/backend/cpu/ops/OperationUtils.h
  runtime/onert/backend/cpu/ops/PackLayer.cc
  runtime/onert/backend/cpu/ops/PadLayer.cc
  runtime/onert/backend/cpu/ops/PoolLayer.cc
  runtime/onert/backend/cpu/ops/PowLayer.cc
  runtime/onert/backend/cpu/ops/QuantizeLayer.cc
  runtime/onert/backend/cpu/ops/RangeLayer.cc
  runtime/onert/backend/cpu/ops/RankLayer.cc
  runtime/onert/backend/cpu/ops/ReduceLayer.cc
  runtime/onert/backend/cpu/ops/ResizeBilinearLayer.cc
  runtime/onert/backend/cpu/ops/ReverseLayer.cc
  runtime/onert/backend/cpu/ops/SelectLayer.cc
  runtime/onert/backend/cpu/ops/ShapeLayer.cc
  runtime/onert/backend/cpu/ops/SliceLayer.cc
  runtime/onert/backend/cpu/ops/SoftMaxLayer.cc
  runtime/onert/backend/cpu/ops/SpaceToBatchNDLayer.cc
  runtime/onert/backend/cpu/ops/SpaceToDepthLayer.cc
  runtime/onert/backend/cpu/ops/SplitLayer.cc
  runtime/onert/backend/cpu/ops/SplitVLayer.cc
  runtime/onert/backend/cpu/ops/SquaredDiffLayer.cc
  runtime/onert/backend/cpu/ops/StatelessRandomUniformLayer.cc
  runtime/onert/backend/cpu/ops/StridedSliceLayer.cc
  runtime/onert/backend/cpu/ops/TileLayer.cc
  runtime/onert/backend/cpu/ops/TransposeLayer.cc
  runtime/onert/backend/cpu/ops/UnpackLayer.cc
Labels: PR/ready for review

#5571 [onert/cpu] Rename getShape function
  runtime/onert/backend/cpu/ops/AddNLayer.cc
  runtime/onert/backend/cpu/ops/ArgMinMaxLayer.cc
  runtime/onert/backend/cpu/ops/BatchMatMulLayer.cc
  runtime/onert/backend/cpu/ops/BatchToSpaceNDLayer.cc
  runtime/onert/backend/cpu/ops/BinaryArithmeticLayer.cc
  runtime/onert/backend/cpu/ops/BroadcastToLayer.cc
  runtime/onert/backend/cpu/ops/ConcatLayer.cc
  runtime/onert/backend/cpu/ops/ConvolutionLayer.cc
  runtime/onert/backend/cpu/ops/DepthToSpaceLayer.cc
  runtime/onert/backend/cpu/ops/DepthwiseConvolutionLayer.cc
  runtime/onert/backend/cpu/ops/EinsumLayer.cc
  runtime/onert/backend/cpu/ops/ElementwiseActivationLayer.cc
  runtime/onert/backend/cpu/ops/ElementwiseBinaryLayer.cc
  runtime/onert/backend/cpu/ops/ElementwiseUnaryLayer.cc
  runtime/onert/backend/cpu/ops/FillLayer.cc
  runtime/onert/backend/cpu/ops/FullyConnectedLayer.cc
  runtime/onert/backend/cpu/ops/FusedBatchNormLayer.cc
  runtime/onert/backend/cpu/ops/GatherLayer.cc
  runtime/onert/backend/cpu/ops/L2NormLayer.cc
  runtime/onert/backend/cpu/ops/LogSoftMaxLayer.cc
  runtime/onert/backend/cpu/ops/MatrixBandPartLayer.cc
  runtime/onert/backend/cpu/ops/MeanLayer.cc
  runtime/onert/backend/cpu/ops/OneHotLayer.cc
  runtime/onert/backend/cpu/ops/OperationUtils.h
  runtime/onert/backend/cpu/ops/PackLayer.cc
  runtime/onert/backend/cpu/ops/PadLayer.cc
  runtime/onert/backend/cpu/ops/PoolLayer.cc
  runtime/onert/backend/cpu/ops/PowLayer.cc
  runtime/onert/backend/cpu/ops/QuantizeLayer.cc
  runtime/onert/backend/cpu/ops/ReduceLayer.cc
  runtime/onert/backend/cpu/ops/ResizeBilinearLayer.cc
  runtime/onert/backend/cpu/ops/ReverseLayer.cc
  runtime/onert/backend/cpu/ops/SelectLayer.cc
  runtime/onert/backend/cpu/ops/SoftMaxLayer.cc
  runtime/onert/backend/cpu/ops/SpaceToBatchNDLayer.cc
  runtime/onert/backend/cpu/ops/SpaceToDepthLayer.cc
  runtime/onert/backend/cpu/ops/SplitLayer.cc
  runtime/onert/backend/cpu/ops/SplitVLayer.cc
  runtime/onert/backend/cpu/ops/SquaredDiffLayer.cc
  runtime/onert/backend/cpu/ops/StatelessRandomUniformLayer.cc
  runtime/onert/backend/cpu/ops/StridedSliceLayer.cc
  runtime/onert/backend/cpu/ops/TileLayer.cc
  runtime/onert/backend/cpu/ops/TransposeLayer.cc
  runtime/onert/backend/cpu/ops/UnpackLayer.cc
Labels: PR/ready for review

#5585 [onert] Fix StatelessRandomUniform data type
  compute/cker/include/cker/operation/StatelessRandomUniform.h
  runtime/onert/backend/cpu/ops/StatelessRandomUniformLayer.cc
  runtime/onert/core/src/ir/OperationValidator.cc
  runtime/onert/core/src/ir/OperationValidator.h
Labels: PR/ready for review

#5588 [doc] Update runtime supported operation
  docs/runtime/supported-operations-backend.md
Labels: PR/ready for review

#5589 [onert] Fix acl-neon backend softmax
  runtime/onert/backend/acl_neon/KernelGenerator.cc
  tests/nnfw_api/src/one_op_tests/Softmax.cc
Labels: PR/ready for review

#5593 [onert/cpu] Support AveragePool2D int8 kernel
  compute/cker/include/cker/operation/AveragePool.h
  runtime/onert/backend/cpu/ops/PoolLayer.cc
  tests/nnfw_api/src/one_op_tests/AveragePool2D.cc
Labels: PR/ready for review

#5597 [tool/stab] Introduce static backend scheduler
  tools/stab/README.md
  tools/stab/backend_profiler.py
  tools/stab/backend_scheduler.py
  tools/stab/nnpkg_helper.py
  tools/stab/op_list.txt
  tools/stab/op_list_parser.py
  tools/stab/remote.py
  tools/stab/stab.py
Labels: PR/ready for review

#5605 [common-artifacts] Update comments in exclude list
  compiler/common-artifacts/exclude.lst
Labels: trivial

#5611 [common-artifacts] Exclude dynamic recipes
  compiler/common-artifacts/exclude.lst
Labels: trivial

#5609 [nnfwapi] Test: fix Add model test bug
  tests/nnfw_api/src/fixtures.h
Labels: bug

#5659 [luci] Add CircleFakeQuant to comment list
  compiler/luci/service/include/luci/Service/CircleShapeInference.h
  compiler/luci/service/include/luci/Service/CircleTypeInference.h
Labels: trivial

#5684 [TensorFlowPythonExamples] Add minimum-maximum small network
  res/TensorFlowPythonModels/examples/minimum-maximum/__init__.py
Labels: PR/ready for review

#5685 [luci] Reorder by alphabet order comments
  compiler/luci/service/include/luci/Service/CircleShapeInference.h
Labels: trivial

#5689 [luci] Fix type of input shape in PassTestGraphs.h
  compiler/luci/pass/src/PassTestGraphs.h
Labels: trivial

#5691 [tflchef] Update Maximum, Minimum filler
  compiler/tflchef/tflite/src/Op/Maximum.cpp
  compiler/tflchef/tflite/src/Op/Minimum.cpp
Labels: PR/ready for review

#5692 [TensorFlowLiteRecipes] Add Net_Maximum_Minimum_000 recipe
  res/TensorFlowLiteRecipes/Net_Maximum_Minimum_000/test.recipe
  res/TensorFlowLiteRecipes/Net_Maximum_Minimum_000/test.rule
Labels: PR/ready for review

#5693 [TensorFlowPythonModels] change driver mode bits
  res/TensorFlowPythonModels/tfpem.py
Labels: PR/ready for review

#5712 [luci] Introudce NodeFiller class
  compiler/luci/pass/src/helpers/NodeFiller.cpp
  compiler/luci/pass/src/helpers/NodeFiller.h
Labels: PR/ready for review

#5720 [luci] Add NodeFiller test
  compiler/luci/pass/src/helpers/NodeFiller.test.cpp
Labels: PR/ready for review

#5719 [luci] Revise FuseInstanceNormPass
  compiler/luci/pass/src/FuseInstanceNormPass.cpp
Labels: PR/ready for review

#5718 [luci] Add ResolveCustomOpBatchMatMulPass test
  compiler/luci/pass/src/ResolveCustomOpBatchMatMulPass.test.cpp
Labels: PR/ready for review

#5727 [luci] Fix invalid type inference test code
  compiler/luci/service/src/CircleTypeInferenceRule.test.cpp
Labels: trivial

#5726 [luci] Remove unused headers in ResolveCustomOpMatMulPass
  compiler/luci/pass/src/ResolveCustomOpMatMulPass.cpp
Labels: trivial

#5731 [luci] Set ShapeStatus of CircleConst in ResolveCustomOpMatMulPass
  compiler/luci/pass/src/ResolveCustomOpMatMulPass.cpp
Labels: trivial

#5729 [luci] Reorder incorrect test code
  compiler/luci/pass/src/ConvertNCHWToNHWCPass.test.cpp
Labels: trivial

#5732 [onert/test] Change TFLite default no. of threads setting
  tests/tools/tflite_loader/src/tflite_loader.cc
  tests/tools/tflite_run/src/tflite_run.cc
Labels: PR/ready for review

#5738 [luci] Reorder incorrect test code
  compiler/luci/pass/src/ConvertNCHWToNHWCPass.test.cpp
Labels: trivial

#5739 [luci] Remove duplicated assert
  compiler/luci/service/src/CircleShapeInferenceRule.cpp
Labels: trivial

#5734 [luci] Substitute shape_known/dtype_known functions to luci
  compiler/luci/service/src/CircleShapeInference.cpp
  compiler/luci/service/src/CircleTypeInference.cpp
Labels: PR/ready for review

#5735 [luci] Introduce TypeMapper
  compiler/luci/pass/src/helpers/TypeMapper.cpp
  compiler/luci/pass/src/helpers/TypeMapper.h
  compiler/luci/pass/src/helpers/TypeMapper.test.cpp
Labels: PR/ready for review

#5699 [luci] Introduce TransformMinMaxToRelu6Pass
  compiler/luci/pass/include/luci/CircleOptimizer.h
  compiler/luci/pass/include/luci/Pass/TransformMinMaxToRelu6Pass.h
  compiler/luci/pass/src/CircleOptimizer.cpp
  compiler/luci/pass/src/TransformMinMaxToRelu6Pass.cpp
  compiler/luci/pass/src/TransformMinMaxToRelu6Pass.test.cpp
Labels: PR/ready for review

#5751 [circle2circle] Introduce transform_min_max_to_relu6 option
  compiler/circle2circle/src/Circle2Circle.cpp
Labels: PR/ready for review

#5754 [circle2circle-dredd-recipe-test] Add transform_min_max_to_relu6 test
  compiler/circle2circle-dredd-recipe-test/test.lst
Labels: PR/ready for review

#5755 [one-cmds] Introduce transform_min_max_to_relu6 option
  compiler/one-cmds/how-to-use-one-commands.txt
  compiler/one-cmds/one-optimize
  compiler/one-cmds/utils.py
Labels: PR/ready for review

#5701 [luci/IR] Add BidirectionalSequenceLSTM op
  compiler/luci/lang/include/luci/IR/CircleNodes.h
  compiler/luci/lang/include/luci/IR/CircleNodes.lst
  compiler/luci/lang/include/luci/IR/Nodes/CircleBidirectionalSequenceLSTM.h
  compiler/luci/lang/include/luci/IR/Nodes/CircleBidirectionalSequenceLSTMOut.h
  compiler/luci/lang/src/Nodes/CircleBidrectionalSequenceLSTM.test.cpp
Labels: PR/ready for review

#5758 [luci] Rename RemoveRedundantTranspose files
  compiler/luci/pass/src/RemoveRedundantTransposePass.cpp
  compiler/luci/pass/src/RemoveRedundantTransposePass.test.cpp
Labels: trivial

#5789 [tools/pareto_profiler] Add preliminary scripts for on-device pareto estimation
  tools/pareto_profiler/README.md
  tools/pareto_profiler/estimator/brute_force_profiler.py
  tools/pareto_profiler/estimator/pareto.py
  tools/pareto_profiler/estimator/profile_args.py
  tools/pareto_profiler/estimator/random_sampler.py
  tools/pareto_profiler/estimator/runner.py
  tools/pareto_profiler/estimator/utils.py
  tools/pareto_profiler/generator/gen_oplist.py
  tools/pareto_profiler/generator/operations_map.json
Labels: PR/ready for review

#5806 [luci] Remove clang-format off
  compiler/luci/pass/src/CircleShapeInferencePass.cpp
  compiler/luci/pass/src/CircleTypeInferencePass.cpp
Labels: trivial

#5825 [luci] Fix indentation in QuantizeWithMinMaxPass
  compiler/luci/pass/src/QuantizeWithMinMaxPass.cpp
Labels: trivial

#5819 [tflchef] Introduce BroadcastTo op
  compiler/tflchef/core/src/CustomOp/BroadcastTo.cpp
  compiler/tflchef/core/src/CustomOp/BroadcastTo.h
  compiler/tflchef/core/src/OpChef.def
  compiler/tflchef/core/src/OpChefs.h
Labels: PR/ready for review

#5820 [common-artifcats] add network having BroadcastTo op to exclude list
  compiler/common-artifacts/exclude.lst
Labels: PR/ready for review

#5842 [tools/pareto_profiler] Implement HLPS algorithm for pareto estimation
  tools/pareto_profiler/estimator/Hlps.py
  tools/pareto_profiler/estimator/hlps_sampler.py
  tools/pareto_profiler/estimator/pareto.py
  tools/pareto_profiler/estimator/profile_args.py
  tools/pareto_profiler/estimator/runner.py
Labels: PR/ready for review

#5864 [TensorFlowLiteRecipes] add Net_TConv_BN_002
  res/TensorFlowLiteRecipes/Net_TConv_BN_002/test.recipe
  res/TensorFlowLiteRecipes/Net_TConv_BN_002/test.rule
Labels: PR/ready for review

#5865 [circle2circle-dredd-recipe-test] add Net_TConv_BN_002
  compiler/circle2circle-dredd-recipe-test/test.lst
Labels: PR/ready for review

#5866 [luci-pass-value-test] add Net_TConv_BN_002
  compiler/luci-pass-value-test/test.lst
Labels: PR/ready for review
