Repository Samsung/ONE, pull requests merged in 2021-04, with the labels that each got.

#6376 [onert/api] Revise CustomKernel
  runtime/onert/api/src/CustomKernel.cc
  runtime/onert/api/src/CustomKernel.h
  runtime/onert/api/src/CustomKernelRegistry.cc
  runtime/onert/api/src/CustomKernelRegistry.h
  runtime/onert/api/src/nnfw_api_internal.cc
  runtime/onert/api/src/nnfw_api_internal.h
Labels: PR/ready for review

#6404 [one-cmds] missing codes that return exit code
  compiler/one-cmds/one-codegen
  compiler/one-cmds/one-import-tflite
Labels: PR/ready for review

#6408 [luci] Tidy Logistic test in QuantizedModelVerifier.test.cpp
  compiler/luci/pass/src/QuantizedModelVerifier.test.cpp
Labels: trivial

#6411 [circle-quantizer] Support quantization of softmax
  compiler/luci/pass/src/QuantizeWithMinMaxPass.cpp
  compiler/luci/pass/src/QuantizedModelVerifier.test.cpp
  compiler/luci/pass/src/VerifyQuantizedNodeChannelWiseGranularity.h
  compiler/luci/pass/src/VerifyQuantizedNodeLayerWiseGranularity.h
  compiler/luci/pass/src/VerifyQuantizedNodeS16Type.h
  compiler/luci/pass/src/VerifyQuantizedNodeU8Type.h
Labels: area/quant

#6416 [luci] Support quantization of tanh
  compiler/luci/pass/src/QuantizeWithMinMaxPass.cpp
  compiler/luci/pass/src/QuantizedModelVerifier.test.cpp
  compiler/luci/pass/src/VerifyQuantizedNodeChannelWiseGranularity.h
  compiler/luci/pass/src/VerifyQuantizedNodeLayerWiseGranularity.h
  compiler/luci/pass/src/VerifyQuantizedNodeS16Type.h
  compiler/luci/pass/src/VerifyQuantizedNodeU8Type.h
Labels: area/quant

#6430 [arser] remove unnamed namespace
  compiler/arser/include/arser/arser.h
Labels: PR/ready for review

#6440 [luci] Verify quantization of transpose
  compiler/luci/pass/src/QuantizedModelVerifier.test.cpp
  compiler/luci/pass/src/VerifyQuantizedNodeChannelWiseGranularity.h
  compiler/luci/pass/src/VerifyQuantizedNodeLayerWiseGranularity.h
  compiler/luci/pass/src/VerifyQuantizedNodeS16Type.h
  compiler/luci/pass/src/VerifyQuantizedNodeU8Type.h
Labels: area/quant

#6445 [preset] Add 20210406 preset
  infra/packaging/preset/20210406
  infra/packaging/preset/20210406_windows
Labels: PR/ready for review

#6442 [luci] Verify quantization of reshape op
  compiler/luci/pass/src/QuantizedModelVerifier.test.cpp
  compiler/luci/pass/src/VerifyQuantizedNodeChannelWiseGranularity.h
  compiler/luci/pass/src/VerifyQuantizedNodeLayerWiseGranularity.h
  compiler/luci/pass/src/VerifyQuantizedNodeS16Type.h
  compiler/luci/pass/src/VerifyQuantizedNodeU8Type.h
Labels: area/quant

#6449 [luci] Tidy quantized model verifier
  compiler/luci/pass/src/QuantizedModelVerifier.test.cpp
Labels: area/quant

#6450 [record-minmax] Do not record min/max of bool type
  compiler/record-minmax/src/MinMaxObserver.cpp
Labels: area/quant

#6453 [packaging] Add tf2nnpkg.20210406
  infra/packaging/res/tf2nnpkg.20210406
Labels: PR/ready for review

#6487 [luci] Support quantization of greater
  compiler/luci/pass/src/QuantizeWithMinMaxPass.cpp
  compiler/luci/pass/src/QuantizedModelVerifier.test.cpp
  compiler/luci/pass/src/VerifyQuantizedNodeChannelWiseGranularity.h
  compiler/luci/pass/src/VerifyQuantizedNodeLayerWiseGranularity.h
  compiler/luci/pass/src/VerifyQuantizedNodeS16Type.h
  compiler/luci/pass/src/VerifyQuantizedNodeU8Type.h
Labels: area/quant

#6488 [preset] Update default preset
  infra/packaging/build
Labels: PR/ready for review

#6490 [luci] Support quantization of NotEqual
  compiler/luci/pass/src/QuantizedModelVerifier.test.cpp
  compiler/luci/pass/src/VerifyQuantizedNodeChannelWiseGranularity.h
  compiler/luci/pass/src/VerifyQuantizedNodeLayerWiseGranularity.h
  compiler/luci/pass/src/VerifyQuantizedNodeS16Type.h
  compiler/luci/pass/src/VerifyQuantizedNodeU8Type.h
Labels: area/quant

#6492 [luci] Support quantization of GreaterEqual
  compiler/luci/pass/src/QuantizedModelVerifier.test.cpp
  compiler/luci/pass/src/VerifyQuantizedNodeChannelWiseGranularity.h
  compiler/luci/pass/src/VerifyQuantizedNodeLayerWiseGranularity.h
  compiler/luci/pass/src/VerifyQuantizedNodeS16Type.h
  compiler/luci/pass/src/VerifyQuantizedNodeU8Type.h
Labels: area/quant

#6498 [luci] Revise non-bool type check
  compiler/luci/pass/src/QuantizeWithMinMaxPass.cpp
Labels: area/quant

#6502 [common-artifacts] Add path options to TestDataGenerator
  compiler/common-artifacts/CMakeLists.txt
  compiler/common-artifacts/src/TestDataGenerator.cpp
Labels: PR/ready for review

#6495 [luci] Support quantization of LogicalOr
  compiler/luci/pass/src/QuantizeWithMinMaxPass.cpp
  compiler/luci/pass/src/QuantizedModelVerifier.test.cpp
  compiler/luci/pass/src/VerifyQuantizedNodeChannelWiseGranularity.h
  compiler/luci/pass/src/VerifyQuantizedNodeLayerWiseGranularity.h
  compiler/luci/pass/src/VerifyQuantizedNodeS16Type.h
  compiler/luci/pass/src/VerifyQuantizedNodeU8Type.h
Labels: area/quant

#6515 [common-artifacts] Prevent cmake from re-running custom command
  compiler/common-artifacts/CMakeLists.txt
Labels: PR/ready for review

#6514 [luci] Verify quantization of Pad
  compiler/luci/pass/src/QuantizedModelVerifier.test.cpp
  compiler/luci/pass/src/VerifyQuantizedNodeChannelWiseGranularity.h
  compiler/luci/pass/src/VerifyQuantizedNodeLayerWiseGranularity.h
  compiler/luci/pass/src/VerifyQuantizedNodeS16Type.h
  compiler/luci/pass/src/VerifyQuantizedNodeU8Type.h
Labels: area/quant

#6520 [one-cmds] Make test script return proper exit code
  compiler/one-cmds/tests/CMakeLists.txt
Labels: PR/ready for review

#6535 [arser] Support short option
  compiler/arser/include/arser/arser.h
  compiler/arser/tests/arser.test.cpp
Labels: PR/ready for review

#6511 [luci] Verify quantization of Concat
  compiler/luci/pass/src/QuantizedModelVerifier.test.cpp
  compiler/luci/pass/src/VerifyQuantizedNodeChannelWiseGranularity.h
  compiler/luci/pass/src/VerifyQuantizedNodeLayerWiseGranularity.h
  compiler/luci/pass/src/VerifyQuantizedNodeS16Type.h
  compiler/luci/pass/src/VerifyQuantizedNodeU8Type.h
Labels: area/quant

#6567 [record-minmax] Skip nan values during calibration
  compiler/record-minmax/src/MinMaxObserver.cpp
Labels: area/quant

#6568 [record-minmax-test] Generate random boolean input
  compiler/record-minmax-conversion-test/gen_h5_random_inputs.py
Labels: area/quant

#6569 [record-minmax] Skip recording bool type tensor
  compiler/record-minmax/src/MinMaxObserver.cpp
Labels: area/quant

#6572 [arser] Apply short option
  compiler/arser/include/arser/arser.h
Labels: PR/ready for review

#6573 [luci] Add missing nnas_find_package
  compiler/luci/testhelper/CMakeLists.txt
Labels: PR/ready for review

#6577 [souschef] Introduce unified gaussian generator
  compiler/souschef/src/Gaussian.cpp
Labels: PR/ready for review

#6578 [souschef] Use unified gaussian generator
  compiler/souschef/src/Gaussian.cpp
Labels: PR/ready for review

#6580 [vconone] Update copyright notice
  compiler/vconone/src/version.cpp
Labels: PR/ready for review

#6582 [record-minmax] Accept bool type input from h5
  compiler/record-minmax/src/HDF5Importer.cpp
Labels: area/quant

#6583 [record-minmax] Generate random bool input data
  compiler/record-minmax/src/RecordMinMax.cpp
Labels: area/quant

#6545 [luci] Verify quantization of Sqrt
  compiler/luci/pass/src/QuantizeWithMinMaxPass.cpp
  compiler/luci/pass/src/QuantizedModelVerifier.test.cpp
  compiler/luci/pass/src/VerifyQuantizedNodeChannelWiseGranularity.h
  compiler/luci/pass/src/VerifyQuantizedNodeLayerWiseGranularity.h
  compiler/luci/pass/src/VerifyQuantizedNodeS16Type.h
  compiler/luci/pass/src/VerifyQuantizedNodeU8Type.h
Labels: area/quant

#6587 [luci] Support quantization of BatchToSpaceND
  compiler/luci/pass/src/QuantizeWithMinMaxPass.cpp
  compiler/luci/pass/src/QuantizedModelVerifier.test.cpp
  compiler/luci/pass/src/VerifyQuantizedNodeChannelWiseGranularity.h
  compiler/luci/pass/src/VerifyQuantizedNodeLayerWiseGranularity.h
  compiler/luci/pass/src/VerifyQuantizedNodeS16Type.h
  compiler/luci/pass/src/VerifyQuantizedNodeU8Type.h
Labels: area/quant

#6585 [luci] Support quantization of StridedSlice
  compiler/luci/pass/src/QuantizeWithMinMaxPass.cpp
  compiler/luci/pass/src/QuantizedModelVerifier.test.cpp
  compiler/luci/pass/src/VerifyQuantizedNodeChannelWiseGranularity.h
  compiler/luci/pass/src/VerifyQuantizedNodeLayerWiseGranularity.h
  compiler/luci/pass/src/VerifyQuantizedNodeS16Type.h
  compiler/luci/pass/src/VerifyQuantizedNodeU8Type.h
Labels: area/quant

#6588 [luci] Fix wrong assert in compute_sym_scale_zp
  compiler/luci/pass/src/QuantizationUtils.cpp
Labels: area/quant

#6581 [luci] Support quantization of Elu
  compiler/luci/pass/src/QuantizeWithMinMaxPass.cpp
  compiler/luci/pass/src/QuantizedModelVerifier.test.cpp
  compiler/luci/pass/src/VerifyQuantizedNodeChannelWiseGranularity.h
  compiler/luci/pass/src/VerifyQuantizedNodeLayerWiseGranularity.h
  compiler/luci/pass/src/VerifyQuantizedNodeS16Type.h
  compiler/luci/pass/src/VerifyQuantizedNodeU8Type.h
Labels: area/quant

#6589 [arser] Make arser print short option properly
  compiler/arser/include/arser/arser.h
Labels: PR/ready for review

#6590 [luci] Support quantization of DepthToSpace
  compiler/luci/pass/src/QuantizeWithMinMaxPass.cpp
  compiler/luci/pass/src/QuantizedModelVerifier.test.cpp
  compiler/luci/pass/src/VerifyQuantizedNodeChannelWiseGranularity.h
  compiler/luci/pass/src/VerifyQuantizedNodeLayerWiseGranularity.h
  compiler/luci/pass/src/VerifyQuantizedNodeS16Type.h
  compiler/luci/pass/src/VerifyQuantizedNodeU8Type.h
Labels: area/quant

#6591 [luci] Add test for InstanceNorm quantization
  compiler/luci/pass/src/QuantizedModelVerifier.test.cpp
Labels: area/quant

#6593 [circlechef] support INT16 TensorType
  compiler/circlechef/circle/src/Convert.cpp
  compiler/circlechef/core/src/Convert.cpp
  compiler/circlechef/core/src/Convert.test.cpp
  compiler/circlechef/core/src/ModelChef.cpp
  compiler/circlechef/proto/circlechef.proto
Labels: PR/ready for review

#6586 [luci] Add interface for QuanizedModelVerifier TestGraphs
  compiler/luci/pass/src/QuantizedModelVerifier.test.cpp
Labels: area/quant

#6584 [luci] Support quantization of Pow
  compiler/luci/pass/src/QuantizeWithMinMaxPass.cpp
  compiler/luci/pass/src/QuantizedModelVerifier.test.cpp
  compiler/luci/pass/src/VerifyQuantizedNodeChannelWiseGranularity.h
  compiler/luci/pass/src/VerifyQuantizedNodeLayerWiseGranularity.h
  compiler/luci/pass/src/VerifyQuantizedNodeS16Type.h
  compiler/luci/pass/src/VerifyQuantizedNodeU8Type.h
Labels: area/quant

#6601 [luci] Resolve gtest no_assertion from our TCM
  compiler/luci/pass/src/QuantizedModelVerifier.test.cpp
Labels: area/quant, trivial

#6604 [luci] Support quantization of SpaceToDepth
  compiler/luci/pass/src/QuantizeWithMinMaxPass.cpp
  compiler/luci/pass/src/QuantizedModelVerifier.test.cpp
  compiler/luci/pass/src/VerifyQuantizedNodeChannelWiseGranularity.h
  compiler/luci/pass/src/VerifyQuantizedNodeLayerWiseGranularity.h
  compiler/luci/pass/src/VerifyQuantizedNodeS16Type.h
  compiler/luci/pass/src/VerifyQuantizedNodeU8Type.h
Labels: area/quant

#6607 [one-cmds] Revise optimization option list
  compiler/one-cmds/one-optimize
  compiler/one-cmds/utils.py
Labels: PR/ready for review

#6613 [circle2circle] Use strncpy instead of strcpy
  compiler/circle2circle/src/TestHelper.h
Labels: trivial

#6614 [circlechef] Introduce INT16 test
  compiler/circlechef/tests/short_int_datatype/test.recipe
  compiler/circlechef/tests/short_int_datatype/test.reverse
Labels: PR/ready for review

#6615 [tflchef] Introduce INT16 test
  compiler/tflchef/tests/short_int_datatype/test.recipe
  compiler/tflchef/tests/short_int_datatype/test.reverse
Labels: PR/ready for review

#6611 [luci] Support quantization of SpaceToBatchND
  compiler/luci/pass/src/QuantizeWithMinMaxPass.cpp
  compiler/luci/pass/src/QuantizedModelVerifier.test.cpp
  compiler/luci/pass/src/VerifyQuantizedNodeChannelWiseGranularity.h
  compiler/luci/pass/src/VerifyQuantizedNodeLayerWiseGranularity.h
  compiler/luci/pass/src/VerifyQuantizedNodeS16Type.h
  compiler/luci/pass/src/VerifyQuantizedNodeU8Type.h
Labels: area/quant

#6605 [luci] Verify quantization of Split
  compiler/luci/pass/src/QuantizedModelVerifier.test.cpp
  compiler/luci/pass/src/VerifyQuantizedNodeChannelWiseGranularity.h
  compiler/luci/pass/src/VerifyQuantizedNodeLayerWiseGranularity.h
  compiler/luci/pass/src/VerifyQuantizedNodeS16Type.h
  compiler/luci/pass/src/VerifyQuantizedNodeU8Type.h
Labels: area/quant

#6617 [arser] Make arser follow ODR
  compiler/arser/include/arser/arser.h
Labels: PR/ready for review

#6619 [arser] Help message test
  compiler/arser/CMakeLists.txt
  compiler/arser/tests/HelpMessage.test.cpp
  compiler/arser/tests/Prompt.h
Labels: PR/ready for review

#6644 [Compiler FE] Bump version to 1.16.0
  compiler/vconone/CMakeLists.txt
Labels: PR/NO MERGE

#6623 [infra] Remove deprecated acl checking on android build test
  infra/scripts/build_android_runtime_release.sh
Labels: PR/ready for review

#6660 Update TCM config
  .ahub/tcchecker-tca/config.yaml
Labels: trivial

#6656 Update TCM script
  infra/scripts/build-tcm.sh
Labels: PR/ready for review, trivial

#6705 [luci] Support quantization of LocalResponseNormalization
  compiler/luci/pass/src/QuantizeWithMinMaxPass.cpp
  compiler/luci/pass/src/QuantizedModelVerifier.test.cpp
  compiler/luci/pass/src/VerifyQuantizedNodeChannelWiseGranularity.h
  compiler/luci/pass/src/VerifyQuantizedNodeLayerWiseGranularity.h
  compiler/luci/pass/src/VerifyQuantizedNodeS16Type.h
  compiler/luci/pass/src/VerifyQuantizedNodeU8Type.h
Labels: area/quant
