Repository Samsung/ONE, pull requests merged in 2021-05, with the labels that each got.

#6724 [one-cmds] Add model_format option to cfg template
  compiler/one-cmds/one-build.template.cfg
Labels: PR/ready for review

#6728 [luci] Install header files
  compiler/luci/env/CMakeLists.txt
  compiler/luci/export/CMakeLists.txt
  compiler/luci/import/CMakeLists.txt
  compiler/luci/lang/CMakeLists.txt
  compiler/luci/log/CMakeLists.txt
  compiler/luci/logex/CMakeLists.txt
  compiler/luci/partition/CMakeLists.txt
  compiler/luci/pass/CMakeLists.txt
  compiler/luci/profile/CMakeLists.txt
  compiler/luci/service/CMakeLists.txt
Labels: PR/ready for review

#6729 [luci-interpreter] Install header files
  compiler/luci-interpreter/src/CMakeLists.txt
Labels: PR/ready for review

#6727 [loco] Install header files
  compiler/loco/CMakeLists.txt
Labels: PR/ready for review

#6732 [circle-tensordump] Install circle-tensordump
  compiler/circle-tensordump/CMakeLists.txt
Labels: PR/ready for review

#6733 [circledump] Install circledump
  compiler/circledump/CMakeLists.txt
Labels: PR/ready for review

#6736 [infra] Add dump tools to exclude list
  infra/scripts/docker_build_nncc.sh
Labels: PR/ready for review

#6737 [preset] Add dev tools to preset 20210406
  infra/packaging/preset/20210406
Labels: PR/ready for review

#6750 [foder] Do not delete move members
  compiler/foder/include/foder/FileLoader.h
Labels: PR/ready for review

#6755 Introduce debian folder
  debian/changelog
  debian/compat
  debian/control
  debian/copyright
  debian/one-compiler-dev.install
  debian/one-compiler-test.install
  debian/one-compiler.install
  debian/postinst
  debian/rules
  debian/source/format
  debian/source/local-options
Labels: PR/ready for review

#6767 [debian] Change the install directory
  debian/one-compiler-dev.install
  debian/one-compiler-test.install
  debian/one-compiler.install
Labels: PR/ready for review

#6788 [one-cmds] Add readlink command
  compiler/one-cmds/one-build
  compiler/one-cmds/one-codegen
  compiler/one-cmds/one-import
  compiler/one-cmds/one-import-bcq
  compiler/one-cmds/one-import-onnx
  compiler/one-cmds/one-import-tf
  compiler/one-cmds/one-import-tflite
  compiler/one-cmds/one-optimize
  compiler/one-cmds/one-pack
  compiler/one-cmds/one-quantize
Labels: PR/ready for review

#6790 [rawdata2hdf5] Add readlink command
  compiler/rawdata2hdf5/rawdata2hdf5
Labels: PR/ready for review

#6791 [bcq-tools] Remove deprecated scripts
  compiler/bcq-tools/CMakeLists.txt
  compiler/bcq-tools/generate_bcq_metadata
  compiler/bcq-tools/generate_bcq_output_arrays
Labels: PR/ready for review

#6792 [debian] Remove deprecated files
  debian/one-compiler.install
Labels: PR/ready for review

#6808 [luci] Quantize Ops with an integer output
  compiler/luci/pass/src/QuantizeWithMinMaxPass.cpp
  compiler/luci/pass/src/VerifyQuantizedNodeS16Type.h
  compiler/luci/pass/src/VerifyQuantizedNodeU8Type.h
Labels: area/quant

#6787 [debian] Change installation dir and add links
  debian/one-compiler-dev.install
  debian/one-compiler-dev.links
  debian/one-compiler-test.install
  debian/one-compiler.install
  debian/one-compiler.links
  debian/postinst
Labels: PR/ready for review

#6809 [one-cmds] Revise one-prepare-venv
  compiler/one-cmds/one-prepare-venv
Labels: PR/ready for review

#6819 [luci-eval-driver] Install binary
  compiler/luci-eval-driver/CMakeLists.txt
Labels: PR/ready for review

#6827 [debian] Relocate dh_install command
  debian/rules
Labels: PR/ready for review

#6823 [debian] Install patch file
  debian/one-compiler.install
Labels: PR/ready for review

#6822 [debian] install luci-eval-driver
  debian/one-compiler.install
Labels: PR/ready for review

#6824 [infra] Ignore debian/rules permission checking
  infra/command/format
Labels: PR/ready for review

#6825 [debian] Install nnpkg tools
  debian/one-compiler.install
Labels: PR/ready for review

#6839 [circle-tensordump] Fix static warnings
  compiler/circle-tensordump/src/Dump.cpp
Labels: trivial

#6835 [debian] Add execute permission
  debian/rules
Labels: PR/ready for review

#6836 [debian] Add postrm script
  debian/postrm
Labels: PR/ready for review

#6830 [debian] Fix install list
  debian/one-compiler-test.install
  debian/one-compiler.install
Labels: PR/ready for review

#6837 [circledump] Fix static warnings
  compiler/circledump/src/Read.h
Labels: trivial

#6838 [debian] Add symlink and tflchef tool
  debian/one-compiler-dev.install
  debian/one-compiler-dev.links
  debian/one-compiler.links
Labels: PR/ready for review

#6845 [debian] Revise postrm script
  debian/postrm
Labels: PR/ready for review

#6850 [debian] Add tflchef tools
  debian/one-compiler-dev.install
  debian/one-compiler-dev.links
Labels: PR/ready for review

#6855 [one-cmds] Make configparser preserve the case
  compiler/one-cmds/one-build
  compiler/one-cmds/utils.py
Labels: PR/ready for review

#6849 [one-cmds] Revise the way one-optimize receive options
  compiler/one-cmds/utils.py
Labels: PR/ready for review

#6858 [circledump] Restore ostream state
  compiler/circledump/src/OpPrinter.cpp
Labels: PR/ready for review

#6859 [tfldump] Restore ostream state
  compiler/tfldump/src/OpPrinter.cpp
Labels: PR/ready for review

#6860 Release Note for ONE 1.16.0
  docs/release/1.16/index.rst
  docs/release/1.16/release-note-1.16.0.md
Labels: PR/ready for review

#6862 Update NN_Runtime TCM configuration to exclude base TC set in anlysis
  .ahub/tcchecker-tca/config.yaml
Labels: PR/ready for review

#6866 [docker] Install debian build tool
  infra/docker/bionic/Dockerfile
Labels: PR/ready for review

#6868 [circle-tensordump] nullptr check for tensor name
  compiler/circle-tensordump/src/Dump.cpp
Labels: trivial

#6872 [luci] Quantize Softmax using fixed values
  compiler/luci/pass/src/QuantizeWithMinMaxPass.cpp
  compiler/luci/pass/src/VerifyQuantizedNodeS16Type.h
  compiler/luci/pass/src/VerifyQuantizedNodeU8Type.h
Labels: area/quant

#6877 [debian] Change distribution value
  debian/changelog
Labels: PR/ready for review

#6881 [debian] Add python3-things to dependencies
  debian/control
Labels: PR/ready for review

#6883 [docker] Install python3-all
  infra/docker/bionic/Dockerfile
Labels: PR/ready for review

#6887 [debian] Add 1.16.1 changelog
  debian/changelog
Labels: PR/ready for review

#6890 [one-cmds] Extends the point where codegen finds backends
  compiler/one-cmds/one-codegen
Labels: PR/ready for review, type/release

#6892 Release Note for ONE 1.16.1
  docs/release/1.16/index.rst
  docs/release/1.16/release-note-1.16.1.md
Labels: PR/NO MERGE, type/release

#6891 [debian] Add 1.16.1 changelog
  debian/changelog
Labels: PR/ready for review, type/release

#6898 [circle-quantizer] Manually set scale/zp of special Ops
  compiler/luci/pass/src/QuantizeWithMinMaxPass.cpp
  compiler/luci/pass/src/VerifyQuantizedNodeS16Type.h
  compiler/luci/pass/src/VerifyQuantizedNodeU8Type.h
Labels: area/quant

#6903 [luci] Quantize const input before bias quantization
  compiler/luci/pass/src/QuantizeWithMinMaxPass.cpp
Labels: area/quant
