Repository Samsung/ONE, pull requests merged in 2021-02, with the labels that each got.

#5879 [luci] Fix indentation in QuantizeWithMinMaxPass
  compiler/luci/pass/src/QuantizeWithMinMaxPass.cpp
Labels: trivial

#5875 [onert/test] Compare float value using misc library
  tests/tools/tflite_loader/src/tflite_loader.cc
Labels: PR/ready for review

#5902 [infra] Update tf2nnpkg for circle2circle optimize option
  infra/packaging/res/tf2nnpkg.20200630
Labels: PR/ready for review

#5903 [infra] Replace TFLite 2.3.0 cmake config for runtime
  infra/nnfw/cmake/packages/TensorFlowLite-2.3.0/TensorFlowLite/CMakeLists.txt
  infra/nnfw/cmake/packages/TensorFlowLite-2.3.0/TensorFlowLiteConfig.cmake
  infra/nnfw/cmake/packages/TensorFlowLite-2.3.0/TensorFlowLiteConfigVersion.cmake
  tests/tools/tflite_vanilla_run/CMakeLists.txt
Labels: PR/ready for review

#5916 [tflchef] Revise the way it cooks custom operator
  compiler/tflchef/core/src/ModelChef.cpp
Labels: PR/ready for review

#5852 [res] Net_Remove_Unnecessary_StridedSlice_000
  res/TensorFlowLiteRecipes/Net_StridedSlice_StridedSlice_000/test.recipe
  res/TensorFlowLiteRecipes/Net_StridedSlice_StridedSlice_000/test.rule
Labels: PR/ready for review

#5924 [luci] Revise ResolveCustomOpAdd pass
  compiler/luci/pass/src/ResolveCustomOpAddPass.cpp
Labels: PR/ready for review

#5929 [infra] Update external library abseil-cpp version
  infra/cmake/packages/AbseilSourceConfig.cmake
  infra/nnfw/cmake/packages/TensorFlowLite-2.3.0/TensorFlowLite/CMakeLists.txt
  infra/nnfw/cmake/packages/TensorFlowLite-2.3.0/TensorFlowLiteConfig.cmake
Labels: PR/ready for review

#5938 [TensorFlowLiteRecipes] Add BroadcastTo_000
  res/TensorFlowLiteRecipes/BroadcastTo_000/test.recipe
Labels: PR/ready for review

#5939 [TensorFlowLiteRecipes] Add Net_BroadcastTo_AddV2_000
  res/TensorFlowLiteRecipes/Net_BroadcastTo_AddV2_000/test.recipe
  res/TensorFlowLiteRecipes/Net_BroadcastTo_AddV2_000/test.rule
  res/TensorFlowLiteRecipes/Net_BroadcastTo_AddV2_001/test.recipe
  res/TensorFlowLiteRecipes/Net_BroadcastTo_AddV2_001/test.rule
Labels: PR/ready for review

#5942 [circle2circle-dredd-recipe-test] Add Net_BroadcastTo_AddV2
  compiler/circle2circle-dredd-recipe-test/test.lst
Labels: PR/ready for review

#5945 [doc] Update runtime cross build documentation
  docs/howto/how-to-cross-build-runtime-for-aarch64.md
  docs/howto/how-to-cross-build-runtime-for-arm.md
Labels: PR/ready for review

#5944 [tools] Remove unsupported rootfs install ubuntu version
  tools/cross/aarch64/sources.list.trusty
  tools/cross/arm/sources.list.trusty
  tools/cross/install_rootfs.sh
Labels: PR/ready for review

#5952 [infra] Fix coverage report excluding test file
  infra/command/gen-coverage-report
Labels: PR/ready for review

#5958 [onert] Remove redundant indentation
  runtime/onert/backend/acl_cl/BackendContext.cc
  runtime/onert/backend/acl_neon/BackendContext.cc
  runtime/onert/core/include/backend/cpu_common/BackendContextHelpers.h
  runtime/onert/core/src/compiler/StaticShapeInferer.cc
Labels: trivial

#5954 [loco] Support more types
  compiler/loco/include/loco/IR/DataTypeTraits.h
Labels: PR/ready for review

#5733 [onert/test] Rename tflite_loader_test_tool to tflite_comparator
  docs/howto/how-to-build-runtime.md
  infra/nnfw/cmake/CfgOptionFlags.cmake
  runtime/contrib/style_transfer_app/CMakeLists.txt
  tests/scripts/command/verify-tflite
  tests/tools/tflite_comparator/CMakeLists.txt
  tests/tools/tflite_comparator/src/args.cc
  tests/tools/tflite_comparator/src/args.h
  tests/tools/tflite_comparator/src/tflite_comparator.cc
  tests/tools/tflite_loader/CMakeLists.txt
Labels: PR/ready for review

#5963 [infra] Remove ubuntu 16.04 dockerfile
  infra/command/build-docker-image
  infra/docker/xenial/Dockerfile
  infra/scripts/docker_build_cross_aarch64_runtime.sh
  infra/scripts/docker_build_cross_arm_runtime.sh
  infra/scripts/docker_build_cross_arm_runtime_release.sh
  infra/scripts/docker_build_cross_coverage.sh
  infra/scripts/docker_build_nncc.sh
  infra/scripts/docker_build_test_x64.sh
  infra/scripts/docker_build_tizen_cross.sh
  infra/scripts/docker_collect_nnpkg_resources.sh
  infra/scripts/docker_coverage_report.sh
Labels: PR/ready for review

#5970 [luci] Revise header of CircleExporterImpl
  compiler/luci/export/src/CircleExporterImpl.cpp
Labels: trivial

#5972 [onert/lib] RandomGenerator for int8 type
  runtime/libs/misc/include/misc/RandomGenerator.h
  runtime/libs/misc/src/RandomGenerator.cpp
Labels: PR/ready for review

#5989 [onert] Remove BackendContext default impl
  runtime/onert/core/include/backend/BackendContext.h
  runtime/onert/test/core/compiler/HEScheduler.cc
Labels: trivial

#5941 [infra] Revise TFLite 2.3 cmake config
  infra/cmake/packages/OouraFFTSourceConfig.cmake
  infra/nnfw/cmake/CfgOptionFlags.cmake
  infra/nnfw/cmake/packages/TensorFlowLite-1.13.1/TensorFlowLiteConfig.cmake
  infra/nnfw/cmake/packages/TensorFlowLite-2.3.0/TensorFlowLite/CMakeLists.txt
  infra/nnfw/cmake/packages/TensorFlowLite-2.3.0/TensorFlowLiteConfig.cmake
Labels: PR/ready for review

#6019 Release Note for ONE 1.13.0
  docs/release/1.13/index.rst
  docs/release/1.13/release-note-1.13.0.md
  docs/release/index.rst
Labels: type/release

#5721 [luci/pass] Introduce RemoveUnnecessaryStridedSlicePass
  compiler/luci/pass/include/luci/CircleOptimizer.h
  compiler/luci/pass/include/luci/Pass/RemoveUnnecessaryStridedSlicePass.h
  compiler/luci/pass/src/CircleOptimizer.cpp
  compiler/luci/pass/src/RemoveUnnecessaryStridedSlicePass.cpp
  compiler/luci/pass/src/RemoveUnnecessaryStridedSlicePass.test.cpp
Labels: PR/ready for review

#5759 [circle2circle] Add RemoveUnnecessaryStridedSlicePass to circle2circle
  compiler/circle2circle/src/Circle2Circle.cpp
Labels: PR/ready for review

#5853 [compiler/luci-pass-value-test] Enable RemoveUnnecessaryStridedSlice_000
  compiler/luci-pass-value-test/test.lst
Labels: PR/ready for review

#6049 [onert/lib] Introduce tflite input initializer
  runtime/libs/tflite/include/tflite/RandomInputInitializer.h
  runtime/libs/tflite/src/RandomInputInitializer.cpp
  runtime/libs/tflite/src/RandomTestRunner.cpp
  tests/tools/tflite_run/src/tflite_run.cc
Labels: PR/ready for review

#6064 [onert/lib] Remove unused tensor util
  runtime/libs/tflite/include/tflite/TensorShapeUtils.h
  runtime/libs/tflite/src/TensorShapeUtils.cpp
Labels: PR/ready for review, trivial
