Repository Samsung/ONE, pull requests merged in 2022-12, with the labels that each got.

#10150 [onert] Deprecate pipeline API
  runtime/onert/api/src/nnfw_api_internal.cc
  runtime/onert/api/src/nnfw_api_internal.h
  runtime/onert/core/include/compiler/Compiler.h
  runtime/onert/core/include/compiler/LoweredGraph.h
  runtime/onert/core/include/exec/Execution.h
  runtime/onert/core/include/exec/IExecutor.h
  runtime/onert/core/include/ir/Graph.h
  runtime/onert/core/include/ir/OperandIndexSequence.h
  runtime/onert/core/src/compiler/Compiler.cc
  runtime/onert/core/src/compiler/LoweredGraph.cc
  runtime/onert/core/src/exec/Execution.cc
  runtime/onert/core/src/exec/ExecutorBase.cc
  runtime/onert/core/src/exec/ExecutorBase.h
  runtime/onert/core/src/interp/InterpExecutor.h
  runtime/onert/frontend/base_loader/include/base_loader.h
  runtime/onert/frontend/circle/src/circle_loader.cc
  runtime/onert/frontend/tflite/src/tflite_loader.cc
  tests/nnfw_api/src/ValidationTestPipelineSession.test.cc
Labels: PR/ready for review, approval: 2

#10153 [onert-micro] Add option to choose pal
  onert-micro/CMakeLists.txt
Labels: approval: 1

#10162 [onert/test] Use curl for test model download
  tests/scripts/models/run_test.sh
Labels: PR/ready for review

#10011 [onert-micro] Enable StaticMemoryManager in onert-micro
  onert-micro/luci-interpreter/include/luci_interpreter/Interpreter.h
  onert-micro/luci-interpreter/include/luci_interpreter/MemoryManager.h
  onert-micro/luci-interpreter/include/luci_interpreter/StaticMemoryManager.h
  onert-micro/luci-interpreter/include/luci_interpreter/core/Tensor.h
  onert-micro/luci-interpreter/include/luci_interpreter/core/reader/CircleMicroReader.h
  onert-micro/luci-interpreter/include/luci_interpreter/memory_managers/BuddyMemoryManager.h
  onert-micro/luci-interpreter/include/luci_interpreter/memory_managers/MemoryManager.h
  onert-micro/luci-interpreter/include/luci_interpreter/memory_managers/SimpleMemoryManager.h
  onert-micro/luci-interpreter/include/luci_interpreter/memory_managers/StaticMemoryManager.h
  onert-micro/luci-interpreter/include/luci_interpreter/memory_managers/TestMemoryManager.h
  onert-micro/luci-interpreter/src/CMakeLists.txt
  onert-micro/luci-interpreter/src/Interpreter.cpp
  onert-micro/luci-interpreter/src/core/RuntimeGraph.cpp
  onert-micro/luci-interpreter/src/core/RuntimeGraph.h
  onert-micro/luci-interpreter/src/core/RuntimeModule.h
  onert-micro/luci-interpreter/src/kernels/CMakeLists.txt
  onert-micro/luci-interpreter/src/loader/CMakeLists.txt
  onert-micro/luci-interpreter/src/loader/GraphLoader.cpp
  onert-micro/luci-interpreter/src/loader/GraphLoader.h
  onert-micro/luci-interpreter/src/loader/KernelBuilder.cpp
  onert-micro/luci-interpreter/src/loader/KernelBuilder.h
  onert-micro/luci-interpreter/src/loader/ModuleLoader.cpp
  onert-micro/luci-interpreter/src/loader/ModuleLoader.h
  onert-micro/luci-interpreter/src/memory_managers/BuddyMemoryManager.cpp
  onert-micro/luci-interpreter/src/memory_managers/BuddyMemoryManager.test.cpp
  onert-micro/luci-interpreter/src/memory_managers/CMakeLists.txt
  onert-micro/luci-interpreter/src/memory_managers/SimpleMemoryManager.cpp
  onert-micro/luci-interpreter/src/memory_managers/StaticMemoryManager.cpp
  onert-micro/luci-interpreter/src/memory_managers/TestMemoryManager.cpp
Labels: approval: 1

#10166 [circle-opselector] Remove deprecated codes
  compiler/circle-opselector/driver/Driver.cpp
  compiler/circle-opselector/src/Driver.test.cpp
  compiler/circle-opselector/src/Driver.test.h
Labels: PR/ready for review

#10168 [onert-micro] Fix CMAKE_TOOLCHAIN_FILE variable
  onert-micro/CMakeLists.txt
Labels: approval: 1

#10169 [onert/test] Update md5 check curl option
  tests/scripts/models/run_test.sh
Labels: PR/ready for review

#10029 [docs] update how-to-build-runtime documents
  docs/howto/how-to-build-runtime.md
  docs/howto/how-to-cross-build-runtime-for-arm.md
Labels: documentation

#10167 [onert-micro] Change Interpreter interface
  onert-micro/luci-interpreter/include/luci_interpreter/Interpreter.h
  onert-micro/luci-interpreter/include/luci_interpreter/InterpreterConfigure.h
  onert-micro/luci-interpreter/src/Interpreter.cpp
  onert-micro/luci-interpreter/src/core/RuntimeGraph.cpp
  onert-micro/luci-interpreter/src/core/RuntimeGraph.h
  onert-micro/luci-interpreter/src/core/RuntimeModule.h
  onert-micro/luci-interpreter/src/loader/GraphLoader.cpp
  onert-micro/luci-interpreter/src/loader/GraphLoader.h
  onert-micro/luci-interpreter/src/loader/ModuleLoader.cpp
  onert-micro/luci-interpreter/src/loader/ModuleLoader.h
  onert-micro/luci-interpreter/src/memory_managers/BuddyMemoryManager.cpp
  onert-micro/luci-interpreter/src/memory_managers/BuddyMemoryManager.h
  onert-micro/luci-interpreter/src/memory_managers/BuddyMemoryManager.test.cpp
  onert-micro/luci-interpreter/src/memory_managers/CMakeLists.txt
  onert-micro/luci-interpreter/src/memory_managers/MemoryManager.h
  onert-micro/luci-interpreter/src/memory_managers/SimpleMemoryManager.cpp
  onert-micro/luci-interpreter/src/memory_managers/SimpleMemoryManager.h
  onert-micro/luci-interpreter/src/memory_managers/StaticMemoryManager.cpp
  onert-micro/luci-interpreter/src/memory_managers/StaticMemoryManager.h
  onert-micro/luci-interpreter/src/memory_managers/TestMemoryManager.cpp
  onert-micro/luci-interpreter/src/memory_managers/TestMemoryManager.h
Labels: approval: 1

#10187 [gbs] Update gbs.conf
  infra/nnfw/config/gbs.conf
Labels: PR/ready for review

#10186 [luci-interpreter] Introduce Abs kernel
  compiler/luci-interpreter/pal/cmsisnn/KernelsToBuild.lst
  compiler/luci-interpreter/pal/linux/KernelsToBuild.lst
  compiler/luci-interpreter/pal/mcu/KernelsToBuild.lst
  compiler/luci-interpreter/src/kernels/Abs.cpp
  compiler/luci-interpreter/src/kernels/Abs.h
  compiler/luci-interpreter/src/kernels/Abs.test.cpp
  compiler/luci-interpreter/src/loader/nodes/Abs.cpp
Labels: approval: 2

#10189 [tools] Add an argument `--store-metadata` to `select_operator.py`
  tools/tflitefile_tool/select_operator.py
Labels: PR/ready for review

#10192 [gbs] Add Flatbuffers 2.0 source
  packaging/FLATBUFFERS-2.0.tar.gz
  packaging/nnfw.spec
Labels: PR/ready for review

#10200 [tools/model2nnpkg] Put missing and fix wrong quotes
  tools/nnpackage_tool/model2nnpkg/model2nnpkg.sh
Labels: area/onert

#10197 [onert-micro] Introduce eval driver
  onert-micro/CMakeLists.txt
  onert-micro/eval-driver/CMakeLists.txt
  onert-micro/eval-driver/Driver.cpp
  onert-micro/luci-interpreter/src/CMakeLists.txt
  onert-micro/luci-interpreter/src/core/CMakeLists.txt
  onert-micro/luci-interpreter/src/core/reader/CMakeLists.txt
  onert-micro/luci-interpreter/src/kernels/CMakeLists.txt
Labels: approval: 1

#10146 [record-minmax] Revise to prepare to multiple instance
  compiler/record-minmax/driver/Driver.cpp
  compiler/record-minmax/include/RecordMinMax.h
  compiler/record-minmax/src/RecordMinMax.cpp
Labels: PR/ready for review

#10222 [tflite2circle] Extends builtin code coverage
  compiler/tflite2circle/src/DataLookup.cpp
  compiler/tflite2circle/src/DataLookup.h
  compiler/tflite2circle/src/TFLOperator.lst
Labels: PR/ready for review

#10223 [record-minmax] Use nncc_common
  compiler/record-minmax/CMakeLists.txt
  compiler/record-minmax/driver/Driver.cpp
  compiler/record-minmax/include/RecordFunction.h
  compiler/record-minmax/include/RecordMinMax.h
  compiler/record-minmax/src/RecordMinMax.cpp
Labels: area/quant

#10219 [onert] Revisit CompilerOptions
  runtime/onert/core/include/compiler/Compiler.h
  runtime/onert/core/include/compiler/CompilerOptions.h
  runtime/onert/core/src/compiler/Compiler.cc
  runtime/onert/core/src/compiler/CompilerOptions.cc
  runtime/onert/frontend/nnapi/wrapper/ANeuralNetworksCompilation.cc
Labels: PR/ready for review, approval: 2

#10230 [infra/runtime] Add shebang to Makefile.template
  Makefile.template
Labels: area/onert, trivial, approval: 1

#10232 [npud] Comment out unreachable code
  runtime/service/npud/core/DBus.cc
Labels: PR/ready for review, approval: 1

#10231 [npud] Initialize variable
  runtime/service/npud/backend/trix/TrixBackend.cc
Labels: PR/ready for review, approval: 1

#10221 [tools/model2nnpkg] Introduce python script
  tools/nnpackage_tool/model2nnpkg/README.md
  tools/nnpackage_tool/model2nnpkg/model2nnpkg.py
Labels: PR/ready for review

#10237 [common-artifacts] Use python model2nnpkg
  compiler/common-artifacts/CMakeLists.txt
Labels: PR/ready for review

#10238 [tf2circle-value-pbtxt-remote-test] Use python model2nnpkg
  compiler/tf2circle-value-pbtxt-remote-test/CMakeLists.txt
  compiler/tf2circle-value-pbtxt-remote-test/testall.sh
Labels: PR/ready for review

#10198 [tools/tflitefile_tool] Add io info of original model to io file
  tools/tflitefile_tool/README.md
  tools/tflitefile_tool/select_operator.py
Labels: PR/ready for review

#10244 [model2nnpkg] Fix diff between bash and python script
  tools/nnpackage_tool/model2nnpkg/model2nnpkg.py
Labels: PR/ready for review

#10233 [infra] Add npud test in TCM configuration
  .ahub/tcchecker-tca/config.yaml
Labels: PR/ready for review

#10253 [tools/tflitefile_tool] Add new line at end of output json files
  tools/tflitefile_tool/select_operator.py
Labels: approval: 1

#10250 [luci/pass] Reduce duplicates of ForwardTransposeOpPass
  compiler/luci/pass/src/ForwardTransposeOpPass.cpp
  compiler/luci/pass/src/ForwardTransposeOpPass.test.cpp
Labels: PR/ready for review

#10258 [onert] Move static shape inferer map creation
  runtime/onert/core/include/compiler/StaticShapeInferer.h
  runtime/onert/core/src/compiler/Compiler.cc
  runtime/onert/core/src/compiler/StaticShapeInferer.cc
Labels: PR/ready for review

#10255 [luci] Fake quantize ABS Op
  compiler/luci/pass/src/ConvertToFakeQuantizedModelPass.cpp
Labels: area/quant

#10259 [doc] Update runtime howto: run test
  docs/howto/how-to-build-runtime.md
Labels: PR/ready for review, approval: 2

#10257 [one-cmds] Install model2nnpkg
  compiler/one-cmds/CMakeLists.txt
Labels: PR/ready for review

#10262 [infra] Use new model2nnpkg script
  infra/debian/compiler/one-compiler.install
  infra/packaging/res/tf2nnpkg.20221125
Labels: PR/ready for review

#10261 [onert] Introduce ICompiler and factory
  runtime/onert/api/src/nnfw_api_internal.cc
  runtime/onert/core/include/compiler/Compiler.h
  runtime/onert/core/include/compiler/CompilerFactory.h
  runtime/onert/core/include/compiler/ICompiler.h
  runtime/onert/core/src/compiler/CompilerFactory.cc
Labels: PR/ready for review

#10263 [one-cmds] Use python model2nnpkg in one-pack
  compiler/one-cmds/one-pack
Labels: PR/ready for review
