Repository Samsung/ONE, pull requests merged in 2022-10, with the labels that each got.

#9817 [onecc-docker] Add argparse to onecc-docker
  compiler/onecc-docker/onecc-docker
Labels: SSAFY

#9815 [onecc-docker] onecc-docker permission error fix
  compiler/onecc-docker/debian/rules
Labels: PR/ready for review, SSAFY

#9826 [onert] Introduce I/O size getter for package
  runtime/onert/api/src/nnfw_api_internal.cc
  runtime/onert/api/src/nnfw_api_internal.h
  runtime/onert/core/include/ir/NNPkg.h
Labels: PR/ready for review

#9831 [onert] Change SubgraphIndex value type
  runtime/onert/core/include/ir/Index.h
  runtime/onert/core/src/compiler/Compiler.cc
  runtime/onert/frontend/base_loader/include/base_loader.h
Labels: area/onert

#9844 [infra] Support parallel build for external build on Makefile.arm32
  infra/nncc/Makefile.arm32
Labels: PR/ready for review

#9845 [infra] Add execution permission to compiler cross build script
  infra/scripts/docker_build_cross_arm_compiler_debug.sh
Labels: PR/ready for review

#9846 [infra] Allow volume mounting on nncc-docker command
  infra/nncc/config/docker.configuration
Labels: PR/ready for review

#9837 [onert-micro] Enable using GeneratedKernelsToBuild list
  onert-micro/luci-interpreter/src/loader/CMakeLists.txt
  onert-micro/luci-interpreter/src/loader/KernelBuilder.cpp
  onert-micro/luci-interpreter/src/loader/nodes/Builders.h
Labels: approval: 1

#9847 [infra/onert-micro] Introduce utils.cmake
  infra/onert-micro/CMakeLists.txt
  infra/onert-micro/cmake/ApplyCompileFlags.cmake
  infra/onert-micro/cmake/CfgOptionFlags.cmake
  infra/onert-micro/utils.cmake
Labels: approval: 1

#9848 [onert-micro] Revisit standalone CMakeLists.txt
  onert-micro/standalone/CMakeLists.txt
Labels: approval: 1

#9855 [onert] Split supported multimodel check
  runtime/onert/core/include/exec/Executors.h
  runtime/onert/core/src/exec/Executors.cc
Labels: PR/ready for review, approval: 1

#9860 [onert] nnfw_session::create covers more allocation failures
  runtime/onert/api/src/nnfw_api_internal.cc
Labels: area/onert

#9859 [onert] Support no branch multimodels execution
  runtime/onert/api/src/nnfw_api_internal.cc
  runtime/onert/core/include/exec/Executors.h
  runtime/onert/core/src/exec/Executors.cc
Labels: PR/ready for review, approval: 2

#9865 [infra/onert-micro] Define build options
  infra/onert-micro/CMakeLists.txt
Labels: approval: 1

#9866 [onert-micro] Change TARGET_CPU and TARGET_ARCH options
  onert-micro/CMakeLists.txt
Labels: approval: 1

#9869 [onert] Check model output connection
  runtime/onert/core/src/exec/Executors.cc
Labels: PR/ready for review

#9867 [infra] Add armv7-r TARGET_ARCH
  infra/cmake/modules/IdentifyPlatform.cmake
Labels: approval: 2

#9870 [onert/nnpackage_run] Introduce single model file loading
  tests/tools/nnpackage_run/src/args.cc
  tests/tools/nnpackage_run/src/args.h
  tests/tools/nnpackage_run/src/nnpackage_run.cc
Labels: PR/ready for review

#9871 [infra/gbs] Reduce external source size
  packaging/EGL_HEADERS.tar.gz
  packaging/XNNPACK.tar.gz
Labels: PR/ready for review, approval: 1

#9874 [onert] Remove forward declaration IExecutionObserver
  runtime/onert/core/include/exec/IExecutor.h
Labels: area/onert, trivial

#9820 [onert] Add handling of errors that occur within threads of `BatchThreadPool`
  runtime/onert/backend/trix/BatchThreadPool.cc
  runtime/onert/backend/trix/DevContext.cc
  runtime/onert/backend/trix/DevContext.h
Labels: PR/ready for review, area/onert

#9875 [onert] Remove NNAPI usage on tflite_run
  tests/tools/tflite_run/src/tflite_run.cc
Labels: PR/ready for review

#9878 [onert/test] Clean up test-driver.sh
  tests/scripts/test-driver.sh
  tests/scripts/test_framework.sh
Labels: PR/ready for review

#9882 [CI] Update workflow with latest actions version
  .github/workflows/check-format.yml
  .github/workflows/check-pr-commit.yml
Labels: PR/ready for review

#9876 [visq] Introduce visq module
  compiler/visq/CMakeLists.txt
  compiler/visq/README.md
  compiler/visq/requires.cmake
  compiler/visq/visq
  compiler/visq/visqlib/DumpFP32FM.py
  compiler/visq/visqlib/DumpFakeQuantFM.py
  compiler/visq/visqlib/Palette.py
  compiler/visq/visqlib/QErrorComputer.py
  compiler/visq/visqlib/Util.py
Labels: area/quant

#9886 [onert/test] Rename unittests install directory
  compute/cker/CMakeLists.txt
  infra/scripts/common.sh
  infra/scripts/test_ubuntu_runtime.sh
  infra/scripts/test_ubuntu_runtime_mixed.sh
  packaging/nnfw.spec
  runtime/libs/misc/CMakeLists.txt
  runtime/libs/ndarray/CMakeLists.txt
  runtime/onert/core/CMakeLists.txt
  runtime/onert/frontend/nnapi/CMakeLists.txt
  runtime/service/npud/CMakeLists.txt
  tests/nnapi/CMakeLists.txt
  tests/nnfw_api/CMakeLists.txt
  tests/tools/tflite_run/CMakeLists.txt
Labels: PR/ready for review

#9888 [visq] Add MSE metric
  compiler/visq/README.md
  compiler/visq/visq
  compiler/visq/visqlib/QErrorComputer.py
Labels: area/quant

#9891 [visq] Add directory for unittest
  compiler/visq/CMakeLists.txt
  compiler/visq/test/__init__.py
  compiler/visq/test/testPalette.py
  compiler/visq/test/testUtil.py
Labels: area/quant

#9901 [record-minmax] Improve error message
  compiler/record-minmax/src/RecordMinMax.cpp
Labels: area/quant

#9897 [luci] Support S2D, D2S in fake quantization
  compiler/luci/pass/src/ConvertToFakeQuantizedModelPass.cpp
Labels: area/quant

#9904 [res] Add S2D, D2S recipes and rules
  res/TensorFlowLiteRecipes/Quant_DepthToSpace_000/test.recipe
  res/TensorFlowLiteRecipes/Quant_DepthToSpace_000/test.rule
  res/TensorFlowLiteRecipes/Quant_SpaceToDepth_000/test.recipe
  res/TensorFlowLiteRecipes/Quant_SpaceToDepth_000/test.rule
Labels: area/quant

#9902 [onert/lib] Remove NNAPISession
  runtime/libs/tflite/include/tflite/NNAPISession.h
  tests/tools/tflite_run/src/tflite_run.cc
Labels: PR/ready for review

#9906 [infra] Introduce visq module
  infra/debian/compiler/one-compiler.install
  infra/packaging/preset/20220323
  infra/packaging/preset/20220323_windows
  infra/scripts/compiler_modules.sh
Labels: area/quant

#9907 [circle-quantizer-dredd] Add S2D, D2S fake quant tests
  compiler/circle-quantizer-dredd-recipe-test/test.lst
Labels: area/quant

#9916 [onecc] Change the way removing whitespace in Makefile.arm32
  infra/nncc/Makefile.arm32
Labels: PR/ready for review

#9918 [onecc/luci] Include `cstddef` in SparsityFormatConverter.h
  compiler/luci/pass/src/helpers/SparsityFormatConverter.h
Labels: PR/ready for review, approval: 1

#9914 [infra] Check pre-installed TFLite 2.8.0
  infra/nnfw/cmake/packages/TensorFlowLite-2.8.0/TensorFlowLiteConfig.cmake
Labels: PR/ready for review

#9924 [lib/tflite] Remove unused implementation
  runtime/libs/tflite/include/tflite/CopyInputInitializer.h
  runtime/libs/tflite/include/tflite/FeatureView.h
  runtime/libs/tflite/include/tflite/OutputIndex.h
  runtime/libs/tflite/include/tflite/OutputResetter.h
  runtime/libs/tflite/include/tflite/Quantization.h
  runtime/libs/tflite/include/tflite/RandomTestRunner.h
  runtime/libs/tflite/include/tflite/TensorLogger.h
  runtime/libs/tflite/include/tflite/TensorUtils.h
  runtime/libs/tflite/src/CopyInputInitializer.cpp
  runtime/libs/tflite/src/FeatureView.cpp
  runtime/libs/tflite/src/OutputResetter.cpp
  runtime/libs/tflite/src/Quantization.cpp
  runtime/libs/tflite/src/RandomTestRunner.cpp
Labels: PR/ready for review

#9943 [infra/onert-micro] Add armv8-m generic options
  infra/onert-micro/cmake/options/options_armv8-m-generic.cmake
Labels: approval: 1

#9936 [onert/test] Retry test model download
  tests/scripts/models/run_test.sh
Labels: PR/ready for review

#9949 [luci] Quantize weights on the fly
  compiler/luci/pass/src/QuantizeWeights.cpp
Labels: area/quant

#9926 [onert/test] Allow small diff on quantization test
  tests/scripts/list/tflite_comparator.aarch64.acl_cl.list
  tests/scripts/list/tflite_comparator.armv7l.acl_cl.list
  tests/tools/tflite_comparator/src/tflite_comparator.cc
Labels: PR/ready for review

#9955 [res] Add test for quant without QuantizeDequantizeWeights
  res/TensorFlowLiteRecipes/Quant_Conv_005/test.recipe
  res/TensorFlowLiteRecipes/Quant_Conv_005/test.rule
  res/TensorFlowLiteRecipes/Quant_Conv_006/test.recipe
  res/TensorFlowLiteRecipes/Quant_Conv_006/test.rule
Labels: area/quant

#9950 [circle-quantizer-dredd-test] Add test for quant without QuantizeDequantizeWeights
  compiler/circle-quantizer-dredd-recipe-test/CMakeLists.txt
  compiler/circle-quantizer-dredd-recipe-test/test.lst
Labels: area/quant

#9951 [onert] Allow using I/O buffer for all models
  runtime/onert/core/src/exec/Executors.cc
Labels: PR/ready for review, approval: 2

#9954 [circle-opselector] Implement circle-opselector main logic
  compiler/circle-opselector/CMakeLists.txt
  compiler/circle-opselector/driver/Driver.cpp
Labels: PR/ready for review
