Repository Samsung/ONE, pull requests merged in 2022-08, with the labels that each got.

#9523 [one-cmds] Add fake quantization option to one-quantize
  compiler/one-cmds/one-quantize
  compiler/one-cmds/tests/one-quantize_015.test
Labels: area/quant

#9529 [circle-eval-diff] Support MSE printer
  compiler/circle-eval-diff/driver/Driver.cpp
  compiler/circle-eval-diff/include/CircleEvalDiff.h
  compiler/circle-eval-diff/src/CircleEvalDiff.cpp
  compiler/circle-eval-diff/src/MetricPrinter.cpp
  compiler/circle-eval-diff/src/MetricPrinter.h
  compiler/circle-eval-diff/src/MetricPrinter.test.cpp
Labels: area/quant

#9530 [one-cmds] Support print_mse in one-quantize
  compiler/one-cmds/one-quantize
Labels: area/quant

#9532 [infra/gbs] Remove gbs.conf internal repo
  infra/nnfw/config/gbs.conf
Labels: PR/ready for review

#9572 [onert/api] Fix typos
  runtime/onert/api/include/nnfw.h
Labels: area/onert, trivial, approval: 1

#9577 [onert] Move setConfigKeyValues
  runtime/onert/api/src/nnfw_api_internal.cc
  runtime/onert/backend/cpu/ExternalContext.h
  runtime/onert/backend/ruy/ExternalContext.h
  runtime/onert/core/include/util/ConfigSource.h
  runtime/onert/core/src/backend/builtin/ExternalContext.h
  runtime/onert/core/src/util/ConfigSource.cc
Labels: PR/ready for review, approval: 2

#9575 [npud] Simplify config implementation
  runtime/service/npud/util/ConfigSource.cc
  runtime/service/npud/util/ConfigSource.h
Labels: PR/ready for review

#9574 [luci] Check if nullptr after dynamic casting
  compiler/luci/pass/src/ConvertNCHWToNHWCPass.test.cpp
Labels: PR/ready for review

#9586 [onert] Change nnfw_lib_misc to private link
  runtime/onert/api/CMakeLists.txt
  runtime/onert/backend/cpu/CMakeLists.txt
  runtime/onert/core/CMakeLists.txt
Labels: PR/ready for review

#9587 [runtime] Move ConfigSource classess
  runtime/libs/misc/include/misc/EnvConfigSource.h
  runtime/libs/misc/include/misc/GeneralConfigSource.h
  runtime/libs/misc/include/misc/IConfigSource.h
  runtime/libs/misc/src/EnvConfigSource.cpp
  runtime/libs/misc/src/GeneralConfigSource.cpp
  runtime/onert/api/src/nnfw_api_internal.h
  runtime/onert/core/include/util/EnvConfigSource.h
  runtime/onert/core/include/util/GeneralConfigSource.h
  runtime/onert/core/src/util/ConfigSource.cc
  runtime/service/npud/CMakeLists.txt
  runtime/service/npud/util/ConfigSource.cc
  runtime/service/npud/util/EnvConfigSource.cc
  runtime/service/npud/util/EnvConfigSource.h
  runtime/service/npud/util/GeneralConfigSource.cc
Labels: PR/ready for review

#9593 [infra] Update CpuInfo
  infra/cmake/packages/CpuInfoSourceConfig.cmake
  infra/nnfw/cmake/packages/CpuInfoConfig.cmake
  packaging/CPUINFO.tar.gz
Labels: PR/ready for review

#9603 [one-cmds] Add workflow test
  compiler/one-cmds/tests/onecc_neg_023.test
  compiler/one-cmds/tests/onecc_neg_023.workflow.json
Labels: PR/ready for review

#9604 [one-cmds] fix onecc_neg_022 test
  compiler/one-cmds/tests/onecc_neg_022.test
Labels: PR/ready for review

#9606 [nnpkg_run] Suppress raw exception message on missing --nnpackage
  tests/tools/nnpackage_run/src/nnpackage_run.cc
Labels: area/onert

#9617 [onert/test] Update nnpkg-test command
  tests/scripts/command/nnpkg-test
Labels: PR/ready for review

#9618 [onert] Rename model connect description struct
  runtime/onert/api/src/nnfw_api_internal.cc
  runtime/onert/core/include/ir/NNPkg.h
Labels: PR/ready for review

#9621 [onert] Add Conv2D per-channel Q8u kernel
  compute/cker/include/cker/operation/reference/Conv.h
Labels: area/onert

#9623 [onert/test] Fix bug nnpkg-test
  tests/scripts/command/nnpkg-test
Labels: PR/ready for review

#9625 [onert] Use template to reduce duplicated in Conv2d
  compute/cker/include/cker/operation/Conv.h
  compute/cker/include/cker/operation/reference/Conv.h
Labels: area/onert

#9622 [onert] Introduce Executors
  runtime/onert/core/include/compiler/Compiler.h
  runtime/onert/core/include/exec/Execution.h
  runtime/onert/core/include/exec/Executors.h
  runtime/onert/core/include/exec/IExecutor.h
  runtime/onert/core/src/backend/builtin/KernelGenerator.cc
  runtime/onert/core/src/backend/builtin/KernelGenerator.h
  runtime/onert/core/src/backend/builtin/kernel/IfLayer.cc
  runtime/onert/core/src/backend/builtin/kernel/IfLayer.h
  runtime/onert/core/src/backend/builtin/kernel/WhileLayer.cc
  runtime/onert/core/src/backend/builtin/kernel/WhileLayer.h
  runtime/onert/core/src/compiler/Compiler.cc
  runtime/onert/core/src/compiler/ExecutorFactory.cc
  runtime/onert/core/src/compiler/ExecutorFactory.h
  runtime/onert/core/src/exec/Execution.cc
  runtime/onert/core/src/exec/Execution.test.cc
  runtime/onert/core/src/exec/ExecutionObservers.h
  runtime/onert/core/src/interp/InterpExecutor.test.cc
  runtime/onert/frontend/nnapi/execution.cc
  runtime/onert/frontend/nnapi/wrapper/ANeuralNetworksCompilation.h
  runtime/onert/frontend/nnapi/wrapper/ANeuralNetworksExecution.h
Labels: PR/ready for review

#9624 [onert] Support conv2d per-channel uint8 quantization
  compute/cker/include/cker/operation/Conv.h
  runtime/onert/backend/cpu/ops/ConvolutionLayer.cc
  runtime/onert/backend/cpu/ops/ConvolutionLayer.h
  runtime/onert/core/include/ir/TypeInfo.h
Labels: area/onert

#9611 [onert/test] Add Conv2D per-channel uint8 test case
  tests/nnfw_api/src/one_op_tests/Conv2D.test.cc
Labels: PR/ready for review, area/onert

#9627 [onert] Introduce Compiler contructor for NNPkg
  runtime/onert/core/include/compiler/Compiler.h
  runtime/onert/core/include/ir/NNPkg.h
  runtime/onert/core/src/compiler/Compiler.cc
Labels: PR/ready for review, approval: 2

#9628 [infra/runtime] Upgrade Ruy version
  compute/cker/include/cker/NeonTensorUtils.h
  compute/cker/include/cker/ruy/RuySupport.h
  compute/ruy/include/ruy/RuySupport.h
  compute/ruy/include/ruy/operation/Conv.h
  compute/ruy/include/ruy/operation/FullyConnected.h
  infra/nnfw/cmake/packages/Ruy/CMakeLists.txt
  infra/nnfw/cmake/packages/RuyConfig.cmake
  infra/nnfw/cmake/packages/TensorFlowLite-2.3.0/TensorFlowLite/CMakeLists.txt
  infra/nnfw/cmake/packages/TensorFlowLite-2.3.0/TensorFlowLiteConfig.cmake
  infra/nnfw/cmake/packages/TensorFlowRuy/CMakeLists.txt
  infra/nnfw/cmake/packages/TensorFlowRuyConfig.cmake
  packaging/RUY.tar.gz
  packaging/TENSORFLOW-2.8.0-RUY.tar.gz
  packaging/nnfw.spec
  tests/tools/tflite_vanilla_run/CMakeLists.txt
Labels: PR/ready for review

#9629 [infra/runtime] Set flag for NEON2SSE debug build
  infra/cmake/packages/NEON2SSESourceConfig.cmake
  infra/nnfw/cmake/packages/TensorFlowLite-1.13.1/TensorFlowLite/CMakeLists.txt
  infra/nnfw/cmake/packages/TensorFlowLite-2.3.0/TensorFlowLite/CMakeLists.txt
Labels: PR/ready for review

#9631 [infra] Add absl::status on abseil library
  infra/cmake/packages/AbseilConfig.cmake
Labels: PR/ready for review

#9630 [onert] Abstract accessing I/O info and execute
  runtime/onert/core/include/exec/Executors.h
  runtime/onert/core/src/exec/Execution.cc
  runtime/onert/core/src/exec/Executors.cc
Labels: PR/ready for review, approval: 2

#9638 [infra] Update FP16
  infra/cmake/packages/Fp16SourceConfig.cmake
  packaging/FP16.tar.gz
Labels: PR/ready for review

#9636 [onert] Create Executors for multimodel
  runtime/onert/api/src/nnfw_api_internal.cc
  runtime/onert/core/include/exec/Executors.h
  runtime/onert/core/include/ir/NNPkg.h
  runtime/onert/core/src/compiler/Compiler.cc
  runtime/onert/core/src/exec/Executors.cc
Labels: PR/ready for review, approval: 2

#9639 [infra] Enable TFLite 2.8 build and use
  infra/debian/runtime/rules
  infra/nnfw/cmake/CfgOptionFlags.cmake
  infra/nnfw/cmake/packages/TensorFlowLite-2.8.0/TensorFlowLite/CMakeLists.txt
  infra/nnfw/cmake/packages/TensorFlowLite-2.8.0/TensorFlowLiteConfig.cmake
  infra/nnfw/cmake/packages/TensorFlowLite-2.8.0/TensorFlowLiteConfigVersion.cmake
  infra/nnfw/cmake/packages/TensorFlowRuy/CMakeLists.txt
  infra/nnfw/cmake/packages/TensorFlowRuyConfig.cmake
  tests/tools/tflite_vanilla_run/CMakeLists.txt
  tests/tools/tflite_vanilla_run/src/tflite_vanilla_run.cc
Labels: PR/ready for review

#9641 [onert] Support simple multimodel package execution
  runtime/onert/core/include/exec/Executors.h
  runtime/onert/core/src/exec/Executors.cc
Labels: PR/ready for review, approval: 2

#9640 [onert] Move ModelEdges
  runtime/onert/core/include/exec/Executors.h
  runtime/onert/core/include/ir/NNPkg.h
  runtime/onert/core/src/compiler/Compiler.cc
Labels: PR/ready for review

#9391 [nnpackage] Add multiple model nnpkg example
  nnpackage/examples/README.md
  nnpackage/examples/v1.3.0/two_tflites/README.md
  nnpackage/examples/v1.3.0/two_tflites/metadata/MANIFEST
  nnpackage/examples/v1.3.0/two_tflites/metadata/tc/expected.h5
  nnpackage/examples/v1.3.0/two_tflites/metadata/tc/input.h5
  nnpackage/examples/v1.3.0/two_tflites/mv1.0.tflite
  nnpackage/examples/v1.3.0/two_tflites/mv1.1.tflite
Labels: area/onert

#9644 [onert] Renames methods in dconv to more proper names
  runtime/onert/backend/cpu/ops/DepthwiseConvolutionLayer.cc
  runtime/onert/backend/cpu/ops/DepthwiseConvolutionLayer.h
Labels: area/onert

#9633 [nnpkg_tools/gen_golden] Use same range for float random
  tools/nnpackage_tool/gen_golden/gen_golden.py
Labels: area/onert
