Repository Samsung/ONE, pull requests merged in 2022-11, with the labels that each got.

#9956 [onert] Use TFLite 2.8 for test driver
  infra/nnfw/cmake/CfgOptionFlags.cmake
  infra/nnfw/cmake/packages/TensorFlowLite-2.8.0/TensorFlowLiteConfig.cmake
  packaging/nnfw.spec
  runtime/libs/tflite/CMakeLists.txt
  runtime/libs/tflite/include/tflite/Diff.h
  runtime/libs/tflite/include/tflite/InterpreterSession.h
  runtime/libs/tflite/include/tflite/RandomInputInitializer.h
  runtime/libs/tflite/include/tflite/Session.h
  runtime/libs/tflite/include/tflite/TensorView.h
  runtime/libs/tflite/include/tflite/interp/Builder.h
  runtime/libs/tflite/include/tflite/interp/FlatBufferBuilder.h
  runtime/libs/tflite/include/tflite/interp/FunctionBuilder.h
  runtime/libs/tflite/src/Diff.cpp
  runtime/libs/tflite/src/RandomInputInitializer.cpp
  runtime/libs/tflite/src/interp/FlatBufferBuilder.cpp
  runtime/libs/tflite/src/interp/FunctionBuilder.cpp
  tests/scripts/list/tflite_comparator.aarch64.cpu.list
  tests/scripts/list/tflite_comparator.armv7l.cpu.list
  tests/scripts/list/tflite_comparator.x86_64.cpu.list
  tests/tools/tflite_comparator/src/tflite_comparator.cc
  tests/tools/tflite_run/src/tensor_dumper.cc
  tests/tools/tflite_run/src/tensor_dumper.h
  tests/tools/tflite_run/src/tensor_loader.cc
  tests/tools/tflite_run/src/tensor_loader.h
  tests/tools/tflite_run/src/tflite_run.cc
  tests/tools/tflite_vanilla_run/CMakeLists.txt
  tests/tools/tflite_vanilla_run/src/args.cc
  tests/tools/tflite_vanilla_run/src/args.h
  tests/tools/tflite_vanilla_run/src/tensor_view.h
  tests/tools/tflite_vanilla_run/src/tflite_vanilla_run.cc
Labels: PR/ready for review

#9976 [compute/cker] Fix Reduce kernel
  compute/cker/include/cker/operation/Reduce.h
  tests/scripts/list/tflite_comparator.aarch64.cpu.list
  tests/scripts/list/tflite_comparator.armv7l.cpu.list
  tests/scripts/list/tflite_comparator.x86_64.cpu.list
Labels: PR/ready for review

#9984 [infra/runtime] Prevent multiple build TFLite 2.8
  infra/nnfw/cmake/packages/TensorFlowLite-2.8.0/TensorFlowLiteConfig.cmake
Labels: PR/ready for review

#9983 [runtime/tool] Remove deprecated benchmark model tool
  infra/debian/runtime/rules
  infra/nnfw/cmake/CfgOptionFlags.cmake
  tests/tools/tflite_benchmark_model/.FORMATDENY
  tests/tools/tflite_benchmark_model/CMakeLists.txt
  tests/tools/tflite_benchmark_model/README.md
  tests/tools/tflite_benchmark_model/benchmark_tflite_model.cc
  tests/tools/tflite_benchmark_model/profile_summarizer.cc
  tests/tools/tflite_benchmark_model/stats_calculator.cc
Labels: PR/ready for review

#9986 [runtime/contrib] Remove android_tflite
  infra/nnfw/cmake/CfgOptionFlags.cmake
  infra/nnfw/cmake/options/options_aarch64-android.cmake
  runtime/contrib/android_tflite/CMakeLists.txt
  runtime/contrib/android_tflite/builtin_ops_jni.cc
Labels: PR/ready for review

#9988 [infra] Introduce ubuntu 22.04 dev dockerfile
  infra/docker/jammy/Dockerfile
Labels: PR/ready for review

#9919 [circle-execution-plan] Support execution plan for onert-micro
  compiler/circle-execution-plan/CMakeLists.txt
  compiler/circle-execution-plan/pal/TargetPlatform.h
  compiler/circle-execution-plan/src/CircleExecutionPlan.cpp
  compiler/circle-execution-plan/src/ExecutionPlanner.cpp
  compiler/circle-execution-plan/src/ExecutionPlanner.h
Labels: approval: 1

#9993 [infra/runtime] Remove TFLite 1.13.1 cmake
  infra/nnfw/cmake/packages/TensorFlowEigen-1.13.1/TensorFlowEigenConfig.cmake
  infra/nnfw/cmake/packages/TensorFlowEigen-1.13.1/TensorFlowEigenConfigVersion.cmake
  infra/nnfw/cmake/packages/TensorFlowLite-1.13.1/TensorFlowLite/CMakeLists.txt
  infra/nnfw/cmake/packages/TensorFlowLite-1.13.1/TensorFlowLiteConfig.cmake
  infra/nnfw/cmake/packages/TensorFlowLite-1.13.1/TensorFlowLiteConfigVersion.cmake
Labels: PR/ready for review

#9996 [infra/gbs] Clean up packaging directory
  packaging/FLATBUFFERS-1.12.tar.gz
  packaging/nnfw.spec
Labels: PR/ready for review, trivial

#10007 [circle-execution-plan] Add luci-interpreter runtime
  compiler/circle-execution-plan/pal/TargetPlatform.h
  compiler/circle-execution-plan/src/CircleExecutionPlan.cpp
  compiler/circle-execution-plan/src/ExecutionPlanner.cpp
  compiler/circle-execution-plan/src/ExecutionPlanner.h
Labels: approval: 1

#10005 [onert] Remove compiler state variable
  runtime/onert/core/include/compiler/Compiler.h
  runtime/onert/core/src/compiler/Compiler.cc
  runtime/onert/frontend/nnapi/compilation.cc
  runtime/onert/frontend/nnapi/wrapper/ANeuralNetworksCompilation.cc
  runtime/onert/frontend/nnapi/wrapper/ANeuralNetworksCompilation.h
Labels: PR/ready for review

#10023 [cli] remove unused variable in Makefile.template
  Makefile.template
Labels: trivial

#10010 [luci/pass] Add RemoveDuplicateConstPass to luci/pass
  compiler/luci/pass/include/luci/CircleOptimizer.h
  compiler/luci/pass/include/luci/Pass/RemoveDuplicateConstPass.h
  compiler/luci/pass/src/CircleOptimizer.cpp
  compiler/luci/pass/src/RemoveDuplicateConstPass.cpp
  compiler/luci/pass/src/RemoveDuplicateConstPass.test.cpp
Labels: approval: 2

#10043 [circle-inspect] Dump constant names
  compiler/circle-inspect/driver/Driver.cpp
  compiler/circle-inspect/src/Dump.cpp
  compiler/circle-inspect/src/Dump.h
Labels: approval: 2

#10044 [dredd-rule-lib] Add rule to check constant tensor count
  compiler/dredd-rule-lib/rule-lib.sh
Labels: approval: 2

#10045 [res] Add test for RemoveDuplicateConstPass
  res/TensorFlowLiteRecipes/Net_Duplicate_Weights_000/test.recipe
  res/TensorFlowLiteRecipes/Net_Duplicate_Weights_000/test.rule
Labels: approval: 2

#10053 [infra/runtime] Find ARMCompute header in src
  infra/nnfw/cmake/packages/ARMComputeConfig.cmake
Labels: PR/ready for review

#10046 [cir2cir-dredd-recipe-test] Add RemoveDuplicateConstPass test
  compiler/circle2circle-dredd-recipe-test/test.lst
Labels: approval: 1

#10076 [infra/npud] Enable tizen aarch64 npud build
  infra/nnfw/cmake/options/options_aarch64-tizen.cmake
Labels: PR/ready for review

#10102 [npud] Fix build fail TrixBackend.cc
  runtime/service/npud/backend/trix/TrixBackend.cc
Labels: PR/ready for review

#10111 [luci] Update minimum scale of int16 quantization
  compiler/luci/pass/src/QuantizationUtils.cpp
Labels: area/quant

#10108 [onert/test] Rename nnpackage_run to onert_run
  docs/howto/how-to-build-runtime-tizen-gbs-rpi4.md
  docs/howto/how-to-build-runtime.md
  docs/howto/how-to-use-specific-backend.md
  packaging/nnfw.spec
  runtime/libs/benchmark/include/benchmark/Result.h
  tests/scripts/README.md
  tests/scripts/benchmark.sh
  tests/scripts/benchmark_nnpkg.sh
  tests/scripts/command/nnpkg-test
  tests/tools/nnpackage_run/CMakeLists.txt
  tests/tools/nnpackage_run/README.md
  tests/tools/nnpackage_run/src/args.cc
  tests/tools/nnpackage_run/src/h5formatter.cc
  tests/tools/nnpackage_run/src/rawformatter.cc
  tools/nnpackage_tool/sth2nnpkgtc/tflite2nnpkgtc.md
  tools/pareto_profiler/README.md
  tools/pareto_profiler/estimator/brute_force_profiler.py
  tools/pareto_profiler/estimator/profile_args.py
  tools/pareto_profiler/estimator/runner.py
  tools/stab/remote.py
Labels: PR/ready for review

#10118 [onert/test] Update file & directory name
  tests/tools/onert_run/CMakeLists.txt
  tests/tools/onert_run/README.md
  tests/tools/onert_run/src/allocation.h
  tests/tools/onert_run/src/args.cc
  tests/tools/onert_run/src/args.h
  tests/tools/onert_run/src/formatter.h
  tests/tools/onert_run/src/h5formatter.cc
  tests/tools/onert_run/src/h5formatter.h
  tests/tools/onert_run/src/nnfw_util.cc
  tests/tools/onert_run/src/nnfw_util.h
  tests/tools/onert_run/src/onert_run.cc
  tests/tools/onert_run/src/randomgen.cc
  tests/tools/onert_run/src/randomgen.h
  tests/tools/onert_run/src/rawformatter.cc
  tests/tools/onert_run/src/rawformatter.h
  tests/tools/onert_run/src/types.h
Labels: PR/ready for review, approval: 1

#10125 [luci] Tidy QuantizeWithMinMaxPass.cpp
  compiler/luci/pass/src/QuantizeWithMinMaxPass.cpp
Labels: area/quant

#10123 [onert/test] Update onert_run CMake file
  infra/debian/runtime/rules
  infra/nnfw/cmake/CfgOptionFlags.cmake
  tests/tools/onert_run/CMakeLists.txt
Labels: PR/ready for review

#10124 [onert/test] Update name in onert_run source
  tests/tools/onert_run/src/allocation.h
  tests/tools/onert_run/src/args.cc
  tests/tools/onert_run/src/args.h
  tests/tools/onert_run/src/formatter.h
  tests/tools/onert_run/src/h5formatter.cc
  tests/tools/onert_run/src/h5formatter.h
  tests/tools/onert_run/src/nnfw_util.cc
  tests/tools/onert_run/src/nnfw_util.h
  tests/tools/onert_run/src/onert_run.cc
  tests/tools/onert_run/src/randomgen.cc
  tests/tools/onert_run/src/randomgen.h
  tests/tools/onert_run/src/rawformatter.cc
  tests/tools/onert_run/src/rawformatter.h
  tests/tools/onert_run/src/types.h
Labels: PR/ready for review

#10136 [infra] Set external source server ID/PWD
  infra/cmake/modules/ExternalSourceTools.cmake
Labels: PR/ready for review

#10140 [infra] Fix external download tool bug
  infra/cmake/modules/ExternalSourceTools.cmake
Labels: PR/ready for review
