Repository Samsung/ONE, pull requests merged in 2022-03, with the labels that each got.

#8517 [luci] Apply activation quantization to visitor target
  compiler/luci/pass/src/QuantizeWithMinMaxPass.cpp
Labels: area/quant

#8523 [luci] Allow backprop of qparam across the same operators
  compiler/luci/pass/src/PropagateConcatenationQparam.test.cpp
  compiler/luci/pass/src/PropagateQParamBackwardPass.cpp
  compiler/luci/pass/src/PropagateQParamBackwardPass.test.cpp
Labels: area/quant

#8522 [luci] Tidy PropagateQParamBackwardPass.cpp file
  compiler/luci/pass/src/PropagateQParamBackwardPass.cpp
Labels: area/quant, trivial

#8540 [luci] Apply QuantizeBias to visitor target
  compiler/luci/pass/src/QuantizeWithMinMaxPass.cpp
Labels: area/quant

#8543 [luci] Introduce Context of QuantizedModelVerifier
  compiler/luci/pass/src/CircleQuantizer.cpp
  compiler/luci/pass/src/QuantizedModelVerifier.cpp
  compiler/luci/pass/src/QuantizedModelVerifier.h
Labels: area/quant

#8542 [luci] Extract QuantizeWeights from QuantizeWithMinMax
  compiler/luci/pass/src/QuantizeWeights.cpp
  compiler/luci/pass/src/QuantizeWeights.h
  compiler/luci/pass/src/QuantizeWithMinMaxPass.cpp
Labels: area/quant

#8545 [luci] Remove duplicate codes in QuantizeBias
  compiler/luci/pass/src/QuantizeWithMinMaxPass.cpp
Labels: area/quant

#8552 [luci] Add min/max to new Quantize Op.
  compiler/luci/pass/src/QuantizeWithMinMaxPass.cpp
Labels: area/quant

#8553 [luci] Extract visitors to quantize activation
  compiler/luci/pass/src/QuantizeActivation.cpp
  compiler/luci/pass/src/QuantizeActivation.h
  compiler/luci/pass/src/QuantizeWithMinMaxPass.cpp
Labels: area/quant

#8556 [luci] Extract QuantizeBias from QuantizeWithMinMax.cpp
  compiler/luci/pass/src/QuantizeBias.cpp
  compiler/luci/pass/src/QuantizeBias.h
  compiler/luci/pass/src/QuantizeWithMinMaxPass.cpp
Labels: area/quant

#8555 [luci] Use layer info during quantization
  compiler/luci/pass/include/luci/Pass/QuantizeWithMinMaxPass.h
  compiler/luci/pass/src/QuantizeWithMinMaxPass.cpp
Labels: area/quant

#8558 [luci] Pass layer info to QuantizedModelVerifier
  compiler/luci/pass/src/QuantizedModelVerifier.cpp
  compiler/luci/pass/src/QuantizedModelVerifier.h
Labels: area/quant

#8579 [luci] Insert Quantize Op to mixed-precision point
  compiler/luci/pass/src/QuantizeWithMinMaxPass.cpp
Labels: area/quant

#8575 [common-artifacts] Support int16 type
  compiler/common-artifacts/src/TestDataGenerator.cpp
Labels: PR/ready for review

#8582 [nnc] Add header for unittest
  compiler/nnc/unittests/soft_backend/ModelAnalyzer.cpp
Labels: PR/ready for review

#8583 [circle-part-value-test] Support int16 type
  compiler/circle-part-value-test/part_eval_one.py
Labels: PR/ready for review

#8584 [luci-pass-value-test] Support int16 type
  compiler/luci-pass-value-test/eval_result_verifier.py
Labels: PR/ready for review

#8585 [luci-value-test] Support int16 type
  compiler/luci-value-test/luci_eval_verifier.py
  compiler/luci-value-test/luci_eval_verifier_ref.py
Labels: PR/ready for review

#8581 [luci] Remove redundant argument from PropagateQParamBackward
  compiler/luci/pass/src/PropagateConcatenationQparam.test.cpp
  compiler/luci/pass/src/PropagateQParamBackwardPass.cpp
  compiler/luci/pass/src/QuantizationUtils.h
Labels: area/quant

#8587 [infra] Use googletest v1.11
  infra/cmake/packages/GTestConfig.cmake
  infra/cmake/packages/GTestSourceConfig.cmake
  infra/nnfw/cmake/packages/GTestConfig.cmake
  packaging/GTEST.tar.gz
  packaging/nnfw.spec
Labels: PR/ready for review

#8588 [luci] Remove redundant Quantize Op in QuantizeWithMinMax
  compiler/luci/pass/src/QuantizeWithMinMaxPass.cpp
Labels: area/quant

#8589 [luci] Add test for quantization with layer info
  compiler/luci/pass/src/QuantizeWithMinMaxPass.cpp
  compiler/luci/pass/src/QuantizedModelVerifier.test.cpp
Labels: area/quant

#8592 [infra] Disable downloading googletest source code
  infra/nnfw/cmake/options/options_aarch64-tizen.cmake
  infra/nnfw/cmake/options/options_armv7hl-tizen.cmake
  infra/nnfw/cmake/options/options_armv7l-tizen.cmake
  infra/nnfw/cmake/options/options_i686-tizen.cmake
  infra/nnfw/cmake/options/options_x86_64-tizen.cmake
Labels: PR/ready for review

#8593 [infra] Fix gbs build error and warning
  infra/nnfw/cmake/packages/CpuInfoConfig.cmake
  infra/nnfw/cmake/packages/GTestConfig.cmake
Labels: PR/ready for review

#8595 [luci] Disable mixed-precision for improper Ops
  compiler/luci/pass/src/QuantizeWithMinMaxPass.cpp
Labels: area/quant

#8599 [infra] Remove BUILD_STAMP
  infra/cmake/modules/ExternalBuildTools.cmake
Labels: PR/ready for review

#8605 [infra] Use gtest package for gbs build
  packaging/nnfw.spec
Labels: PR/ready for review

#8608 [res] Add Net_Conv_Add_Mul_004 TFLite recipe
  res/TensorFlowLiteRecipes/Quant_Conv_Mul_Add_000/test.qconf.json
  res/TensorFlowLiteRecipes/Quant_Conv_Mul_Add_000/test.recipe
  res/TensorFlowLiteRecipes/Quant_Conv_Mul_Add_000/test.rule
Labels: area/quant

#8610 [circle-quantizer-dredd-recipe-test] Add quantizer dredd test
  compiler/circle-quantizer-dredd-recipe-test/CMakeLists.txt
  compiler/circle-quantizer-dredd-recipe-test/README.md
  compiler/circle-quantizer-dredd-recipe-test/requires.cmake
  compiler/circle-quantizer-dredd-recipe-test/test.lst
  compiler/circle-quantizer-dredd-recipe-test/testall.sh
Labels: area/quant

#8613 [luci] Extract layer info map code
  compiler/luci/pass/include/luci/Pass/QuantizeWithMinMaxPass.h
  compiler/luci/pass/src/QuantizeWithMinMaxPass.cpp
  compiler/luci/pass/src/QuantizedModelVerifier.cpp
  compiler/luci/pass/src/QuantizedModelVerifier.h
  compiler/luci/pass/src/helpers/LayerInfoMap.cpp
  compiler/luci/pass/src/helpers/LayerInfoMap.h
  compiler/luci/pass/src/helpers/LayerInfoMap.test.cpp
Labels: area/quant

#8611 [infra] Introduce FlatBuffers-2.0
  infra/cmake/packages/FlatBuffers-2.0/FlatBuffersConfig.cmake
  infra/cmake/packages/FlatBuffers-2.0/FlatBuffersConfigVersion.cmake
Labels: PR/ready for review

#8616 [luci] Initialize pointers with nullptr
  compiler/luci/pass/src/PropagateQParamForwardPass.test.cpp
Labels: trivial

#8615 [luci] Use layer info during FakeQuantization
  compiler/luci/pass/src/QuantizeDequantizeWeightsPass.cpp
Labels: area/quant

#8621 [luci] Add comments for quantization util functions.
  compiler/luci/pass/src/QuantizationUtils.cpp
  compiler/luci/pass/src/QuantizationUtils.h
Labels: area/quant, trivial

#8620 [res] Add quant test Quant_Conv_Mul_Add_002
  res/TensorFlowLiteRecipes/Quant_Conv_Mul_Add_002/test.qconf.json
  res/TensorFlowLiteRecipes/Quant_Conv_Mul_Add_002/test.recipe
  res/TensorFlowLiteRecipes/Quant_Conv_Mul_Add_002/test.rule
Labels: area/quant

#8617 [luci] Extract code to quantize special activation
  compiler/luci/pass/src/QuantizationUtils.cpp
  compiler/luci/pass/src/QuantizationUtils.h
  compiler/luci/pass/src/QuantizeActivation.cpp
Labels: area/quant

#8619 [res] Add quant test Quant_Conv_Mul_Add_001
  res/TensorFlowLiteRecipes/Quant_Conv_Mul_Add_001/test.qconf.json
  res/TensorFlowLiteRecipes/Quant_Conv_Mul_Add_001/test.recipe
  res/TensorFlowLiteRecipes/Quant_Conv_Mul_Add_001/test.rule
Labels: area/quant

#8609 [quantizer] Add tests for QuantizePreCheckerPass
  compiler/luci/pass/src/QuantizePreCheckerPass.test.cpp
Labels: PR/ready for review

#8623 [circle-quantizer-dredd-recipe-test] Add quant tests
  compiler/circle-quantizer-dredd-recipe-test/test.lst
Labels: area/quant

#8626 [luci] Extract function to reduce duplicate codes
  compiler/luci/pass/src/PropagateQParamBackwardPass.cpp
  compiler/luci/pass/src/QuantizationUtils.cpp
  compiler/luci/pass/src/QuantizationUtils.h
  compiler/luci/pass/src/QuantizeActivation.cpp
  compiler/luci/pass/src/QuantizeBias.cpp
  compiler/luci/pass/src/QuantizeWeights.cpp
Labels: area/quant

#8624 [luci] Propagate Quantize Op qparam forward
  compiler/luci/pass/src/PropagateQParamForwardPass.cpp
  compiler/luci/pass/src/PropagateQParamForwardPass.test.cpp
Labels: area/quant

#8627 [luci] Update opcode validation check function
  compiler/luci/import/src/CircleReader.cpp
Labels: PR/ready for review

#8625 [luci] Remove redundant checks in QuantizeActivation
  compiler/luci/pass/src/QuantizationUtils.cpp
  compiler/luci/pass/src/QuantizationUtils.h
  compiler/luci/pass/src/QuantizeActivation.cpp
Labels: area/quant

#8630 [luci] Create Quantize op by activation qtype.
  compiler/luci/pass/src/QuantizeWithMinMaxPass.cpp
Labels: area/quant

#8629 [luci] Add TODO comment
  compiler/luci/import/src/CircleReader.cpp
Labels: PR/ready for review

#8633 [infra] Change FlatBuffers install path on overlay
  infra/cmake/packages/FlatBuffers-2.0/FlatBuffersConfig.cmake
Labels: PR/ready for review

#8640 [luci] Exclude output from layer info map.
  compiler/luci/pass/src/helpers/LayerInfoMap.cpp
Labels: area/quant

#8641 [enco] Use FlatBuffers 2.0
  compiler/enco/frontend/tflite/CMakeLists.txt
Labels: PR/ready for review

#8643 [luci] Use FlatBuffers 2.0
  compiler/luci/pass/CMakeLists.txt
Labels: PR/ready for review

#8645 [mio-tflite] Use FlatBuffers 2.0
  compiler/mio-tflite/CMakeLists.txt
Labels: PR/ready for review

#8600 [luci-interpreter] Change TYPED_TEST_CASE macro
  compiler/luci-interpreter/src/kernels/ArgMax.test.cpp
  compiler/luci-interpreter/src/kernels/BatchToSpaceND.test.cpp
  compiler/luci-interpreter/src/kernels/Cast.test.cpp
  compiler/luci-interpreter/src/kernels/DepthToSpace.test.cpp
  compiler/luci-interpreter/src/kernels/FullyConnected.test.cpp
  compiler/luci-interpreter/src/kernels/L2Normalize.test.cpp
  compiler/luci-interpreter/src/kernels/LeakyRelu.test.cpp
  compiler/luci-interpreter/src/kernels/Logistic.test.cpp
  compiler/luci-interpreter/src/kernels/OneHot.test.cpp
  compiler/luci-interpreter/src/kernels/Pack.test.cpp
  compiler/luci-interpreter/src/kernels/ResizeBilinear.test.cpp
  compiler/luci-interpreter/src/kernels/ResizeNearestNeighbor.test.cpp
  compiler/luci-interpreter/src/kernels/ReverseV2.test.cpp
  compiler/luci-interpreter/src/kernels/Slice.test.cpp
  compiler/luci-interpreter/src/kernels/Softmax.test.cpp
  compiler/luci-interpreter/src/kernels/SpaceToBatchND.test.cpp
  compiler/luci-interpreter/src/kernels/SpaceToDepth.test.cpp
  compiler/luci-interpreter/src/kernels/Split.test.cpp
  compiler/luci-interpreter/src/kernels/SplitV.test.cpp
  compiler/luci-interpreter/src/kernels/Squeeze.test.cpp
  compiler/luci-interpreter/src/kernels/Transpose.test.cpp
  compiler/luci-interpreter/src/kernels/Unpack.test.cpp
Labels: PR/ready for review

#8646 [mio-tflite260] Use FlatBuffers 2.0
  compiler/mio-tflite260/CMakeLists.txt
Labels: PR/ready for review

#8647 [mir] Use FlatBuffers 2.0
  compiler/mir/src/mir_tflite_importer/CMakeLists.txt
Labels: PR/ready for review

#8648 [pota-quant] Use FlatBuffers 2.0
  compiler/pota-quantization-value-test/CMakeLists.txt
Labels: PR/ready for review

#8649 [infra] Use FlatBuffers 2.0 fo TFLite 1.13.1
  infra/cmake/packages/TensorFlowLite-1.13.1/Lite/CMakeLists.txt
  infra/cmake/packages/TensorFlowLite-1.13.1/TensorFlowLiteConfig.cmake
Labels: PR/ready for review

#8655 [one-cmds] Support mixed-precision quantization
  compiler/one-cmds/one-quantize
  compiler/one-cmds/tests/CMakeLists.txt
  compiler/one-cmds/tests/one-quantize_009.qconf.json
  compiler/one-cmds/tests/one-quantize_009.test
Labels: area/quant

#8657 [pota-quantization-value-test] Introduce qconfig test
  compiler/pota-quantization-value-test/CMakeLists.txt
  compiler/pota-quantization-value-test/test_fake_wquant_with_config.sh
  compiler/pota-quantization-value-test/test_quantization_with_config.sh
Labels: area/quant

#8669 [luci] Allow concatenating indices in quantized model
  compiler/luci/pass/src/PropagateQParamBackwardPass.cpp
  compiler/luci/pass/src/VerifyQuantizedNodeGranularity.h
  compiler/luci/pass/src/VerifyQuantizedNodeType.cpp
Labels: area/quant

#8695 [common-artifacts] Add require tflite2circle
  compiler/common-artifacts/requires.cmake
Labels: PR/ready for review

#8684 [recipe] Add recipe for Gather/SparceToDense_AddV2/Cast pattern
  res/TensorFlowLiteRecipes/Net_Gather_SparseToDense_AddV2_000/test.recipe
Labels: PR/ready for review

#8726 [luci] Update dtype of LayerInfoMap
  compiler/luci/pass/src/QuantizeDequantizeWeightsPass.cpp
  compiler/luci/pass/src/QuantizeWithMinMaxPass.cpp
  compiler/luci/pass/src/QuantizedModelVerifier.cpp
  compiler/luci/pass/src/helpers/LayerInfoMap.cpp
  compiler/luci/pass/src/helpers/LayerInfoMap.h
  compiler/luci/pass/src/helpers/LayerInfoMap.test.cpp
Labels: area/quant

#8725 [onert/test] Fix reshape test
  tests/nnfw_api/src/GenModelTests.cc
Labels: PR/ready for review, approval: 1

#8721 [circle2circle] Add Fold Gather pass to circle2circle
  compiler/circle2circle/src/Circle2Circle.cpp
Labels: PR/ready for review

#8733 [onert/frontend] Use flatc 2.0 for header generation
  runtime/onert/frontend/circle_schema/include/circle_schema_generated.h
  runtime/onert/frontend/tflite/src/tflite_schema_generated.h
Labels: PR/ready for review

#8734 [onert/frontend] Update schema version
  runtime/onert/frontend/base_loader/include/base_loader.h
  runtime/onert/frontend/circle/src/circle_loader.cc
  runtime/onert/frontend/circle_schema/include/circle_schema_generated.h
  runtime/onert/frontend/tflite/src/tflite_loader.cc
  runtime/onert/frontend/tflite/src/tflite_schema_generated.h
Labels: PR/ready for review

#8722 [one-cmds] Add Fold Gather pass to one-cmds
  compiler/one-cmds/how-to-use-one-commands.txt
  compiler/one-cmds/onelib/constant.py
Labels: PR/ready for review

#8719 [circle-quantizer-dredd-recipe-test] Add tests with multiple-output nodes
  compiler/circle-quantizer-dredd-recipe-test/test.lst
Labels: PR/ready for review

#8737 [dio-hdf5] Introduce h5-importer module
  compiler/dio-hdf5/CMakeLists.txt
  compiler/dio-hdf5/README.md
  compiler/dio-hdf5/include/dio_hdf5/HDF5Importer.h
  compiler/dio-hdf5/requires.cmake
  compiler/dio-hdf5/src/HDF5Importer.cpp
  compiler/dio-hdf5/src/HDF5Importer.test.cpp
Labels: area/quant

#8742 [circle-eval-diff] Introduce circle-eval-diff
  compiler/circle-eval-diff/CMakeLists.txt
  compiler/circle-eval-diff/README.md
  compiler/circle-eval-diff/driver/Driver.cpp
  compiler/circle-eval-diff/requires.cmake
Labels: area/quant

#8748 [record-minmax] Check input dimension before calibration
  compiler/record-minmax/src/RecordMinMax.cpp
Labels: approval: 1

#8749 [circle-eval-diff] Introduce Tensor data structure
  compiler/circle-eval-diff/CMakeLists.txt
  compiler/circle-eval-diff/requires.cmake
  compiler/circle-eval-diff/src/Tensor.cpp
  compiler/circle-eval-diff/src/Tensor.h
  compiler/circle-eval-diff/src/Tensor.test.cpp
Labels: area/quant
