Repository Samsung/ONE, pull requests merged in 2022-04, with the labels that each got.

#8770 [pota-value-test] Add test for Split with qconfig
  compiler/pota-quantization-value-test/config_files/Split_000/channel/int16/qconf.json
  compiler/pota-quantization-value-test/config_files/Split_000/channel/uint8/qconf.json
  compiler/pota-quantization-value-test/expected_outputs/Split_000_config/channel/int16/quantization/ifm_Quantize.json
  compiler/pota-quantization-value-test/expected_outputs/Split_000_config/channel/int16/quantization/ofm1.json
  compiler/pota-quantization-value-test/expected_outputs/Split_000_config/channel/int16/quantization/ofm2.json
  compiler/pota-quantization-value-test/expected_outputs/Split_000_config/channel/int16/quantization/split_dim.json
  compiler/pota-quantization-value-test/expected_outputs/Split_000_config/channel/uint8/quantization/ifm_Quantize.json
  compiler/pota-quantization-value-test/expected_outputs/Split_000_config/channel/uint8/quantization/ofm1.json
  compiler/pota-quantization-value-test/expected_outputs/Split_000_config/channel/uint8/quantization/ofm2.json
  compiler/pota-quantization-value-test/expected_outputs/Split_000_config/channel/uint8/quantization/split_dim.json
  compiler/pota-quantization-value-test/test.lst
  compiler/pota-quantization-value-test/test_inputs/Split_000_config/channel/int16/0.txt
  compiler/pota-quantization-value-test/test_inputs/Split_000_config/channel/int16/1.txt
  compiler/pota-quantization-value-test/test_inputs/Split_000_config/channel/int16/2.txt
  compiler/pota-quantization-value-test/test_inputs/Split_000_config/channel/int16/3.txt
  compiler/pota-quantization-value-test/test_inputs/Split_000_config/channel/int16/4.txt
  compiler/pota-quantization-value-test/test_inputs/Split_000_config/channel/uint8/0.txt
  compiler/pota-quantization-value-test/test_inputs/Split_000_config/channel/uint8/1.txt
  compiler/pota-quantization-value-test/test_inputs/Split_000_config/channel/uint8/2.txt
  compiler/pota-quantization-value-test/test_inputs/Split_000_config/channel/uint8/3.txt
  compiler/pota-quantization-value-test/test_inputs/Split_000_config/channel/uint8/4.txt
Labels: approval: 1

#8773 [circle-eval-diff] Enable various input dtypes
  compiler/circle-eval-diff/src/ModuleEvalDiff.cpp
Labels: area/quant

#8780 [infra/dockerfile] Fix dockerfile
  infra/docker/bionic/Dockerfile
Labels: PR/ready for review

#8777 [luci] Add pass for FakeQuantization
  compiler/luci/pass/include/luci/Pass/ConvertToFakeQuantizedModelPass.h
  compiler/luci/pass/src/ConvertToFakeQuantizedModelPass.cpp
  compiler/luci/pass/src/ConvertToFakeQuantizedModelPass.test.cpp
Labels: area/quant, approval: 2

#8771 [infra] Introduce TRIXEngine package cmake config
  infra/nnfw/cmake/packages/TRIXEngineConfig.cmake
  infra/nnfw/cmake/packages/TRIXEngineConfigVersion.cmake
  infra/nnfw/cmake/packages/TRIXEngineConfigVersion.extra.cpp
  infra/nnfw/cmake/packages/TRIXEngineConfigVersion.major.cpp
  infra/nnfw/cmake/packages/TRIXEngineConfigVersion.minor.cpp
Labels: PR/ready for review

#8782 [luci-interpreter] Support ExpandDims op in luci-interpreter
  compiler/luci-interpreter/pal/cmsisnn/KernelsToBuild.lst
  compiler/luci-interpreter/pal/linux/KernelsToBuild.lst
  compiler/luci-interpreter/pal/mcu/KernelsToBuild.lst
  compiler/luci-interpreter/src/kernels/ExpandDims.cpp
  compiler/luci-interpreter/src/kernels/ExpandDims.h
  compiler/luci-interpreter/src/kernels/ExpandDims.test.cpp
  compiler/luci-interpreter/src/loader/nodes/ExpandDims.cpp
Labels: PR/ready for review

#8783 [luci] Support fake quantization option
  compiler/luci/pass/include/luci/CircleQuantizer.h
  compiler/luci/pass/src/CircleQuantizer.cpp
Labels: area/quant

#8792 [circle-quantizer] Add fake quantization option
  compiler/circle-quantizer/src/CircleQuantizer.cpp
Labels: area/quant

#8794 [nnpackage] Add model type
  nnpackage/spec/10_packaging_and_manifest.md
Labels: PR/ready for review

#8793 [onert] Merge LoweredGraph constructor code
  runtime/onert/core/include/compiler/LoweredGraph.h
  runtime/onert/core/src/compiler/LoweredGraph.cc
Labels: PR/ready for review, approval: 2

#8801 [luci] Support Add in Fake Quantization
  compiler/luci/pass/src/ConvertToFakeQuantizedModelPass.cpp
Labels: area/quant

#8802 [res] Add Quant_Add_000 dredd test.
  res/TensorFlowLiteRecipes/Quant_Add_000/test.recipe
  res/TensorFlowLiteRecipes/Quant_Add_000/test.rule
Labels: area/quant

#8809 [circle-quantizer-dredd] Support fake quantization test
  compiler/circle-quantizer-dredd-recipe-test/CMakeLists.txt
  compiler/circle-quantizer-dredd-recipe-test/test.lst
Labels: area/quant

#8799 [onert/acl_common] Merge BackendContext
  runtime/onert/backend/acl_cl/BackendContext.cc
  runtime/onert/backend/acl_cl/BackendContext.h
  runtime/onert/backend/acl_common/AclBackendContext.h
  runtime/onert/backend/acl_neon/BackendContext.cc
  runtime/onert/backend/acl_neon/BackendContext.h
Labels: PR/ready for review, approval: 2

#8818 [infra] Install python 3.6 package on bionic dockerfile
  infra/docker/bionic/Dockerfile
Labels: PR/ready for review

#8812 [onert/cl_common] Introduce cl-common library
  runtime/onert/backend/CMakeLists.txt
  runtime/onert/backend/acl_common/AclBackendContext.h
  runtime/onert/backend/acl_common/CMakeLists.txt
  runtime/onert/backend/cl_common/CMakeLists.txt
  runtime/onert/backend/cl_common/include/cl_common/BackendContext.h
  runtime/onert/backend/gpu_cl/BackendContext.cc
  runtime/onert/backend/gpu_cl/BackendContext.h
  runtime/onert/backend/gpu_cl/CMakeLists.txt
Labels: PR/ready for review, approval: 2

#8836 [nnpackage_tool] Update model2nnpkg for trix
  tools/nnpackage_tool/model2nnpkg/README.md
  tools/nnpackage_tool/model2nnpkg/model2nnpkg.sh
Labels: area/onert

#8841 [docs/howto] Fix broken link in how-to-build-runtime
  docs/howto/how-to-build-runtime.md
Labels: area/onert, approval: 1

#8840 [infra] Change tizen package server name
  infra/nnfw/config/gbs.conf
Labels: PR/ready for review, approval: 1

#8848 [infra] Change trix-engine lib name
  infra/nnfw/cmake/packages/TRIXEngineConfig.cmake
Labels: PR/ready for review, approval: 2

#8845 [infra/script] Pass build option
  infra/scripts/docker_build_test_x64.sh
Labels: PR/ready for review

#8860 [onert] Introduce TRIX backend
  runtime/onert/backend/CMakeLists.txt
  runtime/onert/backend/trix/Backend.h
  runtime/onert/backend/trix/BackendContext.cc
  runtime/onert/backend/trix/BackendContext.h
  runtime/onert/backend/trix/CMakeLists.txt
  runtime/onert/backend/trix/Config.cc
  runtime/onert/backend/trix/Config.h
  runtime/onert/backend/trix/DevContext.h
  runtime/onert/backend/trix/KernelGenerator.cc
  runtime/onert/backend/trix/KernelGenerator.h
  runtime/onert/backend/trix/Tensor.h
  runtime/onert/backend/trix/TensorBuilder.h
  runtime/onert/backend/trix/trix.cc
Labels: area/onert

#8866 [onert/gbs] Install trix-engine-dev package
  packaging/nnfw.spec
Labels: PR/ready for review

#8864 [onert] Introduce common CalculateActivationRange
  runtime/onert/backend/cpu/ops/OperationUtils.cc
  runtime/onert/backend/cpu/ops/OperationUtils.h
  runtime/onert/backend/ruy/ops/OperationUtils.h
  runtime/onert/backend/xnnpack/ops/OperationUtils.h
  runtime/onert/core/include/util/CalculateActivationRange.h
Labels: PR/ready for review

#8868 [onert] Revisit OperationDumper
  runtime/onert/core/src/ir/OperationDumper.cc
Labels: PR/ready for review

#8872 [onert] Merge LifetimeMap generation
  runtime/onert/backend/acl_cl/Optimizer.cc
  runtime/onert/backend/acl_common/AclSubTensorAnalyzer.h
  runtime/onert/backend/acl_common/AclTensorBuilder.h
  runtime/onert/backend/acl_neon/Optimizer.cc
  runtime/onert/backend/cl_common/CMakeLists.txt
  runtime/onert/backend/cl_common/include/cl_common/LifetimeMap.h
  runtime/onert/backend/cl_common/include/cl_common/ParentInfo.h
  runtime/onert/backend/cl_common/src/LifetimeMap.cc
  runtime/onert/backend/gpu_cl/ParentInfo.h
  runtime/onert/backend/gpu_cl/TensorBuilder.cc
  runtime/onert/backend/gpu_cl/TensorBuilder.h
Labels: PR/ready for review

#8880 [onert] Revisit tensorinfo API implementation
  runtime/onert/api/src/nnfw_api_internal.cc
Labels: PR/ready for review

#8882 [onert] Introduce trix loader
  infra/nnfw/cmake/CfgOptionFlags.cmake
  runtime/onert/api/CMakeLists.txt
  runtime/onert/frontend/trix/CMakeLists.txt
  runtime/onert/frontend/trix/include/trix_loader.h
  runtime/onert/frontend/trix/src/trix_loader.cc
  runtime/onert/frontend/trix/src/trix_loader_dummy.cc
Labels: area/onert

#8884 [onert/api] Support trix model type
  runtime/onert/api/src/nnfw_api_internal.cc
Labels: area/onert

#8879 [onert] Introduce backend context preparation functions
  runtime/onert/core/src/compiler/ExecutorFactory.cc
  runtime/onert/core/src/compiler/ExecutorFactory.h
Labels: PR/ready for review

#8883 [onert] Introduce getActivation in OperationFactory
  runtime/onert/frontend/nnapi/wrapper/OperationFactory.cc
Labels: PR/ready for review

#8873 [onert] Add BulkLayer on TRIX backend
  runtime/onert/backend/trix/DevContext.h
  runtime/onert/backend/trix/KernelGenerator.cc
  runtime/onert/backend/trix/KernelGenerator.h
  runtime/onert/backend/trix/ops/BulkLayer.cc
  runtime/onert/backend/trix/ops/BulkLayer.h
Labels: area/onert

#8885 [onert] Revisit generator map in OperationFactory
  packaging/nnapi_test_generated.tar.gz
  runtime/onert/frontend/nnapi/wrapper/OperationFactory.cc
  tests/nnapi/specs/V1_2/equal_broadcast_float_nnfw.mod.py
Labels: PR/ready for review

#8886 [onert] Introduce getCustomOpAttrMap in BaseLoader
  runtime/onert/frontend/base_loader/include/base_loader.h
Labels: PR/ready for review

#8892 [onert] Introduce QUANT_INT16_SYMM type
  runtime/onert/core/include/ir/DataType.h
  runtime/onert/core/src/ir/DataType.cc
Labels: area/onert

#8901 [onert/test] Revisit Equal test
  tests/nnfw_api/src/one_op_tests/Equal.cc
Labels: PR/ready for review

#8906 [onert] Support Q16 SYMM model on TRIX Backend
  runtime/onert/backend/trix/DevContext.h
  runtime/onert/core/src/exec/IPermuteFunction.h
  runtime/onert/frontend/trix/src/trix_loader.cc
Labels: PR/ready for review, area/onert

#8905 [nnfw_api] Introduce NNFW_TYPE_TENSOR_QUANT16_SYMM_SIGNED type
  runtime/onert/api/include/nnfw.h
  runtime/onert/api/src/nnfw_api.cc
  runtime/onert/api/src/nnfw_api_internal.cc
  tests/tools/nnpackage_run/src/h5formatter.cc
  tests/tools/nnpackage_run/src/nnfw_util.cc
  tests/tools/nnpackage_run/src/nnpackage_run.cc
  tests/tools/nnpackage_run/src/randomgen.cc
  tests/tools/tflite_comparator/src/tflite_comparator.cc
Labels: PR/ready for review, area/onert

#8934 [onert/trix] Build on higher version
  runtime/onert/backend/trix/CMakeLists.txt
  runtime/onert/frontend/trix/CMakeLists.txt
Labels: PR/ready for review

#8936 [onert/ndarray] Add more NDArray tests
  runtime/libs/ndarray/test/ndarray_test.cpp
Labels: PR/ready for review

#8937 [onert] Add NotEqual Tests in one_op_tests
  tests/nnfw_api/src/CircleGen.cc
  tests/nnfw_api/src/CircleGen.h
  tests/nnfw_api/src/one_op_tests/NotEqual.cc
Labels: PR/ready for review, area/onert

#8939 [onert] Add Less Tests in one_op_tests
  tests/nnfw_api/src/one_op_tests/Less.cc
Labels: area/onert

#8942 [arser] Set type default value
  compiler/arser/include/arser/arser.h
Labels: PR/ready for review

#8946 [onert] Add Greater Tests in one_op_tests
  tests/nnfw_api/src/CircleGen.cc
  tests/nnfw_api/src/CircleGen.h
  tests/nnfw_api/src/one_op_tests/Greater.cc
Labels: PR/ready for review, area/onert

#8943 [onert] Add LessEqual Tests in one_op_tests
  tests/nnfw_api/src/CircleGen.cc
  tests/nnfw_api/src/CircleGen.h
  tests/nnfw_api/src/one_op_tests/LessEqual.cc
Labels: PR/ready for review, area/onert

#8954 [onert/ndarray] Add more tests
  infra/command/gen-coverage-report
  runtime/libs/ndarray/test/CMakeLists.txt
  runtime/libs/ndarray/test/ndarray_test.cpp
Labels: PR/ready for review

#8963 [onert] Add more test for Cast
  runtime/onert/frontend/base_loader/include/base_loader.h
  tests/nnfw_api/src/one_op_tests/Cast.cc
Labels: PR/ready for review, area/onert

#8975 [onert] Fix typo in Add negative test
  tests/nnfw_api/src/one_op_tests/Add.cc
Labels: PR/ready for review, area/onert, approval: 1

#8972 [onert/test] Add Reader and View test
  runtime/onert/core/src/exec/feature/nhwc/View.h
  runtime/onert/test/CMakeLists.txt
  runtime/onert/test/core/exec/feature/MockTensor.h
  runtime/onert/test/core/exec/feature/nchw/Reader.cc
  runtime/onert/test/core/exec/feature/nchw/View.cc
  runtime/onert/test/core/exec/feature/nhwc/Reader.cc
  runtime/onert/test/core/exec/feature/nhwc/View.cc
Labels: PR/ready for review

#8971 [onert] Add tests for IndexEnumerator
  .ahub/tcchecker-tca/config.yaml
  runtime/libs/misc/CMakeLists.txt
  runtime/libs/misc/test/CMakeLists.txt
  runtime/libs/misc/test/IndexEnumerator.test.cpp
Labels: PR/ready for review, area/onert

#9015 [circle-eval-diff] Add MAPE metric printer
  compiler/circle-eval-diff/driver/Driver.cpp
  compiler/circle-eval-diff/include/CircleEvalDiff.h
  compiler/circle-eval-diff/src/CircleEvalDiff.cpp
  compiler/circle-eval-diff/src/MetricPrinter.cpp
  compiler/circle-eval-diff/src/MetricPrinter.h
  compiler/circle-eval-diff/src/MetricPrinter.test.cpp
Labels: area/quant

#9016 [nnpackage_run] Support multiple input for load:raw option
  tests/tools/nnpackage_run/src/rawformatter.cc
Labels: PR/ready for review, area/onert

#9022 [infra] Enable nnpackage_run build on x64 runtime build
  infra/scripts/docker_build_test_x64.sh
Labels: PR/ready for review

#9031 [luci] Support float32 input/output in quantization
  compiler/luci/pass/src/CircleQuantizer.cpp
  compiler/luci/pass/src/QuantizeWithMinMaxPass.cpp
Labels: area/quant

#9037 [res] Add recipes/rules for circle-quantizer-dredd-test
  res/TensorFlowLiteRecipes/Quant_Conv_000/test.recipe
  res/TensorFlowLiteRecipes/Quant_Conv_000/test.rule
  res/TensorFlowLiteRecipes/Quant_Conv_001/test.recipe
  res/TensorFlowLiteRecipes/Quant_Conv_001/test.rule
  res/TensorFlowLiteRecipes/Quant_Conv_002/test.recipe
  res/TensorFlowLiteRecipes/Quant_Conv_002/test.rule
Labels: area/quant

#9036 [one-cmds] Support float32 input/output in one-quantize
  compiler/one-cmds/one-quantize
Labels: area/quant

#9035 [circle-quantizer] Support float32 input/output type
  compiler/circle-quantizer/src/CircleQuantizer.cpp
Labels: area/quant

#9038 [luci] Support more Ops in ConverToFakeQuantizedModelPass.
  compiler/luci/pass/src/ConvertToFakeQuantizedModelPass.cpp
Labels: area/quant

#9041 [one-cmds] Update one-quantize_neg_019 test
  compiler/one-cmds/tests/one-quantize_neg_019.test
Labels: area/quant

#9039 [circle-quantizer-dredd] Add tests for fp32 input/output
  compiler/circle-quantizer-dredd-recipe-test/CMakeLists.txt
  compiler/circle-quantizer-dredd-recipe-test/test.lst
Labels: area/quant

#9034 [nnpackage_run] Support multiple raw output dump
  tests/tools/nnpackage_run/src/rawformatter.cc
Labels: PR/ready for review, area/onert

#9040 [onert/test] Fix mixed test
  infra/scripts/test_ubuntu_runtime_mixed.sh
Labels: PR/ready for review, approval: 2

#9045 [circle-eval-diff] Add comments for metric
  compiler/circle-eval-diff/include/CircleEvalDiff.h
Labels: area/quant

#9048 [debian] Update version to 1.20.0
  infra/debian/compiler/changelog
  infra/debian/runtime/changelog
Labels: approval: 1

#9058 [res] Add resource to test mixed-precision of ADD
  res/TensorFlowLiteRecipes/Quant_Add_001/test.qconf.json
  res/TensorFlowLiteRecipes/Quant_Add_001/test.recipe
  res/TensorFlowLiteRecipes/Quant_Add_001/test.rule
  res/TensorFlowLiteRecipes/Quant_Add_002/test.qconf.json
  res/TensorFlowLiteRecipes/Quant_Add_002/test.recipe
  res/TensorFlowLiteRecipes/Quant_Add_002/test.rule
Labels: area/quant

#9059 [quantizer-dredd] Add mixed-quant test for ADD
  compiler/circle-quantizer-dredd-recipe-test/test.lst
Labels: area/quant

#9047 [onert] update version to 1.21.0
  docs/conf.py
  packaging/nnfw.spec
  runtime/contrib/android/api/build.gradle
  runtime/onert/api/include/nnfw_version.h
Labels: PR/ready for review

#9060 [debian] Fix changelog trailer line
  infra/debian/compiler/changelog
Labels: PR/ready for review

#9062 [luci/pass] Support more dtype for FoldDequantizePass
  compiler/luci/pass/src/FoldDequantizePass.cpp
  compiler/luci/pass/src/FoldDequantizePass.test.cpp
Labels: DRAFT

#9066 [circle-eval-diff] Use different modules for interpretation
  compiler/circle-eval-diff/src/ModuleEvalDiff.cpp
Labels: area/quant

#9065 [circle-eval-diff] Print multiple metrics at once
  compiler/circle-eval-diff/driver/Driver.cpp
  compiler/circle-eval-diff/include/CircleEvalDiff.h
  compiler/circle-eval-diff/src/CircleEvalDiff.cpp
  compiler/circle-eval-diff/src/ModuleEvalDiff.cpp
  compiler/circle-eval-diff/src/ModuleEvalDiff.h
Labels: area/quant

#9067 [onert/ndarray] Remove workaround for C++11
  runtime/libs/ndarray/CMakeLists.txt
  runtime/libs/ndarray/include/ndarray/Array.h
  runtime/libs/ndarray/src/detail/cxx14.h
Labels: PR/ready for review

#9071 [onert/misc] Revisit unittest
  runtime/libs/misc/CMakeLists.txt
  runtime/libs/misc/src/tensor/IndexEnumerator.test.cpp
  runtime/libs/misc/src/tensor/IndexIterator.test.cpp
  runtime/libs/misc/test/CMakeLists.txt
Labels: PR/ready for review
