Repository Samsung/ONE, pull requests merged in 2022-06, with the labels that each got.

#9223 [infra] Exclude more test code on coverage
  infra/command/gen-coverage-report
Labels: PR/ready for review

#9231 [infra] Fix compiler coverage report
  infra/scripts/unittest_compiler_xml.sh
Labels: PR/ready for review

#9242 [one-cmds] Give qconfig when quantize_dequantize
  compiler/one-cmds/one-quantize
Labels: area/quant

#9252 [nnpackage] Update schema
  nnpackage/schema/circle_schema.fbs
Labels: PR/ready for review

#9249 [onert/misc] Resolve string helper warning
  runtime/libs/misc/include/misc/string_helpers.h
  runtime/libs/misc/src/string_helpers.test.cpp
Labels: PR/ready for review

#9251 [one-cmds] Use default dtype/granularity in qconfig
  compiler/one-cmds/one-quantize
  compiler/one-cmds/tests/one-quantize_013.qconf.json
  compiler/one-cmds/tests/one-quantize_013.test
  compiler/one-cmds/tests/one-quantize_neg_020.test
Labels: area/quant

#9261 [circle-eval-diff] Support directory input
  compiler/circle-eval-diff/driver/Driver.cpp
  compiler/circle-eval-diff/src/InputDataLoader.cpp
  compiler/circle-eval-diff/src/InputDataLoader.h
Labels: PR/ready for review

#9272 [onert/api] Revise assert
  runtime/onert/api/src/nnfw_api_internal.cc
Labels: PR/ready for review, area/onert

#9274 [onert/test] Update prepare-model
  tests/scripts/command/prepare-model
Labels: PR/ready for review

#9273 [one-cmds] Add one-quantize test
  compiler/one-cmds/tests/one-quantize_014.test
Labels: PR/ready for review

#9278 [onert/test] Rename TEST_CASE to TEST_SUITE
  runtime/onert/core/src/compiler/HEScheduler.test.cc
  tests/nnfw_api/src/one_op_tests/ArgMinMax.test.cc
  tests/nnfw_api/src/one_op_tests/AveragePool2D.test.cc
  tests/nnfw_api/src/one_op_tests/Concat.test.cc
  tests/nnfw_api/src/one_op_tests/DepthToSpace.test.cc
  tests/nnfw_api/src/one_op_tests/DepthwiseConv2D.test.cc
  tests/nnfw_api/src/one_op_tests/Fill.test.cc
  tests/nnfw_api/src/one_op_tests/If.test.cc
  tests/nnfw_api/src/one_op_tests/Pad.test.cc
  tests/nnfw_api/src/one_op_tests/Reduce.test.cc
  tests/nnfw_api/src/one_op_tests/ResizeBilinear.test.cc
  tests/nnfw_api/src/one_op_tests/Slice.test.cc
  tests/nnfw_api/src/one_op_tests/Softmax.test.cc
  tests/nnfw_api/src/one_op_tests/While.test.cc
Labels: PR/ready for review

#9276 [infra] Use mirror server for external source download
  infra/cmake/packages/CMSISSource-5.8.0/CMSISSourceConfig.cmake
  infra/cmake/packages/CaffeSourceConfig.cmake
  infra/cmake/packages/FarmhashSourceConfig.cmake
  infra/cmake/packages/FlatBuffersSource-2.0/FlatBuffersSourceConfig.cmake
  infra/cmake/packages/GEMMLowpSourceConfig.cmake
  infra/cmake/packages/GFlagsSourceConfig.cmake
  infra/cmake/packages/GTestSourceConfig.cmake
  infra/cmake/packages/HDF5SourceConfig.cmake
  infra/cmake/packages/JsoncppSourceConfig.cmake
  infra/cmake/packages/MbedOSSource-6.15/MbedOSSourceConfig.cmake
  infra/cmake/packages/NEON2SSESourceConfig.cmake
  infra/cmake/packages/ONNXSource-1.4.1/ONNXSourceConfig.cmake
  infra/cmake/packages/ONNXSource-1.6.0/ONNXSourceConfig.cmake
  infra/cmake/packages/OouraFFTSourceConfig.cmake
  infra/cmake/packages/ProtobufSourceConfig.cmake
  infra/cmake/packages/Pybind11SourceConfig.cmake
  infra/cmake/packages/PytorchSourceConfig.cmake
  infra/cmake/packages/TensorFlowEigenSource-2.1.0/TensorFlowEigenSourceConfig.cmake
  infra/cmake/packages/TensorFlowGEMMLowpSource-2.1.0/TensorFlowGEMMLowpSourceConfig.cmake
  infra/cmake/packages/TensorFlowGEMMLowpSource-2.3.0/TensorFlowGEMMLowpSourceConfig.cmake
  infra/cmake/packages/TensorFlowGEMMLowpSource-2.6.0/TensorFlowGEMMLowpSourceConfig.cmake
  infra/cmake/packages/TensorFlowGEMMLowpSource-2.8.0/TensorFlowGEMMLowpSourceConfig.cmake
  infra/cmake/packages/TensorFlowGpuSourceConfig.cmake
  infra/cmake/packages/TensorFlowRuySource-2.3.0/TensorFlowRuySourceConfig.cmake
  infra/cmake/packages/TensorFlowRuySource-2.6.0/TensorFlowRuySourceConfig.cmake
  infra/cmake/packages/TensorFlowSource-1.14/TensorFlowSourceConfig.cmake
  infra/cmake/packages/TensorFlowSource-2.1.0/TensorFlowSourceConfig.cmake
  infra/cmake/packages/TensorFlowSource-2.2.0/TensorFlowSourceConfig.cmake
  infra/cmake/packages/TensorFlowSource-2.3.0-rc0Config.cmake
  infra/cmake/packages/TensorFlowSource-2.3.0/TensorFlowSourceConfig.cmake
  infra/cmake/packages/TensorFlowSource-2.6.0/TensorFlowSourceConfig.cmake
  infra/cmake/packages/TensorFlowSource-2.8.0/TensorFlowSourceConfig.cmake
Labels: PR/ready for review

#9277 [onert] Get CompilerOptions out of Compiler
  runtime/onert/api/src/nnfw_api_internal.cc
  runtime/onert/api/src/nnfw_api_internal.h
  runtime/onert/core/include/compiler/Compiler.h
  runtime/onert/core/src/compiler/Compiler.cc
  runtime/onert/core/src/compiler/HEScheduler.test.cc
  runtime/onert/core/src/exec/Execution.test.cc
  runtime/onert/frontend/nnapi/wrapper/ANeuralNetworksCompilation.cc
  runtime/onert/frontend/nnapi/wrapper/ANeuralNetworksCompilation.h
Labels: PR/ready for review, area/onert

#9268 [infra/gbs] Use pkgconfig
  packaging/nnfw.spec
Labels: PR/ready for review

#9271 [onert/api] Create Compiler in prepare(), not in load...()
  runtime/onert/api/src/nnfw_api_internal.cc
Labels: PR/ready for review, area/onert

#9289 [onert/api] Remove _compiler from nnfw_session
  runtime/onert/api/src/nnfw_api_internal.cc
  runtime/onert/api/src/nnfw_api_internal.h
  runtime/onert/core/src/compiler/Compiler.cc
Labels: PR/ready for review, area/onert

#9291 [onert] Introduce CompilerArtifact
  runtime/onert/api/src/nnfw_api_internal.cc
  runtime/onert/api/src/nnfw_api_internal.h
  runtime/onert/core/include/compiler/Compiler.h
  runtime/onert/core/src/compiler/Compiler.cc
  runtime/onert/core/src/exec/Execution.test.cc
  runtime/onert/frontend/nnapi/wrapper/ANeuralNetworksCompilation.cc
  runtime/onert/frontend/nnapi/wrapper/ANeuralNetworksCompilation.h
Labels: PR/ready for review

#9301 [onert/api] Remove tracing_ctx from nnfw_session
  runtime/onert/api/src/nnfw_api_internal.cc
Labels: PR/ready for review, area/onert

#9302 [onert/nnapi] Remove tracing_ctx from ANeuralNetworkCompilation
  runtime/onert/frontend/nnapi/wrapper/ANeuralNetworksCompilation.cc
  runtime/onert/frontend/nnapi/wrapper/ANeuralNetworksCompilation.h
Labels: PR/ready for review, area/onert

#9305 [infra] Ignore commit message check on draft
  .github/workflows/check-pr-commit.yml
Labels: PR/ready for review

#9298 [onert] Add comment about graph copy on lowering
  runtime/onert/core/include/compiler/LoweredGraph.h
Labels: PR/ready for review

#9306 [onert] Remove unused member in nnfw_session
  runtime/onert/api/src/nnfw_api_internal.h
Labels: PR/ready for review

#9293 [onert] Rename subgraphs to model
  runtime/onert/api/src/nnfw_api_internal.cc
  runtime/onert/api/src/nnfw_api_internal.h
  runtime/onert/core/include/compiler/Compiler.h
  runtime/onert/core/include/ir/Graph.h
  runtime/onert/core/include/ir/Model.h
  runtime/onert/core/include/util/TracingCtx.h
  runtime/onert/core/src/compiler/Compiler.cc
  runtime/onert/core/src/compiler/HEScheduler.test.cc
  runtime/onert/core/src/compiler/ShapeValidator.cc
  runtime/onert/core/src/exec/Execution.test.cc
  runtime/onert/core/src/interp/InterpExecutor.test.cc
  runtime/onert/frontend/base_loader/include/base_loader.h
  runtime/onert/frontend/circle/include/circle_loader.h
  runtime/onert/frontend/circle/src/circle_loader.cc
  runtime/onert/frontend/nnapi/wrapper/ANeuralNetworksCompilation.cc
  runtime/onert/frontend/nnapi/wrapper/ANeuralNetworksCompilation.h
  runtime/onert/frontend/nnapi/wrapper/ANeuralNetworksModel.cc
  runtime/onert/frontend/nnapi/wrapper/ANeuralNetworksModel.h
  runtime/onert/frontend/tflite/include/tflite_loader.h
  runtime/onert/frontend/tflite/src/tflite_loader.cc
  runtime/onert/frontend/trix/include/trix_loader.h
  runtime/onert/frontend/trix/src/trix_loader.cc
  runtime/onert/frontend/trix/src/trix_loader_dummy.cc
Labels: PR/ready for review, area/onert

#9309 [onert/ir] Remove a typo in comment
  runtime/onert/core/include/ir/Index.h
Labels: area/onert, approval: 1

#9312 [onert] Use copy of graph in interpreter
  runtime/onert/core/src/interp/InterpExecutor.h
Labels: PR/ready for review

#9307 [onert] Revisit TracingCtx constructor
  runtime/onert/core/include/util/TracingCtx.h
  runtime/onert/core/src/compiler/Compiler.cc
Labels: PR/ready for review

#9311 [infra] Change using pthread option
  infra/nnfw/cmake/ApplyCompileFlags.cmake
  infra/nnfw/cmake/buildtool/config/config_aarch64-android.cmake
  infra/nnfw/cmake/buildtool/config/config_linux.cmake
  infra/nnfw/cmake/buildtool/config/config_x86_64-darwin.cmake
Labels: PR/ready for review

#9308 [onert] Remove model reference in graph
  runtime/onert/core/include/ir/Graph.h
  runtime/onert/core/src/compiler/Compiler.cc
  runtime/onert/core/src/compiler/ShapeValidator.cc
  runtime/onert/core/src/interp/InterpExecutor.test.cc
Labels: PR/ready for review

#9331 [luci] Remove return with std::move
  compiler/luci/partition/src/PartitionIR.cpp
  compiler/luci/partition/src/PartitionMerge.cpp
  compiler/luci/partition/src/PartitionPGroups.cpp
  compiler/luci/partition/src/PartitionPModules.cpp
  compiler/luci/pass/src/QuantizationUtils.cpp
Labels: PR/ready for review

#9329 [coco] Remove return with std::move
  compiler/coco/core/src/IR/Module.cpp
  compiler/coco/generic/src/IR/Data.cpp
Labels: PR/ready for review

#9330 [enco] Remove return with std::move
  compiler/enco/core/src/CppGen/Host.cpp
  compiler/enco/core/src/CppGen/Subnet.cpp
  compiler/enco/core/src/Transforms/Split.cpp
Labels: PR/ready for review

#9332 [moco] Remove return with std::move
  compiler/moco/import/src/Importer.cpp
Labels: PR/ready for review

#9327 [common-artifact] Support on ubuntu 20.04
  compiler/common-artifacts/CMakeLists.txt
Labels: PR/ready for review

#9333 [infra/onert] Set default ACL build type to release
  infra/nnfw/cmake/CfgOptionFlags.cmake
  infra/nnfw/cmake/packages/ARMComputeConfig.cmake
Labels: PR/ready for review

#9337 [onert] Rename CompilerOptions(Model&) to fromGlobalConfig(Model&)
  runtime/onert/api/src/nnfw_api_internal.cc
  runtime/onert/core/include/compiler/Compiler.h
  runtime/onert/core/src/compiler/Compiler.cc
  runtime/onert/core/src/compiler/HEScheduler.test.cc
  runtime/onert/core/src/exec/Execution.test.cc
  runtime/onert/frontend/nnapi/wrapper/ANeuralNetworksCompilation.cc
Labels: PR/ready for review, area/onert

#9338 [onert] Remove model from ManualSchedulerOptions::setBackendMap
  runtime/onert/api/src/nnfw_api_internal.cc
  runtime/onert/core/include/compiler/Compiler.h
  runtime/onert/core/src/compiler/Compiler.cc
  runtime/onert/core/src/compiler/HEScheduler.test.cc
  runtime/onert/core/src/exec/Execution.test.cc
  runtime/onert/frontend/nnapi/wrapper/ANeuralNetworksCompilation.cc
Labels: PR/ready for review, area/onert

#9335 [onert/api] create CompilerOptions in try block
  runtime/onert/api/src/nnfw_api_internal.cc
Labels: PR/ready for review, area/onert

#9341 [onert/api] Get file extension by searching ., not by fixed length
  runtime/onert/api/src/nnfw_api_internal.cc
Labels: PR/ready for review, area/onert

#9342 [onert] Revisit session creation
  runtime/onert/api/src/nnfw_api.cc
  runtime/onert/api/src/nnfw_api_internal.cc
  runtime/onert/api/src/nnfw_api_internal.h
Labels: PR/ready for review

#9346 [onert] Remove an unused local variable
  runtime/onert/core/src/dumper/dot/DotDumper.cc
Labels: PR/ready for review

#9347 [onert/api] Introduce loadModel helper
  runtime/onert/api/src/nnfw_api_internal.cc
Labels: PR/ready for review, area/onert

#9343 [onert] Refine ShapeValidator
  runtime/onert/core/src/compiler/ShapeValidator.cc
  runtime/onert/core/src/compiler/ShapeValidator.h
Labels: PR/ready for review, area/onert

#9363 [infra] Revisit linking sysroot flag setting
  infra/nnfw/cmake/buildtool/cross/toolchain_aarch64-linux.cmake
  infra/nnfw/cmake/buildtool/cross/toolchain_aarch64-tizen.cmake
  infra/nnfw/cmake/buildtool/cross/toolchain_armv7l-linux.cmake
  infra/nnfw/cmake/buildtool/cross/toolchain_armv7l-tizen.cmake
Labels: PR/ready for review

#9364 [luci] Set quantized dimension of CWQ bias
  compiler/luci/pass/src/QuantizeBias.cpp
  compiler/luci/pass/src/QuantizeBias.test.cpp
Labels: area/quant
