Repository Samsung/ONE, pull requests merged in 2022-05, with the labels that each got.

#9082 [luci] Introduce pass to remove redundant Dequantize Ops
  compiler/luci/pass/include/luci/Pass/RemoveRedundantDequantizePass.h
  compiler/luci/pass/src/RemoveRedundantDequantizePass.cpp
  compiler/luci/pass/src/RemoveRedundantDequantizePass.test.cpp
Labels: area/quant

#9083 [luci] Support more ops in fake quantization.
  compiler/luci/pass/src/ConvertToFakeQuantizedModelPass.cpp
Labels: area/quant

#9089 [luci] Remove redundant dequant in fake quantization
  compiler/luci/pass/src/CircleQuantizer.cpp
Labels: area/quant

#9091 [onert/cker] Move unittest
  .ahub/tcchecker-tca/config.yaml
  compute/cker/CMakeLists.txt
  compute/cker/src/Range.test.cc
  compute/test/CMakeLists.txt
Labels: PR/ready for review

#9095 [one-cmds] Add optimization option to onecc
  compiler/one-cmds/onecc
  compiler/one-cmds/tests/OONECC_024.cfg
  compiler/one-cmds/tests/onecc_024.cfg
  compiler/one-cmds/tests/onecc_024.test
  compiler/one-cmds/tests/onecc_neg_009.test
  compiler/one-cmds/tests/onecc_neg_010.test
Labels: PR/ready for review

#9088 [circle-eval-diff] Support MPEIR metric
  compiler/circle-eval-diff/driver/Driver.cpp
  compiler/circle-eval-diff/include/CircleEvalDiff.h
  compiler/circle-eval-diff/src/CircleEvalDiff.cpp
  compiler/circle-eval-diff/src/MetricPrinter.cpp
  compiler/circle-eval-diff/src/MetricPrinter.h
  compiler/circle-eval-diff/src/MetricPrinter.test.cpp
Labels: area/quant

#9094 [onert] Move core/util unittest
  runtime/onert/core/CMakeLists.txt
  runtime/onert/core/include/util/ObjectManager.h
  runtime/onert/core/src/util/Index.test.cc
  runtime/onert/core/src/util/ObjectManager.test.cc
  runtime/onert/core/src/util/ShapeInference.test.cc
Labels: PR/ready for review

#9098 [circle-eval-diff] Throw exception for dtype/shape mismatch
  compiler/circle-eval-diff/src/MetricPrinter.cpp
Labels: area/quant

#9093 [onert] Change getBuiltin() type
  runtime/onert/core/include/compiler/BackendManager.h
  runtime/onert/core/src/compiler/BackendManager.cc
  runtime/onert/core/src/compiler/ExecutorFactory.cc
  runtime/onert/core/src/compiler/HEScheduler.h
  runtime/onert/core/src/compiler/pass/PermutationInsertionPass.cc
Labels: PR/ready for review, approval: 2

#9100 [onert] Move core/compiler unittest
  runtime/onert/core/src/compiler/HEScheduler.test.cc
  runtime/onert/core/src/compiler/pass/UnusedOperandEliminationPass.test.cc
Labels: PR/ready for review

#9101 [onert] Move exec and interp unittest
  runtime/onert/core/src/exec/ExecTime.test.cc
  runtime/onert/core/src/exec/Execution.test.cc
  runtime/onert/core/src/exec/feature/MockTensor.h
  runtime/onert/core/src/exec/feature/nchw/Reader.test.cc
  runtime/onert/core/src/exec/feature/nchw/View.test.cc
  runtime/onert/core/src/exec/feature/nhwc/Reader.test.cc
  runtime/onert/core/src/exec/feature/nhwc/View.test.cc
  runtime/onert/core/src/interp/InterpExecutor.test.cc
Labels: PR/ready for review

#9110 [circle-eval-diff] Add creating empty tensor method
  compiler/circle-eval-diff/src/Tensor.cpp
  compiler/circle-eval-diff/src/Tensor.h
  compiler/circle-eval-diff/src/Tensor.test.cpp
Labels: PR/ready for review

#9105 [luci] Make pre-defined qparam using input of Quantize Op.
  compiler/luci/pass/src/QuantizationUtils.cpp
  compiler/luci/pass/src/QuantizationUtils.h
  compiler/luci/pass/src/QuantizeWithMinMaxPass.cpp
Labels: area/quant

#9106 [luci] Support MPQ for LeakyRelu Op
  compiler/luci/pass/src/QuantizeWithMinMaxPass.cpp
Labels: area/quant

#9107 [luci] Support fake quantization of LeakyRelu and Transpose
  compiler/luci/pass/src/ConvertToFakeQuantizedModelPass.cpp
Labels: area/quant

#9108 [circle-eval-diff] Dump output with prefix
  compiler/circle-eval-diff/driver/Driver.cpp
  compiler/circle-eval-diff/include/CircleEvalDiff.h
  compiler/circle-eval-diff/src/CircleEvalDiff.cpp
  compiler/circle-eval-diff/src/ModuleEvalDiff.cpp
  compiler/circle-eval-diff/src/ModuleEvalDiff.h
Labels: area/quant

#9109 [circle-eval-diff] Introduce file data loader
  compiler/circle-eval-diff/CMakeLists.txt
  compiler/circle-eval-diff/src/InputDataLoader.cpp
  compiler/circle-eval-diff/src/InputDataLoader.h
  compiler/circle-eval-diff/src/InputDataLoader.test.cpp
Labels: PR/ready for review

#9112 [circle-eval-diff] Use Input data loader
  compiler/circle-eval-diff/driver/Driver.cpp
  compiler/circle-eval-diff/include/CircleEvalDiff.h
  compiler/circle-eval-diff/src/CircleEvalDiff.cpp
Labels: PR/ready for review

#9119 [luci] Refactor activation qtype for pre-defined values
  compiler/luci/pass/src/PropagateQParamForwardPass.cpp
  compiler/luci/pass/src/QuantizationUtils.cpp
  compiler/luci/pass/src/QuantizationUtils.h
  compiler/luci/pass/src/QuantizeActivation.cpp
  compiler/luci/pass/src/QuantizeWithMinMaxPass.cpp
Labels: area/quant

#9121 [luci] Find activation qtype from node's input.
  compiler/luci/pass/src/QuantizationUtils.cpp
Labels: area/quant

#9133 [onert] Move ir unittest
  runtime/onert/core/src/ir/Graph.test.cc
  runtime/onert/core/src/ir/LayoutSet.test.cc
  runtime/onert/core/src/ir/OperandIndexSequence.test.cc
  runtime/onert/core/src/ir/Operands.test.cc
  runtime/onert/core/src/ir/Shape.test.cc
  runtime/onert/test/core/ir/Operations.test.cc
Labels: PR/ready for review

#9139 [luci] Remove redundant Quantize Ops after quantization
  compiler/luci/pass/src/QuantizeWithMinMaxPass.cpp
Labels: area/quant

#9140 [circle-eval-diff] Install circle-eval-diff binary
  compiler/circle-eval-diff/CMakeLists.txt
Labels: area/quant

#9138 [onert] Move remain ir test
  runtime/onert/CMakeLists.txt
  runtime/onert/core/src/ir/MockNode.h
  runtime/onert/core/src/ir/Operand.test.cc
  runtime/onert/core/src/ir/Operation.test.cc
  runtime/onert/core/src/ir/Operations.test.cc
  runtime/onert/core/src/ir/verifier/Verifier.test.cc
  runtime/onert/test/CMakeLists.txt
Labels: PR/ready for review

#9142 [one-cmds] onecc look for one-build section
  compiler/one-cmds/onecc
  compiler/one-cmds/tests/onecc_025.cfg
  compiler/one-cmds/tests/onecc_025.test
Labels: PR/ready for review

#9135 [onert] Remove unneecessary copy
  runtime/onert/core/include/backend/basic/BackendContextHelpers.h
  runtime/onert/core/include/util/ObjectManager.h
Labels: PR/ready for review

#9145 [onert/backend] Fix moved object usage
  runtime/onert/backend/acl_cl/Backend.h
  runtime/onert/backend/acl_neon/Backend.h
  runtime/onert/backend/cpu/ops/DetectionPostProcessLayer.cc
Labels: PR/ready for review

#9147 [circle-eval-diff] Introduce Top-K Match Printer
  compiler/circle-eval-diff/src/MetricPrinter.cpp
  compiler/circle-eval-diff/src/MetricPrinter.h
  compiler/circle-eval-diff/src/MetricPrinter.test.cpp
Labels: area/quant

#9143 [one-cmds] Support evaluation of quantized model
  compiler/one-cmds/one-quantize
  compiler/one-cmds/requires.cmake
  compiler/one-cmds/tests/one-quantize_010.test
  compiler/one-cmds/tests/onecc_026.cfg
  compiler/one-cmds/tests/onecc_026.test
  compiler/one-cmds/utils.py
Labels: PR/ready for review, area/quant

#9148 [circle-eval-diff] Support Top-1 and Top-5 match ratio
  compiler/circle-eval-diff/driver/Driver.cpp
  compiler/circle-eval-diff/include/CircleEvalDiff.h
  compiler/circle-eval-diff/src/CircleEvalDiff.cpp
Labels: area/quant

#9150 [one-cmds] Support Top-1 and Top-5 metrics in one-quantize
  compiler/one-cmds/one-quantize
  compiler/one-cmds/tests/one-quantize_011.test
Labels: area/quant

#9152 [one-cmds] Fix test
  compiler/one-cmds/tests/onecc_025.cfg
  compiler/one-cmds/tests/onecc_025.test
  compiler/one-cmds/tests/onecc_026.cfg
  compiler/one-cmds/tests/onecc_026.test
Labels: PR/ready for review

#9151 [one-cmds] Change warning format
  compiler/one-cmds/onecc
Labels: PR/ready for review

#9149 [infra] Fix developer dockerfile
  infra/docker/bionic/Dockerfile
  infra/docker/focal/Dockerfile
Labels: PR/ready for review

#9157 [one-cmds] Save intermediate files of one-quantize
  compiler/one-cmds/one-quantize
Labels: area/quant

#9165 [circle-eval-diff] Check output signature in init
  compiler/circle-eval-diff/src/CircleEvalDiff.cpp
  compiler/circle-eval-diff/src/MetricPrinter.cpp
Labels: area/quant

#9164 [circle-eval-diff] Remove ModuleEvalDiff files
  compiler/circle-eval-diff/src/ModuleEvalDiff.cpp
  compiler/circle-eval-diff/src/ModuleEvalDiff.h
Labels: area/quant

#9168 [luci] Support more Ops for mixed-precision quantization
  compiler/luci/pass/src/QuantizeWithMinMaxPass.cpp
Labels: area/quant

#9184 [infra/gbs] Remove userinfo
  infra/nnfw/config/gbs.conf
Labels: PR/ready for review

#9178 [res] Add tests for MPQ
  res/TensorFlowLiteRecipes/Quant_Slice_000/test.qconf.json
  res/TensorFlowLiteRecipes/Quant_Slice_000/test.recipe
  res/TensorFlowLiteRecipes/Quant_Slice_000/test.reverse
  res/TensorFlowLiteRecipes/Quant_Slice_000/test.rule
  res/TensorFlowLiteRecipes/Quant_Slice_001/test.qconf.json
  res/TensorFlowLiteRecipes/Quant_Slice_001/test.recipe
  res/TensorFlowLiteRecipes/Quant_Slice_001/test.reverse
  res/TensorFlowLiteRecipes/Quant_Slice_001/test.rule
  res/TensorFlowLiteRecipes/Quant_Softmax_000/test.qconf.json
  res/TensorFlowLiteRecipes/Quant_Softmax_000/test.recipe
  res/TensorFlowLiteRecipes/Quant_Softmax_000/test.reverse
  res/TensorFlowLiteRecipes/Quant_Softmax_000/test.rule
  res/TensorFlowLiteRecipes/Quant_Softmax_001/test.qconf.json
  res/TensorFlowLiteRecipes/Quant_Softmax_001/test.recipe
  res/TensorFlowLiteRecipes/Quant_Softmax_001/test.reverse
  res/TensorFlowLiteRecipes/Quant_Softmax_001/test.rule
  res/TensorFlowLiteRecipes/Quant_Tanh_000/test.qconf.json
  res/TensorFlowLiteRecipes/Quant_Tanh_000/test.recipe
  res/TensorFlowLiteRecipes/Quant_Tanh_000/test.reverse
  res/TensorFlowLiteRecipes/Quant_Tanh_000/test.rule
  res/TensorFlowLiteRecipes/Quant_Tanh_001/test.qconf.json
  res/TensorFlowLiteRecipes/Quant_Tanh_001/test.recipe
  res/TensorFlowLiteRecipes/Quant_Tanh_001/test.reverse
  res/TensorFlowLiteRecipes/Quant_Tanh_001/test.rule
  res/TensorFlowLiteRecipes/Quant_TransposeConv_000/test.qconf.json
  res/TensorFlowLiteRecipes/Quant_TransposeConv_000/test.recipe
  res/TensorFlowLiteRecipes/Quant_TransposeConv_000/test.reverse
  res/TensorFlowLiteRecipes/Quant_TransposeConv_000/test.rule
  res/TensorFlowLiteRecipes/Quant_TransposeConv_001/test.qconf.json
  res/TensorFlowLiteRecipes/Quant_TransposeConv_001/test.recipe
  res/TensorFlowLiteRecipes/Quant_TransposeConv_001/test.reverse
  res/TensorFlowLiteRecipes/Quant_TransposeConv_001/test.rule
  res/TensorFlowLiteRecipes/Quant_Transpose_000/test.qconf.json
  res/TensorFlowLiteRecipes/Quant_Transpose_000/test.recipe
  res/TensorFlowLiteRecipes/Quant_Transpose_000/test.reverse
  res/TensorFlowLiteRecipes/Quant_Transpose_000/test.rule
  res/TensorFlowLiteRecipes/Quant_Transpose_001/test.qconf.json
  res/TensorFlowLiteRecipes/Quant_Transpose_001/test.recipe
  res/TensorFlowLiteRecipes/Quant_Transpose_001/test.reverse
  res/TensorFlowLiteRecipes/Quant_Transpose_001/test.rule
Labels: area/quant, area/test

#9182 [res] Add MPQ tests
  res/TensorFlowLiteRecipes/Quant_AveragePool2D_000/test.qconf.json
  res/TensorFlowLiteRecipes/Quant_AveragePool2D_000/test.recipe
  res/TensorFlowLiteRecipes/Quant_AveragePool2D_000/test.reverse
  res/TensorFlowLiteRecipes/Quant_AveragePool2D_000/test.rule
  res/TensorFlowLiteRecipes/Quant_AveragePool2D_001/test.qconf.json
  res/TensorFlowLiteRecipes/Quant_AveragePool2D_001/test.recipe
  res/TensorFlowLiteRecipes/Quant_AveragePool2D_001/test.reverse
  res/TensorFlowLiteRecipes/Quant_AveragePool2D_001/test.rule
  res/TensorFlowLiteRecipes/Quant_BatchMatMul_000/test.qconf.json
  res/TensorFlowLiteRecipes/Quant_BatchMatMul_000/test.recipe
  res/TensorFlowLiteRecipes/Quant_BatchMatMul_000/test.reverse
  res/TensorFlowLiteRecipes/Quant_BatchMatMul_000/test.rule
  res/TensorFlowLiteRecipes/Quant_BatchMatMul_001/test.qconf.json
  res/TensorFlowLiteRecipes/Quant_BatchMatMul_001/test.recipe
  res/TensorFlowLiteRecipes/Quant_BatchMatMul_001/test.reverse
  res/TensorFlowLiteRecipes/Quant_BatchMatMul_001/test.rule
  res/TensorFlowLiteRecipes/Quant_Concatenation_000/test.qconf.json
  res/TensorFlowLiteRecipes/Quant_Concatenation_000/test.recipe
  res/TensorFlowLiteRecipes/Quant_Concatenation_000/test.reverse
  res/TensorFlowLiteRecipes/Quant_Concatenation_000/test.rule
  res/TensorFlowLiteRecipes/Quant_Concatenation_001/test.qconf.json
  res/TensorFlowLiteRecipes/Quant_Concatenation_001/test.recipe
  res/TensorFlowLiteRecipes/Quant_Concatenation_001/test.reverse
  res/TensorFlowLiteRecipes/Quant_Concatenation_001/test.rule
  res/TensorFlowLiteRecipes/Quant_Conv_003/test.qconf.json
  res/TensorFlowLiteRecipes/Quant_Conv_003/test.recipe
  res/TensorFlowLiteRecipes/Quant_Conv_003/test.reverse
  res/TensorFlowLiteRecipes/Quant_Conv_003/test.rule
  res/TensorFlowLiteRecipes/Quant_Conv_004/test.qconf.json
  res/TensorFlowLiteRecipes/Quant_Conv_004/test.recipe
  res/TensorFlowLiteRecipes/Quant_Conv_004/test.reverse
  res/TensorFlowLiteRecipes/Quant_Conv_004/test.rule
  res/TensorFlowLiteRecipes/Quant_DepthwiseConv2D_000/test.qconf.json
  res/TensorFlowLiteRecipes/Quant_DepthwiseConv2D_000/test.recipe
  res/TensorFlowLiteRecipes/Quant_DepthwiseConv2D_000/test.reverse
  res/TensorFlowLiteRecipes/Quant_DepthwiseConv2D_000/test.rule
  res/TensorFlowLiteRecipes/Quant_DepthwiseConv2D_001/test.qconf.json
  res/TensorFlowLiteRecipes/Quant_DepthwiseConv2D_001/test.recipe
  res/TensorFlowLiteRecipes/Quant_DepthwiseConv2D_001/test.reverse
  res/TensorFlowLiteRecipes/Quant_DepthwiseConv2D_001/test.rule
Labels: area/quant, area/test

#9180 [res] Add tests for MPQ
  res/TensorFlowLiteRecipes/Quant_Mean_000/test.qconf.json
  res/TensorFlowLiteRecipes/Quant_Mean_000/test.recipe
  res/TensorFlowLiteRecipes/Quant_Mean_000/test.reverse
  res/TensorFlowLiteRecipes/Quant_Mean_000/test.rule
  res/TensorFlowLiteRecipes/Quant_Mean_001/test.qconf.json
  res/TensorFlowLiteRecipes/Quant_Mean_001/test.recipe
  res/TensorFlowLiteRecipes/Quant_Mean_001/test.reverse
  res/TensorFlowLiteRecipes/Quant_Mean_001/test.rule
  res/TensorFlowLiteRecipes/Quant_Mul_000/test.qconf.json
  res/TensorFlowLiteRecipes/Quant_Mul_000/test.recipe
  res/TensorFlowLiteRecipes/Quant_Mul_000/test.rule
  res/TensorFlowLiteRecipes/Quant_Mul_001/test.qconf.json
  res/TensorFlowLiteRecipes/Quant_Mul_001/test.recipe
  res/TensorFlowLiteRecipes/Quant_Mul_001/test.rule
  res/TensorFlowLiteRecipes/Quant_Neg_000/test.qconf.json
  res/TensorFlowLiteRecipes/Quant_Neg_000/test.recipe
  res/TensorFlowLiteRecipes/Quant_Neg_000/test.reverse
  res/TensorFlowLiteRecipes/Quant_Neg_000/test.rule
  res/TensorFlowLiteRecipes/Quant_Neg_001/test.qconf.json
  res/TensorFlowLiteRecipes/Quant_Neg_001/test.recipe
  res/TensorFlowLiteRecipes/Quant_Neg_001/test.reverse
  res/TensorFlowLiteRecipes/Quant_Neg_001/test.rule
  res/TensorFlowLiteRecipes/Quant_PRelu_000/test.qconf.json
  res/TensorFlowLiteRecipes/Quant_PRelu_000/test.recipe
  res/TensorFlowLiteRecipes/Quant_PRelu_000/test.reverse
  res/TensorFlowLiteRecipes/Quant_PRelu_000/test.rule
  res/TensorFlowLiteRecipes/Quant_PRelu_001/test.qconf.json
  res/TensorFlowLiteRecipes/Quant_PRelu_001/test.recipe
  res/TensorFlowLiteRecipes/Quant_PRelu_001/test.reverse
  res/TensorFlowLiteRecipes/Quant_PRelu_001/test.rule
  res/TensorFlowLiteRecipes/Quant_Pad_000/test.qconf.json
  res/TensorFlowLiteRecipes/Quant_Pad_000/test.recipe
  res/TensorFlowLiteRecipes/Quant_Pad_000/test.reverse
  res/TensorFlowLiteRecipes/Quant_Pad_000/test.rule
  res/TensorFlowLiteRecipes/Quant_Pad_001/test.qconf.json
  res/TensorFlowLiteRecipes/Quant_Pad_001/test.recipe
  res/TensorFlowLiteRecipes/Quant_Pad_001/test.reverse
  res/TensorFlowLiteRecipes/Quant_Pad_001/test.rule
Labels: area/quant, area/test

#9181 [res] Add tests for MPQ
  res/CircleRecipes/Quant_InstanceNorm_000/test.qconf.json
  res/CircleRecipes/Quant_InstanceNorm_000/test.recipe
  res/CircleRecipes/Quant_InstanceNorm_000/test.reverse
  res/CircleRecipes/Quant_InstanceNorm_000/test.rule
  res/CircleRecipes/Quant_InstanceNorm_001/test.qconf.json
  res/CircleRecipes/Quant_InstanceNorm_001/test.recipe
  res/CircleRecipes/Quant_InstanceNorm_001/test.reverse
  res/CircleRecipes/Quant_InstanceNorm_001/test.rule
  res/TensorFlowLiteRecipes/Quant_FullyConnected_000/test.qconf.json
  res/TensorFlowLiteRecipes/Quant_FullyConnected_000/test.recipe
  res/TensorFlowLiteRecipes/Quant_FullyConnected_000/test.reverse
  res/TensorFlowLiteRecipes/Quant_FullyConnected_000/test.rule
  res/TensorFlowLiteRecipes/Quant_FullyConnected_001/test.qconf.json
  res/TensorFlowLiteRecipes/Quant_FullyConnected_001/test.recipe
  res/TensorFlowLiteRecipes/Quant_FullyConnected_001/test.reverse
  res/TensorFlowLiteRecipes/Quant_FullyConnected_001/test.rule
  res/TensorFlowLiteRecipes/Quant_LeakyRelu_000/test.qconf.json
  res/TensorFlowLiteRecipes/Quant_LeakyRelu_000/test.recipe
  res/TensorFlowLiteRecipes/Quant_LeakyRelu_000/test.reverse
  res/TensorFlowLiteRecipes/Quant_LeakyRelu_000/test.rule
  res/TensorFlowLiteRecipes/Quant_LeakyRelu_001/test.qconf.json
  res/TensorFlowLiteRecipes/Quant_LeakyRelu_001/test.recipe
  res/TensorFlowLiteRecipes/Quant_LeakyRelu_001/test.reverse
  res/TensorFlowLiteRecipes/Quant_LeakyRelu_001/test.rule
  res/TensorFlowLiteRecipes/Quant_Logistic_000/test.qconf.json
  res/TensorFlowLiteRecipes/Quant_Logistic_000/test.recipe
  res/TensorFlowLiteRecipes/Quant_Logistic_000/test.reverse
  res/TensorFlowLiteRecipes/Quant_Logistic_000/test.rule
  res/TensorFlowLiteRecipes/Quant_Logistic_001/test.qconf.json
  res/TensorFlowLiteRecipes/Quant_Logistic_001/test.recipe
  res/TensorFlowLiteRecipes/Quant_Logistic_001/test.reverse
  res/TensorFlowLiteRecipes/Quant_Logistic_001/test.rule
  res/TensorFlowLiteRecipes/Quant_MaxPool2D_000/test.qconf.json
  res/TensorFlowLiteRecipes/Quant_MaxPool2D_000/test.recipe
  res/TensorFlowLiteRecipes/Quant_MaxPool2D_000/test.reverse
  res/TensorFlowLiteRecipes/Quant_MaxPool2D_000/test.rule
  res/TensorFlowLiteRecipes/Quant_MaxPool2D_001/test.qconf.json
  res/TensorFlowLiteRecipes/Quant_MaxPool2D_001/test.recipe
  res/TensorFlowLiteRecipes/Quant_MaxPool2D_001/test.reverse
  res/TensorFlowLiteRecipes/Quant_MaxPool2D_001/test.rule
Labels: area/quant, area/test

#9179 [res] Add tests for MPQ
  res/TensorFlowLiteRecipes/Quant_ReLU6_000/test.qconf.json
  res/TensorFlowLiteRecipes/Quant_ReLU6_000/test.recipe
  res/TensorFlowLiteRecipes/Quant_ReLU6_000/test.reverse
  res/TensorFlowLiteRecipes/Quant_ReLU6_000/test.rule
  res/TensorFlowLiteRecipes/Quant_ReLU6_001/test.qconf.json
  res/TensorFlowLiteRecipes/Quant_ReLU6_001/test.recipe
  res/TensorFlowLiteRecipes/Quant_ReLU6_001/test.reverse
  res/TensorFlowLiteRecipes/Quant_ReLU6_001/test.rule
  res/TensorFlowLiteRecipes/Quant_ReLU_000/test.qconf.json
  res/TensorFlowLiteRecipes/Quant_ReLU_000/test.recipe
  res/TensorFlowLiteRecipes/Quant_ReLU_000/test.reverse
  res/TensorFlowLiteRecipes/Quant_ReLU_000/test.rule
  res/TensorFlowLiteRecipes/Quant_ReLU_001/test.qconf.json
  res/TensorFlowLiteRecipes/Quant_ReLU_001/test.recipe
  res/TensorFlowLiteRecipes/Quant_ReLU_001/test.reverse
  res/TensorFlowLiteRecipes/Quant_ReLU_001/test.rule
  res/TensorFlowLiteRecipes/Quant_Reshape_000/test.qconf.json
  res/TensorFlowLiteRecipes/Quant_Reshape_000/test.recipe
  res/TensorFlowLiteRecipes/Quant_Reshape_000/test.reverse
  res/TensorFlowLiteRecipes/Quant_Reshape_000/test.rule
  res/TensorFlowLiteRecipes/Quant_Reshape_001/test.qconf.json
  res/TensorFlowLiteRecipes/Quant_Reshape_001/test.recipe
  res/TensorFlowLiteRecipes/Quant_Reshape_001/test.reverse
  res/TensorFlowLiteRecipes/Quant_Reshape_001/test.rule
  res/TensorFlowLiteRecipes/Quant_ResizeBilinear_000/test.qconf.json
  res/TensorFlowLiteRecipes/Quant_ResizeBilinear_000/test.recipe
  res/TensorFlowLiteRecipes/Quant_ResizeBilinear_000/test.reverse
  res/TensorFlowLiteRecipes/Quant_ResizeBilinear_000/test.rule
  res/TensorFlowLiteRecipes/Quant_ResizeBilinear_001/test.qconf.json
  res/TensorFlowLiteRecipes/Quant_ResizeBilinear_001/test.recipe
  res/TensorFlowLiteRecipes/Quant_ResizeBilinear_001/test.reverse
  res/TensorFlowLiteRecipes/Quant_ResizeBilinear_001/test.rule
  res/TensorFlowLiteRecipes/Quant_ResizeNearestNeighbor_000/test.qconf.json
  res/TensorFlowLiteRecipes/Quant_ResizeNearestNeighbor_000/test.recipe
  res/TensorFlowLiteRecipes/Quant_ResizeNearestNeighbor_000/test.reverse
  res/TensorFlowLiteRecipes/Quant_ResizeNearestNeighbor_000/test.rule
  res/TensorFlowLiteRecipes/Quant_ResizeNearestNeighbor_001/test.qconf.json
  res/TensorFlowLiteRecipes/Quant_ResizeNearestNeighbor_001/test.recipe
  res/TensorFlowLiteRecipes/Quant_ResizeNearestNeighbor_001/test.reverse
  res/TensorFlowLiteRecipes/Quant_ResizeNearestNeighbor_001/test.rule
Labels: area/quant, area/test

#9185 [circle-quantizer-dredd] Add tests for MPQ
  compiler/circle-quantizer-dredd-recipe-test/test.lst
Labels: area/quant, area/test

#9189 [infra] Fix build script bug
  infra/scripts/docker_build_nncc.sh
  infra/scripts/docker_collect_nnpkg_resources.sh
Labels: PR/ready for review

#9202 [circle-quantizer] Support multiple names in quant config
  compiler/circle-quantizer/src/CircleQuantizer.cpp
Labels: area/quant

#9210 [tools/model2pkg] Fix help message
  tools/nnpackage_tool/model2nnpkg/model2nnpkg.sh
Labels: PR/ready for review

#9214 [one-cmds] Add test for multiple layer names in qconf
  compiler/one-cmds/tests/one-quantize_012.qconf.json
  compiler/one-cmds/tests/one-quantize_012.test
Labels: area/quant
