Repository Samsung/ONE, pull requests merged in 2022-07, with the labels that each got.

#9374 [one-cmds] Rename wrong variables
  compiler/one-cmds/tests/CMakeLists.txt
Labels: PR/ready for review

#9362 [one-cmds] Introduce CfgRunner
  compiler/one-cmds/onecc
  compiler/one-cmds/onelib/CfgRunner.py
Labels: PR/ready for review

#9373 [onert/api] nnfw_session may have multiple CompilerOptions
  runtime/onert/api/src/nnfw_api_internal.cc
  runtime/onert/api/src/nnfw_api_internal.h
Labels: area/onert

#9379 [onert] Revisit trix_loader to remove Subgraphs
  runtime/onert/frontend/trix/src/trix_loader.cc
  runtime/onert/frontend/trix/src/trix_loader_dummy.cc
Labels: area/onert

#9380 [onert] Fix trix error message
  runtime/onert/backend/trix/DevContext.h
  runtime/onert/frontend/trix/src/trix_loader.cc
Labels: area/onert

#9377 [onert/api] Use NNPkg in api internal
  runtime/onert/api/src/nnfw_api_internal.cc
  runtime/onert/api/src/nnfw_api_internal.h
Labels: area/onert

#9385 [onert] Fix build fails on gcc-11
  runtime/onert/core/include/backend/ITensor.h
  runtime/onert/core/include/ir/Layout.h
  runtime/onert/core/include/util/CalculateActivationRange.h
Labels: PR/ready for review

#9378 [onert/ir] Add fields for model connection and nnpkg IO in NNPkg
  runtime/onert/core/include/ir/NNPkg.h
Labels: area/onert

#9388 [onert/api] Read pkg-inputs, pkg-outputs and model-connects
  runtime/onert/api/src/nnfw_api_internal.cc
Labels: area/onert

#9387 [common-artifacts] Fix for protobuf issue
  compiler/common-artifacts/CMakeLists.txt
Labels: PR/ready for review

#9392 [onert/cker] Check ruy::Context pointer to make gcc11 happy
  compute/cker/include/cker/CpuBackendThreadpool.h
Labels: PR/ready for review

#9393 [ArmComputeEx] Use python3 explicitly
  compute/ARMComputeEx/CMakeLists.txt
  packaging/nnfw.spec
Labels: PR/ready for review

#9394 [tools/cross] Update supporting ubuntu version
  tools/cross/arm/sources.list.jammy
  tools/cross/arm/sources.list.xenial
  tools/cross/install_rootfs.sh
Labels: PR/ready for review

#9375 [one-cmds] Introduce workflow
  compiler/one-cmds/CMakeLists.txt
  compiler/one-cmds/onecc
  compiler/one-cmds/onelib/OptionBuilder.py
  compiler/one-cmds/onelib/TopologicalSortHelper.py
  compiler/one-cmds/onelib/WorkflowRunner.py
Labels: PR/ready for review

#9395 [debian] Add workflow things
  infra/debian/compiler/one-compiler.install
Labels: PR/ready for review

#9399 [one-cmds] Add workflow tests
  compiler/one-cmds/dummy-driver/CMakeLists.txt
  compiler/one-cmds/dummy-driver/src/dummy-inferV2.cpp
  compiler/one-cmds/tests/CMakeLists.txt
  compiler/one-cmds/tests/onecc_028.test
  compiler/one-cmds/tests/onecc_028.workflow.json
  compiler/one-cmds/tests/onecc_029.test
  compiler/one-cmds/tests/onecc_029.workflow.json
  compiler/one-cmds/tests/onecc_030.test
  compiler/one-cmds/tests/onecc_030.workflow.json
  compiler/one-cmds/tests/onecc_031.test
  compiler/one-cmds/tests/onecc_031.workflow.json
  compiler/one-cmds/tests/onecc_032.test
  compiler/one-cmds/tests/onecc_032.workflow.json
  compiler/one-cmds/tests/onecc_033.test
  compiler/one-cmds/tests/onecc_033.workflow.json
  compiler/one-cmds/tests/onecc_034.test
  compiler/one-cmds/tests/onecc_034.workflow.json
  compiler/one-cmds/tests/onecc_035.test
  compiler/one-cmds/tests/onecc_035.workflow.json
  compiler/one-cmds/tests/onecc_036.test
  compiler/one-cmds/tests/onecc_036.workflow.json
  compiler/one-cmds/tests/onecc_037.test
  compiler/one-cmds/tests/onecc_037.workflow.json
  compiler/one-cmds/tests/onecc_038.test
  compiler/one-cmds/tests/onecc_038.workflow.json
  compiler/one-cmds/tests/onecc_039.test
  compiler/one-cmds/tests/onecc_039.workflow.json
  compiler/one-cmds/tests/onecc_040.cfg
  compiler/one-cmds/tests/onecc_040.test
  compiler/one-cmds/tests/onecc_040.workflow.json
  compiler/one-cmds/tests/onecc_041.cfg
  compiler/one-cmds/tests/onecc_041.test
  compiler/one-cmds/tests/onecc_041.workflow.json
  compiler/one-cmds/tests/onecc_neg_013.test
  compiler/one-cmds/tests/onecc_neg_014.test
  compiler/one-cmds/tests/onecc_neg_014.workflow.json
  compiler/one-cmds/tests/onecc_neg_015.test
  compiler/one-cmds/tests/onecc_neg_015.workflow.json
  compiler/one-cmds/tests/onecc_neg_016.test
  compiler/one-cmds/tests/onecc_neg_016.workflow.json
  compiler/one-cmds/tests/onecc_neg_017.test
  compiler/one-cmds/tests/onecc_neg_017.workflow.json
  compiler/one-cmds/tests/onecc_neg_018.test
  compiler/one-cmds/tests/onecc_neg_018.workflow.json
  compiler/one-cmds/tests/onecc_neg_019.test
  compiler/one-cmds/tests/onecc_neg_019.workflow.json
  compiler/one-cmds/tests/onecc_neg_020.test
  compiler/one-cmds/tests/onecc_neg_020.workflow.json
  compiler/one-cmds/tests/onecc_neg_021.test
  compiler/one-cmds/tests/onecc_neg_021.workflow.json
  compiler/one-cmds/tests/onecc_neg_022.cfg
  compiler/one-cmds/tests/onecc_neg_022.test
  compiler/one-cmds/tests/onecc_neg_022.workflow.json
Labels: PR/ready for review

#9383 [onert] Refine StaticShapeinferer
  runtime/onert/core/include/compiler/StaticShapeInferer.h
  runtime/onert/core/src/compiler/Compiler.cc
  runtime/onert/core/src/compiler/StaticShapeInferer.cc
  tests/nnfw_api/src/one_op_tests/While.test.cc
Labels: PR/ready for review

#9407 [onert] Change unnecessary copies to use references
  runtime/onert/core/src/compiler/ExecutorFactory.cc
  runtime/onert/core/src/compiler/Fp32ToFp16Converter.cc
Labels: PR/ready for review, trivial

#9411 [onert] Add explicit keyword to Graph constructor
  runtime/onert/api/src/nnfw_api_internal.cc
  runtime/onert/core/include/ir/Graph.h
  runtime/onert/core/src/ir/Graph.cc
Labels: PR/ready for review

#9436 [one-cmds] Fix file name typo
  compiler/one-cmds/dummy-driver/CMakeLists.txt
Labels: PR/ready for review

#9444 [record-minmax] Make gcc-11 happy
  compiler/record-minmax/include/RecordFunction.h
  compiler/record-minmax/src/MinMaxObserver.cpp
Labels: PR/ready for review

#9442 [luci-interpreter] Make gcc-11 happy.
  compiler/luci-interpreter/src/kernels/MirrorPad.cpp
  compiler/luci-interpreter/src/kernels/Pad.cpp
  compiler/luci-interpreter/src/kernels/PadV2.cpp
Labels: PR/ready for review

#9438 [circle-eval-diff] Make gcc-11 happy
  compiler/circle-eval-diff/src/MetricPrinter.cpp
Labels: PR/ready for review

#9437 [luci] Make gcc-11 happy
  compiler/luci/pass/src/FoldSparseToDensePass.cpp
  compiler/luci/pass/src/PropagateQParamBackwardPass.cpp
  compiler/luci/pass/src/QuantizationUtils.cpp
  compiler/luci/pass/src/QuantizeBias.cpp
  compiler/luci/pass/src/QuantizeDequantizeWeightsPass.cpp
  compiler/luci/pass/src/QuantizeWeights.cpp
Labels: PR/ready for review

#9440 [exo] Make gcc-11 happy
  compiler/exo/src/Conversion/DepthwiseConv2DConverter.cpp
Labels: PR/ready for review

#9441 [kuma] Make gcc-11 happy
  compiler/kuma/src/IntervalSet.h
Labels: PR/ready for review

#9443 [moco] Make gcc-11 happy
  compiler/moco/lang/src/IR/TFNode.cpp
Labels: PR/ready for review

#9434 [infra/compiler] Update cmake minimum requirement version to 3.3
  infra/nncc/CMakeLists.txt
Labels: PR/ready for review

#9381 [infra] Update rootfs installation script
  tools/cross/install_rootfs.sh
Labels: PR/ready for review

#9448 [infra] Fix build option on x64 runtime build
  infra/scripts/docker_build_test_x64.sh
Labels: PR/ready for review

#9457 [record-minmax] Improve error message
  compiler/record-minmax/src/MinMaxObserver.cpp
Labels: area/quant

#9454 [luci] Fix QuantizeDequantizeWeights condition
  compiler/luci/pass/src/QuantizeDequantizeWeightsPass.cpp
Labels: area/quant

#9403 [mir2loco] Fix Conv2D_Test
  compiler/mir2loco/src/mir2loco.test.cpp
Labels: PR/ready for review

#9471 [onert] Tidy DynamicTensorCtx
  runtime/onert/backend/cpu/KernelGenerator.cc
  runtime/onert/backend/ruy/KernelGenerator.cc
  runtime/onert/backend/xnnpack/KernelGenerator.cc
  runtime/onert/core/include/exec/FunctionSequence.h
  runtime/onert/core/src/backend/builtin/KernelGenerator.cc
  runtime/onert/core/src/exec/FunctionSequence.cc
Labels: area/onert

#9476 [luci-micro] Fix standalone luci-micro building
  compiler/luci-micro/CMakeLists.txt
  compiler/luci-micro/standalone/CMakeLists.txt
Labels: approval: 1

#9491 [tools] Fix tflite_vanilla_run
  tests/tools/tflite_vanilla_run/CMakeLists.txt
Labels: PR/ready for review

#9489 [luci-interpreter] Support ReduceMax Op
  compiler/luci-interpreter/pal/linux/KernelsToBuild.lst
  compiler/luci-interpreter/src/kernels/ReduceMax.cpp
  compiler/luci-interpreter/src/kernels/ReduceMax.h
  compiler/luci-interpreter/src/kernels/ReduceMax.test.cpp
  compiler/luci-interpreter/src/loader/nodes/ReduceMax.cpp
Labels: area/quant

#9492 [luci] Verify quantization of ReduceMax
  compiler/luci/pass/src/QuantizedModelVerifier.test.cpp
  compiler/luci/pass/src/VerifyQuantizedNodeGranularity.h
  compiler/luci/pass/src/VerifyQuantizedNodeType.cpp
  compiler/luci/pass/src/VerifyQuantizedNodeType.h
Labels: area/quant

#9490 [infra] Update Abseil-cpp
  infra/cmake/packages/AbseilConfig.cmake
  infra/cmake/packages/AbseilSourceConfig.cmake
  packaging/ABSEIL.tar.gz
Labels: PR/ready for review

#9495 [luci] Support fake quantization of ReduceMax Op
  compiler/luci/pass/src/ConvertToFakeQuantizedModelPass.cpp
Labels: area/quant

#9102 [infra/gbs] Build once on tizen test build
  packaging/nnfw.spec
Labels: PR/ready for review

#9508 [luci] Support fake quantization of more Ops
  compiler/luci/pass/src/ConvertToFakeQuantizedModelPass.cpp
Labels: area/quant
