Repository Samsung/ONE, pull requests merged in 2022-09, with the labels that each got.

#9650 [onert] Update default backend list
  runtime/onert/core/include/util/Config.lst
Labels: PR/ready for review

#9649 [onert] Support simply partitioned multimodel execution
  runtime/onert/core/src/exec/Executors.cc
Labels: PR/ready for review, approval: 2

#9654 [onert] Fix a typo in Convolution layer comment
  runtime/onert/backend/cpu/ops/ConvolutionLayer.cc
Labels: PR/NO TEST, area/onert, trivial, approval: 1

#9656 [onert] Use non-negative zeropoint for conv2d uint8 output
  tests/nnfw_api/src/one_op_tests/Conv2D.test.cc
Labels: area/onert

#9661 [onert/test] Update GenModelTest fail message
  tests/nnfw_api/src/GenModelTest.h
Labels: PR/ready for review

#9662 [onert] Introduce dconv per-channel q8 uint kernel
  compute/cker/include/cker/operation/DepthwiseConv.h
  compute/cker/include/cker/operation/reference/integer_ops/DepthwiseConvUInt8.h
Labels: area/onert

#9664 [onert] Support dconv per-channel uint8
  runtime/onert/backend/cpu/ops/DepthwiseConvolutionLayer.cc
  runtime/onert/backend/cpu/ops/DepthwiseConvolutionLayer.h
Labels: PR/ready for review, area/onert

#9666 StaticShapeInferer for Bulk
  runtime/onert/core/include/compiler/StaticShapeInferer.h
  runtime/onert/core/src/compiler/StaticShapeInferer.cc
Labels: PR/ready for review

#9663 [onert] Add testcase dconv uint8 per-channel
  tests/nnfw_api/src/one_op_tests/DepthwiseConv2D.test.cc
Labels: PR/ready for review, area/onert

#9668 Bulk layer's batch execution
  runtime/onert/backend/trix/DevContext.h
  runtime/onert/backend/trix/ops/BulkLayer.cc
  runtime/onert/backend/trix/ops/BulkLayer.h
Labels: PR/ready for review

#9685 [vconone] Bump up to 1.22.0
  compiler/vconone/CMakeLists.txt
Labels: PR/ready for review

#9678 [circle-quantizer] Remove unused argparse
  compiler/circle-quantizer/src/CircleQuantizer.cpp
Labels: trivial

#9677 Update runtime version to 1.22.0
  docs/conf.py
  packaging/nnfw.spec
  runtime/contrib/android/api/build.gradle
  runtime/onert/api/include/nnfw_version.h
Labels: PR/ready for review

#9695 [infra/runtime] Clean up makefile
  Makefile.template
  infra/scripts/docker_build_cross_aarch64_runtime.sh
  infra/scripts/docker_build_cross_arm_runtime.sh
  infra/scripts/docker_build_cross_arm_runtime_release.sh
  infra/scripts/docker_build_cross_coverage.sh
  infra/scripts/docker_build_test_x64.sh
Labels: PR/ready for review

#9726 [infra/test] Remove NNAPI test framework
  infra/scripts/common.sh
  infra/scripts/test_ubuntu_runtime.sh
  tests/scripts/command/verify-tflite
  tests/scripts/list/nnapi_test.aarch64.list
  tests/scripts/list/nnapi_test.armv7l.list
Labels: PR/ready for review

#9730 [onert] Change Executors::at() return type
  runtime/onert/core/include/exec/Execution.h
  runtime/onert/core/include/exec/Executors.h
  runtime/onert/core/include/exec/IExecutor.h
  runtime/onert/core/src/backend/builtin/kernel/IfLayer.cc
  runtime/onert/core/src/backend/builtin/kernel/WhileLayer.cc
  runtime/onert/core/src/exec/ExecutorBase.h
  runtime/onert/core/src/interp/InterpExecutor.h
Labels: PR/ready for review

#9734 [onert/test] Remove nnapi_test
  infra/debian/runtime/rules
  infra/nnfw/cmake/CfgOptionFlags.cmake
  packaging/nnfw.spec
  tests/tools/nnapi_test/CMakeLists.txt
  tests/tools/nnapi_test/src/args.cc
  tests/tools/nnapi_test/src/args.h
  tests/tools/nnapi_test/src/nnapi_test.cc
Labels: PR/ready for review

#9745 [onert] Support Lookup operator loading
  runtime/onert/frontend/base_loader/include/base_loader.h
  tests/scripts/list/tflite_comparator.aarch64.acl_cl.list
  tests/scripts/list/tflite_comparator.aarch64.acl_neon.list
  tests/scripts/list/tflite_comparator.armv7l.acl_cl.list
  tests/scripts/list/tflite_comparator.armv7l.acl_neon.list
Labels: PR/ready for review

#9741 [infra/onert] Update Eigen version
  compute/cker/include/cker/operation/Logistic.h
  infra/nnfw/cmake/packages/EigenConfig.cmake
  packaging/TENSORFLOW-2.3.0-EIGEN.tar.gz
  packaging/TENSORFLOW-2.8.0-EIGEN.tar.gz
  packaging/nnfw.spec
Labels: PR/ready for review

#9748 [onert] Change ir::Shape::MAX_RANK to ir::Shape::ONERT_MAX_RANK
  runtime/onert/backend/acl_common/AclTensorBuilder.h
  runtime/onert/core/include/ir/Shape.h
  runtime/onert/core/src/ir/Shape.cc
  runtime/onert/core/src/ir/Shape.test.cc
  runtime/onert/core/src/util/ShapeInference.cc
Labels: approval: 2

#9727 [luci-micro] Remove arser and foder from GenerateKernelsListHelper
  compiler/luci-micro/CMakeLists.txt
  compiler/luci-micro/helpers/GenerateKernelsListHelper.cpp
Labels: approval: 1

#9758 [luci-micro] Remove mio-circle04 dependency
  compiler/luci-micro/CMakeLists.txt
  compiler/luci-micro/helpers/GenerateKernelsListHelper.cpp
  compiler/luci-micro/luci-interpreter/include/luci_interpreter/core/CircleMicroReader.h
  compiler/luci-micro/luci-interpreter/include/luci_interpreter/core/CircleMicroReaderHelper.h
  compiler/luci-micro/luci-interpreter/src/CMakeLists.txt
  compiler/luci-micro/luci-interpreter/src/core/CMakeLists.txt
  compiler/luci-micro/luci-interpreter/src/core/CircleMicroReader.cpp
  compiler/luci-micro/luci-interpreter/src/core/CircleMicroReaderHelper.cpp
  compiler/luci-micro/luci-interpreter/src/loader/CMakeLists.txt
  compiler/luci-micro/requires.cmake
  compiler/luci-micro/standalone/CMakeLists.txt
Labels: approval: 1

#9761 [onert] Remove handleDynamicInputTensor
  runtime/onert/core/src/exec/ExecutorBase.cc
  runtime/onert/core/src/exec/ExecutorBase.h
Labels: area/onert, trivial

#9762 [onert] Introduce entryExecutor
  runtime/onert/core/include/exec/Execution.h
  runtime/onert/core/include/exec/Executors.h
  runtime/onert/core/src/exec/Execution.cc
  runtime/onert/core/src/exec/Executors.cc
  runtime/onert/core/src/interp/InterpExecutor.test.cc
Labels: PR/ready for review

#9763 [docs] Update make command from how to build runtime
  docs/howto/how-to-build-runtime.md
  docs/howto/how-to-cross-build-runtime-for-aarch64.md
  docs/howto/how-to-cross-build-runtime-for-arm.md
Labels: PR/NO TEST, PR/ready for review, area/onert

#9769 [luci-interpreter] throw error when the memory limit exceeded
  compiler/luci-interpreter/src/BuddyMemoryManager.cpp
Labels: PR/ready for review

#9766 [tools/nncc-tc-to-nnpkg-tc] Update README
  tools/nnpackage_tool/nncc-tc-to-nnpkg-tc/README.md
Labels: trivial

#9770 [tools/tflitefile_tool] Remove duplicated buffer indices
  tools/tflitefile_tool/select_operator.py
Labels: PR/ready for review

#9774 [onert] Lowering multiple model with controlflow
  runtime/onert/core/src/compiler/Compiler.cc
Labels: PR/ready for review, approval: 2

#9652 [infra] Add `circle-interpreter` to debain package
  infra/debian/compiler/one-compiler.install
Labels: PR/NO MERGE

#9776 [luci-interpreter] throw error when the memory limit exceeded
  compiler/luci-interpreter/src/BuddyMemoryManager.cpp
Labels: PR/ready for review, type/release

#9785 [onecc-docker] debian package for onecc-docker
  compiler/onecc-docker/debian/changelog
  compiler/onecc-docker/debian/compat
  compiler/onecc-docker/debian/control
  compiler/onecc-docker/debian/copyright
  compiler/onecc-docker/debian/onecc-docker.install
  compiler/onecc-docker/debian/onecc-docker.links
  compiler/onecc-docker/debian/rules
Labels: PR/ready for review, SSAFY

#9773 [onecc-docker] Dockerfile for onecc-docker
  compiler/onecc-docker/docker/Dockerfile
Labels: PR/ready for review, SSAFY

#9791 [onert] Use ModelIndex on executor map
  runtime/onert/core/include/exec/Executors.h
  runtime/onert/core/src/compiler/Compiler.cc
  runtime/onert/core/src/exec/Executors.cc
  runtime/onert/core/src/interp/InterpExecutor.test.cc
Labels: PR/ready for review

#9794 [onert] Change ModelIndex value type
  runtime/onert/api/src/nnfw_api_internal.cc
  runtime/onert/core/include/exec/Executors.h
  runtime/onert/core/include/ir/Index.h
  runtime/onert/core/include/util/Index.h
  runtime/onert/core/src/compiler/Compiler.cc
Labels: PR/ready for review

#9747 [onert] Support batch-parallel execution of trix models
  runtime/onert/backend/trix/BatchThreadPool.cc
  runtime/onert/backend/trix/BatchThreadPool.h
  runtime/onert/backend/trix/Convert.cc
  runtime/onert/backend/trix/Convert.h
  runtime/onert/backend/trix/DevContext.cc
  runtime/onert/backend/trix/DevContext.h
  runtime/onert/backend/trix/ops/BulkLayer.cc
  runtime/onert/backend/trix/ops/BulkLayer.h
Labels: PR/ready for review, approval: 2

#9795 [onert] Support multiple model on builtin backend
  runtime/onert/core/include/exec/Executors.h
  runtime/onert/core/src/backend/builtin/KernelGenerator.cc
  runtime/onert/core/src/backend/builtin/KernelGenerator.h
  runtime/onert/core/src/backend/builtin/kernel/IfLayer.cc
  runtime/onert/core/src/backend/builtin/kernel/IfLayer.h
  runtime/onert/core/src/backend/builtin/kernel/WhileLayer.cc
  runtime/onert/core/src/backend/builtin/kernel/WhileLayer.h
  runtime/onert/core/src/compiler/Compiler.cc
  runtime/onert/core/src/compiler/ExecutorFactory.cc
  runtime/onert/core/src/compiler/ExecutorFactory.h
Labels: PR/ready for review

#9796 [luci] Use different name for FQ node
  compiler/luci/pass/src/ConvertToFakeQuantizedModelPass.cpp
Labels: area/quant

#9797 [onert] Change Bulk shape inference batch check
  runtime/onert/core/src/compiler/StaticShapeInferer.cc
Labels: PR/ready for review, trivial, approval: 1

#9637 [nnpkg_tools/qnf] Introduce qnf
  tools/nnpackage_tool/qnf/qnf.md
  tools/nnpackage_tool/qnf/qnf.py
  tools/nnpackage_tool/qnf/requirements.txt
Labels: area/onert

#9803 [luci] Quantize fp32 nodes only
  compiler/luci/pass/src/QuantizationUtils.cpp
  compiler/luci/pass/src/QuantizationUtils.h
  compiler/luci/pass/src/QuantizeActivation.cpp
  compiler/luci/pass/src/QuantizedModelVerifier.test.cpp
Labels: area/quant

#9792 [infra/runtime] Revisit TFLite 2.8 build
  infra/nnfw/cmake/packages/TensorFlowLite-2.8.0/TensorFlowLite/CMakeLists.txt
Labels: PR/ready for review

#9804 [onert/test] Remove boost dependency on NNAPI gtest
  tests/nnapi/CMakeLists.txt
  tests/nnapi/include/NeuralNetworksWrapper.h
  tests/nnapi/src/TestNeuralNetworksWrapper.h
Labels: PR/ready for review

#9805 [luci] Skip checks for S32/S64 Add
  compiler/luci/pass/src/QuantizeWithMinMaxPass.cpp
  compiler/luci/pass/src/QuantizedModelVerifier.test.cpp
  compiler/luci/pass/src/VerifyQuantizedNodeGranularity.h
  compiler/luci/pass/src/VerifyQuantizedNodeType.cpp
Labels: area/quant

#9810 [onecc-docker] onecc subtool error fix
  compiler/onecc-docker/onecc-docker
Labels: PR/ready for review, SSAFY

#9811 [onecc-docker] Update dockerfile_path to onecc-docker
  compiler/onecc-docker/onecc-docker
Labels: SSAFY

#9816 [onecc-docker]Update README
  compiler/onecc-docker/README.md
Labels: PR/ready for review, SSAFY

#9821 [onert] Add some comments in DevContext
  runtime/onert/backend/trix/DevContext.cc
Labels: area/onert, approval: 1

#9759 [luci-micro] Change Logistic kernel to reduce memory consumptions
  compiler/luci-micro/luci-interpreter/src/kernels/Logistic.cpp
  compiler/luci-micro/luci-interpreter/src/kernels/Logistic.h
Labels: approval: 1
