Repository Samsung/ONE, pull requests merged in 2023-02, with the labels that each got.

#10407 [onert] Fix Execution unittest for multi-model
  runtime/onert/core/src/exec/Execution.test.cc
Labels: PR/ready for review

#10405 [onert] Revisit `SingleModelExecutors`
  runtime/onert/core/src/exec/SingleModelExecutors.cc
  runtime/onert/core/src/interp/InterpExecutor.cc
  runtime/onert/core/src/interp/InterpExecutor.h
Labels: PR/ready for review

#10422 [tools/tflitefile_tool] Fix numpy bool type
  tools/tflitefile_tool/parser/tflite/tflite_tensor.py
Labels: PR/ready for review

#10423 [onert] Remove interpreter
  infra/scripts/test_coverage.sh
  infra/scripts/test_ubuntu_runtime.sh
  infra/scripts/tizen_xu4_test.sh
  runtime/onert/api/src/nnfw_api_internal.cc
  runtime/onert/core/include/compiler/CompilerOptions.h
  runtime/onert/core/include/util/Config.lst
  runtime/onert/core/src/compiler/Compiler.cc
  runtime/onert/core/src/compiler/CompilerOptions.cc
  runtime/onert/core/src/compiler/MultiModelCompiler.cc
  runtime/onert/core/src/interp/Buffer.h
  runtime/onert/core/src/interp/ExecEnv.h
  runtime/onert/core/src/interp/InterpExecutor.cc
  runtime/onert/core/src/interp/InterpExecutor.h
  runtime/onert/core/src/interp/InterpExecutor.test.cc
  runtime/onert/core/src/interp/InterpOps.lst
  runtime/onert/core/src/interp/Interpreter.cc
  runtime/onert/core/src/interp/Interpreter.h
  runtime/onert/core/src/interp/Registration.h
  runtime/onert/core/src/interp/Tensor.cc
  runtime/onert/core/src/interp/Tensor.h
  runtime/onert/core/src/interp/operations/BinaryArithmeticOps.cc
  runtime/onert/core/src/interp/operations/Concat.cc
  runtime/onert/core/src/interp/operations/Conv2D.cc
  runtime/onert/core/src/interp/operations/DepthwiseConv2D.cc
  runtime/onert/core/src/interp/operations/ElementwiseActivations.cc
  runtime/onert/core/src/interp/operations/FullyConnected.cc
  runtime/onert/core/src/interp/operations/Gather.cc
  runtime/onert/core/src/interp/operations/InstanceNorm.cc
  runtime/onert/core/src/interp/operations/OperationUtil.h
  runtime/onert/core/src/interp/operations/Pad.cc
  runtime/onert/core/src/interp/operations/Pool2D.cc
  runtime/onert/core/src/interp/operations/Reshape.cc
  runtime/onert/core/src/interp/operations/Softmax.cc
  runtime/onert/core/src/interp/operations/TransposeConv.cc
  tests/nnapi/CMakeLists.txt
  tests/nnapi/nnapi_gtest.skip.noarch.interp
  tests/nnfw_api/src/ValidationTestAddModelLoaded.test.cc
  tests/scripts/list/nnpkg_test_list.noarch.interp
  tests/scripts/list/tflite_comparator.noarch.interp.list
Labels: PR/ready for review, approval: 2

#10424 [onert] Fix using after move
  runtime/onert/core/include/util/Utils.h
Labels: PR/ready for review

#10406 [onert] Introduce `EdgeTensor`
  runtime/onert/core/src/exec/Executors.cc
  runtime/onert/core/src/exec/Executors.h
Labels: PR/ready for review

#10427 [infra] Remove interpreter nnpackage test
  infra/scripts/test_arm_nnpkg.sh
Labels: PR/ready for review

#10429 [Ci] Check repo owner on deploy-github-pages
  .github/workflows/deploy-github-pages.yml
Labels: PR/ready for review

#10428 [infra/dockerfile] Add user account and sudo permission
  infra/docker/bionic/Dockerfile
  infra/docker/focal/Dockerfile
  infra/docker/jammy/Dockerfile
Labels: PR/ready for review

#10435 [circle-opselector] Set proper output
  compiler/circle-opselector/src/OpSelector.cpp
Labels: PR/ready for review

#10447 [circle-opselector] Support multioutput nodes
  compiler/circle-opselector/src/OpSelector.cpp
Labels: PR/ready for review

#10448 [infra/dockerfile] Install sudo in ubuntu 22.04
  infra/docker/jammy/Dockerfile
Labels: PR/ready for review

#10449 [res] Add FullyConnected_009 recipe
  res/TensorFlowLiteRecipes/FullyConnected_009/test.recipe
  res/TensorFlowLiteRecipes/FullyConnected_009/test.reverse
Labels: PR/ready for review

#10433 [onert] Support type-aware quant for nnpkg io
  runtime/onert/api/src/nnfw_api_internal.cc
  runtime/onert/core/include/ir/NNPkg.h
  runtime/onert/core/src/exec/Execution.test.cc
  runtime/onert/core/src/exec/Executors.cc
Labels: PR/ready for review

#10452 [luci] Set keep_num_dims of CircleFullyConnected when cloning
  compiler/luci/service/src/Nodes/CircleFullyConnected.cpp
Labels: PR/ready for review

#10454 [onert] Use forwarding reference in range-based for loop
  runtime/contrib/labs/opencl_test/src/opencl_test.cc
  runtime/libs/benchmark/src/MemoryPoller.cpp
  runtime/onert/backend/acl_cl/KernelGenerator.cc
  runtime/onert/backend/acl_common/AclTensorBuilder.h
  runtime/onert/backend/cl_common/include/cl_common/BackendContext.h
  runtime/onert/backend/cpu/BackendContext.cc
  runtime/onert/backend/cpu/KernelGenerator.cc
  runtime/onert/backend/gpu_cl/BackendContext.cc
  runtime/onert/backend/gpu_cl/KernelGenerator.cc
  runtime/onert/backend/gpu_cl/TensorBuilder.cc
  runtime/onert/backend/ruy/BackendContext.cc
  runtime/onert/backend/trix/BackendContext.cc
  runtime/onert/backend/trix/BatchThreadPool.cc
  runtime/onert/backend/trix/DevContext.cc
  runtime/onert/backend/trix/KernelGenerator.cc
  runtime/onert/backend/xnnpack/BackendContext.cc
  runtime/onert/core/include/backend/basic/BackendContextHelpers.h
  runtime/onert/core/include/exec/FunctionSequence.h
  runtime/onert/core/include/util/ObjectManager.h
  runtime/onert/core/src/backend/basic/MemoryManager.cc
  runtime/onert/core/src/backend/basic/MemoryPlanner.cc
  runtime/onert/core/src/backend/basic/StaticTensorManager.cc
  runtime/onert/core/src/backend/builtin/BackendContext.cc
  runtime/onert/core/src/compiler/Compiler.cc
  runtime/onert/core/src/compiler/ExecutorFactory.cc
  runtime/onert/core/src/compiler/Fp32ToFp16Converter.cc
  runtime/onert/core/src/compiler/HEScheduler.cc
  runtime/onert/core/src/compiler/HEScheduler.test.cc
  runtime/onert/core/src/compiler/ManualScheduler.cc
  runtime/onert/core/src/compiler/MultiModelCompiler.cc
  runtime/onert/core/src/compiler/StaticShapeInferer.cc
  runtime/onert/core/src/compiler/TensorRegistries.h
  runtime/onert/core/src/compiler/pass/OddOutputPass.cc
  runtime/onert/core/src/compiler/pass/PassRunner.cc
  runtime/onert/core/src/compiler/pass/PermutationInsertionPass.cc
  runtime/onert/core/src/exec/ExecutionObservee.cc
  runtime/onert/core/src/exec/ExecutorBase.cc
  runtime/onert/core/src/exec/Executors.cc
  runtime/onert/core/src/exec/ParallelScheduler.cc
  runtime/onert/core/src/exec/ThreadPool.cc
  runtime/onert/core/src/util/ChromeTracingEventWriter.cc
  runtime/onert/core/src/util/MDTableEventWriter.cc
  runtime/onert/core/src/util/SNPEEventWriter.cc
  runtime/service/npud/backend/trix/TrixBackend.cc
  runtime/service/npud/core/ContextManager.cc
Labels: PR/ready for review

#10453 [infra/dockerfile] Add sudoers username
  infra/docker/bionic/Dockerfile
  infra/docker/focal/Dockerfile
  infra/docker/jammy/Dockerfile
Labels: PR/ready for review

#10431 [onert-micro] Add Integer UnidirectionalSequenceLSTM
  onert-micro/helpers/GenerateKernelsListHelper.cpp
  onert-micro/luci-interpreter/pal/mcu/PALUnidirectionalSequenceLSTM.h
  onert-micro/luci-interpreter/src/core/KernelParams.h
  onert-micro/luci-interpreter/src/kernels/UnidirectionalSequenceLSTM.cpp
  onert-micro/luci-interpreter/src/kernels/UnidirectionalSequenceLSTM.h
  onert-micro/luci-interpreter/src/kernels/Utils.cpp
  onert-micro/luci-interpreter/src/kernels/Utils.h
  onert-micro/luci-interpreter/src/loader/nodes/UnidirectionalSequenceLSTM.cpp
Labels: approval: 1

#10457 [onert] Fix io tensors of nnpkg for type-aware quantization
  runtime/onert/core/src/exec/Executors.cc
Labels: PR/ready for review

#10461 [onert] Seperate creating things for type-aware quant of nnpkg io
  runtime/onert/core/src/exec/Executors.cc
  runtime/onert/core/src/exec/Executors.h
Labels: PR/ready for review

#10459 [infra] Add CMSIS-NNConfig
  infra/cmake/packages/CMSIS-NN-4.0.0/CMSIS-NNConfig.cmake
  infra/cmake/packages/CMSIS-NN-4.0.0/CMSIS-NNConfigVersion.cmake
Labels: approval: 2

#10460 [onert-micro] Add CMSIS-NN UnidirectionalSequenceLSTM
  onert-micro/luci-interpreter/pal/cmsisnn/KernelsToBuild.lst
  onert-micro/luci-interpreter/pal/cmsisnn/PALUnidirectionalSequenceLSTM.h
  onert-micro/luci-interpreter/pal/cmsisnn/pal.cmake
Labels: approval: 1

#10466 [debian] Revisit rules
  infra/debian/compiler/rules
Labels: PR/ready for review

#10470 [one-cmds] Support O1 optimization option
  compiler/one-cmds/one-optimize
  compiler/one-cmds/onelib/constant.py
  compiler/one-cmds/onelib/utils.py
Labels: area/quant

#10477 [infra/cmake] Fix TensorFlowLite_FOUND invalid scope
  infra/nnfw/cmake/packages/TensorFlowLite-2.8.0/TensorFlowLiteConfig.cmake
Labels: PR/ready for review

#10476 [infra/cmake] Remove GTest cmake warning
  infra/nnfw/cmake/packages/GTestConfig.cmake
Labels: PR/ready for review, trivial

#10456 [onert] Fix the wrong creation of type-aware quantization.
  runtime/onert/core/src/exec/Executors.cc
  runtime/onert/core/src/exec/Executors.h
Labels: PR/ready for review
