Repository Samsung/ONE, pull requests merged in 2023-07, with the labels that each got.

#10968 [visq] Fix typo in CMakeLists.txt
  compiler/visq/CMakeLists.txt
Labels: area/quant

#10925 [onert] Apply TrainableBackendContext to `train` backend
  runtime/onert/backend/train/Backend.h
  runtime/onert/backend/train/BackendContext.cc
  runtime/onert/backend/train/BackendContext.h
  runtime/onert/backend/train/KernelGenerator.cc
  runtime/onert/backend/train/KernelGenerator.h
Labels: PR/ready for review

#10920 [onert] Create trainable executors
  runtime/onert/core/include/util/Set.h
  runtime/onert/core/src/compiler/ExecutorFactory.cc
  runtime/onert/core/src/compiler/ExecutorFactory.h
Labels: PR/ready for review

#10976 [onert] Include header cstdint
  runtime/libs/benchmark/include/benchmark/CsvWriter.h
  runtime/libs/benchmark/include/benchmark/Phase.h
  runtime/onert/core/src/ir/LayoutSet.h
  runtime/service/npud/core/Backend.h
Labels: PR/ready for review

#10937 [onert] Implement TrainingCompiler
  runtime/onert/core/src/compiler/ExecutorFactory.cc
  runtime/onert/core/src/compiler/train/TrainingCompiler.cc
Labels: PR/ready for review

#10989 [infra] Update Abseil-cpp
  infra/cmake/packages/AbseilSourceConfig.cmake
  packaging/ABSEIL.tar.gz
Labels: PR/ready for review

#10986 [circle2circle] Add --dynamic_batch_to_single_batch option
  compiler/circle2circle/src/Circle2Circle.cpp
Labels: PR/NO MERGE

#10991 [onert] Convert Permute op to trainable operation
  runtime/onert/core/src/compiler/train/LoweredTrainableGraph.cc
Labels: PR/ready for review

#10996 [onert] Change parameter of TrainableOperationConverter
  runtime/onert/core/src/compiler/train/LoweredTrainableGraph.cc
  runtime/onert/core/src/compiler/train/TrainingCompiler.cc
  runtime/onert/core/src/compiler/train/UntrainableOperationConverter.cc
  runtime/onert/core/src/compiler/train/UntrainableOperationConverter.h
Labels: PR/ready for review

#10995 [onert] Initialize variable model_id
  runtime/onert/backend/trix/DevContext.cc
Labels: PR/ready for review

#10961 [onert-micro] Support AveragePool2D kernel
  onert-micro/luci-interpreter/include/luci_interpreter/test_models/average_pool_2d/FloatAveragePool2DKernel.h
  onert-micro/luci-interpreter/include/luci_interpreter/test_models/average_pool_2d/NegAveragePool2DKernel.h
  onert-micro/luci-interpreter/include/luci_interpreter/test_models/average_pool_2d/TestDataAveragePool2DBase.h
  onert-micro/luci-interpreter/pal/mcu/KernelsToBuild.lst
  onert-micro/luci-interpreter/pal/mcu/PALAveragePool2D.h
  onert-micro/luci-interpreter/pal/mcu/PALAveragePool2d.h
  onert-micro/luci-interpreter/src/kernels/AveragePool2D.cpp
  onert-micro/luci-interpreter/src/kernels/AveragePool2D.h
  onert-micro/luci-interpreter/src/kernels/AveragePool2D.test.cpp
Labels: approval: 1

#10963 [onert-micro] Support Elu kernel
  onert-micro/luci-interpreter/include/luci_interpreter/test_models/elu/FloatEluKernel.h
  onert-micro/luci-interpreter/include/luci_interpreter/test_models/elu/NegEluKernel.h
  onert-micro/luci-interpreter/include/luci_interpreter/test_models/elu/TestDataEluBase.h
  onert-micro/luci-interpreter/pal/common/PALElu.h
  onert-micro/luci-interpreter/pal/mcu/KernelsToBuild.lst
  onert-micro/luci-interpreter/src/kernels/Elu.cpp
  onert-micro/luci-interpreter/src/kernels/Elu.h
  onert-micro/luci-interpreter/src/kernels/Elu.test.cpp
  onert-micro/luci-interpreter/src/loader/GraphLoader.cpp
Labels: approval: 1

#10964 [onert-micro] Support Exp kernel
  onert-micro/luci-interpreter/include/luci_interpreter/test_models/exp/FloatExpKernel.h
  onert-micro/luci-interpreter/include/luci_interpreter/test_models/exp/NegExpKernel.h
  onert-micro/luci-interpreter/include/luci_interpreter/test_models/exp/TestDataExpBase.h
  onert-micro/luci-interpreter/pal/common/PALExp.h
  onert-micro/luci-interpreter/pal/mcu/KernelsToBuild.lst
  onert-micro/luci-interpreter/src/kernels/Exp.cpp
  onert-micro/luci-interpreter/src/kernels/Exp.h
  onert-micro/luci-interpreter/src/kernels/Exp.test.cpp
  onert-micro/luci-interpreter/src/loader/GraphLoader.cpp
Labels: approval: 1

#10946 [onert-micro] Support Abs kernel
  onert-micro/luci-interpreter/include/luci_interpreter/test_models/abs/FloatAbsKernel.h
  onert-micro/luci-interpreter/include/luci_interpreter/test_models/abs/NegAbsKernel.h
  onert-micro/luci-interpreter/include/luci_interpreter/test_models/abs/TestDataAbsBase.h
  onert-micro/luci-interpreter/pal/common/PALAbs.h
  onert-micro/luci-interpreter/pal/mcu/KernelsToBuild.lst
  onert-micro/luci-interpreter/src/kernels/Abs.cpp
  onert-micro/luci-interpreter/src/kernels/Abs.test.cpp
  onert-micro/luci-interpreter/src/loader/GraphLoader.cpp
Labels: approval: 1

#10997 [onert] Adjust the position of ITrainableFunction.h
  runtime/onert/backend/train/ops/ConvolutionLayer.h
  runtime/onert/backend/train/ops/PoolLayer.h
  runtime/onert/core/include/backend/train/KernelGeneratorBase.h
  runtime/onert/core/include/exec/train/ITrainableFunction.h
  runtime/onert/core/include/exec/train/TrainableFnSequence.h
  runtime/onert/core/src/backend/builtin/train/kernel/PermuteLayer.h
Labels: PR/ready for review

#10942 [onert] Infer shapes in TrainingCompiler
  runtime/onert/core/include/compiler/ILoweredGraph.h
  runtime/onert/core/include/compiler/LoweredGraph.h
  runtime/onert/core/include/compiler/StaticShapeInferer.h
  runtime/onert/core/include/compiler/train/LoweredTrainableGraph.h
  runtime/onert/core/src/compiler/Compiler.cc
  runtime/onert/core/src/compiler/CompilerHelpers.h
  runtime/onert/core/src/compiler/MultiModelCompiler.cc
  runtime/onert/core/src/compiler/StaticShapeInferer.cc
  runtime/onert/core/src/compiler/train/TrainingCompiler.cc
Labels: PR/ready for review

#11005 [onert] Introduce TensorRegistry into train backend
  runtime/onert/backend/train/TensorRegistry.h
Labels: PR/ready for review

#11010 [onert] Fix incorreclty created TensorRegistries
  runtime/onert/core/src/compiler/ExecutorFactory.cc
Labels: PR/ready for review

#11011 [onert] Remove copy from auto keyword
  runtime/onert/backend/cl_common/include/cl_common/BackendContext.h
  runtime/onert/backend/cpu/BackendContext.cc
  runtime/onert/backend/cpu/KernelGenerator.cc
  runtime/onert/backend/gpu_cl/BackendContext.cc
  runtime/onert/backend/gpu_cl/TensorManager.cc
  runtime/onert/backend/ruy/BackendContext.cc
  runtime/onert/backend/ruy/KernelGenerator.cc
  runtime/onert/backend/trix/BackendContext.cc
  runtime/onert/backend/xnnpack/BackendContext.cc
  runtime/onert/backend/xnnpack/KernelGenerator.cc
  runtime/onert/core/include/util/Set.h
  runtime/onert/core/src/backend/builtin/BackendContext.cc
  runtime/onert/core/src/backend/builtin/KernelGenerator.cc
  runtime/onert/core/src/compiler/ExecutorFactory.cc
  runtime/onert/core/src/compiler/Linear.cc
  runtime/onert/core/src/compiler/LoweredGraph.cc
  runtime/onert/core/src/compiler/ManualScheduler.cc
  runtime/onert/core/src/compiler/StaticShapeInferer.cc
  runtime/onert/core/src/compiler/pass/ConstantInsertionPass.cc
  runtime/onert/core/src/compiler/pass/ConstantLoweringPass.cc
  runtime/onert/core/src/compiler/pass/ConstantOutputPass.cc
  runtime/onert/core/src/compiler/pass/PermutationInsertionPass.cc
  runtime/onert/core/src/compiler/pass/UnusedOperandEliminationPass.cc
  runtime/onert/core/src/dumper/dot/DotBuilder.cc
  runtime/onert/core/src/dumper/dot/DotDumper.cc
  runtime/onert/core/src/dumper/text/GraphDumper.cc
  runtime/onert/core/src/exec/DataflowExecutor.cc
  runtime/onert/core/src/exec/DynamicShapeInferer.cc
  runtime/onert/core/src/exec/ExecutorBase.cc
  runtime/onert/core/src/exec/Executors.cc
  runtime/onert/core/src/exec/LinearExecutor.h
  runtime/onert/core/src/ir/Graph.cc
  runtime/onert/core/src/ir/OperationValidator.cc
  runtime/onert/core/src/ir/verifier/Verifier.cc
  runtime/onert/core/src/util/MDTableEventWriter.cc
  runtime/onert/frontend/nnapi/wrapper/ANeuralNetworksModel.cc
Labels: PR/ready for review

#11008 [onert] Introduce MemoryManager into train backend
  runtime/onert/backend/train/MemoryManager.h
Labels: PR/ready for review

#11006 [onert] Disallow dynamic shape of tensors in train backend.
  runtime/onert/backend/train/Tensor.h
Labels: PR/ready for review

#11015 [onert] Convert some operations to trainable.
  runtime/onert/core/src/compiler/train/TrainableOperationConverter.cc
  runtime/onert/core/src/compiler/train/TrainableOperationConverter.h
Labels: PR/ready for review

#11017 [onert] Use forwarding on range based loop
  compute/ARMComputeEx/src/runtime/CL/functions/CLSplitVEx.cpp
  compute/cker/include/cker/Shape.h
  compute/cker/include/cker/operation/Einsum.h
  compute/ruy/include/ruy/Shape.h
  runtime/libs/benchmark/src/Result.cpp
  runtime/onert/backend/acl_cl/KernelGenerator.cc
  runtime/onert/backend/acl_common/AclTensorManager.h
  runtime/onert/backend/acl_neon/KernelGenerator.cc
  runtime/onert/backend/cl_common/include/cl_common/BackendContext.h
  runtime/onert/backend/cpu/BackendContext.cc
  runtime/onert/backend/cpu/KernelGenerator.cc
  runtime/onert/backend/cpu/ops/OperationUtils.cc
  runtime/onert/backend/gpu_cl/BackendContext.cc
  runtime/onert/backend/gpu_cl/TensorManager.cc
  runtime/onert/backend/ruy/BackendContext.cc
  runtime/onert/backend/ruy/KernelGenerator.cc
  runtime/onert/backend/train/BackendContext.cc
  runtime/onert/backend/train/KernelGenerator.cc
  runtime/onert/backend/trix/BackendContext.cc
  runtime/onert/backend/xnnpack/BackendContext.cc
  runtime/onert/backend/xnnpack/KernelGenerator.cc
  runtime/onert/core/include/util/Set.h
  runtime/onert/core/src/backend/builtin/BackendContext.cc
  runtime/onert/core/src/backend/builtin/kernel/WhileLayer.cc
  runtime/onert/core/src/backend/builtin/train/BackendContext.cc
  runtime/onert/core/src/compiler/ExecutorFactory.cc
  runtime/onert/core/src/compiler/Fp32ToFp16Converter.cc
  runtime/onert/core/src/compiler/HEScheduler.h
  runtime/onert/core/src/compiler/LoweredGraph.cc
  runtime/onert/core/src/compiler/ManualScheduler.cc
  runtime/onert/core/src/compiler/MultiModelCompiler.cc
  runtime/onert/core/src/compiler/StaticShapeInferer.cc
  runtime/onert/core/src/compiler/pass/ConstantOutputPass.cc
  runtime/onert/core/src/compiler/pass/PermutationInsertionPass.cc
  runtime/onert/core/src/compiler/pass/UnusedOperandEliminationPass.cc
  runtime/onert/core/src/compiler/train/LoweredTrainableGraph.cc
  runtime/onert/core/src/dumper/dot/DotBuilder.cc
  runtime/onert/core/src/dumper/dot/DotDumper.cc
  runtime/onert/core/src/dumper/h5/MinMaxDumper.cc
  runtime/onert/core/src/dumper/text/GraphDumper.cc
  runtime/onert/core/src/exec/DataflowExecutor.cc
  runtime/onert/core/src/exec/DynamicShapeInferer.cc
  runtime/onert/core/src/exec/ExecutorBase.cc
  runtime/onert/core/src/exec/Executors.cc
  runtime/onert/core/src/exec/LinearExecutor.h
  runtime/onert/core/src/exec/ParallelScheduler.cc
  runtime/onert/core/src/exec/train/TrainableExecutor.cc
  runtime/onert/core/src/ir/Graph.cc
  runtime/onert/core/src/ir/LayoutSet.cc
  runtime/onert/core/src/ir/OperandIndexSequence.cc
  runtime/onert/core/src/ir/OperationValidator.cc
  runtime/onert/core/src/ir/verifier/Verifier.cc
  runtime/onert/core/src/util/MDTableEventWriter.cc
  runtime/onert/frontend/nnapi/wrapper/ANeuralNetworksModel.cc
  runtime/service/npud/backend/trix/TrixBackend.cc
Labels: PR/ready for review

#10945 [onert] Introduce StaticGradientShapeInfer
  runtime/onert/core/src/compiler/train/StaticGradientShapeInferer.cc
  runtime/onert/core/src/compiler/train/StaticGradientShapeInferer.h
  runtime/onert/core/src/compiler/train/TrainingCompiler.cc
Labels: PR/ready for review

#11013 [onert] Separate NativeTensor of TensorRegistry in train backend
  runtime/onert/backend/train/TensorRegistry.h
Labels: PR/ready for review

#11007 [onert] Introduce TrainableTensor
  runtime/onert/backend/train/Tensor.cc
  runtime/onert/backend/train/Tensor.h
  runtime/onert/core/include/backend/train/ITrainableTensor.h
Labels: PR/ready for review

#11026 [onert] Replace Tensor with TrainableTensor
  runtime/onert/backend/train/TensorRegistry.h
Labels: PR/ready for review

#11028 [onert] Ignore GCC warning
  infra/nnfw/cmake/buildtool/config/config_linux.cmake
Labels: PR/ready for review

#10988 [tools/onert_train] Add input and expected datafile arguments
  tests/tools/onert_train/src/args.cc
  tests/tools/onert_train/src/args.h
Labels: PR/ready for review

#11034 [one-cmds] Overwriting commands over given configuration on one-profile
  compiler/one-cmds/dummy-driver/CMakeLists.txt
  compiler/one-cmds/dummy-driver/src/dummyV3-profile.cpp
  compiler/one-cmds/one-profile
  compiler/one-cmds/tests/one-profile_neg_002.test
  compiler/one-cmds/tests/one-profile_neg_003.test
  compiler/one-cmds/tests/one-profile_neg_004.cfg
  compiler/one-cmds/tests/one-profile_neg_004.test
  compiler/one-cmds/tests/one-profile_neg_005.test
  compiler/one-cmds/tests/onecc_056.cfg
  compiler/one-cmds/tests/onecc_056.test
  compiler/one-cmds/tests/onecc_057.cfg
  compiler/one-cmds/tests/onecc_057.test
Labels: PR/ready for review

#11032 [onert] Add train kernels to the TrainableFnSequence
  runtime/onert/backend/train/KernelGenerator.cc
Labels: PR/ready for review

#11030 [onert] Introduce train function in Execution
  runtime/onert/core/include/exec/Execution.h
  runtime/onert/core/src/exec/Execution.cc
Labels: PR/ready for review

#11043 [onert] Rename gradient
  runtime/onert/backend/train/Backend.h
  runtime/onert/backend/train/BackendContext.cc
  runtime/onert/backend/train/BackendContext.h
  runtime/onert/backend/train/KernelGenerator.cc
  runtime/onert/backend/train/KernelGenerator.h
  runtime/onert/core/include/backend/train/TrainableBackendContext.h
  runtime/onert/core/src/backend/builtin/Backend.h
  runtime/onert/core/src/backend/builtin/train/BackendContext.cc
  runtime/onert/core/src/backend/builtin/train/BackendContext.h
  runtime/onert/core/src/backend/builtin/train/KernelGenerator.cc
  runtime/onert/core/src/backend/builtin/train/KernelGenerator.h
  runtime/onert/core/src/compiler/ExecutorFactory.cc
  runtime/onert/core/src/compiler/TensorRegistries.h
  runtime/onert/core/src/compiler/train/StaticDerivativeShapeInferer.cc
  runtime/onert/core/src/compiler/train/StaticDerivativeShapeInferer.h
  runtime/onert/core/src/compiler/train/TrainingCompiler.cc
  runtime/onert/core/src/dumper/dot/DotDumper.cc
Labels: PR/ready for review

#11009 [onert] Introduce TensorManager into train backend
  runtime/onert/backend/train/TensorManager.cc
  runtime/onert/backend/train/TensorManager.h
Labels: PR/ready for review

#11048 [onert] Support hybrid quantization type fix on loader
  runtime/onert/frontend/base_loader/include/base_loader.h
Labels: PR/ready for review

#10990 [tools/onert_train] Prepare input and expected data for nnfw_train
  tests/tools/onert_train/src/onert_train.cc
Labels: PR/ready for review

#11044 [onert] Refine TrainableTensor
  runtime/onert/backend/train/Tensor.cc
  runtime/onert/backend/train/Tensor.h
  runtime/onert/core/include/backend/train/ITrainableTensor.h
Labels: PR/ready for review

#11024 [luci/pass] Introduce GeluPatternBase
  compiler/luci/pass/src/FuseGeluPass.cpp
Labels: approval: 2

#11021 [luci/pass] Change names in FuseGeluPass.test
  compiler/luci/pass/src/FuseGeluPass.test.cpp
Labels: approval: 2

#11025 [onert] Add derivative info to TrainableGraph
  runtime/onert/core/include/ir/train/TrainableGraph.h
  runtime/onert/core/src/compiler/train/StaticDerivativeShapeInferer.cc
  runtime/onert/core/src/compiler/train/StaticDerivativeShapeInferer.h
  runtime/onert/core/src/ir/train/TrainableGraph.cc
Labels: PR/ready for review

#11029 [tools/onert_train] Support multiple input in rawdataloader test
  tests/tools/onert_train/test/rawdataloader.test.cc
Labels: PR/ready for review

#11031 [onert] Implement train_run function in nnfw internal api
  runtime/onert/api/src/nnfw_api_internal.cc
Labels: PR/ready for review

#11060 [luci/pass] Rename GeluPattern to GeluPattern1
  compiler/luci/pass/src/FuseGeluPass.cpp
Labels: approval: 1

#11070 [onert] Add assertion that checks nullptr
  runtime/onert/core/src/backend/basic/Tensor.cc
Labels: PR/ready for review

#11066 [onert] Refine TrainableTensor
  runtime/onert/backend/train/Tensor.h
  runtime/onert/core/include/backend/basic/train/TrainableTensor.h
  runtime/onert/core/include/backend/train/ITrainableTensor.h
  runtime/onert/core/src/backend/basic/train/TrainableTensor.cc
Labels: PR/ready for review

#11067 [onert] Introduce ITensorRegistry for training
  runtime/onert/core/include/backend/train/ITensorRegistry.h
Labels: PR/ready for review

#11064 [onert] Introduce OptimizerCode
  runtime/onert/core/include/exec/train/optimizer/OptimizerCode.h
  runtime/onert/core/src/exec/train/optimizer/OptimizerCode.cc
Labels: PR/ready for review

#11068 [onert] Introduce TensorRegistries for training
  runtime/onert/core/src/compiler/train/TensorRegistries.h
Labels: PR/ready for review

#11069 [onert] Introduce builtin TensorRegistry for training
  runtime/onert/core/src/backend/builtin/train/Tensor.h
  runtime/onert/core/src/backend/builtin/train/TensorRegistry.h
Labels: PR/ready for review

#11071 [onert] Introduce Optimizer
  runtime/onert/core/include/exec/train/optimizer/Optimizer.h
Labels: PR/ready for review

#11076 [onert] Intoroduce OptimizerHelpers
  runtime/onert/core/src/exec/train/optimizer/OptimizerHelpers.h
Labels: PR/ready for review

#11075 [onert] Introduce SGD optimizer
  runtime/onert/core/include/exec/train/optimizer/SGD.h
  runtime/onert/core/src/exec/train/optimizer/SGD.cc
Labels: PR/ready for review

#11062 [luci/pass] Revise GeluPattern1 to inherit from GeluPatternBase
  compiler/luci/pass/src/FuseGeluPass.cpp
Labels: approval: 1

#11082 [luci-interpreter] Revise arm target architecture selection method during kernel build
  compiler/luci-interpreter/pal/linux/pal.cmake
Labels: PR/ready for review

#11049 [onecc-docker] Use onecc version with a certain format
  compiler/onecc-docker/onecc-docker
Labels: PR/ready for review

#11084 [onert] Create SGD optimizer
  runtime/onert/core/include/compiler/train/TrainingInfo.h
  runtime/onert/core/src/compiler/train/TrainingCompiler.cc
Labels: PR/ready for review

#11086 [onert] Change TensorRegistry in builtin backend
  runtime/onert/core/src/backend/builtin/Backend.h
  runtime/onert/core/src/backend/builtin/TensorBuilder.cc
  runtime/onert/core/src/backend/builtin/TensorBuilder.h
  runtime/onert/core/src/backend/builtin/train/KernelGenerator.cc
  runtime/onert/core/src/backend/builtin/train/KernelGenerator.h
Labels: PR/ready for review

#11087 [onert] Implement train Permute kernel
  runtime/onert/core/src/backend/builtin/train/KernelGenerator.cc
  runtime/onert/core/src/backend/builtin/train/kernel/PermuteLayer.cc
  runtime/onert/core/src/backend/builtin/train/kernel/PermuteLayer.h
Labels: PR/ready for review

#11083 [onert] Introduce unified TensorBuilder into train backend
  runtime/onert/backend/train/Backend.h
  runtime/onert/backend/train/BackendContext.cc
  runtime/onert/backend/train/BackendContext.h
  runtime/onert/backend/train/KernelGenerator.cc
  runtime/onert/backend/train/KernelGenerator.h
  runtime/onert/backend/train/Tensor.h
  runtime/onert/backend/train/TensorBuilder.cc
  runtime/onert/backend/train/TensorBuilder.h
  runtime/onert/backend/train/TensorManager.cc
  runtime/onert/backend/train/TensorManager.h
  runtime/onert/backend/train/TensorRegistry.h
Labels: PR/ready for review

#11095 [debian] Update changelog
  infra/debian/compiler/changelog
Labels: type/release

#11094 Release note 1.24.0
  docs/release/1.24/index.rst
  docs/release/1.24/release-note-1.24.0.md
Labels: type/release

#11096 [tools/onert_train] Change Loss function type
  tests/tools/onert_train/src/args.cc
  tests/tools/onert_train/src/args.h
Labels: PR/ready for review

#11053 [oops] Add requires.cmake
  compiler/oops/requires.cmake
Labels: PR/ready for review

#11101 [luci/pass] Revise FuseGelu class
  compiler/luci/pass/src/FuseGeluPass.cpp
Labels: approval: 1

#11103 [vconone] Bump up to 1.25.0
  compiler/vconone/CMakeLists.txt
Labels: PR/ready for review

#11100 [onert] Allow train backend to allocate memory for outputs
  runtime/onert/core/src/compiler/ExecutorFactory.cc
Labels: PR/ready for review

#11102 [onert] Remove Permute op from outputs of trainable graph
  runtime/onert/core/src/compiler/train/LoweredTrainableGraph.cc
  runtime/onert/core/src/compiler/train/pass/PermutationInsertionPass.cc
  runtime/onert/core/src/compiler/train/pass/PermutationInsertionPass.h
Labels: PR/ready for review

#11098 [onert] Unify TensorRegistry for training
  runtime/onert/backend/train/Backend.h
  runtime/onert/backend/train/BackendContext.cc
  runtime/onert/backend/train/BackendContext.h
  runtime/onert/backend/train/KernelGenerator.cc
  runtime/onert/backend/train/KernelGenerator.h
  runtime/onert/backend/train/TensorBuilder.cc
  runtime/onert/backend/train/TensorBuilder.h
  runtime/onert/core/include/backend/train/TrainableBackendContext.h
  runtime/onert/core/src/backend/builtin/train/BackendContext.cc
  runtime/onert/core/src/backend/builtin/train/BackendContext.h
  runtime/onert/core/src/backend/builtin/train/KernelGenerator.cc
  runtime/onert/core/src/backend/builtin/train/KernelGenerator.h
  runtime/onert/core/src/backend/builtin/train/TensorRegistry.h
  runtime/onert/core/src/compiler/ExecutorFactory.cc
  runtime/onert/core/src/compiler/TensorRegistries.h
  runtime/onert/core/src/exec/train/TrainableExecutor.cc
  runtime/onert/core/src/exec/train/TrainableExecutor.h
Labels: PR/ready for review

#11097 [onert] Add NNFW_TRAIN_LOSS enum to nnfw experimental api
  runtime/onert/api/include/nnfw_experimental.h
Labels: PR/ready for review

#11093 [onert] Set optimizer as SGD
  runtime/onert/api/src/nnfw_api_internal.cc
Labels: PR/ready for review

#11078 [onert] Implement train_set_input in nnfw api
  runtime/onert/api/src/nnfw_api_internal.cc
Labels: PR/ready for review

#11104 [tools/onert_train] Change Optimizer type
  tests/tools/onert_train/src/args.cc
  tests/tools/onert_train/src/args.h
Labels: PR/ready for review

#11105 [onert] Introduce MEAN_SQUARED_ERROR to Loss operation
  runtime/onert/core/include/ir/operation/Loss.h
  runtime/onert/core/src/ir/operation/Loss.cc
Labels: PR/ready for review

#11106 [onert] Implement LossInsertionPass
  runtime/onert/core/include/compiler/train/TrainingInfo.h
  runtime/onert/core/src/compiler/train/TrainingCompiler.cc
  runtime/onert/core/src/compiler/train/pass/LossInsertionPass.cc
Labels: PR/ready for review

#11107 [onert] Implement Loss visitor function in OperationDumper
  runtime/onert/core/src/ir/OperationDumper.cc
  runtime/onert/core/src/ir/OperationDumper.h
Labels: PR/ready for review

#11108 [onert] Implement Loss visitor function in StaticShapeInferer
  runtime/onert/core/include/compiler/StaticShapeInferer.h
  runtime/onert/core/src/compiler/StaticShapeInferer.cc
Labels: PR/ready for review

#11092 [onert] Refine TrainableBackendContext in builtin backend
  runtime/onert/core/src/backend/builtin/train/BackendContext.cc
  runtime/onert/core/src/backend/builtin/train/BackendContext.h
Labels: PR/ready for review

#11091 [onert] Pass optimizer to KernelGenerator
  runtime/onert/backend/train/Backend.h
  runtime/onert/backend/train/KernelGenerator.cc
  runtime/onert/backend/train/KernelGenerator.h
  runtime/onert/core/include/backend/train/TrainableBackendContext.h
  runtime/onert/core/src/compiler/ExecutorFactory.cc
  runtime/onert/core/src/compiler/ExecutorFactory.h
  runtime/onert/core/src/compiler/train/TrainingCompiler.cc
Labels: PR/ready for review

#11110 [onert] Infer derivative shape of Permute
  runtime/onert/core/src/compiler/train/StaticDerivativeShapeInferer.cc
Labels: PR/ready for review

#11079 [onert] Introduce ElementwiseActivationLayer in train kernel
  runtime/onert/backend/train/KernelGenerator.cc
  runtime/onert/backend/train/KernelGenerator.h
  runtime/onert/backend/train/ops/ElementwiseActivationLayer.cc
  runtime/onert/backend/train/ops/ElementwiseActivationLayer.h
Labels: PR/ready for review

#11120 [onert] Include builtin train tensor registry in trainable executor
  runtime/onert/core/src/compiler/ExecutorFactory.cc
Labels: PR/ready for review

#11116 [onert] Introduce NNFW_TRAIN_OPTIMIZER enum to nnfw experimental api
  runtime/onert/api/include/nnfw_experimental.h
Labels: PR/ready for review

#11123 [onert] Change input shape after loss insertion pass
  runtime/onert/api/src/nnfw_api_internal.cc
  runtime/onert/core/src/compiler/StaticShapeInferer.cc
  runtime/onert/core/src/compiler/train/TrainingCompiler.cc
Labels: PR/ready for review

#11133 [tflchef] Introduce ErfChef and ErfChefFactory
  compiler/tflchef/core/src/CustomOp/Erf.cpp
  compiler/tflchef/core/src/CustomOp/Erf.h
Labels: approval: 1

#11140 [loco] Install CanonicalNodes.lst file
  compiler/loco/CMakeLists.txt
Labels: PR/ready for review

#11142 [luci/pass] Revise RequantizePass
  compiler/luci/pass/src/RequantizePass.cpp
  compiler/luci/pass/src/RequantizePass.test.cpp
Labels: area/quant

#11127 [luci/pass] Introduce GeluPattern2
  compiler/luci/pass/src/FuseGeluPass.cpp
Labels: approval: 2

#11143 [luci] Remove unnecessary codes
  compiler/luci/pass/src/RequantizePass.cpp
Labels: area/quant

#11115 [tools/onert_train] Use loss type argument
  tests/tools/onert_train/src/onert_train.cc
Labels: PR/ready for review

#11150 [luci] Revise RequantizePass
  compiler/luci/pass/include/luci/Pass/RequantizePass.h
  compiler/luci/pass/src/RequantizePass.cpp
Labels: area/quant

#11125 [onert] Remove creating IOTensors of outputs
  runtime/onert/core/src/compiler/ExecutorFactory.cc
Labels: PR/ready for review

#11128 [onert] Initialize TrainableTensors in train backend
  runtime/onert/backend/train/BackendContext.cc
  runtime/onert/core/include/backend/basic/train/TrainableBackendContextHelpers.h
Labels: PR/ready for review

#11111 [onert] Introduce training step
  runtime/onert/api/src/nnfw_api_internal.cc
  runtime/onert/api/src/nnfw_api_internal.h
  runtime/onert/backend/train/ops/ConvolutionLayer.cc
  runtime/onert/backend/train/ops/ConvolutionLayer.h
  runtime/onert/backend/train/ops/ElementwiseActivationLayer.cc
  runtime/onert/backend/train/ops/ElementwiseActivationLayer.h
  runtime/onert/backend/train/ops/PoolLayer.cc
  runtime/onert/backend/train/ops/PoolLayer.h
  runtime/onert/core/include/exec/Execution.h
  runtime/onert/core/include/exec/train/ITrainableFunction.h
  runtime/onert/core/include/exec/train/TrainableFnSequence.h
  runtime/onert/core/src/backend/builtin/train/kernel/PermuteLayer.cc
  runtime/onert/core/src/backend/builtin/train/kernel/PermuteLayer.h
  runtime/onert/core/src/exec/Execution.cc
  runtime/onert/core/src/exec/train/TrainableExecutor.cc
  runtime/onert/core/src/exec/train/TrainableExecutor.h
  runtime/onert/core/src/exec/train/TrainableExecutors.cc
  runtime/onert/core/src/exec/train/TrainableExecutors.h
  runtime/onert/core/src/exec/train/TrainableFnSequence.cc
Labels: PR/ready for review

#11151 [luci/pass] Revise FuseGelu to use GeluPattern2
  compiler/luci/pass/src/FuseGeluPass.cpp
Labels: approval: 1

#11153 [onert] Add checking output in StaticDerivativeShapeInferer
  runtime/onert/core/src/compiler/train/StaticDerivativeShapeInferer.cc
  runtime/onert/core/src/compiler/train/StaticDerivativeShapeInferer.h
Labels: PR/ready for review

#11135 [onert] Introduce GradientApplier layer
  runtime/onert/backend/train/KernelGenerator.cc
  runtime/onert/backend/train/KernelGenerator.h
  runtime/onert/backend/train/ops/GradientApplier.cc
  runtime/onert/backend/train/ops/GradientApplier.h
Labels: PR/ready for review

#11124 [onert] Exclude copies of derivative inputs of model
  runtime/onert/core/src/backend/builtin/train/KernelGenerator.cc
  runtime/onert/core/src/backend/builtin/train/kernel/PermuteLayer.cc
  runtime/onert/core/src/compiler/ExecutorFactory.cc
Labels: PR/ready for review

#11161 [infra] Install visq Dot builder lib
  infra/debian/compiler/one-compiler.install
Labels: area/quant

#11160 [res] Add int8 recipes and rules
  res/TensorFlowLiteRecipes/Quant_Add_I8_000/test.recipe
  res/TensorFlowLiteRecipes/Quant_Add_I8_000/test.rule
  res/TensorFlowLiteRecipes/Quant_AveragePool2D_I8_000/test.recipe
  res/TensorFlowLiteRecipes/Quant_AveragePool2D_I8_000/test.rule
  res/TensorFlowLiteRecipes/Quant_Conv_I8_000/test.recipe
  res/TensorFlowLiteRecipes/Quant_Conv_I8_000/test.rule
  res/TensorFlowLiteRecipes/Quant_DepthwiseConv2D_I8_000/test.recipe
  res/TensorFlowLiteRecipes/Quant_DepthwiseConv2D_I8_000/test.rule
  res/TensorFlowLiteRecipes/Quant_MaxPool2D_I8_000/test.recipe
  res/TensorFlowLiteRecipes/Quant_MaxPool2D_I8_000/test.rule
  res/TensorFlowLiteRecipes/Quant_Mean_I8_000/test.recipe
  res/TensorFlowLiteRecipes/Quant_Mean_I8_000/test.rule
  res/TensorFlowLiteRecipes/Quant_Mul_I8_000/test.recipe
  res/TensorFlowLiteRecipes/Quant_Mul_I8_000/test.rule
  res/TensorFlowLiteRecipes/Quant_PRelu_I8_000/test.recipe
  res/TensorFlowLiteRecipes/Quant_PRelu_I8_000/test.rule
  res/TensorFlowLiteRecipes/Quant_ReLU_I8_000/test.recipe
  res/TensorFlowLiteRecipes/Quant_ReLU_I8_000/test.rule
  res/TensorFlowLiteRecipes/Quant_TransposeConv_I8_000/test.recipe
  res/TensorFlowLiteRecipes/Quant_TransposeConv_I8_000/test.rule
Labels: area/quant

#11166 [circle-quantizer-dredd] Add requantize tests
  compiler/circle-quantizer-dredd-recipe-test/CMakeLists.txt
  compiler/circle-quantizer-dredd-recipe-test/test.lst
Labels: area/quant

#11165 [onert] Update version to 1.25.0
  docs/conf.py
  packaging/nnfw.spec
  runtime/contrib/android/api/build.gradle
  runtime/onert/api/include/nnfw_version.h
Labels: PR/ready for review

#11167 [one-cmds] Add requantize option to one-quantize
  compiler/one-cmds/one-quantize
Labels: area/quant

#11168 [one-cmds] Add requantize tests
  compiler/one-cmds/tests/one-quantize_017.test
  compiler/one-cmds/tests/one-quantize_neg_022.test
  compiler/one-cmds/tests/onecc_058.cfg
  compiler/one-cmds/tests/onecc_058.test
  compiler/one-cmds/tests/prepare_test_materials.sh
Labels: area/quant

#11118 [onert] Use try block in train_prepare
  runtime/onert/api/src/nnfw_api_internal.cc
Labels: PR/ready for review

#11126 [onert] Compare tensor size in train_set_input
  runtime/onert/api/src/nnfw_api_internal.cc
Labels: PR/ready for review

#11136 [onecc-docker] Set timeout
  compiler/onecc-docker/onecc-docker
Labels: PR/ready for review

#11176 [luci/lang] Support HardSwish operation
  compiler/luci/lang/include/luci/IR/CircleNodes.h
  compiler/luci/lang/include/luci/IR/CircleNodes.lst
  compiler/luci/lang/include/luci/IR/Nodes/CircleHardSwish.h
  compiler/luci/lang/src/Nodes/CircleHardSwish.test.cpp
Labels: PR/ready for review

#11119 [onert] Set loss info to training info
  runtime/onert/api/src/nnfw_api_internal.cc
Labels: PR/ready for review

#11171 [tools/onert_train] Use optimizer type argument
  tests/tools/onert_train/src/onert_train.cc
Labels: PR/ready for review

#11121 [infra] Introduce nncc tizen build option and config
  infra/nncc/cmake/buildtool/config/config_aarch64-tizen.cmake
  infra/nncc/cmake/buildtool/config/config_armv7hl-tizen.cmake
  infra/nncc/cmake/buildtool/config/config_armv7l-tizen.cmake
  infra/nncc/cmake/buildtool/config/config_i686-tizen.cmake
  infra/nncc/cmake/buildtool/config/config_x86_64-tizen.cmake
  infra/nncc/cmake/options/options_aarch64-tizen.cmake
  infra/nncc/cmake/options/options_armv7hl-tizen.cmake
  infra/nncc/cmake/options/options_armv7l-tizen.cmake
  infra/nncc/cmake/options/options_i686-tizen.cmake
  infra/nncc/cmake/options/options_x86_64-tizen.cmake
Labels: PR/ready for review

#11169 [onert] Introduce LossLayer in train kernel
  runtime/onert/backend/train/KernelGenerator.cc
  runtime/onert/backend/train/ops/LossLayer.cc
  runtime/onert/backend/train/ops/LossLayer.h
Labels: PR/ready for review

#11170 [onert] Insert default derivative operands
  runtime/onert/core/src/compiler/train/TrainingCompiler.cc
Labels: PR/ready for review

#11175 [tflchef] Support HardSwish operation
  compiler/tflchef/core/src/Op/HardSwish.cpp
  compiler/tflchef/core/src/Op/HardSwish.h
  compiler/tflchef/core/src/OpChef.def
  compiler/tflchef/core/src/OpChefs.h
  compiler/tflchef/tflite/src/Op/HardSwish.cpp
  compiler/tflchef/tflite/src/Op/include/HardSwish.h
  compiler/tflchef/tflite/src/TFliteOpChefs.h
  compiler/tflchef/tflite/src/TFliteOpRegistry.h
Labels: PR/ready for review

#11183 [onert] Set optimizer info to training info
  runtime/onert/api/src/nnfw_api_internal.cc
Labels: PR/ready for review

#11182 [luci/export] Support HardSwish operation
  compiler/luci/export/src/CircleBuiltinTypesExtractor.h
  compiler/luci/export/src/CircleOps.lst
Labels: PR/ready for review

#11114 [tools/onert_train] Do not multiply batch_size to tensor info
  tests/tools/onert_train/src/onert_train.cc
  tests/tools/onert_train/src/rawdataloader.cc
  tests/tools/onert_train/test/rawdataloader.test.cc
Labels: PR/ready for review

#10947 [onert-micro] Support AddN kernel
  onert-micro/luci-interpreter/include/luci_interpreter/test_models/add_n/FloatAddNKernel.h
  onert-micro/luci-interpreter/include/luci_interpreter/test_models/add_n/NegAddNKernel.h
  onert-micro/luci-interpreter/include/luci_interpreter/test_models/add_n/TestDataAddNBase.h
  onert-micro/luci-interpreter/pal/common/PALAddN.h
  onert-micro/luci-interpreter/pal/mcu/KernelsToBuild.lst
  onert-micro/luci-interpreter/src/kernels/AddN.cpp
  onert-micro/luci-interpreter/src/kernels/AddN.test.cpp
Labels: approval: 1

#10962 [onert-micro] Support Div kernel
  onert-micro/luci-interpreter/include/luci_interpreter/test_models/div/FloatDivKernel.h
  onert-micro/luci-interpreter/include/luci_interpreter/test_models/div/NegDivKernel.h
  onert-micro/luci-interpreter/include/luci_interpreter/test_models/div/TestDataDivBase.h
  onert-micro/luci-interpreter/pal/mcu/KernelsToBuild.lst
  onert-micro/luci-interpreter/pal/mcu/PALDiv.h
  onert-micro/luci-interpreter/src/kernels/Div.cpp
  onert-micro/luci-interpreter/src/kernels/Div.h
  onert-micro/luci-interpreter/src/kernels/Div.test.cpp
Labels: approval: 1

#10965 [onert-micro] Support Relu, Relu6, Leaky_Relu kernels
  onert-micro/luci-interpreter/include/luci_interpreter/test_models/leaky_relu/FloatLeakyReLUKernel.h
  onert-micro/luci-interpreter/include/luci_interpreter/test_models/leaky_relu/NegLeakyReLUKernel.h
  onert-micro/luci-interpreter/include/luci_interpreter/test_models/leaky_relu/TestDataLeakyReLUBase.h
  onert-micro/luci-interpreter/include/luci_interpreter/test_models/relu/FloatReLUKernel.h
  onert-micro/luci-interpreter/include/luci_interpreter/test_models/relu/NegReLUKernel.h
  onert-micro/luci-interpreter/include/luci_interpreter/test_models/relu/TestDataReLUBase.h
  onert-micro/luci-interpreter/include/luci_interpreter/test_models/relu6/FloatReLU6Kernel.h
  onert-micro/luci-interpreter/include/luci_interpreter/test_models/relu6/NegReLU6Kernel.h
  onert-micro/luci-interpreter/include/luci_interpreter/test_models/relu6/TestDataReLU6Base.h
  onert-micro/luci-interpreter/pal/common/PALReluCommon.h
  onert-micro/luci-interpreter/pal/mcu/KernelsToBuild.lst
  onert-micro/luci-interpreter/pal/mcu/PALLeakyRelu.h
  onert-micro/luci-interpreter/src/kernels/LeakyRelu.cpp
  onert-micro/luci-interpreter/src/kernels/LeakyRelu.h
  onert-micro/luci-interpreter/src/kernels/LeakyRelu.test.cpp
  onert-micro/luci-interpreter/src/kernels/Relu.cpp
  onert-micro/luci-interpreter/src/kernels/Relu.h
  onert-micro/luci-interpreter/src/kernels/Relu.test.cpp
  onert-micro/luci-interpreter/src/kernels/Relu6.cpp
  onert-micro/luci-interpreter/src/kernels/Relu6.h
  onert-micro/luci-interpreter/src/kernels/Relu6.test.cpp
  onert-micro/luci-interpreter/src/loader/GraphLoader.cpp
Labels: approval: 1

#10999 [onert-micro] Support Pad, PadV2 kernels
  onert-micro/luci-interpreter/include/luci_interpreter/test_models/pad/FloatPadKernel.h
  onert-micro/luci-interpreter/include/luci_interpreter/test_models/pad/NegPadKernel.h
  onert-micro/luci-interpreter/include/luci_interpreter/test_models/pad/TestDataPadBase.h
  onert-micro/luci-interpreter/include/luci_interpreter/test_models/pad_v2/FloatPadV2Kernel.h
  onert-micro/luci-interpreter/include/luci_interpreter/test_models/pad_v2/NegPadV2Kernel.h
  onert-micro/luci-interpreter/include/luci_interpreter/test_models/pad_v2/TestDataPadV2Base.h
  onert-micro/luci-interpreter/pal/common/PALPad.h
  onert-micro/luci-interpreter/pal/common/Params.h
  onert-micro/luci-interpreter/pal/mcu/KernelsToBuild.lst
  onert-micro/luci-interpreter/src/kernels/CMakeLists.txt
  onert-micro/luci-interpreter/src/kernels/Pad.cpp
  onert-micro/luci-interpreter/src/kernels/Pad.test.cpp
  onert-micro/luci-interpreter/src/kernels/PadCommon.cpp
  onert-micro/luci-interpreter/src/kernels/PadCommon.h
  onert-micro/luci-interpreter/src/kernels/PadV2.cpp
  onert-micro/luci-interpreter/src/kernels/PadV2.h
  onert-micro/luci-interpreter/src/kernels/PadV2.test.cpp
Labels: approval: 1

#11181 [luci/import] Support HardSwish operation
  compiler/luci/import/include/luci/Import/Nodes.h
  compiler/luci/import/include/luci/Import/Nodes/CircleHardSwish.h
  compiler/luci/import/src/GraphBuilderRegistry.cpp
  compiler/luci/import/src/Nodes/CircleHardSwish.cpp
Labels: PR/ready for review

#11185 [luci/service] Support HardSwish operation
  compiler/luci/service/include/luci/Service/CircleShapeInference.h
  compiler/luci/service/include/luci/Service/CircleTypeInference.h
  compiler/luci/service/src/CircleCloneNode.h
  compiler/luci/service/src/CircleShapeInferenceRule.cpp
  compiler/luci/service/src/CircleTypeInferenceRule.cpp
  compiler/luci/service/src/Nodes/CircleHardSwish.cpp
  compiler/luci/service/src/Nodes/CircleHardSwish.test.cpp
Labels: PR/ready for review
