Repository Samsung/ONE, pull requests merged in 2023-04, with the labels that each got.

#10591 [one-cmds] Compile multiple backends with a single cfg file
  compiler/one-cmds/dummy-driver/CMakeLists.txt
  compiler/one-cmds/dummy-driver/src/dummyV2-compile.cpp
  compiler/one-cmds/one-codegen
  compiler/one-cmds/onecc
  compiler/one-cmds/onelib/CfgRunner.py
  compiler/one-cmds/tests/onecc_046.cfg
  compiler/one-cmds/tests/onecc_046.test
  compiler/one-cmds/tests/onecc_047.cfg
  compiler/one-cmds/tests/onecc_047.test
  compiler/one-cmds/tests/onecc_048.cfg
  compiler/one-cmds/tests/onecc_048.test
  compiler/one-cmds/tests/onecc_neg_027.cfg
  compiler/one-cmds/tests/onecc_neg_027.test
  compiler/one-cmds/tests/onecc_neg_028.cfg
  compiler/one-cmds/tests/onecc_neg_028.test
  compiler/one-cmds/tests/onecc_neg_029.cfg
  compiler/one-cmds/tests/onecc_neg_029.test
  compiler/one-cmds/tests/onecc_neg_030.cfg
  compiler/one-cmds/tests/onecc_neg_030.test
  compiler/one-cmds/tests/onecc_neg_031.test
  compiler/one-cmds/tests/onecc_neg_031.workflow.json
Labels: PR/ready for review

#10597 [circle-opselector] Remove assert
  compiler/circle-opselector/driver/Driver.cpp
Labels: PR/ready for review

#10598 [one-cmds] Remove deprecated function
  compiler/one-cmds/onelib/utils.py
Labels: PR/ready for review

#10602 [luci] Verify quantization of Sum
  compiler/luci/pass/src/QuantizedModelVerifier.test.cpp
  compiler/luci/pass/src/VerifyQuantizedNodeGranularity.h
  compiler/luci/pass/src/VerifyQuantizedNodeType.cpp
  compiler/luci/pass/src/VerifyQuantizedNodeType.h
Labels: area/quant

#10601 [luci] Support Sum in fake quantization
  compiler/luci/pass/src/ConvertToFakeQuantizedModelPass.cpp
Labels: area/quant

#10600 [luci-interpreter] Support Sum kernel on Linux
  compiler/luci-interpreter/pal/linux/KernelsToBuild.lst
  compiler/luci-interpreter/src/kernels/Sum.cpp
  compiler/luci-interpreter/src/kernels/Sum.h
  compiler/luci-interpreter/src/kernels/Sum.test.cpp
  compiler/luci-interpreter/src/loader/nodes/Sum.cpp
Labels: area/quant

#10603 [luci] Add more fake quantization Ops
  compiler/luci/pass/src/ConvertToFakeQuantizedModelPass.cpp
Labels: area/quant

#10611 [luci] Fix bug in ConvertNCHWToNHWCPass
  compiler/luci/pass/src/ConvertNCHWToNHWCPass.cpp
Labels: area/quant

#10599 [one-cmds] Verify backend option in onecc
  compiler/one-cmds/onecc
Labels: PR/ready for review

#10614 [onert/test] Fix meaningless test
  runtime/libs/ndarray/src/ContiguousSpan.test.cpp
Labels: PR/ready for review

#10626 [onert] Fix negative index bug
  runtime/onert/core/src/exec/Executors.cc
Labels: PR/ready for review

#10627 [luci] Fix Quantize Op insertion in QuantizeWithMinMaxPass
  compiler/luci/pass/src/QuantizeWithMinMaxPass.cpp
Labels: area/quant

#10628 [onert] Fix negative index bug
  runtime/onert/core/src/exec/Executors.cc
Labels: PR/ready for review

#10639 [onert] Add negative TC for StridedSlice
  tests/nnfw_api/src/one_op_tests/StridedSlice.test.cc
Labels: PR/ready for review

#10640 [onert] Add negative TC for Reverse
  tests/nnfw_api/src/one_op_tests/Reverse.test.cc
Labels: PR/ready for review

#10631 [onert] Update version to 1.22.1
  docs/conf.py
  packaging/nnfw.spec
  runtime/contrib/android/api/build.gradle
  runtime/onert/api/include/nnfw_version.h
Labels: PR/ready for review

#9156 [nnpackage] Update schema
  nnpackage/schema/circle_schema.fbs
Labels: PR/ready for review

#10657 [infra] Add tf2nnpkg for preset 20230413
  infra/packaging/res/tf2nnpkg.20230413
Labels: PR/ready for review

#10656 [onert] Remove ExecutionEvent{Emitter,Listener}
  runtime/onert/core/src/exec/ExecutionEventEmitter.cc
  runtime/onert/core/src/exec/ExecutionEventEmitter.h
  runtime/onert/core/src/exec/IExecutionEventEmitter.h
  runtime/onert/core/src/exec/IExecutionEventListener.h
Labels: approval: 1

#10658 [onert/test] Fix meaningless test
  runtime/libs/ndarray/src/ContiguousSpan.test.cpp
Labels: PR/ready for review

#10664 [onert] Update generated header
  runtime/onert/frontend/circle_schema/include/circle_schema_generated.h
  runtime/onert/frontend/tflite/src/tflite_schema_generated.h
  runtime/onert/frontend/tflite/tflite_schema.fbs
Labels: PR/ready for review

#10682 [onert-micro] Add missing kernels in GenerateKernelsListHelper
  onert-micro/helpers/GenerateKernelsListHelper.cpp
Labels: approval: 1

#10716 [onert] Release note for 1.22.1
  docs/release/1.22/release-note-1.22.1.md
Labels: PR/ready for review

#10684 [onert-micro] Move kernels list to rodata section
  onert-micro/CMakeLists.txt
  onert-micro/luci-interpreter/pal/mcu/pal.cmake
  onert-micro/luci-interpreter/src/core/RuntimeGraph.cpp
  onert-micro/luci-interpreter/src/kernels/Builders.h
  onert-micro/luci-interpreter/src/kernels/KernelBuilder.cpp
  onert-micro/luci-interpreter/src/kernels/KernelBuilder.h
Labels: approval: 2

#10712 [onert-micro] Support StridedSlice kernel
  onert-micro/luci-interpreter/include/luci_interpreter/test_models/strided_slice/StridedSliceKernel.h
  onert-micro/luci-interpreter/pal/mcu/KernelsToBuild.lst
  onert-micro/luci-interpreter/src/kernels/MISOKernel.h
  onert-micro/luci-interpreter/src/kernels/StridedSlice.cpp
  onert-micro/luci-interpreter/src/kernels/StridedSlice.h
  onert-micro/luci-interpreter/src/kernels/StridedSlice.test.cpp
Labels: approval: 1
