Repository Samsung/ONE, pull requests merged in 2023-01, with the labels that each got.

#10228 [record-minmax] Add parallel recording
  compiler/record-minmax/CMakeLists.txt
  compiler/record-minmax/driver/Driver.cpp
  compiler/record-minmax/include/MinMaxObserver.h
  compiler/record-minmax/include/RecordMinMax.h
  compiler/record-minmax/src/RecordMinMax.cpp
Labels: approval: 2

#10267 [tools/model2nnpkg] Fix incorrectly generating metadata
  tools/nnpackage_tool/model2nnpkg/model2nnpkg.py
Labels: PR/ready for review

#10265 [onert] Introduce MultiModelCompiler
  runtime/onert/core/include/compiler/Compiler.h
  runtime/onert/core/src/compiler/Compiler.cc
  runtime/onert/core/src/compiler/CompilerFactory.cc
Labels: PR/ready for review

#10271 [circle-mpqsolver] Add fusedActivationFunction
  compiler/circle-mpqsolver/src/bisection/Quantizer.test.cpp
Labels: area/quant

#10178 [doxygen] Update doxygen config file
  infra/doxygen/Doxyfile
Labels: PR/ready for review

#10274 [one-cmds] Install python model2nnpkg
  compiler/one-cmds/CMakeLists.txt
Labels: PR/ready for review

#10275 [onert] Fix inclusion guard typo
  runtime/onert/core/src/compiler/MultiModelCompiler.h
Labels: PR/ready for review, trivial, approval: 1

#10282 [model2nnpkg] Handling exception
  tools/nnpackage_tool/model2nnpkg/model2nnpkg.py
Labels: PR/ready for review

#10280 [onert] Introduce IExecutors
  runtime/onert/core/include/compiler/ICompiler.h
  runtime/onert/core/include/exec/Execution.h
  runtime/onert/core/include/exec/IExecutors.h
  runtime/onert/core/src/backend/builtin/KernelGenerator.h
  runtime/onert/core/src/backend/builtin/kernel/IfLayer.cc
  runtime/onert/core/src/backend/builtin/kernel/IfLayer.h
  runtime/onert/core/src/backend/builtin/kernel/WhileLayer.cc
  runtime/onert/core/src/backend/builtin/kernel/WhileLayer.h
  runtime/onert/core/src/compiler/Compiler.cc
  runtime/onert/core/src/compiler/ExecutorFactory.cc
  runtime/onert/core/src/compiler/ExecutorFactory.h
  runtime/onert/core/src/compiler/MultiModelCompiler.cc
  runtime/onert/core/src/exec/Execution.cc
  runtime/onert/core/src/exec/Execution.test.cc
  runtime/onert/core/src/exec/ExecutionObservers.h
  runtime/onert/core/src/exec/Executors.cc
  runtime/onert/core/src/exec/Executors.h
  runtime/onert/core/src/interp/InterpExecutor.test.cc
  runtime/onert/frontend/nnapi/execution.cc
  runtime/onert/frontend/nnapi/wrapper/ANeuralNetworksCompilation.h
  runtime/onert/frontend/nnapi/wrapper/ANeuralNetworksExecution.h
Labels: PR/ready for review

#10278 [one-cmds] Add model input argument
  compiler/one-cmds/one-pack
Labels: PR/ready for review

#10289 [tools] Update using model2nnpkg
  tools/nnpackage_tool/nncc-tc-to-nnpkg-tc/nncc-tc-to-nnpkg-tc.sh
  tools/nnpackage_tool/sth2nnpkgtc/pb2nnpkgtc.sh
  tools/nnpackage_tool/sth2nnpkgtc/tflite2nnpkgtc.sh
Labels: PR/ready for review

#10279 [infra] Fix tf2nnpkg.20221125
  infra/packaging/res/tf2nnpkg.20221125
Labels: PR/ready for review

#10293 [tools/doc] Add prerequisite for model2nnpkg
  tools/nnpackage_tool/model2nnpkg/README.md
  tools/nnpackage_tool/nncc-tc-to-nnpkg-tc/README.md
Labels: PR/ready for review

#10297 [common-artifacts] Install pydot libraray
  compiler/common-artifacts/CMakeLists.txt
Labels: area/quant

#10299 [pota-quantization] Add parallel record-minmax test
  compiler/pota-quantization-value-test/CMakeLists.txt
  compiler/pota-quantization-value-test/test_parallel_record_minmax.sh
Labels: PR/NO MERGE, approval: 2

#10298 [one-cmds] Install pydot on onecc venv
  compiler/one-cmds/one-prepare-venv
Labels: area/quant

#10308 [infra] Add pics to compiler_modules.sh
  infra/scripts/compiler_modules.sh
Labels: PR/ready for review

#10296 [onert] Enhance supporting multi-model
  runtime/onert/core/include/ir/NNPkg.h
  runtime/onert/core/src/exec/Executors.cc
Labels: PR/ready for review

#10309 [onert] Revisit IExecutors and derivered
  runtime/onert/core/include/exec/IExecutors.h
  runtime/onert/core/src/exec/Executors.cc
  runtime/onert/core/src/exec/Executors.h
Labels: PR/ready for review

#10300 [record-minmax] Create record-minmax-for-thread-test target
  compiler/record-minmax/CMakeLists.txt
Labels: approval: 2

#10314 [one-cmds] Introduce Environment section
  compiler/one-cmds/dummy-driver/CMakeLists.txt
  compiler/one-cmds/dummy-driver/src/dummyEnv-compile.cpp
  compiler/one-cmds/onecc.template.cfg
  compiler/one-cmds/onelib/CfgRunner.py
  compiler/one-cmds/tests/onecc_042.cfg
  compiler/one-cmds/tests/onecc_042.test
Labels: PR/ready for review

#10312 [onert] Add comment in IExecutors.h
  runtime/onert/core/include/exec/IExecutors.h
Labels: PR/ready for review

#10315 [one-cmds] Introduce Command.py
  compiler/one-cmds/one-quantize
  compiler/one-cmds/onelib/Command.py
  compiler/one-cmds/utils.py
Labels: PR/ready for review

#10316 [debian] Add Command.py to install list
  infra/debian/compiler/one-compiler.install
Labels: PR/ready for review

#10301 [visq] Add DotBuilder module
  compiler/visq/CMakeLists.txt
  compiler/visq/requires.cmake
  compiler/visq/test/testDotBuilder.py
  compiler/visq/visqlib/DotBuilder.py
Labels: area/quant

#10321 [one-cmds] Revisit function naming in utils.py
  compiler/one-cmds/one-build
  compiler/one-cmds/one-codegen
  compiler/one-cmds/one-import
  compiler/one-cmds/one-import-bcq
  compiler/one-cmds/one-import-onnx
  compiler/one-cmds/one-import-pytorch
  compiler/one-cmds/one-import-tf
  compiler/one-cmds/one-import-tflite
  compiler/one-cmds/one-infer
  compiler/one-cmds/one-init
  compiler/one-cmds/one-optimize
  compiler/one-cmds/one-pack
  compiler/one-cmds/one-partition
  compiler/one-cmds/one-profile
  compiler/one-cmds/one-quantize
  compiler/one-cmds/onecc
  compiler/one-cmds/onelib/CfgRunner.py
  compiler/one-cmds/onelib/Command.py
  compiler/one-cmds/onelib/WorkflowRunner.py
  compiler/one-cmds/onelib/make_cmd.py
  compiler/one-cmds/utils.py
Labels: PR/ready for review

#10328 [visq] Remove unittests
  compiler/visq/CMakeLists.txt
  compiler/visq/requires.cmake
  compiler/visq/test/__init__.py
  compiler/visq/test/testDotBuilder.py
  compiler/visq/test/testPalette.py
  compiler/visq/test/testQErrorComputer.py
  compiler/visq/test/testUtil.py
Labels: area/quant

#10320 [visq] Add --dump_dot_graph option
  compiler/visq/README.md
  compiler/visq/visq
Labels: area/quant

#10310 [luci-interpreter] Add ReduceProd op
  compiler/luci-interpreter/pal/linux/KernelsToBuild.lst
  compiler/luci-interpreter/src/kernels/ReduceProd.cpp
  compiler/luci-interpreter/src/kernels/ReduceProd.h
  compiler/luci-interpreter/src/kernels/ReduceProd.test.cpp
  compiler/luci-interpreter/src/loader/nodes/ReduceProd.cpp
Labels: approval: 2

#10307 [record-minmax-thread-safety-test] Introduce thread safety test
  compiler/record-minmax-thread-safety-test/CMakeLists.txt
  compiler/record-minmax-thread-safety-test/gen_h5_random_inputs.py
  compiler/record-minmax-thread-safety-test/requires.cmake
  compiler/record-minmax-thread-safety-test/test.lst
  compiler/record-minmax-thread-safety-test/testall.sh
Labels: approval: 2

#10330 [one-cmds] Move utils.py into onelib dir
  compiler/one-cmds/CMakeLists.txt
  compiler/one-cmds/one-build
  compiler/one-cmds/one-codegen
  compiler/one-cmds/one-import
  compiler/one-cmds/one-import-bcq
  compiler/one-cmds/one-import-onnx
  compiler/one-cmds/one-import-pytorch
  compiler/one-cmds/one-import-tf
  compiler/one-cmds/one-import-tflite
  compiler/one-cmds/one-infer
  compiler/one-cmds/one-init
  compiler/one-cmds/one-optimize
  compiler/one-cmds/one-pack
  compiler/one-cmds/one-partition
  compiler/one-cmds/one-profile
  compiler/one-cmds/one-quantize
  compiler/one-cmds/onecc
  compiler/one-cmds/onelib/CfgRunner.py
  compiler/one-cmds/onelib/Command.py
  compiler/one-cmds/onelib/WorkflowRunner.py
  compiler/one-cmds/onelib/utils.py
Labels: PR/ready for review

#10331 [debian] Move utils.py into onelib dir
  infra/debian/compiler/one-compiler.install
Labels: PR/ready for review

#10332 [visq-unittest] Initialize visq-unittest module
  compiler/visq-unittest/CMakeLists.txt
  compiler/visq-unittest/README.md
  compiler/visq-unittest/requires.cmake
  compiler/visq-unittest/test/__init__.py
  compiler/visq-unittest/test/testDotBuilder.py
  compiler/visq-unittest/test/testPalette.py
  compiler/visq-unittest/test/testQErrorComputer.py
  compiler/visq-unittest/test/testUtil.py
Labels: area/quant

#10334 [one-cmds] Get right optimization list
  compiler/one-cmds/onelib/utils.py
Labels: PR/ready for review

#10333 [onert-micro] Fix building on armv8-m
  onert-micro/luci-interpreter/pal/mcu/PALBatchToSpaceND.h
  onert-micro/luci-interpreter/pal/mcu/PALConv2d.h
  onert-micro/luci-interpreter/pal/mcu/PALResizeBilinear.h
  onert-micro/luci-interpreter/pal/mcu/PALResizeNearestNeighbor.h
  onert-micro/luci-interpreter/pal/mcu/PALSoftmax.h
  onert-micro/luci-interpreter/pal/mcu/PALSpaceToBatchND.h
  onert-micro/luci-interpreter/src/kernels/DepthwiseConv2D.cpp
  onert-micro/luci-interpreter/src/kernels/TransposeConv.cpp
  onert-micro/luci-interpreter/src/kernels/Utils.cpp
Labels: approval: 1

#10340 [infra] Update excluded files on coverage report
  infra/command/gen-coverage-report
Labels: PR/ready for review

#10341 [cker] Introduce optimized kernels for quantization
  compute/cker/include/cker/operation/Quantize.h
  compute/cker/include/cker/operation/Round.h
  runtime/onert/core/src/exec/IPermuteFunction.cc
Labels: PR/ready for review

#10337 [one-cmds] Use no-verbose option for materials download
  compiler/one-cmds/tests/prepare_test_materials.sh
Labels: PR/ready for review

#10342 [onert] Support type-aware quantization of non-portable tensors
  runtime/onert/core/src/exec/IPermuteFunction.cc
Labels: PR/ready for review

#10343 [visq] Use quoted node name
  compiler/visq-unittest/test/testDotBuilder.py
  compiler/visq/visqlib/DotBuilder.py
Labels: area/quant

#10350 [onert] Introduce `IPermuteFunction` unittest
  runtime/onert/core/src/exec/IPermuteFunction.test.cc
Labels: PR/ready for review

#10353 [visq] Support multiple data
  compiler/visq/visqlib/QErrorComputer.py
Labels: area/quant

#10354 [visq-unittest] Add multi data test
  compiler/visq-unittest/test/testQErrorComputer.py
Labels: area/quant

#10338 [infra] Remove unused CI scripts
  infra/scripts/build_android_runtime_release.sh
  infra/scripts/docker_build_cross_aarch64_runtime.sh
  infra/scripts/docker_build_cross_arm_compiler_debug.sh
  infra/scripts/docker_build_cross_arm_runtime.sh
  infra/scripts/docker_build_cross_arm_runtime_release.sh
  infra/scripts/docker_build_cross_coverage.sh
  infra/scripts/docker_build_test_x64.sh
  infra/scripts/docker_build_tizen_cross.sh
  infra/scripts/docker_build_tizen_gbs.sh
  infra/scripts/docker_coverage_report.sh
Labels: PR/ready for review

#10355 [onert] Support NCHW layout for type-aware quantization
  runtime/onert/core/src/exec/IPermuteFunction.cc
  runtime/onert/core/src/exec/IPermuteFunction.test.cc
Labels: PR/ready for review

#10369 [visq-unittest] Remove redundant log
  compiler/visq-unittest/test/testUtil.py
Labels: area/quant

#10373 [onert-micro] Fix inplace optimization loader
  onert-micro/luci-interpreter/src/loader/GraphLoader.cpp
Labels: approval: 1

#10386 [onert-micro] Support variable and intermediate tensors
  onert-micro/luci-interpreter/src/core/RuntimeGraph.cpp
  onert-micro/luci-interpreter/src/core/RuntimeGraph.h
  onert-micro/luci-interpreter/src/loader/GraphLoader.cpp
  onert-micro/luci-interpreter/src/loader/GraphLoader.h
  onert-micro/luci-interpreter/src/loader/ModuleLoader.cpp
Labels: approval: 1

#10360 [onert] Support type-aware quantization for multi-model
  runtime/onert/core/include/exec/IExecutor.h
  runtime/onert/core/src/backend/builtin/IOTensor.h
  runtime/onert/core/src/exec/Execution.test.cc
  runtime/onert/core/src/exec/ExecutorBase.h
  runtime/onert/core/src/exec/Executors.cc
  runtime/onert/core/src/exec/Executors.h
  runtime/onert/core/src/interp/InterpExecutor.h
Labels: PR/ready for review

#10388 [luci] Quantize inactive inputs
  compiler/luci/pass/src/QuantizeWithMinMaxPass.cpp
  compiler/luci/pass/src/QuantizeWithMinMaxPass.test.cpp
Labels: area/quant

#10400 [onert-micro] Introduce UnidirectionalSequenceLSTMParams
  onert-micro/luci-interpreter/src/core/KernelParams.h
Labels: approval: 1

#10401 [onert-micro] Introduce getTfLiteActivation
  onert-micro/luci-interpreter/src/kernels/Utils.h
Labels: approval: 1
