Repository Samsung/ONE, pull requests merged in 2023-05, with the labels that each got.

#10756 [luci] Quantize Gelu Op
  compiler/luci/pass/src/ConvertToFakeQuantizedModelPass.cpp
  compiler/luci/pass/src/QuantizeActivation.cpp
  compiler/luci/pass/src/QuantizeActivation.h
  compiler/luci/pass/src/VerifyQuantizedNodeGranularity.h
  compiler/luci/pass/src/VerifyQuantizedNodeType.cpp
  compiler/luci/pass/src/VerifyQuantizedNodeType.h
Labels: area/quant

#10736 [onert] Revisit ShapeLoop
  runtime/onert/core/include/util/Utils.h
Labels: PR/ready for review

#10764 [luci] Support mixed-precision quantization of Gelu
  compiler/luci/pass/src/QuantizeWithMinMaxPass.cpp
Labels: area/quant

#10771 [onert-micro] Fix MISO kernel
  onert-micro/luci-interpreter/src/kernels/MISOKernel.h
Labels: approval: 1

#10775 [onert-micro] Enable test coverage
  onert-micro/luci-interpreter/src/kernels/CMakeLists.txt
Labels: approval: 1

#10696 [onert-micro] Add FullyConnected unit test
  onert-micro/luci-interpreter/include/luci_interpreter/test_models/fully_connected/FloatFullyConnectedKernel.h
  onert-micro/luci-interpreter/include/luci_interpreter/test_models/fully_connected/TestDataFullyConnectedBase.h
  onert-micro/luci-interpreter/include/luci_interpreter/test_models/fully_connected/U8FullyConnectedKernel.h
  onert-micro/luci-interpreter/src/kernels/FullyConnected.test.cpp
Labels: approval: 1

#10697 [onert-micro] Add Logistic unit test
  onert-micro/luci-interpreter/include/luci_interpreter/test_models/logistic/FloatLogisticKernel.h
  onert-micro/luci-interpreter/include/luci_interpreter/test_models/logistic/TestDataLogisticBase.h
  onert-micro/luci-interpreter/src/kernels/Logistic.test.cpp
Labels: approval: 1

#10724 [onert-micro] Add Sub unit test
  onert-micro/luci-interpreter/include/luci_interpreter/test_models/sub/FloatSubKernel.h
  onert-micro/luci-interpreter/include/luci_interpreter/test_models/sub/IntSubKernel.h
  onert-micro/luci-interpreter/include/luci_interpreter/test_models/sub/TestDataSubBase.h
  onert-micro/luci-interpreter/src/kernels/Sub.h
  onert-micro/luci-interpreter/src/kernels/Sub.test.cpp
Labels: approval: 1

#10809 [debian] Update changelog
  infra/debian/compiler/changelog
Labels: type/release

#10807 [onecc-docker] Change the release name of one-compiler in docker file
  compiler/onecc-docker/docker/Dockerfile
Labels: PR/ready for review

#10810 Release note 1.23.0
  docs/release/1.23/index.rst
  docs/release/1.23/release-note-1.23.0.md
Labels: type/release

#10812 [vconone] Bump up to 1.24.0
  compiler/vconone/CMakeLists.txt
Labels: PR/ready for review

#10790 [onert] Make cpu backend position independent shared library.
  runtime/onert/backend/cpu/CMakeLists.txt
Labels: PR/ready for review

#10791 [onert] Choose memory planner
  runtime/onert/core/include/backend/basic/StaticTensorManager.h
  runtime/onert/core/include/backend/basic/TensorBuilder.h
  runtime/onert/core/src/backend/basic/StaticTensorManager.cc
  runtime/onert/core/src/backend/basic/TensorBuilder.cc
Labels: PR/ready for review

#10708 [onert-micro] Support Fill kernel
  onert-micro/luci-interpreter/include/luci_interpreter/test_models/fill/FillKernel.h
  onert-micro/luci-interpreter/pal/mcu/KernelsToBuild.lst
  onert-micro/luci-interpreter/src/kernels/Fill.cpp
  onert-micro/luci-interpreter/src/kernels/Fill.h
  onert-micro/luci-interpreter/src/kernels/Fill.test.cpp
Labels: approval: 1

#10711 [onert-micro] Support Transpose kernel
  onert-micro/luci-interpreter/include/luci_interpreter/test_models/transpose/TransposeKernel.h
  onert-micro/luci-interpreter/pal/mcu/KernelsToBuild.lst
  onert-micro/luci-interpreter/src/kernels/Shape.test.cpp
  onert-micro/luci-interpreter/src/kernels/Transpose.cpp
  onert-micro/luci-interpreter/src/kernels/Transpose.h
  onert-micro/luci-interpreter/src/kernels/Transpose.test.cpp
Labels: approval: 1

#10713 [onert-micro] Support SplitV kernel
  onert-micro/helpers/GenerateKernelsListHelper.cpp
  onert-micro/luci-interpreter/include/luci_interpreter/test_models/split_v/SplitVKernel.h
  onert-micro/luci-interpreter/pal/mcu/KernelsToBuild.lst
  onert-micro/luci-interpreter/src/kernels/Split.cpp
  onert-micro/luci-interpreter/src/kernels/Split.h
  onert-micro/luci-interpreter/src/kernels/SplitV.cpp
  onert-micro/luci-interpreter/src/kernels/SplitV.h
  onert-micro/luci-interpreter/src/kernels/SplitV.test.cpp
Labels: approval: 1

#10818 [onert-micro] Add Conv2D unit test
  onert-micro/luci-interpreter/include/luci_interpreter/test_models/conv2d/FloatConv2DKernel.h
  onert-micro/luci-interpreter/include/luci_interpreter/test_models/conv2d/TestDataConv2DBase.h
  onert-micro/luci-interpreter/include/luci_interpreter/test_models/conv2d/U8Conv2DKernel.h
  onert-micro/luci-interpreter/src/kernels/Conv2D.test.cpp
Labels: approval: 1

#10822 [onert-micro] Introduce kernels without TF
  onert-micro/luci-interpreter/pal/mcu/PALApplyActivationToVector.h
  onert-micro/luci-interpreter/pal/mcu/PALConv2d.h
  onert-micro/luci-interpreter/pal/mcu/PALFullyConnected.h
  onert-micro/luci-interpreter/pal/mcu/PALMul.h
  onert-micro/luci-interpreter/pal/mcu/PALSoftmax.h
  onert-micro/luci-interpreter/pal/mcu/PALSub.h
  onert-micro/luci-interpreter/pal/mcu/PALUnidirectionalSequenceLSTM.h
  onert-micro/luci-interpreter/pal/mcu/pal.cmake
  onert-micro/luci-interpreter/src/core/RuntimeGraph.cpp
  onert-micro/luci-interpreter/src/core/RuntimeGraph.h
  onert-micro/luci-interpreter/src/kernels/Add.cpp
  onert-micro/luci-interpreter/src/kernels/BinaryOpCommon.h
  onert-micro/luci-interpreter/src/kernels/CMakeLists.txt
  onert-micro/luci-interpreter/src/kernels/Concatenation.cpp
  onert-micro/luci-interpreter/src/kernels/Conv2D.cpp
  onert-micro/luci-interpreter/src/kernels/FullyConnected.cpp
  onert-micro/luci-interpreter/src/kernels/Less.cpp
  onert-micro/luci-interpreter/src/kernels/Logistic.cpp
  onert-micro/luci-interpreter/src/kernels/MaxPool2D.cpp
  onert-micro/luci-interpreter/src/kernels/Mul.cpp
  onert-micro/luci-interpreter/src/kernels/ReduceCommon.cpp
  onert-micro/luci-interpreter/src/kernels/Reshape.cpp
  onert-micro/luci-interpreter/src/kernels/Slice.cpp
  onert-micro/luci-interpreter/src/kernels/Softmax.cpp
  onert-micro/luci-interpreter/src/kernels/StridedSlice.cpp
  onert-micro/luci-interpreter/src/kernels/Sub.cpp
  onert-micro/luci-interpreter/src/kernels/TISOKernel.h
  onert-micro/luci-interpreter/src/kernels/Tanh.cpp
  onert-micro/luci-interpreter/src/kernels/Transpose.cpp
  onert-micro/luci-interpreter/src/kernels/UnidirectionalSequenceLSTM.cpp
  onert-micro/luci-interpreter/src/kernels/UnidirectionalSequenceLSTM.h
  onert-micro/luci-interpreter/src/kernels/Utils.cpp
  onert-micro/luci-interpreter/src/kernels/Utils.h
Labels: approval: 1

#10699 [onert-micro] Add Reshape unit test
  onert-micro/luci-interpreter/include/luci_interpreter/test_models/reshape/ReshapeKernel.h
  onert-micro/luci-interpreter/src/kernels/Reshape.test.cpp
Labels: approval: 1

#10698 [onert-micro] Add ExpandDims unit test
  onert-micro/luci-interpreter/include/luci_interpreter/test_models/expand_dims/ExpandDimsKernel.h
  onert-micro/luci-interpreter/src/kernels/ExpandDims.test.cpp
Labels: approval: 1

#10831 [onert-micro] Add UnidirectionalSequenceLSTM unit tests
  onert-micro/luci-interpreter/include/luci_interpreter/test_models/unidirectional_lstm/FloatUnidirectionalLSTMKernel.h
  onert-micro/luci-interpreter/include/luci_interpreter/test_models/unidirectional_lstm/QuantS8UnidirectionalLSTM.h
  onert-micro/luci-interpreter/include/luci_interpreter/test_models/unidirectional_lstm/TestDataUnidirectionalLSTMBase.h
  onert-micro/luci-interpreter/src/kernels/UnidirectionalSequenceLSTM.test.cpp
Labels: approval: 1

#10829 [onert-micro] Add Gather unit tests
  onert-micro/luci-interpreter/include/luci_interpreter/test_models/gather/FloatGatherKernel.h
  onert-micro/luci-interpreter/include/luci_interpreter/test_models/gather/IntGatherKernel.h
  onert-micro/luci-interpreter/include/luci_interpreter/test_models/gather/TestDataGatherBase.h
  onert-micro/luci-interpreter/src/kernels/Gather.h
  onert-micro/luci-interpreter/src/kernels/Gather.test.cpp
Labels: approval: 1

#10830 [onert-micro] Add Tanh unit tests
  onert-micro/luci-interpreter/include/luci_interpreter/test_models/tanh/FloatTanhKernel.h
  onert-micro/luci-interpreter/include/luci_interpreter/test_models/tanh/TestDataTanhBase.h
  onert-micro/luci-interpreter/src/kernels/Tanh.h
  onert-micro/luci-interpreter/src/kernels/Tanh.test.cpp
Labels: approval: 1

#10836 [onert-micro] Add Slice unit tests
  onert-micro/luci-interpreter/include/luci_interpreter/test_models/slice/FloatSliceKernel.h
  onert-micro/luci-interpreter/include/luci_interpreter/test_models/slice/QuantS16SliceKernel.h
  onert-micro/luci-interpreter/include/luci_interpreter/test_models/slice/QuantU8SliceKernel.h
  onert-micro/luci-interpreter/include/luci_interpreter/test_models/slice/TestDataSliceBase.h
  onert-micro/luci-interpreter/src/kernels/Slice.h
  onert-micro/luci-interpreter/src/kernels/Slice.test.cpp
Labels: approval: 1

#10838 [onert-micro] Add Concatenation unit tests
  onert-micro/luci-interpreter/include/luci_interpreter/test_models/concatenation/FloatConcatenationKernel.h
  onert-micro/luci-interpreter/include/luci_interpreter/test_models/concatenation/IntConcatenationKernel.h
  onert-micro/luci-interpreter/include/luci_interpreter/test_models/concatenation/TestDataConcatenationBase.h
  onert-micro/luci-interpreter/src/kernels/Concatenation.test.cpp
Labels: approval: 1

#10839 [onert-micro] Add Split unit tests
  onert-micro/luci-interpreter/include/luci_interpreter/test_models/split/FloatSplitKernel.h
  onert-micro/luci-interpreter/include/luci_interpreter/test_models/split/IntSplitKernel.h
  onert-micro/luci-interpreter/include/luci_interpreter/test_models/split/TestDataSplitBase.h
  onert-micro/luci-interpreter/src/kernels/Split.test.cpp
Labels: approval: 1

#10840 [onert-micro] Add NEG test for ExpandDims, Reshape, Less
  onert-micro/luci-interpreter/include/luci_interpreter/test_models/expand_dims/ExpandDimsKernel.h
  onert-micro/luci-interpreter/include/luci_interpreter/test_models/less/FloatLessKernel.h
  onert-micro/luci-interpreter/include/luci_interpreter/test_models/less/IntLessKernel.h
  onert-micro/luci-interpreter/include/luci_interpreter/test_models/less/NegTestDataLessKernel.h
  onert-micro/luci-interpreter/include/luci_interpreter/test_models/less/QuantLessKernel.h
  onert-micro/luci-interpreter/include/luci_interpreter/test_models/reshape/ReshapeKernel.h
  onert-micro/luci-interpreter/src/kernels/ExpandDims.test.cpp
  onert-micro/luci-interpreter/src/kernels/Less.test.cpp
  onert-micro/luci-interpreter/src/kernels/Reshape.test.cpp
Labels: approval: 1

#10842 [onert-micro] Add NEG test for MaxPool2D, Concatenation, Mul
  onert-micro/luci-interpreter/include/luci_interpreter/test_models/concatenation/NegConcatenationKernel.h
  onert-micro/luci-interpreter/include/luci_interpreter/test_models/maxpool2d/NegMaxPool2DKernel.h
  onert-micro/luci-interpreter/include/luci_interpreter/test_models/mul/NegMulKernel.h
  onert-micro/luci-interpreter/src/kernels/Concatenation.test.cpp
  onert-micro/luci-interpreter/src/kernels/MaxPool2D.test.cpp
  onert-micro/luci-interpreter/src/kernels/Mul.test.cpp
Labels: approval: 1

#10806 [tools/onert_train] Introduce onert_train tool
  infra/nnfw/cmake/CfgOptionFlags.cmake
  tests/tools/onert_train/CMakeLists.txt
  tests/tools/onert_train/README.md
  tests/tools/onert_train/src/allocation.h
  tests/tools/onert_train/src/args.cc
  tests/tools/onert_train/src/args.h
  tests/tools/onert_train/src/formatter.h
  tests/tools/onert_train/src/h5formatter.cc
  tests/tools/onert_train/src/h5formatter.h
  tests/tools/onert_train/src/nnfw_util.cc
  tests/tools/onert_train/src/nnfw_util.h
  tests/tools/onert_train/src/onert_train.cc
  tests/tools/onert_train/src/randomgen.cc
  tests/tools/onert_train/src/randomgen.h
  tests/tools/onert_train/src/rawformatter.cc
  tests/tools/onert_train/src/rawformatter.h
  tests/tools/onert_train/src/types.h
Labels: PR/ready for review

#10826 [onert] Implement convolution layer in train backend
  runtime/onert/backend/train/KernelGenerator.cc
  runtime/onert/backend/train/KernelGenerator.h
  runtime/onert/backend/train/ops/ConvolutionLayer.cc
  runtime/onert/backend/train/ops/ConvolutionLayer.h
Labels: area/onert

#10849 [onert-micro] Add While unit tests
  onert-micro/luci-interpreter/include/luci_interpreter/test_models/TestDataBase.h
  onert-micro/luci-interpreter/include/luci_interpreter/test_models/while/NegWhileKernel.h
  onert-micro/luci-interpreter/include/luci_interpreter/test_models/while/WhileKernel.h
  onert-micro/luci-interpreter/src/kernels/While.h
  onert-micro/luci-interpreter/src/kernels/While.test.cpp
Labels: approval: 1

#10851 [onert-micro] Refactor NEG unit tests
  onert-micro/luci-interpreter/include/luci_interpreter/test_models/add/NegAddKernel.h
  onert-micro/luci-interpreter/include/luci_interpreter/test_models/add/U8AddKernel.h
  onert-micro/luci-interpreter/include/luci_interpreter/test_models/concatenation/NegConcatenationKernel.h
  onert-micro/luci-interpreter/include/luci_interpreter/test_models/conv2d/NegConv2DKernel.h
  onert-micro/luci-interpreter/include/luci_interpreter/test_models/conv2d/S32Conv2DKernel.h
  onert-micro/luci-interpreter/include/luci_interpreter/test_models/expand_dims/ExpandDimsKernel.h
  onert-micro/luci-interpreter/include/luci_interpreter/test_models/fully_connected/NegFullyConnectedKernel.h
  onert-micro/luci-interpreter/include/luci_interpreter/test_models/fully_connected/S32FullyConnectedKernel.h
  onert-micro/luci-interpreter/include/luci_interpreter/test_models/gather/NegGatherKernel.h
  onert-micro/luci-interpreter/include/luci_interpreter/test_models/gather/S16GatherKernel.h
  onert-micro/luci-interpreter/include/luci_interpreter/test_models/less/NegTestDataLessKernel.h
  onert-micro/luci-interpreter/include/luci_interpreter/test_models/logistic/NegLogisticKernel.h
  onert-micro/luci-interpreter/include/luci_interpreter/test_models/logistic/S32LogisticKernel.h
  onert-micro/luci-interpreter/include/luci_interpreter/test_models/maxpool2d/NegMaxPool2DKernel.h
  onert-micro/luci-interpreter/include/luci_interpreter/test_models/mul/NegMulKernel.h
  onert-micro/luci-interpreter/src/kernels/Add.test.cpp
  onert-micro/luci-interpreter/src/kernels/Concatenation.test.cpp
  onert-micro/luci-interpreter/src/kernels/Conv2D.test.cpp
  onert-micro/luci-interpreter/src/kernels/ExpandDims.test.cpp
  onert-micro/luci-interpreter/src/kernels/FullyConnected.test.cpp
  onert-micro/luci-interpreter/src/kernels/Gather.test.cpp
  onert-micro/luci-interpreter/src/kernels/Less.test.cpp
  onert-micro/luci-interpreter/src/kernels/Logistic.test.cpp
  onert-micro/luci-interpreter/src/kernels/MaxPool2D.test.cpp
  onert-micro/luci-interpreter/src/kernels/Mul.test.cpp
Labels: approval: 1
