Repository Samsung/ONE, pull requests merged in 2023-06, with the labels that each got.

#10843 tca config.yaml for onert-micro
  .ahub/tcchecker-tca/config.yaml
Labels: approval: 1

#10854 [infra] Use one-version
  infra/scripts/docker_build_nncc.sh
Labels: PR/ready for review

#10857 [one-cmds] Fix minor bug in test
  compiler/one-cmds/tests/onecc_046.test
Labels: PR/ready for review

#10858 [one-cmds] Profile multiple backends with a single cfg file
  compiler/one-cmds/dummy-driver/CMakeLists.txt
  compiler/one-cmds/dummy-driver/src/dummyV2-profile.cpp
  compiler/one-cmds/one-profile
  compiler/one-cmds/onecc
  compiler/one-cmds/onelib/CfgRunner.py
  compiler/one-cmds/tests/onecc_049.cfg
  compiler/one-cmds/tests/onecc_049.test
  compiler/one-cmds/tests/onecc_050.cfg
  compiler/one-cmds/tests/onecc_050.test
  compiler/one-cmds/tests/onecc_051.cfg
  compiler/one-cmds/tests/onecc_051.test
  compiler/one-cmds/tests/onecc_052.cfg
  compiler/one-cmds/tests/onecc_052.test
  compiler/one-cmds/tests/onecc_053.cfg
  compiler/one-cmds/tests/onecc_053.test
  compiler/one-cmds/tests/onecc_neg_032.cfg
  compiler/one-cmds/tests/onecc_neg_032.test
  compiler/one-cmds/tests/onecc_neg_033.cfg
  compiler/one-cmds/tests/onecc_neg_033.test
  compiler/one-cmds/tests/onecc_neg_034.cfg
  compiler/one-cmds/tests/onecc_neg_034.test
  compiler/one-cmds/tests/onecc_neg_035.cfg
  compiler/one-cmds/tests/onecc_neg_035.test
  compiler/one-cmds/tests/onecc_neg_036.test
  compiler/one-cmds/tests/onecc_neg_036.workflow.json
Labels: PR/ready for review

#10863 Add version file for onert-micro
  onert-micro/luci-interpreter/include/luci_interpreter/onert-micro-version.h
Labels: approval: 1

#10861 [onert] Introduce ITrainableOperation
  runtime/onert/core/include/ir/Operation.h
  runtime/onert/core/include/ir/train/ITrainableOperation.h
  runtime/onert/core/include/ir/train/TrainableOperations.h
Labels: PR/ready for review, area/onert

#10865 [onert] Introduce TrainingInfo
  runtime/onert/core/include/compiler/train/TrainingInfo.h
Labels: PR/ready for review, area/onert

#10866 [onert] Introduce TrainableOperationVisitor
  runtime/onert/core/include/ir/train/TrainableOperationVisitor.h
Labels: PR/ready for review, area/onert

#10872 [luci] Propagate QParam backward across more Ops
  compiler/luci/pass/src/PropagateQParamBackwardPass.cpp
  compiler/luci/pass/src/PropagateQParamBackwardPass.test.cpp
Labels: area/quant

#10874 [onert] Revise ITrainableOperation
  runtime/onert/core/include/ir/train/ITrainableOperation.h
Labels: PR/ready for review

#10876 [onert] Introduce TrainingCompiler
  runtime/onert/core/src/compiler/train/TrainingCompiler.cc
  runtime/onert/core/src/compiler/train/TrainingCompiler.h
Labels: PR/ready for review, area/onert

#10880 [onert] Introduce ITrainableBackend
  runtime/onert/core/include/backend/train/ITrainableBackend.h
Labels: PR/ready for review

#10883 [onert] Introduce IGraph
  runtime/onert/core/include/ir/Graph.h
  runtime/onert/core/include/ir/IGraph.h
  runtime/onert/core/src/ir/Graph.cc
Labels: PR/ready for review

#10888 [onert] Separate IOperation from the Operation header
  runtime/onert/core/include/backend/IConfig.h
  runtime/onert/core/include/backend/basic/DynamicTensorManager.h
  runtime/onert/core/include/compiler/CodeMap.h
  runtime/onert/core/include/ir/IOperation.h
  runtime/onert/core/include/ir/Operation.h
  runtime/onert/core/include/ir/Operations.h
  runtime/onert/core/include/ir/train/ITrainableOperation.h
  runtime/onert/core/src/backend/BackendContext.cc
  runtime/onert/core/src/compiler/pass/OperationPass.cc
  runtime/onert/core/src/dumper/dot/OperationNode.h
  runtime/onert/core/src/exec/ExecutionObservers.h
  runtime/onert/core/src/exec/FunctionSequence.cc
Labels: PR/ready for review

#10893 [onert] Encapsulate NNPkg
  runtime/onert/api/src/nnfw_api_internal.cc
  runtime/onert/core/include/ir/NNPkg.h
Labels: PR/ready for review

#10864 [onert] Introduce TrainableGraph
  runtime/onert/core/include/ir/Graph.h
  runtime/onert/core/include/ir/OperandIndexSequence.h
  runtime/onert/core/include/ir/train/TrainableGraph.h
  runtime/onert/core/src/ir/Graph.cc
  runtime/onert/core/src/ir/OperandIndexSequence.cc
  runtime/onert/core/src/ir/train/TrainableGraph.cc
Labels: PR/ready for review, area/onert

#10891 [onert] Introduce Pass for training
  runtime/onert/core/src/compiler/train/pass/Pass.h
Labels: PR/ready for review

#10892 [onert] Introduce ExecutorFactoryArgs
  runtime/onert/core/src/compiler/Compiler.cc
  runtime/onert/core/src/compiler/ExecutorFactory.cc
  runtime/onert/core/src/compiler/ExecutorFactory.h
  runtime/onert/core/src/compiler/MultiModelCompiler.cc
Labels: PR/ready for review

#10881 [onert] Introduce TrainableFnSequence
  runtime/onert/core/include/exec/train/TrainableFnSequence.h
Labels: PR/ready for review

#10896 [onert] Move custom kernel builders into Model
  runtime/onert/api/src/nnfw_api_internal.cc
  runtime/onert/core/include/ir/Graph.h
  runtime/onert/core/include/ir/Model.h
  runtime/onert/core/src/compiler/Compiler.cc
  runtime/onert/core/src/compiler/ExecutorFactory.cc
  runtime/onert/core/src/compiler/ExecutorFactory.h
  runtime/onert/core/src/compiler/MultiModelCompiler.cc
Labels: PR/ready for review

#10898 [onert] Introduce TrainableBackendContext
  runtime/onert/core/include/backend/train/TrainableBackendContext.h
Labels: PR/ready for review

#10902 [onert] Remove TrainableOperations
  runtime/onert/core/include/ir/train/TrainableOperations.h
Labels: PR/ready for review

#10868 [onert] Introduce experimental training APIs
  runtime/onert/api/include/nnfw_experimental.h
  runtime/onert/api/src/nnfw_api.cc
  runtime/onert/api/src/nnfw_api_internal.cc
  runtime/onert/api/src/nnfw_api_internal.h
Labels: PR/ready for review

#10904 [onert] Introduce LossInsertionPass
  runtime/onert/core/src/compiler/train/pass/LossInsertionPass.cc
  runtime/onert/core/src/compiler/train/pass/LossInsertionPass.h
Labels: PR/ready for review

#10903 [onert] Introduce CodeMap for training
  runtime/onert/core/include/compiler/train/TrainableCodeMap.h
Labels: PR/ready for review

#10895 [onert] Apply IGraph to Model
  runtime/onert/api/src/nnfw_api_internal.cc
  runtime/onert/api/src/nnfw_api_internal.h
  runtime/onert/core/include/ir/Model.h
  runtime/onert/core/include/ir/NNPkg.h
  runtime/onert/core/src/compiler/Compiler.cc
  runtime/onert/core/src/compiler/MultiModelCompiler.cc
  runtime/onert/core/src/compiler/MultiModelCompiler.h
Labels: PR/ready for review

#10909 [onert] Introduce Permute operation for training
  runtime/onert/core/include/ir/train/Operations.Include.h
  runtime/onert/core/include/ir/train/Operations.lst
  runtime/onert/core/include/ir/train/operation/Permute.h
  runtime/onert/core/src/ir/train/operations/Permute.cc
Labels: PR/ready for review

#10907 [onert] Introduce `builtin` backend's KernelGenerator for training
  runtime/onert/core/include/backend/train/KernelGeneratorBase.h
  runtime/onert/core/src/backend/builtin/train/KernelGenerator.cc
  runtime/onert/core/src/backend/builtin/train/KernelGenerator.h
Labels: PR/ready for review

#10918 [onert] Add PermuteLayer for training
  runtime/onert/core/src/backend/builtin/train/KernelGenerator.cc
  runtime/onert/core/src/backend/builtin/train/KernelGenerator.h
  runtime/onert/core/src/backend/builtin/train/kernel/PermuteLayer.cc
  runtime/onert/core/src/backend/builtin/train/kernel/PermuteLayer.h
Labels: PR/ready for review

#10915 [onert] Fix directory typo
  runtime/onert/core/src/ir/train/operation/Permute.cc
Labels: PR/ready for review

#10910 [onert] Introduce UntrainableOperation
  runtime/onert/core/include/ir/train/operation/UntrainableOperation.h
Labels: PR/ready for review

#10899 [onert] Introduce LoweredTrainableGraph
  runtime/onert/core/include/compiler/train/LoweredTrainableGraph.h
  runtime/onert/core/src/compiler/train/LoweredTrainableGraph.cc
  runtime/onert/core/src/dumper/text/GraphDumper.cc
  runtime/onert/core/src/dumper/text/GraphDumper.h
Labels: PR/ready for review

#10914 [onert] Introduce ElementwiseActivation operation for training
  runtime/onert/core/include/ir/train/Operations.Include.h
  runtime/onert/core/include/ir/train/Operations.lst
  runtime/onert/core/include/ir/train/operation/ElementwiseActivation.h
  runtime/onert/core/src/ir/train/operation/ElementwiseActivation.cc
Labels: PR/ready for review

#10911 [onert] Introduce UntrainableOperationConverter
  runtime/onert/core/include/ir/operation/BinaryArithmetic.h
  runtime/onert/core/src/compiler/train/UntrainableOperationConverter.cc
  runtime/onert/core/src/compiler/train/UntrainableOperationConverter.h
Labels: PR/ready for review

#10917 [onert] Add helper functions for TrainableBackendContext
  runtime/onert/backend/train/BackendContext.cc
  runtime/onert/backend/train/BackendContext.h
  runtime/onert/core/include/backend/basic/BackendContextHelpers.h
  runtime/onert/core/include/backend/basic/train/TrainableBackendContextHelpers.h
Labels: PR/ready for review

#10927 [onert] Access gradient tensors in builtin KernelGenerator
  runtime/onert/core/src/backend/builtin/train/KernelGenerator.cc
  runtime/onert/core/src/backend/builtin/train/KernelGenerator.h
Labels: PR/ready for review

#10912 [onert] Introduce TrainableExecutor
  runtime/onert/core/src/exec/train/TrainableExecutor.cc
  runtime/onert/core/src/exec/train/TrainableExecutor.h
Labels: PR/ready for review

#10913 [onert] Introduce TrainableOperationConverter
  runtime/onert/core/src/compiler/train/TrainableOperationConverter.cc
  runtime/onert/core/src/compiler/train/TrainableOperationConverter.h
Labels: PR/ready for review

#10916 [onert] Introduce builtin backend's BackendContext for training
  runtime/onert/core/include/backend/basic/train/TrainableBackendContextHelpers.h
  runtime/onert/core/src/backend/builtin/train/BackendContext.cc
  runtime/onert/core/src/backend/builtin/train/BackendContext.h
Labels: PR/ready for review

#10928 [onert] Create TensorRegistries by using TrainableBackendContexts
  runtime/onert/core/src/compiler/TensorRegistries.h
Labels: PR/ready for review

#10919 [onert] Introduce TrainableExecutors
  runtime/onert/core/src/exec/train/TrainableExecutors.cc
  runtime/onert/core/src/exec/train/TrainableExecutors.h
Labels: PR/ready for review

#10939 [onert] Remove an unnecessary member from TrainingCompiler
  runtime/onert/core/src/compiler/train/TrainingCompiler.cc
  runtime/onert/core/src/compiler/train/TrainingCompiler.h
Labels: PR/ready for review

#10938 [onert] Support DotDumper for LoweredTrainableGraph
  runtime/onert/core/src/dumper/dot/DotDumper.cc
  runtime/onert/core/src/dumper/dot/DotDumper.h
Labels: PR/ready for review

#10943 [visq] Improve error message
  compiler/visq/visq
Labels: area/quant

#10951 [visq-unittest] Turn off for a while
  compiler/visq-unittest/CMakeLists.txt
Labels: area/quant

#10935 [onert] Introduce trainable kernel generator into train backend
  runtime/onert/backend/train/Backend.h
  runtime/onert/backend/train/BackendContext.h
  runtime/onert/backend/train/KernelGenerator.cc
  runtime/onert/backend/train/KernelGenerator.h
Labels: PR/ready for review

#10934 [onert] Introduce training feature flag
  infra/nnfw/cmake/CfgOptionFlags.cmake
  infra/nnfw/cmake/options/options_aarch64-tizen.cmake
  infra/nnfw/cmake/options/options_armv7hl-tizen.cmake
  infra/nnfw/cmake/options/options_armv7l-tizen.cmake
  infra/nnfw/cmake/options/options_i686-tizen.cmake
  infra/nnfw/cmake/options/options_x86_64-tizen.cmake
  runtime/onert/api/src/nnfw_api.cc
  runtime/onert/api/src/nnfw_api_internal.cc
  runtime/onert/api/src/nnfw_api_internal.h
  runtime/onert/backend/CMakeLists.txt
  runtime/onert/core/CMakeLists.txt
  runtime/onert/core/src/compiler/CompilerFactory.cc
  runtime/onert/core/src/compiler/TensorRegistries.h
  runtime/onert/core/src/dumper/text/GraphDumper.cc
  runtime/onert/core/src/dumper/text/GraphDumper.h
Labels: PR/ready for review

#10936 [onert] Fix missing override methods in TrainableGraph
  runtime/onert/core/include/ir/train/TrainableGraph.h
  runtime/onert/core/src/ir/train/TrainableGraph.cc
Labels: PR/ready for review

#10955 [visq] Support multi-out nodes
  compiler/visq/visqlib/DumpFP32FM.py
  compiler/visq/visqlib/DumpFakeQuantFM.py
Labels: area/quant

#10956 [visq-unittest] Enable tests
  compiler/visq-unittest/CMakeLists.txt
Labels: area/quant, approval: 1

#10959 [onert] Fix gbs build error
  runtime/onert/core/src/backend/builtin/Backend.h
Labels: PR/ready for review, Urgent
