Repository Samsung/ONE, pull requests merged in 2023-03, with the labels that each got.

#10483 [infra] Update binary gitattributes
  .gitattributes
Labels: PR/ready for review

#10486 [gbs] Disable armcl backend on tizen
  infra/nnfw/cmake/options/options_aarch64-tizen.cmake
  infra/nnfw/cmake/options/options_armv7hl-tizen.cmake
  infra/nnfw/cmake/options/options_armv7l-tizen.cmake
  packaging/nnfw.spec
Labels: PR/ready for review

#10494 [luci] Support more Ops for fake quantization
  compiler/luci/pass/src/ConvertToFakeQuantizedModelPass.cpp
Labels: area/quant

#10499 [onert/test] Update profiling mode test script
  tests/scripts/common.sh
  tests/scripts/test_scheduler_with_profiling.sh
Labels: PR/ready for review

#10498 [onert/test] Set test command common variables
  tests/scripts/command/prepare-model
  tests/scripts/command/unittest
  tests/scripts/command/verify-tflite
  tests/scripts/onert-test
Labels: PR/ready for review

#10508 [luci] Revisit QuantizeWithMinMaxPass
  compiler/luci/pass/include/luci/Pass/QuantizeWithMinMaxPass.h
  compiler/luci/pass/src/QuantizeWithMinMaxPass.test.cpp
  compiler/luci/pass/src/QuantizedModelVerifier.test.cpp
Labels: area/quant

#10505 [infra/onert] Introduce model download dev command
  infra/nnfw/command/prepare-model
  infra/scripts/tizen_xu4_test.sh
Labels: PR/ready for review

#10514 [luci] Revisit QuantizedModelVerifier
  compiler/luci/pass/src/QuantizedModelVerifier.h
  compiler/luci/pass/src/QuantizedModelVerifier.test.cpp
Labels: area/quant

#10515 [gbs] Update gbs.conf
  infra/nnfw/config/gbs.conf
Labels: PR/ready for review

#10507 [onert/test] Update nnpackage test script
  tests/scripts/benchmark_nnpkg.sh
  tests/scripts/merge_result_of_benchmark_nnpkg.py
Labels: PR/ready for review

#10521 [luci] Canonicalize user-given input/output_type
  compiler/luci/pass/src/CircleQuantizer.cpp
  compiler/luci/pass/src/helpers/Strings.cpp
  compiler/luci/pass/src/helpers/Strings.h
  compiler/luci/pass/src/helpers/Strings.test.cpp
Labels: area/quant

#10516 [one-cmds] Introduce export_constant.py
  compiler/one-cmds/onelib/export_constant.py
Labels: PR/ready for review

#10506 [onert/test] Revive operator kernel test script
  tests/scripts/benchmark_nnapi.sh
  tests/scripts/common.sh
Labels: PR/ready for review

#10517 [debian] Install export_constant.py
  infra/debian/compiler/one-compiler.install
Labels: PR/ready for review

#10520 [one-cmds] Remove unnecessary O1 logic
  compiler/one-cmds/one-optimize
  compiler/one-cmds/onelib/constant.py
  compiler/one-cmds/onelib/utils.py
Labels: PR/ready for review

#10527 [onert/test] Revise benchmark scripts
  tests/scripts/benchmark_ops.sh
  tests/scripts/common.sh
  tests/scripts/test-driver.sh
  tests/scripts/test_scheduler_with_profiling.sh
Labels: PR/ready for review

#10528 [onert/test] Use common variable DRIVER_PATH on command
  tests/scripts/command/prepare-model
  tests/scripts/onert-test
Labels: PR/ready for review

#10529 [onert/test] Revise run_test.sh
  tests/scripts/models/run_test.sh
Labels: PR/ready for review

#10526 [luci] Use vector type input/output_type in QuantizeWithMinMaxPass
  compiler/luci/pass/include/luci/Pass/QuantizeWithMinMaxPass.h
  compiler/luci/pass/src/CircleQuantizer.cpp
  compiler/luci/pass/src/QuantizeWithMinMaxPass.cpp
  compiler/luci/pass/src/QuantizedModelVerifier.test.cpp
Labels: area/quant

#10522 [onert-micro] Refactor UnidirectionalSequenceLSTM kernel
  onert-micro/CMakeLists.txt
  onert-micro/luci-interpreter/CMakeLists.txt
  onert-micro/luci-interpreter/pal/mcu/KernelsToBuild.lst
  onert-micro/luci-interpreter/pal/mcu/PALUnidirectionalSequenceLSTM.h
  onert-micro/luci-interpreter/src/core/RuntimeGraph.cpp
  onert-micro/luci-interpreter/src/kernels/UnidirectionalSequenceLSTM.cpp
  onert-micro/luci-interpreter/src/kernels/UnidirectionalSequenceLSTM.h
  onert-micro/luci-interpreter/src/kernels/Utils.cpp
  onert-micro/luci-interpreter/src/kernels/Utils.h
Labels: approval: 1

#10532 [luci] Use vector type input/output_type in QuantizedModelVerifier
  compiler/luci/pass/src/CircleQuantizer.cpp
  compiler/luci/pass/src/QuantizedModelVerifier.h
  compiler/luci/pass/src/QuantizedModelVerifier.test.cpp
Labels: area/quant

#10533 [circle-quantizer] Revise help message
  compiler/circle-quantizer/src/CircleQuantizer.cpp
Labels: area/quant

#10535 [luci] Support quantization of MUL with indices
  compiler/luci/pass/src/QuantizedModelVerifier.test.cpp
  compiler/luci/pass/src/VerifyQuantizedNodeGranularity.h
  compiler/luci/pass/src/VerifyQuantizedNodeType.cpp
Labels: area/quant

#10541 [preset] Add circle-opselector to preset 20221125
  infra/packaging/preset/20221125
Labels: PR/ready for review

#10542 [debian] Install circle-opselector
  infra/debian/compiler/one-compiler-dev.install
Labels: PR/ready for review

#10538 [one-cmds] Add quantiation tests for input/output_type
  compiler/one-cmds/tests/one-quantize_016.test
  compiler/one-cmds/tests/one-quantize_neg_021.test
  compiler/one-cmds/tests/onecc_045.cfg
  compiler/one-cmds/tests/onecc_045.test
  compiler/one-cmds/tests/onecc_neg_026.cfg
  compiler/one-cmds/tests/onecc_neg_026.test
Labels: area/quant

#10543 [infra] Add circle-opselector to compiler_modules script
  infra/scripts/compiler_modules.sh
Labels: PR/ready for review

#10546 [circle-opselector] Fix static analysis warning
  compiler/circle-opselector/src/OpSelector.cpp
Labels: PR/ready for review

#10544 [debian] Update changelog
  infra/debian/compiler/changelog
Labels: PR/ready for review, type/release

#10551 [one-cmds] Skip some tests for a while
  compiler/one-cmds/tests/one-quantize_016.test
  compiler/one-cmds/tests/onecc_045.test
Labels: PR/ready for review

#10559 [debian] Install optimization folder
  infra/debian/compiler/one-compiler.install
Labels: PR/ready for review

#10545 Release note 1.22.0
  docs/release/1.22/index.rst
  docs/release/1.22/release-note-1.22.0.md
Labels: PR/ready for review, type/release

#10557 Remove bad escape
  compiler/nnc/backends/soft_backend/code_snippets/eigen.def
Labels: PR/ready for review

#10561 [vconone] Bump up to 1.23.0
  compiler/vconone/CMakeLists.txt
Labels: PR/ready for review

#10562 Update runtime version to 1.23.0
  docs/conf.py
  packaging/nnfw.spec
  runtime/contrib/android/api/build.gradle
  runtime/onert/api/include/nnfw_version.h
Labels: PR/ready for review

#10578 [one-cmds] Fix error message
  compiler/one-cmds/tests/one-quantize_neg_003.test
Labels: area/quant

#10575 [visq] Introduce SRMSE metric
  compiler/visq/visq
  compiler/visq/visqlib/DumpFakeQuantFM.py
  compiler/visq/visqlib/QErrorComputer.py
Labels: area/quant

#10583 [visq] Use defaultdict
  compiler/visq/visqlib/QErrorComputer.py
Labels: area/quant

#10582 [visq-unittest] Add test for SRMSE
  compiler/visq-unittest/test/testQErrorComputer.py
Labels: area/quant

#10565 [onert-micro] Add kernels for GRU models
  onert-micro/CMakeLists.txt
  onert-micro/eval-driver/Driver.cpp
  onert-micro/luci-interpreter/include/luci_interpreter/Interpreter.h
  onert-micro/luci-interpreter/include/luci_interpreter/core/Tensor.h
  onert-micro/luci-interpreter/include/luci_interpreter/core/reader/CircleMicroReader.h
  onert-micro/luci-interpreter/pal/mcu/KernelsToBuild.lst
  onert-micro/luci-interpreter/pal/mcu/PALMul.h
  onert-micro/luci-interpreter/pal/mcu/pal.cmake
  onert-micro/luci-interpreter/src/Interpreter.cpp
  onert-micro/luci-interpreter/src/core/RuntimeGraph.cpp
  onert-micro/luci-interpreter/src/core/RuntimeGraph.h
  onert-micro/luci-interpreter/src/core/RuntimeModule.h
  onert-micro/luci-interpreter/src/core/reader/CircleMicroReader.cpp
  onert-micro/luci-interpreter/src/kernels/Add.cpp
  onert-micro/luci-interpreter/src/kernels/Add.test.cpp
  onert-micro/luci-interpreter/src/kernels/BinaryOpCommon.h
  onert-micro/luci-interpreter/src/kernels/CMakeLists.txt
  onert-micro/luci-interpreter/src/kernels/Concatenation.cpp
  onert-micro/luci-interpreter/src/kernels/Gather.cpp
  onert-micro/luci-interpreter/src/kernels/KernelBuilder.h
  onert-micro/luci-interpreter/src/kernels/Less.cpp
  onert-micro/luci-interpreter/src/kernels/Less.h
  onert-micro/luci-interpreter/src/kernels/Less.test.cpp
  onert-micro/luci-interpreter/src/kernels/MISOKernel.h
  onert-micro/luci-interpreter/src/kernels/Mul.cpp
  onert-micro/luci-interpreter/src/kernels/Reshape.cpp
  onert-micro/luci-interpreter/src/kernels/SISOKernel.h
  onert-micro/luci-interpreter/src/kernels/Slice.cpp
  onert-micro/luci-interpreter/src/kernels/Softmax.cpp
  onert-micro/luci-interpreter/src/kernels/Split.cpp
  onert-micro/luci-interpreter/src/kernels/Sub.cpp
  onert-micro/luci-interpreter/src/kernels/Sub.test.cpp
  onert-micro/luci-interpreter/src/kernels/TISOKernel.h
  onert-micro/luci-interpreter/src/kernels/Tanh.cpp
  onert-micro/luci-interpreter/src/kernels/Utils.cpp
  onert-micro/luci-interpreter/src/kernels/Utils.h
  onert-micro/luci-interpreter/src/kernels/While.cpp
  onert-micro/luci-interpreter/src/loader/GraphLoader.cpp
  onert-micro/luci-interpreter/src/loader/ModuleLoader.cpp
  onert-micro/luci-interpreter/src/loader/ModuleLoader.h
Labels: approval: 1
