Repository Samsung/ONE, pull requests merged in 2023-08, with the labels that each got.

#11194 [luci/import] Clean up some comments
  compiler/luci/import/src/GraphBuilderRegistry.cpp
Labels: PR/ready for review

#11193 [luci/partition] Support HardSwish operation
  compiler/luci/partition/include/luci/ConnectNode.h
  compiler/luci/partition/src/Nodes/CircleHardSwish.cpp
  compiler/luci/partition/src/Nodes/CircleHardSwish.test.cpp
Labels: PR/ready for review

#11187 [infra/docker] Install android sdk
  infra/docker/focal/Dockerfile
Labels: PR/ready for review

#11195 [luci-interpreter] Support HardSwish operation
  compiler/luci-interpreter/pal/linux/KernelsToBuild.lst
  compiler/luci-interpreter/pal/linux/PALHardSwish.h
  compiler/luci-interpreter/src/kernels/HardSwish.cpp
  compiler/luci-interpreter/src/kernels/HardSwish.h
  compiler/luci-interpreter/src/kernels/HardSwish.test.cpp
  compiler/luci-interpreter/src/loader/nodes/HardSwish.cpp
Labels: PR/ready for review

#11191 [onert] Restore IOTensors for outputs of graph
  runtime/onert/core/src/compiler/ExecutorFactory.cc
  runtime/onert/core/src/exec/train/TrainableExecutor.cc
Labels: PR/ready for review

#11196 [res] Support HardSwish operation
  res/TensorFlowLiteRecipes/HardSwish_000/test.recipe
  res/TensorFlowLiteRecipes/HardSwish_000/test.reverse
Labels: PR/ready for review

#10998 [onert-micro] Support LogicalAnd, LogicalOr kernels
  onert-micro/luci-interpreter/include/luci_interpreter/test_models/logical_and/BoolLogicalAndKernel.h
  onert-micro/luci-interpreter/include/luci_interpreter/test_models/logical_and/NegLogicalAndKernel.h
  onert-micro/luci-interpreter/include/luci_interpreter/test_models/logical_and/TestDataLogicalAndBase.h
  onert-micro/luci-interpreter/include/luci_interpreter/test_models/logical_or/BoolLogicalOrKernel.h
  onert-micro/luci-interpreter/include/luci_interpreter/test_models/logical_or/NegLogicalOrKernel.h
  onert-micro/luci-interpreter/include/luci_interpreter/test_models/logical_or/TestDataLogicalOrBase.h
  onert-micro/luci-interpreter/pal/common/PALLogicalCommon.h
  onert-micro/luci-interpreter/pal/mcu/KernelsToBuild.lst
  onert-micro/luci-interpreter/src/kernels/LogicalAnd.cpp
  onert-micro/luci-interpreter/src/kernels/LogicalAnd.h
  onert-micro/luci-interpreter/src/kernels/LogicalAnd.test.cpp
  onert-micro/luci-interpreter/src/kernels/LogicalNot.h
  onert-micro/luci-interpreter/src/kernels/LogicalOr.cpp
  onert-micro/luci-interpreter/src/kernels/LogicalOr.h
  onert-micro/luci-interpreter/src/kernels/LogicalOr.test.cpp
Labels: approval: 1

#11192 [onert] Ignore permutation for IOTensors for outputs
  runtime/onert/core/src/backend/builtin/train/KernelGenerator.cc
  runtime/onert/core/src/backend/builtin/train/kernel/PermuteLayer.cc
  runtime/onert/core/src/backend/builtin/train/kernel/PermuteLayer.h
  runtime/onert/core/src/compiler/train/LoweredTrainableGraph.cc
  runtime/onert/core/src/compiler/train/pass/PermutationInsertionPass.cc
  runtime/onert/core/src/compiler/train/pass/PermutationInsertionPass.h
Labels: PR/ready for review

#11197 [luci/test] Support HardSwish operation
  compiler/luci/tests/test.lst
Labels: PR/ready for review

#11203 [luci-value-test] Support HardSwish operation
  compiler/luci-value-test/test.lst
Labels: PR/ready for review

#11198 [onert] Change train_get_loss function signature
  runtime/onert/api/src/nnfw_api.cc
  runtime/onert/api/src/nnfw_api_internal.cc
  runtime/onert/api/src/nnfw_api_internal.h
Labels: PR/ready for review

#11208 [onert] Allow to use multiple GradientAppliers
  runtime/onert/backend/train/KernelGenerator.cc
  runtime/onert/backend/train/KernelGenerator.h
Labels: PR/ready for review

#11207 [cker] Introduce a kernel that computes gradient of relu
  compute/cker/include/cker/operation/ReLU.h
  compute/cker/src/Relu.test.cc
Labels: PR/ready for review

#11218 [onert] Fix shallow copy of TrainableGraph
  runtime/onert/core/src/ir/train/TrainableGraph.cc
Labels: PR/ready for review

#11219 [onert] Use trainable graph as a class member variable in lowered trainable graph
  runtime/onert/core/include/compiler/train/LoweredTrainableGraph.h
Labels: PR/ready for review

#11212 [infra] Add CMSIS-NN-4.1.0
  infra/cmake/packages/CMSIS-NN-4.1.0/CMSIS-NNConfig.cmake
  infra/cmake/packages/CMSIS-NN-4.1.0/CMSIS-NNConfigVersion.cmake
Labels: approval: 1

#11213 [onert-micro] Clean pal/cmsisnn dir
  onert-micro/luci-interpreter/pal/cmsisnn/PALArgMax.h
  onert-micro/luci-interpreter/pal/cmsisnn/PALAveragePool2d.h
  onert-micro/luci-interpreter/pal/cmsisnn/PALBatchToSpaceND.h
  onert-micro/luci-interpreter/pal/cmsisnn/PALDepthToSpace.h
  onert-micro/luci-interpreter/pal/cmsisnn/PALDepthwiseConv2d.h
  onert-micro/luci-interpreter/pal/cmsisnn/PALDequantize.h
  onert-micro/luci-interpreter/pal/cmsisnn/PALElu.h
  onert-micro/luci-interpreter/pal/cmsisnn/PALFill.h
  onert-micro/luci-interpreter/pal/cmsisnn/PALL2Normalize.h
  onert-micro/luci-interpreter/pal/cmsisnn/PALLeakyRelu.h
  onert-micro/luci-interpreter/pal/cmsisnn/PALNeg.h
  onert-micro/luci-interpreter/pal/cmsisnn/PALQuantize.h
  onert-micro/luci-interpreter/pal/cmsisnn/PALResizeBilinear.h
  onert-micro/luci-interpreter/pal/cmsisnn/PALResizeNearestNeighbor.h
  onert-micro/luci-interpreter/pal/cmsisnn/PALSVDF.h
  onert-micro/luci-interpreter/pal/cmsisnn/PALSoftmax.h
  onert-micro/luci-interpreter/pal/cmsisnn/PALSpaceToBatchND.h
  onert-micro/luci-interpreter/pal/cmsisnn/PALSpaceToDepth.h
  onert-micro/luci-interpreter/pal/cmsisnn/PALreference_ops.h
Labels: approval: 1

#11214 [onert-micro] Clean pal/mcu dir
  onert-micro/luci-interpreter/pal/mcu/PALBatchToSpaceND.h
  onert-micro/luci-interpreter/pal/mcu/PALDepthToSpace.h
  onert-micro/luci-interpreter/pal/mcu/PALDepthwiseConv2d.h
  onert-micro/luci-interpreter/pal/mcu/PALDequantize.h
  onert-micro/luci-interpreter/pal/mcu/PALFill.h
  onert-micro/luci-interpreter/pal/mcu/PALL2Normalize.h
  onert-micro/luci-interpreter/pal/mcu/PALNeg.h
  onert-micro/luci-interpreter/pal/mcu/PALQuantize.h
  onert-micro/luci-interpreter/pal/mcu/PALResizeNearestNeighbor.h
  onert-micro/luci-interpreter/pal/mcu/PALSVDF.h
  onert-micro/luci-interpreter/pal/mcu/PALSpaceToBatchND.h
  onert-micro/luci-interpreter/pal/mcu/PALSpaceToDepth.h
  onert-micro/luci-interpreter/pal/mcu/PALreference_ops.h
Labels: approval: 1

#11221 [onert] Introduce OperationUtils for train kernal
  runtime/onert/backend/train/ops/OperationUtils.h
Labels: PR/ready for review

#11225 [visq-unittest] Remove unused module
  compiler/visq-unittest/test/testDotBuilder.py
Labels: area/quant

#11224 [onert] Implement train_set_expected in nnfw api
  runtime/onert/api/src/nnfw_api_internal.cc
  runtime/onert/core/include/exec/Execution.h
  runtime/onert/core/src/exec/Execution.cc
Labels: PR/ready for review

#11215 [onert-micro] Move common kernels to pal/common
  onert-micro/luci-interpreter/pal/common/PALAddCommon.h
  onert-micro/luci-interpreter/pal/common/PALAveragePool2DCommon.h
  onert-micro/luci-interpreter/pal/common/PALConv2DCommon.h
  onert-micro/luci-interpreter/pal/common/PALDiv.h
  onert-micro/luci-interpreter/pal/common/PALFullyConnectedCommon.h
  onert-micro/luci-interpreter/pal/common/PALMaxPool2DCommon.h
  onert-micro/luci-interpreter/pal/common/PALMulCommon.h
  onert-micro/luci-interpreter/pal/common/PALResizeBilinear.h
  onert-micro/luci-interpreter/pal/common/PALSoftmax.h
  onert-micro/luci-interpreter/pal/common/PALSub.h
  onert-micro/luci-interpreter/pal/common/PALUnidirectionalSequenceLSTMCommon.h
  onert-micro/luci-interpreter/pal/mcu/PALAdd.h
  onert-micro/luci-interpreter/pal/mcu/PALAveragePool2D.h
  onert-micro/luci-interpreter/pal/mcu/PALConv2d.h
  onert-micro/luci-interpreter/pal/mcu/PALFullyConnected.h
  onert-micro/luci-interpreter/pal/mcu/PALMaxPool2D.h
  onert-micro/luci-interpreter/pal/mcu/PALMul.h
  onert-micro/luci-interpreter/pal/mcu/PALUnidirectionalSequenceLSTM.h
Labels: approval: 1

#11226 [onert] Add derivatives into partial graphs for each backend
  runtime/onert/core/src/compiler/ExecutorFactory.cc
Labels: PR/ready for review

#11231 [infra/nnfw] Remove tizen cross build infra
  infra/nnfw/cmake/buildtool/cross/toolchain_armv7l-tizen.cmake
  tools/cross/armel/tizen-build-rootfs.sh
  tools/cross/armel/tizen-fetch.sh
  tools/cross/armel/tizen.patch
Labels: PR/ready for review

#11233 [onert] Apply FullyconnectedLayer for training
  runtime/onert/backend/train/KernelGenerator.cc
  runtime/onert/backend/train/KernelGenerator.h
Labels: PR/ready for review

#11222 [onert] Introduce loss map for training
  runtime/onert/core/include/ir/train/TrainableGraph.h
  runtime/onert/core/src/ir/train/TrainableGraph.cc
Labels: PR/ready for review

#11235 [luci] Add check before QuantizeSpecialActivation
  compiler/luci/pass/src/QuantizeWithMinMaxPass.cpp
Labels: area/quant

#11234 [res] Support HardSwish decomposing pass
  res/TensorFlowLiteRecipes/HardSwish_001/test.recipe
  res/TensorFlowLiteRecipes/HardSwish_001/test.rule
Labels: PR/ready for review

#11228 [onert] Fix use of partial graph's outputs
  runtime/onert/core/src/backend/builtin/train/KernelGenerator.cc
  runtime/onert/core/src/backend/builtin/train/KernelGenerator.h
  runtime/onert/core/src/compiler/ExecutorFactory.cc
Labels: PR/ready for review

#11237 [onert] Fix optimizer being nullptr
  runtime/onert/backend/train/Backend.h
Labels: PR/ready for review

#11241 [tools/rootfs] Update rootfs install script
  tools/cross/install_rootfs.sh
Labels: PR/ready for review

#11230 [luci/pass] Support HardSwish decomposing pass
  compiler/luci/pass/include/luci/CircleOptimizer.h
  compiler/luci/pass/include/luci/Pass/DecomposeHardSwishPass.h
  compiler/luci/pass/src/CircleOptimizer.cpp
  compiler/luci/pass/src/DecomposeHardSwishPass.cpp
  compiler/luci/pass/src/DecomposeHardSwishPass.test.cpp
Labels: PR/ready for review

#11242 [doc] Update runtime build document
  docs/howto/how-to-build-runtime.md
Labels: PR/ready for review

#11246 [luci-pass-value-test] Support HardSwish decomposing pass
  compiler/luci-pass-value-test/test.lst
Labels: PR/ready for review

#11247 [circle2circle-dredd-recipe-test] Support HardSwish decomposing pass
  compiler/circle2circle-dredd-recipe-test/test.lst
Labels: PR/ready for review

#11252 [onert] Implement getLoss function in Execution
  runtime/onert/core/include/exec/Execution.h
  runtime/onert/core/src/exec/Execution.cc
Labels: PR/ready for review

#11253 [onert] Add y_pred and loss pairs to trainable graph loss map
  runtime/onert/core/src/compiler/train/pass/LossInsertionPass.cc
Labels: PR/ready for review

#11249 [onert] Introduce LossMSEGrad function in train backend
  compute/cker/include/cker/train/operation/Loss.h
  compute/cker/src/train/Loss.test.cc
  runtime/onert/backend/train/KernelGenerator.cc
  runtime/onert/backend/train/ops/LossLayer.cc
  runtime/onert/backend/train/ops/LossLayer.h
Labels: PR/ready for review

#11258 [one-cmds] Support HardSwish decomposing option
  compiler/one-cmds/onelib/constant.py
Labels: PR/ready for review

#11267 [luci/pass] Missing to add origin
  compiler/luci/pass/src/ReplaceSubWithAddPass.cpp
Labels: PR/ready for review

#11261 [doc] Update onert cross build documentation
  docs/howto/how-to-cross-build-runtime-for-arm.md
Labels: PR/ready for review

#11259 [infra/runtime] Update cmake minimum requirement
  infra/nnfw/CMakeLists.txt
Labels: PR/ready for review, approval: 2

#11260 [tools/cross] Revise rootfs script
  tools/cross/aarch64/sources.list.jammy
  tools/cross/aarch64/sources.list.xenial
  tools/cross/install_rootfs.sh
Labels: PR/ready for review

#11262 [onert] Implement train_get_loss in nnfw api
  runtime/onert/api/src/nnfw_api_internal.cc
Labels: PR/ready for review

#11256 [luci] Remove zeropoint from symmetric quantization
  compiler/luci/pass/src/QuantizationUtils.cpp
  compiler/luci/pass/src/QuantizationUtils.h
  compiler/luci/pass/src/QuantizeActivation.cpp
  compiler/luci/pass/src/QuantizeDequantizeWeightsPass.cpp
  compiler/luci/pass/src/QuantizeWeights.cpp
  compiler/luci/pass/src/QuantizeWithMinMaxPass.cpp
Labels: area/quant

#11251 [onert] Apply ReLUGrad to ElementwiseActivationLayer
  runtime/onert/backend/cpu/ops/ElementwiseActivationLayer.h
  runtime/onert/backend/train/ops/ElementwiseActivationLayer.cc
  runtime/onert/backend/train/ops/ElementwiseActivationLayer.h
Labels: PR/ready for review

#11321 [onert] Use EXPECT gtest interface in cker Loss unittest
  compute/cker/src/train/Loss.test.cc
Labels: PR/ready for review

#11324 [tools/onert_train] Show average loss per epoch
  tests/tools/onert_train/src/onert_train.cc
Labels: PR/ready for review

#11353 [one-cmds] Revise `one-prepare-venv.aarch64` script to build and install missing package from source code.
  compiler/one-cmds/one-prepare-venv.aarch64
Labels: PR/ready for review

#11344 [onert] Do not use uninitialized variable in train ElementwiseActivat…
  runtime/onert/backend/train/ops/ElementwiseActivationLayer.cc
Labels: PR/ready for review

#11350 [infra/gbs] Fix test install path typo
  packaging/nnfw.spec
Labels: PR/ready for review

#11352 [onert] Fix wrong shapes in FullyConnectedLayer for training
  runtime/onert/backend/train/ops/FullyConnectedLayer.cc
Labels: PR/ready for review

#11349 [infra/onert] Build and install luci library
  Makefile.template
  packaging/FLATBUFFERS-2.0.tar.gz
  packaging/nnfw.spec
Labels: PR/ready for review

#11339 [onert] Bring FullyConnected kernel from tensorflow v2.12.1.
  compute/cker/CMakeLists.txt
  compute/cker/include/cker/Types.h
  compute/cker/include/cker/eigen/eigen_gemm_eigen.h
  compute/cker/include/cker/operation/FullyConnected.h
  compute/cker/include/cker/operation/optimized/Gemm.h
  runtime/onert/backend/cpu/ops/FullyConnectedLayer.cc
  runtime/onert/backend/train/ops/FullyConnectedLayer.cc
Labels: PR/ready for review

#11380 [infra/gbs] Use parallel build option
  packaging/nnfw.spec
Labels: PR/ready for review

#11373 [tools/onert_train] Measure training speed in one step
  tests/tools/onert_train/src/measure.h
  tests/tools/onert_train/src/onert_train.cc
Labels: PR/ready for review

#11393 [tools/onert_train] Change variable name
  tests/tools/onert_train/src/onert_train.cc
Labels: PR/ready for review

#11382 [nnpackage] Update circle schema to 0.6
  nnpackage/schema/circle_schema.fbs
Labels: PR/ready for review

#11399 [onert] Introduce IGradientApplier
  runtime/onert/core/include/exec/train/IGradientApplier.h
Labels: PR/ready for review

#11406 [onert] Don't show intended cp fail
  Makefile.template
Labels: PR/ready for review

#11383 [onert] Support circle schema v0.6
  runtime/onert/frontend/circle_schema/include/circle_schema_generated.h
Labels: PR/ready for review

#11402 [tools] Introduce tf dataset converter
  tools/generate_datafile/tf_dataset_converter/README.md
  tools/generate_datafile/tf_dataset_converter/argparser.py
  tools/generate_datafile/tf_dataset_converter/datasets.py
  tools/generate_datafile/tf_dataset_converter/main.py
  tools/generate_datafile/tf_dataset_converter/requirements.txt
Labels: PR/ready for review

#11410 [record-minmax] Revise record-minmax
  compiler/record-minmax/driver/Driver.cpp
  compiler/record-minmax/include/MinMaxComputer.h
  compiler/record-minmax/include/RecordMinMax.h
  compiler/record-minmax/src/MinMaxComputer.cpp
  compiler/record-minmax/src/RecordMinMax.cpp
Labels: area/quant

#11408 [tools/onert_train] Add mem_poll argument
  tests/tools/onert_train/src/args.cc
  tests/tools/onert_train/src/args.h
Labels: PR/ready for review

#11407 [onert] Introduce weight quantization API
  runtime/onert/api/include/nnfw_experimental.h
  runtime/onert/api/src/nnfw_api.cc
  runtime/onert/api/src/nnfw_api_internal.cc
  runtime/onert/api/src/nnfw_api_internal.h
Labels: PR/ready for review
