Repository Samsung/ONE, pull requests merged in 2023-12, with the labels that each got.

#12169 [common-artifacts] Install pytest
  compiler/common-artifacts/CMakeLists.txt
Labels: PR/ready for review

#12172 [onert] Update circle loader for schema v0.7
  runtime/onert/frontend/circle/src/circle_loader.cc
  runtime/onert/frontend/circle_schema/include/circle_schema_generated.h
Labels: PR/ready for review

#12146 [onert] Support FloorMod
  compute/cker/include/cker/operation/FloorMod.h
  runtime/onert/backend/cpu/KernelGenerator.cc
  runtime/onert/backend/cpu/ops/ElementwiseBinaryLayer.cc
  runtime/onert/backend/cpu/ops/ElementwiseBinaryLayer.h
  tests/nnfw_api/src/CircleGen.cc
  tests/nnfw_api/src/CircleGen.h
  tests/nnfw_api/src/one_op_tests/FloorMod.test.cc
Labels: PR/ready for review

#12193 [luci-value-py-test] Add README.md
  compiler/luci-value-py-test/README.md
Labels: PR/ready for review

#12192 [tools/tf_dataset_converter] Support imagenet dataset
  tools/generate_datafile/tf_dataset_converter/README.md
  tools/generate_datafile/tf_dataset_converter/argparser.py
  tools/generate_datafile/tf_dataset_converter/datasets.py
  tools/generate_datafile/tf_dataset_converter/main.py
Labels: PR/ready for review

#12194 [luci-value-py-test] Update test list
  compiler/luci-value-py-test/test.lst
Labels: PR/ready for review

#12200 [luci-value-py-test] Resolve warning
  compiler/luci-value-py-test/conftest.py
Labels: PR/ready for review

#12201 [luci-value-test] Turn off the test
  compiler/luci-value-test/exclude.me
Labels: PR/ready for review

#12199 [luci-pass-value-py-test] Introduce pytest
  compiler/luci-pass-value-py-test/CMakeLists.txt
  compiler/luci-pass-value-py-test/README.md
  compiler/luci-pass-value-py-test/conftest.py
  compiler/luci-pass-value-py-test/requires.cmake
  compiler/luci-pass-value-py-test/test.lst
  compiler/luci-pass-value-py-test/test_luci_eval.py
Labels: PR/ready for review

#12145 [cker] Make Mul support bool type
  compute/cker/include/cker/operation/BinaryArithmeticOps.h
  compute/cker/include/cker/operation/reference/BinaryArithmeticOps.h
  compute/cker/src/Mul.test.cc
Labels: PR/ready for review

#12225 [infra/onert] Add mio-circle07 for luci build
  Makefile.template
  packaging/nnfw.spec
Labels: PR/ready for review

#12236 [luci-pass-value-test] Trun off the test
  compiler/luci-pass-value-test/exclude.me
Labels: PR/ready for review

#12239 [infra] Update compiler modules for py test
  infra/scripts/compiler_modules.sh
Labels: PR/ready for review

#12245 [circle-part-value-py-test] Introduce py test
  compiler/circle-part-value-py-test/CMakeLists.txt
  compiler/circle-part-value-py-test/README.md
  compiler/circle-part-value-py-test/conftest.py
  compiler/circle-part-value-py-test/parts/Net_InstanceNorm_003.001.part
  compiler/circle-part-value-py-test/parts/Net_InstanceNorm_003.002.part
  compiler/circle-part-value-py-test/parts/Net_InstanceNorm_003.003.part
  compiler/circle-part-value-py-test/parts/Net_InstanceNorm_003.part
  compiler/circle-part-value-py-test/parts/Net_UnpackAdd_001.001.part
  compiler/circle-part-value-py-test/parts/Net_UnpackAdd_001.002.part
  compiler/circle-part-value-py-test/parts/Net_UnpackAdd_001.part
  compiler/circle-part-value-py-test/parts/Part_Add_Sqrt_000.part
  compiler/circle-part-value-py-test/parts/Part_Add_Sqrt_Rsqrt_000.part
  compiler/circle-part-value-py-test/parts/Part_Add_Sub_000.001.part
  compiler/circle-part-value-py-test/parts/Part_Add_Sub_000.part
  compiler/circle-part-value-py-test/parts/Part_Add_Sub_001.part
  compiler/circle-part-value-py-test/parts/Part_Add_Sub_002.001.part
  compiler/circle-part-value-py-test/parts/Part_Add_Sub_002.002.part
  compiler/circle-part-value-py-test/parts/Part_If_Add_Sub_000.001.part
  compiler/circle-part-value-py-test/parts/Part_If_Add_Sub_001.001.part
  compiler/circle-part-value-py-test/parts/Part_Mul_Sqrt_FC_nobias_000_000.part
  compiler/circle-part-value-py-test/parts/Part_Mul_Sqrt_FC_nobias_000_001.part
  compiler/circle-part-value-py-test/parts/Part_Mul_Sqrt_FC_nobias_000_002.part
  compiler/circle-part-value-py-test/parts/Part_Split_Add_000.part
  compiler/circle-part-value-py-test/parts/Part_Sqrt_Rsqrt_000.part
  compiler/circle-part-value-py-test/parts/Part_Sqrt_Rsqrt_001.part
  compiler/circle-part-value-py-test/parts/Part_Sqrt_Rsqrt_002.part
  compiler/circle-part-value-py-test/parts/Part_Sqrt_Rsqrt_003.part
  compiler/circle-part-value-py-test/parts/Part_Sqrt_Rsqrt_Add_000.part
  compiler/circle-part-value-py-test/parts/Part_Sqrt_Rsqrt_Add_001.part
  compiler/circle-part-value-py-test/parts/Part_Sqrt_Rsqrt_Add_002.part
  compiler/circle-part-value-py-test/parts/Part_Sqrt_Rsqrt_Add_003.part
  compiler/circle-part-value-py-test/parts/Part_Sqrt_Rsqrt_Add_004.part
  compiler/circle-part-value-py-test/parts/Part_Tanh_FC_nobias.part
  compiler/circle-part-value-py-test/parts/Part_Tanh_FC_nobias_001.part
  compiler/circle-part-value-py-test/parts/Part_Tanh_FC_nobias_002.part
  compiler/circle-part-value-py-test/parts/Part_Tanh_FC_nobias_003.part
  compiler/circle-part-value-py-test/parts/Part_While_000.part
  compiler/circle-part-value-py-test/parts/Part_While_001.part
  compiler/circle-part-value-py-test/parts/SignatureDef_MultiOut_000.part
  compiler/circle-part-value-py-test/parts/SignatureDef_MultiOut_001.part
  compiler/circle-part-value-py-test/requires.cmake
  compiler/circle-part-value-py-test/test.lst
  compiler/circle-part-value-py-test/test_circle_part_value.py
Labels: PR/ready for review

#12231 [onert] Apply bool type kernel of Mul op
  compute/cker/include/cker/operation/BinaryArithmeticOps.h
  runtime/onert/backend/cpu/ops/BinaryArithmeticLayer.cc
  tests/nnfw_api/src/one_op_tests/Mul.test.cc
Labels: PR/ready for review

#12251 [infra] Add circle-part-value-py-test to compiler modules
  infra/scripts/compiler_modules.sh
Labels: PR/ready for review

#12252 [record-minmax-conversion-test] Revise test
  compiler/record-minmax-conversion-test/gen_h5_random_inputs.py
  compiler/record-minmax-conversion-test/gen_h5_random_inputs_all.py
  compiler/record-minmax-conversion-test/testall.sh
Labels: PR/ready for review

#12258 [res] TensorFlowLiteRecipes for mul div pattern
  res/TensorFlowLiteRecipes/Net_Mul_Div_000/test.recipe
  res/TensorFlowLiteRecipes/Net_Mul_Div_000/test.rule
Labels: approval: 2

#12259 [res] TensorFlowLiteRecipes for reshape mean pattern
  res/TensorFlowLiteRecipes/Net_Reshape_Mean_000/test.recipe
Labels: approval: 2

#12260 [luci/pass] Extend ForwardReshapeToUnaryOpPass with Mul and Div ops
  compiler/luci/pass/src/ForwardReshapeToUnaryOpPass.cpp
Labels: approval: 2

#12262 [luci/pass] Introduce FuseMulWithDivPass
  compiler/luci/pass/include/luci/CircleOptimizer.h
  compiler/luci/pass/include/luci/Pass/FuseMulWithDivPass.h
  compiler/luci/pass/src/CircleOptimizer.cpp
  compiler/luci/pass/src/FuseMulWithDivPass.cpp
  compiler/luci/pass/src/FuseMulWithDivPass.test.cpp
Labels: approval: 2

#12163 [onert] Update Categorical crossentropy implementation
  compute/cker/include/cker/train/operation/Loss.h
  compute/cker/src/train/Loss.test.cc
  runtime/onert/backend/train/ops/LossCategoricalCrossentropyLayer.cc
  runtime/onert/backend/train/ops/LossCategoricalCrossentropyLayer.h
Labels: PR/ready for review

#12282 [circle-interpreter-test] Update requires.cmake
  compiler/circle-interpreter-test/requires.cmake
Labels: PR/ready for review

#12283 [one-cmds] Preprocess the image in numpy format to test numpy2hdf5
  compiler/one-cmds/tests/CMakeLists.txt
  compiler/one-cmds/tests/preprocess_images_numpy.py
Labels: PR/ready for review

#12272 [pota-quantization-value-test] Revise test
  compiler/pota-quantization-value-test/CMakeLists.txt
  compiler/pota-quantization-value-test/compare_tensors.py
  compiler/pota-quantization-value-test/compare_tensors_all.py
  compiler/pota-quantization-value-test/gen_h5_explicit_inputs.py
  compiler/pota-quantization-value-test/gen_h5_explicit_inputs_all.py
  compiler/pota-quantization-value-test/test_fake_wquant.sh
  compiler/pota-quantization-value-test/test_fake_wquant_with_config.sh
  compiler/pota-quantization-value-test/test_parallel_record_minmax.sh
  compiler/pota-quantization-value-test/test_quantization.sh
  compiler/pota-quantization-value-test/test_quantization_with_config.sh
  compiler/pota-quantization-value-test/test_record_minmax.sh
  compiler/pota-quantization-value-test/test_wo_quantization.sh
Labels: PR/ready for review

#12286 [circle2circle] Add fuse_mul_with_div option
  compiler/circle2circle/src/Circle2Circle.cpp
Labels: approval: 2

#12298 [one-cmds] Deprecate one-build test
  compiler/one-cmds/tests/OONE-BUILD_014.cfg
  compiler/one-cmds/tests/one-build_001.cfg
  compiler/one-cmds/tests/one-build_001.test
  compiler/one-cmds/tests/one-build_002.cfg
  compiler/one-cmds/tests/one-build_002.test
  compiler/one-cmds/tests/one-build_003.cfg
  compiler/one-cmds/tests/one-build_003.test
  compiler/one-cmds/tests/one-build_004.cfg
  compiler/one-cmds/tests/one-build_004.test
  compiler/one-cmds/tests/one-build_005.cfg
  compiler/one-cmds/tests/one-build_005.test
  compiler/one-cmds/tests/one-build_006.cfg
  compiler/one-cmds/tests/one-build_006.test
  compiler/one-cmds/tests/one-build_007.cfg
  compiler/one-cmds/tests/one-build_007.test
  compiler/one-cmds/tests/one-build_008.cfg
  compiler/one-cmds/tests/one-build_008.test
  compiler/one-cmds/tests/one-build_009.cfg
  compiler/one-cmds/tests/one-build_009.test
  compiler/one-cmds/tests/one-build_010.cfg
  compiler/one-cmds/tests/one-build_010.test
  compiler/one-cmds/tests/one-build_011.cfg
  compiler/one-cmds/tests/one-build_011.test
  compiler/one-cmds/tests/one-build_012.cfg
  compiler/one-cmds/tests/one-build_012.test
  compiler/one-cmds/tests/one-build_013.cfg
  compiler/one-cmds/tests/one-build_013.test
  compiler/one-cmds/tests/one-build_014.cfg
  compiler/one-cmds/tests/one-build_014.test
  compiler/one-cmds/tests/one-build_neg_001.test
  compiler/one-cmds/tests/one-build_neg_002.cfg
  compiler/one-cmds/tests/one-build_neg_002.test
  compiler/one-cmds/tests/one-build_neg_003.cfg
  compiler/one-cmds/tests/one-build_neg_003.test
  compiler/one-cmds/tests/one-build_neg_004.cfg
  compiler/one-cmds/tests/one-build_neg_004.test
  compiler/one-cmds/tests/one-build_neg_005.cfg
  compiler/one-cmds/tests/one-build_neg_005.test
  compiler/one-cmds/tests/one-build_neg_006.cfg
  compiler/one-cmds/tests/one-build_neg_006.test
  compiler/one-cmds/tests/one-build_neg_007.test
  compiler/one-cmds/tests/one-build_neg_008.test
  compiler/one-cmds/tests/one-build_neg_009.test
Labels: PR/ready for review

#12288 [tools/onert_train] Implement basic skeleton code of validation
  tests/tools/onert_train/src/onert_train.cc
Labels: PR/ready for review

#12261 [luci/pass] Extend ForwardReshapeToUnaryOpPass with Mean op
  compiler/luci/pass/src/ForwardReshapeToUnaryOpPass.cpp
  compiler/luci/pass/src/ForwardReshapeToUnaryOpPass.test.cpp
Labels: approval: 2

#12305 [luci-pass-value-py-test] Add fuse_mul_with_div test
  compiler/luci-pass-value-py-test/test.lst
Labels: approval: 2

#12304 [circle2circle-dredd-recipe-test] Add fuse_mul_with_div test
  compiler/circle2circle-dredd-recipe-test/test.lst
Labels: approval: 2

#12301 [onert] Remove ONERT_TRAIN flag
  runtime/onert/api/src/nnfw_api.cc
  runtime/onert/api/src/nnfw_api_internal.cc
  runtime/onert/api/src/nnfw_api_internal.h
  runtime/onert/backend/CMakeLists.txt
  runtime/onert/core/CMakeLists.txt
  runtime/onert/core/include/exec/Execution.h
  runtime/onert/core/src/backend/builtin/Backend.h
  runtime/onert/core/src/compiler/CompilerFactory.cc
  runtime/onert/core/src/compiler/ExecutorFactory.cc
  runtime/onert/core/src/compiler/ExecutorFactory.h
  runtime/onert/core/src/dumper/text/GraphDumper.cc
  runtime/onert/core/src/dumper/text/GraphDumper.h
  runtime/onert/core/src/exec/Execution.cc
Labels: PR/ready for review

#12300 [onert] Introduce nnfw_train_set_output api
  runtime/onert/api/include/nnfw_experimental.h
  runtime/onert/api/src/nnfw_api.cc
  runtime/onert/api/src/nnfw_api_internal.cc
  runtime/onert/api/src/nnfw_api_internal.h
Labels: PR/ready for review

#12281 [onert] Make log aligned using fixed width of index
  runtime/onert/core/include/ir/Index.h
  runtime/onert/core/src/dumper/text/GraphDumper.cc
Labels: type/suggestion

#12302 [tools/onert_train] Add metric argument
  tests/tools/onert_train/src/args.cc
  tests/tools/onert_train/src/args.h
Labels: PR/ready for review

#12307 [infra/onert] Fix cmake overlay searching
  infra/nnfw/CMakeLists.txt
  infra/nnfw/cmake/packages/ARMComputeConfig.cmake
  infra/nnfw/cmake/packages/LuciConfig.cmake
Labels: PR/ready for review

#12309 [circle-quantizer] Prevent copy of an object
  compiler/circle-quantizer/src/CircleQuantizer.cpp
Labels: PR/ready for review

#12308 [circle-mqpsolver] Prevent copy of an object
  compiler/circle-mpqsolver/src/bisection/VISQErrorApproximator.cpp
  compiler/circle-mpqsolver/src/pattern/PatternSolver.cpp
Labels: PR/ready for review

#12306 [one-cmds] Enable fuse_mul_div
  compiler/one-cmds/how-to-use-one-commands.txt
  compiler/one-cmds/onelib/constant.py
Labels: approval: 2

#12312 [luci-pass-value-py-test] Add Net_Reshape_Mean_000 test
  compiler/luci-pass-value-py-test/test.lst
Labels: approval: 2

#12316 [infra/onert] Remove training feature option
  infra/nnfw/cmake/CfgOptionFlags.cmake
Labels: PR/ready for review

#12315 [onert] Update half library
  runtime/3rdparty/half/README.md
  runtime/3rdparty/half/include/half/ChangeLog.txt
  runtime/3rdparty/half/include/half/LICENSE.txt
  runtime/3rdparty/half/include/half/README.txt
  runtime/3rdparty/half/include/half/include/half.hpp
Labels: PR/ready for review

#12294 [onert] Introduce metadata to model and loader
  runtime/onert/core/include/ir/Model.h
  runtime/onert/frontend/base_loader/include/base_loader.h
  runtime/onert/frontend/circle/src/circle_loader.cc
  runtime/onert/frontend/tflite/src/tflite_loader.cc
Labels: PR/ready for review, approval: 2

#12303 [tools/onert_train] Introduce Metric class
  tests/tools/onert_train/CMakeLists.txt
  tests/tools/onert_train/src/metrics.cc
  tests/tools/onert_train/src/metrics.h
Labels: PR/ready for review

#12314 [one-cmds] Fix fuse_mul_with_div option
  compiler/one-cmds/how-to-use-one-commands.txt
  compiler/one-cmds/onelib/constant.py
Labels: approval: 2

#12321 [tools/onert_train] Add validation_split argument
  tests/tools/onert_train/src/args.cc
  tests/tools/onert_train/src/args.h
Labels: PR/ready for review

#12331 [onert/train] Fix build fail
  tests/tools/onert_train/src/nnfw_util.h
Labels: PR/ready for review

#12333 [onert] Add OptimizerInfo default constructor
  runtime/onert/core/include/compiler/train/TrainingInfo.h
  runtime/onert/core/include/ir/train/OptimizerInfo.h
Labels: approval: 2

#12324 [tools/onert_train] Introduce DataLoader class
  tests/tools/onert_train/src/dataloader.h
  tests/tools/onert_train/src/onert_train.cc
  tests/tools/onert_train/src/rawdataloader.cc
  tests/tools/onert_train/src/rawdataloader.h
  tests/tools/onert_train/test/rawdataloader.test.cc
Labels: PR/ready for review

#12334 [tools/onert_train] Add the required software tools to readme file
  tests/tools/onert_train/README.md
Labels: PR/ready for review

#12339 [tools/onert_train] Apply validation split value
  tests/tools/onert_train/src/onert_train.cc
Labels: PR/ready for review

#12341 [luci-value-py-test] Enable BroadcastTo operation
  compiler/luci-value-py-test/test.lst
Labels: PR/ready for review

#12340 [onert] Introduce ir::train::TrainingInfo
  runtime/onert/core/include/compiler/train/TrainingInfo.h
  runtime/onert/core/include/ir/train/TrainingInfo.h
  runtime/onert/core/src/ir/train/TrainingInfo.cc
Labels: PR/ready for review, approval: 2

#12336 Release note 1.26.0
  docs/release/1.26/index.rst
  docs/release/1.26/release-note-1.26.0.md
Labels: PR/ready for review, type/release

#12344 [debian] Update changelog
  infra/debian/compiler/changelog
Labels: PR/ready for review, type/release

#12350 [pp] Add cstdint header include
  compiler/pp/include/pp/IndentedStringBuilder.h
Labels: PR/ready for review

#12354 [infra] Fix flatc build error
  infra/cmake/packages/FlatBuffers-2.0/FlatBuffersConfig.cmake
Labels: PR/ready for review

#12356 [infra/onert] Fix buildtool build bug
  infra/buildtool/CMakeLists.txt
Labels: PR/ready for review

#12360 [onert] Update TrainingInfo::isValid() condition
  runtime/onert/core/src/ir/train/TrainingInfo.cc
Labels: PR/ready for review, approval: 2

#12351 [tools/onert_train] Use metric parameter
  tests/tools/onert_train/src/args.cc
  tests/tools/onert_train/src/onert_train.cc
Labels: PR/ready for review

#12353 [infra] Add riscv64 HOST_ARCH and TARGET_ARCH
  infra/cmake/modules/IdentifyPlatform.cmake
Labels: PR/ready for review

#12355 [infra] Add RISC-V tizen cmake build config and options
  infra/nncc/cmake/options/options_riscv64-tizen.cmake
  infra/nnfw/cmake/buildtool/config/config_riscv64-tizen.cmake
  infra/nnfw/cmake/options/options_riscv64-tizen.cmake
Labels: PR/ready for review

#12363 [onert] Remove training start and finish log
  runtime/onert/core/src/exec/Execution.cc
Labels: PR/ready for review

#12342 [onert/api] Add TrainingInfo into nnfw_session
  runtime/onert/api/src/nnfw_api_internal.cc
  runtime/onert/api/src/nnfw_api_internal.h
Labels: PR/ready for review, approval: 2

#12361 [onert] Implement ReduceMean gradient kernel
  compute/cker/include/cker/train/operation/ReduceMean.h
  compute/cker/src/train/ReduceMean.test.cc
Labels: PR/ready for review

#12364 [infra/onert] Fix buildtool build bug (#12356)
  infra/buildtool/CMakeLists.txt
Labels: type/release

#12317 [one-cmds] Introduce one-create-quant-dataset
  compiler/one-cmds/CMakeLists.txt
  compiler/one-cmds/one-create-quant-dataset
  compiler/one-cmds/tests/one-create-quant-dataset_001.test
  compiler/one-cmds/tests/one-create-quant-dataset_002.test
  compiler/one-cmds/tests/one-create-quant-dataset_neg_001.test
  compiler/one-cmds/tests/one-create-quant-dataset_neg_002.test
  compiler/one-cmds/tests/one-create-quant-dataset_neg_003.test
  compiler/one-cmds/tests/one-create-quant-dataset_neg_004.test
  compiler/one-cmds/tests/one-create-quant-dataset_neg_005.test
Labels: PR/ready for review

#12365 [onert] Change DERIVATIVE log to BACK_PROP
  runtime/onert/backend/train/TensorManager.cc
Labels: PR/ready for review

#12362 [onert] Introduce AUTO loss reduction type
  runtime/onert/api/include/nnfw_experimental.h
  runtime/onert/api/src/nnfw_api_internal.cc
  runtime/onert/core/include/compiler/train/TrainingInfo.h
  runtime/onert/core/include/ir/train/LossInfo.h
  tests/tools/onert_train/src/args.cc
  tests/tools/onert_train/src/nnfw_util.cc
  tests/tools/onert_train/src/onert_train.cc
Labels: PR/ready for review

#12318 [luci/pass] Introduce ResovleFormerCustomOpPass
  compiler/luci/pass/include/luci/CircleOptimizer.h
  compiler/luci/pass/include/luci/Pass/ResolveFormerCustomOpPass.h
  compiler/luci/pass/src/CircleOptimizer.cpp
  compiler/luci/pass/src/ResolveFormerCustomOpPass.cpp
  compiler/luci/pass/src/ResolveFormerCustomOpPass.test.cpp
Labels: PR/ready for review

#12352 [one-cmds] Invoke preprocessing script for numpy files
  compiler/one-cmds/tests/prepare_test_materials.sh
Labels: PR/ready for review

#12366 [onert] Rename DERIVATIVE to BACK_PROP in marco definition
  runtime/onert/core/src/compiler/train/StaticBackPropShapeInferer.h
Labels: PR/ready for review

#12375 [onert/cker] Update ReduceMeanGrad to consider floating point error
  compute/cker/src/train/ReduceMean.test.cc
Labels: PR/ready for review, approval: 2

#12376 [onert] Rename backward operands from BackProp to Backward
  runtime/onert/core/include/ir/train/TrainableGraph.h
  runtime/onert/core/src/compiler/ExecutorFactory.cc
  runtime/onert/core/src/compiler/train/StaticBackwardShapeInferer.cc
  runtime/onert/core/src/compiler/train/StaticBackwardShapeInferer.h
  runtime/onert/core/src/compiler/train/TrainingCompiler.cc
  runtime/onert/core/src/ir/train/TrainableGraph.cc
Labels: PR/ready for review

#12369 [onert] Replace compiler::train::TrainingInfo with ir::train::TrainingInfo
  runtime/onert/api/src/nnfw_api_internal.cc
  runtime/onert/core/include/compiler/CompilerFactory.h
  runtime/onert/core/include/compiler/train/TrainingInfo.h
  runtime/onert/core/include/ir/train/TrainingInfo.h
  runtime/onert/core/src/compiler/CompilerFactory.cc
  runtime/onert/core/src/compiler/ExecutorFactory.cc
  runtime/onert/core/src/compiler/ExecutorFactory.h
  runtime/onert/core/src/compiler/train/TrainableOperationConverter.cc
  runtime/onert/core/src/compiler/train/TrainableOperationConverter.h
  runtime/onert/core/src/compiler/train/TrainingCompiler.cc
  runtime/onert/core/src/compiler/train/TrainingCompiler.h
  runtime/onert/core/src/compiler/train/pass/LossInsertionPass.cc
  runtime/onert/core/src/compiler/train/pass/LossInsertionPass.h
  runtime/onert/core/src/compiler/train/pass/Pass.h
Labels: PR/ready for review, approval: 2

#12379 [tools/onert_train] Add vdata_length check logic
  tests/tools/onert_train/src/onert_train.cc
Labels: PR/ready for review

#12384 [onert/api] Add nnfw_train_set_traininfo()
  runtime/onert/api/include/nnfw_experimental.h
  runtime/onert/api/src/nnfw_api.cc
  runtime/onert/api/src/nnfw_api_internal.cc
  runtime/onert/api/src/nnfw_api_internal.h
Labels: PR/ready for review, approval: 2

#12383 [onert] Remove training info from nnfw_train_prepare
  runtime/onert/api/include/nnfw_experimental.h
  runtime/onert/api/src/nnfw_api.cc
  runtime/onert/api/src/nnfw_api_internal.cc
  runtime/onert/api/src/nnfw_api_internal.h
  tests/tools/onert_train/src/onert_train.cc
Labels: PR/ready for review, approval: 2

#12387 [one-cmds] Add one-create-quant-dataset to debian package
  infra/debian/compiler/one-compiler.install
Labels: PR/ready for review
