Repository Samsung/ONE, pull requests merged in 2023-10, with the labels that each got.

#11622 [onert-micro] Add float DepthToSpace kernels
  onert-micro/luci-interpreter/include/luci_interpreter/test_models/depth_to_space/FloatDepthToSpaceKernel.h
  onert-micro/luci-interpreter/include/luci_interpreter/test_models/depth_to_space/NegDepthToSpaceKernel.h
  onert-micro/luci-interpreter/include/luci_interpreter/test_models/depth_to_space/TestDataDepthToSpaceBase.h
  onert-micro/luci-interpreter/pal/cmsisnn/KernelsToBuild.lst
  onert-micro/luci-interpreter/pal/common/PALDepthToSpace.h
  onert-micro/luci-interpreter/pal/mcu/KernelsToBuild.lst
  onert-micro/luci-interpreter/src/kernels/DepthToSpace.cpp
  onert-micro/luci-interpreter/src/kernels/DepthToSpace.h
  onert-micro/luci-interpreter/src/kernels/DepthToSpace.test.cpp
Labels: approval: 1

#11623 [onert-micro] Add float SpaceToDepth kernels
  onert-micro/luci-interpreter/include/luci_interpreter/test_models/space_to_depth/FloatSpaceToDepthKernel.h
  onert-micro/luci-interpreter/include/luci_interpreter/test_models/space_to_depth/NegSpaceToDepthKernel.h
  onert-micro/luci-interpreter/include/luci_interpreter/test_models/space_to_depth/TestDataSpaceToDepthBase.h
  onert-micro/luci-interpreter/pal/cmsisnn/KernelsToBuild.lst
  onert-micro/luci-interpreter/pal/common/PALSpaceToDepth.h
  onert-micro/luci-interpreter/pal/mcu/KernelsToBuild.lst
  onert-micro/luci-interpreter/src/kernels/SpaceToDepth.cpp
  onert-micro/luci-interpreter/src/kernels/SpaceToDepth.h
  onert-micro/luci-interpreter/src/kernels/SpaceToDepth.test.cpp
Labels: approval: 1

#11624 [onert-micro] Add float LogSoftmax kernels
  onert-micro/luci-interpreter/include/luci_interpreter/test_models/log_softmax/FloatLogSoftmaxKernel.h
  onert-micro/luci-interpreter/include/luci_interpreter/test_models/log_softmax/NegLogSoftmaxKernel.h
  onert-micro/luci-interpreter/include/luci_interpreter/test_models/log_softmax/TestDataLogSoftmaxBase.h
  onert-micro/luci-interpreter/pal/cmsisnn/KernelsToBuild.lst
  onert-micro/luci-interpreter/pal/common/PALLogSoftmax.h
  onert-micro/luci-interpreter/pal/mcu/KernelsToBuild.lst
  onert-micro/luci-interpreter/src/kernels/LogSoftmax.cpp
  onert-micro/luci-interpreter/src/kernels/LogSoftmax.h
  onert-micro/luci-interpreter/src/kernels/LogSoftmax.test.cpp
Labels: approval: 1

#11625 [onert-micro] Add float Round kernels
  onert-micro/luci-interpreter/include/luci_interpreter/test_models/round/FloatRoundKernel.h
  onert-micro/luci-interpreter/include/luci_interpreter/test_models/round/NegRoundKernel.h
  onert-micro/luci-interpreter/include/luci_interpreter/test_models/round/TestDataRoundBase.h
  onert-micro/luci-interpreter/pal/cmsisnn/KernelsToBuild.lst
  onert-micro/luci-interpreter/pal/common/PALRound.h
  onert-micro/luci-interpreter/pal/mcu/KernelsToBuild.lst
  onert-micro/luci-interpreter/src/kernels/Round.cpp
  onert-micro/luci-interpreter/src/kernels/Round.test.cpp
  onert-micro/luci-interpreter/src/loader/GraphLoader.cpp
Labels: approval: 1

#11627 [onert-micro] Add float Ceil kernels
  onert-micro/luci-interpreter/include/luci_interpreter/test_models/ceil/FloatCeilKernel.h
  onert-micro/luci-interpreter/include/luci_interpreter/test_models/ceil/NegCeilKernel.h
  onert-micro/luci-interpreter/include/luci_interpreter/test_models/ceil/TestDataCeilBase.h
  onert-micro/luci-interpreter/pal/cmsisnn/KernelsToBuild.lst
  onert-micro/luci-interpreter/pal/common/PALCeil.h
  onert-micro/luci-interpreter/pal/mcu/KernelsToBuild.lst
  onert-micro/luci-interpreter/src/kernels/Ceil.cpp
  onert-micro/luci-interpreter/src/kernels/Ceil.test.cpp
  onert-micro/luci-interpreter/src/loader/GraphLoader.cpp
Labels: approval: 1

#11628 [onert-micro] Introduce Maximum kernel
  onert-micro/luci-interpreter/include/luci_interpreter/test_models/maximum/FloatMaximumKernel.h
  onert-micro/luci-interpreter/include/luci_interpreter/test_models/maximum/NegMaximumKernel.h
  onert-micro/luci-interpreter/include/luci_interpreter/test_models/maximum/TestDataMaximumBase.h
  onert-micro/luci-interpreter/pal/common/PALMaximumCommon.h
  onert-micro/luci-interpreter/pal/mcu/KernelsToBuild.lst
  onert-micro/luci-interpreter/pal/mcu/PALMaximum.h
  onert-micro/luci-interpreter/src/kernels/Maximum.cpp
  onert-micro/luci-interpreter/src/kernels/Maximum.h
  onert-micro/luci-interpreter/src/kernels/Maximum.test.cpp
Labels: approval: 1

#11629 [onert-micro] Rename include guard in PALMinimum.h
  onert-micro/luci-interpreter/pal/mcu/PALMinimum.h
Labels: approval: 1

#11632 [onert-micro] Add float Cast kernels
  onert-micro/luci-interpreter/include/luci_interpreter/test_models/cast/FloatCastKernel.h
  onert-micro/luci-interpreter/include/luci_interpreter/test_models/cast/NegCastKernel.h
  onert-micro/luci-interpreter/include/luci_interpreter/test_models/cast/TestDataCastBase.h
  onert-micro/luci-interpreter/pal/cmsisnn/KernelsToBuild.lst
  onert-micro/luci-interpreter/pal/mcu/KernelsToBuild.lst
  onert-micro/luci-interpreter/src/kernels/Cast.cpp
  onert-micro/luci-interpreter/src/kernels/Cast.h
  onert-micro/luci-interpreter/src/kernels/Cast.test.cpp
Labels: approval: 1

#11633 [onert-micro] Add float BroadcastTo kernels
  onert-micro/luci-interpreter/include/luci_interpreter/test_models/broadcast_to/FloatBroadcastToKernel.h
  onert-micro/luci-interpreter/include/luci_interpreter/test_models/broadcast_to/NegBroadcastToKernel.h
  onert-micro/luci-interpreter/include/luci_interpreter/test_models/broadcast_to/TestDataBroadcastToBase.h
  onert-micro/luci-interpreter/pal/cmsisnn/KernelsToBuild.lst
  onert-micro/luci-interpreter/pal/common/PALBroadcastTo.h
  onert-micro/luci-interpreter/pal/mcu/KernelsToBuild.lst
  onert-micro/luci-interpreter/src/kernels/BroadcastTo.cpp
  onert-micro/luci-interpreter/src/kernels/BroadcastTo.test.cpp
Labels: approval: 1

#11634 [onert-micro] Add float GatherND kernels
  onert-micro/luci-interpreter/include/luci_interpreter/test_models/gather_nd/FloatGatherNDKernel.h
  onert-micro/luci-interpreter/include/luci_interpreter/test_models/gather_nd/NegGatherNDKernel.h
  onert-micro/luci-interpreter/include/luci_interpreter/test_models/gather_nd/TestDataGatherNDBase.h
  onert-micro/luci-interpreter/pal/cmsisnn/KernelsToBuild.lst
  onert-micro/luci-interpreter/pal/common/PALGatherND.h
  onert-micro/luci-interpreter/pal/mcu/KernelsToBuild.lst
  onert-micro/luci-interpreter/src/kernels/GatherND.cpp
  onert-micro/luci-interpreter/src/kernels/GatherND.test.cpp
Labels: approval: 1

#11635 [onert-micro] Add float ReduceMax kernels
  onert-micro/luci-interpreter/include/luci_interpreter/test_models/reduce_max/FloatReduceMaxKernel.h
  onert-micro/luci-interpreter/include/luci_interpreter/test_models/reduce_max/NegReduceMaxKernel.h
  onert-micro/luci-interpreter/include/luci_interpreter/test_models/reduce_max/TestDataReduceMaxBase.h
  onert-micro/luci-interpreter/pal/cmsisnn/KernelsToBuild.lst
  onert-micro/luci-interpreter/pal/mcu/KernelsToBuild.lst
  onert-micro/luci-interpreter/src/kernels/ReduceMax.cpp
  onert-micro/luci-interpreter/src/kernels/ReduceMax.test.cpp
Labels: approval: 1

#11636 [onert-micro] Add float L2Pool2D kernels
  onert-micro/luci-interpreter/include/luci_interpreter/test_models/l2_poop_2d/FloatL2Pool2DKernel.h
  onert-micro/luci-interpreter/include/luci_interpreter/test_models/l2_poop_2d/NegL2Pool2DKernel.h
  onert-micro/luci-interpreter/include/luci_interpreter/test_models/l2_poop_2d/TestDataL2Pool2DBase.h
  onert-micro/luci-interpreter/pal/cmsisnn/KernelsToBuild.lst
  onert-micro/luci-interpreter/pal/common/PALL2Pool2D.h
  onert-micro/luci-interpreter/pal/mcu/KernelsToBuild.lst
  onert-micro/luci-interpreter/src/kernels/L2Pool2D.cpp
  onert-micro/luci-interpreter/src/kernels/L2Pool2D.h
  onert-micro/luci-interpreter/src/kernels/L2Pool2D.test.cpp
Labels: approval: 1

#11662 [onert-micro] Introduce LogicalNot kernel
  onert-micro/luci-interpreter/include/luci_interpreter/test_models/logical_not/BoolLogicalNotKernel.h
  onert-micro/luci-interpreter/include/luci_interpreter/test_models/logical_not/NegLogicalNotKernel.h
  onert-micro/luci-interpreter/include/luci_interpreter/test_models/logical_not/TestDataLogicalNotBase.h
  onert-micro/luci-interpreter/pal/common/PALLogicalNotCommon.h
  onert-micro/luci-interpreter/pal/mcu/KernelsToBuild.lst
  onert-micro/luci-interpreter/pal/mcu/PALLogicalNot.h
  onert-micro/luci-interpreter/src/kernels/LogicalNot.cpp
  onert-micro/luci-interpreter/src/kernels/LogicalNot.test.cpp
Labels: approval: 1

#11661 [onert-micro] Add float Mean kernels
  onert-micro/luci-interpreter/include/luci_interpreter/test_models/mean/FloatMeanKernel.h
  onert-micro/luci-interpreter/include/luci_interpreter/test_models/mean/NegMeanKernel.h
  onert-micro/luci-interpreter/include/luci_interpreter/test_models/mean/TestDataMeanBase.h
  onert-micro/luci-interpreter/pal/cmsisnn/KernelsToBuild.lst
  onert-micro/luci-interpreter/pal/common/PALMean.h
  onert-micro/luci-interpreter/pal/common/Params.h
  onert-micro/luci-interpreter/pal/mcu/KernelsToBuild.lst
  onert-micro/luci-interpreter/src/kernels/Mean.cpp
  onert-micro/luci-interpreter/src/kernels/Mean.h
  onert-micro/luci-interpreter/src/kernels/Mean.test.cpp
Labels: approval: 1

#11653 [onert-micro] Add float MirrorPad kernels
  onert-micro/luci-interpreter/include/luci_interpreter/test_models/mirror_pad/FloatMirrorPadKernel.h
  onert-micro/luci-interpreter/include/luci_interpreter/test_models/mirror_pad/NegMirrorPadKernel.h
  onert-micro/luci-interpreter/include/luci_interpreter/test_models/mirror_pad/TestDataMirrorPadBase.h
  onert-micro/luci-interpreter/pal/cmsisnn/KernelsToBuild.lst
  onert-micro/luci-interpreter/pal/common/PALMirrorPad.h
  onert-micro/luci-interpreter/pal/mcu/KernelsToBuild.lst
  onert-micro/luci-interpreter/src/kernels/MirrorPad.cpp
  onert-micro/luci-interpreter/src/kernels/MirrorPad.h
  onert-micro/luci-interpreter/src/kernels/MirrorPad.test.cpp
Labels: approval: 1

#11655 [onert-micro] Add float Sum kernels
  onert-micro/luci-interpreter/include/luci_interpreter/test_models/sum/FloatSumKernel.h
  onert-micro/luci-interpreter/include/luci_interpreter/test_models/sum/NegSumKernel.h
  onert-micro/luci-interpreter/include/luci_interpreter/test_models/sum/TestDataSumBase.h
  onert-micro/luci-interpreter/pal/cmsisnn/KernelsToBuild.lst
  onert-micro/luci-interpreter/pal/mcu/KernelsToBuild.lst
  onert-micro/luci-interpreter/src/kernels/Sum.cpp
  onert-micro/luci-interpreter/src/kernels/Sum.test.cpp
Labels: approval: 1

#11671 [onert-micro] Introduce Square kernel
  onert-micro/luci-interpreter/include/luci_interpreter/test_models/square/FloatSquareKernel.h
  onert-micro/luci-interpreter/include/luci_interpreter/test_models/square/NegSquareKernel.h
  onert-micro/luci-interpreter/include/luci_interpreter/test_models/square/TestDataSquareBase.h
  onert-micro/luci-interpreter/pal/common/PALSquareCommon.h
  onert-micro/luci-interpreter/pal/mcu/KernelsToBuild.lst
  onert-micro/luci-interpreter/pal/mcu/PALSquare.h
  onert-micro/luci-interpreter/src/kernels/Square.cpp
  onert-micro/luci-interpreter/src/kernels/Square.h
  onert-micro/luci-interpreter/src/kernels/Square.test.cpp
Labels: approval: 1

#11672 [onert-micro] Introduce Sin kernel
  onert-micro/luci-interpreter/include/luci_interpreter/test_models/sin/FloatSinKernel.h
  onert-micro/luci-interpreter/include/luci_interpreter/test_models/sin/NegSinKernel.h
  onert-micro/luci-interpreter/include/luci_interpreter/test_models/sin/TestDataSinBase.h
  onert-micro/luci-interpreter/pal/common/PALSinCommon.h
  onert-micro/luci-interpreter/pal/mcu/KernelsToBuild.lst
  onert-micro/luci-interpreter/pal/mcu/PALSin.h
  onert-micro/luci-interpreter/src/kernels/Sin.cpp
  onert-micro/luci-interpreter/src/kernels/Sin.test.cpp
Labels: approval: 1

#11673 [onert-micro] Introduce Cos kernel
  onert-micro/luci-interpreter/include/luci_interpreter/test_models/cos/FloatCosKernel.h
  onert-micro/luci-interpreter/include/luci_interpreter/test_models/cos/NegCosKernel.h
  onert-micro/luci-interpreter/include/luci_interpreter/test_models/cos/TestDataCosBase.h
  onert-micro/luci-interpreter/pal/common/PALCosCommon.h
  onert-micro/luci-interpreter/pal/mcu/KernelsToBuild.lst
  onert-micro/luci-interpreter/pal/mcu/PALCos.h
  onert-micro/luci-interpreter/src/kernels/Cos.cpp
  onert-micro/luci-interpreter/src/kernels/Cos.test.cpp
Labels: approval: 1

#11691 [luci] Fake quantize Maximum/Minimum
  compiler/luci/pass/src/ConvertToFakeQuantizedModelPass.cpp
Labels: area/quant

#11680 [onert-micro] Add float SVDF kernels
  onert-micro/luci-interpreter/include/luci_interpreter/test_models/svdf/FloatSVDFKernel.h
  onert-micro/luci-interpreter/include/luci_interpreter/test_models/svdf/NegSVDFKernel.h
  onert-micro/luci-interpreter/include/luci_interpreter/test_models/svdf/TestDataSVDFBase.h
  onert-micro/luci-interpreter/pal/cmsisnn/KernelsToBuild.lst
  onert-micro/luci-interpreter/pal/cmsisnn/PALSVDF.h
  onert-micro/luci-interpreter/pal/common/PALSVDFCommon.h
  onert-micro/luci-interpreter/pal/mcu/KernelsToBuild.lst
  onert-micro/luci-interpreter/pal/mcu/PALSVDF.h
  onert-micro/luci-interpreter/src/kernels/SVDF.cpp
  onert-micro/luci-interpreter/src/kernels/SVDF.h
  onert-micro/luci-interpreter/src/kernels/SVDF.test.cpp
Labels: approval: 1

#11682 [onert-micro] Add float ResizeNearestNeighbor kernels
  onert-micro/luci-interpreter/include/luci_interpreter/test_models/resize_nearest_neighbor/FloatResizeNearestNeighborKernel.h
  onert-micro/luci-interpreter/include/luci_interpreter/test_models/resize_nearest_neighbor/NegResizeNearestNeighborKernel.h
  onert-micro/luci-interpreter/include/luci_interpreter/test_models/resize_nearest_neighbor/TestDataResizeNearestNeighborBase.h
  onert-micro/luci-interpreter/pal/cmsisnn/KernelsToBuild.lst
  onert-micro/luci-interpreter/pal/common/PALResizeNearestNeighbor.h
  onert-micro/luci-interpreter/pal/common/Params.h
  onert-micro/luci-interpreter/pal/mcu/KernelsToBuild.lst
  onert-micro/luci-interpreter/src/kernels/ResizeBilinear.h
  onert-micro/luci-interpreter/src/kernels/ResizeNearestNeighbor.cpp
  onert-micro/luci-interpreter/src/kernels/ResizeNearestNeighbor.h
  onert-micro/luci-interpreter/src/kernels/ResizeNearestNeighbor.test.cpp
Labels: approval: 1

#11639 [onert] Update NNFW Python API
  docs/howto/how-to-use-nnfw-python-api.md
  infra/nnfw/python/README.md
  infra/nnfw/python/nnfwapi/libnnfw_api_pybind.py
  infra/nnfw/python/setup.py
  runtime/onert/python/package/__init__.py
  runtime/onert/python/package/libnnfw_api_pybind.py
  runtime/onert/sample/minimal-python/src/minimal.py
Labels: PR/ready for review, area/onert, SSAFY

#11588 [cker] Bring Adam kernel from tensorflow v2.12.1
  compute/cker/include/cker/eigen/training_ops.h
  compute/cker/include/cker/train/optimizer/Adam.h
  compute/cker/src/train/Adam.test.cc
Labels: PR/ready for review

#11659 [onert] Allocate tensors for optimizer variables
  runtime/onert/backend/train/TensorBuilder.cc
  runtime/onert/backend/train/optimizer/SGD.h
  runtime/onert/core/include/exec/train/optimizer/Optimizer.h
Labels: PR/ready for review

#11700 [luci] Fake quantize Exp
  compiler/luci/pass/src/ConvertToFakeQuantizedModelPass.cpp
Labels: area/quant

#11697 [onert] Introduce and apply adam optimizer
  runtime/onert/backend/train/optimizer/Adam.cc
  runtime/onert/backend/train/optimizer/Adam.h
  runtime/onert/backend/train/optimizer/Optimizers.h
Labels: PR/ready for review

#11606 [infra/runtime] Revise debian build
  infra/debian/runtime/rules
Labels: PR/ready for review

#11656 [cker] Bring SGD kernel from tensorflow v2.12.1
  compute/cker/include/cker/eigen/training_ops.h
  compute/cker/include/cker/train/optimizer/SGD.h
  compute/cker/src/train/SGD.test.cc
Labels: PR/ready for review

#11721 [one-cmds] Support HardSwish decomposing option
  compiler/one-cmds/how-to-use-one-commands.txt
Labels: PR/ready for review

#11686 [onert] Enable max2d PoolLayer for training
  compute/cker/include/cker/train/operation/MaxPool.h
  compute/cker/src/train/MaxPool.test.cc
  runtime/onert/backend/cpu/ops/PoolLayer.h
  runtime/onert/backend/train/KernelGenerator.cc
  runtime/onert/backend/train/KernelGenerator.h
  runtime/onert/backend/train/ops/PoolLayer.cc
  runtime/onert/backend/train/ops/PoolLayer.h
  runtime/onert/core/include/compiler/StaticShapeInferer.h
  runtime/onert/core/src/compiler/StaticShapeInferer.cc
Labels: PR/ready for review, approval: 2

#11715 [onert-micro] Add float Unpack kernel
  onert-micro/luci-interpreter/include/luci_interpreter/test_models/unpack/FloatUnpackKernel.h
  onert-micro/luci-interpreter/include/luci_interpreter/test_models/unpack/NegUnpackKernel.h
  onert-micro/luci-interpreter/include/luci_interpreter/test_models/unpack/TestDataUnpackBase.h
  onert-micro/luci-interpreter/pal/mcu/KernelsToBuild.lst
  onert-micro/luci-interpreter/src/kernels/Unpack.cpp
  onert-micro/luci-interpreter/src/kernels/Unpack.h
  onert-micro/luci-interpreter/src/kernels/Unpack.test.cpp
Labels: approval: 1

#11729 [onert/gpu_cl] Fix compile option for clang
  runtime/onert/backend/gpu_cl/CMakeLists.txt
Labels: PR/ready for review

#11728 [infra] Update docker build default setting
  infra/command/build-docker-image
Labels: PR/ready for review

#11731 [tools/onert_train] Implement memory profiling functions
  tests/tools/onert_train/src/measure.h
  tests/tools/onert_train/src/onert_train.cc
Labels: PR/ready for review

#11732 [tools/onert_run] Add the function to dump input raw data
  tests/tools/onert_run/src/args.cc
  tests/tools/onert_run/src/args.h
  tests/tools/onert_run/src/onert_run.cc
  tests/tools/onert_run/src/rawformatter.cc
  tests/tools/onert_run/src/rawformatter.h
Labels: PR/ready for review

#11733 [infra/acl] Fix build fail on clang
  infra/nnfw/cmake/packages/ARMComputeConfig.cmake
Labels: PR/ready for review

#11658 [onert] Replace SGD kernel with the optimized kernel
  compute/cker/include/cker/train/optimizer/SGD.h
  runtime/onert/backend/train/optimizer/OptimizerHelpers.h
  runtime/onert/backend/train/optimizer/SGD.cc
Labels: PR/ready for review

#11736 [infra/docker] Update android sdk installation
  infra/docker/focal/Dockerfile
Labels: PR/ready for review

#11745 [tools/onert_train] Change default learning rate
  tests/tools/onert_train/src/args.cc
Labels: PR/ready for review

#11752 [tools] Update android SDK & NDK install script
  docs/nnfw/howto/CrossBuildForAndroid.md
  tools/cross/install_android_ndk.sh
  tools/cross/install_android_sdk.sh
Labels: PR/ready for review

#11756 [tools] Revisit install_rootfs.sh
  docs/howto/how-to-cross-build-runtime-for-aarch64.md
  docs/howto/how-to-cross-build-runtime-for-arm.md
  tools/cross/install_rootfs.sh
Labels: PR/ready for review

#11753 [tflchef] Introduce extype and custom_code for custom operators
  compiler/tflchef/proto/tflchef.proto
Labels: PR/ready for review

#11757 [circlechef] Introduce extype and custom_code for custom operators
  compiler/circlechef/proto/circlechef.proto
Labels: PR/ready for review

#11764 [res] Introduce extype and custom_code for custom operators
  res/TensorFlowLiteRecipes/All_000/test.recipe
  res/TensorFlowLiteRecipes/BatchMatMulV2_000/test.recipe
  res/TensorFlowLiteRecipes/BatchMatMulV2_001/test.recipe
  res/TensorFlowLiteRecipes/BroadcastTo_000/test.recipe
  res/TensorFlowLiteRecipes/MatMul_000/test.recipe
  res/TensorFlowLiteRecipes/MatrixBandPart_000/test.recipe
  res/TensorFlowLiteRecipes/MaxPoolWithArgmax_000/test.recipe
  res/TensorFlowLiteRecipes/MaxPoolWithArgmax_001/test.recipe
  res/TensorFlowLiteRecipes/MaxPoolWithArgmax_002/test.recipe
  res/TensorFlowLiteRecipes/Net_BroadcastTo_AddV2_000/test.recipe
  res/TensorFlowLiteRecipes/Net_BroadcastTo_AddV2_001/test.recipe
  res/TensorFlowLiteRecipes/Net_FC_Gelu_FC_000/test.recipe
  res/TensorFlowLiteRecipes/Net_Gather_SparseToDense_AddV2_000/test.recipe
  res/TensorFlowLiteRecipes/Net_Gelu_000/test.recipe
  res/TensorFlowLiteRecipes/Net_Gelu_001/test.recipe
Labels: PR/ready for review

#11755 [onert/python] Fix build issue on cross build
  runtime/onert/python/api/CMakeLists.txt
Labels: PR/ready for review

#11773 [one-quantize] Support QuantizeWeightsOnly for FullyConnected
  compiler/luci/pass/src/QuantizeWeightsOnly.cpp
  compiler/luci/pass/src/QuantizeWeightsOnly.h
Labels: approval: 2

#11783 [luci/pass] Add saving recorded min-max
  compiler/luci/pass/include/luci/CircleQuantizer.h
  compiler/luci/pass/include/luci/Pass/QuantizeWithMinMaxPass.h
  compiler/luci/pass/src/CircleQuantizer.cpp
  compiler/luci/pass/src/PropagateQParamForwardPass.cpp
  compiler/luci/pass/src/QuantizationUtils.cpp
  compiler/luci/pass/src/QuantizationUtils.h
  compiler/luci/pass/src/QuantizeActivation.cpp
  compiler/luci/pass/src/QuantizeWeights.cpp
  compiler/luci/pass/src/QuantizeWithMinMaxPass.cpp
  compiler/luci/pass/src/QuantizeWithMinMaxPass.test.cpp
Labels: approval: 2

#11788 [res] TensorFlowLiteRecipes for horizontal FC pattern fusion
  res/TensorFlowLiteRecipes/Net_Horizontal_FullyConnected_Add_000/test.recipe
  res/TensorFlowLiteRecipes/Net_Horizontal_FullyConnected_Add_000/test.rule
Labels: approval: 2

#11793 [circle-quantizer] Add save_min_max option
  compiler/circle-quantizer/src/CircleQuantizer.cpp
Labels: approval: 2

#11798 [infra] Remove unused cmake config
  infra/3rdparty/.gitignore
  infra/3rdparty/Eigen/fd6845384b86/URL.default
  infra/3rdparty/Eigen/fd6845384b86/URL.info
  infra/cmake/packages/Eigen-fd6845384b86Config.cmake
  infra/cmake/packages/EigenSource-fd6845384b86Config.cmake
  infra/cmake/packages/TensorFlowConfig.cmake
Labels: PR/ready for review

#11787 [luci/pass] Introduce FuseHorizontalFCLayers pass
  compiler/luci/pass/include/luci/CircleOptimizer.h
  compiler/luci/pass/include/luci/Pass/FuseHorizontalFullyConnectedPass.h
  compiler/luci/pass/src/CircleOptimizer.cpp
  compiler/luci/pass/src/FuseHorizontalFullyConnectedPass.cpp
  compiler/luci/pass/src/FuseHorizontalFullyConnectedPass.test.cpp
Labels: approval: 2

#11813 [tflchef] Introduce a op util function to check custom codes
  compiler/tflchef/core/src/CustomOp/AddV2.cpp
  compiler/tflchef/core/src/CustomOp/All.cpp
  compiler/tflchef/core/src/CustomOp/BatchMatMulV2.cpp
  compiler/tflchef/core/src/CustomOp/BroadcastTo.cpp
  compiler/tflchef/core/src/CustomOp/Erf.cpp
  compiler/tflchef/core/src/CustomOp/MatMul.cpp
  compiler/tflchef/core/src/CustomOp/MatrixBandPart.cpp
  compiler/tflchef/core/src/CustomOp/MaxPoolWithArgmax.cpp
  compiler/tflchef/core/src/OpUtils.cpp
  compiler/tflchef/core/src/OpUtils.h
Labels: PR/ready for review

#11818 [infra/gbs] Add tizen 8.0 profile
  infra/nnfw/config/gbs.conf
Labels: PR/ready for review

#11820 [onert/train] Initialize class field for train
  runtime/onert/backend/train/ops/ElementwiseActivationLayer.h
  runtime/onert/core/include/compiler/train/TrainingInfo.h
Labels: PR/ready for review

#11819 [circle2circle] Add fuse_horizontal_fc_layers option
  compiler/circle2circle/src/Circle2Circle.cpp
Labels: approval: 2

#11830 [infra] Update Makefile target dependency
  Makefile.template
Labels: PR/ready for review

#11826 [onert-micro] Add tflite model for example app
  onert-micro/examples/README.md
  onert-micro/examples/models/speech_recognition/speech_recognition_float.tflite
Labels: approval: 1
