Repository Samsung/ONE, pull requests merged in 2023-09, with the labels that each got.

#11418 [record-minmax] Add parameters for moving_average
  compiler/record-minmax/driver/Driver.cpp
Labels: area/quant

#11428 [luci/service] Use explicit int64_t type zero
  compiler/luci/service/src/ShapeInfer_StridedSlice.cpp
Labels: PR/ready for review

#11414 [onert/odc] Introduce Quantizer
  infra/nnfw/CMakeLists.txt
  infra/nnfw/cmake/packages/LuciConfig.cmake
  packaging/nnfw.spec
  runtime/onert/CMakeLists.txt
  runtime/onert/core/include/odc/IQuantizer.h
  runtime/onert/odc/CMakeLists.txt
  runtime/onert/odc/Quantizer.cc
  runtime/onert/odc/Quantizer.h
  runtime/onert/odc/Quantizer.test.cc
Labels: PR/ready for review

#11430 [onert] Use ASSERT_NE for negative test
  runtime/onert/odc/Quantizer.test.cc
Labels: PR/ready for review

#11424 [record-minmax] Remove unused code
  compiler/record-minmax/driver/Driver.cpp
  compiler/record-minmax/include/RecordMinMax.h
  compiler/record-minmax/src/RecordMinMax.cpp
Labels: area/quant

#11431 [onert] Introduce QuantizerLoader
  runtime/onert/core/src/odc/QuantizerLoader.cc
  runtime/onert/core/src/odc/QuantizerLoader.h
  runtime/onert/core/src/odc/QuantizerLoader.test.cc
Labels: PR/ready for review

#11429 [one-cmds] Add moving_average parameters
  compiler/one-cmds/one-quantize
  compiler/one-cmds/tests/one-quantize_021.test
  compiler/one-cmds/tests/one-quantize_neg_023.test
Labels: area/quant

#11419 [onert] Apply IGradientApplier
  runtime/onert/backend/train/KernelGenerator.h
  runtime/onert/backend/train/ops/GradientApplier.cc
  runtime/onert/backend/train/ops/GradientApplier.h
  runtime/onert/core/include/exec/train/ITrainableFunction.h
  runtime/onert/core/include/exec/train/TrainableFnSequence.h
  runtime/onert/core/src/exec/train/TrainableFnSequence.cc
Labels: PR/ready for review

#11466 [record-minmax] Update function signature
  compiler/record-minmax/include/MinMaxComputer.h
  compiler/record-minmax/include/MinMaxObserver.h
  compiler/record-minmax/include/RecordMinMax.h
  compiler/record-minmax/src/MinMaxComputer.cpp
  compiler/record-minmax/src/RecordMinMax.cpp
Labels: area/quant

#11388 [onrt-micro] Fix buffer overflow warning in svace
  onert-micro/luci-interpreter/pal/common/PALReduceCommon.h
  onert-micro/luci-interpreter/src/kernels/ReduceCommon.cpp
Labels: approval: 1

#11472 [record-minmax] Add MinMaxComputer unittest
  compiler/record-minmax/CMakeLists.txt
  compiler/record-minmax/tests/MinMaxComputer.test.cpp
Labels: area/quant

#11470 [onert] Introduce QuantizeManager
  runtime/onert/api/src/nnfw_api_internal.cc
  runtime/onert/api/src/nnfw_api_internal.h
  runtime/onert/core/include/ir/NNPkg.h
  runtime/onert/core/include/odc/QuantizeManager.h
  runtime/onert/core/src/odc/QuantizeManager.cc
  runtime/onert/core/src/odc/QuantizeManager.test.cc
Labels: PR/ready for review

#11473 [onert/test] Add quantization option in onert_run
  runtime/onert/api/src/nnfw_api.cc
  tests/tools/onert_run/src/args.cc
  tests/tools/onert_run/src/args.h
  tests/tools/onert_run/src/onert_run.cc
Labels: PR/ready for review

#11477 [onert] Remove training step from ITranableFunction
  runtime/onert/backend/train/ops/ConvolutionLayer.cc
  runtime/onert/backend/train/ops/ConvolutionLayer.h
  runtime/onert/backend/train/ops/ElementwiseActivationLayer.cc
  runtime/onert/backend/train/ops/ElementwiseActivationLayer.h
  runtime/onert/backend/train/ops/FullyConnectedLayer.cc
  runtime/onert/backend/train/ops/FullyConnectedLayer.h
  runtime/onert/backend/train/ops/LossLayer.cc
  runtime/onert/backend/train/ops/LossLayer.h
  runtime/onert/backend/train/ops/PoolLayer.cc
  runtime/onert/backend/train/ops/PoolLayer.h
  runtime/onert/backend/train/ops/ReshapeLayer.cc
  runtime/onert/backend/train/ops/ReshapeLayer.h
  runtime/onert/core/include/exec/train/ITrainableFunction.h
  runtime/onert/core/include/exec/train/TrainableFnSequence.h
  runtime/onert/core/src/backend/builtin/train/kernel/PermuteLayer.cc
  runtime/onert/core/src/backend/builtin/train/kernel/PermuteLayer.h
  runtime/onert/core/src/exec/train/TrainableFnSequence.cc
Labels: PR/ready for review

#11478 [onert] Close file handle before return
  runtime/onert/core/src/odc/QuantizerLoader.cc
Labels: PR/ready for review

#11482 [onert] Initialize ConvolutionLayer field
  runtime/onert/backend/cpu/ops/ConvolutionLayer.cc
Labels: PR/ready for review

#11488 [onert] Initialize DepthwiseConvolutionLayer field
  runtime/onert/backend/cpu/ops/DepthwiseConvolutionLayer.h
Labels: PR/ready for review

#11495 [infra] Exclude intermediate workspace on SAM exclude file
  .ahub/sam/exclude.txt
Labels: PR/ready for review

#11493 Release note 1.25.0
  docs/release/1.25/index.rst
  docs/release/1.25/release-note_1.25.0.md
Labels: PR/ready for review

#11501 [onert-micor] Update onert-micro verison to 1.0
  onert-micro/luci-interpreter/include/luci_interpreter/onert-micro-version.h
Labels: approval: 1

#11512 [onert/test] Merge test function
  runtime/onert/core/src/exec/IPermuteFunction.test.cc
Labels: PR/ready for review

#11510 [runtime] Update runtime version to 1.26.0
  docs/conf.py
  packaging/nnfw.spec
  runtime/contrib/android/api/build.gradle
  runtime/onert/api/include/nnfw_version.h
Labels: PR/ready for review

#11514 [infra/nnfw] Disable default path when finding luci lib
  infra/nnfw/cmake/packages/LuciConfig.cmake
Labels: PR/ready for review

#11516 [vconone] Bump up to 1.26.0
  compiler/vconone/CMakeLists.txt
Labels: PR/ready for review

#11515 [onert] Fix a missed nullptr check
  runtime/onert/backend/train/ops/FullyConnectedLayer.cc
Labels: PR/ready for review

#11538 [infra/onert] Fix build fail on tizen i686
  infra/nnfw/cmake/options/options_i686-tizen.cmake
Labels: PR/ready for review

#11537 [infra/gbs] Fix build fail for tizen armv7hl
  packaging/nnfw.spec
Labels: PR/ready for review

#11511 [onert] Move OptimizerCode and OptimizerInfo into ir
  runtime/onert/api/src/nnfw_api_internal.cc
  runtime/onert/core/include/compiler/train/TrainingInfo.h
  runtime/onert/core/include/ir/train/OptimizerCode.h
  runtime/onert/core/include/ir/train/OptimizerInfo.h
  runtime/onert/core/src/compiler/train/TrainingCompiler.cc
  runtime/onert/core/src/ir/train/OptimizerCode.cc
Labels: PR/ready for review

#11555 [circle-opselector] Bug on operators having optional input
  compiler/circle-opselector/src/OpSelector.cpp
Labels: PR/ready for review

#11554 [onecc-docker] Revisit onecc-docker command
  compiler/onecc-docker/README.md
  compiler/onecc-docker/debian/control
  compiler/onecc-docker/docker/Dockerfile
  compiler/onecc-docker/onecc-docker
Labels: PR/ready for review

#11546 [onert-micro] Add REGISTER_TRAIN_KERNEL interface
  onert-micro/luci-interpreter/pal/mcu/KernelsToTrain.lst
  onert-micro/luci-interpreter/src/kernels/Builders.h
  onert-micro/luci-interpreter/src/kernels/CMakeLists.txt
  onert-micro/luci-interpreter/src/kernels/KernelBuilder.cpp
  onert-micro/luci-interpreter/src/kernels/KernelBuilder.h
Labels: approval: 1

#11547 [onert-micro] Add training into RuntimeModule
  onert-micro/luci-interpreter/src/core/RuntimeModule.h
Labels: approval: 1

#11548 [onert-micro] Add training into RuntimeGraph
  onert-micro/luci-interpreter/src/core/RuntimeGraph.cpp
  onert-micro/luci-interpreter/src/core/RuntimeGraph.h
Labels: approval: 1

#11549 [onert-micro] Change allocateAndWriteInputTensor's data type
  onert-micro/luci-interpreter/include/luci_interpreter/Interpreter.h
  onert-micro/luci-interpreter/src/Interpreter.cpp
Labels: approval: 1

#11550 [onert-micro] Introduce FullyConnected train kernel
  onert-micro/luci-interpreter/src/kernels/FullyConnected.train.cpp
Labels: approval: 1

#11557 [onert-micro] Introduce TrainingOnertMicro
  onert-micro/luci-interpreter/include/luci_interpreter/Interpreter.h
  onert-micro/luci-interpreter/include/luci_interpreter/TrainingOnertMicro.h
  onert-micro/luci-interpreter/pal/mcu/KernelsToTrain.lst
  onert-micro/luci-interpreter/src/CMakeLists.txt
  onert-micro/luci-interpreter/src/TrainingOnertMicro.cpp
  onert-micro/luci-interpreter/src/kernels/Builders.h
Labels: approval: 1

#11558 [onert-micro] Introduce TrainingDriver
  onert-micro/CMakeLists.txt
  onert-micro/eval-driver/CMakeLists.txt
  onert-micro/eval-driver/TrainingDriver.cpp
  onert-micro/luci-interpreter/CMakeLists.txt
Labels: approval: 1

#11563 [onert-micro] Fix kernels CMake file
  onert-micro/luci-interpreter/src/kernels/CMakeLists.txt
Labels: approval: 1

#11564 [onert-micro] Add cmsis-nn FullyConnected kernel
  onert-micro/luci-interpreter/pal/cmsisnn/KernelsToBuild.lst
  onert-micro/luci-interpreter/pal/cmsisnn/KernelsToTrain.lst
  onert-micro/luci-interpreter/pal/cmsisnn/PALFullyConnected.h
  onert-micro/luci-interpreter/pal/mcu/PALFullyConnected.h
  onert-micro/luci-interpreter/src/kernels/FullyConnected.cpp
Labels: approval: 1

#11565 [onert-micro] Add cmsis-nn Add kernel
  onert-micro/luci-interpreter/pal/cmsisnn/KernelsToBuild.lst
  onert-micro/luci-interpreter/pal/cmsisnn/PALAdd.h
  onert-micro/luci-interpreter/src/kernels/Add.cpp
Labels: approval: 1

#11566 [onert-micro] Add cmsis-nn Mul kernel
  onert-micro/luci-interpreter/pal/cmsisnn/KernelsToBuild.lst
  onert-micro/luci-interpreter/pal/cmsisnn/PALMul.h
  onert-micro/luci-interpreter/src/kernels/Mul.cpp
Labels: approval: 1

#11562 [q-implant] q-implant implementation
  compiler/q-implant/README.md
  compiler/q-implant/src/QImplant.cpp
Labels: area/quant

#11571 [onert-micro] Introduce Floor kernel
  onert-micro/luci-interpreter/include/luci_interpreter/test_models/floor/FloatFloorKernel.h
  onert-micro/luci-interpreter/include/luci_interpreter/test_models/floor/NegFloorKernel.h
  onert-micro/luci-interpreter/include/luci_interpreter/test_models/floor/TestDataFloorBase.h
  onert-micro/luci-interpreter/pal/common/PALFloorCommon.h
  onert-micro/luci-interpreter/pal/mcu/KernelsToBuild.lst
  onert-micro/luci-interpreter/pal/mcu/PALFloor.h
  onert-micro/luci-interpreter/src/kernels/Floor.cpp
  onert-micro/luci-interpreter/src/kernels/Floor.h
  onert-micro/luci-interpreter/src/kernels/Floor.test.cpp
Labels: approval: 1

#11577 [luci-compute] Download neon-to-sse source
  compiler/luci-compute/CMakeLists.txt
Labels: PR/ready for review

#11590 [onert-micro] Add float L2Normalization kernel
  onert-micro/luci-interpreter/include/luci_interpreter/test_models/l2_normalization/FloatL2NormalizeKernel.h
  onert-micro/luci-interpreter/include/luci_interpreter/test_models/l2_normalization/NegL2NormalizeKernel.h
  onert-micro/luci-interpreter/include/luci_interpreter/test_models/l2_normalization/TestDataL2NormalizeBase.h
  onert-micro/luci-interpreter/pal/cmsisnn/KernelsToBuild.lst
  onert-micro/luci-interpreter/pal/cmsisnn/PALL2Pool2D.h
  onert-micro/luci-interpreter/pal/common/PALL2Normalize.h
  onert-micro/luci-interpreter/pal/common/PALUtils.h
  onert-micro/luci-interpreter/pal/mcu/KernelsToBuild.lst
  onert-micro/luci-interpreter/pal/mcu/PALL2Pool2D.h
  onert-micro/luci-interpreter/src/kernels/L2Normalize.cpp
  onert-micro/luci-interpreter/src/kernels/L2Normalize.h
  onert-micro/luci-interpreter/src/kernels/L2Normalize.test.cpp
Labels: approval: 1

#11589 [onert] Add NNFW Python API
  docs/howto/how-to-use-nnfw-python-api.md
  infra/nnfw/cmake/CfgOptionFlags.cmake
  infra/nnfw/cmake/options/options_aarch64-android.cmake
  infra/nnfw/cmake/options/options_aarch64-linux.cmake
  infra/nnfw/cmake/options/options_armv7l-linux.cmake
  infra/nnfw/cmake/options/options_x86_64-linux.cmake
  infra/nnfw/cmake/packages/Pybind11Config.cmake
  runtime/onert/CMakeLists.txt
  runtime/onert/python/CMakeLists.txt
  runtime/onert/python/api/CMakeLists.txt
  runtime/onert/python/api/include/nnfw_api_wrapper.h
  runtime/onert/python/api/src/nnfw_api_wrapper.cc
  runtime/onert/python/api/src/nnfw_api_wrapper_pybind.cc
  runtime/onert/sample/minimal-python/README.md
  runtime/onert/sample/minimal-python/src/minimal.py
Labels: PR/ready for review, SSAFY

#11570 [onert-micro] Add cmsis-nn Pooling kernels
  onert-micro/luci-interpreter/pal/cmsisnn/KernelsToBuild.lst
  onert-micro/luci-interpreter/pal/cmsisnn/PALAveragePool2D.h
  onert-micro/luci-interpreter/pal/cmsisnn/PALMaxPool2D.h
  onert-micro/luci-interpreter/pal/common/PALMaxPool2DCommon.h
  onert-micro/luci-interpreter/pal/mcu/PALAveragePool2D.h
  onert-micro/luci-interpreter/pal/mcu/PALMaxPool2D.h
  onert-micro/luci-interpreter/src/kernels/AveragePool2D.cpp
  onert-micro/luci-interpreter/src/kernels/MaxPool2D.cpp
Labels: approval: 1

#11600 [onert-micro] Add cmsis-nn Softmax kernels
  onert-micro/luci-interpreter/pal/cmsisnn/PALSoftmax.h
  onert-micro/luci-interpreter/pal/common/PALSoftmaxCommon.h
  onert-micro/luci-interpreter/pal/common/Params.h
  onert-micro/luci-interpreter/pal/mcu/PALSoftmax.h
  onert-micro/luci-interpreter/src/kernels/Softmax.cpp
Labels: approval: 1

#11597 [infra/runtime] Update TRIXEngine check
  infra/nnfw/cmake/packages/TRIXEngineConfig.cmake
  infra/nnfw/cmake/packages/TRIXEngineConfigVersion.cmake
  runtime/onert/backend/trix/CMakeLists.txt
  runtime/onert/frontend/trix/CMakeLists.txt
  runtime/service/npud/backend/trix/CMakeLists.txt
Labels: PR/ready for review

#11591 [onert] Add Package of NNFW Python API
  infra/nnfw/python/README.md
  infra/nnfw/python/nnfwapi/__init__.py
  infra/nnfw/python/nnfwapi/libnnfw_api_pybind.py
  infra/nnfw/python/pack.sh
  infra/nnfw/python/setup.py
Labels: PR/ready for review, SSAFY

#11586 [onert-micro] Add float Sqrt kernel
  onert-micro/luci-interpreter/include/luci_interpreter/test_models/sqrt/FloatSqrtKernel.h
  onert-micro/luci-interpreter/include/luci_interpreter/test_models/sqrt/NegSqrtKernel.h
  onert-micro/luci-interpreter/include/luci_interpreter/test_models/sqrt/TestDataSqrtBase.h
  onert-micro/luci-interpreter/pal/cmsisnn/KernelsToBuild.lst
  onert-micro/luci-interpreter/pal/common/PALSqrt.h
  onert-micro/luci-interpreter/pal/mcu/KernelsToBuild.lst
  onert-micro/luci-interpreter/src/kernels/Sqrt.cpp
  onert-micro/luci-interpreter/src/kernels/Sqrt.h
  onert-micro/luci-interpreter/src/kernels/Sqrt.test.cpp
Labels: approval: 1

#11587 [onert-micro] Add float SquaredDifference kernel
  onert-micro/luci-interpreter/include/luci_interpreter/test_models/squared_difference/FloatSquaredDifferenceKernel.h
  onert-micro/luci-interpreter/include/luci_interpreter/test_models/squared_difference/NegSquaredDifferenceKernel.h
  onert-micro/luci-interpreter/include/luci_interpreter/test_models/squared_difference/TestDataSquaredDifferenceBase.h
  onert-micro/luci-interpreter/pal/cmsisnn/KernelsToBuild.lst
  onert-micro/luci-interpreter/pal/common/PALSquaredDifference.h
  onert-micro/luci-interpreter/pal/mcu/KernelsToBuild.lst
  onert-micro/luci-interpreter/src/kernels/SquaredDifference.cpp
  onert-micro/luci-interpreter/src/kernels/SquaredDifference.h
  onert-micro/luci-interpreter/src/kernels/SquaredDifference.test.cpp
Labels: approval: 1

#11601 [onert-micro] Add float SelectV2 kernels
  onert-micro/luci-interpreter/include/luci_interpreter/test_models/select_v2/FloatSelectV2Kernel.h
  onert-micro/luci-interpreter/include/luci_interpreter/test_models/select_v2/NegSelectV2Kernel.h
  onert-micro/luci-interpreter/include/luci_interpreter/test_models/select_v2/TestDataSelectV2Base.h
  onert-micro/luci-interpreter/pal/cmsisnn/KernelsToBuild.lst
  onert-micro/luci-interpreter/pal/common/PALSelectV2.h
  onert-micro/luci-interpreter/pal/mcu/KernelsToBuild.lst
  onert-micro/luci-interpreter/src/kernels/SelectV2.cpp
  onert-micro/luci-interpreter/src/kernels/SelectV2.test.cpp
Labels: approval: 1

#11602 [onert-micro] Add float Log kernels
  onert-micro/luci-interpreter/include/luci_interpreter/test_models/log/FloatLogKernel.h
  onert-micro/luci-interpreter/include/luci_interpreter/test_models/log/NegLogKernel.h
  onert-micro/luci-interpreter/include/luci_interpreter/test_models/log/TestDataLogBase.h
  onert-micro/luci-interpreter/pal/cmsisnn/KernelsToBuild.lst
  onert-micro/luci-interpreter/pal/common/PALLog.h
  onert-micro/luci-interpreter/pal/mcu/KernelsToBuild.lst
  onert-micro/luci-interpreter/src/kernels/Log.cpp
  onert-micro/luci-interpreter/src/kernels/Log.test.cpp
  onert-micro/luci-interpreter/src/loader/GraphLoader.cpp
Labels: approval: 1

#11616 [onert-micro] Introduce FloorDiv kernel
  onert-micro/luci-interpreter/include/luci_interpreter/test_models/floordiv/FloatFloorDivKernel.h
  onert-micro/luci-interpreter/include/luci_interpreter/test_models/floordiv/NegFloorDivKernel.h
  onert-micro/luci-interpreter/include/luci_interpreter/test_models/floordiv/TestDataFloorDivBase.h
  onert-micro/luci-interpreter/pal/common/PALFloorDivCommon.h
  onert-micro/luci-interpreter/pal/mcu/KernelsToBuild.lst
  onert-micro/luci-interpreter/pal/mcu/PALFloorDiv.h
  onert-micro/luci-interpreter/src/kernels/FloorDiv.cpp
  onert-micro/luci-interpreter/src/kernels/FloorDiv.h
  onert-micro/luci-interpreter/src/kernels/FloorDiv.test.cpp
Labels: approval: 1

#11617 [onert-micro] Introduce FloorMod kernel
  onert-micro/luci-interpreter/include/luci_interpreter/test_models/floormod/FloatFloorModKernel.h
  onert-micro/luci-interpreter/include/luci_interpreter/test_models/floormod/NegFloorModKernel.h
  onert-micro/luci-interpreter/include/luci_interpreter/test_models/floormod/TestDataFloorModBase.h
  onert-micro/luci-interpreter/pal/common/PALFloorModCommon.h
  onert-micro/luci-interpreter/pal/mcu/KernelsToBuild.lst
  onert-micro/luci-interpreter/pal/mcu/PALFloorMod.h
  onert-micro/luci-interpreter/src/kernels/FloorMod.cpp
  onert-micro/luci-interpreter/src/kernels/FloorMod.test.cpp
Labels: approval: 1

#11615 [onert-micro] Add float ZerosLike kernels
  onert-micro/luci-interpreter/include/luci_interpreter/test_models/zeros_like/FloatZerosLikeKernel.h
  onert-micro/luci-interpreter/include/luci_interpreter/test_models/zeros_like/NegZerosLikeKernel.h
  onert-micro/luci-interpreter/include/luci_interpreter/test_models/zeros_like/TestDataZerosLikeBase.h
  onert-micro/luci-interpreter/pal/cmsisnn/KernelsToBuild.lst
  onert-micro/luci-interpreter/pal/mcu/KernelsToBuild.lst
  onert-micro/luci-interpreter/src/kernels/ZerosLike.cpp
  onert-micro/luci-interpreter/src/kernels/ZerosLike.test.cpp
  onert-micro/luci-interpreter/src/loader/GraphLoader.cpp
Labels: approval: 1

#11618 [onert-micro] Add float Quantize kernels
  onert-micro/luci-interpreter/include/luci_interpreter/test_models/quantize/FloatQuantizeKernel.h
  onert-micro/luci-interpreter/include/luci_interpreter/test_models/quantize/NegQuantizeKernel.h
  onert-micro/luci-interpreter/include/luci_interpreter/test_models/quantize/TestDataQuantizeBase.h
  onert-micro/luci-interpreter/pal/cmsisnn/KernelsToBuild.lst
  onert-micro/luci-interpreter/pal/common/PALQuantize.h
  onert-micro/luci-interpreter/pal/common/Params.h
  onert-micro/luci-interpreter/pal/mcu/KernelsToBuild.lst
  onert-micro/luci-interpreter/src/kernels/Quantize.cpp
  onert-micro/luci-interpreter/src/kernels/Quantize.h
  onert-micro/luci-interpreter/src/kernels/Quantize.test.cpp
Labels: approval: 1

#11620 [onert-micro] Add float BatchToSpaceND kernels
  onert-micro/luci-interpreter/include/luci_interpreter/test_models/batch_to_space_nd/FloatBatchToSpaceNDKernel.h
  onert-micro/luci-interpreter/include/luci_interpreter/test_models/batch_to_space_nd/NegBatchToSpaceNDKernel.h
  onert-micro/luci-interpreter/include/luci_interpreter/test_models/batch_to_space_nd/TestDataBatchToSpaceNDBase.h
  onert-micro/luci-interpreter/pal/cmsisnn/KernelsToBuild.lst
  onert-micro/luci-interpreter/pal/common/PALBatchToSpaceND.h
  onert-micro/luci-interpreter/pal/mcu/KernelsToBuild.lst
  onert-micro/luci-interpreter/src/kernels/BatchToSpaceND.cpp
  onert-micro/luci-interpreter/src/kernels/BatchToSpaceND.h
  onert-micro/luci-interpreter/src/kernels/BatchToSpaceND.test.cpp
Labels: approval: 1

#11621 [onert-micro] Add float SpaceToBatchND kernels
  onert-micro/luci-interpreter/include/luci_interpreter/test_models/space_to_batch_nd/FloatSpaceToBatchNDKernel.h
  onert-micro/luci-interpreter/include/luci_interpreter/test_models/space_to_batch_nd/NegSpaceToBatchNDKernel.h
  onert-micro/luci-interpreter/include/luci_interpreter/test_models/space_to_batch_nd/TestDataSpaceToBatchNDBase.h
  onert-micro/luci-interpreter/pal/cmsisnn/KernelsToBuild.lst
  onert-micro/luci-interpreter/pal/common/PALSpaceToBatchND.h
  onert-micro/luci-interpreter/pal/mcu/KernelsToBuild.lst
  onert-micro/luci-interpreter/src/kernels/SpaceToBatchND.cpp
  onert-micro/luci-interpreter/src/kernels/SpaceToBatchND.h
  onert-micro/luci-interpreter/src/kernels/SpaceToBatchND.test.cpp
Labels: approval: 1

#11626 [onert-micro] Introduce Minimum kernel
  onert-micro/luci-interpreter/include/luci_interpreter/test_models/minimum/FloatMinimumKernel.h
  onert-micro/luci-interpreter/include/luci_interpreter/test_models/minimum/NegMinimumKernel.h
  onert-micro/luci-interpreter/include/luci_interpreter/test_models/minimum/TestDataMinimumBase.h
  onert-micro/luci-interpreter/pal/common/PALMinimumCommon.h
  onert-micro/luci-interpreter/pal/mcu/KernelsToBuild.lst
  onert-micro/luci-interpreter/pal/mcu/PALMinimum.h
  onert-micro/luci-interpreter/src/kernels/Minimum.cpp
  onert-micro/luci-interpreter/src/kernels/Minimum.h
  onert-micro/luci-interpreter/src/kernels/Minimum.test.cpp
Labels: approval: 1
