Repository Samsung/ONE, pull requests merged in 2023-11, with the labels that each got.

#11839 [one-cmds] Enable fuse_horizontal_fc_layers
  compiler/one-cmds/how-to-use-one-commands.txt
  compiler/one-cmds/onelib/constant.py
Labels: approval: 2

#11837 [luci-pass-value-test] Add fuse_horizontal_fc_layers test
  compiler/luci-pass-value-test/test.lst
Labels: approval: 2

#11838 [circle2circle-dredd-recipe-test] Add fuse_horizontal_fc_layers test
  compiler/circle2circle-dredd-recipe-test/test.lst
Labels: approval: 2

#11845 [rawdata2hdf5] Support multi-input list
  compiler/rawdata2hdf5/rawdata2hdf5
Labels: area/quant

#11832 [record-minmax] Support multi-input list format
  compiler/record-minmax/src/RecordMinMax.cpp
Labels: area/quant

#11846 [one-cmds] Add multi-input quantization dataset test
  compiler/one-cmds/tests/one-quantize_023.test
  compiler/one-cmds/tests/one-quantize_neg_024.test
  compiler/one-cmds/tests/prepare_test_materials.sh
  compiler/one-cmds/tests/rawdata2hdf5_002.test
Labels: area/quant

#11785 [tflchef] Use extype and custom_code type for custom operators
  compiler/tflchef/core/src/ModelChef.cpp
  compiler/tflchef/tests/custom_erf/test.recipe
Labels: PR/ready for review

#11816 [infra/gbs] Enable training feature
  infra/nnfw/cmake/options/options_aarch64-tizen.cmake
  infra/nnfw/cmake/options/options_armv7hl-tizen.cmake
  infra/nnfw/cmake/options/options_armv7l-tizen.cmake
  infra/nnfw/cmake/options/options_i686-tizen.cmake
  infra/nnfw/cmake/options/options_x86_64-tizen.cmake
Labels: PR/ready for review

#11841 [onert-micro] Add basic mbed-os example app
  onert-micro/examples/speech_recognition/DISCO_F746/mbed-os/CMakeLists.txt
  onert-micro/examples/speech_recognition/DISCO_F746/mbed-os/main.cpp
  onert-micro/examples/speech_recognition/DISCO_F746/mbed-os/mbed-sources.cmake
  onert-micro/examples/speech_recognition/DISCO_F746/mbed-os/mbed_config.h
Labels: approval: 1

#11852 [circlechef] Use extype and custom_code for custom operators
  compiler/circlechef/core/src/ModelChef.cpp
Labels: PR/ready for review

#11854 [tflchef] Refactor check_custom_op_value in OpUtils
  compiler/tflchef/core/src/OpUtils.cpp
Labels: PR/ready for review

#11863 [one-cmds] Add fuse_horizontal_fc_layers to O1
  compiler/one-cmds/onelib/constant.py
Labels: approval: 1

#11853 [one-cmds] Add save_min_max option to one-quantize
  compiler/one-cmds/one-quantize
  compiler/one-cmds/tests/one-quantize_024.test
Labels: area/quant

#11864 [res] Remove extype and Change type value to Custom for custom operators
  res/TensorFlowLiteRecipes/All_000/test.recipe
  res/TensorFlowLiteRecipes/BatchMatMulV2_000/test.recipe
  res/TensorFlowLiteRecipes/BatchMatMulV2_001/test.recipe
  res/TensorFlowLiteRecipes/BroadcastTo_000/test.recipe
  res/TensorFlowLiteRecipes/MatMul_000/test.recipe
  res/TensorFlowLiteRecipes/MatrixBandPart_000/test.recipe
  res/TensorFlowLiteRecipes/MaxPoolWithArgmax_000/test.recipe
  res/TensorFlowLiteRecipes/MaxPoolWithArgmax_001/test.recipe
  res/TensorFlowLiteRecipes/MaxPoolWithArgmax_002/test.recipe
  res/TensorFlowLiteRecipes/Net_BroadcastTo_AddV2_000/test.recipe
  res/TensorFlowLiteRecipes/Net_BroadcastTo_AddV2_001/test.recipe
  res/TensorFlowLiteRecipes/Net_FC_Gelu_FC_000/test.recipe
  res/TensorFlowLiteRecipes/Net_Gather_SparseToDense_AddV2_000/test.recipe
  res/TensorFlowLiteRecipes/Net_Gelu_000/test.recipe
  res/TensorFlowLiteRecipes/Net_Gelu_001/test.recipe
Labels: PR/ready for review

#11828 [onert] Change SoftMaxGrad test suite name
  compute/cker/src/train/SoftMax.test.cc
Labels: approval: 1

#11867 [circlechef] Remove extype used for custom op
  compiler/circlechef/core/src/ModelChef.cpp
  compiler/circlechef/proto/circlechef.proto
Labels: PR/ready for review

#11868 [tflchef] Remove extype used for custom op
  compiler/tflchef/core/src/ModelChef.cpp
  compiler/tflchef/core/src/OpUtils.cpp
  compiler/tflchef/proto/tflchef.proto
  compiler/tflchef/tests/custom_erf/test.recipe
Labels: PR/ready for review

#11879 [tflite2circle] Support BroadcastTo
  compiler/tflite2circle/src/BuildBuiltinOptions.h
  compiler/tflite2circle/src/BuildBuiltinOptions/BroadcastToOptions.cpp
  compiler/tflite2circle/src/BuildBuiltinOptions/BroadcastToOptions.h
  compiler/tflite2circle/src/TFLBuiltinOptions.lst
Labels: PR/ready for review

#11886 [common-artifacts] Exclude Broadcast_To
  compiler/common-artifacts/exclude.lst
Labels: PR/ready for review

#11913 [luci] Improve multi-input mpq pattern
  compiler/luci/pass/src/QuantizeWithMinMaxPass.cpp
Labels: area/quant

#11896 [common-artifacts] Exclude BroadcastTo operation
  compiler/common-artifacts/exclude.lst
Labels: PR/ready for review

#11914 [res] Add Quant_Mul_002
  res/TensorFlowLiteRecipes/Quant_Mul_002/test.qconf.json
  res/TensorFlowLiteRecipes/Quant_Mul_002/test.recipe
  res/TensorFlowLiteRecipes/Quant_Mul_002/test.rule
Labels: area/quant

#11911 [tf_dataset_converter] Fix wrong help in argparser
  tools/generate_datafile/tf_dataset_converter/argparser.py
Labels: approval: 1

#11884 [onert] Rename derivative to back prop
  runtime/onert/backend/train/BackendContext.cc
  runtime/onert/backend/train/KernelGenerator.cc
  runtime/onert/backend/train/Tensor.h
  runtime/onert/backend/train/TensorBuilder.cc
  runtime/onert/backend/train/TensorManager.cc
  runtime/onert/backend/train/TensorManager.h
  runtime/onert/backend/train/TensorRegistry.h
  runtime/onert/backend/train/ops/ElementwiseActivationLayer.cc
  runtime/onert/backend/train/ops/ElementwiseActivationLayer.h
  runtime/onert/backend/train/ops/FullyConnectedLayer.cc
  runtime/onert/backend/train/ops/FullyConnectedLayer.h
  runtime/onert/backend/train/ops/LossLayer.cc
  runtime/onert/backend/train/ops/LossLayer.h
  runtime/onert/backend/train/ops/PoolLayer.cc
  runtime/onert/backend/train/ops/PoolLayer.h
  runtime/onert/backend/train/ops/ReshapeLayer.cc
  runtime/onert/backend/train/ops/ReshapeLayer.h
  runtime/onert/backend/train/ops/SoftMaxLayer.cc
  runtime/onert/backend/train/ops/SoftMaxLayer.h
  runtime/onert/core/include/backend/train/ITensorRegistry.h
  runtime/onert/core/include/ir/train/TrainableGraph.h
  runtime/onert/core/src/backend/builtin/train/KernelGenerator.cc
  runtime/onert/core/src/backend/builtin/train/KernelGenerator.h
  runtime/onert/core/src/backend/builtin/train/Tensor.h
  runtime/onert/core/src/backend/builtin/train/TensorRegistry.h
  runtime/onert/core/src/backend/builtin/train/kernel/PermuteLayer.cc
  runtime/onert/core/src/backend/builtin/train/kernel/PermuteLayer.h
  runtime/onert/core/src/compiler/ExecutorFactory.cc
  runtime/onert/core/src/compiler/train/StaticBackPropShapeInferer.cc
  runtime/onert/core/src/compiler/train/StaticBackPropShapeInferer.h
  runtime/onert/core/src/compiler/train/TensorRegistries.h
  runtime/onert/core/src/compiler/train/TrainingCompiler.cc
  runtime/onert/core/src/dumper/dot/DotDumper.cc
  runtime/onert/core/src/ir/train/TrainableGraph.cc
Labels: PR/ready for review, trivial

#11936 [circle-quantizer-dredd-test] Add Quant_Mul_002 test
  compiler/circle-quantizer-dredd-recipe-test/test.lst
Labels: area/quant

#11876 [onert-micro] Add build example application target
  onert-micro/CMakeLists.txt
  onert-micro/examples/speech_recognition/DISCO_F746/mbed-os/CMakeLists.txt
Labels: approval: 1

#11948 [CI] Remove docker_build_nncc.sh
  infra/scripts/docker_build_nncc.sh
Labels: PR/ready for review, trivial

#11979 [circle-mpqsolver] Sync options with one-quantize
  compiler/circle-mpqsolver/src/CircleMPQSolver.cpp
  compiler/circle-mpqsolver/src/MPQSolver.cpp
  compiler/circle-mpqsolver/src/MPQSolver.h
  compiler/circle-mpqsolver/src/core/Quantizer.cpp
  compiler/circle-mpqsolver/src/core/Quantizer.h
  compiler/circle-mpqsolver/src/pattern/PatternSolver.cpp
  compiler/circle-mpqsolver/src/pattern/PatternSolver.h
  compiler/circle-mpqsolver/src/pattern/PatternSolver.test.cpp
Labels: area/quant

#11976 [luci/pass] Introduce RemoveUnnecessaryTransposeNetPass
  compiler/luci/pass/include/luci/CircleOptimizer.h
  compiler/luci/pass/include/luci/Pass/RemoveUnnecessaryTransposeNetPass.h
  compiler/luci/pass/src/CircleOptimizer.cpp
  compiler/luci/pass/src/RemoveUnnecessaryTransposeNetPass.cpp
  compiler/luci/pass/src/RemoveUnnecessaryTransposeNetPass.test.cpp
Labels: approval: 2

#11978 [res] Add TensorFlowLiteRecipes for TransposeReshapeTranspose pattern
  res/TensorFlowLiteRecipes/Net_Trans_Reshape_Trans_000/test.recipe
  res/TensorFlowLiteRecipes/Net_Trans_Reshape_Trans_000/test.rule
Labels: approval: 2

#11984 [onert] Allow uint8 BatchMatMul
  runtime/onert/core/src/ir/OperationValidator.cc
Labels: PR/ready for review

#11987 [onert] Fix typo Tanh error message
  runtime/onert/backend/cpu/ops/ElementwiseActivationLayer.cc
Labels: PR/ready for review, trivial

#11981 [one-cmds] Add options to circle-mpqsolver
  compiler/one-cmds/one-quantize
Labels: area/quant

#11898 [cker] Rename derivative to grad or incoming
  compute/cker/include/cker/train/operation/MaxPool.h
  compute/cker/src/train/MaxPool.test.cc
Labels: PR/ready for review, trivial

#11988 [cker] Bring Conv2D kernels from tensorflow v2.12.1
  compute/cker/include/cker/eigen/eigen_backward_spatial_convolutions.h
  compute/cker/include/cker/train/operation/Conv.h
  compute/cker/src/train/Conv.test.cc
Labels: PR/ready for review

#11989 [onert] Adjust whether to cache cpu conv weights
  runtime/onert/backend/cpu/KernelGenerator.cc
  runtime/onert/backend/cpu/ops/ConvolutionLayer.cc
  runtime/onert/backend/cpu/ops/ConvolutionLayer.h
  runtime/onert/backend/train/ops/ConvolutionLayer.cc
Labels: PR/ready for review

#11982 [circle2circle] Add remove_unnecessary_transpose option
  compiler/circle2circle/src/Circle2Circle.cpp
Labels: approval: 2

#11877 [luci] Introduce CircleBroadcastTo IR
  compiler/luci/lang/include/luci/IR/CircleNodes.h
  compiler/luci/lang/include/luci/IR/CircleNodes.lst
  compiler/luci/lang/include/luci/IR/Nodes/CircleBroadcastTo.h
  compiler/luci/lang/src/Nodes/CircleBroadcastTo.test.cpp
Labels: PR/ready for review

#11932 [tflchef] Support BroadcastTo
  compiler/tflchef/core/src/Op/BroadcastTo.cpp
  compiler/tflchef/core/src/Op/BroadcastTo.h
  compiler/tflchef/core/src/OpChef.def
  compiler/tflchef/core/src/OpChefs.h
  compiler/tflchef/proto/tflchef.proto
  compiler/tflchef/tflite/src/Op/BroadcastTo.cpp
  compiler/tflchef/tflite/src/Op/include/BroadcastTo.h
  compiler/tflchef/tflite/src/TFliteOpChefs.h
  compiler/tflchef/tflite/src/TFliteOpRegistry.h
Labels: PR/ready for review

#12000 [luci-pass-value-test] Add remove_unnecessary_transpose test
  compiler/luci-pass-value-test/test.lst
Labels: approval: 2

#11999 [circle2circle-dredd-recipe-test] Add remove_unnecessary_transpose test
  compiler/circle2circle-dredd-recipe-test/test.lst
Labels: approval: 2

#12003 [infra] Remove nnfw docker-run command
  infra/command/docker-shell
  infra/nnfw/command/docker-run
  infra/nnfw/command/docker-run-user
  infra/nnfw/config/docker.configuration
Labels: PR/ready for review

#12015 [common-artifacts] Exclude BroadcastTo_002
  compiler/common-artifacts/exclude.lst
Labels: PR/ready for review

#11944 [infra/command] Update docker-run and config
  infra/command/docker-run
  infra/config/docker.configuration
Labels: PR/ready for review

#12021 [onert] Fix wrong doxygen comment in TrainingCompiler
  runtime/onert/core/src/compiler/train/TrainingCompiler.h
Labels: approval: 1

#12023 [luci/import] Support BroadcastTo operation
  compiler/luci/import/include/luci/Import/Nodes.h
  compiler/luci/import/include/luci/Import/Nodes/CircleBroadcastTo.h
  compiler/luci/import/src/GraphBuilderRegistry.cpp
  compiler/luci/import/src/Nodes/CircleBroadcastTo.cpp
Labels: PR/ready for review

#12022 [onert/train] Fix reference after move
  runtime/onert/core/src/exec/train/TrainableExecutor.cc
Labels: PR/ready for review

#12026 [luci/export] Support BroadcastTo
  compiler/luci/export/src/CircleBuiltinTypesExtractor.h
  compiler/luci/export/src/CircleOps.lst
Labels: PR/ready for review

#12025 [luci/logex] Support BroadcastTo
  compiler/luci/logex/src/CircleNodeSummaryBuilder.cpp
  compiler/luci/logex/src/CircleNodeSummaryBuilders.cpp
  compiler/luci/logex/src/CircleNodeSummaryBuilders.h
Labels: PR/ready for review

#11990 [onert] Apply Conv2D kernel for training
  runtime/onert/backend/train/KernelGenerator.cc
  runtime/onert/backend/train/ops/ConvolutionLayer.cc
  runtime/onert/backend/train/ops/ConvolutionLayer.h
  runtime/onert/backend/train/ops/OperationUtils.h
Labels: PR/ready for review

#12017 [one-cmds] Enable remove_unnecessary_transpose
  compiler/one-cmds/how-to-use-one-commands.txt
  compiler/one-cmds/onelib/constant.py
Labels: approval: 2

#12037 [infra] Remove nncc docker-run command
  infra/nncc/command/docker-nncc
  infra/nncc/command/docker-run
  infra/nncc/command/docker-shell
  infra/nncc/config/docker.configuration
  infra/scripts/docker_collect_nnpkg_resources.sh
Labels: PR/ready for review

#11996 [onert-micro] Introduce stm32f746 example app
  onert-micro/examples/speech_recognition/DISCO_F746/mbed-os/main.cpp
  onert-micro/examples/speech_recognition/DISCO_F746/mbed-os/speech_recognition_float.circle.h
  onert-micro/examples/speech_recognition/DISCO_F746/mbed-os/test_data.h
Labels: approval: 1

#11957 [onert-micro] Introduce If kernel
  onert-micro/luci-interpreter/include/luci_interpreter/test_models/if/IfKernel.h
  onert-micro/luci-interpreter/include/luci_interpreter/test_models/if/NegIfKernel.h
  onert-micro/luci-interpreter/src/kernels/If.cpp
  onert-micro/luci-interpreter/src/kernels/If.h
  onert-micro/luci-interpreter/src/kernels/If.test.cpp
Labels: approval: 1

#12035 [onert] Remove index copy
  runtime/onert/core/src/compiler/ExecutorFactory.cc
  runtime/onert/core/src/compiler/train/StaticBackPropShapeInferer.cc
Labels: PR/ready for review

#12033 [tools/onert_train] Remove data_length parameter from onert_train tool
  tests/tools/onert_train/src/args.cc
  tests/tools/onert_train/src/args.h
  tests/tools/onert_train/src/onert_train.cc
  tests/tools/onert_train/src/rawdataloader.cc
  tests/tools/onert_train/src/rawdataloader.h
  tests/tools/onert_train/test/rawdataloader.test.cc
Labels: PR/ready for review

#12036 [cker] Set struct PoolParams initial value
  compute/cker/include/cker/Types.h
Labels: PR/ready for review

#12014 [onert] Introduce CategoricalCrossEntropy kernel
  compute/cker/include/cker/train/operation/Loss.h
  compute/cker/src/train/Loss.test.cc
Labels: PR/ready for review

#11992 [infra] Revise nnpackage collection script
  infra/scripts/compiler_modules.sh
  infra/scripts/configure_collect_nnpkgs.sh
  infra/scripts/docker_collect_nnpkg_resources.sh
Labels: PR/ready for review

#12024 [luci/service] Support BroadcastTo
  compiler/luci/service/src/CircleCloneNode.h
  compiler/luci/service/src/CircleShapeInferenceRule.cpp
  compiler/luci/service/src/CircleTypeInferenceRule.cpp
  compiler/luci/service/src/Nodes/CircleBroadcastTo.cpp
  compiler/luci/service/src/Nodes/CircleBroadcastTo.test.cpp
Labels: PR/ready for review

#12048 [luci/partition] Support BroadcastTo
  compiler/luci/partition/include/luci/ConnectNode.h
  compiler/luci/partition/src/Nodes/CircleBroadcastTo.cpp
  compiler/luci/partition/src/Nodes/CircleBroadcastTo.test.cpp
Labels: PR/ready for review

#12012 Add BroadcastTo_001
  res/TensorFlowLiteRecipes/BroadcastTo_001/test.recipe
  res/TensorFlowLiteRecipes/BroadcastTo_001/test.reverse
Labels: PR/ready for review

#12056 [luci/tests] Enable BroadcastTo operation
  compiler/luci/tests/test.lst
Labels: PR/ready for review

#12064 [onert] Change OperationDumper's FullyConnected
  runtime/onert/core/src/ir/OperationDumper.cc
Labels: PR/ready for review

#12065 [infra] Remove unused script
  infra/scripts/docker_collect_nnpkg_resources.sh
Labels: PR/ready for review, trivial

#12044 [onert-micro] Refactor Minimum kernel
  onert-micro/luci-interpreter/pal/common/Broadcast.h
  onert-micro/luci-interpreter/pal/common/PALMinimumCommon.h
  onert-micro/luci-interpreter/src/kernels/Minimum.cpp
Labels: approval: 1

#12076 [infra] Fix HDF5Config.cmake
  infra/nnfw/cmake/packages/HDF5Config.cmake
Labels: PR/ready for review

#12077 [luci/pass] Enhance RemoveUnnecessaryTransposeNetPass test verification
  compiler/luci/pass/src/RemoveUnnecessaryTransposeNetPass.test.cpp
Labels: approval: 2

#12075 [infra] Add toolchain file for aarch64 cross compile
  infra/nncc/cmake/buildtool/cross/toolchain_aarch64-linux.cmake
Labels: PR/ready for review

#12084 [onert-micro] Support more dynamic shapes cases
  onert-micro/luci-interpreter/src/core/RuntimeGraph.cpp
  onert-micro/luci-interpreter/src/kernels/Add.cpp
  onert-micro/luci-interpreter/src/kernels/BinaryOpCommon.h
  onert-micro/luci-interpreter/src/kernels/Div.cpp
  onert-micro/luci-interpreter/src/kernels/FullyConnected.cpp
  onert-micro/luci-interpreter/src/kernels/Mul.cpp
  onert-micro/luci-interpreter/src/kernels/Reshape.cpp
  onert-micro/luci-interpreter/src/kernels/Sub.cpp
Labels: approval: 1

#12080 [tools] Remove symbolic link creation
  tools/cross/install_rootfs.sh
Labels: PR/ready for review

#11776 [onert] Support ODC cross build
  Makefile.template
  infra/buildtool/CMakeLists.txt
  runtime/onert/odc/CMakeLists.txt
Labels: PR/ready for review

#12103 [infra] Set external mirror server login
  infra/buildtool/CMakeLists.txt
Labels: PR/ready for review

#12089 [one-cmds] Improve help message of one-quantize granularity
  compiler/one-cmds/one-quantize
Labels: PR/ready for review, approval: 1

#12104 [circle-mpqsolver] Improve help message of circle-mpqsolver granularity
  compiler/circle-mpqsolver/src/CircleMPQSolver.cpp
Labels: approval: 1

#12086 [onert-micro] Support keep_dims in FullyConnected
  onert-micro/luci-interpreter/pal/cmsisnn/PALFullyConnected.h
  onert-micro/luci-interpreter/pal/common/PALFullyConnectedCommon.h
  onert-micro/luci-interpreter/pal/common/PALUnidirectionalSequenceLSTMCommon.h
  onert-micro/luci-interpreter/pal/mcu/PALFullyConnected.h
  onert-micro/luci-interpreter/src/kernels/FullyConnected.cpp
Labels: approval: 1

#12082 [infra] Revise format command
  infra/command/format
Labels: PR/ready for review

#12115 [circle-mpqsolver] Set proper int16 granularity
  compiler/circle-mpqsolver/src/core/Quantizer.cpp
Labels: area/quant

#12058 [luci-interpreter] Support BroadcastTo
  compiler/luci-interpreter/pal/linux/KernelsToBuild.lst
  compiler/luci-interpreter/pal/linux/PALBroadcastTo.h
  compiler/luci-interpreter/pal/linux/pal.cmake
  compiler/luci-interpreter/src/kernels/BroadcastTo.cpp
  compiler/luci-interpreter/src/kernels/BroadcastTo.h
  compiler/luci-interpreter/src/kernels/BroadcastTo.test.cpp
  compiler/luci-interpreter/src/loader/nodes/BroadcastTo.cpp
Labels: PR/ready for review

#12131 [common-artifacts] Remove BroadcastTo operation in exclude.lst
  compiler/common-artifacts/exclude.lst
Labels: PR/ready for review

#12106 [tools/onert_train] Add loss_reduction_type option
  tests/tools/onert_train/src/args.cc
  tests/tools/onert_train/src/args.h
  tests/tools/onert_train/src/onert_train.cc
Labels: PR/ready for review

#12137 [cker] Introduce FloorMod kernels
  compute/cker/include/cker/operation/FloorMod.h
  compute/cker/src/FloorMod.test.cc
Labels: PR/ready for review

#12139 [onert] Introduce FloorMod operator
  runtime/onert/api/src/OpMap.lst
  runtime/onert/core/include/ir/operation/ElementwiseBinary.h
  runtime/onert/core/src/ir/operation/ElementwiseBinary.cc
  runtime/onert/frontend/base_loader/include/base_loader.h
Labels: PR/ready for review

#12142 [common-artifacts] Enable optimization test for BroadcastTo op
  compiler/common-artifacts/exclude.lst
Labels: PR/ready for review

#12135 [onert] Apply reduction type to Loss
  compute/cker/include/cker/train/operation/Loss.h
  compute/cker/src/train/Loss.test.cc
  runtime/onert/core/src/compiler/ExecutorFactory.cc
  runtime/onert/core/src/compiler/StaticShapeInferer.cc
  runtime/onert/core/src/compiler/train/pass/LossInsertionPass.cc
  runtime/onert/core/src/exec/train/TrainableExecutor.cc
  runtime/onert/core/src/exec/train/TrainableExecutor.h
Labels: PR/ready for review
