Repository Samsung/ONE, pull requests merged in 2024-04, with the labels that each got.

#12819 [circle-quantizer] Add quantize_onnx_fq_model option
  compiler/circle-quantizer/src/CircleQuantizer.cpp
Labels: area/quant

#12742 [onert-micro] Add Softmax kernel
  onert-micro/onert-micro/include/pal/common/PALSoftmaxCommon.h
  onert-micro/onert-micro/include/pal/mcu/PALSoftmax.h
  onert-micro/onert-micro/include/test_models/softmax/FloatSoftmaxKernel.h
  onert-micro/onert-micro/include/test_models/softmax/NegSoftmaxKernel.h
  onert-micro/onert-micro/include/test_models/softmax/TestDataSoftmaxBase.h
  onert-micro/onert-micro/src/execute/kernels/Softmax.cpp
  onert-micro/onert-micro/src/execute/kernels/tests/Softmax.test.cpp
  onert-micro/onert-micro/src/import/kernels/Softmax.cpp
Labels: approval: 2

#12822 [luci] Fix quantized_dimension during Requantization
  compiler/luci/pass/src/RequantizePass.cpp
Labels: area/quant

#12825 [luci] Enable INT4 weight quantization in circle-quantizer
  compiler/luci/pass/src/CircleQuantizer.cpp
Labels: area/quant

#12835 [circle-opselector] Check if given operators include If or While
  compiler/circle-opselector/driver/Driver.cpp
  compiler/circle-opselector/src/OpSelector.cpp
Labels: PR/ready for review

#12833 [infra] Update dockerfile
  infra/docker/bionic/Dockerfile
  infra/docker/focal/Dockerfile
  infra/docker/jammy/Dockerfile
Labels: PR/ready for review

#12846 [luci] Remove unused code.
  compiler/luci/pass/src/QuantizeOnnxDequantizeLinearPass.cpp
Labels: area/quant

#12848 [infra] Introduce nncc install command
  infra/nncc/command/install
Labels: PR/ready for review, approval: 2

#12855 [luci] Copy qparam to circle output
  compiler/luci/pass/src/CopyQuantParamPass.cpp
Labels: area/quant

#12856 [onert] Change trix backend version
  runtime/onert/backend/trix/DevContext.cc
Labels: PR/ready for review

#12860 [onert] Handle batch input shape inference on Reshape operator
  runtime/onert/core/include/util/ShapeInference.h
  runtime/onert/core/src/compiler/StaticShapeInferer.cc
  runtime/onert/core/src/exec/DynamicShapeInferer.cc
  runtime/onert/core/src/util/ShapeInference.cc
Labels: PR/ready for review

#12861 [onert] Introduce Pool2D dynamic shape inference
  runtime/onert/core/include/exec/DynamicShapeInferer.h
  runtime/onert/core/src/exec/DynamicShapeInferer.cc
Labels: PR/ready for review

#12862 [nnpackage] Update circle schema
  nnpackage/schema/circle_schema.fbs
Labels: PR/ready for review

#12863 [onert] Update circle schema generated file
  runtime/libs/circle-schema/include/circle_schema_generated.h
Labels: PR/ready for review

#12870 [luci] Extend QuantizeOnnxDequantizeLinearPass
  compiler/luci/pass/src/QuantizeOnnxDequantizeLinearPass.cpp
  compiler/luci/pass/src/QuantizeOnnxDequantizeLinearPass.test.cpp
Labels: area/quant

#12871 [luci] Support Squeeze in QuantizeWithPredecessorPass
  compiler/luci/pass/src/QuantizeWithPredecessorPass.cpp
  compiler/luci/pass/src/QuantizeWithPredecessorPass.test.cpp
Labels: area/quant

#12875 [luci] Insert Quantize Op to quantize mixed-precision onnx
  compiler/luci/pass/src/InsertQuantizeOpOnDTypeMismatch.cpp
  compiler/luci/pass/src/InsertQuantizeOpOnDTypeMismatch.h
  compiler/luci/pass/src/InsertQuantizeOpOnDTypeMismatch.test.cpp
  compiler/luci/pass/src/QuantizeOnnxFakeQuantModelPass.cpp
Labels: area/quant

#12876 [onert] Update RPATH option
  infra/nnfw/CMakeLists.txt
  runtime/onert/core/CMakeLists.txt
  runtime/onert/odc/CMakeLists.txt
Labels: PR/ready for review

#12867 [onert] Update I/O info handling
  runtime/onert/api/nnapi/wrapper/ANeuralNetworksExecution.cc
  runtime/onert/core/include/exec/Execution.h
  runtime/onert/core/include/exec/IODescription.h
  runtime/onert/core/include/ir/OperandInfo.h
  runtime/onert/core/src/exec/Execution.cc
  runtime/onert/core/src/exec/Execution.test.cc
  runtime/onert/core/src/exec/ExecutorBase.cc
Labels: PR/ready for review

#12881 [onert] Remove outdated TODO comment
  runtime/onert/core/src/exec/Execution.cc
Labels: PR/ready for review

#12874 [onert] Change memory planners to class template
  runtime/onert/core/include/backend/basic/IMemoryPlanner.h
  runtime/onert/core/include/backend/basic/MemoryManager.h
  runtime/onert/core/src/backend/basic/MemoryManager.cc
  runtime/onert/core/src/backend/basic/MemoryPlanner.cc
  runtime/onert/core/src/backend/basic/MemoryPlanner.h
  runtime/onert/core/src/backend/basic/MemoryPlanner.test.cc
  runtime/onert/core/src/backend/basic/MemoryPlannerFactory.cc
  runtime/onert/core/src/backend/basic/MemoryPlannerFactory.h
Labels: PR/ready for review

#12877 [onert] Introduce DisposableTensorIndex
  runtime/onert/backend/train/DisposableTensorIndex.h
Labels: PR/ready for review

#12885 [one-cmds] Support inline comment in the cfg file
  compiler/one-cmds/one-build
  compiler/one-cmds/onecc
  compiler/one-cmds/onelib/CfgRunner.py
  compiler/one-cmds/onelib/utils.py
Labels: PR/ready for review

#12878 [onert] Introduce BackPropAccumulator
  runtime/onert/backend/train/ops/BackPropAccumulator.cc
  runtime/onert/backend/train/ops/BackPropAccumulator.h
Labels: PR/ready for review

#12887 [infra] Update gio-unix-2.0 header directory finding
  infra/nnfw/cmake/packages/Giounix2.0Config.cmake
Labels: PR/ready for review

#12889 [one-cmds] Add test that checks if writing comments are enabled
  compiler/one-cmds/tests/onecc_059.cfg
  compiler/one-cmds/tests/onecc_059.test
Labels: PR/ready for review

#12895 [onert] Initialize param in BaseLoader
  runtime/onert/core/src/loader/BaseLoader.h
Labels: PR/ready for review

#12891 [infra/gbs] Change gbs.conf url to reference
  infra/nnfw/config/gbs.conf
Labels: PR/ready for review

#12890 [onert] Remove apply_tensorinfo
  runtime/onert/api/nnfw/include/nnfw.h
  runtime/onert/api/nnfw/src/nnfw_api.cc
  runtime/onert/api/nnfw/src/nnfw_api_internal.cc
  runtime/onert/api/nnfw/src/nnfw_api_internal.h
Labels: PR/ready for review

#12894 [onert] Remove copy warning in ANeuralNetworksExecution
  runtime/onert/api/nnapi/wrapper/ANeuralNetworksExecution.cc
Labels: PR/ready for review

#12896 [onert] Fix hash value size of DisposableTensorIndex
  runtime/onert/backend/train/DisposableTensorIndex.h
Labels: PR/ready for review

#12906 [infra] Disable onert luci build
  Makefile.template
  packaging/nnfw.spec
Labels: PR/ready for review

#12907 [enco] Use FlatBuffers 23.5.26
  compiler/enco/frontend/tflite/CMakeLists.txt
Labels: PR/ready for review

#12909 [exo] Use FlatBuffer 23.5.26
  compiler/exo/CMakeLists.txt
Labels: PR/ready for review

#12910 [mio-circle08] Use FlatBuffer 23.5.26
  compiler/mio-circle08/CMakeLists.txt
Labels: PR/ready for review

#12911 [mio-tflite280] Use FlatBuffer 23.5.26
  compiler/mio-tflite280/CMakeLists.txt
Labels: PR/ready for review

#12912 [mir] Use FlatBuffer 23.5.26
  compiler/mir/src/mir_tflite_importer/CMakeLists.txt
Labels: PR/ready for review

#12913 [pics] Use FlatBuffer 23.5.26
  compiler/pics/CMakeLists.txt
Labels: PR/ready for review

#12915 [mio-tflite2121] Use FlatBuffer 23.5.26
  compiler/mio-tflite2121/CMakeLists.txt
Labels: PR/ready for review

#12919 [mio-tflite260] Use FlatBuffer 23.5.26
  compiler/mio-tflite260/CMakeLists.txt
Labels: PR/ready for review

#12908 [luci] Use FlatBuffers 23.5.26
  compiler/luci/pass/CMakeLists.txt
Labels: PR/ready for review

#12920 [mio-tflite] Use FlatBuffer 23.5.26
  compiler/mio-tflite/CMakeLists.txt
Labels: PR/ready for review

#12921 [mio-circle07] Use FlatBuffer 23.5.26
  compiler/mio-circle07/CMakeLists.txt
Labels: PR/ready for review

#12922 [mio-circle06] Use FlatBuffer 23.5.26
  compiler/mio-circle06/CMakeLists.txt
Labels: PR/ready for review

#12923 [mio-circle05] Use FlatBuffer 23.5.26
  compiler/mio-circle05/CMakeLists.txt
Labels: PR/ready for review

#12924 [mio-circle04] Use FlatBuffer 23.5.26
  compiler/mio-circle04/CMakeLists.txt
Labels: PR/ready for review

#12925 [mio-circle] Use FlatBuffer 23.5.26
  compiler/mio-circle/CMakeLists.txt
Labels: PR/ready for review

#12931 [onert] Introduce DisposableBackPropTensor into TensorRegistry
  runtime/onert/backend/train/TensorRegistry.h
Labels: PR/ready for review

#12929 [onert] Apply more strict shape validation check
  runtime/onert/core/src/compiler/ShapeValidator.cc
Labels: PR/ready for review

#12928 [onert] Introduce BackPropInitializer
  runtime/onert/backend/train/ops/BackPropInitializer.cc
  runtime/onert/backend/train/ops/BackPropInitializer.h
Labels: PR/ready for review

#12932 [onert] Revert applying template to memory planners in core backend
  runtime/onert/core/src/backend/basic/MemoryManager.cc
  runtime/onert/core/src/backend/basic/MemoryPlanner.cc
  runtime/onert/core/src/backend/basic/MemoryPlanner.h
  runtime/onert/core/src/backend/basic/MemoryPlanner.test.cc
  runtime/onert/core/src/backend/basic/MemoryPlannerFactory.cc
  runtime/onert/core/src/backend/basic/MemoryPlannerFactory.h
Labels: PR/ready for review

#12937 [debian] Introduce whitelist env option to the su command
  infra/debian/compiler/postinst
Labels: PR/ready for review

#12930 [onert] Introduce memory planners into train backend
  runtime/onert/backend/train/MemoryPlanner.cc
  runtime/onert/backend/train/MemoryPlanner.h
  runtime/onert/backend/train/MemoryPlannerFactory.cc
  runtime/onert/backend/train/MemoryPlannerFactory.h
Labels: PR/ready for review, area/onert
