Repository Samsung/ONE, pull requests merged in 2024-01, with the labels that each got.

#12389 [onert/api] Enhance nnfw_train_set_traininfo description
  runtime/onert/api/include/nnfw_experimental.h
Labels: PR/ready for review

#12385 [onert] Implement DepthwiseConv2D shape inferer
  runtime/onert/core/include/compiler/StaticShapeInferer.h
  runtime/onert/core/src/compiler/StaticShapeInferer.cc
Labels: PR/ready for review

#12396 [luci/pass] Revise empty lines of FoldCastPass
  compiler/luci/pass/src/FoldCastPass.cpp
Labels: approval: 1

#12397 [luci/pass] Revise FoldCastPass to early check
  compiler/luci/pass/src/FoldCastPass.cpp
Labels: approval: 1

#12391 [onert/api] Add nnfw_train_get_traininfo
  runtime/onert/api/include/nnfw_experimental.h
  runtime/onert/api/src/nnfw_api.cc
  runtime/onert/api/src/nnfw_api_internal.cc
  runtime/onert/api/src/nnfw_api_internal.h
Labels: PR/ready for review, approval: 2

#12377 [luci/pass] Add more unit tests for ResovleFormerCustomPass
  compiler/luci/pass/src/ResolveFormerCustomOpPass.test.cpp
Labels: PR/ready for review

#12399 [vconone] Bump up to 1.27.0
  compiler/vconone/CMakeLists.txt
Labels: PR/ready for review

#12335 [one-cmds] Revise preprocess_images.py to process also numpy files
  compiler/one-cmds/tests/prepare_test_materials.sh
  compiler/one-cmds/tests/preprocess_images.py
Labels: PR/ready for review

#12393 [onert] Rename training ir Invalid to Undefined
  runtime/onert/api/src/nnfw_api_internal.cc
  runtime/onert/core/include/ir/train/LossCode.h
  runtime/onert/core/include/ir/train/LossInfo.h
  runtime/onert/core/include/ir/train/OptimizerCode.h
  runtime/onert/core/include/ir/train/OptimizerInfo.h
  runtime/onert/core/src/ir/train/LossCode.cc
  runtime/onert/core/src/ir/train/OptimizerCode.cc
  runtime/onert/core/src/ir/train/TrainingInfo.cc
Labels: PR/ready for review, approval: 2

#12402 [circle2circle] Add resolve_former_customop
  compiler/circle2circle/src/Circle2Circle.cpp
Labels: PR/ready for review

#12390 [onert] Merge _training_step into TrainingInfo
  runtime/onert/api/src/nnfw_api_internal.cc
  runtime/onert/api/src/nnfw_api_internal.h
  runtime/onert/core/include/ir/train/TrainingInfo.h
Labels: PR/ready for review

#12404 [runtime] Update runtime version to 1.27.0
  docs/conf.py
  packaging/nnfw.spec
  runtime/contrib/android/api/build.gradle
  runtime/onert/api/include/nnfw_version.h
Labels: PR/ready for review

#12401 [onert] Introduce DepthwiseConv2D trainable operation
  runtime/onert/core/include/ir/train/Operations.Include.h
  runtime/onert/core/include/ir/train/Operations.lst
  runtime/onert/core/include/ir/train/operation/DepthwiseConv2D.h
  runtime/onert/core/src/compiler/train/TrainableOperationConverter.cc
  runtime/onert/core/src/compiler/train/TrainableOperationConverter.h
  runtime/onert/core/src/ir/train/operation/DepthwiseConv2D.cc
Labels: PR/ready for review

#12405 [infra] Support RISC-V gbs build
  infra/nnfw/config/gbs.conf
  packaging/nnfw.spec
Labels: PR/ready for review

#12400 [onert/frontend] Add circle training info loader
  runtime/onert/frontend/circle_traininfo/CMakeLists.txt
  runtime/onert/frontend/circle_traininfo/circle_traininfo.fbs
  runtime/onert/frontend/circle_traininfo/include/traininfo_loader.h
  runtime/onert/frontend/circle_traininfo/src/circle_traininfo_generated.h
  runtime/onert/frontend/circle_traininfo/src/traininfo_loader.cc
Labels: PR/ready for review, approval: 2

#12411 [tools/onert_train] Get training info from session
  tests/tools/onert_train/src/onert_train.cc
Labels: PR/ready for review, approval: 2

#12412 [tools/onert_train] Add *_UNDEF to the dump utility
  tests/tools/onert_train/src/nnfw_util.cc
Labels: PR/ready for review, approval: 2

#12410 [onert/frontend] Revisit traininfo metadata name
  runtime/onert/frontend/circle_traininfo/include/traininfo_loader.h
  runtime/onert/frontend/circle_traininfo/src/traininfo_loader.cc
Labels: PR/ready for review, approval: 2

#12419 [onert] Remove AUTO from train loss reduction type
  runtime/onert/api/include/nnfw_experimental.h
  runtime/onert/api/src/nnfw_api_internal.cc
  runtime/onert/core/include/ir/train/LossInfo.h
  runtime/onert/core/include/ir/train/TrainingInfo.h
  tests/tools/onert_train/src/args.cc
  tests/tools/onert_train/src/nnfw_util.cc
  tests/tools/onert_train/src/onert_train.cc
Labels: PR/ready for review, approval: 2

#12425 [tests/onert_train] Change the type number of loss and optimizer
  tests/tools/onert_train/src/args.cc
  tests/tools/onert_train/src/onert_train.cc
Labels: PR/ready for review

#12430 [onert] Remove api comments no longer valid
  runtime/onert/api/include/nnfw_experimental.h
Labels: PR/ready for review

#12432 [infra] Install clang-format-16 on docker
  infra/docker/focal/Dockerfile
  infra/docker/focal/Dockerfile.aarch64
  infra/docker/jammy/Dockerfile
  infra/docker/jammy/Dockerfile.aarch64
Labels: PR/ready for review

#12408 [onert/api] Load TrainingInfo from the session model
  runtime/onert/api/CMakeLists.txt
  runtime/onert/api/src/nnfw_api_internal.cc
Labels: PR/ready for review, approval: 2

#12435 [luci] Use own shape in the shape inference
  compiler/luci/service/src/CircleShapeInferenceRule.cpp
Labels: PR/ready for review

#12440 [res] Introduce TransposeConv_002
  res/TensorFlowLiteRecipes/TransposeConv_002/test.recipe
Labels: PR/ready for review

#12439 [tflite_comparator] Remove unused header
  tests/tools/tflite_comparator/CMakeLists.txt
  tests/tools/tflite_comparator/src/args.cc
Labels: PR/ready for review

#12409 [res] Add BroadcastTo_000 test.rule
  res/TensorFlowLiteRecipes/BroadcastTo_000/test.rule
Labels: PR/ready for review

#12447 [runtime] Remove boost dependency on logging runtime
  runtime/contrib/logging/CMakeLists.txt
  runtime/contrib/logging/src/nnapi_logging.cc
Labels: PR/ready for review

#12446 [runtime] Move nnfw_lib_benchmark into test directory
  tests/libs/CMakeLists.txt
  tests/libs/benchmark/CMakeLists.txt
  tests/libs/benchmark/include/benchmark.h
  tests/libs/benchmark/include/benchmark/CsvHeader.lst
  tests/libs/benchmark/include/benchmark/CsvWriter.h
  tests/libs/benchmark/include/benchmark/MemoryInfo.h
  tests/libs/benchmark/include/benchmark/MemoryPoller.h
  tests/libs/benchmark/include/benchmark/Phase.h
  tests/libs/benchmark/include/benchmark/Phases.h
  tests/libs/benchmark/include/benchmark/Result.h
  tests/libs/benchmark/include/benchmark/Types.h
  tests/libs/benchmark/src/CsvWriter.cpp
  tests/libs/benchmark/src/MemoryInfo.cpp
  tests/libs/benchmark/src/MemoryPoller.cpp
  tests/libs/benchmark/src/Phases.cpp
  tests/libs/benchmark/src/Result.cpp
Labels: PR/ready for review

#12451 [tools/kbenchmark] Remove boost filesystem dependency
  infra/cmake/packages/NoniusSourceConfig.cmake
  tools/kbenchmark/Args.cc
  tools/kbenchmark/CMakeLists.txt
Labels: PR/ready for review

#12444 [onert] Add time measurement define
  runtime/onert/core/include/util/logging.h
Labels: PR/ready for review

#12452 [tools/tflite_accuracy] Remove tflite_accuracy
  tools/tflite_accuracy/CMakeLists.txt
  tools/tflite_accuracy/README.md
  tools/tflite_accuracy/src/labels.h
  tools/tflite_accuracy/src/tflite_accuracy.cc
Labels: PR/ready for review

#12453 [contrib/tflite_classify] Remove boost dependency
  runtime/contrib/tflite_classify/CMakeLists.txt
  runtime/contrib/tflite_classify/src/tflite_classify.cc
Labels: PR/ready for review

#12454 [contrib/style_transfer_app] Remove boost filesystem dependency
  runtime/contrib/style_transfer_app/CMakeLists.txt
  runtime/contrib/style_transfer_app/src/args.cc
  runtime/contrib/style_transfer_app/src/jpeg_helper.cc
Labels: PR/ready for review

#12406 [circle2circle-dredd-recipe-test] Add resolve_former_customop test
  compiler/circle2circle-dredd-recipe-test/test.lst
Labels: PR/ready for review

#12456 [doc] Move runtime android build guide
  docs/howto/how-to-cross-build-runtime-for-android.md
  docs/nnfw/howto/CrossBuildForAndroid.md
Labels: PR/ready for review

#12475 [res] Add Net_BroadcastTo_AddV2_002
  res/TensorFlowLiteRecipes/Net_BroadcastTo_AddV2_002/test.recipe
  res/TensorFlowLiteRecipes/Net_BroadcastTo_AddV2_002/test.rule
Labels: PR/ready for review

#12479 [rawdata2hdf5] Add warning to deprecate rawdata2hdf5
  compiler/rawdata2hdf5/rawdata2hdf5
Labels: PR/ready for review

#12458 [onert-micro] Change some kernels to use SISOKernel
  onert-micro/luci-interpreter/src/kernels/Abs.cpp
  onert-micro/luci-interpreter/src/kernels/Logistic.cpp
Labels: PR/ready for review

#12476 [cker] Introduce ReLU6 gradient kernel
  compute/cker/include/cker/train/operation/ReLU6.h
  compute/cker/src/train/Relu6.test.cc
Labels: PR/ready for review, approval: 2

#12428 [onert-micro] Reduce duplicate code in pool layers
  onert-micro/luci-interpreter/src/kernels/AveragePool2D.cpp
  onert-micro/luci-interpreter/src/kernels/L2Pool2D.cpp
  onert-micro/luci-interpreter/src/kernels/MaxPool2D.cpp
  onert-micro/luci-interpreter/src/kernels/Pool2DCommon.h
Labels: PR/ready for review

#12436 [onert-micro] Reduce duplicate code in arithmetic kernels
  onert-micro/luci-interpreter/pal/common/PALAddCommon.h
  onert-micro/luci-interpreter/pal/common/PALArithmeticOpCommon.h
  onert-micro/luci-interpreter/pal/common/PALDiv.h
  onert-micro/luci-interpreter/pal/common/PALMulCommon.h
  onert-micro/luci-interpreter/pal/common/PALSub.h
  onert-micro/luci-interpreter/src/kernels/Add.test.cpp
  onert-micro/luci-interpreter/src/kernels/BinaryOpCommon.h
  onert-micro/luci-interpreter/src/kernels/Div.test.cpp
  onert-micro/luci-interpreter/src/kernels/Mul.test.cpp
  onert-micro/luci-interpreter/src/kernels/Sub.test.cpp
Labels: PR/ready for review

#12486 [infra] Use googletest 1.12.1
  infra/cmake/packages/GTestSourceConfig.cmake
Labels: PR/ready for review

#12448 [cker] Introduce DepthwiseConv2D gradient kernel
  compute/cker/include/cker/eigen/depthwise_conv_op.h
  compute/cker/include/cker/train/operation/DepthwiseConv.h
  compute/cker/src/train/DepthwiseConv.test.cc
Labels: PR/ready for review

#12490 [onert/style_transfer_app] Remove unnecessary dependency
  runtime/contrib/style_transfer_app/CMakeLists.txt
Labels: PR/ready for review

#12487 [onert] Apply ReLU6Grad to ElementwiseActivationLayer
  runtime/onert/backend/train/ops/ElementwiseActivationLayer.cc
Labels: PR/ready for review, approval: 2

#12500 [onert-micro] Enable layer-wise hybrid FC
  onert-micro/luci-interpreter/pal/common/PALFullyConnectedCommon.h
  onert-micro/luci-interpreter/pal/common/Params.h
  onert-micro/luci-interpreter/src/kernels/FullyConnected.cpp
Labels: approval: 1

#12459 [onert-micro] Reduce duplicate code in binary kernels
  onert-micro/luci-interpreter/pal/common/PALBinaryOpCommon.h
  onert-micro/luci-interpreter/pal/common/PALFloorDivCommon.h
  onert-micro/luci-interpreter/pal/common/PALFloorModCommon.h
  onert-micro/luci-interpreter/pal/common/PALMaximumCommon.h
  onert-micro/luci-interpreter/pal/common/PALMinimumCommon.h
  onert-micro/luci-interpreter/src/kernels/BinaryOpCommon.h
  onert-micro/luci-interpreter/src/kernels/FloorDiv.cpp
  onert-micro/luci-interpreter/src/kernels/FloorDiv.test.cpp
  onert-micro/luci-interpreter/src/kernels/FloorMod.cpp
  onert-micro/luci-interpreter/src/kernels/FloorMod.test.cpp
  onert-micro/luci-interpreter/src/kernels/Maximum.cpp
  onert-micro/luci-interpreter/src/kernels/Maximum.test.cpp
  onert-micro/luci-interpreter/src/kernels/Minimum.cpp
  onert-micro/luci-interpreter/src/kernels/Minimum.test.cpp
  onert-micro/luci-interpreter/src/kernels/Utils.cpp
  onert-micro/luci-interpreter/src/kernels/Utils.h
Labels: PR/ready for review

#12460 [onert-micro] Reduce duplicate code in comparison kernels
  onert-micro/luci-interpreter/src/kernels/ComparisonCommon.h
  onert-micro/luci-interpreter/src/kernels/Equal.cpp
  onert-micro/luci-interpreter/src/kernels/Greater.cpp
  onert-micro/luci-interpreter/src/kernels/GreaterEqual.cpp
  onert-micro/luci-interpreter/src/kernels/Less.cpp
  onert-micro/luci-interpreter/src/kernels/LessEqual.cpp
  onert-micro/luci-interpreter/src/kernels/NotEqual.cpp
Labels: PR/ready for review

#12497 [infra] Update Pybind11
  infra/cmake/packages/Pybind11SourceConfig.cmake
  runtime/onert/python/api/src/nnfw_api_wrapper.cc
Labels: PR/ready for review

#12492 [onert] Extract fused activation backprop to OperationUtils
  runtime/onert/backend/train/ops/ConvolutionLayer.cc
  runtime/onert/backend/train/ops/FullyConnectedLayer.cc
  runtime/onert/backend/train/ops/OperationUtils.cc
  runtime/onert/backend/train/ops/OperationUtils.h
  runtime/onert/backend/train/ops/PoolLayer.cc
Labels: PR/ready for review, approval: 2

#12498 [onert] Move circle schema generated header
  .ahub/sam/exclude.txt
  runtime/libs/circle-schema/CMakeLists.txt
  runtime/libs/circle-schema/include/circle_schema_generated.h
Labels: PR/ready for review

#12502 [onert] Add ReLU6 grad to OperationUtils
  runtime/onert/backend/train/ops/OperationUtils.cc
Labels: PR/ready for review, approval: 2

#12511 [onert] Move nnfw API implementation
  runtime/onert/CMakeLists.txt
  runtime/onert/api/nnfw/CMakeLists.txt
  runtime/onert/api/nnfw/include/nnfw.h
  runtime/onert/api/nnfw/include/nnfw_experimental.h
  runtime/onert/api/nnfw/include/nnfw_internal.h
  runtime/onert/api/nnfw/include/nnfw_version.h
  runtime/onert/api/nnfw/src/CustomKernel.cc
  runtime/onert/api/nnfw/src/CustomKernel.h
  runtime/onert/api/nnfw/src/CustomKernelRegistry.cc
  runtime/onert/api/nnfw/src/CustomKernelRegistry.h
  runtime/onert/api/nnfw/src/OpMap.lst
  runtime/onert/api/nnfw/src/nnfw_api.cc
  runtime/onert/api/nnfw/src/nnfw_api_internal.cc
  runtime/onert/api/nnfw/src/nnfw_api_internal.h
  runtime/onert/api/nnfw/src/nnfw_debug.cc
Labels: PR/ready for review

#12508 [infra] Remove unused packages on docker image
  infra/docker/bionic/Dockerfile
  infra/docker/focal/Dockerfile
  infra/docker/focal/Dockerfile.aarch64
Labels: PR/ready for review

#12514 [onert] Update DConvLayer to use backpropActivation
  runtime/onert/backend/train/ops/DepthwiseConvolutionLayer.cc
Labels: PR/ready for review, approval: 2

#12513 [onert] Move loaders into core
  .ahub/sam/exclude.txt
  docs/howto/how-to-introduce-a-new-operation-into-runtime.md
  runtime/onert/api/nnfw/CMakeLists.txt
  runtime/onert/api/nnfw/src/nnfw_api_internal.cc
  runtime/onert/core/CMakeLists.txt
  runtime/onert/core/include/loader/circle_loader.h
  runtime/onert/core/include/loader/tflite_loader.h
  runtime/onert/core/include/loader/traininfo_loader.h
  runtime/onert/core/src/loader/base_loader.h
  runtime/onert/core/src/loader/circle_loader.cc
  runtime/onert/core/src/loader/circle_traininfo.fbs
  runtime/onert/core/src/loader/circle_traininfo_generated.h
  runtime/onert/core/src/loader/tflite_loader.cc
  runtime/onert/core/src/loader/tflite_schema.fbs
  runtime/onert/core/src/loader/tflite_schema_generated.h
  runtime/onert/core/src/loader/traininfo_loader.cc
  runtime/onert/frontend/base_loader/CMakeLists.txt
  runtime/onert/frontend/circle/CMakeLists.txt
  runtime/onert/frontend/circle_traininfo/CMakeLists.txt
  runtime/onert/frontend/tflite/CMakeLists.txt
  runtime/onert/frontend/tflite/tflite_schema-1.13.1.fbs
Labels: PR/ready for review

#12517 [tools/onert_train] Add virtual destructor for DataLoader
  tests/tools/onert_train/src/dataloader.h
Labels: PR/ready for review

#12515 [onert] Move APIs implementation
  runtime/onert/CMakeLists.txt
  runtime/onert/api/CMakeLists.txt
  runtime/onert/api/nnapi/CMakeLists.txt
  runtime/onert/api/nnapi/compilation.cc
  runtime/onert/api/nnapi/event.cc
  runtime/onert/api/nnapi/execution.cc
  runtime/onert/api/nnapi/memory.cc
  runtime/onert/api/nnapi/model.cc
  runtime/onert/api/nnapi/wrapper/ANeuralNetworksCompilation.cc
  runtime/onert/api/nnapi/wrapper/ANeuralNetworksCompilation.h
  runtime/onert/api/nnapi/wrapper/ANeuralNetworksEvent.cc
  runtime/onert/api/nnapi/wrapper/ANeuralNetworksEvent.h
  runtime/onert/api/nnapi/wrapper/ANeuralNetworksExecution.cc
  runtime/onert/api/nnapi/wrapper/ANeuralNetworksExecution.h
  runtime/onert/api/nnapi/wrapper/ANeuralNetworksMemory.cc
  runtime/onert/api/nnapi/wrapper/ANeuralNetworksMemory.h
  runtime/onert/api/nnapi/wrapper/ANeuralNetworksModel.cc
  runtime/onert/api/nnapi/wrapper/ANeuralNetworksModel.h
  runtime/onert/api/nnapi/wrapper/ANeuralNetworksModel.test.cc
  runtime/onert/api/nnapi/wrapper/NNAPIConvert.cc
  runtime/onert/api/nnapi/wrapper/NNAPIConvert.h
  runtime/onert/api/nnapi/wrapper/OperationFactory.cc
  runtime/onert/api/nnapi/wrapper/OperationFactory.h
  runtime/onert/api/python/CMakeLists.txt
  runtime/onert/api/python/include/nnfw_api_wrapper.h
  runtime/onert/api/python/package/__init__.py
  runtime/onert/api/python/package/libnnfw_api_pybind.py
  runtime/onert/api/python/src/nnfw_api_wrapper.cc
  runtime/onert/api/python/src/nnfw_api_wrapper_pybind.cc
  runtime/onert/python/CMakeLists.txt
Labels: PR/ready for review

#12484 [onert-micro] Reduce duplicate code in PadCommon.cpp
  onert-micro/luci-interpreter/src/kernels/PadCommon.cpp
Labels: PR/ready for review

#12531 [onert] Introduce ICodegen class
  runtime/onert/core/include/odc/ICodegen.h
Labels: PR/ready for review

#12529 [tools/onert_train] Update onert_train to use C++17
  tests/tools/onert_train/CMakeLists.txt
Labels: PR/ready for review

#12533 [onert] Rename frontend to loader
  runtime/onert/CMakeLists.txt
  runtime/onert/loader/CMakeLists.txt
  runtime/onert/loader/trix/CMakeLists.txt
  runtime/onert/loader/trix/include/trix_loader.h
  runtime/onert/loader/trix/src/trix_loader.cc
  runtime/onert/loader/trix/src/trix_loader_dummy.cc
Labels: PR/ready for review

#12532 [cker] Introduce Add gradient kernel
  compute/cker/include/cker/train/operation/BinaryArithmetic.h
  compute/cker/src/train/BinaryArithmetic.test.cc
Labels: PR/ready for review, approval: 2

#12528 [tools/onert_train] Refactor print logic of train info
  tests/tools/onert_train/src/nnfw_util.cc
  tests/tools/onert_train/src/nnfw_util.h
Labels: PR/ready for review, approval: 2

#12537 [tools/onert_run] Introduce compile and cpath arguments
  tests/tools/onert_run/src/args.cc
  tests/tools/onert_run/src/args.h
Labels: PR/ready for review

#12538 [onert-micro] Introduce user interface entities
  onert-micro/onert-micro/include/OMConfig.h
  onert-micro/onert-micro/include/OMInterpreter.h
  onert-micro/onert-micro/include/OMStatus.h
  onert-micro/onert-micro/src/OMInterpreter.cpp
Labels: approval: 2

#12539 [tflchef] Fix shadows local variable problem
  compiler/tflchef/tflite/src/RecipeChef.cpp
Labels: approval: 1

#12483 [onert-micro] Reduce duplicate code in convolution kernels
  onert-micro/luci-interpreter/src/kernels/CMakeLists.txt
  onert-micro/luci-interpreter/src/kernels/Conv2D.cpp
  onert-micro/luci-interpreter/src/kernels/ConvolutionCommon.cpp
  onert-micro/luci-interpreter/src/kernels/ConvolutionCommon.h
  onert-micro/luci-interpreter/src/kernels/DepthwiseConv2D.cpp
Labels: PR/ready for review

#12478 [luci/pass] Introduce the pass to FoldShape
  compiler/luci/pass/include/luci/Pass/FoldShapePass.h
  compiler/luci/pass/src/FoldShapePass.cpp
  compiler/luci/pass/src/FoldShapePass.test.cpp
Labels: PR/ready for review, approval: 2

#12527 [luci/pass] Introduce a ResolveCustomOpAddPassTest class to use TEST_F
  compiler/luci/pass/src/ResolveCustomOpAddPass.test.cpp
Labels: PR/ready for review

#12544 [luci] Introduce FoldShape
  compiler/luci/pass/include/luci/CircleOptimizer.h
  compiler/luci/pass/src/CircleOptimizer.cpp
Labels: PR/ready for review, approval: 2

#12540 [cker] Fix typo on license
  compute/cker/src/train/BinaryArithmetic.test.cc
Labels: PR/ready for review, approval: 1

#12547 [souschef] Add clear tensor filler methods
  compiler/souschef/include/souschef/TensorFiller.h
Labels: approval: 2

#12536 [onert] Introduce CodegenLoader class
  runtime/onert/core/include/odc/ICodegen.h
  runtime/onert/core/src/odc/CodegenLoader.cc
  runtime/onert/core/src/odc/CodegenLoader.h
Labels: PR/ready for review

#12543 [cker] Introduce Subtract gradient kernel
  compute/cker/include/cker/train/operation/BinaryArithmetic.h
  compute/cker/src/train/BinaryArithmetic.test.cc
Labels: PR/ready for review, approval: 2

#12552 [circle2circle] Add option to fold Shape op
  compiler/circle2circle/src/Circle2Circle.cpp
Labels: PR/ready for review

#12542 [onert] Implement BinaryArithmeticLayer in train backend
  runtime/onert/backend/cpu/ops/BinaryArithmeticLayer.h
  runtime/onert/backend/train/KernelGenerator.cc
  runtime/onert/backend/train/KernelGenerator.h
  runtime/onert/backend/train/ops/BinaryArithmeticLayer.cc
  runtime/onert/backend/train/ops/BinaryArithmeticLayer.h
Labels: PR/ready for review, approval: 2

#12549 [res] Add a TensorFlowLiteRecipes to test fold Shape
  res/TensorFlowLiteRecipes/Net_Shape_Add_000/test.recipe
Labels: PR/ready for review, approval: 2

#12557 [luci-pass-value-py-test] Add fold_shape test
  compiler/luci-pass-value-py-test/test.lst
Labels: PR/ready for review

#12558 [luci-pass-value-py-test] Sort tests in alphabetical order
  compiler/luci-pass-value-py-test/test.lst
Labels: PR/ready for review

#12559 [res] Add dredd test rule for fold_shape
  res/TensorFlowLiteRecipes/Net_Shape_Add_000/test.rule
Labels: PR/ready for review

#12550 [onert-micro] Add circle reader entities
  onert-micro/onert-micro/include/core/OMDataType.h
  onert-micro/onert-micro/include/core/OMKernelData.h
  onert-micro/onert-micro/include/core/OMKernelType.h
  onert-micro/onert-micro/include/core/reader/OMCircleReader.h
  onert-micro/onert-micro/src/core/OMDataType.cpp
  onert-micro/onert-micro/src/core/OMKernelType.cpp
  onert-micro/onert-micro/src/core/reader/OMCircleReader.cpp
Labels: approval: 2

#12566 [luci-interpreter] Prevent overflow from bit shifting
  compiler/luci-interpreter/include/luci_interpreter/BuddyMemoryManager.h
Labels: PR/ready for review

#12567 [luci] Prevent overflow from bit shifting
  compiler/luci/service/src/ShapeInfer_StridedSlice.cpp
Labels: PR/ready for review

#12568 [luci] Casting to larger dtype before performing arithmetic
  compiler/luci/pass/src/helpers/SparsityFormatConverter.cpp
Labels: PR/ready for review

#12553 [onert] Introduce CodegenManager class
  runtime/onert/core/include/odc/CodegenManager.h
  runtime/onert/core/src/odc/CodegenManager.cc
Labels: PR/ready for review

#12573 [circle2circle-dredd-recipe-test] Add fold_shape test
  compiler/circle2circle-dredd-recipe-test/test.lst
Labels: PR/ready for review

#12580 [tflchef] Add While op
  compiler/tflchef/tflite/src/Op/While.cpp
  compiler/tflchef/tflite/src/Op/include/While.h
  compiler/tflchef/tflite/src/TFliteOpChefs.h
  compiler/tflchef/tflite/src/TFliteOpRegistry.h
Labels: approval: 2

#12551 [tflchef] Support multiple subgraphs
  compiler/tflchef/tflite/src/RecipeChef.cpp
  compiler/tflchef/tflite/src/TFliteImport.cpp
Labels: approval: 2

#12581 [tflchef] Add filler for Less op
  compiler/tflchef/tflite/src/Op/Less.cpp
Labels: approval: 2

#12575 [luci/pass] Revise ResolveCustomOpAddPass to introduce num_of_broadcast_to
  compiler/luci/pass/src/ResolveCustomOpAddPass.cpp
Labels: PR/ready for review
