Repository Samsung/ONE, pull requests merged in 2024-07, with the labels that each got.

#13318 [onert] Introduce index types for training
  runtime/onert/core/include/ir/train/Index.h
Labels: PR/ready for review

#13315 [one-cmds] Revise onecc script
  compiler/one-cmds/onecc
  compiler/one-cmds/onelib/CfgRunner.py
  compiler/one-cmds/onelib/utils.py
Labels: PR/ready for review

#13336 [luci-interpreter] Support int64 dtype in the CircleTranspose
  compiler/luci-interpreter/src/kernels/Transpose.cpp
Labels: PR/ready for review

#13339 [one-cmds] Print available target
  compiler/one-cmds/onecc
  compiler/one-cmds/onelib/utils.py
Labels: PR/ready for review

#13340 [one-cmds] Raise error when backend and target option are given
  compiler/one-cmds/onecc
  compiler/one-cmds/tests/onecc_neg_037.test
Labels: PR/ready for review

#13341 [tflite2circle] Support more data types
  compiler/tflite2circle/src/TFLTensorType.lst
Labels: PR/ready for review

#13343 [luci-interpreter] Support bool type in NotEqual and ReduceMax op
  compiler/luci-interpreter/src/kernels/NotEqual.cpp
  compiler/luci-interpreter/src/kernels/NotEqual.h
  compiler/luci-interpreter/src/kernels/ReduceMax.cpp
  compiler/luci-interpreter/src/kernels/ReduceMax.h
Labels: PR/ready for review

#13338 [onert] Introduce UseDefChain
  runtime/onert/core/include/ir/train/UseDefChain.h
  runtime/onert/core/include/ir/train/UseDefChains.h
  runtime/onert/core/src/ir/train/UseDefChain.cc
Labels: PR/ready for review

#13345 [infra] Update onert python packaging
  infra/nnfw/python/.gitignore
  infra/nnfw/python/README.md
  infra/nnfw/python/setup.py
  runtime/onert/api/python/package/libnnfw_api_pybind.py
Labels: PR/ready for review

#13344 [onert/test] Support minmax_runs argument in onert_run
  tests/tools/onert_run/src/args.cc
  tests/tools/onert_run/src/args.h
  tests/tools/onert_run/src/onert_run.cc
Labels: PR/ready for review

#13349 [infra/onert] Use static link for Boost and HDF5
  infra/nnfw/cmake/CfgOptionFlags.cmake
  infra/nnfw/cmake/packages/BoostConfig.cmake
  infra/nnfw/cmake/packages/HDF5Config.cmake
Labels: PR/ready for review

#13356 [luci-interpreter] Add test for NotEqual, ReduceMax, Transpose
  compiler/luci-interpreter/src/kernels/NotEqual.test.cpp
  compiler/luci-interpreter/src/kernels/ReduceMax.test.cpp
  compiler/luci-interpreter/src/kernels/Transpose.test.cpp
Labels: PR/ready for review

#13354 [oenrt_run] Force input/output type to float
  tests/tools/onert_run/src/args.cc
  tests/tools/onert_run/src/args.h
  tests/tools/onert_run/src/onert_run.cc
Labels: PR/ready for review

#13351 [onert] Fix wrong applied shape in backward of MeanLayer
  runtime/onert/backend/train/ops/MeanLayer.cc
Labels: PR/ready for review

#13361 [contrib/style_transfer_app] Add size limit to input images
  runtime/contrib/style_transfer_app/src/jpeg_helper.cc
Labels: PR/ready for review, approval: 1

#13358 [onert] Add assertion to check whether tensor is dynamic
  runtime/onert/backend/train/ops/OperationUtils.cc
  runtime/onert/backend/train/ops/OperationUtils.h
Labels: PR/ready for review

#13360 [onert/test] Use arser for tflite_run argument parsing
  infra/nnfw/CMakeLists.txt
  tests/tools/tflite_run/CMakeLists.txt
  tests/tools/tflite_run/src/args.cc
  tests/tools/tflite_run/src/args.h
Labels: PR/ready for review

#13357 [infra] Update tizen test build
  infra/nnfw/cmake/options/options_aarch64-tizen.cmake
  infra/nnfw/cmake/options/options_armv7hl-tizen.cmake
  infra/nnfw/cmake/options/options_armv7l-tizen.cmake
  infra/nnfw/cmake/options/options_riscv64-tizen.cmake
  infra/nnfw/cmake/options/options_x86_64-tizen.cmake
  packaging/nnfw.spec
Labels: PR/ready for review

#13352 [onert] Add essentialBackwardOrder to TrainableGraph
  runtime/onert/core/include/ir/train/TrainableGraph.h
  runtime/onert/core/src/ir/train/TrainableGraph.cc
  runtime/onert/core/src/ir/train/TrainableGraph.test.cc
Labels: PR/ready for review

#13353 [onert] Add use-def chains to TrainableGraph
  runtime/onert/core/include/ir/train/TrainableGraph.h
  runtime/onert/core/include/ir/train/UseDefChains.h
  runtime/onert/core/src/ir/train/TrainableGraph.cc
  runtime/onert/core/src/ir/verifier/Verifier.cc
  runtime/onert/core/src/ir/verifier/Verifier.h
Labels: PR/ready for review

#13342 [onert] Revisit IOTensor
  runtime/onert/core/src/backend/builtin/IOTensor.cc
  runtime/onert/core/src/backend/builtin/IOTensor.h
  runtime/onert/core/src/backend/builtin/kernel/WhileLayer.cc
  runtime/onert/core/src/exec/ExecutorBase.cc
  runtime/onert/core/src/exec/MultiModelExecutors.cc
  runtime/onert/core/src/exec/SingleModelExecutors.cc
  runtime/onert/core/src/exec/train/TrainableExecutors.cc
Labels: PR/ready for review, approval: 2

#13369 [onert/onert_run] Reshape output shape
  tests/tools/onert_run/src/args.cc
  tests/tools/onert_run/src/args.h
  tests/tools/onert_run/src/onert_run.cc
Labels: PR/ready for review

#13372 [onert] Add disabling backward to TrainableGraph
  runtime/onert/core/include/ir/train/ITrainableOperation.h
  runtime/onert/core/include/ir/train/TrainableGraph.h
  runtime/onert/core/include/ir/train/TrainableOperation.h
  runtime/onert/core/src/ir/train/TrainableGraph.cc
Labels: PR/ready for review

#13368 [onert] Revisit IPortableTensor
  runtime/onert/backend/train/optimizer/Optimizers.test.cc
  runtime/onert/core/include/backend/IPortableTensor.h
  runtime/onert/core/include/backend/basic/Tensor.h
  runtime/onert/core/include/backend/basic/train/TrainableTensor.h
  runtime/onert/core/src/backend/IPortableTensor.cc
  runtime/onert/core/src/backend/basic/Tensor.cc
  runtime/onert/core/src/backend/builtin/IOTensor.h
  runtime/onert/core/src/backend/builtin/UserTensor.cc
  runtime/onert/core/src/backend/builtin/UserTensor.h
Labels: PR/ready for review

#13375 [onert] Replace btopolSortOperations with essentialBackwardOrder
  runtime/onert/backend/train/BackendContext.cc
  runtime/onert/core/src/compiler/ExecutorFactory.cc
Labels: PR/ready for review

#13380 [onert] Fix typo in IPortableTensor.h
  runtime/onert/core/include/backend/IPortableTensor.h
Labels: PR/ready for review, approval: 1

#13376 [onert] Add missing allocation in train BinaryArithmeticLayer
  runtime/onert/backend/train/ops/BinaryArithmeticLayer.cc
Labels: PR/ready for review

#13373 [onert] Add missing definition in TrainableGraph
  runtime/onert/core/src/ir/train/TrainableGraph.cc
Labels: PR/ready for review

#13378 [onert] Move assertion in loss layers
  runtime/onert/backend/train/ops/LossCategoricalCrossentropyLayer.cc
  runtime/onert/backend/train/ops/LossLayer.cc
  runtime/onert/backend/train/ops/LossMeanSquaredErrorLayer.cc
Labels: PR/ready for review

#13379 [onert] Introduce GradientMemoryManager
  runtime/onert/backend/train/MemoryManager.cc
  runtime/onert/backend/train/MemoryManager.h
  runtime/onert/backend/train/TensorBuilder.cc
  runtime/onert/backend/train/TensorManager.cc
  runtime/onert/backend/train/TensorManager.h
  runtime/onert/core/include/backend/basic/MemoryManager.h
  runtime/onert/core/include/backend/basic/train/TrainableTensor.h
Labels: PR/ready for review

#13387 [onert/tflite_comparator] Use arser for tflite_comparator
  tests/tools/tflite_comparator/CMakeLists.txt
  tests/tools/tflite_comparator/src/args.cc
  tests/tools/tflite_comparator/src/args.h
Labels: PR/ready for review

#13395 [onert] Use reference in TrainInfoBuilder
  runtime/onert/core/src/exporter/TrainInfoBuilder.h
Labels: PR/ready for review, approval: 1

#13386 [onert/kbenchmark] Use arser for kbenchmark
  tools/kbenchmark/Args.cc
  tools/kbenchmark/CMakeLists.txt
Labels: PR/ready for review

#13383 [onert] Remove IOTensor dependency in IExecutor
  runtime/onert/core/include/exec/IExecutor.h
  runtime/onert/core/src/backend/builtin/kernel/IfLayer.h
  runtime/onert/core/src/backend/builtin/kernel/WhileLayer.cc
  runtime/onert/core/src/exec/ExecutorBase.h
  runtime/onert/core/src/exec/MultiModelExecutors.cc
  runtime/onert/core/src/exec/MultiModelExecutors.h
  runtime/onert/core/src/exec/SingleModelExecutors.cc
  runtime/onert/core/src/exec/train/TrainableExecutor.h
  runtime/onert/core/src/exec/train/TrainableExecutors.cc
Labels: PR/ready for review

#13389 [vconone] Bump up to 1.27.1
  compiler/vconone/CMakeLists.txt
Labels: PR/ready for review, type/release

#13390 [debian] Update changelog
  infra/debian/compiler/changelog
Labels: PR/ready for review, type/release

#13391 Release note 1.27.1
  docs/release/1.27/index.rst
  docs/release/1.27/release-note-1.27.1.md
Labels: type/release

#13400 [one-cmds] Revisit command schema feature
  docs/release/1.27/index.rst
  docs/release/1.27/release-note-1.27.1.md
Labels: type/release

#13394 [onert] Correct the shape when _keep_dims is false in backward of MeanLayer
  runtime/onert/backend/train/ops/MeanLayer.cc
Labels: PR/ready for review

#13403 [debian] Update changelog
  infra/debian/compiler/changelog
Labels: type/release

#13402 [arser] Support multiline help message alignment
  compiler/arser/include/arser/arser.h
  compiler/arser/tests/arser.test.cpp
Labels: PR/ready for review

#13405 [luci-interpreter] Support int type of CumSum op
  compiler/luci-interpreter/src/kernels/CumSum.cpp
  compiler/luci-interpreter/src/kernels/CumSum.test.cpp
Labels: PR/ready for review

#13399 [onert] Change Edge tensor type in MultiModelExecutors
  runtime/onert/core/src/exec/MultiModelExecutors.cc
  runtime/onert/core/src/exec/MultiModelExecutors.h
Labels: PR/ready for review

#13401 [onert] Support type-aware quantization in SingleModelExecutors
  runtime/onert/core/src/exec/Execution.test.cc
  runtime/onert/core/src/exec/ExecutorBase.cc
  runtime/onert/core/src/exec/SingleModelExecutors.cc
Labels: PR/ready for review

#13408 [onert/cker] Remove unused variable
  compute/cker/include/cker/operation/SplitV.h
Labels: PR/ready for review, approval: 1

#13409 [onert] Remove unused variable in ShapeInference
  runtime/onert/core/src/util/ShapeInference.cc
Labels: PR/ready for review, approval: 1

#13406 [infra] Update android build
  infra/nnfw/cmake/buildtool/cross/toolchain_aarch64-android.cmake
  infra/nnfw/cmake/packages/ARMComputeConfig.cmake
Labels: PR/ready for review

#13410 [debian] Update one-cmds man pages
  infra/debian/compiler/docs/one-codegen.1
  infra/debian/compiler/docs/one-import-bcq.1
  infra/debian/compiler/docs/one-import-onnx.1
  infra/debian/compiler/docs/one-import-tf.1
  infra/debian/compiler/docs/one-import-tflite.1
  infra/debian/compiler/docs/one-import.1
  infra/debian/compiler/docs/one-infer.1
  infra/debian/compiler/docs/one-optimize.1
  infra/debian/compiler/docs/one-pack.1
  infra/debian/compiler/docs/one-partition.1
  infra/debian/compiler/docs/one-profile.1
  infra/debian/compiler/docs/one-quantize.1
  infra/debian/compiler/docs/onecc.1
Labels: PR/ready for review

#13417 [debian] Update help message of man page
  infra/debian/compiler/docs/one-codegen.1
  infra/debian/compiler/docs/one-profile.1
  infra/debian/compiler/docs/onecc.1
Labels: PR/ready for review

#13416 [one-cmds] Update help message usage
  compiler/one-cmds/one-codegen
  compiler/one-cmds/one-profile
  compiler/one-cmds/onecc
Labels: PR/ready for review

#13418 [one-cmds] Support target option with command args
  compiler/one-cmds/one-codegen
  compiler/one-cmds/one-profile
  compiler/one-cmds/tests/one-codegen_010.ini
  compiler/one-cmds/tests/one-codegen_010.test
  compiler/one-cmds/tests/one-codegen_011.ini
  compiler/one-cmds/tests/one-codegen_011.test
  compiler/one-cmds/tests/one-codegen_neg_001.test
  compiler/one-cmds/tests/one-codegen_neg_002.test
  compiler/one-cmds/tests/one-codegen_neg_003.test
  compiler/one-cmds/tests/one-profile_010.ini
  compiler/one-cmds/tests/one-profile_010.test
  compiler/one-cmds/tests/one-profile_011.ini
  compiler/one-cmds/tests/one-profile_011.test
  compiler/one-cmds/tests/one-profile_neg_001.test
  compiler/one-cmds/tests/one-profile_neg_002.test
  compiler/one-cmds/tests/one-profile_neg_003.test
Labels: PR/ready for review

#13414 [compute/cker] Mark UNUSED_RELEASE
  compute/cker/include/cker/operation/Concatenation.h
  compute/cker/include/cker/operation/StridedSlice.h
Labels: PR/ready for review, approval: 1

#13413 [infra] Version up NDK
  docs/howto/how-to-cross-build-runtime-for-android.md
  infra/docker/android-sdk/Dockerfile
  tools/cross/install_android_ndk.sh
  tools/cross/install_android_sdk.sh
Labels: PR/ready for review

#13420 [onert/test] Fix unittest bug in CompiledMockUpQuantModel
  runtime/onert/core/src/exec/Execution.test.cc
Labels: PR/ready for review, approval: 1

#13412 [onert] Support float type I/O setting API on quantized model
  runtime/onert/api/nnfw/include/nnfw.h
  runtime/onert/api/nnfw/src/nnfw_api_internal.cc
  runtime/onert/core/src/exec/Execution.cc
  runtime/onert/core/src/exec/Execution.test.cc
  tests/nnfw_api/src/GenModelTests/ModelTestDynamicTensor.test.cc
  tests/nnfw_api/src/NNPackageTests/AddSessionPrepared.test.cc
Labels: PR/ready for review

#13421 [onert] Move EdgeTensor and PermuteFunction classes
  runtime/onert/core/src/exec/EdgeTensor.cc
  runtime/onert/core/src/exec/EdgeTensor.h
  runtime/onert/core/src/exec/IPermuteFunction.h
  runtime/onert/core/src/exec/MultiModelExecutors.cc
  runtime/onert/core/src/exec/MultiModelExecutors.h
  runtime/onert/core/src/exec/SingleModelExecutors.cc
Labels: PR/ready for review

#13426 [debian] Update changelog for 1.27.2
  infra/debian/compiler/changelog
Labels: type/release

#13424 [vconone] Bump up to 1.27.2
  compiler/vconone/CMakeLists.txt
Labels: type/release

#13427 Release note 1.27.2
  docs/release/1.27/index.rst
  docs/release/1.27/release-note-1.27.2.md
Labels: type/release

#13432 [onert/training] Store disposable tensor indices in TensorBuilder
  runtime/onert/backend/train/TensorBuilder.cc
  runtime/onert/backend/train/TensorBuilder.h
Labels: PR/ready for review

#13430 [onert] Change TrainableExecutor forward call
  runtime/onert/core/src/exec/train/TrainableExecutor.cc
  runtime/onert/core/src/exec/train/TrainableExecutor.h
  runtime/onert/core/src/exec/train/TrainableExecutors.cc
  runtime/onert/core/src/exec/train/TrainableExecutors.h
Labels: PR/ready for review

#13434 [onert] Remove unused Executor and IOTensor method
  runtime/onert/core/include/exec/IExecutor.h
  runtime/onert/core/src/backend/builtin/IOTensor.cc
  runtime/onert/core/src/backend/builtin/IOTensor.h
  runtime/onert/core/src/exec/ExecutorBase.cc
  runtime/onert/core/src/exec/ExecutorBase.h
  runtime/onert/core/src/exec/train/TrainableExecutor.h
Labels: PR/ready for review, approval: 1

#13450 [infra] Bump up CpuInfo
  infra/cmake/packages/CpuInfoSourceConfig.cmake
  packaging/CPUINFO.tar.gz
Labels: PR/ready for review

#13451 [CI/github] Bump up actions
  .github/workflows/check-format.yml
  .github/workflows/check-pr-commit.yml
  .github/workflows/deploy-github-pages.yml
  .github/workflows/run-onert-micro-unit-tests.yml
Labels: PR/ready for review

#13374 [onert] Introduce UseDefGenerator
  runtime/onert/core/src/ir/train/UseDefGenerator.cc
  runtime/onert/core/src/ir/train/UseDefGenerator.h
Labels: PR/ready for review

#13443 Release note 1.28.0
  docs/release/1.28/index.rst
  docs/release/1.28/release-note_1.28.0.md
Labels: PR/ready for review

#13465 [vconone] Bump up to 1.29.0
  compiler/vconone/CMakeLists.txt
Labels: PR/ready for review

#13466 [onert] Fix typo in train kernel generator
  runtime/onert/backend/train/KernelGenerator.cc
Labels: PR/ready for review, approval: 1

#13464 [onert] Bump up to 1.29.0
  docs/conf.py
  packaging/nnfw.spec
  runtime/contrib/android/api/build.gradle
  runtime/onert/api/nnfw/include/nnfw_version.h
  tools/release_tool/onert_version.sh
Labels: PR/ready for review

#13469 [onert] Fix a typo in train kernel generator
  runtime/onert/backend/train/KernelGenerator.cc
Labels: approval: 1

#13433 [onert/training] Introduce TensorPlanner
  runtime/onert/backend/train/TensorPlanner.cc
  runtime/onert/backend/train/TensorPlanner.h
Labels: PR/ready for review

#13460 [onert] Add generating training usedefs for Reshape op
  runtime/onert/core/src/ir/train/UseDefGenerator.cc
  runtime/onert/core/src/ir/train/UseDefGenerator.h
Labels: PR/ready for review

#13453 [onert] Add generating training usedefs for Conv2D op
  runtime/onert/core/src/ir/train/UseDefGenerator.cc
  runtime/onert/core/src/ir/train/UseDefGenerator.h
Labels: PR/ready for review

#13474 [infra/debian] Remove unused runtime build dependency
  infra/debian/runtime/control
Labels: PR/ready for review

#13473 [infra/onert] Remove ACL from runtime package
  Makefile.template
Labels: PR/ready for review

#13454 [onert] Add generating training usedefs for DepthwiseConv2D op
  runtime/onert/core/src/ir/train/UseDefGenerator.cc
  runtime/onert/core/src/ir/train/UseDefGenerator.h
Labels: PR/ready for review

#13457 [onert] Add generating training usedefs for Pad op
  runtime/onert/core/src/ir/train/UseDefGenerator.cc
  runtime/onert/core/src/ir/train/UseDefGenerator.h
Labels: PR/ready for review

#13475 [onert] Use C++17
  infra/nnfw/CMakeLists.txt
  runtime/contrib/style_transfer_app/CMakeLists.txt
  runtime/contrib/tflite_classify/CMakeLists.txt
  tests/CMakeLists.txt
  tools/CMakeLists.txt
Labels: PR/ready for review

#13455 [onert] Add generating training usedefs for ElementwiseActivation op
  runtime/onert/core/src/ir/train/UseDefGenerator.cc
  runtime/onert/core/src/ir/train/UseDefGenerator.h
Labels: PR/ready for review

#13458 [onert] Add generating training usedefs for Pool2D op
  runtime/onert/core/src/ir/train/UseDefGenerator.cc
  runtime/onert/core/src/ir/train/UseDefGenerator.h
Labels: PR/ready for review

#13484 [fme-detect] Introduce fme-detect
  compiler/fme-detect/CMakeLists.txt
  compiler/fme-detect/README.md
  compiler/fme-detect/driver/Driver.cpp
  compiler/fme-detect/requires.cmake
  compiler/fme-detect/src/EqualizePattern.h
  compiler/fme-detect/src/EqualizePatternFinder.cpp
  compiler/fme-detect/src/EqualizePatternFinder.h
  compiler/fme-detect/src/EqualizePatternFinder.test.cpp
  compiler/fme-detect/src/EqualizePatternWrite.cpp
  compiler/fme-detect/src/EqualizePatternWrite.h
  compiler/fme-detect/src/EqualizePatternWrite.test.cpp
Labels: PR/ready for review

#13485 [fme-apply] Introduce fme-apply
  compiler/fme-apply/CMakeLists.txt
  compiler/fme-apply/README.md
  compiler/fme-apply/driver/Driver.cpp
  compiler/fme-apply/requires.cmake
  compiler/fme-apply/src/EqualizePattern.h
  compiler/fme-apply/src/EqualizePatternCheck.cpp
  compiler/fme-apply/src/EqualizePatternCheck.h
  compiler/fme-apply/src/EqualizePatternCheck.test.cpp
  compiler/fme-apply/src/EqualizePatternRead.cpp
  compiler/fme-apply/src/EqualizePatternRead.h
  compiler/fme-apply/src/EqualizePatternRead.test.cpp
  compiler/fme-apply/src/FMEqualizer.cpp
  compiler/fme-apply/src/FMEqualizer.h
  compiler/fme-apply/src/FMEqualizer.test.cpp
  compiler/fme-apply/src/InsertScaleShift.cpp
  compiler/fme-apply/src/InsertScaleShift.h
  compiler/fme-apply/src/InsertScaleShift.test.cpp
  compiler/fme-apply/src/ProgressReporter.cpp
  compiler/fme-apply/src/ProgressReporter.h
  compiler/fme-apply/src/RandomString.cpp
  compiler/fme-apply/src/RandomString.h
  compiler/fme-apply/src/RandomString.test.cpp
  compiler/fme-apply/src/Support.Cast.cpp
  compiler/fme-apply/src/Support.Cast.h
  compiler/fme-apply/src/Support.Cast.test.cpp
  compiler/fme-apply/src/Support.Misc.cpp
  compiler/fme-apply/src/Support.Misc.h
  compiler/fme-apply/src/Support.Misc.test.cpp
  compiler/fme-apply/src/pass/ForwardPreScalePass.cpp
  compiler/fme-apply/src/pass/ForwardPreScalePass.h
  compiler/fme-apply/src/pass/ForwardPreScalePass.test.cpp
  compiler/fme-apply/src/pass/ForwardPreShiftPass.cpp
  compiler/fme-apply/src/pass/ForwardPreShiftPass.h
  compiler/fme-apply/src/pass/ForwardPreShiftPass.test.cpp
  compiler/fme-apply/src/pass/FusePostScalePass.cpp
  compiler/fme-apply/src/pass/FusePostScalePass.h
  compiler/fme-apply/src/pass/FusePostScalePass.test.cpp
  compiler/fme-apply/src/pass/FusePostShiftPass.cpp
  compiler/fme-apply/src/pass/FusePostShiftPass.h
  compiler/fme-apply/src/pass/FusePostShiftPass.test.cpp
  compiler/fme-apply/src/pass/FusePreScalePass.cpp
  compiler/fme-apply/src/pass/FusePreScalePass.h
  compiler/fme-apply/src/pass/FusePreScalePass.test.cpp
  compiler/fme-apply/src/pass/FusePreShiftPass.cpp
  compiler/fme-apply/src/pass/FusePreShiftPass.h
  compiler/fme-apply/src/pass/FusePreShiftPass.test.cpp
Labels: PR/ready for review

#13481 [onert] Use original map in ConstantInsertionPass
  runtime/onert/core/src/compiler/pass/ConstantInsertionPass.cc
  runtime/onert/core/src/compiler/pass/ConstantInsertionPass.h
Labels: PR/ready for review

#13452 [onert] Add generating training usedefs for BinaryArithmetic op
  runtime/onert/core/src/ir/train/UseDefGenerator.cc
  runtime/onert/core/src/ir/train/UseDefGenerator.h
Labels: PR/ready for review

#13470 [onert] Plan non-const tensors on train backend
  runtime/onert/backend/train/TensorPlanner.cc
Labels: PR/ready for review

#13456 [onert] Add generating training usedefs for FullyConnected op
  runtime/onert/core/src/ir/train/UseDefGenerator.cc
  runtime/onert/core/src/ir/train/UseDefGenerator.h
Labels: PR/ready for review

#13459 [onert] Add generating training usedefs for Reduce op
  runtime/onert/core/src/ir/train/UseDefGenerator.cc
  runtime/onert/core/src/ir/train/UseDefGenerator.h
Labels: PR/ready for review

#13461 [onert] Add generating training usedefs for Softmax op
  runtime/onert/core/src/ir/train/UseDefGenerator.cc
  runtime/onert/core/src/ir/train/UseDefGenerator.h
Labels: PR/ready for review

#13493 [fm-equalize] Introduce fm-equalize
  compiler/fm-equalize/CMakeLists.txt
  compiler/fm-equalize/README.md
  compiler/fm-equalize/fm-equalize
  compiler/fm-equalize/fmelib/ComputeParam.py
  compiler/fm-equalize/fmelib/__init__.py
  compiler/fm-equalize/requires.cmake
  compiler/fm-equalize/test/__init__.py
  compiler/fm-equalize/test/testComputeParam.py
Labels: PR/ready for review

#13497 [onert] Remove backend layout config
  infra/scripts/test_ubuntu_runtime_mixed.sh
  runtime/onert/backend/acl_cl/Config.cc
  runtime/onert/backend/acl_neon/Config.cc
  runtime/onert/core/include/util/Config.lst
Labels: PR/ready for review

#13498 [onert] Remove layout usage in basic tensor
  runtime/onert/backend/train/BackendContext.cc
  runtime/onert/backend/train/Tensor.h
  runtime/onert/backend/train/TensorBuilder.cc
  runtime/onert/backend/train/TensorBuilder.h
  runtime/onert/backend/train/ops/BinaryArithmeticLayer.cc
  runtime/onert/backend/train/ops/ConvolutionLayer.cc
  runtime/onert/backend/train/ops/DepthwiseConvolutionLayer.cc
  runtime/onert/backend/train/ops/FullyConnectedLayer.cc
  runtime/onert/backend/train/ops/PoolLayer.cc
  runtime/onert/core/include/backend/basic/BackendContextHelpers.h
  runtime/onert/core/include/backend/basic/DynamicTensorManager.h
  runtime/onert/core/include/backend/basic/StaticTensorManager.h
  runtime/onert/core/include/backend/basic/Tensor.h
  runtime/onert/core/include/backend/basic/TensorBuilder.h
  runtime/onert/core/include/backend/basic/train/TrainableBackendContextHelpers.h
  runtime/onert/core/include/backend/basic/train/TrainableTensor.h
  runtime/onert/core/src/backend/basic/DynamicTensorManager.cc
  runtime/onert/core/src/backend/basic/StaticTensorManager.cc
  runtime/onert/core/src/backend/basic/TensorBuilder.cc
  runtime/onert/core/src/backend/builtin/IOTensor.cc
  runtime/onert/core/src/backend/builtin/IOTensor.h
  runtime/onert/core/src/backend/builtin/TensorBuilder.cc
  runtime/onert/core/src/backend/builtin/TensorBuilder.h
  runtime/onert/core/src/backend/builtin/kernel/WhileLayer.cc
  runtime/onert/core/src/compiler/ExecutorFactory.cc
Labels: PR/ready for review

#13501 [format] Add fm-equalize
  infra/command/format
Labels: PR/ready for review

#13471 [onert] Plan trainable tensors on train backend
  runtime/onert/backend/train/TensorPlanner.cc
Labels: PR/ready for review

#13496 [onert] Use structured binding declaration in optimizers
  runtime/onert/backend/train/optimizer/Adam.cc
  runtime/onert/backend/train/optimizer/SGD.cc
Labels: PR/ready for review

#13510 [onert/test] Report unittest result
  infra/scripts/test_ubuntu_runtime_mixed.sh
Labels: PR/ready for review

#13476 [onert] Add notifyBackwardLastUse() to TensorBuilder
  runtime/onert/backend/train/TensorBuilder.cc
  runtime/onert/backend/train/TensorBuilder.h
Labels: PR/ready for review

#13516 [onert] Remove unused ConstantInitializer
  runtime/onert/core/src/backend/builtin/ConstantInitializer.h
Labels: PR/ready for review, approval: 1

#13512 [onert] Introduce Bias_Op cpu kernel
  compute/cker/include/cker/eigen/bias_op.h
Labels: PR/ready for review

#13502 [luci] Add RELU in RemoveUnnecessaryReshapeNetPass
  compiler/luci/pass/src/RemoveUnnecessaryReshapeNetPass.cpp
Labels: PR/ready for review

#13519 [onert] Remove backend layout checking in KernelGenerator
  runtime/onert/backend/cpu/KernelGenerator.cc
Labels: PR/ready for review

#13499 [onert] Use structured binding for pair
  runtime/onert/backend/acl_common/AclConstantInitializer.h
  runtime/onert/backend/acl_common/AclTensorBuilder.h
  runtime/onert/backend/cl_common/src/LifetimeMap.cc
  runtime/onert/backend/train/MemoryPlanner.cc
  runtime/onert/backend/train/TensorManager.cc
  runtime/onert/backend/train/TensorPlanner.cc
  runtime/onert/core/include/backend/basic/BackendContextHelpers.h
  runtime/onert/core/include/backend/train/ITensorRegistry.h
  runtime/onert/core/include/compiler/BackendResolver.h
  runtime/onert/core/include/ir/Model.h
  runtime/onert/core/include/util/ObjectManager.h
  runtime/onert/core/src/backend/basic/MemoryPlanner.cc
  runtime/onert/core/src/backend/basic/StaticTensorManager.cc
  runtime/onert/core/src/compiler/Compiler.cc
  runtime/onert/core/src/compiler/CompilerHelpers.h
  runtime/onert/core/src/compiler/ExecutorFactory.cc
  runtime/onert/core/src/compiler/ManualScheduler.cc
  runtime/onert/core/src/compiler/StaticShapeInferer.cc
  runtime/onert/core/src/compiler/TensorRegistries.h
  runtime/onert/core/src/compiler/train/TrainingCompiler.cc
  runtime/onert/core/src/dumper/dot/DotBuilder.cc
  runtime/onert/core/src/exec/DataflowExecutor.cc
  runtime/onert/core/src/exec/JSONExecTime.cc
  runtime/onert/core/src/exec/MinMaxData.cc
  runtime/onert/core/src/exec/MinMaxRecorder.cc
  runtime/onert/core/src/exec/MultiModelExecutors.cc
  runtime/onert/core/src/ir/train/TrainableGraph.cc
  runtime/onert/core/src/ir/verifier/Verifier.cc
  runtime/onert/core/src/util/ChromeTracingEventWriter.cc
  runtime/onert/core/src/util/ConfigSource.cc
  runtime/onert/core/src/util/MDTableEventWriter.cc
  runtime/onert/core/src/util/SNPEEventWriter.cc
  runtime/onert/core/src/util/ShapeInference.cc
Labels: PR/ready for review

#13462 [onert] Apply usedef chains for training
  runtime/onert/core/include/ir/train/TrainableGraph.h
  runtime/onert/core/src/compiler/ExecutorFactory.cc
  runtime/onert/core/src/compiler/train/TrainingCompiler.cc
  runtime/onert/core/src/ir/train/TrainableGraph.cc
Labels: PR/ready for review

#13524 [oenrt] Remove supportLayout function in backend config
  runtime/onert/backend/acl_cl/Config.cc
  runtime/onert/backend/acl_cl/Config.h
  runtime/onert/backend/acl_neon/Config.cc
  runtime/onert/backend/acl_neon/Config.h
  runtime/onert/backend/cpu/Config.cc
  runtime/onert/backend/cpu/Config.h
  runtime/onert/backend/ruy/Config.cc
  runtime/onert/backend/ruy/Config.h
  runtime/onert/backend/train/Config.cc
  runtime/onert/backend/train/Config.h
  runtime/onert/backend/trix/Config.cc
  runtime/onert/backend/trix/Config.h
  runtime/onert/backend/xnnpack/Config.cc
  runtime/onert/backend/xnnpack/Config.h
  runtime/onert/core/include/backend/IConfig.h
  runtime/onert/core/src/backend/builtin/Config.cc
  runtime/onert/core/src/backend/builtin/Config.h
  runtime/onert/core/src/compiler/HEScheduler.test.cc
  runtime/onert/core/src/compiler/LoweredGraph.cc
  runtime/onert/core/src/compiler/train/LoweredTrainableGraph.cc
  runtime/onert/core/src/exec/ExecTime.test.cc
Labels: PR/ready for review

#13518 [onert] Use Eigen in ReLU6 cker
  compute/cker/include/cker/operation/ReLU6.h
  runtime/onert/backend/cpu/ops/ElementwiseActivationLayer.cc
Labels: PR/ready for review

#13517 [onert] Introduce TrainableConstantInsertionPass
  runtime/onert/core/src/compiler/train/LoweredTrainableGraph.cc
  runtime/onert/core/src/compiler/train/pass/TrainableConstantInsertionPass.cc
  runtime/onert/core/src/compiler/train/pass/TrainableConstantInsertionPass.h
Labels: PR/ready for review

#13535 [onert] Add assertion to ReLU6
  compute/cker/include/cker/operation/ReLU6.h
Labels: PR/ready for review, approval: 1

#13522 [onert] Plan back-propagated tensors on train backend
  runtime/onert/backend/train/TensorPlanner.cc
Labels: PR/ready for review

#13523 [onert] Plan gradient tensors on train backend
  runtime/onert/backend/train/TensorPlanner.cc
Labels: PR/ready for review

#13537 [onert] Introduce LaunchDepthwiseConvOp cpu kernel
  compute/cker/include/cker/eigen/depthwise_conv_op.h
Labels: PR/ready for review

#13540 [onert] Set dilation factor in DepthwiseConv train kernel
  compute/cker/include/cker/train/operation/DepthwiseConv.h
  runtime/onert/backend/train/ops/DepthwiseConvolutionLayer.cc
Labels: PR/ready for review

#13538 [infra/onert] Remove unused debian build dependency
  infra/debian/runtime/control
Labels: PR/ready for review, approval: 1

#13539 [onert] Remove setLayout in graph
  runtime/onert/core/include/ir/Graph.h
  runtime/onert/core/include/ir/train/TrainableGraph.h
  runtime/onert/core/src/compiler/ExecutorFactory.cc
  runtime/onert/core/src/ir/train/TrainableGraph.cc
  runtime/onert/core/src/loader/CircleLoader.cc
  runtime/onert/loader/trix/TrixLoader.cc
Labels: PR/ready for review

#13544 [onert] Fix typo
  runtime/onert/backend/train/TensorPlanner.cc
Labels: PR/ready for review

#13541 [onert] Remove frontend layout usage in ACL backend
  runtime/onert/backend/acl_cl/ConstantInitializer.cc
  runtime/onert/backend/acl_cl/KernelGenerator.cc
  runtime/onert/backend/acl_cl/KernelGenerator.h
  runtime/onert/backend/acl_cl/Optimizer.cc
  runtime/onert/backend/acl_common/AclBackendContext.h
  runtime/onert/backend/acl_common/AclConstantInitializer.cc
  runtime/onert/backend/acl_common/AclConstantInitializer.h
  runtime/onert/backend/acl_common/AclKernelGen.h
  runtime/onert/backend/acl_common/AclSubTensorAnalyzer.h
  runtime/onert/backend/acl_common/AclTensorBuilder.h
  runtime/onert/backend/acl_common/Convert.cc
  runtime/onert/backend/acl_common/Convert.h
  runtime/onert/backend/acl_common/Swizzle.h
  runtime/onert/backend/acl_neon/KernelGenerator.cc
  runtime/onert/backend/acl_neon/KernelGenerator.h
  runtime/onert/backend/acl_neon/Optimizer.cc
  runtime/onert/backend/cl_common/include/cl_common/BackendContext.h
  runtime/onert/backend/cl_common/include/cl_common/ParentInfo.h
Labels: PR/ready for review

#13543 [onert] Remove frontend layout usage in non-ACL backend
  runtime/onert/backend/cpu/KernelGenerator.cc
  runtime/onert/backend/cpu/KernelGenerator.h
  runtime/onert/backend/cpu/ops/OperationUtils.h
  runtime/onert/backend/ruy/KernelGenerator.cc
  runtime/onert/backend/ruy/KernelGenerator.h
  runtime/onert/backend/train/BackendContext.cc
  runtime/onert/backend/train/KernelGenerator.cc
  runtime/onert/backend/train/KernelGenerator.h
  runtime/onert/backend/trix/KernelGenerator.cc
  runtime/onert/backend/trix/KernelGenerator.h
  runtime/onert/backend/xnnpack/KernelGenerator.cc
  runtime/onert/backend/xnnpack/KernelGenerator.h
Labels: PR/ready for review

#13545 [nnfw_tests] Move a test from wrong location
  tests/nnfw_api/src/GenModelTests/BranchModelTrain.test.cc
Labels: PR/ready for review

#13556 [github] Introduce android build test
  .github/workflows/run-onert-android-build.yml
Labels: PR/NO TEST, PR/ready for review

#13553 [onert] Implement notifyLastUse in training TensorBuilder
  runtime/onert/backend/train/TensorBuilder.cc
Labels: PR/ready for review

#13547 [onert] Add unit tests for UseDefGenerator
  runtime/onert/core/src/ir/train/UseDefGenerator.test.cc
Labels: PR/ready for review

#13552 [onert] Plan disposable tensors on train backend
  runtime/onert/backend/train/TensorPlanner.cc
  runtime/onert/backend/train/TensorPlanner.h
Labels: PR/ready for review

#13560 [onert] Remove layout in graph
  runtime/onert/core/include/backend/basic/BackendContextHelpers.h
  runtime/onert/core/include/backend/basic/train/TrainableBackendContextHelpers.h
  runtime/onert/core/include/ir/Graph.h
  runtime/onert/core/include/ir/train/TrainableGraph.h
  runtime/onert/core/include/util/ShapeInference.h
  runtime/onert/core/src/compiler/ExecutorFactory.cc
  runtime/onert/core/src/compiler/LoweredGraph.cc
  runtime/onert/core/src/compiler/ShapeValidator.cc
  runtime/onert/core/src/compiler/StaticShapeInferer.cc
  runtime/onert/core/src/compiler/pass/PermutationOperationPass.cc
  runtime/onert/core/src/compiler/train/LoweredTrainableGraph.cc
  runtime/onert/core/src/util/ShapeInference.cc
Labels: PR/ready for review

#13562 [onert/onert_train] Use arser for onert_train
  tests/tools/onert_train/CMakeLists.txt
  tests/tools/onert_train/src/args.cc
  tests/tools/onert_train/src/args.h
  tests/tools/onert_train/src/onert_train.cc
Labels: PR/ready for review

#13549 [onert/onert_run] Use arser for onert_run
  tests/tools/onert_run/CMakeLists.txt
  tests/tools/onert_run/src/args.cc
  tests/tools/onert_run/src/args.h
  tests/tools/onert_run/src/onert_run.cc
Labels: PR/ready for review

#13566 [onert] Simplfy asFeature
  runtime/onert/backend/acl_cl/KernelGenerator.cc
  runtime/onert/backend/acl_common/AclKernelGen.h
  runtime/onert/backend/acl_neon/KernelGenerator.cc
  runtime/onert/backend/cpu/KernelGenerator.cc
  runtime/onert/backend/cpu/ops/ConvolutionLayer.cc
  runtime/onert/backend/ruy/KernelGenerator.cc
  runtime/onert/backend/ruy/ops/ConvolutionLayer.cc
  runtime/onert/backend/train/KernelGenerator.cc
  runtime/onert/backend/xnnpack/KernelGenerator.cc
  runtime/onert/core/include/ir/Shape.h
  runtime/onert/core/src/compiler/ShapeValidator.cc
  runtime/onert/core/src/ir/Shape.cc
  runtime/onert/core/src/util/ShapeInference.cc
  runtime/onert/core/src/util/ShapeInference.test.cc
Labels: PR/ready for review, approval: 1
