Repository Samsung/ONE, pull requests merged in 2024-03, with the labels that each got.

#12714 [tools/onert_train] Add onert_train usage example to readme
  tests/tools/onert_train/README.md
Labels: approval: 2

#12705 [onert] Force bias rank to 1 and fix GenModelTests
  runtime/onert/core/src/compiler/ShapeValidator.cc
  runtime/onert/core/src/compiler/ShapeValidator.h
  tests/nnfw_api/src/GenModelTests/one_op_tests/Conv2D.test.cc
  tests/nnfw_api/src/GenModelTests/one_op_tests/DepthwiseConv2D.test.cc
Labels: PR/ready for review, approval: 2

#12703 [onert/lib] Update circle_traininfo schema
  runtime/libs/circle-schema/include/circle_traininfo.fbs
  runtime/libs/circle-schema/include/circle_traininfo_generated.h
Labels: approval: 2

#12719 [mio-circle08] Introduce mio-circle for v0.8
  compiler/mio-circle08/CMakeLists.txt
  compiler/mio-circle08/README.md
  compiler/mio-circle08/example.cpp
  compiler/mio-circle08/include/mio_circle/Helper.h
  compiler/mio-circle08/include/mio_circle/Reader.h
  compiler/mio-circle08/src/Helper.cpp
  compiler/mio-circle08/src/Helper.test.cpp
  compiler/mio-circle08/src/Reader.cpp
  compiler/mio-circle08/src/Reader.test.cpp
Labels: approval: 2

#12718 [onert] Strip installed libraries
  runtime/onert/api/python/CMakeLists.txt
  runtime/onert/loader/trix/CMakeLists.txt
  runtime/onert/odc/CMakeLists.txt
  runtime/service/npud/backend/trix/CMakeLists.txt
Labels: PR/ready for review

#12712 [onert-micro] Add Pack kernel
  onert-micro/onert-micro/include/test_models/pack/PackKernel.h
  onert-micro/onert-micro/include/test_models/pack/TestDataPackBase.h
  onert-micro/onert-micro/src/execute/kernels/Pack.cpp
  onert-micro/onert-micro/src/execute/kernels/tests/Pack.test.cpp
  onert-micro/onert-micro/src/import/kernels/Pack.cpp
Labels: approval: 2

#12711 [onert-micro] Add Gather kernel
  onert-micro/onert-micro/include/test_models/gather/FloatGatherKernel.h
  onert-micro/onert-micro/include/test_models/gather/IntGatherKernel.h
  onert-micro/onert-micro/include/test_models/gather/NegGatherKernel.h
  onert-micro/onert-micro/include/test_models/gather/TestDataGatherBase.h
  onert-micro/onert-micro/src/execute/kernels/Gather.cpp
  onert-micro/onert-micro/src/execute/kernels/tests/Gather.test.cpp
  onert-micro/onert-micro/src/import/kernels/Gather.cpp
Labels: approval: 2

#12709 [onert-micro] Add Reshape
  onert-micro/onert-micro/include/test_models/reshape/ReshapeKernel.h
  onert-micro/onert-micro/src/execute/kernels/Reshape.cpp
  onert-micro/onert-micro/src/execute/kernels/tests/Reshape.test.cpp
  onert-micro/onert-micro/src/import/kernels/Reshape.cpp
Labels: approval: 2

#12710 [onert-micro] Add Shape kernel
  onert-micro/onert-micro/include/test_models/shape/NegShapeKernel.h
  onert-micro/onert-micro/include/test_models/shape/ShapeKernel.h
  onert-micro/onert-micro/src/execute/kernels/Shape.cpp
  onert-micro/onert-micro/src/execute/kernels/tests/Shape.test.cpp
  onert-micro/onert-micro/src/import/kernels/Shape.cpp
Labels: approval: 2

#12598 [luci/lang] Add CircleGRU node
  compiler/luci/lang/include/luci/IR/CircleNodes.h
  compiler/luci/lang/include/luci/IR/CircleNodes.lst
  compiler/luci/lang/include/luci/IR/Nodes/CircleGRU.h
  compiler/luci/lang/src/Nodes/CircleGRU.test.cpp
Labels: approval: 2

#12747 [luci/export] Support GRU operation
  compiler/luci/export/src/CircleBuiltinTypesExtractor.h
  compiler/luci/export/src/CircleOps.lst
Labels: approval: 2

#12746 [circlechef] Support GRU operation
  compiler/circlechef/circle/src/CircleOpChefs.h
  compiler/circlechef/circle/src/CircleOpRegistry.h
  compiler/circlechef/circle/src/Op/GRU.cpp
  compiler/circlechef/circle/src/Op/GRU.h
  compiler/circlechef/core/src/Op/GRU.cpp
  compiler/circlechef/core/src/Op/GRU.h
  compiler/circlechef/core/src/OpChef.def
  compiler/circlechef/core/src/OpChefs.h
  compiler/circlechef/proto/circlechef.proto
Labels: approval: 2

#12755 [tflchef] Support int4 datatype
  compiler/tflchef/core/src/Convert.cpp
  compiler/tflchef/core/src/DataChef.def
  compiler/tflchef/core/src/ModelChef.cpp
  compiler/tflchef/proto/tflchef.proto
  compiler/tflchef/tests/short_int4/test.recipe
  compiler/tflchef/tests/short_int4_quant/test.recipe
Labels: approval: 2

#12749 [onert-micro] Add StridedSlice
  onert-micro/onert-micro/include/pal/common/PALStridedSlice.h
  onert-micro/onert-micro/include/test_models/strided_slice/StridedSliceKernel.h
  onert-micro/onert-micro/src/execute/kernels/StridedSlice.cpp
  onert-micro/onert-micro/src/execute/kernels/tests/StridedSlice.test.cpp
  onert-micro/onert-micro/src/import/kernels/StridedSlice.cpp
Labels: approval: 2

#12761 [souschef] Introduce DataChef for INT4, UINT4
  compiler/souschef/include/souschef/Data/Constant.h
  compiler/souschef/include/souschef/Data/Explicit.h
  compiler/souschef/src/Explicit.cpp
Labels: approval: 2

#12760 [circlechef] Support INT4/UINT4 data type
  compiler/circlechef/circle/src/Convert.cpp
  compiler/circlechef/core/src/Convert.cpp
  compiler/circlechef/core/src/Convert.test.cpp
  compiler/circlechef/core/src/DataChef.def
  compiler/circlechef/core/src/ModelChef.cpp
  compiler/circlechef/proto/circlechef.proto
  compiler/circlechef/tests/int4_datatype/test.recipe
  compiler/circlechef/tests/uint4_datatype/test.recipe
Labels: approval: 2

#12762 [onert/lib] Remove a sync line from circle_traininfo schema
  runtime/libs/circle-schema/include/circle_traininfo.fbs
Labels: PR/ready for review, approval: 2

#12754 [loco] Support S4/U4 for int4/uint4 data type
  compiler/loco/include/loco/IR/DataType.h
  compiler/loco/include/loco/IR/DataTypeTraits.h
  compiler/loco/src/Service/TypeInference.test.cpp
Labels: approval: 2

#12791 [luci] Support INT4/UINT4
  compiler/luci/export/src/CircleExporterUtils.cpp
  compiler/luci/export/src/CircleTensorExporter.cpp
  compiler/luci/import/src/CircleReader.cpp
  compiler/luci/import/src/Nodes/CircleConst.cpp
  compiler/luci/lang/src/Nodes/CircleConst.cpp
  compiler/luci/logex/src/CircleNodeSummaryBuilders.cpp
  compiler/luci/pass/src/RemoveDuplicateConstPass.cpp
  compiler/luci/pass/src/ResolveCustomOpAddPass.cpp
  compiler/luci/pass/src/helpers/Strings.cpp
  compiler/luci/pass/src/helpers/Strings.test.cpp
  compiler/luci/service/src/Nodes/CircleConst.cpp
  compiler/luci/service/src/Nodes/CircleConst.test.cpp
Labels: approval: 2

#12807 [luci/pass] Support s4/u4 in FoldDequantizePass
  compiler/luci/pass/src/FoldDequantizePass.cpp
  compiler/luci/pass/src/FoldDequantizePass.test.cpp
Labels: area/quant

#12808 [luci/pass] Quantize const input of SelectV2
  compiler/luci/pass/src/QuantizeActivation.cpp
  compiler/luci/pass/src/QuantizeActivation.h
Labels: area/quant

#12810 [luci/pass] Introduce QuantizeWithPredecessorPass
  compiler/luci/pass/src/QuantizeWithPredecessorPass.cpp
  compiler/luci/pass/src/QuantizeWithPredecessorPass.h
  compiler/luci/pass/src/QuantizeWithPredecessorPass.test.cpp
Labels: area/quant

#12809 [luci/pass] Introduce QuantizeOnnxQDQPass
  compiler/luci/pass/src/QuantizationUtils.cpp
  compiler/luci/pass/src/QuantizationUtils.h
  compiler/luci/pass/src/QuantizeOnnxQDQPass.cpp
  compiler/luci/pass/src/QuantizeOnnxQDQPass.h
  compiler/luci/pass/src/QuantizeOnnxQDQPass.test.cpp
Labels: area/quant

#12812 [luci/pass] Introduce QuantizeOnnxDequantizeLinearPass
  compiler/luci/pass/src/QuantizeOnnxDequantizeLinearPass.cpp
  compiler/luci/pass/src/QuantizeOnnxDequantizeLinearPass.h
  compiler/luci/pass/src/QuantizeOnnxDequantizeLinearPass.test.cpp
Labels: area/quant

#12813 [luci/pass] Introduce QuantizeOnnxFakeQuantModelPass
  compiler/luci/pass/include/luci/Pass/QuantizeOnnxFakeQuantModelPass.h
  compiler/luci/pass/src/QuantizeOnnxFakeQuantModelPass.cpp
  compiler/luci/pass/src/QuantizeOnnxFakeQuantModelPass.test.cpp
Labels: area/quant

#12815 [luci] Add INT4 weights quantization to quantizer
  compiler/luci/pass/src/QuantizationUtils.cpp
  compiler/luci/pass/src/QuantizationUtils.h
  compiler/luci/pass/src/QuantizeWeightsOnly.cpp
Labels: area/quant
