Repository Samsung/ONE, pull requests merged in 2024-09, with the labels that each got.

#13862 [luci] Migrate helperPads to ShapeInferenceHelper
  compiler/luci/service/src/CircleShapeInferenceHelper.cpp
  compiler/luci/service/src/CircleShapeInferenceHelper.h
  compiler/luci/service/src/HelperPads.h
  compiler/luci/service/src/Nodes/CirclePad.cpp
Labels: PR/ready for review, SSAFY

#13855 [arser] Fix build fail on gcc 13
  compiler/arser/include/arser/arser.h
Labels: PR/ready for review

#13861 [onert] Add lifetime enum to LayerScopeTensor
  runtime/onert/core/include/backend/train/LayerScopeTensor.h
Labels: PR/ready for review

#13887 [onert] Bump up to 1.30.0
  docs/conf.py
  packaging/nnfw.spec
  runtime/contrib/android/api/build.gradle
  runtime/onert/api/nnfw/include/nnfw_version.h
Labels: PR/ready for review

#13882 [onert/cross] Update rootfs script and document
  docs/howto/how-to-cross-build-runtime-for-arm.md
  tools/cross/install_rootfs.sh
Labels: PR/ready for review

#13886 [onert] Support block quantization operand size calculation
  runtime/onert/core/include/ir/OperandInfo.h
  runtime/onert/core/src/ir/DataType.cc
  runtime/onert/core/src/ir/OperandInfo.cc
  runtime/onert/core/src/ir/OperandInfo.test.cc
Labels: PR/ready for review

#13884 [onert] Support block quantization in CircleLoader
  runtime/onert/core/src/loader/BaseLoader.h
  runtime/onert/core/src/loader/CircleLoader.cc
Labels: PR/ready for review

#13472 [onert] Change core install path
  compute/ARMComputeEx/CMakeLists.txt
  infra/debian/runtime/onert.install
  packaging/nnfw.spec
  runtime/onert/api/nnapi/CMakeLists.txt
  runtime/onert/api/nnfw/CMakeLists.txt
  runtime/onert/backend/acl_cl/CMakeLists.txt
  runtime/onert/backend/acl_neon/CMakeLists.txt
  runtime/onert/backend/cpu/CMakeLists.txt
  runtime/onert/backend/ruy/CMakeLists.txt
  runtime/onert/backend/train/CMakeLists.txt
  runtime/onert/backend/trix/CMakeLists.txt
  runtime/onert/backend/xnnpack/CMakeLists.txt
  runtime/onert/core/CMakeLists.txt
  runtime/onert/loader/trix/CMakeLists.txt
  runtime/onert/odc/CMakeLists.txt
Labels: PR/ready for review

#13815 [onert] Export tensor and optimizer data to the checkpoint file
  runtime/onert/core/src/exporter/train/CheckpointExporter.cc
Labels: PR/ready for review

#13892 [onert] Templatize memory planners in train backend
  runtime/onert/backend/train/DisposableTensorIndex.h
  runtime/onert/backend/train/MemoryPlanner.cc
  runtime/onert/backend/train/MemoryPlanner.h
  runtime/onert/backend/train/MemoryPlanner.test.cc
  runtime/onert/backend/train/MemoryPlannerFactory.cc
Labels: PR/ready for review

#13931 [onert] Use getUses() copy instead of reference
  runtime/onert/core/src/compiler/train/pass/TrainableConstantInsertionPass.cc
  runtime/onert/core/src/ir/train/UseDefGenerator.cc
Labels: PR/ready for review

#13933 [onert/lib] Move NNAPI header files
  .ahub/sam/exclude.txt
  runtime/nnapi-header/CMakeLists.txt
  runtime/onert/api/nnapi/CMakeLists.txt
  runtime/onert/api/nnapi/include/NeuralNetworks.h
  runtime/onert/api/nnapi/include/NeuralNetworksEx.h
  runtime/onert/api/nnapi/include/NeuralNetworksExtensions.h
  runtime/onert/api/nnfw/CMakeLists.txt
  tests/custom_op/CMakeLists.txt
  tests/libs/nnapi/CMakeLists.txt
Labels: PR/ready for review

#13922 [luci/service] Migrate Neg shape inference rule to sinf::Algorithm
  compiler/luci/service/include/luci/Service/CircleShapeInference.h
  compiler/luci/service/src/CircleShapeInferenceRule.cpp
  compiler/luci/service/src/Nodes/CircleNeg.cpp
  compiler/luci/service/src/Nodes/CircleNeg.test.cpp
Labels: PR/ready for review, SSAFY

#13929 [onert] Introduce NUM_THREADS config
  runtime/onert/backend/cpu/ExternalContext.h
  runtime/onert/backend/ruy/ExternalContext.h
  runtime/onert/backend/xnnpack/BackendContext.h
  runtime/onert/core/include/util/Config.lst
  runtime/onert/core/src/backend/builtin/ExternalContext.h
  tools/stab/backend_scheduler.py
  tools/stab/remote.py
Labels: PR/ready for review

#13943 [res] Update operand name of Gather_SparseToDense_AddV2 recipe
  res/TensorFlowLiteRecipes/Net_Gather_SparseToDense_AddV2_000/test.recipe
Labels: PR/ready for review, approval: 1

#13945 [luci] Fix overflow warning
  compiler/luci/export/src/CircleExporterUtils.h
Labels: PR/ready for review

#13948 [res] Fix Net_Gather_SparseToDense_AddV2_000 recipe
  res/TensorFlowLiteRecipes/Net_Gather_SparseToDense_AddV2_000/test.recipe
Labels: PR/ready for review

#13930 [nnpackage] Update circle schema
  nnpackage/schema/circle_schema.fbs
Labels: PR/ready for review

#13947 [onert/test] Move NNAPI test header
  tests/libs/nnapi/CMakeLists.txt
  tests/nnapi/CMakeLists.txt
  tests/nnapi/include/NeuralNetworksExShim.h
  tests/nnapi/include/NeuralNetworksLoadHelpers.h
  tests/nnapi/include/NeuralNetworksShim.h
  tests/nnapi/include/NeuralNetworksTypes.h
Labels: PR/ready for review, approval: 1

#13946 [onert] Fix warnings in checkpoint loader and exporter
  runtime/onert/core/src/exporter/train/CheckpointExporter.cc
  runtime/onert/core/src/loader/train/CheckpointLoader.cc
Labels: PR/ready for review

#13954 [onert] Apply updated quant name to schema header
  runtime/libs/circle-schema/include/circle_schema_generated.h
  runtime/onert/core/src/loader/CircleLoader.cc
Labels: PR/ready for review, approval: 1

#13955 [luci/service] Migrate StridedSlice shape inference rule
  compiler/luci/service/include/luci/Service/CircleShapeInference.h
  compiler/luci/service/src/CircleShapeInferenceRule.cpp
  compiler/luci/service/src/Nodes/CircleStridedSlice.cpp
  compiler/luci/service/src/ShapeInfer_StridedSlice.cpp
  compiler/luci/service/src/ShapeInfer_StridedSlice.h
Labels: PR/ready for review, SSAFY

#13958 [luci/service] Remove Unintended Changes for StridedSlice
  compiler/luci/service/src/Nodes/CircleStridedSlice.cpp
Labels: PR/ready for review, SSAFY

#13918 [onert] Load tensor and optimizer data from the checkpoint file
  runtime/onert/core/src/loader/train/CheckpointLoader.cc
Labels: PR/ready for review

#13944 [cker] Fix computing MSE Gradient
  compute/cker/include/cker/train/Types.h
  compute/cker/include/cker/train/operation/Loss.h
  compute/cker/src/train/Loss.test.cc
  runtime/onert/backend/train/KernelGenerator.cc
  runtime/onert/backend/train/ops/LossCategoricalCrossentropyLayer.cc
  runtime/onert/backend/train/ops/LossCategoricalCrossentropyLayer.h
  runtime/onert/backend/train/ops/LossLayer.cc
  runtime/onert/backend/train/ops/LossLayer.h
  runtime/onert/backend/train/ops/LossMeanSquaredErrorLayer.cc
  runtime/onert/backend/train/ops/LossMeanSquaredErrorLayer.h
  runtime/onert/backend/train/ops/OperationUtils.cc
  runtime/onert/backend/train/ops/OperationUtils.h
Labels: PR/ready for review

#13957 [onert] Change NNAPI library type
  runtime/onert/api/nnapi/CMakeLists.txt
  runtime/onert/api/nnapi/compilation.cc
  runtime/onert/api/nnapi/execution.cc
  runtime/onert/api/nnapi/model.cc
  tests/nnapi/CMakeLists.txt
  tests/nnapi/include/NeuralNetworksWrapper.h
Labels: PR/ready for review

#13960 [infra/onert] Make flatbuffers library static explicitly
  infra/nnfw/cmake/packages/FlatBuffers-23.5.26/FlatBuffersConfig.cmake
Labels: PR/ready for review

#13966 [one-cmds] Add missing comma
  compiler/one-cmds/onelib/constant.py
Labels: PR/ready for review

#13963 [fme-apply] Fix build fail on gcc 13
  compiler/fme-apply/src/RandomString.h
Labels: PR/ready for review

#13962 [onert/android] Update lib path
  runtime/contrib/android/api/Prebuilt.mk
Labels: PR/ready for review

#13938 [cker] Introduce CategoricalCrossEntropyWithLogits
  compute/cker/include/cker/eigen/xent_op.h
  compute/cker/include/cker/operation/Helper/Tensor.h
  compute/cker/include/cker/train/operation/Loss.h
  compute/cker/src/train/Loss.test.cc
Labels: PR/ready for review

#13970 [res] Add some test networks
  res/TensorFlowLiteRecipes/Conv2D_007/test.recipe
  res/TensorFlowLiteRecipes/Conv2D_007/test.reverse
  res/TensorFlowLiteRecipes/FullyConnected_010/test.recipe
  res/TensorFlowLiteRecipes/FullyConnected_010/test.reverse
  res/TensorFlowLiteRecipes/Net_Conv_Gelu_000/test.recipe
  res/TensorFlowLiteRecipes/Net_Conv_Pad_000/test.recipe
  res/TensorFlowLiteRecipes/Net_Conv_TConv_000/test.recipe
  res/TensorFlowLiteRecipes/Net_Conv_TConv_000/test.reverse
  res/TensorFlowLiteRecipes/Net_DConv_Conv_000/test.recipe
  res/TensorFlowLiteRecipes/Net_DConv_Conv_000/test.reverse
  res/TensorFlowLiteRecipes/Net_FullyConnected_Gelu_000/test.recipe
  res/TensorFlowLiteRecipes/Net_FullyConnected_Gelu_000/test.reverse
  res/TensorFlowLiteRecipes/Net_InstNorm_Conv_000/test.recipe
Labels: PR/ready for review

#13975 [fme-apply] Remove unused passes
  compiler/fme-apply/src/FMEqualizer.cpp
  compiler/fme-apply/src/pass/ForwardPreScalePass.cpp
  compiler/fme-apply/src/pass/ForwardPreScalePass.h
  compiler/fme-apply/src/pass/ForwardPreScalePass.test.cpp
  compiler/fme-apply/src/pass/ForwardPreShiftPass.cpp
  compiler/fme-apply/src/pass/ForwardPreShiftPass.h
  compiler/fme-apply/src/pass/ForwardPreShiftPass.test.cpp
  compiler/fme-apply/src/pass/FusePostShiftPass.cpp
  compiler/fme-apply/src/pass/FusePostShiftPass.h
  compiler/fme-apply/src/pass/FusePostShiftPass.test.cpp
  compiler/fme-apply/src/pass/FusePreShiftPass.cpp
  compiler/fme-apply/src/pass/FusePreShiftPass.h
  compiler/fme-apply/src/pass/FusePreShiftPass.test.cpp
Labels: PR/ready for review

#13949 [luci/service] Support shape inference for non-const paddings
  compiler/luci/service/src/CircleShapeInferenceHelper.cpp
  compiler/luci/service/src/CircleShapeInferenceHelper.h
  compiler/luci/service/src/Nodes/CirclePad.cpp
  compiler/luci/service/src/Nodes/CirclePad.test.cpp
Labels: PR/ready for review, SSAFY

#13969 [cker] Fix computing CCE Gradient
  compute/cker/include/cker/eigen/xent_op.h
  compute/cker/include/cker/train/operation/Loss.h
  compute/cker/src/train/Loss.test.cc
  runtime/onert/backend/train/ops/LossCategoricalCrossentropyLayer.cc
Labels: PR/ready for review

#13982 [fme-detect] Revise the way it finds patterns
  compiler/fme-detect/src/EqualizePatternFinder.cpp
  compiler/fme-detect/src/EqualizePatternFinder.test.cpp
Labels: PR/ready for review

#13984 [onert/backend] Templatize MemoryPlannerFactory in train
  runtime/onert/backend/train/MemoryManager.cc
  runtime/onert/backend/train/MemoryManager.h
  runtime/onert/backend/train/MemoryPlannerFactory.cc
  runtime/onert/backend/train/MemoryPlannerFactory.h
Labels: PR/ready for review

#13980 [onert] Add registerLayerScopeTensors to ITrainableFuntion
  runtime/onert/core/include/backend/train/LayerScopeTensor.h
  runtime/onert/core/include/exec/train/ITrainableFunction.h
Labels: PR/ready for review

#13974 [onert/backend] Refactor train/Memory.test.cc
  runtime/onert/backend/train/MemoryPlanner.test.cc
Labels: PR/ready for review

#13987 [luci/service] migrate Range shape inference rule to sinf::Algorithm
  compiler/luci/service/include/luci/Service/CircleShapeInference.h
  compiler/luci/service/src/CircleShapeInferenceRule.cpp
  compiler/luci/service/src/Nodes/CircleRange.cpp
  compiler/luci/service/src/Nodes/CircleRange.test.cpp
Labels: PR/ready for review, SSAFY

#13979 [fm-equalize] Add DumpFMEParams script
  compiler/fm-equalize/fmelib/ComputeParam.py
  compiler/fm-equalize/fmelib/DumpFMEParams.py
Labels: PR/ready for review

#13986 [fme-apply] Revise overall codes
  compiler/fme-apply/src/EqualizePattern.h
  compiler/fme-apply/src/EqualizePatternCheck.cpp
  compiler/fme-apply/src/EqualizePatternCheck.test.cpp
  compiler/fme-apply/src/EqualizePatternRead.cpp
  compiler/fme-apply/src/EqualizePatternRead.test.cpp
  compiler/fme-apply/src/FMEqualizer.cpp
  compiler/fme-apply/src/FMEqualizer.h
  compiler/fme-apply/src/InsertScaleShift.cpp
  compiler/fme-apply/src/InsertScaleShift.h
  compiler/fme-apply/src/InsertScaleShift.test.cpp
  compiler/fme-apply/src/Support.Cast.cpp
  compiler/fme-apply/src/Support.Cast.h
  compiler/fme-apply/src/Support.Cast.test.cpp
  compiler/fme-apply/src/Support.Misc.cpp
  compiler/fme-apply/src/Support.Misc.h
  compiler/fme-apply/src/Support.Misc.test.cpp
  compiler/fme-apply/src/pass/FusePostScalePass.cpp
  compiler/fme-apply/src/pass/FusePostScalePass.h
  compiler/fme-apply/src/pass/FusePostScalePass.test.cpp
  compiler/fme-apply/src/pass/FusePreScalePass.cpp
  compiler/fme-apply/src/pass/FusePreScalePass.h
  compiler/fme-apply/src/pass/FusePreScalePass.test.cpp
Labels: PR/ready for review

#13994 [onert] Move NNAPI implementation into test
  .ahub/sam/exclude.txt
  runtime/onert/api/CMakeLists.txt
  tests/libs/nnapi/CMakeLists.txt
  tests/libs/nnapi/compilation.cc
  tests/libs/nnapi/event.cc
  tests/libs/nnapi/execution.cc
  tests/libs/nnapi/include/NeuralNetworks.h
  tests/libs/nnapi/include/NeuralNetworksEx.h
  tests/libs/nnapi/include/NeuralNetworksExtensions.h
  tests/libs/nnapi/memory.cc
  tests/libs/nnapi/model.cc
  tests/libs/nnapi/wrapper/ANeuralNetworksCompilation.cc
  tests/libs/nnapi/wrapper/ANeuralNetworksCompilation.h
  tests/libs/nnapi/wrapper/ANeuralNetworksEvent.cc
  tests/libs/nnapi/wrapper/ANeuralNetworksEvent.h
  tests/libs/nnapi/wrapper/ANeuralNetworksExecution.cc
  tests/libs/nnapi/wrapper/ANeuralNetworksExecution.h
  tests/libs/nnapi/wrapper/ANeuralNetworksMemory.cc
  tests/libs/nnapi/wrapper/ANeuralNetworksMemory.h
  tests/libs/nnapi/wrapper/ANeuralNetworksModel.cc
  tests/libs/nnapi/wrapper/ANeuralNetworksModel.h
  tests/libs/nnapi/wrapper/ANeuralNetworksModel.test.cc
  tests/libs/nnapi/wrapper/NNAPIConvert.cc
  tests/libs/nnapi/wrapper/NNAPIConvert.h
  tests/libs/nnapi/wrapper/OperationFactory.cc
  tests/libs/nnapi/wrapper/OperationFactory.h
Labels: PR/ready for review

#13968 [luci/service] Support StridedSlice dynamic shape inference
  compiler/luci/service/src/Nodes/CircleStridedSlice.cpp
  compiler/luci/service/src/Nodes/CircleStridedSlice.test.cpp
Labels: PR/ready for review, SSAFY

#13989 [luci/service] Migrate reshape shape inference rule to sinf::Algorithm
  compiler/luci/service/include/luci/Service/CircleShapeInference.h
  compiler/luci/service/src/CircleShapeInferenceRule.cpp
  compiler/luci/service/src/Nodes/CircleReshape.cpp
  compiler/luci/service/src/Nodes/CircleReshape.test.cpp
Labels: PR/ready for review, SSAFY

#14000 [infra/onert] Rename onert library name
  packaging/nnfw.pc.in
  runtime/contrib/android/api/Prebuilt.mk
  runtime/onert/api/nnfw/CMakeLists.txt
Labels: PR/ready for review

#13996 [onert/backend] Remove commented code
  runtime/onert/backend/train/MemoryPlanner.test.cc
Labels: PR/ready for review, approval: 1

#14002 [luci/service] Add Assert about Shape Inference Condition for Range
  compiler/luci/service/src/Nodes/CircleRange.cpp
Labels: PR/ready for review, SSAFY

#13995 [onert/3rdparty] Introduce ggml
  runtime/3rdparty/ggml/CMakeLists.txt
  runtime/3rdparty/ggml/LICENSE
  runtime/3rdparty/ggml/README.md
  runtime/3rdparty/ggml/include/ggml.h
  runtime/3rdparty/ggml/src/CMakeLists.txt
  runtime/3rdparty/ggml/src/ggml-aarch64.c
  runtime/3rdparty/ggml/src/ggml-aarch64.h
  runtime/3rdparty/ggml/src/ggml-common.h
  runtime/3rdparty/ggml/src/ggml-impl.h
  runtime/3rdparty/ggml/src/ggml-quants.c
  runtime/3rdparty/ggml/src/ggml-quants.h
  runtime/3rdparty/ggml/src/ggml.c
Labels: PR/ready for review

#14001 [fm-equalize-value-py-test] Introduce tests
  compiler/fm-equalize-value-py-test/CMakeLists.txt
  compiler/fm-equalize-value-py-test/README.md
  compiler/fm-equalize-value-py-test/conftest.py
  compiler/fm-equalize-value-py-test/requires.cmake
  compiler/fm-equalize-value-py-test/test.lst
  compiler/fm-equalize-value-py-test/test_luci_eval.py
Labels: PR/ready for review

#14010 [luci/service] Support Range op Shape Inference for Non-const Param
  compiler/luci/service/src/Nodes/CircleRange.cpp
  compiler/luci/service/src/Nodes/CircleRange.test.cpp
Labels: PR/ready for review, SSAFY

#14006 [luci/service] Migrate logistic op to sinf::Algorithm
  compiler/luci/service/include/luci/Service/CircleShapeInference.h
  compiler/luci/service/src/CircleShapeInferenceRule.cpp
  compiler/luci/service/src/Nodes/CircleLogistic.cpp
Labels: PR/ready for review, SSAFY

#14015 [one-cmds] Add missing clean envir in tests
  compiler/one-cmds/tests/one-codegen_006.test
  compiler/one-cmds/tests/one-codegen_010.test
  compiler/one-cmds/tests/one-codegen_011.test
  compiler/one-cmds/tests/one-profile_006.test
  compiler/one-cmds/tests/one-profile_010.test
  compiler/one-cmds/tests/one-profile_011.test
  compiler/one-cmds/tests/onecc_057.test
  compiler/one-cmds/tests/onecc_neg_038.test
Labels: PR/ready for review

#14016 [luci/service] Change assert to throw exception for invalid paddings
  compiler/luci/service/src/CircleShapeInferenceHelper.cpp
  compiler/luci/service/src/Nodes/CirclePad.test.cpp
Labels: PR/ready for review, SSAFY

#14018 [one-cmds] Revise backends.py in onelib
  compiler/one-cmds/one-codegen
  compiler/one-cmds/one-profile
  compiler/one-cmds/onelib/backends.py
  compiler/one-cmds/tests/onecc_060.ini
  compiler/one-cmds/tests/onecc_neg_039.cfg
  compiler/one-cmds/tests/onecc_neg_039.ini
  compiler/one-cmds/tests/onecc_neg_039.test
Labels: PR/ready for review

#14019 [onert] Remove backend layout helper
  runtime/onert/backend/acl_common/Convert.cc
  runtime/onert/backend/acl_common/Convert.h
  runtime/onert/backend/trix/Convert.cc
  runtime/onert/backend/trix/Convert.h
Labels: PR/ready for review, approval: 1

#14021 [onert/backend] Introduce LayerScopeMemoryManager
  runtime/onert/backend/train/MemoryManager.cc
  runtime/onert/backend/train/MemoryManager.h
  runtime/onert/backend/train/TensorManager.h
Labels: PR/ready for review, approval: 2

#14017 [onert/backend] Add tests for LayerScopeTensorIndex planner
  runtime/onert/backend/train/MemoryPlanner.test.cc
Labels: PR/ready for review

#14009 [infra/onert] Bump up ARM Compute Library v24.07
  Makefile.template
  compute/ARMComputeEx/arm_compute/runtime/CL/functions/CLFullyConnectedHybridLayer.h
  compute/ARMComputeEx/arm_compute/runtime/CL/functions/CLFullyConnectedLayerEx.h
  compute/ARMComputeEx/arm_compute/runtime/CL/functions/CLPadLayerEx.h
  compute/ARMComputeEx/arm_compute/runtime/NEON/functions/NEFullyConnectedHybridLayer.h
  compute/ARMComputeEx/arm_compute/runtime/NEON/functions/NEFullyConnectedLayerEx.h
  compute/ARMComputeEx/src/runtime/CL/functions/CLDirectTransposeConvLayer.cpp
  compute/ARMComputeEx/src/runtime/CL/functions/CLFullyConnectedHybridLayer.cpp
  compute/ARMComputeEx/src/runtime/CL/functions/CLFullyConnectedLayerEx.cpp
  compute/ARMComputeEx/src/runtime/CL/functions/CLPadLayerEx.cpp
  compute/ARMComputeEx/src/runtime/CL/functions/CLTransposeConvLayer.cpp
  compute/ARMComputeEx/src/runtime/NEON/functions/NEFullyConnectedHybridLayer.cpp
  compute/ARMComputeEx/src/runtime/NEON/functions/NEFullyConnectedLayerEx.cpp
  compute/ARMComputeEx/src/runtime/NEON/functions/NEFullyConnectedReshapingLayer.cpp
  infra/cmake/packages/ARMComputeSourceConfig.cmake
  infra/nnfw/cmake/packages/ARMComputeConfig.cmake
  runtime/onert/backend/acl_cl/KernelGenerator.cc
  runtime/onert/backend/acl_neon/KernelGenerator.cc
  tests/nnapi/nnapi_gtest.skip.aarch64-android.acl_neon
  tests/nnapi/nnapi_gtest.skip.aarch64-linux.acl_neon
  tests/nnapi/nnapi_gtest.skip.armv7l-linux.acl_neon
  tests/nnfw_api/src/GenModelTests/one_op_tests/Add.test.cc
Labels: PR/ready for review

#14020 [onert/test] Introduce block quantized buffer helper
  tests/nnfw_api/CMakeLists.txt
  tests/nnfw_api/lib/common.cc
  tests/nnfw_api/lib/common.h
Labels: PR/ready for review

#14033 [luci/pass] Revise comments
  compiler/luci/pass/src/QuantizeWithMinMaxPass.cpp
Labels: trivial

#14037 [luci/service] Enhance handling CircleConst as reshape's shape
  compiler/luci/service/src/Nodes/CircleReshape.cpp
Labels: PR/ready for review, SSAFY

#14027 [onert/backend] Fix test names in MemoryPlanner.test.cc
  runtime/onert/backend/train/MemoryPlanner.test.cc
Labels: approval: 1

#14055 [logo/pass] Fix RemoveDeadNodeWithQueryPass
  compiler/logo/src/Passes/RemoveDeadNodeWithQueryPass.cpp
Labels: PR/ready for review, SSAFY

#14060 [onert] Initialize loss reduction type
  runtime/onert/backend/train/ops/LossLayer.cc
Labels: PR/ready for review, approval: 1

#14062 [infra/github] Change format check runner
  .github/workflows/check-format.yml
Labels: PR/ready for review, approval: 1

#14064 [res/tfl_recipes] Add REGRESS_Issue_13863
  res/TensorFlowLiteRecipes/REGRESS_Issue_13863/test.recipe
  res/TensorFlowLiteRecipes/REGRESS_Issue_13863/test.rule
Labels: PR/ready for review, SSAFY

#14061 [luci/service] Fix dynamic shape inference for reshape operation
  compiler/luci/service/src/Nodes/CircleReshape.cpp
  compiler/luci/service/src/Nodes/CircleReshape.test.cpp
Labels: PR/ready for review, SSAFY

#14024 [onert/backend] Add LayerScopeTensors into TensorRegistry
  runtime/onert/backend/train/TensorRegistry.h
Labels: PR/ready for review, approval: 2

#14052 [onert/cpu] Support Q4_0 Gather
  runtime/onert/backend/cpu/KernelGenerator.cc
  runtime/onert/backend/cpu/ops/GGMLHelper.cc
  runtime/onert/backend/cpu/ops/GGMLHelper.h
  runtime/onert/backend/cpu/ops/GatherLayer.cc
  runtime/onert/backend/cpu/ops/GatherLayer.h
  tests/nnfw_api/lib/CircleGen.cc
  tests/nnfw_api/lib/CircleGen.h
  tests/nnfw_api/src/GenModelTests/one_op_tests/Gather.test.cc
Labels: PR/ready for review

#14054 [onert] Check Gather operand data type
  runtime/onert/core/src/ir/OperationValidator.cc
  runtime/onert/core/src/ir/OperationValidator.h
Labels: PR/ready for review

#14067 [circle2circle] Add Dredd test for Issue_13863
  compiler/circle2circle-dredd-recipe-test/test.lst
Labels: PR/ready for review, SSAFY

#14085 [common-artifacts] Install h5py
  compiler/common-artifacts/CMakeLists.txt
Labels: PR/ready for review

#14070 [onert] Add Gather negative test
  tests/nnfw_api/src/GenModelTests/one_op_tests/Gather.test.cc
Labels: PR/ready for review, approval: 1

#14092 [circle-inspect] Introduce new circleInspect for tensor shape
  compiler/circle-inspect/driver/Driver.cpp
  compiler/circle-inspect/src/Dump.cpp
  compiler/circle-inspect/src/Dump.h
Labels: PR/ready for review, SSAFY

#14098 [dredd] Introduce new dredd rule for tensor shape
  compiler/dredd-rule-lib/README.md
  compiler/dredd-rule-lib/rule-lib.sh
Labels: PR/ready for review, SSAFY

#14113 [common-artifacts] Exclude Reshape_003 optimization test
  compiler/common-artifacts/exclude.lst
Labels: PR/ready for review, SSAFY

#14109 [res] Add TFLiteRecipe for dynamic shape pad
  res/TensorFlowLiteRecipes/Inf_Pad_000/test.recipe
  res/TensorFlowLiteRecipes/Inf_Pad_000/test.rule
Labels: PR/ready for review, SSAFY

#14117 [luci/test] Exclude Reshape_003 test
  compiler/luci/tests/test.lst
Labels: PR/ready for review, SSAFY

#14124 [circle2circle-dredd-recipe-test] Add Inf_Pad test
  compiler/circle2circle-dredd-recipe-test/test.lst
Labels: PR/ready for review, SSAFY

#14122 [circle2circle] Move comments in RmUnnecessaryTransNetPass
  compiler/luci/pass/src/RemoveUnnecessaryTransposeNetPass.cpp
Labels: approval: 1

#14129 [res] Add TFLiteRecipe for dynamic shape Quantize
  res/TensorFlowLiteRecipes/Inf_Quantize_000/test.recipe
  res/TensorFlowLiteRecipes/Inf_Quantize_000/test.rule
Labels: PR/ready for review, SSAFY

#14130 [luci] Resolve static analysis warning
  compiler/luci/service/src/Nodes/CircleStridedSlice.cpp
Labels: PR/ready for review

#14131 [luci/pass] Simplify TaggedShapeAnalyzer in RmUnnesTransNetPass
  compiler/luci/pass/src/RemoveUnnecessaryTransposeNetPass.cpp
Labels: approval: 1
