Repository Samsung/ONE, pull requests merged in 2024-05, with the labels that each got.

#12956 [debian] Revisit postinst script
  infra/debian/compiler/postinst
Labels: PR/ready for review

#12960 [luci-interpreter] Enable S32 type in SelectV2 op
  compiler/luci-interpreter/src/kernels/SelectV2.cpp
  compiler/luci-interpreter/src/kernels/SelectV2.h
  compiler/luci-interpreter/src/kernels/SelectV2.test.cpp
Labels: PR/ready for review

#12964 [debian] Fix postinst script
  infra/debian/compiler/postinst
Labels: PR/ready for review

#12944 [onert] Introduce DisposableMemoryManager into train backend
  runtime/onert/backend/train/DisposableTensorIndex.h
  runtime/onert/backend/train/MemoryManager.cc
  runtime/onert/backend/train/MemoryManager.h
  runtime/onert/backend/train/TensorManager.cc
  runtime/onert/backend/train/TensorManager.h
Labels: PR/ready for review

#12950 [onert] Change FunctionMap to unordered_map
  runtime/onert/backend/cl_common/include/cl_common/BackendContext.h
  runtime/onert/backend/cpu/BackendContext.cc
  runtime/onert/backend/gpu_cl/BackendContext.cc
  runtime/onert/backend/ruy/BackendContext.cc
  runtime/onert/backend/train/BackendContext.cc
  runtime/onert/backend/trix/BackendContext.cc
  runtime/onert/backend/xnnpack/BackendContext.cc
  runtime/onert/core/include/backend/BackendContext.h
  runtime/onert/core/include/backend/train/TrainableBackendContext.h
  runtime/onert/core/src/backend/builtin/BackendContext.cc
  runtime/onert/core/src/backend/builtin/train/BackendContext.cc
Labels: PR/ready for review

#12974 [onert] Introduce DisposableBackPropTensor into TensorBuilder
  runtime/onert/backend/train/TensorBuilder.cc
  runtime/onert/backend/train/TensorBuilder.h
Labels: PR/ready for review

#12945 [onert] Apply BackPropInitializer layer
  runtime/onert/backend/train/BackendContext.cc
  runtime/onert/backend/train/BackendContext.h
Labels: PR/ready for review

#12983 [onert] Fix quantization type setting bug
  runtime/onert/api/nnfw/src/nnfw_api_internal.cc
Labels: PR/ready for review

#12982 [tools/onert_run] Add more quantization type
  tests/tools/onert_run/src/args.cc
  tests/tools/onert_run/src/onert_run.cc
Labels: PR/ready for review

#12980 [luci-interpreter] Add a feature to infer the output shape
  compiler/luci-interpreter/include/luci_interpreter/Interpreter.h
  compiler/luci-interpreter/src/Interpreter.cpp
Labels: PR/ready for review

#12991 [luci] Quantize Square with predecessors
  compiler/luci/pass/src/QuantizeWithPredecessorPass.cpp
  compiler/luci/pass/src/QuantizeWithPredecessorPass.test.cpp
Labels: area/quant

#12995 [circle-interpreter] Use the actual output tensor size
  compiler/circle-interpreter/src/CircleInterpreter.cpp
Labels: PR/ready for review

#12993 [luci-interpreter] Change to use `luci-interface` interface
  compiler/luci-interpreter/src/Interpreter.cpp
Labels: PR/ready for review

#12977 [tools] introduce circle plus generator
  tools/circle_plus_gen/README.md
  tools/circle_plus_gen/example/sample.circle
  tools/circle_plus_gen/example/sample_tpram.circle
  tools/circle_plus_gen/lib/__init__.py
  tools/circle_plus_gen/lib/circle_plus.py
  tools/circle_plus_gen/lib/train_param.py
  tools/circle_plus_gen/lib/utils.py
  tools/circle_plus_gen/main.py
  tools/circle_plus_gen/requirements.txt
  tools/circle_plus_gen/schema/__init__.py
  tools/circle_plus_gen/schema/circle_schema_generated.py
  tools/circle_plus_gen/schema/circle_traininfo_generated.py
Labels: approval: 2

#13011 [tools/circle_plus_gen] Extend Namer to support various naming
  tools/circle_plus_gen/lib/train_param.py
  tools/circle_plus_gen/lib/utils.py
Labels: PR/ready for review, approval: 1

#13017 [infra] Update coverage exclusion rule for flatc
  infra/command/gen-coverage-report
Labels: PR/ready for review

#13015 [infra] Strip using cmake command
  Makefile.template
  infra/debian/runtime/rules
  packaging/nnfw.spec
Labels: PR/ready for review

#12976 [onert] Apply BackPropAccumulator layer
  runtime/onert/backend/train/BackendContext.cc
  runtime/onert/backend/train/BackendContext.h
  runtime/onert/backend/train/KernelGenerator.cc
  runtime/onert/backend/train/KernelGenerator.h
Labels: PR/ready for review

#13018 [runtime] Move test libs
  tests/libs/nnapi/CMakeLists.txt
  tests/libs/nnapi/include/NeuralNetworksExShim.h
  tests/libs/nnapi/include/NeuralNetworksLoadHelpers.h
  tests/libs/nnapi/include/NeuralNetworksShim.h
  tests/libs/nnapi/include/NeuralNetworksTypes.h
  tests/libs/rua/CMakeLists.txt
  tests/libs/rua/README.md
  tests/libs/rua/anchor/CMakeLists.txt
  tests/libs/rua/anchor/include/rua/Anchor.h
  tests/libs/rua/anchor/src/Anchor.cpp
  tests/libs/rua/core/CMakeLists.txt
  tests/libs/rua/core/include/rua/Service.h
  tests/libs/rua/dyn/CMakeLists.txt
  tests/libs/rua/dyn/include/rua/DynamicBinder.h
  tests/libs/rua/dyn/src/DynamicBinder.cpp
  tests/libs/rua/shim/CMakeLists.txt
  tests/libs/rua/shim/include/rua/Shim.h
  tests/libs/tflite/CMakeLists.txt
  tests/libs/tflite/include/tflite/Assert.h
  tests/libs/tflite/include/tflite/Diff.h
  tests/libs/tflite/include/tflite/InputIndex.h
  tests/libs/tflite/include/tflite/InterpreterSession.h
  tests/libs/tflite/include/tflite/RandomInputInitializer.h
  tests/libs/tflite/include/tflite/Session.h
  tests/libs/tflite/include/tflite/TensorView.h
  tests/libs/tflite/src/Diff.cpp
  tests/libs/tflite/src/RandomInputInitializer.cpp
  tests/libs/tflite/src/TensorView.test.cpp
Labels: PR/ready for review

#13024 [onert/testlib] Update tflite namespace and headers
  tests/libs/tflite/include/tflite/Diff.h
  tests/libs/tflite/include/tflite/InterpreterSession.h
  tests/libs/tflite/src/Diff.cpp
  tests/libs/tflite/src/RandomInputInitializer.cpp
Labels: PR/ready for review

#13010 [onert/odc] Prepare full quantization parameter
  runtime/onert/odc/Quantizer.cc
Labels: PR/ready for review

#13028 [infra] Remove test header from coverage
  infra/command/gen-coverage-report
Labels: PR/ready for review

#13029 [onert/test] Rename test mock header file
  runtime/onert/core/src/exec/feature/MockTensor.test.h
  runtime/onert/core/src/exec/feature/nchw/Reader.test.cc
  runtime/onert/core/src/exec/feature/nchw/View.test.cc
  runtime/onert/core/src/exec/feature/nhwc/Reader.test.cc
  runtime/onert/core/src/exec/feature/nhwc/View.test.cc
Labels: PR/ready for review

#13026 [runtime/lib] Move Accumulator class
  runtime/contrib/detection/CMakeLists.txt
  runtime/contrib/detection/detection.cpp
  runtime/contrib/mlapse/tfl/CMakeLists.txt
  runtime/contrib/mlapse/tfl/mlapse/benchmark_runner.cc
  tests/libs/benchmark/include/benchmark/Accumulator.h
  tests/tools/tflite_run/src/tflite_run.cc
Labels: PR/ready for review

#13030 [compute/acl-ex] Remove unused code
  compute/ARMComputeEx/arm_compute/core/NEON/NEElementwiseOperationFuncs.h
  compute/ARMComputeEx/arm_compute/core/NEON/kernels/NEBinaryLogicalOperationKernel.h
  compute/ARMComputeEx/arm_compute/runtime/NEON/functions/NEBinaryLogicalOperation.h
  compute/ARMComputeEx/src/core/NEON/NEElementwiseOperationFuncs.cpp
  compute/ARMComputeEx/src/core/NEON/kernels/NEBinaryLogicalOperationKernel.cpp
  compute/ARMComputeEx/src/runtime/NEON/functions/NEBinaryLogicalOperation.cpp
Labels: PR/ready for review

#13031 [onert] Introduce workspace setting API
  runtime/onert/api/nnfw/include/nnfw.h
Labels: PR/ready for review, approval: 2

#13032 [onert/test] Move RandomGenerator
  tests/libs/benchmark/CMakeLists.txt
  tests/libs/benchmark/include/benchmark/RandomGenerator.h
  tests/libs/benchmark/src/RandomGenerator.cpp
  tests/libs/tflite/CMakeLists.txt
  tests/libs/tflite/include/tflite/RandomInputInitializer.h
  tests/libs/tflite/src/RandomInputInitializer.cpp
  tests/tools/onert_run/src/randomgen.cc
  tests/tools/onert_train/src/randomgen.cc
  tests/tools/tflite_comparator/src/tflite_comparator.cc
  tests/tools/tflite_run/src/tflite_run.cc
Labels: PR/ready for review

#13034 [onert] Remove dead code in HEScheduler
  runtime/onert/core/src/compiler/HEScheduler.cc
Labels: PR/ready for review

#13041 [infra/gbs] Add tizen 9.0 repo and 7.0 profile
  infra/nnfw/config/gbs.conf
Labels: PR/ready for review

#13040 [onert] Move gpu-cl backend into contrib
  infra/nnfw/cmake/CfgOptionFlags.cmake
  infra/nnfw/cmake/options/options_aarch64-android.cmake
  infra/nnfw/cmake/options/options_armv7hl-tizen.cmake
  infra/nnfw/cmake/options/options_armv7l-linux.cmake
  infra/nnfw/cmake/options/options_armv7l-tizen.cmake
  infra/nnfw/cmake/options/options_i686-tizen.cmake
  infra/nnfw/cmake/options/options_riscv64-tizen.cmake
  infra/nnfw/cmake/options/options_x86_64-tizen.cmake
  packaging/EGL_HEADERS.tar.gz
  packaging/FLATBUFFERS-2.0.tar.gz
  packaging/OPENCL_HEADERS.tar.gz
  packaging/OPENGL_HEADERS.tar.gz
  packaging/VULKAN.tar.gz
  packaging/nnfw.spec
  runtime/contrib/gpu_cl/Backend.h
  runtime/contrib/gpu_cl/BackendContext.cc
  runtime/contrib/gpu_cl/BackendContext.h
  runtime/contrib/gpu_cl/CMakeLists.txt
  runtime/contrib/gpu_cl/ClConstantInitializer.cc
  runtime/contrib/gpu_cl/ClConstantInitializer.h
  runtime/contrib/gpu_cl/ClFunction.h
  runtime/contrib/gpu_cl/Config.cc
  runtime/contrib/gpu_cl/Config.h
  runtime/contrib/gpu_cl/ConstantInitializer.cc
  runtime/contrib/gpu_cl/ConstantInitializer.h
  runtime/contrib/gpu_cl/KernelGenerator.cc
  runtime/contrib/gpu_cl/KernelGenerator.h
  runtime/contrib/gpu_cl/MemoryManager.h
  runtime/contrib/gpu_cl/TensorBuilder.cc
  runtime/contrib/gpu_cl/TensorBuilder.h
  runtime/contrib/gpu_cl/TensorManager.cc
  runtime/contrib/gpu_cl/TensorManager.h
  runtime/contrib/gpu_cl/TensorRegistry.h
  runtime/contrib/gpu_cl/Utils.h
  runtime/contrib/gpu_cl/gpu_cl.cc
  runtime/contrib/gpu_cl/operand/CLTensor.cc
  runtime/contrib/gpu_cl/operand/CLTensor.h
  runtime/contrib/gpu_cl/operand/ICLTensor.cc
  runtime/contrib/gpu_cl/operand/ICLTensor.h
  runtime/onert/backend/CMakeLists.txt
Labels: PR/ready for review

#13012 [tools/circle_plus_gen] Add training parameters json loader
  tools/circle_plus_gen/example/train_tparam.json
  tools/circle_plus_gen/lib/json_parser.py
  tools/circle_plus_gen/lib/train_param.py
  tools/circle_plus_gen/main.py
Labels: PR/ready for review

#13043 [onert] Set workspace to session
  runtime/onert/api/nnfw/src/nnfw_api.cc
  runtime/onert/api/nnfw/src/nnfw_api_internal.cc
  runtime/onert/api/nnfw/src/nnfw_api_internal.h
Labels: PR/ready for review

#13044 [onert/gbs] Change repo url to use latest
  infra/nnfw/config/gbs.conf
Labels: PR/ready for review

#13049 [onert/test] Print number value on tflite comparator
  tests/tools/tflite_comparator/src/tflite_comparator.cc
Labels: PR/ready for review

#13027 [tools/circle_plus_gen] Add tparam inject feature
  tools/circle_plus_gen/README.md
  tools/circle_plus_gen/lib/circle_plus.py
  tools/circle_plus_gen/lib/train_param.py
  tools/circle_plus_gen/main.py
Labels: PR/ready for review, approval: 2

#13046 [onert/odc] Introduce minmax embedder
  Makefile.template
  packaging/nnfw.spec
  runtime/onert/odc/Embedder.cc
  runtime/onert/odc/Embedder.h
  runtime/onert/odc/MinMaxReader.cc
  runtime/onert/odc/MinMaxReader.h
  runtime/onert/odc/Quantizer.cc
Labels: PR/ready for review

#13061 [tools/circle_plus_gen] Fix typos
  tools/circle_plus_gen/README.md
  tools/circle_plus_gen/example/sample_tparam.circle
  tools/circle_plus_gen/schema/__init__.py
Labels: PR/ready for review, approval: 1

#13035 [runtime] Use c++17 for tests and tools
  tests/CMakeLists.txt
  tests/nnapi/CMakeLists.txt
  tests/tools/onert_train/CMakeLists.txt
  tools/CMakeLists.txt
  tools/kbenchmark/CMakeLists.txt
Labels: PR/ready for review

#13047 [onert] Introduce raw format minmax file
  runtime/onert/core/CMakeLists.txt
  runtime/onert/core/include/util/MinMaxMap.h
  runtime/onert/core/src/compiler/ExecutorFactory.cc
  runtime/onert/core/src/exec/MinMaxData.cc
  runtime/onert/core/src/exec/MinMaxData.h
  runtime/onert/core/src/exec/MinMaxRecorder.cc
  runtime/onert/core/src/exec/MinMaxRecorder.h
Labels: PR/ready for review

#13063 [luci-interpreter] Support boolean type on BroadcastTo op
  compiler/luci-interpreter/src/kernels/BroadcastTo.cpp
  compiler/luci-interpreter/src/kernels/BroadcastTo.h
  compiler/luci-interpreter/src/kernels/BroadcastTo.test.cpp
Labels: PR/ready for review

#13075 [onert] Remove custom strip in cmake
  runtime/contrib/gpu_cl/CMakeLists.txt
  runtime/onert/api/nnapi/CMakeLists.txt
  runtime/onert/api/nnfw/CMakeLists.txt
  runtime/onert/api/python/CMakeLists.txt
  runtime/onert/backend/acl_cl/CMakeLists.txt
  runtime/onert/backend/acl_neon/CMakeLists.txt
  runtime/onert/backend/cpu/CMakeLists.txt
  runtime/onert/backend/ruy/CMakeLists.txt
  runtime/onert/backend/train/CMakeLists.txt
  runtime/onert/backend/trix/CMakeLists.txt
  runtime/onert/backend/xnnpack/CMakeLists.txt
  runtime/onert/core/CMakeLists.txt
  runtime/onert/loader/trix/CMakeLists.txt
  runtime/onert/odc/CMakeLists.txt
  runtime/service/npud/backend/trix/CMakeLists.txt
Labels: PR/ready for review

#13077 [onert] Change backend and loader install path
  infra/debian/runtime/nnfw.install
  packaging/nnfw.spec
  runtime/onert/backend/acl_cl/CMakeLists.txt
  runtime/onert/backend/acl_neon/CMakeLists.txt
  runtime/onert/backend/cpu/CMakeLists.txt
  runtime/onert/backend/ruy/CMakeLists.txt
  runtime/onert/backend/train/CMakeLists.txt
  runtime/onert/backend/trix/CMakeLists.txt
  runtime/onert/backend/xnnpack/CMakeLists.txt
  runtime/onert/core/CMakeLists.txt
  runtime/onert/loader/trix/CMakeLists.txt
Labels: PR/ready for review, approval: 2

#13053 [onert] Use unified compile option for multimodel
  runtime/onert/api/nnapi/wrapper/ANeuralNetworksCompilation.cc
  runtime/onert/api/nnfw/src/nnfw_api_internal.cc
  runtime/onert/api/nnfw/src/nnfw_api_internal.h
  runtime/onert/core/include/compiler/Compiler.h
  runtime/onert/core/include/compiler/CompilerFactory.h
  runtime/onert/core/src/compiler/Compiler.cc
  runtime/onert/core/src/compiler/CompilerFactory.cc
  runtime/onert/core/src/compiler/MultiModelCompiler.cc
  runtime/onert/core/src/compiler/MultiModelCompiler.h
  runtime/onert/core/src/compiler/train/TrainingCompiler.cc
  runtime/onert/core/src/compiler/train/TrainingCompiler.h
  runtime/onert/core/src/exec/Execution.test.cc
Labels: PR/ready for review

#13078 [onert] Remove null check for non-null
  runtime/onert/core/src/compiler/Compiler.cc
  runtime/onert/core/src/compiler/train/TrainingCompiler.cc
Labels: PR/ready for review

#13066 [onert] Introduce magic code and version to minmax data file
  runtime/onert/core/src/exec/MinMaxData.cc
  runtime/onert/core/src/exec/MinMaxData.h
  runtime/onert/odc/MinMaxReader.cc
  runtime/onert/odc/MinMaxReader.h
Labels: PR/ready for review
