Repository Samsung/ONE, pull requests merged in 2024-10, with the labels that each got.

#14086 [cker] Introduce cker for avgpool
  compute/cker/include/cker/train/operation/AveragePool.h
  compute/cker/src/train/AveragePool.test.cc
Labels: PR/ready for review

#14136 [luci/pass] Update reshape handling in RmUnnTransNetPass
  compiler/luci/pass/src/RemoveUnnecessaryTransposeNetPass.cpp
  compiler/luci/pass/src/RemoveUnnecessaryTransposeNetPass.test.cpp
Labels: PR/ready for review

#14133 [cker] Fix min-max calculation in MaxPool2D
  compute/cker/include/cker/train/operation/MaxPool.h
  compute/cker/src/train/MaxPool.test.cc
Labels: PR/ready for review, approval: 2

#14146 [luci] static cast from uint32 to int64
  compiler/luci/service/src/Nodes/CircleStridedSlice.cpp
Labels: PR/ready for review

#14145 [common-artifacts] Exclude Inf_Mul_000 recipe
  compiler/common-artifacts/exclude.lst
Labels: SSAFY

#14139 [res] Add TFLiteRecipe for non-const reshape
  res/TensorFlowLiteRecipes/Reshape_005/test.recipe
Labels: PR/ready for review, SSAFY

#14147 [res] Add TFLiteRecipe for dynamic shape Multiply
  res/TensorFlowLiteRecipes/Inf_Mul_000/test.recipe
  res/TensorFlowLiteRecipes/Inf_Mul_000/test.rule
Labels: SSAFY

#14152 [luci/pass] Add TaggedShapeAnalyzer::init() in RmUnnTransNetPass
  compiler/luci/pass/src/RemoveUnnecessaryTransposeNetPass.cpp
Labels: PR/ready for review

#14158 [res] Add TFLiteRecipe for dynamic shape NEG
  res/TensorFlowLiteRecipes/Inf_Neg_000/test.recipe
  res/TensorFlowLiteRecipes/Inf_Neg_000/test.rule
Labels: SSAFY

#14150 [luci/pass] Update TaggedShapeAnaylzer methods interface
  compiler/luci/pass/src/RemoveUnnecessaryTransposeNetPass.cpp
Labels: PR/ready for review

#14155 [circle2circle-dredd-recipe-test] Add Inf_Mul_000 test
  compiler/circle2circle-dredd-recipe-test/test.lst
Labels: SSAFY

#14047 [onert/train] Add LayerScopeManager into TensorManager
  runtime/onert/backend/train/TensorManager.cc
  runtime/onert/backend/train/TensorManager.h
Labels: PR/ready for review

#14161 [onert/core] Add RmsNorm operation
  runtime/onert/core/include/ir/Operations.Include.h
  runtime/onert/core/include/ir/Operations.lst
  runtime/onert/core/include/ir/operation/RmsNorm.h
  runtime/onert/core/src/ir/OperationDumper.cc
  runtime/onert/core/src/ir/OperationDumper.h
  runtime/onert/core/src/ir/operation/RmsNorm.cc
  runtime/onert/core/src/ir/train/operation/UntrainableOperation.test.cc
Labels: PR/ready for review

#14149 [onert/train] Support averagePool2D operation for training
  runtime/onert/backend/train/KernelGenerator.cc
  runtime/onert/backend/train/ops/PoolLayer.cc
  runtime/onert/backend/train/ops/PoolLayer.h
  runtime/onert/core/src/ir/train/UseDefGenerator.cc
Labels: PR/ready for review

#14105 [onert] Apply softmax to CategoricalCrossEntropy automatically
  runtime/onert/api/nnfw/include/nnfw_experimental.h
  runtime/onert/backend/train/KernelGenerator.cc
  runtime/onert/backend/train/ops/LossCategoricalCrossentropyLayer.cc
  runtime/onert/backend/train/ops/LossCategoricalCrossentropyLayer.h
  runtime/onert/core/include/ir/train/operation/Loss.h
  runtime/onert/core/src/compiler/train/TrainableOperationConverter.cc
  runtime/onert/core/src/compiler/train/pass/LossInsertionPass.cc
  runtime/onert/core/src/ir/train/TrainableGraph.test.cc
  runtime/onert/core/src/ir/train/UseDefGenerator.test.cc
  runtime/onert/core/src/ir/train/operation/Loss.cc
Labels: PR/ready for review

#14156 [res] Add TFLiteRecipe for dynamic shape StridedSlice
  res/TensorFlowLiteRecipes/Inf_StridedSlice_000/test.recipe
  res/TensorFlowLiteRecipes/Inf_StridedSlice_000/test.rule
  res/TensorFlowLiteRecipes/Inf_StridedSlice_001/test.recipe
  res/TensorFlowLiteRecipes/Inf_StridedSlice_001/test.rule
Labels: SSAFY

#14157 [res] Add TFLiteRecipe for FullyConnected dynamic shape
  res/TensorFlowLiteRecipes/Inf_FullyConnected_000/test.recipe
  res/TensorFlowLiteRecipes/Inf_FullyConnected_000/test.rule
  res/TensorFlowLiteRecipes/Inf_FullyConnected_001/test.recipe
  res/TensorFlowLiteRecipes/Inf_FullyConnected_001/test.rule
Labels: SSAFY

#14162 [res] Add TFLiteRecipe for dynamic shape Reshape
  res/TensorFlowLiteRecipes/Inf_Reshape_000/test.recipe
  res/TensorFlowLiteRecipes/Inf_Reshape_000/test.rule
Labels: PR/ready for review, SSAFY

#14168 [onert] Remove unnecessary op conversion
  runtime/onert/core/src/compiler/train/TrainableOperationConverter.cc
  runtime/onert/core/src/compiler/train/TrainableOperationConverter.h
Labels: PR/ready for review

#14174 [circle2circle-dredd-recipe-test] Add Inf_FullyConnected test
  compiler/circle2circle-dredd-recipe-test/test.lst
Labels: SSAFY

#14172 [circle2circle-dredd-recipe-test] Add Inf_Neg_000 test
  compiler/circle2circle-dredd-recipe-test/test.lst
Labels: SSAFY

#14167 [luci/pass] Support rank expansion case in RmUnnTransNetPass
  compiler/luci/pass/src/RemoveUnnecessaryTransposeNetPass.cpp
  compiler/luci/pass/src/RemoveUnnecessaryTransposeNetPass.test.cpp
Labels: PR/ready for review

#14181 [luci/pass] Add origins to const node
  compiler/luci/pass/src/ResolveCustomOpMatMulPass.cpp
  compiler/luci/pass/src/ShuffleWeightTo16x1Float32Pass.cpp
  compiler/luci/pass/src/SubstitutePackToReshapePass.cpp
  compiler/luci/pass/src/SubstituteSqueezeToReshapePass.cpp
  compiler/luci/pass/src/SubstituteTransposeToReshapePass.cpp
Labels: PR/ready for review

#14182 [onert] Support Q4_0 & Q8_0 FC weight
  runtime/3rdparty/ggml/src/ggml.c
  runtime/onert/backend/cpu/ops/FullyConnectedLayer.cc
  runtime/onert/backend/cpu/ops/FullyConnectedLayer.h
Labels: PR/ready for review

#14166 [train] Modify maxPool2D in training
  runtime/onert/backend/train/ops/PoolLayer.cc
Labels: PR/ready for review

#14186 [onert] Revisit CPU ExternalContext
  runtime/onert/backend/cpu/ExternalContext.cc
  runtime/onert/backend/cpu/ExternalContext.h
  runtime/onert/backend/cpu/ops/GatherLayer.cc
Labels: PR/ready for review

#14159 [luci/pass] Introduce SubstituteExpandDimsToReshapePass
  compiler/luci/pass/include/luci/Pass/SubstituteExpandDimsToReshapePass.h
  compiler/luci/pass/src/SubstituteExpandDimsToReshapePass.cpp
  compiler/luci/pass/src/SubstituteExpandDimsToReshapePass.test.cpp
Labels: PR/ready for review

#14187 [luci/pass] Trim RemoveUnnecessaryTransposesNetPass
  compiler/luci/pass/src/RemoveUnnecessaryTransposeNetPass.cpp
Labels: PR/ready for review, approval: 1

#14065 [infra/github] Test onecc without docker
  .github/workflows/run-onecc-build.yml
Labels: PR/ready for review

#14194 [onert/cpu] Update ggml usage
  runtime/onert/backend/cpu/ops/FullyConnectedLayer.cc
  runtime/onert/backend/cpu/ops/GatherLayer.cc
Labels: PR/ready for review

#14201 [circle2circle-dredd-recipe-test] Add Inf_StridedSlice test
  compiler/circle2circle-dredd-recipe-test/test.lst
Labels: SSAFY

#14197 [circle2circle] Add substitute_expand_dims_to_reshape option
  compiler/circle2circle/src/Circle2Circle.cpp
Labels: PR/ready for review

#14204 [dalgona] Support ubuntu 24.04
  compiler/dalgona/CMakeLists.txt
Labels: PR/ready for review

#14203 [common-artifacts] Support ubuntu 24.04
  compiler/common-artifacts/CMakeLists.txt
Labels: PR/ready for review

#14198 [onert/backend] Add LayerScopeTensor interface to TensorBuilder
  runtime/onert/backend/train/TensorBuilder.cc
  runtime/onert/backend/train/TensorBuilder.h
Labels: PR/ready for review

#14199 [onert/backend] Add LayerScopeTensor Planning
  runtime/onert/backend/train/BackendContext.cc
  runtime/onert/backend/train/BackendContext.h
  runtime/onert/backend/train/TensorPlanner.cc
  runtime/onert/backend/train/TensorPlanner.h
Labels: PR/ready for review

#14236 [onert/train] Update TensorPlanner log
  runtime/onert/backend/train/TensorPlanner.cc
Labels: PR/ready for review

#14235 [onert/train] Register LayerScopeTensor to registry
  runtime/onert/backend/train/BackendContext.cc
Labels: PR/ready for review

#14240 [fme-apply] Change phase strategy and find depth
  compiler/fme-apply/src/FMEqualizer.cpp
  compiler/fme-apply/src/InsertScaleShift.cpp
Labels: PR/ready for review

#14241 [fme-detect] Support one more forwardable successors
  compiler/fme-detect/src/EqualizePatternFinder.cpp
Labels: PR/ready for review

#14242 [fme-detect] Do not forward Gelu
  compiler/fme-detect/src/EqualizePatternFinder.cpp
Labels: PR/ready for review

#14243 [fme-apply] Apply abs to weight
  compiler/fme-apply/src/InsertScaleShift.cpp
Labels: PR/ready for review

#14248 [dalgona] Add bool type
  compiler/dalgona/src/Utils.cpp
Labels: PR/ready for review

#14249 [dalgona] Consider no bias in FullyConnected
  compiler/dalgona/src/PostOperatorHook.h
Labels: PR/ready for review

#14250 [fme-apply] Consider no bias FullyConnected
  compiler/fme-apply/src/pass/FusePostScalePass.cpp
Labels: PR/ready for review
