Repository Samsung/ONE, pull requests merged in 2024-06, with the labels that each got.

#13079 [onert] Add workspace directory compiler option
  runtime/onert/api/nnfw/include/nnfw.h
  runtime/onert/api/nnfw/src/nnfw_api_internal.cc
  runtime/onert/api/nnfw/src/nnfw_api_internal.h
  runtime/onert/core/include/compiler/CompilerOptions.h
  runtime/onert/core/include/util/Config.lst
  runtime/onert/core/src/compiler/CompilerOptions.cc
Labels: PR/ready for review

#13090 [onert] Use workspace for execution data dump
  infra/scripts/test_coverage.sh
  runtime/onert/api/nnfw/src/nnfw_api_internal.cc
  runtime/onert/core/include/compiler/CompilerOptions.h
  runtime/onert/core/include/util/Config.lst
  runtime/onert/core/src/compiler/Compiler.cc
  runtime/onert/core/src/compiler/CompilerOptions.cc
  runtime/onert/core/src/compiler/ExecutorFactory.cc
  runtime/onert/core/src/compiler/MultiModelCompiler.cc
  runtime/onert/core/src/compiler/train/TrainingCompiler.cc
  runtime/onert/core/src/exec/ExecutionObservers.cc
  runtime/onert/core/src/exec/ExecutionObservers.h
  runtime/onert/core/src/exec/MinMaxRecorder.cc
  runtime/onert/core/src/exec/MinMaxRecorder.h
  runtime/onert/core/src/util/EventWriter.h
  runtime/onert/odc/Quantizer.cc
  tests/nnfw_api/src/NNPackageTests/AddModelLoaded.test.cc
  tests/nnfw_api/src/NNPackageTests/AddSessionPrepared.test.cc
  tests/nnfw_api/src/NNPackageTests/SessionCreated.test.cc
  tests/nnfw_api/src/NNPackageTests/SingleSession.test.cc
  tests/scripts/benchmark.sh
Labels: PR/ready for review

#13069 [tools/circle_plus_gen] Add document for json file
  tools/circle_plus_gen/README.md
  tools/circle_plus_gen/example/tparam_sgd_scce.json
  tools/circle_plus_gen/how-to-write-tparam-json.md
  tools/circle_plus_gen/lib/json_parser.py
Labels: PR/ready for review, approval: 2

#13093 [tools/circle_plus_gen] Fix regular expression in json parser
  tools/circle_plus_gen/lib/json_parser.py
Labels: PR/ready for review, approval: 2

#13092 [infra] Introduce android sdk docker
  infra/docker/android-sdk/Dockerfile
Labels: PR/ready for review

#13101 [onert] Fix android packaging fail
  runtime/contrib/android/api/Prebuilt.mk
Labels: PR/ready for review

#13089 [nnfw_api] Remove losses buffer from SessionObjectTraining
  tests/nnfw_api/lib/GenModelTrain.h
Labels: PR/ready for review

#13100 [onert_run] Revise allocation and session access
  tests/tools/onert_run/src/allocation.h
  tests/tools/onert_run/src/formatter.h
  tests/tools/onert_run/src/h5formatter.cc
  tests/tools/onert_run/src/h5formatter.h
  tests/tools/onert_run/src/onert_run.cc
  tests/tools/onert_run/src/randomgen.cc
  tests/tools/onert_run/src/randomgen.h
  tests/tools/onert_run/src/rawformatter.cc
  tests/tools/onert_run/src/rawformatter.h
  tests/tools/onert_run/src/types.h
Labels: PR/ready for review

#13112 [infra] Remove android sdk in ubuntu 20.04 docker image
  docs/howto/how-to-cross-build-runtime-for-android.md
  infra/docker/focal/Dockerfile
Labels: PR/ready for review

#13105 [onert] Add unit tests for memory planners
  runtime/onert/backend/train/CMakeLists.txt
  runtime/onert/backend/train/MemoryPlanner.test.cc
Labels: PR/ready for review

#13104 Add unit tests for `UntrainableOperation`
  runtime/onert/core/src/ir/train/operation/UntrainableOperation.test.cc
Labels: PR/ready for review

#13113 [onert] Add version to the TrainingInfo strcture
  runtime/onert/core/include/ir/train/TrainingInfo.h
  runtime/onert/core/src/loader/TrainInfoLoader.cc
Labels: PR/ready for review

#13131 [tools/circle_plus_gen] Update flatc generated files
  tools/circle_plus_gen/schema/circle_schema_generated.py
  tools/circle_plus_gen/schema/circle_traininfo_generated.py
Labels: PR/ready for review, approval: 2

#13132 [tools/circle_plus_gen] add script to update flatc generated files
  tools/circle_plus_gen/schema/__init__.py
  tools/circle_plus_gen/schema/_gen.py
Labels: PR/ready for review

#13111 [onert] Revisit GenModelTrain
  tests/nnfw_api/lib/GenModelTrain.h
  tests/nnfw_api/src/GenModelTests/one_op_trains/Conv2D.test.cc
Labels: PR/ready for review

#13114 [onert] Introduce CircleExporter class
  runtime/libs/circle-schema/include/circle_schema_generated.h
  runtime/onert/core/include/exporter/CircleExporter.h
  runtime/onert/core/src/exporter/CircleExporter.cc
Labels: PR/ready for review

#13118 [onert_run] Support different random input on each rerun
  tests/tools/onert_run/src/args.cc
  tests/tools/onert_run/src/args.h
  tests/tools/onert_run/src/onert_run.cc
  tests/tools/onert_run/src/randomgen.cc
  tests/tools/onert_run/src/randomgen.h
Labels: PR/ready for review

#13139 [onert_train] Print metric result during training
  tests/tools/onert_train/src/onert_train.cc
Labels: PR/ready for review

#13142 [onert] Fix MinMaxRecorder header include
  runtime/onert/odc/MinMaxReader.cc
  runtime/onert/odc/MinMaxReader.h
Labels: PR/ready for review

#13143 [infra] Fix xnnpack tizen build
  infra/nnfw/cmake/packages/XnnpackConfig.cmake
Labels: PR/ready for review

#13153 [onert] Use reinterpret_cast instead of the classic C casts
  runtime/onert/core/src/exporter/CircleExporter.cc
Labels: PR/ready for review, approval: 1

#13141 [onert] Add unit tests for optimizers
  runtime/onert/backend/train/optimizer/Optimizers.test.cc
Labels: PR/ready for review

#13152 [onert] Add dilation check logic in DepthwiseConvolution layer for train
  runtime/onert/backend/train/ops/DepthwiseConvolutionLayer.cc
Labels: PR/ready for review

#13159 [onert] Revisits CompilerOptions
  runtime/onert/api/nnapi/wrapper/ANeuralNetworksCompilation.cc
  runtime/onert/api/nnfw/src/nnfw_api_internal.h
  runtime/onert/core/include/compiler/CompilerOptions.h
Labels: PR/ready for review, approval: 1

#13166 [one-cmds] Expand interface of the dummy tools for test
  compiler/one-cmds/dummy-driver/src/dummy-compile.cpp
  compiler/one-cmds/dummy-driver/src/dummy-profile.cpp
Labels: PR/ready for review

#13165 [one-cmds] Introduce arguemntparse lib
  compiler/one-cmds/CMakeLists.txt
  compiler/one-cmds/onelib/argumentparse.py
Labels: PR/ready for review

#13144 [onert] Add unit tests for training FC
  tests/nnfw_api/src/GenModelTests/one_op_trains/FullyConnected.test.cc
Labels: PR/ready for review

#13169 [one-cmds] Implement get_arg_parser
  compiler/one-cmds/onelib/utils.py
Labels: PR/ready for review

#13171 [one-cmds] Introduce target option
  compiler/one-cmds/one-codegen
  compiler/one-cmds/one-init
  compiler/one-cmds/one-profile
  compiler/one-cmds/onecc
  compiler/one-cmds/onecc.template.cfg
  compiler/one-cmds/onelib/CfgRunner.py
  compiler/one-cmds/onelib/backends.py
  compiler/one-cmds/tests/CMakeLists.txt
  compiler/one-cmds/tests/one-codegen_005.cfg
  compiler/one-cmds/tests/one-codegen_005.test
  compiler/one-cmds/tests/one-codegen_006.cfg
  compiler/one-cmds/tests/one-codegen_006.test
  compiler/one-cmds/tests/one-codegen_007.cfg
  compiler/one-cmds/tests/one-codegen_007.test
  compiler/one-cmds/tests/one-codegen_008.cfg
  compiler/one-cmds/tests/one-codegen_008.test
  compiler/one-cmds/tests/one-profile_005.cfg
  compiler/one-cmds/tests/one-profile_005.test
  compiler/one-cmds/tests/one-profile_006.cfg
  compiler/one-cmds/tests/one-profile_006.test
  compiler/one-cmds/tests/one-profile_007.cfg
  compiler/one-cmds/tests/one-profile_007.test
  compiler/one-cmds/tests/one-profile_008.cfg
  compiler/one-cmds/tests/one-profile_008.test
  compiler/one-cmds/tests/one_codegen_008.py
  compiler/one-cmds/tests/one_profile_008.py
  compiler/one-cmds/tests/onecc_060.cfg
  compiler/one-cmds/tests/onecc_060.test
  compiler/one-cmds/tests/onecc_061.cfg
  compiler/one-cmds/tests/onecc_061.test
  compiler/one-cmds/tests/onecc_062.cfg
  compiler/one-cmds/tests/onecc_062.py
  compiler/one-cmds/tests/onecc_062.test
  compiler/one-cmds/tests/onecc_063.cfg
  compiler/one-cmds/tests/onecc_063.py
  compiler/one-cmds/tests/onecc_063.test
Labels: PR/ready for review

#13174 [onert] Add validation check unittest for workspace
  runtime/onert/api/nnfw/src/nnfw_api_internal.cc
  tests/nnfw_api/src/NNPackageTests/AddModelLoaded.test.cc
  tests/nnfw_api/src/NNPackageTests/AddSessionPrepared.test.cc
Labels: PR/ready for review, approval: 1

#13175 [onert] Add validation test for set_backends_per_operation
  runtime/onert/api/nnfw/src/nnfw_api_internal.cc
  runtime/onert/core/src/compiler/CompilerOptions.cc
  tests/nnfw_api/src/NNPackageTests/AddModelLoaded.test.cc
Labels: PR/ready for review, approval: 1

#13157 [infra] Update exclude.txt
  .ahub/sam/exclude.txt
Labels: PR/ready for review

#13168 [tools/circle_plus_gen] Add operator access methods to CirclePlus
  tools/circle_plus_gen/lib/circle_plus.py
  tools/circle_plus_gen/test/__init__.py
  tools/circle_plus_gen/test/test_circle_plus.py
Labels: PR/ready for review, approval: 2

#13156 [onert] Move updateWeight function to the CircleExporter
  runtime/onert/api/nnfw/src/nnfw_api_internal.cc
  runtime/onert/core/include/exporter/CircleExporter.h
  runtime/onert/core/src/exporter/CircleExporter.cc
Labels: PR/ready for review

#13164 [onert] Revise wrong comments
  runtime/onert/backend/train/optimizer/Optimizers.test.cc
Labels: PR/ready for review

#13160 [onert] Introduce ExecutionContext
  runtime/onert/core/include/exec/Execution.h
  runtime/onert/core/include/exec/ExecutionContext.h
  runtime/onert/core/include/exec/IExecutor.h
  runtime/onert/core/include/exec/IExecutors.h
  runtime/onert/core/src/exec/Execution.cc
  runtime/onert/core/src/exec/ExecutorBase.cc
  runtime/onert/core/src/exec/ExecutorBase.h
  runtime/onert/core/src/exec/MultiModelExecutors.cc
  runtime/onert/core/src/exec/MultiModelExecutors.h
  runtime/onert/core/src/exec/SingleModelExecutors.cc
  runtime/onert/core/src/exec/SingleModelExecutors.h
  runtime/onert/core/src/exec/train/TrainableExecutor.cc
  runtime/onert/core/src/exec/train/TrainableExecutor.h
  runtime/onert/core/src/exec/train/TrainableExecutors.cc
  runtime/onert/core/src/exec/train/TrainableExecutors.h
Labels: PR/ready for review, approval: 2

#13170 [onert] Create minmax dump file in handleSubgraphEnd
  runtime/onert/core/src/exec/MinMaxRecorder.cc
  runtime/onert/core/src/exec/MinMaxRecorder.h
Labels: PR/ready for review

#13173 [onert] Update deprecated API implementation
  runtime/onert/api/nnfw/include/nnfw_experimental.h
  runtime/onert/api/nnfw/src/nnfw_api.cc
  runtime/onert/api/nnfw/src/nnfw_api_internal.cc
  runtime/onert/api/nnfw/src/nnfw_api_internal.h
  tests/nnfw_api/src/NNPackageTests/SingleSession.test.cc
Labels: PR/ready for review, approval: 1

#13151 [onert] Change TracingObserver writing policy
  runtime/onert/core/src/exec/ExecutionObservers.cc
  runtime/onert/core/src/exec/ExecutionObservers.h
Labels: PR/ready for review, approval: 2

#13176 [debian] Install argumentparse.py
  infra/debian/compiler/one-compiler.install
Labels: PR/ready for review

#13177 [infra/onert] Disable hdf5 minmax dumper
  infra/nnfw/cmake/CfgOptionFlags.cmake
  infra/nnfw/cmake/options/options_aarch64-android.cmake
  infra/nnfw/cmake/options/options_aarch64-tizen.cmake
  infra/nnfw/cmake/options/options_armv7hl-tizen.cmake
  infra/nnfw/cmake/options/options_armv7l-tizen.cmake
  infra/nnfw/cmake/options/options_i686-tizen.cmake
  infra/nnfw/cmake/options/options_riscv64-tizen.cmake
  infra/nnfw/cmake/options/options_x86_64-tizen.cmake
Labels: PR/ready for review

#13180 [tools/onert_train] Print trainable ops
  tests/tools/onert_train/src/nnfw_util.cc
Labels: trivial

#13179 [one-cmds] Fix bug on target feature
  compiler/one-cmds/onelib/CfgRunner.py
Labels: PR/ready for review

#13155 [onert] Enable observer on execution
  runtime/onert/core/src/compiler/ExecutorFactory.cc
  runtime/onert/core/src/exec/DataflowExecutor.cc
  runtime/onert/core/src/exec/DataflowExecutor.h
  runtime/onert/core/src/exec/ExecutionObservee.cc
  runtime/onert/core/src/exec/ExecutionObservee.h
  runtime/onert/core/src/exec/ExecutionObservers.h
  runtime/onert/core/src/exec/ExecutorBase.cc
  runtime/onert/core/src/exec/ExecutorBase.h
  runtime/onert/core/src/exec/LinearExecutor.cc
  runtime/onert/core/src/exec/LinearExecutor.h
  runtime/onert/core/src/exec/MinMaxRecorder.h
  runtime/onert/core/src/exec/ParallelExecutor.cc
  runtime/onert/core/src/exec/ParallelExecutor.h
  runtime/onert/core/src/exec/train/TrainableExecutor.cc
  runtime/onert/core/src/exec/train/TrainableExecutor.h
Labels: PR/ready for review, approval: 2

#13182 [one-cmds] Support boolean type in the command schema
  compiler/one-cmds/dummy-driver/CMakeLists.txt
  compiler/one-cmds/dummy-driver/src/dummy-compiler.cpp
  compiler/one-cmds/onelib/argumentparse.py
  compiler/one-cmds/tests/onecc_064.cfg
  compiler/one-cmds/tests/onecc_064.py
  compiler/one-cmds/tests/onecc_064.test
Labels: PR/ready for review

#13192 [one-cmds] Revise the way command schema is interpreted
  compiler/one-cmds/one-codegen
  compiler/one-cmds/one-profile
  compiler/one-cmds/onelib/backends.py
  compiler/one-cmds/onelib/utils.py
  compiler/one-cmds/tests/CMakeLists.txt
  compiler/one-cmds/tests/one-codegen_005.cfg
  compiler/one-cmds/tests/one-codegen_005.ini
  compiler/one-cmds/tests/one-codegen_005.test
  compiler/one-cmds/tests/one-codegen_006.cfg
  compiler/one-cmds/tests/one-codegen_006.ini
  compiler/one-cmds/tests/one-codegen_006.test
  compiler/one-cmds/tests/one-codegen_007.cfg
  compiler/one-cmds/tests/one-codegen_007.ini
  compiler/one-cmds/tests/one-codegen_007.test
  compiler/one-cmds/tests/one-codegen_008.cfg
  compiler/one-cmds/tests/one-codegen_008.ini
  compiler/one-cmds/tests/one-codegen_008.py
  compiler/one-cmds/tests/one-codegen_008.test
  compiler/one-cmds/tests/one-profile_005.cfg
  compiler/one-cmds/tests/one-profile_005.ini
  compiler/one-cmds/tests/one-profile_005.test
  compiler/one-cmds/tests/one-profile_006.cfg
  compiler/one-cmds/tests/one-profile_006.ini
  compiler/one-cmds/tests/one-profile_006.test
  compiler/one-cmds/tests/one-profile_007.cfg
  compiler/one-cmds/tests/one-profile_007.ini
  compiler/one-cmds/tests/one-profile_007.test
  compiler/one-cmds/tests/one-profile_008.cfg
  compiler/one-cmds/tests/one-profile_008.ini
  compiler/one-cmds/tests/one-profile_008.py
  compiler/one-cmds/tests/one-profile_008.test
  compiler/one-cmds/tests/onecc_060.cfg
  compiler/one-cmds/tests/onecc_060.ini
  compiler/one-cmds/tests/onecc_060.test
  compiler/one-cmds/tests/onecc_061.ini
  compiler/one-cmds/tests/onecc_061.test
  compiler/one-cmds/tests/onecc_062.cfg
  compiler/one-cmds/tests/onecc_062.ini
  compiler/one-cmds/tests/onecc_062.test
  compiler/one-cmds/tests/onecc_063.cfg
  compiler/one-cmds/tests/onecc_063.ini
  compiler/one-cmds/tests/onecc_063.test
  compiler/one-cmds/tests/onecc_064.cfg
  compiler/one-cmds/tests/onecc_064.ini
  compiler/one-cmds/tests/onecc_064.test
Labels: PR/ready for review

#13191 [onert] Remove unused variable in planTensors, genTensors
  runtime/onert/core/include/backend/basic/BackendContextHelpers.h
  runtime/onert/core/include/backend/basic/train/TrainableBackendContextHelpers.h
Labels: PR/ready for review, trivial

#13198 [onert] Use dlmopen for codegen lib
  runtime/onert/core/src/odc/CodegenLoader.cc
Labels: PR/ready for review

#13190 [onert] Remove nnfw_set_op_backend implementation
  docs/howto/how-to-use-nnfw-api.md
  docs/howto/how-to-use-specific-backend.md
  runtime/onert/api/nnfw/include/nnfw.h
  runtime/onert/api/nnfw/src/nnfw_api.cc
  runtime/onert/api/nnfw/src/nnfw_api_internal.cc
  runtime/onert/api/nnfw/src/nnfw_api_internal.h
  runtime/onert/api/python/src/nnfw_api_wrapper.cc
  tests/nnfw_api/src/NNPackageTests/SingleSession.test.cc
Labels: PR/ready for review

#13178 [onert] Implement config APIs
  runtime/onert/api/nnfw/src/nnfw_api.cc
  runtime/onert/api/nnfw/src/nnfw_api_internal.cc
  runtime/onert/api/nnfw/src/nnfw_api_internal.h
  runtime/onert/core/include/exec/ExecutionContext.h
  runtime/onert/core/src/exec/ExecutionContext.cc
  tests/nnfw_api/src/NNPackageTests/AddModelLoaded.test.cc
  tests/nnfw_api/src/NNPackageTests/AddSessionPrepared.test.cc
Labels: PR/ready for review, approval: 2

#13212 [onert/android] Update gradle version
  runtime/contrib/android/build.gradle
  runtime/contrib/android/gradle/wrapper/gradle-wrapper.jar
  runtime/contrib/android/gradle/wrapper/gradle-wrapper.properties
  runtime/contrib/android/gradlew
  runtime/contrib/android/gradlew.bat
Labels: PR/ready for review

#13227 [one-cmds] Revisit the tests
  compiler/one-cmds/tests/one-codegen_005.cfg
  compiler/one-cmds/tests/one-codegen_005.test
  compiler/one-cmds/tests/one-codegen_006.cfg
  compiler/one-cmds/tests/one-codegen_006.test
  compiler/one-cmds/tests/one-codegen_007.cfg
  compiler/one-cmds/tests/one-codegen_007.test
  compiler/one-cmds/tests/one-codegen_008.test
  compiler/one-cmds/tests/one-profile_005.test
  compiler/one-cmds/tests/one-profile_006.test
  compiler/one-cmds/tests/one-profile_007.test
  compiler/one-cmds/tests/one-profile_008.test
  compiler/one-cmds/tests/onecc_060.cfg
  compiler/one-cmds/tests/onecc_062.test
  compiler/one-cmds/tests/onecc_063.test
  compiler/one-cmds/tests/onecc_064.test
Labels: PR/ready for review

#13228 [one-cmds] Allow command key for gradual change
  compiler/one-cmds/one-codegen
  compiler/one-cmds/one-profile
  compiler/one-cmds/tests/one-codegen_009.cfg
  compiler/one-cmds/tests/one-codegen_009.ini
  compiler/one-cmds/tests/one-codegen_009.py
  compiler/one-cmds/tests/one-codegen_009.test
  compiler/one-cmds/tests/one-profile_009.cfg
  compiler/one-cmds/tests/one-profile_009.ini
  compiler/one-cmds/tests/one-profile_009.py
  compiler/one-cmds/tests/one-profile_009.test
  compiler/one-cmds/tests/onecc_065.cfg
  compiler/one-cmds/tests/onecc_065.ini
  compiler/one-cmds/tests/onecc_065.py
  compiler/one-cmds/tests/onecc_065.test
Labels: PR/ready for review

#13225 [onert] Remove noexcept specifier from ANeuralNetworksCompilation constructor
  runtime/onert/api/nnapi/wrapper/ANeuralNetworksCompilation.cc
  runtime/onert/api/nnapi/wrapper/ANeuralNetworksCompilation.h
Labels: PR/ready for review

#13172 [tools/circle_plus_gen] Update main to reuse print function
  tools/circle_plus_gen/main.py
Labels: PR/ready for review, approval: 2

#13195 [onert] Add unit tests for training ReLU6 op
  tests/nnfw_api/src/GenModelTests/nontrainable_op_trains/Relu6.test.cc
Labels: PR/ready for review

#13194 [onert] Add unit tests for training ReLU op
  tests/nnfw_api/src/GenModelTests/nontrainable_op_trains/Relu.test.cc
Labels: PR/ready for review

#13184 [onert] Add unit tests for training arithmetic ops
  tests/nnfw_api/src/GenModelTests/BranchModelTrain.test.cc
  tests/nnfw_api/src/GenModelTests/nontrainable_op_trains/Add.test.cc
  tests/nnfw_api/src/GenModelTests/nontrainable_op_trains/Mul.test.cc
  tests/nnfw_api/src/GenModelTests/nontrainable_op_trains/Sub.test.cc
Labels: PR/ready for review

#13183 [onert/odc] Fix quantization bug
  runtime/onert/odc/MinMaxReader.cc
  runtime/onert/odc/Quantizer.cc
Labels: PR/ready for review

#13181 [onert] Add updateMetadata function to CircleExporter
  runtime/onert/core/include/exporter/CircleExporter.h
  runtime/onert/core/src/exporter/CircleExporter.cc
  runtime/onert/core/src/exporter/TrainInfoBuilder.h
Labels: PR/ready for review

#13196 [onert] Add unit tests for training Reshape op
  tests/nnfw_api/src/GenModelTests/nontrainable_op_trains/Reshape.test.cc
Labels: PR/ready for review

#13197 [onert] Add unit tests for training Softmax op
  tests/nnfw_api/src/GenModelTests/nontrainable_op_trains/Softmax.test.cc
Labels: PR/ready for review

#13242 [onert] store the weights of the internally generated tensors
  runtime/onert/core/src/exporter/CircleExporter.cc
Labels: PR/ready for review

#13236 [onert] Remove warning in MinMaxReader
  runtime/onert/odc/MinMaxReader.cc
Labels: PR/ready for review

#13193 [onert] Add unit tests for training Pad op
  tests/nnfw_api/src/GenModelTests/nontrainable_op_trains/Pad.test.cc
Labels: PR/ready for review

#13216 [onert] Pass execution option into Execution and Executor
  runtime/onert/api/nnfw/src/nnfw_api_internal.cc
  runtime/onert/api/nnfw/src/nnfw_api_internal.h
  runtime/onert/core/include/exec/Execution.h
  runtime/onert/core/include/exec/ExecutionContext.h
  runtime/onert/core/include/exec/IExecutor.h
  runtime/onert/core/src/backend/builtin/kernel/IfLayer.cc
  runtime/onert/core/src/backend/builtin/kernel/WhileLayer.cc
  runtime/onert/core/src/exec/Execution.cc
  runtime/onert/core/src/exec/ExecutionContext.cc
  runtime/onert/core/src/exec/ExecutionObservee.cc
  runtime/onert/core/src/exec/ExecutionObservee.h
  runtime/onert/core/src/exec/ExecutorBase.cc
  runtime/onert/core/src/exec/ExecutorBase.h
  runtime/onert/core/src/exec/MultiModelExecutors.cc
  runtime/onert/core/src/exec/train/TrainableExecutor.cc
  runtime/onert/core/src/exec/train/TrainableExecutor.h
Labels: PR/ready for review, approval: 2

#13240 [onert] Introduce `export_circleplus` internal API
  runtime/onert/api/nnfw/include/nnfw_internal.h
  runtime/onert/api/nnfw/src/nnfw_api.cc
  runtime/onert/api/nnfw/src/nnfw_api_internal.cc
  runtime/onert/api/nnfw/src/nnfw_api_internal.h
Labels: PR/ready for review

#13209 [onert] Fix value error when training MaxPool2D
  runtime/onert/backend/train/ops/PoolLayer.cc
  tests/nnfw_api/lib/CircleGen.cc
  tests/nnfw_api/lib/CircleGen.h
  tests/nnfw_api/src/GenModelTests/nontrainable_op_trains/MaxPool2D.test.cc
Labels: PR/ready for review, approval: 2

#13258 [tools/onert_train] Introduce export_circleplus option
  tests/tools/onert_train/src/args.cc
  tests/tools/onert_train/src/args.h
  tests/tools/onert_train/src/onert_train.cc
Labels: PR/ready for review

#13253 [onert] Add more unit tests for MaxPool2D op
  tests/nnfw_api/src/GenModelTests/nontrainable_op_trains/MaxPool2D.test.cc
Labels: PR/ready for review, approval: 2

#13262 [tools/circle_plus_gen] Fix type bug
  tools/circle_plus_gen/lib/circle_plus.py
Labels: approval: 1

#13255 [infra] Cleanup dockerfiles
  infra/docker/android-sdk/Dockerfile
  infra/docker/focal/Dockerfile
  infra/docker/jammy/Dockerfile
Labels: PR/ready for review

#13279 [luci-interperter] Support bool type in the StridedSlice
  compiler/luci-interpreter/src/kernels/StridedSlice.cpp
Labels: PR/ready for review

#13271 [onert/nnfw_api] Specify loss per epoch in GenModelTrain tests
  tests/nnfw_api/lib/GenModelTrain.h
  tests/nnfw_api/src/GenModelTests/BranchModelTrain.test.cc
  tests/nnfw_api/src/GenModelTests/nontrainable_op_trains/MaxPool2D.test.cc
  tests/nnfw_api/src/GenModelTests/nontrainable_op_trains/Mean.test.cc
  tests/nnfw_api/src/GenModelTests/nontrainable_op_trains/Pad.test.cc
  tests/nnfw_api/src/GenModelTests/nontrainable_op_trains/Relu.test.cc
  tests/nnfw_api/src/GenModelTests/nontrainable_op_trains/Relu6.test.cc
  tests/nnfw_api/src/GenModelTests/nontrainable_op_trains/Reshape.test.cc
  tests/nnfw_api/src/GenModelTests/nontrainable_op_trains/Softmax.test.cc
  tests/nnfw_api/src/GenModelTests/one_op_trains/Conv2D.test.cc
  tests/nnfw_api/src/GenModelTests/one_op_trains/DepthwiseConvolution.test.cc
  tests/nnfw_api/src/GenModelTests/one_op_trains/FullyConnected.test.cc
Labels: PR/ready for review

#13280 [onert] Change API status condition
  runtime/onert/api/nnfw/include/nnfw.h
  runtime/onert/api/nnfw/src/nnfw_api_internal.cc
  tests/nnfw_api/src/NNPackageTests/AddModelLoaded.test.cc
  tests/nnfw_api/src/NNPackageTests/SessionCreated.test.cc
Labels: PR/ready for review, approval: 2

#13285 [one-cmds] Add warning message on target related process
  compiler/one-cmds/dummy-driver/src/dummy-compile.cpp
  compiler/one-cmds/dummy-driver/src/dummy-compiler.cpp
  compiler/one-cmds/one-codegen
  compiler/one-cmds/one-profile
  compiler/one-cmds/onelib/argumentparse.py
  compiler/one-cmds/tests/onecc_066.cfg
  compiler/one-cmds/tests/onecc_066.ini
  compiler/one-cmds/tests/onecc_066.py
  compiler/one-cmds/tests/onecc_066.test
Labels: PR/ready for review

#13295 [luci] Use auto & instead of auto
  compiler/luci/export/src/CircleExporterImpl.cpp
  compiler/luci/export/src/CircleTensorExporter.cpp
  compiler/luci/pass/src/CircleQuantizer.cpp
Labels: PR/ready for review

#13296 [one-cmds] Fix target option
  compiler/one-cmds/onelib/CfgRunner.py
  compiler/one-cmds/tests/onecc_067.cfg
  compiler/one-cmds/tests/onecc_067.ini
  compiler/one-cmds/tests/onecc_067.py
  compiler/one-cmds/tests/onecc_067.test
Labels: PR/ready for review

#13294 [luci] Add nullptr check
  compiler/luci/pass/src/QuantizeWithPredecessorPass.cpp
Labels: PR/ready for review

#13281 [onert] Update status on quantize and codegen
  runtime/onert/api/nnfw/src/nnfw_api_internal.cc
Labels: PR/ready for review

#13299 [onert] Add static_cast in CircleExporter
  runtime/onert/core/src/exporter/CircleExporter.cc
Labels: PR/ready for review, approval: 1

#13261 [tools/circle_plus_gen] support fine-tuning feature
  tools/circle_plus_gen/README.md
  tools/circle_plus_gen/example/tparam_sgd_scce.json
  tools/circle_plus_gen/example/train_tparam.json
  tools/circle_plus_gen/how-to-write-tparam-json.md
  tools/circle_plus_gen/lib/json_parser.py
  tools/circle_plus_gen/lib/train_param.py
  tools/circle_plus_gen/main.py
Labels: PR/ready for review, approval: 2

#13301 [ahub] Fix tc checker config
  .ahub/tcchecker-tca/config.yaml
Labels: PR/ready for review

#13298 [one-cmds] Add comments about command schema
  compiler/one-cmds/onelib/argumentparse.py
Labels: PR/ready for review

#13297 [onert] Add overflow check in MinMaxReader
  runtime/onert/odc/MinMaxReader.cc
Labels: PR/ready for review, approval: 1

#13302 [infra] Fix compiler TC checker config
  .ahub/tcchecker-tca/config.yaml
Labels: PR/ready for review, approval: 1

#13303 [onert/test] Add SUCCEED to unittest
  compute/cker/src/train/Conv.test.cc
  tests/nnfw_api/src/GenModelTests/nontrainable_op_trains/Add.test.cc
  tests/nnfw_api/src/GenModelTests/nontrainable_op_trains/MaxPool2D.test.cc
  tests/nnfw_api/src/GenModelTests/nontrainable_op_trains/Mean.test.cc
  tests/nnfw_api/src/GenModelTests/nontrainable_op_trains/Mul.test.cc
  tests/nnfw_api/src/GenModelTests/nontrainable_op_trains/Pad.test.cc
  tests/nnfw_api/src/GenModelTests/nontrainable_op_trains/Relu.test.cc
  tests/nnfw_api/src/GenModelTests/nontrainable_op_trains/Relu6.test.cc
  tests/nnfw_api/src/GenModelTests/nontrainable_op_trains/Reshape.test.cc
  tests/nnfw_api/src/GenModelTests/nontrainable_op_trains/Softmax.test.cc
  tests/nnfw_api/src/GenModelTests/nontrainable_op_trains/Sub.test.cc
Labels: PR/ready for review, approval: 1

#13310 Release note 1.27.0
  docs/release/1.27/index.rst
  docs/release/1.27/release-note-1.27.0.md
Labels: type/release

#13311 [debian] Update changelog for version 1.27.0
  infra/debian/compiler/changelog
Labels: type/release

#13300 [onert] Change ODC input file setting
  runtime/onert/api/nnfw/src/nnfw_api_internal.cc
  runtime/onert/core/include/odc/CodegenManager.h
  runtime/onert/core/include/odc/QuantizeManager.h
  runtime/onert/core/src/odc/CodegenManager.cc
  runtime/onert/core/src/odc/QuantizeManager.cc
  runtime/onert/core/src/odc/QuantizeManager.test.cc
Labels: PR/ready for review

#13312 [vconone] Bump up to 1.28.0
  compiler/vconone/CMakeLists.txt
Labels: PR/ready for review

#13314 [onert] Reset compile result after reload
  runtime/onert/api/nnfw/src/nnfw_api_internal.cc
  runtime/onert/api/nnfw/src/nnfw_api_internal.h
Labels: PR/ready for review

#13319 [onert] Bump up to 1.28.0
  docs/conf.py
  packaging/nnfw.spec
  runtime/contrib/android/api/build.gradle
  runtime/onert/api/nnfw/include/nnfw_version.h
Labels: PR/ready for review

#13322 [luci-interpreter] Support int64 type in StridedSlice op
  compiler/luci-interpreter/src/kernels/StridedSlice.cpp
Labels: PR/ready for review
