Repository Samsung/ONE, pull requests merged in 2024-02, with the labels that each got.

#12577 [tools/onert_train] Rename toString() to to_string()
  tests/tools/onert_train/src/nnfw_util.cc
  tests/tools/onert_train/src/nnfw_util.h
Labels: PR/ready for review, trivial, approval: 1

#12556 [onert/libs] Add to_underlying to misc
  runtime/libs/misc/include/misc/to_underlying.h
Labels: PR/ready for review, approval: 2

#12554 [cker] Introduce Multiply gradient kernel
  compute/cker/include/cker/train/operation/BinaryArithmetic.h
  compute/cker/src/train/BinaryArithmetic.test.cc
  runtime/onert/backend/train/ops/BinaryArithmeticLayer.cc
Labels: PR/ready for review, approval: 2

#12579 [one-cmds] Support for FoldShape pass
  compiler/one-cmds/how-to-use-one-commands.txt
  compiler/one-cmds/onelib/constant.py
Labels: PR/ready for review, approval: 2

#12586 [onert] Initialize PadLayer
  runtime/onert/backend/cpu/ops/PadLayer.cc
Labels: PR/ready for review

#12587 [onert] Check metadata buffer
  runtime/onert/core/src/loader/base_loader.h
Labels: PR/ready for review

#12545 [tools/onert_train] Revise args to hold NNFW_TRAIN_* enum
  tests/tools/onert_train/src/args.cc
  tests/tools/onert_train/src/args.h
  tests/tools/onert_train/src/onert_train.cc
Labels: PR/ready for review, approval: 2

#12588 [onert] Initialize train BinaryArithmeticLayer
  runtime/onert/backend/train/ops/BinaryArithmeticLayer.cc
Labels: PR/ready for review

#12589 [onert] Introduce ILoader
  runtime/onert/core/include/loader/ILoader.h
Labels: PR/ready for review, approval: 2

#12592 [onert] Remove copy by auto in train_get_traininfo
  runtime/onert/api/nnfw/src/nnfw_api_internal.cc
Labels: PR/ready for review, approval: 1

#12591 [onert/train] Remove copy by auto in KernelGenerator
  runtime/onert/backend/train/KernelGenerator.cc
Labels: PR/ready for review, approval: 1

#12583 [onert/api] Introduce nnfw_compile and nnfw_set_compiled_model_path APIs
  runtime/onert/api/nnfw/include/nnfw_experimental.h
  runtime/onert/api/nnfw/src/nnfw_api.cc
  runtime/onert/api/nnfw/src/nnfw_api_internal.cc
  runtime/onert/api/nnfw/src/nnfw_api_internal.h
Labels: PR/ready for review

#12585 [cker] Add more BinaryArithmeticDistinctShape tests
  compute/cker/src/train/BinaryArithmetic.test.cc
Labels: PR/ready for review, approval: 2

#12594 [onert] Support plugin model loader
  runtime/onert/api/nnfw/src/nnfw_api_internal.cc
  runtime/onert/core/include/loader/ModelLoader.h
  runtime/onert/core/src/loader/ModelLoader.cc
Labels: PR/ready for review

#12608 [onert] Fix missing throw expression
  runtime/onert/core/src/ir/train/TrainableGraph.cc
Labels: PR/ready for review

#12584 [tools/onert_run] Implement codegen function
  tests/tools/onert_run/src/args.cc
  tests/tools/onert_run/src/args.h
  tests/tools/onert_run/src/onert_run.cc
Labels: PR/ready for review

#12607 [onert/core] Update circle_traininfo to support loss reduction type
  runtime/onert/core/src/loader/circle_traininfo.fbs
  runtime/onert/core/src/loader/circle_traininfo_generated.h
Labels: PR/ready for review, approval: 2

#12609 [onert/core] Update traininfo_loader to support loss reduction type
  runtime/onert/core/src/loader/traininfo_loader.cc
Labels: PR/ready for review, approval: 2

#12610 [infra] Revise TFLite GPU delegate library
  infra/nnfw/cmake/packages/TensorFlowGpuConfig.cmake
  infra/nnfw/cmake/packages/TensorFlowLiteGpu/CMakeLists.txt
  runtime/onert/backend/gpu_cl/CMakeLists.txt
Labels: PR/ready for review

#12611 [infra/onert] Fix cmake find mode on android
  infra/nnfw/cmake/buildtool/cross/toolchain_aarch64-android.cmake
Labels: PR/ready for review

#12613 [onert] Fix btopolSortOperations
  runtime/onert/core/src/ir/train/TrainableGraph.cc
  runtime/onert/core/src/ir/train/TrainableGraph.test.cc
Labels: PR/ready for review, approval: 2

#12614 [onert] Clean up gpu-cl backend cmake
  runtime/onert/backend/gpu_cl/CMakeLists.txt
Labels: PR/ready for review

#12615 [luci/pass] Add note comments to know about ResolveCustomOpAddPass
  compiler/luci/pass/src/ResolveCustomOpAddPass.cpp
Labels: PR/ready for review

#12595 [onert-micro] Add import part
  onert-micro/onert-micro/include/import/OMConfigureArgs.h
  onert-micro/onert-micro/include/import/OMExecutionPlanCreator.h
  onert-micro/onert-micro/include/import/OMKernelConfiguration.h
  onert-micro/onert-micro/include/import/OMKernelConfigureBuilder.h
  onert-micro/onert-micro/src/import/CMakeLists.txt
  onert-micro/onert-micro/src/import/OMExecutionPlanCreator.cpp
  onert-micro/onert-micro/src/import/OMKernelConfiguration.cpp
  onert-micro/onert-micro/src/import/OMKernelConfigureBuilder.cpp
Labels: approval: 2

#12596 [onert-micro] Add optimize part
  onert-micro/onert-micro/include/optimize/BuildPass.lst
  onert-micro/onert-micro/include/optimize/OMGraphStatus.h
  onert-micro/onert-micro/include/optimize/OMOptimizePassesBuilder.h
  onert-micro/onert-micro/include/optimize/OMOptimizer.h
  onert-micro/onert-micro/src/optimize/CMakeLists.txt
  onert-micro/onert-micro/src/optimize/OMOptimizer.cpp
  onert-micro/onert-micro/src/optimize/pass/FindInplaceOpPass.cpp
Labels: approval: 2

#12618 [onert] Strip NNAPI frontend library
  runtime/onert/api/nnapi/CMakeLists.txt
Labels: PR/ready for review

#12509 [luci/pass] Revise ResolveCustomOpAddPass to process BroadcastTo
  compiler/luci/pass/src/ResolveCustomOpAddPass.cpp
  compiler/luci/pass/src/ResolveCustomOpAddPass.test.cpp
Labels: PR/ready for review

#12627 [res] Revise Net_BroadcastTo_AddV2_002 test.rule
  res/TensorFlowLiteRecipes/Net_BroadcastTo_AddV2_002/test.rule
Labels: PR/ready for review

#12628 [circle2circle-dredd-test] Add Net_BroadcastTo_AddV2_002 test
  compiler/circle2circle-dredd-recipe-test/test.lst
Labels: PR/ready for review

#12633 [luci-pass-value-py-test] Remove unused variable
  compiler/luci-pass-value-py-test/test_luci_eval.py
Labels: PR/ready for review

#12634 [pota-quantization-value-test] Set right mode
  compiler/pota-quantization-value-test/compare_tensors_all.py
  compiler/pota-quantization-value-test/test_fake_wquant_with_config.sh
  compiler/pota-quantization-value-test/test_parallel_record_minmax.sh
  compiler/pota-quantization-value-test/test_quantization_with_config.sh
Labels: PR/ready for review

#12622 [ONERT] Add index comparison operator
  runtime/onert/core/include/util/Index.h
  runtime/onert/core/src/ir/train/TrainableGraph.cc
Labels: PR/ready for review, approval: 2

#12597 [res] Add GRU in CircleSchema
  res/CircleSchema/0.8/circle_schema.fbs
Labels: approval: 2

#12654 [luci] Remove copy by auto
  compiler/luci/pass/src/CircleQuantizer.cpp
  compiler/luci/pass/src/FoldFullyConnectedPass.cpp
  compiler/luci/service/src/CircleShapeInferenceRule.cpp
Labels: PR/ready for review

#12656 [onert] Remove copy by auto
  runtime/onert/backend/trix/KernelGenerator.cc
  runtime/onert/core/src/compiler/StaticShapeInferer.cc
Labels: PR/ready for review

#12651 [onert-micro] Add Add kernel
  onert-micro/onert-micro/include/pal/common/PALAddCommon.h
  onert-micro/onert-micro/include/pal/common/PALArithmeticOpCommon.h
  onert-micro/onert-micro/include/pal/common/PALUtils.h
  onert-micro/onert-micro/include/pal/common/ProcessBroadcastShapes.h
  onert-micro/onert-micro/include/pal/mcu/KernelsToBuild.lst
  onert-micro/onert-micro/include/pal/mcu/PALAdd.h
  onert-micro/onert-micro/include/test_models/add/FloatAddKernel.h
  onert-micro/onert-micro/include/test_models/add/IntAddKernel.h
  onert-micro/onert-micro/include/test_models/add/NegAddKernel.h
  onert-micro/onert-micro/include/test_models/add/TestDataAddBase.h
  onert-micro/onert-micro/src/execute/kernels/Add.cpp
  onert-micro/onert-micro/src/execute/kernels/tests/Add.test.cpp
  onert-micro/onert-micro/src/import/kernels/Add.cpp
Labels: approval: 2

#12652 [onert-micro] Add Concatenation kernel
  onert-micro/onert-micro/include/pal/common/PALConcatenation.h
  onert-micro/onert-micro/include/pal/mcu/KernelsToBuild.lst
  onert-micro/onert-micro/include/test_models/concatenation/FloatConcatenationKernel.h
  onert-micro/onert-micro/include/test_models/concatenation/IntConcatenationKernel.h
  onert-micro/onert-micro/include/test_models/concatenation/NegConcatenationKernel.h
  onert-micro/onert-micro/include/test_models/concatenation/TestDataConcatenationBase.h
  onert-micro/onert-micro/src/execute/kernels/Concatenation.cpp
  onert-micro/onert-micro/src/execute/kernels/tests/Concatenation.test.cpp
  onert-micro/onert-micro/src/import/kernels/Concatenation.cpp
Labels: approval: 2

#12669 [onert] Use FlatBuffers 23.5.26
  packaging/FLATBUFFERS-23.5.26.tar.gz
  packaging/nnfw.spec
  runtime/libs/circle-schema/CMakeLists.txt
  runtime/libs/circle-schema/include/circle_schema_generated.h
  runtime/onert/core/CMakeLists.txt
  runtime/onert/core/src/loader/circle_traininfo_generated.h
  runtime/onert/core/src/loader/tflite_schema_generated.h
  tests/custom_op/CMakeLists.txt
Labels: PR/ready for review

#12623 [ONERT] Add hasTrainableParameter member function
  runtime/onert/core/include/ir/train/ITrainableOperation.h
  runtime/onert/core/include/ir/train/operation/BinaryArithmetic.h
  runtime/onert/core/include/ir/train/operation/Conv2D.h
  runtime/onert/core/include/ir/train/operation/DepthwiseConv2D.h
  runtime/onert/core/include/ir/train/operation/ElementwiseActivation.h
  runtime/onert/core/include/ir/train/operation/FullyConnected.h
  runtime/onert/core/include/ir/train/operation/Loss.h
  runtime/onert/core/include/ir/train/operation/Pad.h
  runtime/onert/core/include/ir/train/operation/Permute.h
  runtime/onert/core/include/ir/train/operation/Pool2D.h
  runtime/onert/core/include/ir/train/operation/Reduce.h
  runtime/onert/core/include/ir/train/operation/Reshape.h
  runtime/onert/core/include/ir/train/operation/Softmax.h
  runtime/onert/core/include/ir/train/operation/UntrainableOperation.h
Labels: PR/ready for review, approval: 2

#12681 [onert] Rename loader file and namespace
  runtime/onert/api/nnfw/src/nnfw_api_internal.cc
  runtime/onert/core/include/loader/CircleLoader.h
  runtime/onert/core/include/loader/TFLiteLoader.h
  runtime/onert/core/include/loader/TrainInfoLoader.h
  runtime/onert/core/src/loader/BaseLoader.h
  runtime/onert/core/src/loader/CircleLoader.cc
  runtime/onert/core/src/loader/TFLiteLoader.cc
  runtime/onert/core/src/loader/TrainInfoLoader.cc
Labels: PR/ready for review

#12680 [onert] Move generated traininfo header
  .ahub/sam/exclude.txt
  runtime/libs/circle-schema/include/circle_traininfo.fbs
  runtime/libs/circle-schema/include/circle_traininfo_generated.h
  tests/nnfw_api/CMakeLists.txt
Labels: PR/ready for review

#12684 [onert] Change trix loader to plugin
  runtime/onert/api/nnfw/CMakeLists.txt
  runtime/onert/api/nnfw/src/nnfw_api_internal.cc
  runtime/onert/loader/trix/CMakeLists.txt
  runtime/onert/loader/trix/TrixLoader.cc
  runtime/onert/loader/trix/include/trix_loader.h
  runtime/onert/loader/trix/src/trix_loader_dummy.cc
Labels: PR/ready for review

#12673 [onert] Optimize Bias Grad Computation
  compute/cker/include/cker/eigen/redux_functor.h
  runtime/onert/backend/train/ops/ConvolutionLayer.cc
  runtime/onert/backend/train/ops/DepthwiseConvolutionLayer.cc
  runtime/onert/backend/train/ops/OperationUtils.cc
  runtime/onert/backend/train/ops/OperationUtils.h
Labels: PR/ready for review, approval: 2

#12687 [onert-micro] Add Logistic kernel
  onert-micro/onert-micro/include/pal/common/PALLogistic.h
  onert-micro/onert-micro/include/pal/mcu/KernelsToBuild.lst
  onert-micro/onert-micro/include/test_models/logistic/FloatLogisticKernel.h
  onert-micro/onert-micro/include/test_models/logistic/NegLogisticKernel.h
  onert-micro/onert-micro/include/test_models/logistic/TestDataLogisticBase.h
  onert-micro/onert-micro/src/execute/kernels/Logistic.cpp
  onert-micro/onert-micro/src/execute/kernels/tests/Logistic.test.cpp
  onert-micro/onert-micro/src/import/kernels/Logistic.cpp
Labels: approval: 2

#12699 [tools/dataset_converter] Add the mnist dataset
  tools/generate_datafile/tf_dataset_converter/datasets.py
Labels: PR/ready for review, approval: 1

#12698 [tools/onert_train] Add onert_train usage to readme
  tests/tools/onert_train/README.md
Labels: PR/ready for review, approval: 2
