Repository Samsung/ONE, pull requests merged in 2024-08, with the labels that each got.

#13565 [onert] Remove PermutationOperationPass
  runtime/onert/core/src/compiler/LoweredGraph.cc
  runtime/onert/core/src/compiler/pass/PermutationOperationPass.cc
  runtime/onert/core/src/compiler/pass/PermutationOperationPass.h
  runtime/onert/core/src/compiler/train/LoweredTrainableGraph.cc
Labels: PR/ready for review

#13546 [onert] Revisit DepthwiseConv train cker
  compute/cker/include/cker/eigen/EigenSupport.h
  compute/cker/include/cker/train/operation/DepthwiseConv.h
  compute/cker/src/train/DepthwiseConv.test.cc
  runtime/onert/backend/train/ops/DepthwiseConvolutionLayer.cc
  runtime/onert/backend/train/ops/DepthwiseConvolutionLayer.h
Labels: PR/ready for review

#13569 [onert/test] Remove nnpackage and modelfile options
  docs/howto/how-to-build-runtime-tizen-gbs-rpi4.md
  docs/runtime/transfer_learning.md
  tests/scripts/benchmark.sh
  tests/scripts/command/nnpkg-test
  tests/tools/onert_run/src/args.cc
  tests/tools/onert_train/README.md
  tests/tools/onert_train/src/args.cc
  tools/stab/remote.py
Labels: PR/ready for review

#13572 [onert] Simplify OperationLowerInfo usage
  runtime/onert/backend/ruy/BackendContext.h
  runtime/onert/core/include/backend/BackendContext.h
  runtime/onert/core/include/compiler/CodeMap.h
  runtime/onert/core/include/compiler/GraphLowerInfo.h
  runtime/onert/core/include/compiler/OperationLowerInfo.h
  runtime/onert/core/include/compiler/train/TrainableCodeMap.h
  runtime/onert/core/src/backend/builtin/BackendContext.h
  runtime/onert/core/src/compiler/ExecutorFactory.cc
  runtime/onert/core/src/compiler/LoweredGraph.cc
  runtime/onert/core/src/compiler/OperationLowerInfo.cc
  runtime/onert/core/src/compiler/pass/ConstantInsertionPass.cc
  runtime/onert/core/src/compiler/pass/ConstantLoweringPass.cc
  runtime/onert/core/src/compiler/pass/PermutationInsertionPass.cc
  runtime/onert/core/src/compiler/train/LoweredTrainableGraph.cc
  runtime/onert/core/src/compiler/train/pass/TrainableConstantInsertionPass.cc
  runtime/onert/core/src/dumper/dot/DotDumper.cc
  runtime/onert/core/src/exec/DataflowExecutor.cc
  runtime/onert/core/src/exec/LinearExecutor.cc
  runtime/onert/core/src/exec/ParallelExecutor.cc
  runtime/onert/core/src/exec/train/TrainableExecutor.cc
Labels: PR/ready for review

#13559 [onert] Revisit DepthwiseConv2D nnfw_api test
  tests/nnfw_api/src/GenModelTests/one_op_tests/DepthwiseConv2D.test.cc
Labels: PR/ready for review

#13571 [onert] Revise generating tensors for training
  runtime/onert/backend/train/BackendContext.cc
  runtime/onert/backend/train/BackendContext.h
Labels: PR/ready for review

#13578 [onnx-tools] Support onnx model over 2GB
  compiler/onnx-tools/onnx-dump.py
  compiler/onnx-tools/onnx-ops.py
Labels: PR/ready for review

#13580 [conrtib] Remove benchmark_acl
  infra/nnfw/cmake/CfgOptionFlags.cmake
  runtime/contrib/benchmark_acl/.FORMATDENY
  runtime/contrib/benchmark_acl/CMakeLists.txt
  runtime/contrib/benchmark_acl/src/Benchmark.cpp
  runtime/contrib/benchmark_acl/src/Benchmark.h
  runtime/contrib/benchmark_acl/src/benchmark_googlenet.cpp
  runtime/contrib/benchmark_acl/src/benchmark_inception_v3.cpp
  runtime/contrib/benchmark_acl/src/benchmark_mobilenet.cpp
Labels: PR/ready for review

#13579 [onert/contrib] Remove boost dependency in style_tranfer_app
  runtime/contrib/style_transfer_app/CMakeLists.txt
  runtime/contrib/style_transfer_app/src/args.cc
  runtime/contrib/style_transfer_app/src/args.h
Labels: PR/ready for review, approval: 1

#13577 [onert] Simplify OperandLowerInfo
  runtime/onert/core/include/compiler/OperandLowerInfo.h
  runtime/onert/core/src/compiler/ExecutorFactory.cc
  runtime/onert/core/src/compiler/LoweredGraph.cc
  runtime/onert/core/src/compiler/pass/ConstantLoweringPass.cc
  runtime/onert/core/src/compiler/pass/PermutationEliminationPass.cc
  runtime/onert/core/src/compiler/pass/PermutationInsertionPass.cc
  runtime/onert/core/src/compiler/pass/PermutationInsertionPass.h
  runtime/onert/core/src/compiler/train/LoweredTrainableGraph.cc
  runtime/onert/core/src/compiler/train/pass/TrainableConstantInsertionPass.cc
  runtime/onert/core/src/dumper/dot/DotDumper.cc
Labels: PR/ready for review

#13582 [onert] Use maybe_unused attribute for local variable in bias_op kernel
  compute/cker/include/cker/eigen/bias_op.h
Labels: PR/ready for review, approval: 1

#13576 [onert] Introduce ExtraTensor
  runtime/onert/core/include/backend/train/ExtraTensor.h
Labels: PR/ready for review, approval: 2

#13581 [infra/onert] Remove boost usage on infra resources
  Makefile.template
  docs/howto/how-to-build-runtime.md
  docs/howto/how-to-cross-build-runtime-for-arm.md
  infra/nnfw/CMakeLists.txt
  infra/nnfw/cmake/CfgOptionFlags.cmake
  infra/nnfw/cmake/options/options_aarch64-android.cmake
  infra/nnfw/cmake/options/options_aarch64-tizen.cmake
  infra/nnfw/cmake/options/options_armv7hl-tizen.cmake
  infra/nnfw/cmake/options/options_armv7l-tizen.cmake
  infra/nnfw/cmake/options/options_x86_64-tizen.cmake
  infra/nnfw/cmake/packages/BoostConfig.cmake
  packaging/nnfw.spec
  tests/tools/onert_train/README.md
  tools/cross/install_rootfs.sh
  tools/kbenchmark/Args.h
Labels: PR/ready for review

#13584 [github] Use cache for android externals
  .github/workflows/run-onert-android-build.yml
Labels: PR/ready for review

#13570 [onert] Generate BackPropAccumulator only if necessary
  runtime/onert/backend/train/KernelGenerator.cc
  runtime/onert/backend/train/KernelGenerator.h
Labels: PR/ready for review

#13591 [infra] Remove npud test script
  infra/scripts/test_ubuntu_npud.sh
Labels: PR/ready for review, approval: 1

#13596 [one-cmds] Set env variables when running sub-command
  compiler/one-cmds/onelib/utils.py
  compiler/one-cmds/tests/one-codegen_012.cfg
  compiler/one-cmds/tests/one-codegen_012.test
Labels: PR/ready for review

#13587 [infra] Introduce github workflow for onecc
  .github/workflows/run-onecc-build.yml
Labels: PR/ready for review

#13598 [github] Enable onecc test workflow trigger on push evnet
  .github/workflows/run-onecc-build.yml
Labels: PR/ready for review

#13594 [onert] Remove Permute IR handling in general backend
  runtime/onert/backend/acl_cl/KernelGenerator.cc
  runtime/onert/backend/acl_cl/KernelGenerator.h
  runtime/onert/backend/acl_neon/KernelGenerator.cc
  runtime/onert/backend/acl_neon/KernelGenerator.h
  runtime/onert/core/src/compiler/pass/PermutationInsertionPass.cc
Labels: PR/ready for review

#13600 [onert] Use default cpu planner for training
  runtime/onert/backend/train/Backend.h
  runtime/onert/backend/train/MemoryManager.cc
  runtime/onert/backend/train/MemoryManager.h
  runtime/onert/backend/train/TensorBuilder.cc
  runtime/onert/backend/train/TensorBuilder.h
  runtime/onert/backend/train/TensorManager.cc
  runtime/onert/backend/train/TensorManager.h
Labels: PR/ready for review

#13601 [onert] Fix wrong allocation of optimizer variables
  runtime/onert/backend/train/MemoryManager.cc
  runtime/onert/backend/train/MemoryManager.h
  runtime/onert/backend/train/TensorManager.cc
  runtime/onert/backend/train/TensorManager.h
Labels: PR/ready for review

#13599 [infra/onert] Rename debian package
  infra/debian/runtime/control
  infra/debian/runtime/onert-dev.install
  infra/debian/runtime/onert-plugin-dev.install
  infra/debian/runtime/onert.install
  infra/debian/runtime/rules
  packaging/nnfw-plugin.pc.in
  packaging/nnfw.pc.in
Labels: PR/ready for review

#13605 [onert] Introduce ExtraTensorIndex
  runtime/onert/backend/train/ExtraTensorIndex.h
Labels: PR/ready for review, approval: 2

#13589 [onert] Remove type in Permute IR
  runtime/onert/core/include/ir/operation/Permute.h
  runtime/onert/core/src/compiler/pass/ConstantOutputPass.cc
  runtime/onert/core/src/compiler/pass/OddOutputPass.cc
  runtime/onert/core/src/compiler/pass/PermutationInsertionPass.cc
  runtime/onert/core/src/ir/OperationDumper.cc
  runtime/onert/core/src/ir/operation/Permute.cc
  runtime/onert/core/src/ir/train/operation/Permute.cc
  runtime/onert/core/src/ir/train/operation/UntrainableOperation.test.cc
Labels: PR/ready for review

#13618 [github] Update android build workflow
  .github/workflows/run-onert-android-build.yml
Labels: PR/ready for review

#13574 [onert] Introduce DepthwiseConvOp in cpu kernel
  compute/cker/include/cker/operation/DepthwiseConv.h
  compute/cker/src/DepthwiseConv.test.cc
Labels: PR/ready for review

#13631 [onert] Unify interface for generating tensors
  runtime/onert/backend/train/BackendContext.cc
  runtime/onert/backend/train/BackendContext.h
  runtime/onert/core/include/backend/train/TrainableBackendContext.h
  runtime/onert/core/src/backend/builtin/train/BackendContext.cc
  runtime/onert/core/src/backend/builtin/train/BackendContext.h
  runtime/onert/core/src/compiler/ExecutorFactory.cc
Labels: PR/ready for review

#13619 [github] Add ubuntu 22.04 test to onecc workflow
  .github/workflows/run-onecc-build.yml
Labels: PR/ready for review

#13635 [onert] Remove layout info in BackendContext
  runtime/onert/backend/cl_common/include/cl_common/BackendContext.h
  runtime/onert/core/include/backend/BackendContext.h
  runtime/onert/core/include/backend/basic/BackendContextHelpers.h
  runtime/onert/core/src/compiler/ExecutorFactory.cc
Labels: PR/ready for review

#13658 [onert] Reallocated tensor when size becomes larger
  runtime/onert/core/include/backend/basic/Tensor.h
  runtime/onert/core/src/backend/basic/Tensor.cc
Labels: PR/ready for review

#13654 [onert/onert_run] Allow shape_prepare and shape_run together
  tests/tools/onert_run/src/args.cc
Labels: PR/ready for review

#13669 [onert] Use DepthwiseConvOp cpu kernel
  runtime/onert/backend/cpu/ops/DepthwiseConvolutionLayer.cc
  runtime/onert/backend/cpu/ops/DepthwiseConvolutionLayer.h
  runtime/onert/backend/train/ops/DepthwiseConvolutionLayer.cc
  runtime/onert/backend/train/ops/DepthwiseConvolutionLayer.h
Labels: PR/ready for review

#13656 [onert] Unify generating training tensors and kernels
  runtime/onert/backend/train/BackendContext.cc
  runtime/onert/backend/train/BackendContext.h
  runtime/onert/core/include/backend/train/TrainableBackendContext.h
  runtime/onert/core/src/backend/builtin/train/BackendContext.cc
  runtime/onert/core/src/backend/builtin/train/BackendContext.h
  runtime/onert/core/src/compiler/ExecutorFactory.cc
Labels: PR/ready for review

#13583 [onert] Revisits python API
  docs/howto/how-to-use-nnfw-python-api.md
  infra/nnfw/python/.gitignore
  infra/nnfw/python/README.md
  infra/nnfw/python/setup.py
  runtime/onert/api/python/package/__init__.py
  runtime/onert/api/python/package/infer.py
  runtime/onert/sample/minimal-python/src/minimal.py
Labels: PR/ready for review

#13680 [onert-micro] fix build error with cmsisnn
  onert-micro/onert-micro/include/pal/cmsisnn/PALArgMax.h
Labels: approval: 1

#13689 [onert] Fix DepthwiseConvOp kernel condition
  runtime/onert/backend/cpu/ops/DepthwiseConvolutionLayer.cc
Labels: PR/ready for review, approval: 1

#13704 [doc] Add ONERT Training document
  docs/runtime/training.md
Labels: PR/ready for review

#13716 [onert] Remove PermuteFactor
  runtime/onert/core/include/compiler/PermuteFactor.h
  runtime/onert/core/src/compiler/PermuteFactor.cc
  runtime/onert/core/src/compiler/pass/ConstantInsertionPass.cc
  runtime/onert/core/src/compiler/pass/ConstantInsertionPass.h
  runtime/onert/core/src/compiler/pass/ConstantLoweringPass.cc
  runtime/onert/core/src/compiler/pass/PermutationInsertionPass.h
Labels: PR/ready for review

#13722 [onert] Add ir namespace to checkpoint header file
  runtime/onert/core/include/ir/train/Checkpoint.h
Labels: PR/ready for review, approval: 1

#13718 [github] Run workflow jobs only in Samsung org
  .github/workflows/check-format.yml
  .github/workflows/check-pr-commit.yml
  .github/workflows/run-onert-android-build.yml
  .github/workflows/run-onert-micro-unit-tests.yml
Labels: PR/ready for review

#13711 [onert/cpu] Support INT64 BinaryArithemtic operation
  compute/cker/include/cker/Types.h
  compute/cker/include/cker/operation/reference/BinaryArithmeticOps.h
  compute/cker/src/Mul.test.cc
  runtime/onert/backend/cpu/ops/BinaryArithmeticLayer.cc
Labels: PR/ready for review

#13720 [onert] Introduce checkpoint apis
  runtime/onert/api/nnfw/include/nnfw_experimental.h
  runtime/onert/api/nnfw/src/nnfw_api.cc
  runtime/onert/api/nnfw/src/nnfw_api_internal.cc
  runtime/onert/api/nnfw/src/nnfw_api_internal.h
Labels: PR/ready for review

#13733 [luci-interpreter] Support InstanceNorm 3D kernel
  compiler/luci-interpreter/src/kernels/InstanceNorm.cpp
  compiler/luci-interpreter/src/kernels/InstanceNorm.test.cpp
Labels: PR/ready for review

#13739 [compute/cker] Add big integer mul test
  compute/cker/src/Mul.test.cc
Labels: PR/ready for review

#13724 [doc] Add training CNN model on MNIST
  docs/runtime/training.md
  docs/runtime/training_cnn_on_mnist.md
Labels: PR/ready for review

#13719 [onert-micro] Add svdf cmsis-nn
  onert-micro/onert-micro/include/core/OMKernelData.h
  onert-micro/onert-micro/include/pal/cmsisnn/KernelsToBuild.lst
  onert-micro/onert-micro/include/pal/cmsisnn/PALSVDF.h
  onert-micro/onert-micro/include/pal/mcu/PALSVDF.h
  onert-micro/onert-micro/src/execute/kernels/SVDF.cpp
Labels: PR/ready for review

#13593 [onert-micro] Introduce training configure tool
  onert-micro/CMakeLists.txt
  onert-micro/training-configure-tool/CMakeLists.txt
  onert-micro/training-configure-tool/TrainingConfigureTool.cpp
  onert-micro/training-configure-tool/include/SparseBackpropagationHandler.h
  onert-micro/training-configure-tool/include/SparseBackpropagationHelper.h
  onert-micro/training-configure-tool/include/TensorRankSparseBackpropagationHandler.h
  onert-micro/training-configure-tool/include/TrainConfigData.h
  onert-micro/training-configure-tool/include/TrainingConfigureFileHandler.h
  onert-micro/training-configure-tool/include/TrainingDriverHandler.h
  onert-micro/training-configure-tool/src/SparseBackpropagationHandler.cpp
  onert-micro/training-configure-tool/src/SparseBackpropagationHelper.cpp
  onert-micro/training-configure-tool/src/TensorRankSparseBackpropagationHandler.cpp
  onert-micro/training-configure-tool/src/TrainingConfigureFileHandler.cpp
  onert-micro/training-configure-tool/src/TrainingDriverHandler.cpp
Labels: PR/ready for review

#13744 [onert_train] Introduce some arguments for checkpoint apis
  tests/tools/onert_train/src/args.cc
  tests/tools/onert_train/src/args.h
  tests/tools/onert_train/src/onert_train.cc
Labels: PR/ready for review

#13766 [onert] Remove tensor layout check on permute function
  runtime/onert/core/src/backend/builtin/kernel/PermuteLayer.cc
  runtime/onert/core/src/backend/builtin/train/kernel/PermuteLayer.cc
  runtime/onert/core/src/exec/IPermuteFunction.cc
  runtime/onert/core/src/exec/IPermuteFunction.h
  runtime/onert/core/src/exec/IPermuteFunction.test.cc
Labels: PR/ready for review

#13787 [onert] Remove HDF5 minmax dumper
  infra/nnfw/cmake/CfgOptionFlags.cmake
  runtime/onert/core/CMakeLists.txt
  runtime/onert/core/src/compiler/ExecutorFactory.cc
  runtime/onert/core/src/dumper/h5/Dumper.cc
  runtime/onert/core/src/dumper/h5/Dumper.h
  runtime/onert/core/src/dumper/h5/MinMaxDumper.cc
  runtime/onert/core/src/dumper/h5/MinMaxDumper.h
  runtime/onert/core/src/exec/MinMaxRecorder.cc
Labels: PR/ready for review

#13789 [onert] Use constructor paramter to set permute type
  runtime/onert/core/src/backend/builtin/KernelGenerator.cc
  runtime/onert/core/src/backend/builtin/kernel/PermuteLayer.cc
  runtime/onert/core/src/backend/builtin/kernel/PermuteLayer.h
  runtime/onert/core/src/backend/builtin/kernel/WhileLayer.cc
  runtime/onert/core/src/backend/builtin/train/KernelGenerator.cc
  runtime/onert/core/src/backend/builtin/train/kernel/PermuteLayer.cc
  runtime/onert/core/src/backend/builtin/train/kernel/PermuteLayer.h
  runtime/onert/core/src/exec/IPermuteFunction.h
  runtime/onert/core/src/exec/MultiModelExecutors.cc
  runtime/onert/core/src/exec/SingleModelExecutors.cc
Labels: PR/ready for review

#13799 [onert] Add space to increase readability
  runtime/onert/core/include/ir/train/operation/UntrainableOperation.h
Labels: PR/ready for review, approval: 1

#13783 [onert] Introduce CheckpointExporter to store checkpoint file
  runtime/onert/api/nnfw/src/nnfw_api_internal.cc
  runtime/onert/core/include/exporter/train/CheckpointExporter.h
  runtime/onert/core/src/exporter/train/CheckpointExporter.cc
Labels: PR/ready for review

#13801 [cker] Fix casting warning
  compute/cker/include/cker/eigen/depthwise_conv_op.h
Labels: PR/ready for review

#13809 [luci] Revise FuseBatchNormWithDwConvPass
  compiler/luci/pass/src/FuseBatchNormWithDwConvPass.cpp
Labels: PR/ready for review

#13805 [onert] Use permute type on permute task and coordinate conversion
  runtime/onert/core/include/ir/Coordinates.h
  runtime/onert/core/src/backend/builtin/kernel/PermuteLayer.cc
  runtime/onert/core/src/backend/builtin/kernel/PermuteLayer.h
  runtime/onert/core/src/exec/IPermuteFunction.cc
  runtime/onert/core/src/ir/Coordinates.cc
Labels: PR/ready for review

#13807 [pass] Revise FuseBatchNormWithConvPass
  compiler/luci/pass/src/FuseBatchNormWithConvPass.cpp
Labels: PR/ready for review

#13803 [onert] Use getUses() reference
  runtime/onert/core/src/compiler/train/pass/TrainableConstantInsertionPass.cc
  runtime/onert/core/src/ir/train/UseDefGenerator.cc
Labels: PR/ready for review

#13795 [luci/service] Support MUL dynamic shape inference
  compiler/luci/service/include/luci/Service/CircleShapeInference.h
  compiler/luci/service/src/CircleShapeInferenceRule.cpp
  compiler/luci/service/src/Nodes/CircleMul.cpp
  compiler/luci/service/src/Nodes/CircleMul.test.cpp
Labels: PR/ready for review, SSAFY

#13818 [onert/contrib] Disable logging runtime build as default
  infra/debian/runtime/rules
  infra/nnfw/cmake/CfgOptionFlags.cmake
  infra/nnfw/cmake/options/options_aarch64-android.cmake
  infra/nnfw/cmake/options/options_aarch64-tizen.cmake
  infra/nnfw/cmake/options/options_armv7hl-tizen.cmake
  infra/nnfw/cmake/options/options_armv7l-tizen.cmake
  infra/nnfw/cmake/options/options_i686-tizen.cmake
  infra/nnfw/cmake/options/options_riscv64-tizen.cmake
  infra/nnfw/cmake/options/options_x86_64-tizen.cmake
Labels: PR/ready for review

#13821 [luci] Revise CircleQuantizer
  compiler/luci/pass/include/luci/CircleQuantizer.h
  compiler/luci/pass/src/CircleQuantizer.cpp
Labels: PR/ready for review

#13800 [luci] Reduce multiple if conditions
  compiler/luci/pass/src/CircleOptimizer.cpp
Labels: PR/ready for review

#13822 [circle2circle] Revise driver script
  compiler/circle2circle/src/Circle2Circle.cpp
Labels: PR/ready for review

#13812 [luci/service] Migrate Quantize shape inference rule to sinf::Algorithm
  compiler/luci/service/include/luci/Service/CircleShapeInference.h
  compiler/luci/service/src/CircleShapeInferenceRule.cpp
  compiler/luci/service/src/Nodes/CircleQuantize.cpp
  compiler/luci/service/src/Nodes/CircleQuantize.test.cpp
Labels: PR/ready for review, SSAFY

#13828 [tflchef] Add const reference
  compiler/tflchef/core/src/ModelChef.cpp
Labels: PR/ready for review

#13813 [onert] Remove shape conversion function duplication
  runtime/onert/core/include/ir/Shape.h
  runtime/onert/core/src/backend/builtin/kernel/PermuteLayer.cc
  runtime/onert/core/src/exec/ExecutorBase.cc
  runtime/onert/core/src/exec/ShapeConverter.cc
  runtime/onert/core/src/exec/ShapeConverter.h
  runtime/onert/core/src/ir/Shape.cc
Labels: PR/ready for review

#13831 [onert] Remove rua library
  tests/libs/rua/CMakeLists.txt
  tests/libs/rua/README.md
  tests/libs/rua/anchor/CMakeLists.txt
  tests/libs/rua/anchor/include/rua/Anchor.h
  tests/libs/rua/anchor/src/Anchor.cpp
  tests/libs/rua/core/CMakeLists.txt
  tests/libs/rua/core/include/rua/Service.h
  tests/libs/rua/dyn/CMakeLists.txt
  tests/libs/rua/dyn/include/rua/DynamicBinder.h
  tests/libs/rua/dyn/src/DynamicBinder.cpp
  tests/libs/rua/shim/CMakeLists.txt
  tests/libs/rua/shim/include/rua/Shim.h
Labels: PR/ready for review

#13833 [debian] Update changelog
  infra/debian/compiler/changelog
Labels: PR/ready for review, type/release

#13832 Release note 1.29.0
  docs/release/1.29/index.rst
  docs/release/1.29/release-note_1.29.0.md
Labels: PR/ready for review, type/release

#13836 [tflchef] Add const reference
  compiler/tflchef/core/src/ModelChef.cpp
Labels: PR/ready for review

#13834 [onert] Simplify IPermuteFunction unittest
  runtime/onert/core/src/exec/IPermuteFunction.test.cc
Labels: PR/ready for review

#13841 [vconone] Bump up to 1.30.0
  compiler/vconone/CMakeLists.txt
Labels: PR/ready for review

#13837 [onert] Update circle schema generated header for block quantization
  runtime/libs/circle-schema/include/circle_schema_generated.h
Labels: PR/ready for review

#13839 [onert] Remove layout in ITensor
  runtime/onert/backend/acl_common/IACLTensor.cc
  runtime/onert/backend/acl_common/IACLTensor.h
  runtime/onert/backend/cpu/KernelGenerator.cc
  runtime/onert/backend/cpu/ops/OperationUtils.cc
  runtime/onert/backend/cpu/ops/OperationUtils.h
  runtime/onert/backend/ruy/KernelGenerator.cc
  runtime/onert/backend/ruy/ops/OperationUtils.h
  runtime/onert/backend/train/KernelGenerator.cc
  runtime/onert/backend/train/ops/OperationUtils.cc
  runtime/onert/backend/train/ops/PoolLayer.cc
  runtime/onert/backend/train/optimizer/Optimizers.test.cc
  runtime/onert/backend/trix/Convert.h
  runtime/onert/backend/xnnpack/KernelGenerator.cc
  runtime/onert/backend/xnnpack/ops/ConvolutionLayer.cc
  runtime/onert/backend/xnnpack/ops/DepthwiseConvolutionLayer.cc
  runtime/onert/backend/xnnpack/ops/FullyConnectedLayer.cc
  runtime/onert/core/include/backend/ITensor.h
  runtime/onert/core/include/backend/basic/Tensor.h
  runtime/onert/core/include/backend/basic/train/TrainableTensor.h
  runtime/onert/core/src/backend/builtin/IOTensor.cc
  runtime/onert/core/src/backend/builtin/IOTensor.h
  runtime/onert/core/src/backend/builtin/UserTensor.h
  runtime/onert/core/src/backend/builtin/kernel/PermuteLayer.cc
  runtime/onert/core/src/exec/EdgeTensor.h
  runtime/onert/core/src/exec/IPermuteFunction.cc
  runtime/onert/core/src/exec/IPermuteFunction.h
  runtime/onert/core/src/exec/IPermuteFunction.test.cc
  runtime/onert/core/src/exec/feature/MockTensor.test.h
  runtime/onert/core/src/exec/feature/nchw/Reader.h
  runtime/onert/core/src/exec/feature/nhwc/Reader.h
Labels: PR/ready for review

#13780 [luci/service] Infer dynamic shape for pad
  compiler/luci/service/include/luci/Service/CircleShapeInference.h
  compiler/luci/service/src/CircleShapeInferenceRule.cpp
  compiler/luci/service/src/HelperPads.h
  compiler/luci/service/src/Nodes/CirclePad.cpp
  compiler/luci/service/src/Nodes/CirclePad.test.cpp
Labels: PR/ready for review, SSAFY

#13811 [onert] Introduce CheckpointLoader to load checkpoint file
  runtime/onert/api/nnfw/src/nnfw_api_internal.cc
  runtime/onert/core/include/loader/train/CheckpointLoader.h
  runtime/onert/core/src/loader/train/CheckpointLoader.cc
Labels: PR/ready for review

#13854 [onert] Remove unused header include in Embedder
  runtime/onert/odc/Embedder.cc
Labels: PR/ready for review, approval: 1

#13845 [onert] Rename ExtraTensor to LayerScopeTensor
  runtime/onert/backend/train/LayerScopeTensorIndex.h
  runtime/onert/core/include/backend/train/LayerScopeTensor.h
Labels: PR/ready for review

#13853 [infra/onert] Copy included headers to overlay
  Makefile.template
  packaging/nnfw.spec
Labels: PR/ready for review
