Repository Samsung/ONE, pull requests merged in 2025-04, with the labels that each got.

#14960 [infra] Add path filter for docker build test
  .github/workflows/build-dev-docker.yml
Labels: PR/ready for review

#15015 [onert/test] Add BatchMatMul OP test
  runtime/tests/nnfw_api/lib/CircleGen.cc
  runtime/tests/nnfw_api/lib/CircleGen.h
  runtime/tests/nnfw_api/src/GenModelTests/one_op_tests/BatchMatMul.test.cc
Labels: PR/ready for review

#15033 [onert] Support constant input BatchMatMul
  runtime/compute/cker/include/cker/operation/BatchMatMul.h
  runtime/compute/cker/include/cker/operation/Einsum.h
  runtime/onert/backend/cpu/ops/BatchMatMulLayer.cc
  runtime/onert/core/src/ir/OperationValidator.cc
  runtime/tests/nnfw_api/src/GenModelTests/one_op_tests/BatchMatMul.test.cc
Labels: PR/ready for review

#15101 [cker] Fix `array-bounds` build error: Refactor Shape.h to use C++17 std::variant
  runtime/compute/cker/include/cker/Shape.h
  runtime/compute/cker/include/cker/operation/Einsum.h
Labels: PR/ready for review, Urgent

#15155 [compute] Explicitly initialize dims_ in constructors to avoid uninitialized warnings
  runtime/compute/cker/include/cker/Shape.h
Labels: PR/ready for review, Urgent

#15161 [compute/cker] Fix einsum test error
  runtime/compute/cker/include/cker/Shape.h
Labels: PR/ready for review

#15082 [circle-resizer] Add Shape parser
  compiler/circle-resizer/CMakeLists.txt
  compiler/circle-resizer/include/Dim.h
  compiler/circle-resizer/include/Shape.h
  compiler/circle-resizer/include/ShapeParser.h
  compiler/circle-resizer/src/CMakeLists.txt
  compiler/circle-resizer/src/Dim.cpp
  compiler/circle-resizer/src/Shape.cpp
  compiler/circle-resizer/src/ShapeParser.cpp
  compiler/circle-resizer/tests/CMakeLists.txt
  compiler/circle-resizer/tests/Shape.test.cpp
  compiler/circle-resizer/tests/ShapeParser.test.cpp
Labels: PR/NO MERGE

#15183 [onert/python] Add typing annotations across training API modules
  runtime/onert/api/python/package/experimental/train/losses/cce.py
  runtime/onert/api/python/package/experimental/train/losses/loss.py
  runtime/onert/api/python/package/experimental/train/losses/mse.py
  runtime/onert/api/python/package/experimental/train/losses/registry.py
  runtime/onert/api/python/package/experimental/train/metrics/categorical_accuracy.py
  runtime/onert/api/python/package/experimental/train/metrics/metric.py
  runtime/onert/api/python/package/experimental/train/metrics/registry.py
  runtime/onert/api/python/package/experimental/train/optimizer/adam.py
  runtime/onert/api/python/package/experimental/train/optimizer/optimizer.py
  runtime/onert/api/python/package/experimental/train/optimizer/registry.py
  runtime/onert/api/python/package/experimental/train/optimizer/sgd.py
  runtime/onert/api/python/package/experimental/train/session.py
Labels: PR/ready for review

#15178 [onert] Remove Einsum support
  runtime/compute/cker/include/cker/operation/Einsum.h
  runtime/compute/cker/include/cker/operation/FusedBatchNorm.h
  runtime/compute/cker/include/cker/operation/Helper/BCast.h
  runtime/compute/cker/include/cker/operation/Helper/MatmulBCast.h
  runtime/onert/backend/cpu/KernelGenerator.cc
  runtime/onert/backend/cpu/KernelGenerator.h
  runtime/onert/backend/cpu/ops/EinsumLayer.cc
  runtime/onert/backend/cpu/ops/EinsumLayer.h
  runtime/onert/core/include/ir/Operations.Include.h
  runtime/onert/core/include/ir/Operations.lst
  runtime/onert/core/include/ir/operation/Einsum.h
  runtime/onert/core/src/ir/operation/Einsum.cc
  runtime/onert/core/src/ir/train/operation/UntrainableOperation.test.cc
  runtime/onert/core/src/loader/BaseLoader.h
  runtime/tests/nnapi/CMakeLists.txt
  runtime/tests/nnapi/bridge/include/NeuralNetworksEx.h
  runtime/tests/nnapi/bridge/wrapper/OperationFactory.cc
  runtime/tests/nnapi/nnapi_gtest.skip.aarch64-android.acl_cl
  runtime/tests/nnapi/nnapi_gtest.skip.aarch64-android.acl_neon
  runtime/tests/nnapi/nnapi_gtest.skip.aarch64-linux.acl_cl
  runtime/tests/nnapi/nnapi_gtest.skip.aarch64-linux.acl_neon
  runtime/tests/nnapi/nnapi_gtest.skip.armv7l-linux.acl_cl
  runtime/tests/nnapi/nnapi_gtest.skip.armv7l-linux.acl_neon
  runtime/tests/nnapi/specs/Ex/einsum_ex_float.mod.py
Labels: PR/ready for review

#15184 [onert/python] Support static shape modification across inference API
  runtime/onert/api/python/package/common/basesession.py
  runtime/onert/api/python/package/infer/session.py
  runtime/onert/sample/minimal-python/src/minimal.py
  runtime/onert/sample/minimal-python/src/static_shape_inference.py
Labels: PR/ready for review

#15197 [onert] Remove BradcastTo custom OP
  runtime/onert/core/src/loader/BaseLoader.h
  runtime/tests/nnapi/bridge/wrapper/OperationFactory.cc
  runtime/tests/nnapi/nnapi_gtest.skip.armv7l-linux.acl_cl
  runtime/tests/nnapi/nnapi_gtest.skip.armv7l-linux.acl_neon
  runtime/tests/nnapi/specs/Ex/broadcast_to_ex_1D_nnfw.mod.py
  runtime/tests/nnapi/specs/Ex/broadcast_to_ex_2D_nnfw.mod.py
  runtime/tests/nnapi/specs/Ex/broadcast_to_ex_dynamic_2D_nnfw.mod.py
  runtime/tests/nnapi/specs/Ex/broadcast_to_ex_dynamic_3D_nnfw.mod.py
Labels: PR/ready for review

#15193 [circle-mlir/infra] Downgrade a few packages
  circle-mlir/infra/overlay/prepare-venv
Labels: PR/ready for review

#15203 [circle-mlir/infra] Fix the value test failure in U20.04
  circle-mlir/infra/overlay/prepare-venv
Labels: PR/ready for review

#15204 [circle-mlir/infra] Revise the package versions in Dockerfile
  circle-mlir/infra/docker/u2004/Dockerfile
  circle-mlir/infra/docker/u2204/Dockerfile
Labels: PR/ready for review

#15192 [onert/python] Support infernece benchmark
  runtime/onert/api/python/package/common/basesession.py
  runtime/onert/api/python/package/infer/session.py
  runtime/onert/sample/minimal-python/src/inference_benchmark.py
Labels: PR/ready for review

#15210 [circle-mlir/infra] Revise the Dockerfile for Ubuntu-20.04
  circle-mlir/infra/docker/u2004/Dockerfile
Labels: PR/ready for review

#15198 [onert/python] Introduce `eval_step`
  runtime/onert/api/python/package/experimental/train/session.py
Labels: PR/ready for review, area/onert

#15252 [onert] Remove AddV2 custom OP
  runtime/onert/core/src/loader/BaseLoader.h
  runtime/tests/nnapi/bridge/include/NeuralNetworksEx.h
  runtime/tests/nnapi/bridge/wrapper/OperationFactory.cc
  runtime/tests/nnapi/specs/Ex/add_v2_ex.mod.py
Labels: PR/ready for review

#15247 [infra] Move cmake config for runtime only
  infra/nnfw/cmake/packages/ARMComputeConfig.cmake
  infra/nnfw/cmake/packages/ARMComputeSourceConfig.cmake
  infra/nnfw/cmake/packages/AbseilConfig.cmake
  infra/nnfw/cmake/packages/AbseilSourceConfig.cmake
  infra/nnfw/cmake/packages/CpuInfoConfig.cmake
  infra/nnfw/cmake/packages/CpuInfoSourceConfig.cmake
  infra/nnfw/cmake/packages/Egl_HeadersSourceConfig.cmake
  infra/nnfw/cmake/packages/Farmhash/CMakeLists.txt
  infra/nnfw/cmake/packages/FarmhashConfig.cmake
  infra/nnfw/cmake/packages/FarmhashSourceConfig.cmake
  infra/nnfw/cmake/packages/Fp16Config.cmake
  infra/nnfw/cmake/packages/FxdivConfig.cmake
  infra/nnfw/cmake/packages/FxdivSourceConfig.cmake
  infra/nnfw/cmake/packages/MLDtypesSourceConfig.cmake
  infra/nnfw/cmake/packages/Nonius/html_report_template.g.h++
  infra/nnfw/cmake/packages/NoniusConfig.cmake
  infra/nnfw/cmake/packages/NoniusSourceConfig.cmake
  infra/nnfw/cmake/packages/OouraFFTConfig.cmake
  infra/nnfw/cmake/packages/OouraFFTSourceConfig.cmake
  infra/nnfw/cmake/packages/Opencl_HeadersConfig.cmake
  infra/nnfw/cmake/packages/Opencl_HeadersSourceConfig.cmake
  infra/nnfw/cmake/packages/Opengl_HeadersSourceConfig.cmake
  infra/nnfw/cmake/packages/PsimdConfig.cmake
  infra/nnfw/cmake/packages/PsimdSourceConfig.cmake
  infra/nnfw/cmake/packages/PthreadpoolConfig.cmake
  infra/nnfw/cmake/packages/PthreadpoolSourceConfig.cmake
  infra/nnfw/cmake/packages/TensorFlowGpuConfig.cmake
  infra/nnfw/cmake/packages/TensorFlowLite-2.16.1/TensorFlowLiteConfig.cmake
  infra/nnfw/cmake/packages/VulkanSourceConfig.cmake
  infra/nnfw/cmake/packages/XnnpackConfig.cmake
  infra/nnfw/cmake/packages/XnnpackSource.patch
  infra/nnfw/cmake/packages/XnnpackSourceConfig.cmake
  runtime/contrib/uben/CMakeLists.txt
  runtime/tests/nnfw_api/CMakeLists.txt
Labels: PR/ready for review

#15262 [onert] Remove ReduceAll custom OP
  runtime/onert/core/src/loader/BaseLoader.h
Labels: PR/ready for review

#15205 [onert/python] Support dynamic shapes(on-the-fly)
  runtime/onert/api/python/package/infer/session.py
  runtime/onert/sample/minimal-python/src/dynamic_shape_inference.py
  runtime/onert/sample/minimal-python/src/static_shape_inference.py
Labels: PR/ready for review
